Repository microsoft/azurelinux, pull requests merged in 2020-11, with the labels that each got.

#307 [dev] Handle binary requires as dynamic dependencies
  toolkit/tools/internal/pkggraph/pkggraph.go
  toolkit/tools/internal/rpm/rpm.go
  toolkit/tools/scheduler/schedulerutils/implicitprovides.go
Labels: Tools

#277 Patch CVE-2020-25637
  SPECS/libvirt/CVE-2020-25637.patch
  SPECS/libvirt/libvirt.spec
Labels: Packaging

#328 [dev] Support cycles that only contain run nodes
  toolkit/tools/grapher/grapher.go
Labels: Tools

#300 Adding the `dpdk` package.
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/dpdk/app-pie.patch
  SPECS/dpdk/dpdk-rte-ether-align.patch
  SPECS/dpdk/dpdk.signatures.json
  SPECS/dpdk/dpdk.spec
  SPECS/dpdk/fcf-protection.patch
  cgmanifest.json
Labels: Packaging

#329 [dev] Explicitly specify rpms to install for build dependencies
  toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
  toolkit/tools/internal/packagerepo/repocloner/repocloner.go
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
  toolkit/tools/internal/pkggraph/pkggraph.go
  toolkit/tools/internal/pkgjson/pkgjson.go
  toolkit/tools/pkgworker/pkgworker.go
  toolkit/tools/scheduler/buildagents/chrootagent.go
  toolkit/tools/scheduler/buildagents/definition.go
  toolkit/tools/scheduler/buildagents/testagent.go
  toolkit/tools/scheduler/schedulerutils/buildworker.go
  toolkit/tools/scheduler/schedulerutils/preparerequest.go
Labels: Tools

#331 [dev] Resolve header file conflict between `libevent-devel` and `libev-devel`
  SPECS/libev/libev.spec
Labels: Packaging

#334 [dev] Add additional provides to dbus and audit
  SPECS/audit/audit.spec
  SPECS/dbus/dbus.spec
Labels: Packaging

#335 [dev] Reduce log noise and give more helpful errors
  toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
  toolkit/tools/internal/shell/shell.go
  toolkit/tools/scheduler/scheduler.go
  toolkit/tools/scheduler/schedulerutils/printresults.go
Labels: Tools

#248 Patch systemd CVEs: 2019-3842, 2019-3843, 2019-3844, 2019-6454, 2019-20386, 2020-1712, 2020-13776
  SPECS/systemd/CVE-2019-20386.patch
  SPECS/systemd/CVE-2019-3842.patch
  SPECS/systemd/CVE-2019-3843.patch
  SPECS/systemd/CVE-2019-3844.patch
  SPECS/systemd/CVE-2019-6454.patch
  SPECS/systemd/CVE-2020-13776.patch
  SPECS/systemd/CVE-2020-1712.patch
  SPECS/systemd/systemd-bootstrap.spec
  SPECS/systemd/systemd.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#267 Patch CVE-2019-12749 in dbus
  SPECS/dbus/CVE-2019-12749.patch
  SPECS/dbus/dbus.spec
Labels: Packaging

#268 Patch CVE-2020-25613 in ruby
  SPECS/ruby/CVE-2020-25613.patch
  SPECS/ruby/ruby.spec
Labels: Packaging

#339 [dev] Restore preview repo support after merge
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
Labels: Tools

#319 Fixing CVE-2020-15705 in `grub2`.
  SPECS-SIGNED/grub2-efi-binary-signed-aarch64/grub2-efi-binary-signed-aarch64.spec
  SPECS-SIGNED/grub2-efi-binary-signed-x64/grub2-efi-binary-signed-x64.spec
  SPECS/grub2/CVE-2020-15705.patch
  SPECS/grub2/grub2.spec
Labels: Packaging

#315 OpenSSH: No patch CVE-2007-2768
  SPECS/openssh/CVE-2007-2768.nopatch
  SPECS/openssh/openssh.spec
Labels: Packaging

#269 Nopatch CVE-2019-1010180 in gdb
  SPECS/gdb/CVE-2019-1010180.nopatch
  SPECS/gdb/gdb.spec
Labels: Packaging

#287 Nopatch for trousers CVE-2020-24332
  SPECS/trousers/CVE-2020-24331.nopatch
  SPECS/trousers/CVE-2020-24332.nopatch
  SPECS/trousers/trousers.spec
Labels: Packaging

#344 [dev] Build without dpdk tools
  SPECS/dpdk/dpdk.spec
Labels: Packaging

#280 Include all sources in bond regardless of arch
  SPECS/bond/bond.signatures.json
  SPECS/bond/bond.spec
Labels: Packaging

#323 Patch CVE-2020-8927 in brotli
  SPECS/brotli/CVE-2020-8927.patch
  SPECS/brotli/brotli.spec
Labels: Packaging

#326 Patch CVE-2020-24553 in go
  SPECS/golang/CVE-2020-24553.patch
  SPECS/golang/golang-1.13.spec
Labels: Packaging

#345 [dev] Print unresolved dependencies in build summary
  toolkit/tools/scheduler/schedulerutils/printresults.go
Labels: Tools

#347 [dev] Update url for raw toolchain man-pages
  toolkit/scripts/toolchain/container/toolchain-remote-wget-list
Labels: Tools

#324 Patch CVE-2018-19665 in qemu
  SPECS/qemu-kvm/CVE-2015-7504.nopatch
  SPECS/qemu-kvm/CVE-2016-7161.nopatch
  SPECS/qemu-kvm/CVE-2017-14167.nopatch
  SPECS/qemu-kvm/CVE-2017-5931.nopatch
  SPECS/qemu-kvm/CVE-2018-19665.patch
  SPECS/qemu-kvm/qemu-kvm.spec
Labels: Packaging

#349 Update url for raw toolchain man-pages
  toolkit/scripts/toolchain/container/toolchain-remote-wget-list
Labels: Tools

#266 Nopatch CVE-2019-18276 in bash
  SPECS/bash/CVE-2019-18276.nopatch
  SPECS/bash/bash.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#350 Remove RPM path macros from local package build contexts in golang
  SPECS/golang/golang-1.13.spec
Labels: Packaging

#337 Nopatching CVE-2020-14145.
  SPECS/openssh/CVE-2020-14145.nopatch
  SPECS/openssh/openssh.spec
Labels: Packaging

#351 Replacing deprecated flags with `imagepkgfetcher_extra_flags`.
  toolkit/scripts/imggen.mk
Labels: Tools

#354 [dev] Allow unpackaged files in dpdk
  SPECS/dpdk/dpdk.spec
Labels: Packaging

#353 No patch for mySQL and CVE-2012-5627
  SPECS/mysql/CVE-2012-5627.nopatch
  SPECS/mysql/mysql.spec
Labels: Packaging

#352 Replacing deprecated flags with `imagepkgfetcher_extra_flags`.
  toolkit/scripts/imggen.mk
Labels: Tools

#346 [dev] Include all sources in bond regardless of arch
  SPECS/bond/bond.signatures.json
  SPECS/bond/bond.spec
Labels: Packaging

#356 Fix word wrapping in qemu-kvm CVE-2018-19665 patch
  SPECS/qemu-kvm/CVE-2018-19665.patch
Labels: Packaging, security

#357 [dev] Update systemd-units provide
  SPECS/systemd/systemd.spec
Labels: Packaging

#362 Creating packages summary for correct repo for Docker builds.
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
Labels: Tools

#340 ExecuteLiveWithCallback can dump output on error.
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/internal/logger/log.go
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
  toolkit/tools/internal/shell/shell.go
  toolkit/tools/liveinstaller/liveinstaller.go
  toolkit/tools/roast/formats/ova.go
Labels: Tools

#363 Skipping one `zsh` ptest testcase if ran as superuser.
  SPECS/zsh/0001-Skipping-test-if-ran-as-superuser.patch
  SPECS/zsh/zsh.spec
Labels: Packaging

#366 Enable arm64 hyperv and SoCs support for CBL-Mariner
  SPECS-SIGNED/kernel-signed-aarch64/kernel-signed-aarch64.spec
  SPECS-SIGNED/kernel-signed-x64/kernel-signed-x64.spec
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  SPECS/kernel/ver5_4_72_arm64_hyperv_support.patch
Labels: Packaging

#368 Patch CVE-2020-14352 in librepo
  SPECS/librepo/CVE-2020-14352.patch
  SPECS/librepo/librepo.spec
Labels: Packaging

#371 Fix qemu-kvm CVEs (CVE-2020-13361, CVE-2020-11869, CVE-2020-14415, CVE-2020-15859, CVE-2020-13362, CVE-2020-25742, CVE-2020-25743, CVE-2020-15469, CVE-2020-24352)
  SPECS/qemu-kvm/CVE-2020-11869.patch
  SPECS/qemu-kvm/CVE-2020-13361.patch
  SPECS/qemu-kvm/CVE-2020-13362.patch
  SPECS/qemu-kvm/CVE-2020-14415.patch
  SPECS/qemu-kvm/CVE-2020-15469.patch
  SPECS/qemu-kvm/CVE-2020-15859.patch
  SPECS/qemu-kvm/CVE-2020-24352.patch
  SPECS/qemu-kvm/CVE-2020-25742.patch
  SPECS/qemu-kvm/CVE-2020-25743.patch
  SPECS/qemu-kvm/qemu-kvm.spec
Labels: Packaging

#369 Add missing requires to auoms package
  SPECS/auoms/auoms.spec
Labels: Packaging

#378 Repetition removal suggestions.
  toolkit/tools/isomaker/maker.go
Labels: Tools

#380 Enabling network access for package builds running with `%check`.
  toolkit/tools/pkgworker/pkgworker.go
Labels: Tools

#379 [dev] Guard scheduler's graph to prevent concurrent reads and writes
  toolkit/tools/scheduler/scheduler.go
  toolkit/tools/scheduler/schedulerutils/buildworker.go
  toolkit/tools/scheduler/schedulerutils/depsolver.go
  toolkit/tools/scheduler/schedulerutils/preparerequest.go
  toolkit/tools/scheduler/schedulerutils/printresults.go
Labels: Tools

#375 [dev] Install cracklib in toolchain before building pam
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
Labels: Tools

#385 [dev] Fix minor toolkit typos
  toolkit/tools/graphanalytics/graphanalytics.go
  toolkit/tools/imager/imager.go
  toolkit/tools/internal/buildpipeline/buildpipeline.go
  toolkit/tools/internal/network/network.go
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
  toolkit/tools/internal/pkgjson/pkgjson.go
  toolkit/tools/internal/rpm/rpm.go
  toolkit/tools/internal/safechroot/safechroot.go
  toolkit/tools/isomaker/isomaker.go
  toolkit/tools/isomaker/maker.go
  toolkit/tools/pkgworker/pkgworker.go
  toolkit/tools/scheduler/buildagents/definition.go
  toolkit/tools/scheduler/scheduler.go
  toolkit/tools/scheduler/schedulerutils/depsolver.go
  toolkit/tools/scheduler/schedulerutils/graphbuildstate.go
  toolkit/tools/scheduler/schedulerutils/implicitprovides.go
  toolkit/tools/scheduler/schedulerutils/preparerequest.go
  toolkit/tools/specreader/specreader.go
  toolkit/tools/srpmpacker/srpmpacker.go
Labels: Tools

#383 Patch CVE-2020-8037 in tcpdump
  SPECS/tcpdump/CVE-2020-8037.patch
  SPECS/tcpdump/tcpdump.spec
Labels: Packaging

#389 Installing `ca-certificates` package for ptest builds.
  toolkit/tools/pkgworker/pkgworker.go
Labels: Tools

#390 Change name of CVE-2019-16275 patch
  SPECS/wpa_supplicant/CVE-2019-16275.patch
  SPECS/wpa_supplicant/wpa_supplicant.spec
Labels: Packaging

#391 Nopatch QEMU CVE-2020-12829
  SPECS/qemu-kvm/CVE-2020-12829.nopatch
  SPECS/qemu-kvm/qemu-kvm.spec
Labels: Packaging

#394 nopatch nginx CVE-2009-4487
  SPECS/nginx/CVE-2009-4487.nopatch
  SPECS/nginx/nginx.spec
Labels: Packaging

#393 CVE-2020-15778 - no patch
  SPECS/openssh/CVE-2020-15778.nopatch
  SPECS/openssh/openssh.spec
Labels: Packaging

#397 [dev] Fix ant to run without extra setup
  SPECS/ant/ant.spec
Labels: Packaging

#396 cherry-pick: Install cracklib before building pam
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
Labels: Tools

#398 Fix ant to run without extra setup
  SPECS/ant/ant.spec
Labels: Packaging

#387 Disable kernel config SLUB_DEBUG_ON due to tcp throughput perf impact
  SPECS-SIGNED/kernel-signed-aarch64/kernel-signed-aarch64.spec
  SPECS-SIGNED/kernel-signed-x64/kernel-signed-x64.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
Labels: Packaging

#382 diskutils: Add MBR disk setup
  toolkit/tools/imagegen/configuration/partitiontabletype.go
  toolkit/tools/imagegen/configuration/partitiontabletype_test.go
  toolkit/tools/imagegen/diskutils/diskutils.go
Labels: Tools

#401 [dev] Improve graphpkgfetcher logging
  toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
Labels: Tools

#400 Don't warn about StreamOutput log buffer overflow
  toolkit/tools/internal/logger/log.go
Labels: Tools

#402 Fixing `subversion` ptests.
  SPECS/subversion/subversion.spec
Labels: Packaging

#365 Enable package test for openssl package
  SPECS/openssl/openssl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#405 Fix check tests for json-c, libmodulemd, libpwquality
  SPECS/json-c/json-c.spec
  SPECS/libmodulemd/libmodulemd.spec
  SPECS/libpwquality/libpwquality.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#399 Fix qemu CVE-2018-12617
  SPECS/qemu-kvm/CVE-2018-12617.patch
  SPECS/qemu-kvm/qemu-kvm.spec
Labels: Packaging

#409 increment release number for CBL-Mariner November release
  SPECS/mariner-release/mariner-release.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#411 Generalizing and simplifying TDNF output regex for reading RPM repo contents.
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
Labels: Tools
