Repository microsoft/azurelinux, pull requests merged in 2020-10, with the labels that each got.

#166 Remove chrony-wait as a boot service dependency
  SPECS/chrony/chrony.spec
  cgmanifest.json
Labels: Packaging

#170 initramfs: Regenerate initrd using host-only mode on file-based trigger
  SPECS/initramfs/initramfs.spec
Labels: Packaging

#164 Fix kernel specs' %postun scripts
  SPECS-SIGNED/kernel-signed-aarch64/kernel-signed-aarch64.spec
  SPECS-SIGNED/kernel-signed-x64/kernel-signed-x64.spec
  SPECS/kernel-hyperv/kernel-hyperv.spec
  SPECS/kernel/kernel.spec
Labels: Packaging

#171 Fix kernel aarch64 package build break due to missing CONFIG_IMA_KEXEC
  SPECS-SIGNED/kernel-signed-aarch64/kernel-signed-aarch64.spec
  SPECS-SIGNED/kernel-signed-x64/kernel-signed-x64.spec
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
Labels: Packaging

#167 Replace mariner-repos's %post scriptlet as %posttrans
  SPECS/mariner-repos/mariner-repos.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#173 Extending 'strongswan' test timeout.
  SPECS/strongswan/0001-Extending-timeout-for-test-cases-with-multiple-read-.patch
  SPECS/strongswan/strongswan.spec
Labels: Packaging

#140 Enable debug symbols for swupdate
  SPECS/swupdate/.config
  SPECS/swupdate/swupdate.signatures.json
  SPECS/swupdate/swupdate.spec
Labels: Packaging

#147 installutils: Supply blank /etc/machine-id file
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/internal/file/file.go
Labels: Tools

#161 installutils: Remove root password expiry when no root user is specified in imageconfig file
  toolkit/tools/imagegen/installutils/installutils.go
Labels: Tools

#176 Nopatching `httpd` CVE-2007-0086.
  SPECS/httpd/CVE-2007-0086.nopatch
  SPECS/httpd/httpd.spec
Labels: Packaging

#141 Improve spec file compatibility [1/2]
  toolkit/Makefile
  toolkit/docs/building/building.md
  toolkit/docs/how_it_works/1_initial_prep.md
  toolkit/docs/how_it_works/2_local_packages.md
  toolkit/docs/how_it_works/3_package_building.md
  toolkit/docs/how_it_works/5_misc.md
  toolkit/scripts/pkggen.mk
  toolkit/scripts/srpm_pack.mk
  toolkit/scripts/toolchain.mk
  toolkit/scripts/toolchain/check_manifests.sh
  toolkit/scripts/toolchain/list_toolchain_specs.sh
  toolkit/scripts/tools.mk
  toolkit/tools/graphanalytics/graphanalytics.go
  toolkit/tools/grapher/grapher.go
  toolkit/tools/graphoptimizer/graphoptimizer.go
  toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
  toolkit/tools/internal/directory/directory.go
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
  toolkit/tools/internal/pkggraph/pkggraph.go
  toolkit/tools/internal/pkggraph/pkggraph_test.go
  toolkit/tools/internal/pkggraph/test_graph_reference.dot
  toolkit/tools/internal/pkgjson/pkgjson.go
  toolkit/tools/internal/rpm/rpm.go
  toolkit/tools/internal/safechroot/safechroot.go
  toolkit/tools/internal/shell/shell.go
  toolkit/tools/pkgworker/pkgworker.go
  toolkit/tools/scheduler/buildagents/chrootagent.go
  toolkit/tools/scheduler/buildagents/definition.go
  toolkit/tools/scheduler/buildagents/testagent.go
  toolkit/tools/scheduler/scheduler.go
  toolkit/tools/scheduler/schedulerutils/buildlist.go
  toolkit/tools/scheduler/schedulerutils/buildworker.go
  toolkit/tools/scheduler/schedulerutils/depsolver.go
  toolkit/tools/scheduler/schedulerutils/graphbuildstate.go
  toolkit/tools/scheduler/schedulerutils/implicitprovides.go
  toolkit/tools/scheduler/schedulerutils/initializegraph.go
  toolkit/tools/scheduler/schedulerutils/prebuilt.go
  toolkit/tools/scheduler/schedulerutils/preparerequest.go
  toolkit/tools/scheduler/schedulerutils/printresults.go
  toolkit/tools/specreader/specreader.go
  toolkit/tools/srpmpacker/srpmpacker.go
  toolkit/tools/unravel/formats/definition.go
  toolkit/tools/unravel/formats/linear.go
  toolkit/tools/unravel/formats/makefile.go
  toolkit/tools/unravel/unravel.go
Labels: Tools, enhancement

#138 Replace the misuse of `archdir` shell variable
  SPECS/kernel/kernel.spec
Labels: Packaging

#185 Spec changelog fixes
  SPECS/libarchive/libarchive.spec
  SPECS/libassuan/libassuan.spec
  SPECS/pkgconf/pkgconf.spec
Labels: Packaging

#192 Fix missing macro in secilc
  SPECS/secilc/secilc.spec
Labels: Packaging

#189 Removing documentation for deprecated 'TERMINAL_ISO_INSTALLER' argument.
  toolkit/docs/building/building.md
Labels: documentation

#165 Patch CVE-2020-14342 in cifs-utils
  SPECS/cifs-utils/CVE-2020-14342-fix.patch
  SPECS/cifs-utils/CVE-2020-14342.patch
  SPECS/cifs-utils/cifs-utils.spec
Labels: Packaging

#182 Add architecture at the end of toolkit archive name
  toolkit/scripts/toolkit.mk
Labels: Tools

#174 Enable valgrind tests for librelp
  SPECS/librelp/librelp.spec
Labels: Packaging

#195 Adding a missing '%{?dist}' tag.
  SPECS/cloud-init-vmware-guestinfo/cloud-init-vmware-guestinfo.spec
Labels: Packaging

#196 [dev] Avoid repacking SRPMs during container builds
  toolkit/tools/srpmpacker/srpmpacker.go
Labels: Tools

#198 enable fetching RPMs from pacakges.microsoft.com for Docker based build
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
Labels: Tools

#202 Fix repolock removal
  toolkit/tools/internal/packagerepo/repomanager/rpmrepomanager/rpmrepomanager.go
Labels: Tools

#201 Fix graph corruption during cycle resolution
  toolkit/tools/grapher/grapher.go
Labels: Tools

#199 Natively support pulling from the preview repo
  toolkit/Makefile
  toolkit/docs/building/building.md
  toolkit/docs/how_it_works/3_package_building.md
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/update_manifests.sh
  toolkit/scripts/imggen.mk
  toolkit/scripts/pkggen.mk
  toolkit/scripts/toolchain.mk
  toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
  toolkit/tools/imagepkgfetcher/imagepkgfetcher.go
  toolkit/tools/internal/packagerepo/repocloner/repocloner.go
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
Labels: Tools

#211 Fix CVE-2020-26159 in oniguruma
  SPECS/oniguruma/CVE-2020-26159.patch
  SPECS/oniguruma/oniguruma.spec
Labels: Packaging

#205 Adding the 'syslog-ng' package.
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/syslog-ng/60-syslog-ng-journald.conf
  SPECS/syslog-ng/syslog-ng.service
  SPECS/syslog-ng/syslog-ng.signatures.json
  SPECS/syslog-ng/syslog-ng.spec
  cgmanifest.json
Labels: Packaging

#206 Adding the 'tinyxml2' package.
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/tinyxml2/tinyxml2.signatures.json
  SPECS/tinyxml2/tinyxml2.spec
  cgmanifest.json
Labels: Packaging

#207 Adding the 'toml11' package.
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/toml11/toml11.signatures.json
  SPECS/toml11/toml11.spec
  cgmanifest.json
Labels: Packaging

#208 Adding the 'tracelogging' and 'zipper' packages.
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/tracelogging/tracelogging.signatures.json
  SPECS/tracelogging/tracelogging.spec
  SPECS/zipper/minizip.tar.gz
  SPECS/zipper/zipper.signatures.json
  SPECS/zipper/zipper.spec
  cgmanifest.json
Labels: Packaging

#212 Remove toolchain-local-wget-list after use
  toolkit/.gitignore
  toolkit/scripts/toolchain/create_toolchain_in_container.sh
Labels: Tools

#219 [dev] Support epochs in spec versions
  toolkit/tools/internal/versioncompare/versioncompare.go
  toolkit/tools/internal/versioncompare/versioncompare_test.go
Labels: Tools

#213 Update libestr
  SPECS/libestr/libestr.spec
Labels: Packaging

#228 Disable debug package for nlohmann-json
  SPECS/nlohmann-json/nlohmann-json.spec
Labels: Packaging

#162 Nopatch qemu CVE-2015-7504, CVE-2017-5931, CVE-2017-14167
  SPECS/qemu-kvm/CVE-2015-7504.nopatch
  SPECS/qemu-kvm/CVE-2016-7161.nopatch
  SPECS/qemu-kvm/CVE-2017-14167.nopatch
  SPECS/qemu-kvm/CVE-2017-5931.nopatch
  SPECS/qemu-kvm/qemu-kvm.spec
Labels: Packaging

#193 Nopatch kernel CVE-2020-10757, CVE-2020-12653, CVE-2020-12657, CVE-2010-3865, CVE-2020-11668, CVE-2020-12654, CVE-2020-24394, CVE-2020-8428
  SPECS-SIGNED/kernel-signed-aarch64/kernel-signed-aarch64.spec
  SPECS-SIGNED/kernel-signed-x64/kernel-signed-x64.spec
  SPECS/kernel/CVE-2010-3865.nopatch
  SPECS/kernel/CVE-2020-10757.nopatch
  SPECS/kernel/CVE-2020-11668.nopatch
  SPECS/kernel/CVE-2020-12653.nopatch
  SPECS/kernel/CVE-2020-12654.nopatch
  SPECS/kernel/CVE-2020-12657.nopatch
  SPECS/kernel/CVE-2020-24394.nopatch
  SPECS/kernel/CVE-2020-8428.nopatch
  SPECS/kernel/kernel.spec
Labels: Packaging

#238 patch openssh for CVE-2019-16905
  SPECS/openssh/CVE-2019-16905.patch
  SPECS/openssh/openssh.spec
Labels: Packaging

#230 Fix CVE-2019-12735 in vim
  SPECS/vim/CVE-2019-12735.patch
  SPECS/vim/vim.spec
Labels: Packaging

#233 Enable QAT kernel configs in CBL-Mariner
  SPECS-SIGNED/kernel-signed-aarch64/kernel-signed-aarch64.spec
  SPECS-SIGNED/kernel-signed-x64/kernel-signed-x64.spec
  SPECS/kernel/config
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
Labels: Packaging

#246 Patch unbound CVE-2020-12662 and CVE-2020-12663
  SPECS/unbound/CVE-2020-12662.patch
  SPECS/unbound/CVE-2020-12663.nopatch
  SPECS/unbound/unbound.spec
Labels: Packaging

#139 Portablectl patches for to support --now --enable and --no-block flags
  SPECS/systemd/100-portabled-allow-to-detach-an-image-with-a-unit-in-li.patch
  SPECS/systemd/101-Portabled-fix-inspect-on-image-attached-as-directory.patch
  SPECS/systemd/102-portablectl-add-now-and-enable-to-attach-detach.patch
  SPECS/systemd/103-core-allow-portablectl-to-load-new-services-without-.patch
  SPECS/systemd/104-portablectl-block-when-stopping-a-unit-on-detach-now.patch
  SPECS/systemd/105-portablectl-use-replace-unload-when-stopping-a-servi.patch
  SPECS/systemd/106-portabled-implement-container-host-os-release-interf.patch
  SPECS/systemd/systemd.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#209 Nopatch ed CVE-2015-2987
  SPECS/ed/CVE-2015-2987.nopatch
  SPECS/ed/ed.spec
Labels: Packaging

#247 Patch gnutls CVE-2020-24659
  SPECS/gnutls/CVE-2020-24659.patch
  SPECS/gnutls/gnutls.spec
Labels: Packaging

#253 Fix Ant CVE-2020-11979
  SPECS/ant/ant.spec
  cgmanifest.json
Labels: Packaging

#254 Nopatch sqlite CVE-2015-3717
  SPECS/sqlite/CVE-2015-3717.nopatch
  SPECS/sqlite/sqlite.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#260 Update ant signatures
  SPECS/ant/ant.signatures.json
Labels: Packaging

#263 Fix auoms setup issue
  SPECS/auoms/auoms.spec
Labels: Packaging

#271 Patch CVE-2018-19876 (Cairo)
  SPECS/cairo/CVE-2018-19876.patch
  SPECS/cairo/cairo.spec
Labels: Packaging

#249 Patch Python2 CVEs: 2019-9674, 2019-20907, 2020-26116
  SPECS/python2/CVE-2007-4559.nopatch
  SPECS/python2/CVE-2017-18207.patch
  SPECS/python2/CVE-2019-18348.nopatch
  SPECS/python2/CVE-2019-20907.patch
  SPECS/python2/CVE-2019-9674.nopatch
  SPECS/python2/CVE-2020-26116.patch
  SPECS/python2/python2.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#261 Fix redis CVE-2020-14147
  SPECS/redis/CVE-2020-14147.patch
  SPECS/redis/redis.spec
Labels: Packaging

#276 Fix openldap CVE-2015-3276
  SPECS/openldap/CVE-2015-3276.patch
  SPECS/openldap/openldap.spec
Labels: Packaging

#274 Patch CVE-2020-8631 and CVE-2020-8632 in cloud-init
  SPECS/cloud-init/CVE-2020-8631.patch
  SPECS/cloud-init/CVE-2020-8632.patch
  SPECS/cloud-init/cloud-init.spec
Labels: Packaging

#297 Prevent AdditionalFiles from being modified during iteration
  toolkit/scripts/imggen.mk
  toolkit/tools/imagegen/configuration/configuration.go
  toolkit/tools/isomaker/maker.go
Labels: Tools

#296 Fix nginx CVE-2019-20372
  SPECS/nginx/CVE-2019-20372.patch
  SPECS/nginx/nginx.spec
Labels: Packaging

#298 Prevent AdditionalFiles from being modified during iteration (#297)
  toolkit/scripts/imggen.mk
  toolkit/tools/imagegen/configuration/configuration.go
  toolkit/tools/isomaker/maker.go
Labels: Tools

#282 Patch CVE-2020-24977 in libxml2
  SPECS/libxml2/CVE-2020-24977.patch
  SPECS/libxml2/libxml2.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#293 Fix Qemu CVE-2020-10702, CVE-2020-10761
  SPECS/qemu-kvm/CVE-2020-10702.patch
  SPECS/qemu-kvm/CVE-2020-10761.patch
  SPECS/qemu-kvm/qemu-kvm.spec
Labels: Packaging

#302 Fix glibc CVE-2019-7309
  SPECS/glibc/CVE-2019-7309.patch
  SPECS/glibc/glibc.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#303 Address source RPM publishing issue on packages.microsoft.com
  SPECS/liblogging/liblogging.spec
Labels: Packaging

#304 Fixing `qemu-kvm` CVE-2020-13253 and CVE-2020-13754.
  SPECS/qemu-kvm/CVE-2020-13253.patch
  SPECS/qemu-kvm/CVE-2020-13754.patch
  SPECS/qemu-kvm/qemu-kvm.spec
Labels: Packaging

#281 Patch CVE-2020-13791 in qemu
  SPECS/qemu-kvm/CVE-2020-13791.patch
  SPECS/qemu-kvm/qemu-kvm.spec
Labels: Packaging

#309 [1.0] Properly update AdditionalFiles in isomaker
  toolkit/tools/isomaker/maker.go
Labels: Tools

#310 [dev] Properly update AdditionalFiles in isomaker
  toolkit/tools/isomaker/maker.go
Labels: Tools

#311 Properly update AdditionalFiles in isomaker
  toolkit/tools/isomaker/maker.go
Labels: Tools

#316 Update pkggen merge
  toolkit/scripts/pkggen.mk
Labels: Tools

#318 Clean up lua.spec 1.0 to dev merge
  SPECS/lua/lua.spec
Labels: Packaging
