Repository microsoft/azurelinux, pull requests merged in 2020-12, with the labels that each got.

#415 Fix kexec() flow in HyperV
  SPECS-SIGNED/kernel-signed-aarch64/kernel-signed-aarch64.spec
  SPECS-SIGNED/kernel-signed-x64/kernel-signed-x64.spec
  SPECS/kernel/0001-Drivers-hv-vmbus-Allow-cleanup-of-VMBUS_CONNECT_CPU-.patch
  SPECS/kernel/kernel.spec
Labels: Packaging

#424 Delete version-check.sh
  toolkit/scripts/toolchain/version-check.sh
Labels: Tools

#408 Unblocking `ruby` test from being run.
  SPECS/ruby/ruby.spec
Labels: Packaging

#406 HyperV IP injection support
  SPECS/hyperv-daemons/hv_set_ifconfig
  SPECS/hyperv-daemons/hyperv-daemons.signatures.json
  SPECS/hyperv-daemons/hyperv-daemons.spec
Labels: Packaging

#430 Unifying toolchain build log file names with package builds.
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
Labels: Tools

#428 Move "waagent" to sbindir in WALinuxAgent
  SPECS/WALinuxAgent/WALinuxAgent.spec
  SPECS/WALinuxAgent/add-distro.patch
Labels: Packaging

#426 kernel: Add tpm eventlog patch for arm
  SPECS-SIGNED/kernel-signed-aarch64/kernel-signed-aarch64.spec
  SPECS-SIGNED/kernel-signed-x64/kernel-signed-x64.spec
  SPECS/kernel/0002-efi-libstub-tpm-enable-tpm-eventlog-function-for-ARM.patch
  SPECS/kernel/kernel.spec
Labels: Packaging

#432 [dev] Skip refetching synonymous provides
  toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
Labels: Tools

#433 Change systemConfig test to copy rather than reference valid users
  toolkit/tools/imagegen/configuration/systemconfig_test.go
Labels: Tools

#435 Adding timestamp to toolchain builds.
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
Labels: Tools

#438 Remove private ADO reference in docs
  toolkit/docs/security/ca-certificates.md
Labels: documentation

#439 Fix check tests for json-glib, libuv, pango
  SPECS/json-glib/json-glib.spec
  SPECS/libuv/libuv.spec
  SPECS/pango/pango.spec
Labels: Packaging

#436 Decreasing logging noise for package test builds.
  toolkit/scripts/pkggen.mk
  toolkit/tools/pkgworker/pkgworker.go
Labels: Tools

#446 Fixing `pkggen.mk` bug.
  toolkit/scripts/pkggen.mk
Labels: Tools

#448 [dev] Ensure the graph is acyclic after injecting implicit provides
  toolkit/tools/grapher/grapher.go
  toolkit/tools/internal/pkggraph/pkggraph.go
  toolkit/tools/scheduler/scheduler.go
  toolkit/tools/scheduler/schedulerutils/implicitprovides.go
Labels: Tools

#447 Patch CVE-2020-25723 in qemu-kvm
  SPECS/qemu-kvm/CVE-2020-25723.patch
  SPECS/qemu-kvm/qemu-kvm.spec
Labels: Packaging

#444 Fix check tests for Cython, libserf, librelp, apr and autoconf213
  SPECS/Cython/Cython.spec
  SPECS/apr/apr.spec
  SPECS/autoconf213/autoconf213.spec
  SPECS/librelp/librelp.spec
  SPECS/libserf/libserf.spec
Labels: Packaging

#452 Fix bad changelog date in autoconf213
  SPECS/autoconf213/autoconf213.spec
Labels: Packaging

#453 Patch openldap CVE-2020-25692
  SPECS/openldap/CVE-2020-25692.patch
  SPECS/openldap/openldap.spec
Labels: Packaging

#456 [dev] Patch maven dependency generator to remove epoch
  SPECS/javapackages-tools/javapackages-tools.spec
  SPECS/javapackages-tools/remove-epoch-from-java-requires.patch
Labels: Packaging

#451 Fixing `rpm-ostree` ptests.
  SPECS/rpm-ostree/rpm-ostree.spec
Labels: Packaging

#460 Increment release for all specs building with golang 1.15
  SPECS/audit/audit.spec
  SPECS/cni/cni.spec
  SPECS/cri-tools/cri-tools.spec
  SPECS/etcd/etcd.spec
  SPECS/go-md2man/go-md2man.spec
  SPECS/gobject-introspection/gobject-introspection.spec
  SPECS/kubernetes/kubernetes-1.16.spec
  SPECS/moby-buildx/moby-buildx.spec
  SPECS/moby-cli/moby-cli.spec
  SPECS/moby-containerd/moby-containerd.spec
  SPECS/moby-engine/moby-engine.spec
  SPECS/moby-runc/moby-runc.spec
  SPECS/runc/runc.spec
  SPECS/telegraf/telegraf.spec
Labels: Packaging

#462 Patch qemu CVE-2020-27821
  SPECS/qemu-kvm/CVE-2020-27821.patch
  SPECS/qemu-kvm/qemu-kvm.spec
Labels: Packaging

#449 Nicogbg/ms kubernetes
  SPECS/kubernetes/kubelet.service
  SPECS/kubernetes/kubernetes-1.16.signatures.json
  SPECS/kubernetes/kubernetes-1.16.spec
  SPECS/kubernetes/kubernetes-1.17.signatures.json
  SPECS/kubernetes/kubernetes-1.17.spec
  SPECS/kubernetes/kubernetes-1.18.signatures.json
  SPECS/kubernetes/kubernetes-1.18.spec
  SPECS/kubernetes/kubernetes-1.19.signatures.json
  SPECS/kubernetes/kubernetes-1.19.spec
  cgmanifest.json
Labels: Packaging

#465 Fix tests for grub2, perl, and skip libsoup tests
  SPECS/grub2/grub2.spec
  SPECS/perl/perl.spec
  toolkit/resources/manifests/package/macros.override
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: ptest

#464 [dev] Optional python2 support in python-sphinx
  SPECS/python-sphinx/python-sphinx.spec
Labels: Packaging

#468 Remove password aging customized value to set default
  SPECS/shadow-utils/shadow-utils.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#471 Fix file paths for prebuilt certificates
  SPECS/ca-certificates/ca-certificates.spec
  SPECS/prebuilt-ca-certificates-base/prebuilt-ca-certificates-base.spec
Labels: Packaging

#466 Update prerequisites with golang 1.15
  toolkit/docs/building/prerequisites.md
Labels: documentation

#475 Fix tests for llvm and libaio
  SPECS/libaio/libaio.spec
  SPECS/llvm/llvm.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, ptest

#474 Fixing misleading doc entry about update repo's defaults.
  toolkit/docs/building/building.md
Labels: documentation

#488 Updating `python-py` to 1.10.0 to fix CVE-2020-29651
  SPECS/python-py/python-py.signatures.json
  SPECS/python-py/python-py.spec
  cgmanifest.json
Labels: Packaging

#487 Adding a patch for 'unbound' to fix CVE-2020-28935
  SPECS/unbound/CVE-2020-28935.patch
  SPECS/unbound/unbound.spec
Labels: Packaging

#490 Fix tests for elfutils and python-imagesize
  SPECS/elfutils/elfutils.spec
  SPECS/python-imagesize/python-imagesize.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, ptest

#495 Updating SIGNED-SPECS to make the releases match their unsigned counterparts.
  SPECS-SIGNED/grub2-efi-binary-signed-aarch64/grub2-efi-binary-signed-aarch64.spec
  SPECS-SIGNED/grub2-efi-binary-signed-x64/grub2-efi-binary-signed-x64.spec
  SPECS-SIGNED/kernel-signed-x64/kernel-signed-x64.spec
Labels: Packaging

#496 Updating signed specs to be aligned with their unsigned counterparts.
  SPECS-SIGNED/grub2-efi-binary-signed-aarch64/grub2-efi-binary-signed-aarch64.spec
  SPECS-SIGNED/grub2-efi-binary-signed-x64/grub2-efi-binary-signed-x64.spec
  SPECS-SIGNED/kernel-signed-x64/kernel-signed-x64.spec
Labels: Packaging

#500 Mamalisz/fix chage shadow
  toolkit/tools/imagegen/installutils/installutils.go
Labels: Tools

#497 Fixing spacing in TDNF's package list output
  SPECS/tdnf/tdnf-add-download-command.patch
  SPECS/tdnf/tdnf-add-showorder-argument.patch
  SPECS/tdnf/tdnf-mandatory-space-list-output.patch
  SPECS/tdnf/tdnf-support-multiple-gpgkeys.patch
  SPECS/tdnf/tdnf.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Tools

#501 Mamalisz/fix chage shadow (#500)
  toolkit/tools/imagegen/installutils/installutils.go
Labels: Tools

#502 Adding Fedora 32 patch to make `perl-WWW-Curl` work with new version of `curl`
  SPECS/perl-WWW-Curl/WWW-Curl-4.17-Adapt-to-changes-in-cURL-7.69.0.patch
  SPECS/perl-WWW-Curl/perl-WWW-Curl.spec
Labels: Packaging
