Repository microsoft/azurelinux, pull requests merged in 2020-09, with the labels that each got.

#101 [Security] libxml2 CVE patches
  SPECS/libxml2/CVE-2019-20388.patch
  SPECS/libxml2/CVE-2020-7595.patch
  SPECS/libxml2/libxml2.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security

#106 [Security] Clean up non-applicable CVEs
  SPECS/gcc/CVE-2019-15847.nopatch
  SPECS/gcc/gcc.spec
  SPECS/glibc/CVE-2018-20796.nopatch
  SPECS/glibc/glibc.spec
  SPECS/python2/CVE-2013-1753.nopatch
  SPECS/python2/CVE-2017-17522.nopatch
  SPECS/python2/python2.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security

#111 fix qemu CVE-2020-15863
  SPECS/qemu-kvm/CVE-2020-15863.patch
  SPECS/qemu-kvm/qemu-kvm.spec
Labels: Packaging

#113 Add SRPM_UPDATE_URL
  toolkit/Makefile
  toolkit/docs/building/building.md
  toolkit/scripts/srpm_pack.mk
Labels: Tools

#117 Use SRPM name as the working directory name to pack in
  toolkit/tools/srpmpacker/srpmpacker.go
Labels: Tools

#118 Pull toolchain RPMs from the correct directory
  toolkit/scripts/tools.mk
Labels: Tools

#123 Adding a small build tip to the quick start instructions
  toolkit/docs/building/building.md
Labels: documentation

#122 Markdown lint-induced clean-up of doc files.
  toolkit/docs/building/building.md
  toolkit/docs/building/prerequisites.md
Labels: documentation

#134 Update tpm2 tools to 4.2, tss to 2.4.0
  SPECS/tpm2-tools/tpm2-tools.signatures.json
  SPECS/tpm2-tools/tpm2-tools.spec
  SPECS/tpm2-tss/tpm2-tss.signatures.json
  SPECS/tpm2-tss/tpm2-tss.spec
  cgmanifest.json
Labels: Packaging

#148 Nopatch httpd CVE-1999-0236, CVE-1999-1412
  SPECS/httpd/CVE-1999-0236.nopatch
  SPECS/httpd/CVE-1999-1412.nopatch
  SPECS/httpd/httpd.spec
  cgmanifest.json
Labels: Packaging

#149 Nopatch groff CVE-2000-0803
  SPECS/groff/CVE-2000-0803.nopatch
  SPECS/groff/groff.spec
Labels: Packaging

#150 Nopatch apparmor CVE-2016-1585
  SPECS/apparmor/CVE-2016-1585.nopatch
  SPECS/apparmor/apparmor.spec
Labels: Packaging

#152 Nopatch qemu CVE-2016-7161
  SPECS/qemu-kvm/CVE-2016-7161.nopatch
  SPECS/qemu-kvm/qemu-kvm.spec
Labels: Packaging

#153 Nopatch lua CVE-2020-15889
  SPECS/lua/CVE-2020-15889.nopatch
  SPECS/lua/lua.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#142 Enable Mellanox kernel configs
  SPECS-SIGNED/kernel-signed-aarch64/kernel-signed-aarch64.spec
  SPECS-SIGNED/kernel-signed-x64/kernel-signed-x64.spec
  SPECS/kernel/config
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
Labels: Packaging
