Repository microsoft/azurelinux, pull requests merged in 2021-03, with the labels that each got.

#675 bind: fix CVE-2020-8625
  SPECS/bind/CVE-2020-8625.patch
  SPECS/bind/bind.spec
Labels: Packaging

#669 Update azure-iotedge to version 1.1.0
  SPECS/azure-iotedge/azure-iotedge.signatures.json
  SPECS/azure-iotedge/azure-iotedge.spec
  SPECS/libiothsm-std/libiothsm-std.signatures.json
  SPECS/libiothsm-std/libiothsm-std.spec
  SPECS/rust/ignore-linker-output-non-utf8-test.patch
  SPECS/rust/robust-build.patch
  SPECS/rust/rust.signatures.json
  SPECS/rust/rust.spec
  cgmanifest.json
Labels: Packaging

#680 [dev] Fix smp_build_cpus macro definition
  SPECS/mariner-rpm-macros/macros
Labels: Packaging

#653 [Tools] Fix parsing of new lsblk JSON output format in diskutils
  toolkit/tools/imagegen/diskutils/diskutils.go
  toolkit/tools/imagegen/diskutils/diskutils_test.go
Labels: Tools

#677 Fix tests for python-distro and python-requests
  SPECS/python-distro/python-distro.signatures.json
  SPECS/python-distro/python-distro.spec
  SPECS/python-requests/python-requests.spec
  SPECS/python-requests/test_requests_support_pytest_4.patch
  SPECS/python-requests/test_requests_typeerror_testfix.patch
  cgmanifest.json
Labels: ptest

#688 [dev] Fix macros signature
  SPECS/mariner-rpm-macros/mariner-rpm-macros.signatures.json
Labels: Packaging

#689 Remove ntopng
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/ntopng/ntopng.signatures.json
  SPECS/ntopng/ntopng.spec
  cgmanifest.json
Labels: Packaging

#693 Fix check tests for apparmor, redis, python-pycurl, skip WALinuxAgent
  SPECS/apparmor/apparmor-update-severity-db.patch
  SPECS/apparmor/apparmor.spec
  SPECS/python-pycurl/python-pycurl.spec
  SPECS/redis/disable_active_defrag_big_keys.patch
  SPECS/redis/redis.spec
  toolkit/resources/manifests/package/macros.override
Labels: ptest

#703 Fix tests for gdb, libxml2, net-snmp, python-werkzeug, skip python-psutil tests
  SPECS/gdb/gdb.spec
  SPECS/libxml2/libxml2.spec
  SPECS/net-snmp/net-snmp.spec
  SPECS/python-werkzeug/python-werkzeug.spec
  toolkit/resources/manifests/package/macros.override
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: ptest

#692 Fix issue with multiple empty mount validation
  toolkit/tools/imagegen/configuration/systemconfig.go
  toolkit/tools/imagegen/configuration/systemconfig_test.go
Labels: Tools

#713 Fix libpng random test failure
  SPECS/libpng/libpng-fix-pngtest-random-failures.patch
  SPECS/libpng/libpng.spec
Labels: Packaging, ptest

#708 Nopatch CVE-2020-8032 in cyrus-sasl
  SPECS/cyrus-sasl/CVE-2020-8032.nopatch
  SPECS/cyrus-sasl/cyrus-sasl.spec
Labels: Packaging

#717 Fix failing test for espeak-ng
  SPECS/espeak-ng/espeak-ng.spec
  SPECS/espeak-ng/tests-fix-greek-letter-variants.patch
  SPECS/espeak-ng/tests-newline-fixes.patch
Labels: Packaging, ptest

#716 diskutils: add clearer error when no disk found
  toolkit/tools/imagegen/diskutils/diskutils.go
Labels: Tools

#705 diskutils: refactor partition detection
  toolkit/tools/imagegen/diskutils/diskutils.go
Labels: Tools

#720 Patch CVE-2021-0326, CVE-2021-27803 in wpa_supplicant
  SPECS/wpa_supplicant/CVE-2021-0326.patch
  SPECS/wpa_supplicant/CVE-2021-27803.patch
  SPECS/wpa_supplicant/wpa_supplicant.spec
Labels: Packaging, security

#721 [dev] Make bash-completion compatible with other distros
  SPECS/bash-completion/bash-completion.spec
Labels: Packaging

#718 Improving toolchain download logs.
  toolkit/scripts/toolchain.mk
Labels: Tools

#724 Fix typo in prerequisites.md
  toolkit/docs/building/prerequisites.md
Labels: documentation

#728 file: add append data to debug output
  toolkit/tools/internal/file/file.go
Labels: Tools

#729 installutils: Remove stale constant
  toolkit/tools/imagegen/installutils/installutils.go
Labels: Tools

#733 Package bash-completion files properly in packages that autodetect directory from pkg-config
  SPECS/dnf/dnf.spec
  SPECS/libstoragemgmt/libstoragemgmt.spec
Labels: Packaging

#719 Adding retries to jdk8 tarballs downloads during toolchain builds
  toolkit/scripts/toolchain/container/toolchain-jdk8-wget.sh
Labels: Tools

#739 Modify SRPMPacker tool to use system cert pool
  toolkit/docs/building/building.md
  toolkit/tools/srpmpacker/srpmpacker.go
Labels: Tools

#744 [dev] Upgrade and modify ruby and rubygem-bundler
  SPECS/ruby/macros.ruby
  SPECS/ruby/macros.rubygems
  SPECS/ruby/operating_system.rb
  SPECS/ruby/ruby-2.1.0-Prevent-duplicated-paths-when-empty-version-string-i.patch
  SPECS/ruby/ruby-2.3.0-ruby_version.patch
  SPECS/ruby/ruby.signatures.json
  SPECS/ruby/ruby.spec
  SPECS/ruby/rubygems.attr
  SPECS/ruby/rubygems.con
  SPECS/ruby/rubygems.prov
  SPECS/ruby/rubygems.req
  SPECS/rubygem-bundler/rubygem-bundler.spec
  cgmanifest.json
Labels: Packaging

#730 diskutils: Add partscan flag to losetup cmd
  toolkit/tools/imagegen/diskutils/diskutils.go
Labels: Tools

#749 installutils: only return grub2-pc on amd64 install
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/imagegen/installutils/installutils_test.go
Labels: Tools

#750 Fix perl-Crypt-SSLeay test
  SPECS/perl-Crypt-SSLeay/Use_TLS_client_method-with-OpenSSL-1.1.1.patch
  SPECS/perl-Crypt-SSLeay/perl-Crypt-SSLeay.spec
Labels: Packaging, ptest

#756 Modify SRPMPacker tool to use system cert pool (dev branch)
  toolkit/docs/building/building.md
  toolkit/tools/srpmpacker/srpmpacker.go
Labels: Tools

#709 [dev] Curb expansion in srpm_expand.mk
  toolkit/scripts/srpm_expand.mk
Labels: Tools

#758 Unifying `coredns` specs for the sake of automation.
  SPECS/coredns/coredns-1.6.5.spec
  SPECS/coredns/coredns-1.6.7.spec
  SPECS/coredns/coredns-1.7.0.spec
Labels: Packaging

#760 [dev] Fix toolchain glib build
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
Labels: Tools

#763 [dev] Update file section of vala main package
  SPECS/vala/vala.spec
Labels: Packaging

#725 diskutils: Add partprobe after partition creation
  .github/workflows/quickstart_1.0.yml
  toolkit/docs/building/prerequisites.md
  toolkit/tools/imagegen/diskutils/diskutils.go
Labels: Tools

#741 Iptables: Add ssh brute force protection rules
  SPECS/iptables/ip4save
  SPECS/iptables/ip6save
  SPECS/iptables/iptables.signatures.json
  SPECS/iptables/iptables.spec
Labels: Packaging

#770 Add patch to qemu-kvm to fix CVE-2021-20203
  SPECS/qemu-kvm/CVE-2021-20203.patch
  SPECS/qemu-kvm/qemu-kvm.spec
Labels: Packaging

#771 [dev] Update ruby spec
  SPECS/ruby/macros.rubygems
  SPECS/ruby/ruby.signatures.json
  SPECS/ruby/ruby.spec
Labels: Packaging

#764 add bios-grub partition flag
  toolkit/tools/imagegen/configuration/partitionflag.go
  toolkit/tools/imagegen/configuration/partitionflag_test.go
  toolkit/tools/imagegen/diskutils/diskutils.go
Labels: Tools

#746 Update default sshd_config to match other distros
  SPECS/openssh/openssh.spec
Labels: Packaging

#734 Add nopatch for CVE-2021-21309 for redis
  SPECS/redis/CVE-2021-21309.nopatch
  SPECS/redis/redis.spec
Labels: Packaging

#782 Add patch to qemu-kvm to fix CVE-2021-20255
  SPECS/qemu-kvm/CVE-2021-20255.patch
  SPECS/qemu-kvm/qemu-kvm.spec
Labels: Packaging

#789 subversion patch CVE-2020-17525
  SPECS/subversion/CVE-2020-17525.patch
  SPECS/subversion/subversion.spec
Labels: Packaging

#787 python-pygments patch CVE-2021-27291
  SPECS/python-pygments/CVE-2021-27291.patch
  SPECS/python-pygments/python-pygments.spec
Labels: Packaging

#802 Make grpc use system zlib and openssl
  SPECS/grpc/grpc.spec
Labels: Packaging

#799 python-pygments patch CVE-2021-20270
  SPECS/python-pygments/CVE-2021-20270.patch
  SPECS/python-pygments/python-pygments.spec
Labels: Packaging

#800 busybox patch CVE-2021-28831
  SPECS/busybox/CVE-2021-28831.patch
  SPECS/busybox/busybox.spec
Labels: Packaging

#804 Change dropdown menus to accessible input fields
  toolkit/scripts/toolchain.mk
  toolkit/tools/imagegen/attendedinstaller/uitext/uitext.go
  toolkit/tools/imagegen/attendedinstaller/views/diskview/manualpartitionwidget/manualpartitionwidget.go
Labels: Tools

#803 Fixing older toolkit builds. Ignoring 'BuildRequires' on pre-installed packages.
  toolkit/tools/cgmanifest.json
  toolkit/tools/go.mod
  toolkit/tools/go.sum
  toolkit/tools/internal/rpm/rpm.go
  toolkit/tools/internal/safechroot/safechroot.go
  toolkit/tools/internal/sliceutils/sliceutils.go
  toolkit/tools/pkgworker/pkgworker.go
Labels: Tools

#792 Remove unused file toolchain-jdk8-md5sums
  toolkit/scripts/toolchain/container/toolchain-jdk8-md5sums
  toolkit/scripts/toolchain/container/toolchain-jdk8-wget.sh
Labels: Tools

#808 Remove shortcuts from ISO installer views
  toolkit/tools/imagegen/attendedinstaller/views/diskview/autopartitionwidget/autopartitionwidget.go
  toolkit/tools/imagegen/attendedinstaller/views/installationview/installationview.go
  toolkit/tools/imagegen/attendedinstaller/views/installerview/installerview.go
Labels: Tools

#765 Cleaning SRPM expansion and chroot creation console output
  toolkit/Makefile
  toolkit/scripts/pkggen.mk
  toolkit/scripts/srpm_expand.mk
  toolkit/scripts/srpm_pack.mk
  toolkit/scripts/toolchain.mk
  toolkit/tools/pkggen/worker/create_worker_chroot.sh
Labels: Tools

#805 diskutils: add more robust handling of disk/partition operations
  toolkit/tools/imagegen/diskutils/diskutils.go
Labels: Tools

#810 [dev] pkggraph: Add warning when resolving dependency to remote node over local node
  toolkit/tools/internal/pkggraph/pkggraph.go
Labels: Tools

#816 installkernel: Add custom installkernel package
  .github/workflows/validate-cg-manifest.sh
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/installkernel/COPYING
  SPECS/installkernel/installkernel
  SPECS/installkernel/installkernel.signatures.json
  SPECS/installkernel/installkernel.spec
Labels: Packaging

#820 CVE-2020-27618 patch fixed to enable glibc build
  SPECS/glibc/CVE-2020-27618.patch
Labels: Packaging, security
