Repository microsoft/azurelinux, pull requests merged in 2021-08, with the labels that each got.

#1175 [dev] Bringing back `libvirt` subpackages. Revert of #1174.
  SPECS/libvirt/libvirt.spec
Labels: Packaging

#1230 Use sha256sum for toolchain sources
  toolkit/scripts/toolchain/container/Dockerfile
  toolkit/scripts/toolchain/container/toolchain-md5sums
  toolkit/scripts/toolchain/container/toolchain-sha256sums
Labels: Tools

#1235 libdb - no patch CVE-2017-3604 to CVE-2017-3617 and CVE-2020-2981
  SPECS/libdb/CVE-2017-3604.nopatch
  SPECS/libdb/CVE-2017-3605.nopatch
  SPECS/libdb/CVE-2017-3606.nopatch
  SPECS/libdb/CVE-2017-3607.nopatch
  SPECS/libdb/CVE-2017-3608.nopatch
  SPECS/libdb/CVE-2017-3609.nopatch
  SPECS/libdb/CVE-2017-3610.nopatch
  SPECS/libdb/CVE-2017-3611.nopatch
  SPECS/libdb/CVE-2017-3612.nopatch
  SPECS/libdb/CVE-2017-3613.nopatch
  SPECS/libdb/CVE-2017-3614.nopatch
  SPECS/libdb/CVE-2017-3615.nopatch
  SPECS/libdb/CVE-2017-3616.nopatch
  SPECS/libdb/CVE-2017-3617.nopatch
  SPECS/libdb/CVE-2020-2981.nopatch
  SPECS/libdb/libdb.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#1245 [dev] Disable dpdk-examples subpackage
  SPECS/dpdk/dpdk.spec
Labels: Packaging

#1246 Update python-lxml to fix CVEs
  SPECS/python-lxml/lxml-make-check-fix.patch
  SPECS/python-lxml/python-lxml.signatures.json
  SPECS/python-lxml/python-lxml.spec
  cgmanifest.json
Labels: Packaging

#1249 [ISO] Fix display update issues in ManualPartitionWidget
  toolkit/tools/imagegen/attendedinstaller/views/diskview/manualpartitionwidget/manualpartitionwidget.go
Labels: Tools

#1251 Add etcd-tools package
  SPECS/etcd/etcd-3.4.13.spec
Labels: Packaging

#1253 Fix qt5-qtbase Qt5.pc version
  SPECS/qt5-qtbase/qt5-qtbase.spec
Labels: Packaging, ptest

#1259 Fix dbus-python build issue
  SPECS/dbus-python/dbus-python.spec
Labels: Packaging

#1264 Update release in core-packages
  SPECS/core-packages/core-packages.spec
Labels: Packaging

#1180 initial cockpit and dependencies commit
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/cmocka/cmocka.signatures.json
  SPECS/cmocka/cmocka.spec
  SPECS/cockpit/cockpit.signatures.json
  SPECS/cockpit/cockpit.spec
  SPECS/doxygen/doxygen.signatures.json
  SPECS/doxygen/doxygen.spec
  SPECS/libssh/libssh.signatures.json
  SPECS/libssh/libssh.spec
  SPECS/libssh/libssh_client.config
  SPECS/libssh/libssh_server.config
  SPECS/mozjs60/mozjs60.spec
  SPECS/nss_wrapper/nss_wrapper.signatures.json
  SPECS/nss_wrapper/nss_wrapper.spec
  SPECS/pam_wrapper/pam_wrapper.signatures.json
  SPECS/pam_wrapper/pam_wrapper.spec
  SPECS/socket_wrapper/socket_wrapper.signatures.json
  SPECS/socket_wrapper/socket_wrapper.spec
  SPECS/uid_wrapper/0001-pkg-config-Fix-installation-path.patch
  SPECS/uid_wrapper/uid_wrapper-1.2.7-cmake-config-fix-installation-path.patch
  SPECS/uid_wrapper/uid_wrapper.signatures.json
  SPECS/uid_wrapper/uid_wrapper.spec
  cgmanifest.json
Labels: Packaging

#1266 Fix qt5-qtbase Qt5.pc version (1.0 branch)
  SPECS/qt5-qtbase/qt5-qtbase.spec
Labels: Packaging, ptest

#1267 Fixing CVE-2021-32066 in `ruby`
  SPECS/ruby/CVE-2021-32066.patch
  SPECS/ruby/ruby.spec
Labels: Packaging

#1265 Add service/timer for checking restart
  .github/workflows/validate-cg-manifest.sh
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/check-restart/check-restart.service
  SPECS/check-restart/check-restart.sh
  SPECS/check-restart/check-restart.signatures.json
  SPECS/check-restart/check-restart.spec
  SPECS/check-restart/check-restart.timer
  SPECS/core-packages/core-packages.spec
Labels: Packaging

#1280 make cockpit depend on python3 rpm
  SPECS/cockpit/cockpit.spec
Labels: Packaging

#1278 Update sodiff to correctly handle rebuilt/unreleased packages.
  toolkit/scripts/sodiff/mariner-sodiff.sh
Labels: Tools

#1286 Fixing CVE-2021-3682 in `qemu-kvm`.
  SPECS/qemu-kvm/CVE-2021-3682.patch
  SPECS/qemu-kvm/qemu-kvm.spec
Labels: Packaging

#1297 srpmpacker: Change warning to error when duplicate source files detected
  toolkit/tools/srpmpacker/srpmpacker.go
Labels: Tools

#1303 rust: fix CVE-2021-29922
  SPECS/rust/CVE-2021-29922.patch
  SPECS/rust/rust.spec
Labels: Packaging

#1306 Fix sodiff file generation
  toolkit/scripts/sodiff/mariner-sodiff.sh
Labels: Tools

#1318 ctags: fix CVE-2014-7204
  SPECS/ctags/CVE-2014-7204.patch
  SPECS/ctags/ctags.spec
Labels: Packaging

#1315 python3: Resolve python3 broken symlink
  SPECS/python3/python3.spec
Labels: Packaging

#1323 [dev] Adding `Provides: anacron` to `cronie`
  SPECS/cronie/cronie.spec
Labels: Packaging

#1326 `apt-util`: adding more subpackages
  SPECS/apr-util/apr-util.spec
Labels: Packaging

#1328 `cronie`: splitting into subpackages
  SPECS/cronie/cronie.spec
  SPECS/sysstat/sysstat.spec
  toolkit/imageconfigs/packagelists/core-packages-image-aarch64.json
  toolkit/imageconfigs/packagelists/core-packages-image.json
Labels: Packaging

#1332 Disable collectd-virt subpackage due to build break
  SPECS/collectd/collectd.spec
Labels: Packaging

#1345 Fix majority of broken mysql package tests
  SPECS/mysql/mysql.spec
Labels: Packaging

#1347 installutils: Fix generation of SSH user directories when keys not provided
  toolkit/tools/imagegen/installutils/installutils.go
Labels: Tools

#1285 Update prerequisites.md
  toolkit/docs/building/prerequisites.md
Labels: documentation

#1356 Remove diff glyphs
  SPECS/hyperv-daemons/hyperv-daemons.signatures.json
  SPECS/hyperv-daemons/hyperv-daemons.spec
  SPECS/kernel-headers/kernel-headers.signatures.json
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel-hyperv/config
  SPECS/kernel-hyperv/kernel-hyperv.signatures.json
  SPECS/kernel-hyperv/kernel-hyperv.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  SPECS/mariner-release/mariner-release.spec
  SPECS/mysql/mysql.spec
Labels: Packaging
