Repository microsoft/azurelinux, pull requests merged in 2021-09, with the labels that each got.

#1359 [dev] git: bump version to 2.33.0
  SPECS/git/git.signatures.json
  SPECS/git/git.spec
  cgmanifest.json
Labels: Packaging

#1361 [dev] Adding `libradosstriper` subpackvages to `ceph`.
  SPECS/ceph/ceph.spec
Labels: Packaging

#1367 Enable omuxsock in rsyslog and add customized syslog-ng conf
  SPECS/rsyslog/rsyslog.spec
  SPECS/syslog-ng/syslog-ng.conf
  SPECS/syslog-ng/syslog-ng.signatures.json
  SPECS/syslog-ng/syslog-ng.spec
Labels: Packaging

#1368 [dev] git: enable subpackages deamon, subtree & svn
  SPECS/git/git.spec
Labels: Packaging

#1374 Fix elfutils break from _sysctldir macro
  SPECS/elfutils/elfutils.spec
Labels: Packaging

#1335 [dev] Add dwarves package
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/dwarves/0001-btf-Remove-ftrace-filter.patch
  SPECS/dwarves/dwarves.signatures.json
  SPECS/dwarves/dwarves.spec
  cgmanifest.json
Labels: Packaging

#1353 Update lldpad to version 1.1
  SPECS/lldpad/lldpad.signatures.json
  SPECS/lldpad/lldpad.spec
  SPECS/lldpad/remove-lldp-ethertype-use-linux-5.3-header-instead.patch
  cgmanifest.json
Labels: ptest

#1379 Enable omuxsock in rsyslog and add customized syslog-ng conf (#1367)
  SPECS/rsyslog/rsyslog.spec
  SPECS/syslog-ng/syslog-ng.conf
  SPECS/syslog-ng/syslog-ng.signatures.json
  SPECS/syslog-ng/syslog-ng.spec
Labels: Packaging

#1380 Remove references to toolchain-md5sums
  toolkit/scripts/toolchain/container/toolchain-jdk8-wget.sh
  toolkit/scripts/toolchain/create_toolchain_in_container.sh
Labels: Tools

#1384 [dev] Cleaning SRPM expansion console output
  toolkit/scripts/srpm_expand.mk
  toolkit/scripts/srpm_pack.mk
  toolkit/scripts/toolchain.mk
Labels: Tools

#1389 Enable systemd plug-in in fluent-bit to support journal reader
  SPECS/fluent-bit/fluent-bit.spec
Labels: Packaging

#1400 [dev]: adding missing signatures for `httpd` sources.
  SPECS/httpd/httpd.signatures.json
  SPECS/httpd/httpd.spec
Labels: Packaging

#1403 Fix libdb CVE-2019-2708
  SPECS/libdb/CVE-2019-2708.patch
  SPECS/libdb/libdb.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#1413 Fix rsyslog.d and product_uuid permissions
  SPECS/WALinuxAgent/WALinuxAgent.spec
  SPECS/rsyslog/rsyslog.spec
Labels: Packaging

#1391 Fix qemu CVE-2021-3713
  SPECS/qemu-kvm/CVE-2020-12829.nopatch
  SPECS/qemu-kvm/CVE-2021-3713.patch
  SPECS/qemu-kvm/qemu-kvm.spec
Labels: Packaging

#1414 [dev] Fix rsyslog.d and product_uuid permissions
  SPECS/WALinuxAgent/WALinuxAgent.spec
  SPECS/rsyslog/rsyslog.spec
Labels: Packaging

#1421 Patch helm CVE-2021-21303
  SPECS/helm/CVE-2021-21303.patch
  SPECS/helm/helm.spec
Labels: Packaging

#1422 [dev] Patch helm CVE-2021-21303
  SPECS/helm/CVE-2021-21303.patch
  SPECS/helm/helm.spec
Labels: Packaging

#1423 Patch helm CVE-2021-32690
  SPECS/helm/CVE-2021-32690.patch
  SPECS/helm/helm.spec
Labels: Packaging

#1424 [dev] Patch helm CVE-2021-32690
  SPECS/helm/CVE-2021-32690.patch
  SPECS/helm/helm.spec
Labels: Packaging

#1442 Use sha256sum for dev branch toolchain sources
  toolkit/scripts/toolchain/container/Dockerfile
  toolkit/scripts/toolchain/container/toolchain-jdk8-wget.sh
  toolkit/scripts/toolchain/container/toolchain-md5sums
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/create_toolchain_in_container.sh
Labels: Tools

#1445 Patch graphviz CVE-2020-18032
  SPECS/graphviz/CVE-2020-18032.patch
  SPECS/graphviz/graphviz.spec
Labels: Packaging

#1440 Add partition and disk config validation
  toolkit/scripts/tools.mk
  toolkit/tools/imagegen/configuration/configuration.go
  toolkit/tools/imagegen/configuration/configuration_test.go
  toolkit/tools/imagegen/configuration/verityerrorbehavior_test.go
Labels: Tools

#1441 Don't override all artifact settings if using diff
  toolkit/tools/roast/roast.go
Labels: Tools

#1451 [dev] dpdk: enable `tools` subpackage by default
  SPECS/dpdk/dpdk.spec
Labels: Packaging

#1428 [dev] Update clang/llvm to latest 12.0.1 release and update downstream packages as necessary
  SPECS/bcc/bcc.signatures.json
  SPECS/bcc/bcc.spec
  SPECS/bpftrace/bpftrace.signatures.json
  SPECS/bpftrace/bpftrace.spec
  SPECS/clang/clang.signatures.json
  SPECS/clang/clang.spec
  SPECS/lldb/0001-Silence-GCC-warnings-about-format-not-being-a-string.patch
  SPECS/lldb/lldb.signatures.json
  SPECS/lldb/lldb.spec
  SPECS/llvm/llvm.signatures.json
  SPECS/llvm/llvm.spec
  cgmanifest.json
Labels: Packaging

#1369 Add specfile for DataStax Cassandra CPP driver
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/cassandra-cpp-driver/cassandra-cpp-driver.signatures.json
  SPECS/cassandra-cpp-driver/cassandra-cpp-driver.spec
  cgmanifest.json
Labels: Packaging

#1468 Fix grpc-devel file conflict
  SPECS/grpc/grpc.spec
Labels: Packaging

#1474 [dev] `openssh` and `cifs-utils`: adding `pam_*` subpackages
  SPECS/cifs-utils/cifs-utils.spec
  SPECS/openssh/openssh.signatures.json
  SPECS/openssh/openssh.spec
  SPECS/openssh/pam_ssh_agent-rmheaders
  SPECS/openssh/pam_ssh_agent_auth-0.10.2-compat.patch
  SPECS/openssh/pam_ssh_agent_auth-0.10.2-dereference.patch
  SPECS/openssh/pam_ssh_agent_auth-0.10.3-seteuid.patch
  SPECS/openssh/pam_ssh_agent_auth-0.9.2-visibility.patch
  SPECS/openssh/pam_ssh_agent_auth-0.9.3-agent_structure.patch
  SPECS/openssh/pam_ssh_agent_auth-0.9.3-build.patch
Labels: Packaging
