Repository microsoft/azurelinux, pull requests merged in 2021-06, with the labels that each got.

#1006 Reduce toolchain build time (via nss) and speed up nss package tests
  SPECS/nss/nss.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
Labels: ptest

#1007 growpart: Remove flock workaround
  SPECS/cloud-utils-growpart/cloud-utils-growpart.spec
  SPECS/cloud-utils-growpart/growpart-remove-flock-disk-locking.patch
Labels: Packaging

#1010 Fix polkit CVE-2021-3560
  SPECS/polkit/CVE-2021-3560.patch
  SPECS/polkit/polkit.spec
Labels: Packaging

#1001 Creating nvidia repo file and user instructions
  toolkit/docs/nvidia/mariner-nvidia.repo
  toolkit/docs/nvidia/nvidia.md
Labels: documentation

#1014 Updated zeromq to 4.3.4 to address CVE-2021-20236
  SPECS/zeromq/zeromq.signatures.json
  SPECS/zeromq/zeromq.spec
  cgmanifest.json
Labels: Packaging

#1008 Fix libxml2 CVEs
  SPECS/libxml2/CVE-2019-20388.patch
  SPECS/libxml2/CVE-2020-24977.patch
  SPECS/libxml2/CVE-2020-7595.patch
  SPECS/libxml2/libxml2.signatures.json
  SPECS/libxml2/libxml2.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#1027 kexec-tools: Always use -s option in kdumpctl
  SPECS/kexec-tools/kdumpctl
  SPECS/kexec-tools/kexec-tools.signatures.json
  SPECS/kexec-tools/kexec-tools.spec
Labels: Packaging

#1026 dhcp: add explicit provides for dhclient
  SPECS/dhcp/dhcp.spec
Labels: Packaging

#1025 Update PR template with package test check
  .github/pull_request_template.md
Labels: ptest

#1023 Patch qemu-kvm: CVE-2021-20181
  SPECS/qemu-kvm/CVE-2021-20181.patch
  SPECS/qemu-kvm/qemu-kvm.spec
Labels: Packaging

#1029 Fix check tests for python-execnet and python-repoze-lru
  SPECS/python-execnet/python-execnet.spec
  SPECS/python-repoze-lru/python-repoze-lru.spec
Labels: Packaging, ptest

#1016 Enable polkit check tests
  SPECS/polkit/polkit.spec
Labels: Packaging, ptest

#1030 [dev] man-db: add explicit provides for 'man-pages-reader'
  SPECS/man-db/man-db.spec
Labels: Packaging

#1040 Patch libjpeg-turbo CVE-2020-17541
  SPECS/libjpeg-turbo/CVE-2020-17541.patch
  SPECS/libjpeg-turbo/libjpeg-turbo.spec
Labels: Packaging

#1044 installutils: remove machine-id owner write perms
  toolkit/tools/imagegen/installutils/installutils.go
Labels: Tools

#1045 python-sphinx: Add missing runtime dependency on setuptools
  SPECS/python-sphinx/python-sphinx.spec
Labels: Packaging

#1043 populate user's ssh/authorized_keys
  toolkit/tools/imagegen/installutils/installutils.go
Labels: Tools

#1057 Update perl Requires for collectd
  SPECS/collectd/collectd.spec
Labels: Packaging

#1051 Patch CVE-2020-10701
  SPECS/libvirt/CVE-2020-10701.patch
  SPECS/libvirt/libvirt.spec
Labels: Packaging

#1058 Fix libcurl issue in python-pycurl tests
  SPECS/python-pycurl/python-pycurl.spec
  SPECS/python-pycurl/skip-incompatible-libcurl-tests.patch
Labels: Packaging, ptest

#953 Align toolchain package versions to SPEC versions
  toolkit/scripts/toolchain/container/jdk8-build-raw.sh
  toolkit/scripts/toolchain/container/toolchain-md5sums
  toolkit/scripts/toolchain/container/toolchain-remote-wget-list
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
  toolkit/scripts/toolchain/container/toolchain_build_temp_tools.sh
Labels: Tools

#1060 disable debuginfo due to size
  SPECS/ceph/ceph.spec
Labels: Packaging

#1063 Remove unused toolchain SCRIPTS directory
  toolkit/scripts/toolchain.mk
  toolkit/scripts/toolchain/SCRIPTS/brp-strip-debug-symbols
  toolkit/scripts/toolchain/SCRIPTS/brp-strip-unneeded
  toolkit/scripts/toolchain/SCRIPTS/macros
Labels: Tools

#1066 [dev] Update harfbuzz to have icu support
  SPECS/harfbuzz/harfbuzz.spec
Labels: Packaging

#1041 Force install RPMs in toolchain build
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
Labels: Tools

#1068 Making `grpc` use system's `protobuf`.
  SPECS/grpc/grpc.spec
  SPECS/protobuf/protobuf.signatures.json
  SPECS/protobuf/protobuf.spec
  cgmanifest.json
Labels: Packaging

#1069 iptables: Add dependency on iana-etc
  SPECS/iptables/iptables.spec
Labels: Packaging

#1070 CVE fixes for httpd libgcrypt tpm2-tools and qemu-kvm SPECs
  SPECS/httpd/CVE-2020-13950.patch
  SPECS/httpd/CVE-2020-35452.patch
  SPECS/httpd/CVE-2021-26690.patch
  SPECS/httpd/CVE-2021-30641.patch
  SPECS/httpd/httpd.spec
  SPECS/libgcrypt/libgcrypt-CVE-2021-33560-fix.patch
  SPECS/libgcrypt/libgcrypt.spec
  SPECS/qemu-kvm/CVE-2020-27661.nopatch
  SPECS/qemu-kvm/qemu-kvm.spec
  SPECS/tpm2-tools/CVE-2021-3565.patch
  SPECS/tpm2-tools/tpm2-tools.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#1078 [dev] Adding `libnghttp2*` `Provides` to `nghttp2`.
  SPECS/nghttp2/nghttp2.spec
Labels: Packaging

#1083 Fix ptests for python-ptyprocess, python-pexpect
  SPECS/python-pexpect/python-pexpect.spec
  SPECS/python-pexpect/sys_executable.patch
  SPECS/python-ptyprocess/python-ptyprocess.spec
Labels: Packaging, ptest

#1076 Make chronyd not listen on UDP port by default
  SPECS/chrony/chrony.spec
Labels: Packaging

#1082 [dev] Force install RPMs in toolchain build
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
Labels: Tools

#1087 Fix CVE-2021-26691 for httpd
  SPECS/httpd/CVE-2021-26691.patch
  SPECS/httpd/httpd.spec
Labels: Packaging

#1088 [dev] Fix harfbuzz dependency on freetype
  SPECS/harfbuzz/harfbuzz.spec
Labels: Packaging

#1080 Pass tests in python packages jwt, pecan, routes, remoto
  SPECS/python-jwt/python-jwt.spec
  SPECS/python-pecan/python-pecan.spec
  SPECS/python-remoto/python-remoto.spec
  SPECS/python-routes/python-routes.spec
Labels: Packaging, ptest

#1067 [dev] Fix location of dbus-glib pkgconfig provides
  SPECS/dbus-glib/dbus-glib.spec
Labels: Packaging

#1098 [dev] Upgrade libusb to 1.0.24, add compatibility provides
  SPECS/libusb/libusb.signatures.json
  SPECS/libusb/libusb.spec
  cgmanifest.json
Labels: Packaging

#1099 [dev] Add static subpackage provides to libseccomp-devel
  SPECS/libseccomp/libseccomp.spec
Labels: Packaging
