Repository microsoft/azurelinux, pull requests merged in 2021-07, with the labels that each got.

#1108 Fixing shared libraries declaration.
  SPECS/libconfig/libconfig.spec
Labels: Packaging

#1109 Adding alternative 'Provides' for 'python-six'.
  SPECS/python-six/python-six.spec
Labels: Packaging

#1117 [dev] Fixing spec dependencies parsing bugs.
  toolkit/tools/go.mod
  toolkit/tools/go.sum
  toolkit/tools/internal/pkggraph/pkggraph_test.go
  toolkit/tools/internal/pkgjson/pkgjson.go
  toolkit/tools/internal/pkgjson/pkgjson_test.go
  toolkit/tools/internal/versioncompare/versioncompare.go
  toolkit/tools/specreader/specreader.go
Labels: Tools

#1129 [dev] Install ruby's json library as a gem
  SPECS/ruby/ruby.spec
Labels: Packaging

#1127 [dev] psycopg2: add doc subpackage
  SPECS/python-psycopg2/python-psycopg2.spec
Labels: Packaging

#1126 [dev] newt: enable subpackage python3-newt
  SPECS/newt/newt.spec
Labels: Packaging

#1131 [dev] Resolve bazel aarch64 build break
  SPECS/bazel/bazel.spec
  SPECS/bazel/fix-jni-build-error.patch
Labels: Packaging

#1137 Build PAM with selinux support
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
Labels: Tools

#1140 Update moby-containerd to version 1.4.4 - port to 1.0 branch
  SPECS/moby-containerd/generate-sources.sh
  SPECS/moby-containerd/moby-containerd.signatures.json
  SPECS/moby-containerd/moby-containerd.spec
Labels: Packaging

#1155 Removing unused run-time requirement from `glusterfs-thin-arbiter`.
  SPECS/glusterfs/glusterfs.spec
Labels: Packaging

#1156 [dev] Update bubblewrap to 0.4.1
  SPECS/bubblewrap/CVE-2019-12439.patch
  SPECS/bubblewrap/CVE-2020-5291.nopatch
  SPECS/bubblewrap/bubblewrap.signatures.json
  SPECS/bubblewrap/bubblewrap.spec
  cgmanifest.json
Labels: Packaging

#1153 patch moby-containerd to resolve CVE-2021-32760
  SPECS/moby-containerd/CVE-2021-32760.patch
  SPECS/moby-containerd/moby-containerd.spec
Labels: Packaging

#1162 [dev] Adding `Provides` for common `grub2` subpackages.
  SPECS-SIGNED/grub2-efi-binary-signed/grub2-efi-binary-signed.spec
  SPECS/grub2/grub2.spec
Labels: Packaging

#1163 patch moby-containerd to resolve CVE-2021-32760 (#1153)
  SPECS/moby-containerd/CVE-2021-32760.patch
  SPECS/moby-containerd/moby-containerd.spec
Labels: Packaging

#1174 Reverting extension of `libvirt` by 25 subpackages.
  SPECS/libvirt/libvirt.spec
Labels: Packaging

#1182 [dev] libseccomp-devel: Add runtime requirement on base package
  SPECS/libseccomp/libseccomp.spec
Labels: Packaging

#1192 [dev] Add compatibility package provides to several packages
  SPECS/boost/boost.spec
  SPECS/clamav/clamav.spec
  SPECS/dtc/dtc.spec
  SPECS/efivar/efivar.spec
  SPECS/fuse/fuse.spec
  SPECS/gdb/gdb.spec
  SPECS/gnutls/gnutls.spec
  SPECS/libcap-ng/libcap-ng.spec
  SPECS/libjpeg-turbo/libjpeg-turbo.spec
  SPECS/libqmi/libqmi.spec
  SPECS/lm-sensors/lm-sensors.spec
  SPECS/net-snmp/net-snmp.spec
  SPECS/openldap/openldap.spec
  SPECS/openscap/openscap.spec
  SPECS/pcre/pcre.spec
  SPECS/pcre2/pcre2.spec
  SPECS/unbound/unbound.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#1200 Fixing `dtc` and `net-snmp` specs.
  SPECS/dtc/dtc.spec
  SPECS/net-snmp/net-snmp.spec
Labels: Packaging

#1204 Fix test for perl-CPAN-Meta-Check
  SPECS/perl-CPAN-Meta-Check/perl-CPAN-Meta-Check.spec
Labels: Packaging, ptest
