Repository microsoft/azurelinux, pull requests merged in 2021-05, with the labels that each got.

#908 Thcrain/corrosion
  SPECS/rust/CVE-2021-28879.patch
Labels: security

#909 [dev] Fix typo in glib spec
  SPECS/glib/glib.spec
Labels: Packaging

#910 Patching CVE-2021-20208 in `cifs-utils`.
  SPECS/cifs-utils/CVE-2021-20208.patch
  SPECS/cifs-utils/cifs-utils.spec
Labels: Packaging

#907 [dev] Adding symbolic links to `groff`.
  SPECS/groff/groff.spec
Labels: Packaging

#912 [dev] Update bind to enable missing packages
  SPECS/bind/bind-9.10-dist-native-pkcs11.patch
  SPECS/bind/bind-9.14-config-pkcs11.patch
  SPECS/bind/bind.signatures.json
  SPECS/bind/bind.spec
  SPECS/bind/generate-rndc-key.sh
  SPECS/bind/named-chroot.files
  SPECS/bind/named.conf.sample
  SPECS/bind/named.empty
  SPECS/bind/named.localhost
  SPECS/bind/named.logrotate
  SPECS/bind/named.loopback
  SPECS/bind/named.rfc1912.zones
  SPECS/bind/named.root
  SPECS/bind/named.root.key
  SPECS/bind/named.rwtab
  SPECS/bind/named.sysconfig
  SPECS/bind/setup-named-chroot.sh
  SPECS/bind/setup-named-softhsm.sh
  SPECS/bind/trusted-key.key
Labels: Packaging

#911 Updating `ruby` to version 2.6.7 to fix CVE-2021-28965.
  SPECS/ruby/CVE-2020-25613.patch
  SPECS/ruby/ruby.signatures.json
  SPECS/ruby/ruby.spec
Labels: Packaging

#916 Disable test_ssl_handshake in libserf
  SPECS/libserf/libserf.spec
Labels: Packaging

#915 Adding heartbeat log for package builds.
  toolkit/tools/pkgworker/pkgworker.go
Labels: Tools

#918 Fix td-agent build break
  SPECS/td-agent/td-agent.patch
  SPECS/td-agent/td-agent.spec
Labels: Packaging

#921 quickstart: add Secure Boot instructions on HyperV
  toolkit/docs/quick_start/quickstart.md
Labels: documentation

#924 Add python3-Cython subpackage
  SPECS/Cython/Cython.spec
  SPECS/Cython/cython_testfix_with_outer_raising.patch
Labels: Packaging

#927 Fix "Mr serious" voice name in espeak-ng
  SPECS/espeak-ng/espeak-ng.spec
Labels: Packaging

#933 Fix build break due to file dependency in python-pexpect
  SPECS/python-pexpect/python-pexpect.spec
Labels: Packaging

#931 Fixing parsing the packages JSON.
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/internal/pkgjson/pkgjson.go
  toolkit/tools/internal/pkgjson/pkgjson_test.go
Labels: Tools

#936 Fix doubly packaged file in sos package
  SPECS/sos/sos.spec
Labels: Packaging

#941 [dev] Fix build break caused by bind and man-db
  SPECS/bind/bind.spec
  SPECS/man-db/man-db.spec
Labels: Packaging

#938 Adding more details for reproducing builds with summary files.
  toolkit/docs/building/building.md
Labels: documentation

#950 [dev] Add "cargo" provides to rust package
  SPECS/rust/rust.spec
Labels: Packaging

#951 Adding missing signature in `mariner-rpm-macros`.
  SPECS/mariner-rpm-macros/mariner-rpm-macros.signatures.json
Labels: Packaging

#960 fix moby-runc merge issues in 1.0 branch
  SPECS/moby-runc/moby-runc.signatures.json
  SPECS/moby-runc/moby-runc.spec
Labels: Packaging

#956 fix k8s version issue
  SPECS/kubernetes/kubernetes-1.18.14.signatures.json
  SPECS/kubernetes/kubernetes-1.18.14.spec
  SPECS/kubernetes/kubernetes-1.18.17.signatures.json
  SPECS/kubernetes/kubernetes-1.18.17.spec
  SPECS/kubernetes/kubernetes-1.19.7.signatures.json
  SPECS/kubernetes/kubernetes-1.19.7.spec
  SPECS/kubernetes/kubernetes-1.19.9.signatures.json
  SPECS/kubernetes/kubernetes-1.19.9.spec
  SPECS/kubernetes/kubernetes-1.20.2.signatures.json
  SPECS/kubernetes/kubernetes-1.20.2.spec
  SPECS/kubernetes/kubernetes-1.20.5.signatures.json
  SPECS/kubernetes/kubernetes-1.20.5.spec
  SPECS/kubernetes/version-file-1.18.14.sh
  SPECS/kubernetes/version-file-1.18.17.sh
  SPECS/kubernetes/version-file-1.19.7.sh
  SPECS/kubernetes/version-file-1.19.9.sh
  SPECS/kubernetes/version-file-1.20.2.sh
  SPECS/kubernetes/version-file-1.20.5.sh
Labels: Packaging

#965 Adding CBL-Mariner .repo files to the toolkit.
  toolkit/scripts/toolkit.mk
Labels: Tools

#966 Adding documentation about the `REPO_LIST` argument.
  toolkit/docs/building/building.md
Labels: documentation

#968 Added explicit dependency on python-xml for libxml2
  SPECS/libxml2/libxml2.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#928 Add Jitterentropy to OpenSSL
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/jitterentropy/jitterentropy.signatures.json
  SPECS/jitterentropy/jitterentropy.spec
  SPECS/openssl/openssl-1.1.1-jitterentropy.patch
  SPECS/openssl/openssl.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#969 cdrkit: add an explicit provides for 'genisoimage'
  SPECS/cdrkit/cdrkit.spec
Labels: Packaging

#979 Updating `nvidia-container-toolkit` signatures to match source.
  SPECS/nvidia-container-toolkit/nvidia-container-toolkit.signatures.json
  SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec
Labels: Packaging

#975 kernel: Fix build break in aarch64 build
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
Labels: Packaging

#987 Update libwebp to 1.0.3, fixing CVEs.
  SPECS/libwebp/libwebp.signatures.json
  SPECS/libwebp/libwebp.spec
  cgmanifest.json
Labels: Packaging

#981 [dev] Add libgudev1* provides to libgudev spec
  SPECS/libgudev/libgudev.spec
Labels: Packaging

#837 Implement and integrate enumfield
  toolkit/tools/imagegen/attendedinstaller/primitives/enumfield/enumfield.go
  toolkit/tools/imagegen/attendedinstaller/views/diskview/manualpartitionwidget/manualpartitionwidget.go
Labels: Tools

#996 Patch dhcp for CVE-2021-25217
  SPECS/dhcp/CVE-2021-25217.patch
  SPECS/dhcp/dhcp.spec
Labels: Packaging

#983 Making vendor tarballs reproducible for `coredns` and `nvidia-container-toolkit`
  SPECS/coredns/coredns-1.6.7.signatures.json
  SPECS/coredns/coredns-1.6.7.spec
  SPECS/coredns/coredns-1.7.0.signatures.json
  SPECS/coredns/coredns-1.7.0.spec
  SPECS/nvidia-container-toolkit/nvidia-container-toolkit.signatures.json
  SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec
Labels: Packaging

#984 [dev] Updating `coredns` signatures
  SPECS/coredns/coredns-1.6.7.signatures.json
  SPECS/coredns/coredns-1.6.7.spec
  SPECS/coredns/coredns-1.7.0.signatures.json
  SPECS/coredns/coredns-1.7.0.spec
Labels: Packaging
