Repository microsoft/azurelinux, pull requests merged in 2021-04, with the labels that each got.

#822 Patch CVE-2021-3416 and add tests to qemu-kvm
  SPECS/qemu-kvm/CVE-2021-3416.patch
  SPECS/qemu-kvm/qemu-kvm.spec
Labels: Packaging

#809 grub2: Add a few more patches
  SPECS-SIGNED/grub2-efi-binary-signed-aarch64/grub2-efi-binary-signed-aarch64.spec
  SPECS-SIGNED/grub2-efi-binary-signed-x64/grub2-efi-binary-signed-x64.spec
  SPECS/grub2/0017-Pass-x-hex-hex-straight-through-unmolested.patch
  SPECS/grub2/0037-Replace-a-lot-of-man-pages-with-slightly-nicer-ones.patch
  SPECS/grub2/0052-Make-our-info-pages-say-grub2-where-appropriate.patch
  SPECS/grub2/0069-Make-pmtimer-tsc-calibration-not-take-51-seconds-to-.patch
  SPECS/grub2/0166-grub-install-disable-support-for-EFI-platforms.patch
  SPECS/grub2/grub2.spec
Labels: Packaging

#834 grub2: Add nopatches for tooling
  SPECS-SIGNED/grub2-efi-binary-signed-aarch64/grub2-efi-binary-signed-aarch64.spec
  SPECS-SIGNED/grub2-efi-binary-signed-x64/grub2-efi-binary-signed-x64.spec
  SPECS/grub2/CVE-2020-10713.nopatch
  SPECS/grub2/CVE-2020-14308.nopatch
  SPECS/grub2/CVE-2020-14309.nopatch
  SPECS/grub2/CVE-2020-14310.nopatch
  SPECS/grub2/CVE-2020-14311.nopatch
  SPECS/grub2/CVE-2020-14372.nopatch
  SPECS/grub2/CVE-2020-25632.nopatch
  SPECS/grub2/CVE-2020-25647.nopatch
  SPECS/grub2/CVE-2020-27749.nopatch
  SPECS/grub2/CVE-2020-27779.nopatch
  SPECS/grub2/CVE-2021-20225.nopatch
  SPECS/grub2/CVE-2021-20233.nopatch
  SPECS/grub2/CVE-2021-3418.nopatch
  SPECS/grub2/grub2.spec
Labels: Packaging

#821 update community instructions
  toolkit/docs/building/building.md
Labels: documentation

#824 update community instructions (1.0 branch)
  toolkit/docs/building/building.md
Labels: documentation

#839 [dev] Update httpd to include necessary macros
  SPECS/httpd/httpd.signatures.json
  SPECS/httpd/httpd.spec
  SPECS/httpd/macros.httpd
Labels: Packaging

#843 Fixing parsing toolchain and worker chroot manifests
  toolkit/scripts/addcerts.sh
  toolkit/scripts/preparemacros.sh
  toolkit/tools/pkggen/worker/create_worker_chroot.sh
Labels: Tools

#842 Fix CVE-2021-3392 and CVE-2021-3409 in qemu-kvm
  SPECS/qemu-kvm/CVE-2021-3392.patch
  SPECS/qemu-kvm/CVE-2021-3409.patch
  SPECS/qemu-kvm/qemu-kvm.spec
Labels: Packaging

#832 Upgrade mariadb to 10.3.28
  SPECS/mariadb/mariadb.signatures.json
  SPECS/mariadb/mariadb.spec
  cgmanifest.json
Labels: Packaging

#845 Add CVE-2021-3470 for redis and CVE-2021-30004 for wpa_supplicant
  SPECS/redis/CVE-2021-3470.patch
  SPECS/redis/redis.spec
  SPECS/wpa_supplicant/CVE-2021-30004.patch
  SPECS/wpa_supplicant/wpa_supplicant.spec
Labels: Packaging

#848 Update openvswitch signatures file to version 2.12.3
  SPECS/openvswitch/openvswitch.signatures.json
Labels: Packaging

#844 Fixing azure-iotedge.spec `BuildRequires` typo from '==' to '='.
  SPECS/azure-iotedge/azure-iotedge.spec
Labels: Packaging

#849 [dev] Fix dtc build error
  SPECS/dtc/dtc-disable-warning.patch
  SPECS/dtc/dtc.spec
Labels: Packaging

#854 Making 'keepalived' link against latest 'net-snmp' libraries.
  SPECS/keepalived/keepalived.spec
Labels: Packaging

#858 1.0-dev cherry-pick: Making 'keepalived' link against latest 'net-snmp' libraries.
  SPECS/keepalived/keepalived.spec
Labels: Packaging

#853 Adding clarifications about config file paths.
  toolkit/docs/building/building.md
Labels: documentation

#864 Don't Configure Grub Encryption Settings in Chroot
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/imager/imager.go
Labels: Tools

#868 Don't Configure Grub Encryption Settings in Chroot (#864)
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/imager/imager.go
Labels: Tools

#785 kernel-signed: define a new kernel subpackage
  .github/workflows/check_entangled_specs.py
  .github/workflows/validate-cg-manifest.sh
  SPECS-SIGNED/kernel-signed-aarch64/kernel-signed-aarch64.spec
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel-hyperv/kernel-hyperv.spec
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#866 shim: Introduce shim package
  .github/workflows/validate-cg-manifest.sh
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/shim/shim.signatures.json
  SPECS/shim/shim.spec
Labels: Packaging

#855 grub-efi-binary-signed: define new grub2-efi-binary subpackage
  .github/workflows/check_entangled_specs.py
  .github/workflows/validate-cg-manifest.sh
  SPECS-SIGNED/grub2-efi-binary-signed-x64/grub2-efi-binary-signed-x64.spec
  SPECS-SIGNED/grub2-efi-binary-signed/grub2-efi-binary-signed.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/grub2/grub2.spec
Labels: Packaging

#865 Exclude static libraries in openvswitch package
  SPECS/openvswitch/openvswitch.spec
Labels: Packaging

#870 Fix installation and removal of atd.service
  SPECS/at/at.spec
Labels: Packaging

#876 Adding missing patch signature for "kubernetes-1.18.17".
  SPECS/kubernetes/kubernetes-1.18.17.signatures.json
Labels: Packaging

#878 Updating license info for 'kubernetes' and 'coredns'.
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
Labels: Packaging

#883 Patch CVE-2021-28879 in Rust
  SPECS/azure-iotedge/azure-iotedge.spec
  SPECS/cloud-hypervisor/cloud-hypervisor.spec
  SPECS/rpm-ostree/rpm-ostree.spec
  SPECS/rust/CVE-2021-28879.patch
  SPECS/rust/rust.spec
Labels: Packaging

#887 Patch several CVEs in Rust
  SPECS/azure-iotedge/azure-iotedge.spec
  SPECS/cloud-hypervisor/cloud-hypervisor.spec
  SPECS/rpm-ostree/rpm-ostree.spec
  SPECS/rust/CVE-2020-36317.patch
  SPECS/rust/CVE-2020-36323.patch
  SPECS/rust/CVE-2021-28875.patch
  SPECS/rust/CVE-2021-28876.patch
  SPECS/rust/CVE-2021-28877.patch
  SPECS/rust/CVE-2021-28878.patch
  SPECS/rust/CVE-2021-28879.patch
  SPECS/rust/rust.spec
Labels: Packaging

#891 [dev] Update clang to fix lldb build error
  SPECS/clang/clang.spec
Labels: Packaging

#898 Fix python3 test_ssl tests
  SPECS/python3/fix_broken_mariner_ssl_tests.patch
  SPECS/python3/python3.spec
Labels: Packaging, ptest

#899 Added config line to unvendor c-ares in grpc; now uses system package
  SPECS/grpc/grpc.spec
Labels: Packaging

#896 cloud-utils-growpart: Workaround for timeout
  SPECS/cloud-utils-growpart/cloud-utils-growpart.spec
  SPECS/cloud-utils-growpart/growpart-remove-flock-disk-locking.patch
Labels: Packaging
