Repository microsoft/azurelinux, pull requests merged in 2021-01, with the labels that each got.

#427 diskutils: Include virtual disk devices in search
  toolkit/tools/imagegen/diskutils/diskutils.go
Labels: Tools

#505 Kubernetes: No patch CVE-2020-8564, CVE-2020-8565, CVE-2020-8566
  SPECS/kubernetes/CVE-2020-8564.nopatch
  SPECS/kubernetes/CVE-2020-8565.nopatch
  SPECS/kubernetes/CVE-2020-8566.nopatch
  SPECS/kubernetes/kubernetes-1.17.11.spec
  SPECS/kubernetes/kubernetes-1.17.13.spec
  SPECS/kubernetes/kubernetes-1.18.10.spec
  SPECS/kubernetes/kubernetes-1.18.8.spec
  SPECS/kubernetes/kubernetes-1.19.1.spec
  SPECS/kubernetes/kubernetes-1.19.3.spec
Labels: Packaging

#507 openssh: add BRs for check section, patch broken tests
  SPECS/openssh/openssh.spec
  SPECS/openssh/regress-test-future-cert-fix.patch
Labels: Packaging, ptest

#509 Fix tests for grep, gawk, mozjs60, skip jna test
  SPECS/gawk/gawk.spec
  SPECS/grep/grep.spec
  SPECS/mozjs60/mozjs60.spec
  toolkit/resources/manifests/package/macros.override
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: ptest

#510 [dev] Add additional provides and compatibility links
  SPECS/docbook-style-xsl/docbook-style-xsl.spec
  SPECS/guile/guile.spec
  SPECS/keyutils/keyutils.spec
  SPECS/ruby/ruby.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#511 libisoburn: fix package test
  SPECS/libisoburn/libisoburn.spec
Labels: Packaging, ptest

#512 librepo: enable package tests
  SPECS/librepo/librepo.spec
Labels: Packaging, ptest

#513 python-bcrypt, python-pynacl: Fix package tests
  SPECS/python-bcrypt/python-bcrypt.spec
  SPECS/python-pynacl/python-pynacl.spec
Labels: Packaging, ptest

#515 Fix test for python-attrs, libmodulemd, skip dracut tests
  SPECS/libmodulemd/libmodulemd.spec
  SPECS/libmodulemd/test_v1_import_headers_timeout.patch
  SPECS/python-attrs/python-attrs.spec
  toolkit/resources/manifests/package/macros.override
Labels: ptest

#514 rust: Fix package test
  SPECS/rust/ignore-linker-output-non-utf8-test.patch
  SPECS/rust/rust.spec
Labels: Packaging, ptest

#517 [dev] Enable gobject-instrospection support in `libsoup`
  SPECS/libsoup/libsoup.spec
Labels: Packaging

#518 Fix check test for strace
  SPECS/strace/gen_tests_fixes.patch
  SPECS/strace/strace.spec
Labels: Packaging, ptest

#516 Kubernetes: nopatch CVE-2020-8563, fix tests issue when built against golang 1.15 (k8s 1.17 and 1.18)
  SPECS/kubernetes/CVE-2020-8563.nopatch
  SPECS/kubernetes/golang-1.15-k8s-1.17-test.patch
  SPECS/kubernetes/golang-1.15-k8s-1.18-test.patch
  SPECS/kubernetes/kubernetes-1.17.11.signatures.json
  SPECS/kubernetes/kubernetes-1.17.11.spec
  SPECS/kubernetes/kubernetes-1.17.13.signatures.json
  SPECS/kubernetes/kubernetes-1.17.13.spec
  SPECS/kubernetes/kubernetes-1.18.10.signatures.json
  SPECS/kubernetes/kubernetes-1.18.10.spec
  SPECS/kubernetes/kubernetes-1.18.8.signatures.json
  SPECS/kubernetes/kubernetes-1.18.8.spec
  SPECS/kubernetes/kubernetes-1.19.1.spec
Labels: Packaging, ptest

#520 [dev] Provide valgrind-devel
  SPECS/valgrind/valgrind.spec
Labels: Packaging

#521 Fix libunistring test and skip strongswan
  SPECS/libunistring/libunistring.spec
  toolkit/resources/manifests/package/macros.override
Labels: ptest

#480 [2/5 verity read-only root] Support validating packages during config check
  toolkit/scripts/imggen.mk
  toolkit/scripts/pkggen.mk
  toolkit/scripts/srpm_pack.mk
  toolkit/tools/imageconfigvalidator/imageconfigvalidator.go
  toolkit/tools/imageconfigvalidator/imageconfigvalidator_test.go
  toolkit/tools/imagegen/configuration/systemconfig.go
Labels: Tools

#525 Fix gettest test and correct typo to disable strongswan test
  SPECS/gettext/gettext.spec
  toolkit/resources/manifests/package/macros.override
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: ptest

#472 Add i.MX8mq-evk board support
  SPECS-SIGNED/kernel-signed-aarch64/kernel-signed-aarch64.spec
  SPECS-SIGNED/kernel-signed-x64/kernel-signed-x64.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#541 Fix ruby tests and disable asciidoc and ipv6calc tests
  SPECS/ruby/ruby.spec
  toolkit/resources/manifests/package/macros.override
Labels: ptest

#542 Fix openssl and python-ecdsa tests
  SPECS/openssl/openssl-1.1.1-ec-curves.patch
  SPECS/openssl/openssl-1.1.1-no-brainpool.patch
  SPECS/openssl/openssl.spec
  SPECS/python-ecdsa/disable_nist192_test.patch
  SPECS/python-ecdsa/python-ecdsa.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: ptest

#540 Update qmu-kvm CVE-2020-15469 to resolve QEMU bug
  SPECS/qemu-kvm/CVE-2020-15469.patch
  SPECS/qemu-kvm/qemu-kvm.spec
Labels: Packaging

#547 Fixing `Requires` cycles resolution across specs.
  toolkit/tools/grapher/grapher.go
Labels: Tools

#544 Fix test: mariadb
  SPECS/mariadb/mariadb.spec
Labels: Packaging, ptest

#550 Fix tests: chrony and ModemManager
  SPECS/ModemManager/ModemManager.spec
  SPECS/chrony/chrony.spec
Labels: Packaging

#551 Fix tests: cloud-init and python-pycurl
  SPECS/cloud-init/cloud-init.spec
  SPECS/python-pycurl/python-pycurl.spec
Labels: Packaging, ptest

#545 kubernetes: build RPM for containers and build containers
  SPECS/kubernetes/kubernetes-1.17.11.spec
  SPECS/kubernetes/kubernetes-1.17.13.spec
  SPECS/kubernetes/kubernetes-1.18.10.spec
  SPECS/kubernetes/kubernetes-1.18.8.spec
  SPECS/kubernetes/kubernetes-1.19.1.spec
  SPECS/kubernetes/kubernetes-1.19.3.spec
  toolkit/scripts/kubernertes-container/CreateContainerImages.sh
  toolkit/scripts/kubernertes-container/Dockerfile-Distroless
  toolkit/scripts/kubernertes-container/InstallComponentsBase.sh
Labels: Packaging

#553 Update prerequisites.md
  toolkit/docs/building/prerequisites.md
Labels: documentation

#554 Moving "Provides: pkgconfig(*)" for "libpng" to correct subpackage.
  SPECS/libpng/libpng.spec
Labels: Packaging

#556 kubernetes: apply hotfixes for 1.19.3, 1.18.10 and 1.17.13 and fix container script
  SPECS/kubernetes/kubernetes-1.17.13.signatures.json
  SPECS/kubernetes/kubernetes-1.17.13.spec
  SPECS/kubernetes/kubernetes-1.18.10.signatures.json
  SPECS/kubernetes/kubernetes-1.18.10.spec
  SPECS/kubernetes/kubernetes-1.19.3.signatures.json
  SPECS/kubernetes/kubernetes-1.19.3.spec
  cgmanifest.json
  toolkit/scripts/kubernertes-container/CreateContainerImages.sh
Labels: Packaging

#552 Update sudo package to 1.9.5p1
  SPECS/sudo/sudo.signatures.json
  SPECS/sudo/sudo.spec
  cgmanifest.json
Labels: Packaging

#555 Remove RubyGem Source File
  SPECS/rubygem-fluentd/SOURCES/fluentd-1.11.0.gem
  SPECS/rubygem-rdkafka/SOURCES/rdkafka-0.7.0.gem
Labels: Packaging

#561 Fix tests for swig, remove unreliable memtest from python-pycurl
  SPECS/python-pycurl/python-pycurl.spec
  SPECS/swig/swig.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, ptest

#560 Patch python-cryptography CVE-2020-25659
  SPECS/python-cryptography/CVE-2020-25659.patch
  SPECS/python-cryptography/python-cryptography.spec
Labels: Packaging

#564 Fix check tests for coreutils and bc
  SPECS/bc/bc.spec
  SPECS/coreutils/coreutils.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, ptest

#565 Extending `mariner-repos`.
  SPECS/mariner-repos/mariner-repos.signatures.json
  SPECS/mariner-repos/mariner-repos.spec
  SPECS/mariner-repos/mariner-ui-preview.repo
  SPECS/mariner-repos/mariner-ui.repo
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#568 WALinuxAgent change log directory
  SPECS/WALinuxAgent/WALinuxAgent.spec
Labels: Packaging

#570 Fix check tests for: gnutls
  SPECS/gnutls/gnutls.spec
Labels: Packaging, ptest

#572 [dev] Update lsblk json contract in go tools to match updated version
  toolkit/tools/imagegen/diskutils/diskutils.go
Labels: Tools

#574 Fix check tests: acl, mercurial, nss, perl-IO-Socket-SSL
  SPECS/acl/acl.spec
  SPECS/mercurial/mercurial.spec
  SPECS/nss/nss.spec
  SPECS/perl-IO-Socket-SSL/perl-IO-Socket-SSL.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, ptest

#558 Script to cross compile GCC for aarch64-linux
  toolkit/scripts/toolchain/cross/gcc_cross.sh
  toolkit/scripts/toolchain/cross/pathmax.patch
Labels: Tools

#579 Fixes CVE-2021-3177 in Python 3
  SPECS/python3/CVE-2021-3177.patch
  SPECS/python3/python3.spec
Labels: Packaging
