Repository microsoft/azurelinux, pull requests merged in 2021-02, with the labels that each got.

#582 [dev] Fix mutex usage in scheduler
  toolkit/tools/scheduler/scheduler.go
  toolkit/tools/scheduler/schedulerutils/buildworker.go
  toolkit/tools/scheduler/schedulerutils/depsolver.go
  toolkit/tools/scheduler/schedulerutils/preparerequest.go
  toolkit/tools/scheduler/schedulerutils/printresults.go
Labels: Tools

#586 Fixing changelog entries and license mapping.
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/coredns/coredns-1.6.5.spec
  SPECS/coredns/coredns-1.6.7.spec
  SPECS/coredns/coredns-1.7.0.spec
  SPECS/flannel/flannel.spec
  SPECS/kubernetes/kubernetes-1.17.13.spec
  SPECS/kubernetes/kubernetes-1.17.16.spec
  SPECS/kubernetes/kubernetes-1.18.10.spec
  SPECS/kubernetes/kubernetes-1.18.14.spec
  SPECS/kubernetes/kubernetes-1.19.3.spec
  SPECS/kubernetes/kubernetes-1.19.6.spec
Labels: Packaging

#588 Pick Python and CVE fixes to 1.0
  SPECS/python3/CVE-2021-3177.patch
  SPECS/python3/python3.spec
Labels: Packaging

#587 kernel: enable REED_SOLOMON_DEC8
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
Labels: Packaging

#590 Fix td-agent installation
  SPECS/td-agent/td-agent.spec
Labels: Packaging

#594 [dev] Use dependency graph to calculate RPMs from an SRPM
  toolkit/tools/internal/rpm/rpm.go
  toolkit/tools/scheduler/schedulerutils/buildworker.go
  toolkit/tools/scheduler/schedulerutils/prebuilt.go
  toolkit/tools/specreader/specreader.go
Labels: Tools

#592 Add package "dracut-fips"
  SPECS/dracut/disable-tcrypt-check-dracut-fips.patch
  SPECS/dracut/dracut.spec
  SPECS/initramfs/initramfs.spec
Labels: Packaging

#597 [dev] Add Provides net-snmp-utils
  SPECS/net-snmp/net-snmp.spec
Labels: Packaging

#598 Use OpenSSL to perform hmac in libkcapi
  SPECS/libkcapi/libkcapi.spec
Labels: Packaging

#599 Add CONFIG_CRYPTO_STATS line in kernel configs
  SPECS/kernel-hyperv/config
  SPECS/kernel-hyperv/kernel-hyperv.signatures.json
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
Labels: Packaging

#602 Update golang changelog entry
  SPECS/golang/golang-1.15.spec
Labels: Packaging

#605 [dev] Fix runtime requirement for cppunit-devel
  SPECS/cppunit/cppunit.spec
Labels: Packaging

#617 Add sha512hmac-openssl to kernel-hyperv source
  SPECS/kernel-hyperv/kernel-hyperv.spec
Labels: Packaging

#600 [cross]Add busybox container script
  toolkit/scripts/toolchain/cross/Dockerfile
  toolkit/scripts/toolchain/cross/busybox_container.sh
Labels: Tools

#589 Script to cross compile busybox
  toolkit/scripts/toolchain/cross/busybox.patch
  toolkit/scripts/toolchain/cross/busybox_cross.sh
Labels: Tools

#620 Correctly format output for sha512hmac in kernel hmac calculation
  SPECS/kernel-hyperv/kernel-hyperv.signatures.json
  SPECS/kernel-hyperv/kernel-hyperv.spec
  SPECS/kernel-hyperv/sha512hmac-openssl.sh
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  SPECS/kernel/sha512hmac-openssl.sh
Labels: Packaging

#621 [cross] use sysroot for busybox and container
  toolkit/scripts/toolchain/cross/Dockerfile
  toolkit/scripts/toolchain/cross/busybox_container.sh
  toolkit/scripts/toolchain/cross/busybox_cross.sh
  toolkit/scripts/toolchain/cross/gcc_cross.sh
Labels: Tools

#624 create etcd, coredns and flannel containers
  toolkit/scripts/kubernertes-container/CreateContainerImages.sh
Labels: Tools

#610 Use sysroot in cross build script
  toolkit/scripts/toolchain/cross/Dockerfile
  toolkit/scripts/toolchain/cross/busybox.patch
  toolkit/scripts/toolchain/cross/busybox_container.sh
  toolkit/scripts/toolchain/cross/busybox_cross.sh
  toolkit/scripts/toolchain/cross/gcc_cross.sh
  toolkit/scripts/toolchain/cross/pathmax.patch
Labels: Tools

#622 [cross] add basic kernel cross compile script
  toolkit/scripts/toolchain/cross/kernel_cross.sh
Labels: Tools

#618 Add patch for qemu CVE-2020-17380
  SPECS/qemu-kvm/CVE-2020-17380.patch
  SPECS/qemu-kvm/qemu-kvm.spec
Labels: Packaging

#627 [cross] Add cross aware binutils package
  SPECS-CROSS/binutils_cross/binutils_cross.signatures.json
  SPECS-CROSS/binutils_cross/binutils_cross.spec
Labels: Tools

#632 [dev] Update httpd and nginx
  SPECS/httpd/httpd.spec
  SPECS/nginx/nginx.spec
Labels: Packaging

#629 Update mysql to version 8.0.23 for CVE-2020-15358
  SPECS/mysql/mysql.signatures.json
  SPECS/mysql/mysql.spec
  cgmanifest.json
Labels: Packaging

#639 [dev] Remove duplicate distribution tag from python-jwt
  SPECS/python-jwt/python-jwt.spec
Labels: Packaging

#628 [cross] create minimal aarch64 image that boots in qemu
  toolkit/scripts/toolchain/cross/generate_minimal_rootfs.sh
  toolkit/scripts/toolchain/cross/inittab
  toolkit/scripts/toolchain/cross/kernel_cross.sh
  toolkit/scripts/toolchain/cross/launch_qemu.sh
Labels: Tools

#642 [dev] Fix incorrect lib macro usage in net-snmp
  SPECS/net-snmp/net-snmp.spec
Labels: Packaging

#644 quickstart: update git clone to use https
  toolkit/docs/quick_start/quickstart.md
Labels: documentation

#638 Add GCC compile.exp tests
  toolkit/scripts/toolchain/cross/gcc_cross_test.sh
Labels: Tools

#649 [dev] Rework cycle detection in dependency graph to scale with larger graphs
  toolkit/tools/grapher/grapher.go
  toolkit/tools/internal/pkggraph/cyclefind.go
  toolkit/tools/internal/pkggraph/cyclefind_test.go
  toolkit/tools/internal/pkggraph/pkggraph.go
Labels: Tools

#648 Update default sudo config
  SPECS/sudo/sudo.spec
Labels: Packaging

#650 [cross] GCC emulation tests
  toolkit/scripts/toolchain/cross/aarch64-linux-gnu.xfail
  toolkit/scripts/toolchain/cross/gcc_cross_test.sh
Labels: Tools

#658 Fix python-sqlalchemy test
  SPECS/python-sqlalchemy/python-sqlalchemy.spec
Labels: Packaging, ptest

#656 Fix CVE-2020-35498 in openvswitch
  SPECS/openvswitch/CVE-2020-35498.patch
  SPECS/openvswitch/openvswitch.spec
Labels: Packaging

#655 Add speakup support to kernel
  SPECS-SIGNED/kernel-signed-aarch64/kernel-signed-aarch64.spec
  SPECS-SIGNED/kernel-signed-x64/kernel-signed-x64.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#668 Tweak installer to meet accessibility standards
  toolkit/tools/cgmanifest.json
  toolkit/tools/go.mod
  toolkit/tools/go.sum
  toolkit/tools/imagegen/attendedinstaller/attendedinstaller.go
  toolkit/tools/imagegen/attendedinstaller/primitives/progressbar/progressbar.go
  toolkit/tools/imagegen/attendedinstaller/speakuputils/speakuputils.go
  toolkit/tools/imagegen/attendedinstaller/uitext/uitext.go
  toolkit/tools/imagegen/attendedinstaller/views/diskview/manualpartitionwidget/manualpartitionwidget.go
Labels: Tools

#646 linux-firmware: Add bnx2x and qed firmware, WHENCE, and license files
  SPECS/linux-firmware/linux-firmware.spec
Labels: Packaging

#671 Update signatures for espeakup and kernel,
  SPECS/espeakup/espeakup.signatures.json
  SPECS/kernel/kernel.signatures.json
  SPECS/pcaudiolib/pcaudiolib.spec
Labels: Packaging

#673 Fixing `ntopng` source URLs.
  SPECS/ntopng/ntopng.spec
Labels: Packaging

#670 openldap: fix CVE-2021-27212
  SPECS/openldap/CVE-2021-27212.patch
  SPECS/openldap/openldap.spec
Labels: Packaging
