Repository microsoft/azurelinux, pull requests merged in 2021-10, with the labels that each got.

#1473 [dev] `clang`: splitting into subpackages and adding extra tools subpackages
  SPECS/clang/clang.signatures.json
  SPECS/clang/clang.spec
Labels: Packaging

#1481 Add no patches for qt5-qtsvg
  SPECS/qt5-qtsvg/CVE-2018-21035.nopatch
  SPECS/qt5-qtsvg/CVE-2021-38593.nopatch
  SPECS/qt5-qtsvg/qt5-qtsvg.spec
Labels: Packaging

#1479 [dev] Add ipset service subpackage
  SPECS/ipset/ipset.service
  SPECS/ipset/ipset.signatures.json
  SPECS/ipset/ipset.spec
  SPECS/ipset/ipset.start-stop
  SPECS/iptables/iptables.spec
Labels: Packaging

#1482 [dev] Fix SRPM re-expansion detection logic
  toolkit/scripts/srpm_expand.mk
Labels: Tools

#1489 update documentation to cover building on mariner
  toolkit/docs/building/prerequisites-mariner.md
  toolkit/docs/building/prerequisites-ubuntu.md
  toolkit/docs/building/prerequisites.md
Labels: documentation

#1490 [dev] `systemd`: removing incorrect `Provides` and changing `libinput` BR.
  SPECS/libinput/libinput.spec
  SPECS/systemd/systemd.spec
Labels: Packaging

#1492 Fix moby-containerd CVE-2021-41103
  SPECS/moby-containerd/CVE-2021-41103.patch
  SPECS/moby-containerd/moby-containerd.spec
Labels: Packaging

#1495 Fix moby-engine CVE-2021-41091 CVE-2021-41089
  SPECS/moby-engine/CVE-2021-41089.patch
  SPECS/moby-engine/CVE-2021-41091.patch
  SPECS/moby-engine/moby-engine.spec
Labels: Packaging

#1493 Fix moby-containerd CVE-2021-41103 (#1492)
  SPECS/moby-containerd/CVE-2021-41103.patch
  SPECS/moby-containerd/moby-containerd.spec
Labels: Packaging

#1496 Fix moby-engine CVE-2021-41091 CVE-2021-41089 (#1495)
  SPECS/moby-engine/CVE-2021-41089.patch
  SPECS/moby-engine/CVE-2021-41091.patch
  SPECS/moby-engine/moby-engine.spec
Labels: Packaging

#1497 [dev] Fix moby-engine CVE-2021-41091 CVE-2021-41089
  SPECS/moby-engine/CVE-2021-41089.patch
  SPECS/moby-engine/CVE-2021-41091.patch
  SPECS/moby-engine/moby-engine.spec
Labels: Packaging

#1503 Fix grpc-devel file conflict (dev branch)
  SPECS/grpc/grpc.spec
Labels: Packaging

#1515 Fixing no `ExclusiveArch` tag case
  toolkit/tools/internal/rpm/rpm.go
  toolkit/tools/internal/rpm/rpm_test.go
  toolkit/tools/internal/rpm/testdata/no_exclusive_architecture.spec
  toolkit/tools/specreader/specreader.go
  toolkit/tools/srpmpacker/srpmpacker.go
Labels: Tools

#1514 [dev]: Adding tests for `ExclusiveArch` parsing from #1511
  toolkit/scripts/toolchain/check_manifests.sh
  toolkit/tools/internal/rpm/rpm.go
  toolkit/tools/internal/rpm/rpm_test.go
  toolkit/tools/internal/rpm/testdata/no_exclusive_architecture.spec
  toolkit/tools/internal/rpm/testdata/supported_unsupported_architectures.spec
  toolkit/tools/internal/rpm/testdata/unsupported_architectures.spec
Labels: Tools

#1547 [dev] Restoring `brp-*` scripts in `rpm-build`
  SPECS/rpm/rpm.spec
Labels: Packaging

#1548 [dev] `powershell`: moving source extraction to the `%install` section
  SPECS/powershell/powershell.spec
Labels: Packaging

#1526 [1.0] openscap: Add dbus BuildRequire to oscap package
  SPECS/openscap/openscap.spec
Labels: Packaging

#1555 openscap: Update to 1.3.2
  SPECS/openscap/openscap.signatures.json
  SPECS/openscap/openscap.spec
  cgmanifest.json
Labels: Packaging
