Repository microsoft/azurelinux, pull requests merged in 2022-10, with the labels that each got.

#3883 Add git-lfs and move rubygem-ronn dependencies to SPECS
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/git-lfs/git-lfs.signatures.json
  SPECS/git-lfs/git-lfs.spec
  SPECS/rubygem-hpricot/rubygem-hpricot.signatures.json
  SPECS/rubygem-hpricot/rubygem-hpricot.spec
  SPECS/rubygem-mustache/rubygem-mustache-1.1.1-Fix-test-race-condition.patch
  SPECS/rubygem-mustache/rubygem-mustache.signatures.json
  SPECS/rubygem-mustache/rubygem-mustache.spec
  SPECS/rubygem-rdiscount/rubygem-rdiscount.signatures.json
  SPECS/rubygem-rdiscount/rubygem-rdiscount.spec
  SPECS/rubygem-ronn/rubygem-ronn.signatures.json
  SPECS/rubygem-ronn/rubygem-ronn.spec
  cgmanifest.json
Labels: main

#3882 vim: upgrade to version 9.0.0598
  SPECS/vim/vim.signatures.json
  SPECS/vim/vim.spec
  cgmanifest.json
Labels: security, main

#3874 Add CVE-2022-2962 nopatch file to QEMU
  SPECS/qemu-kvm/0001-removed-tulip.c-from-build-process-due-to-CVE-2022-2962.patch
  SPECS/qemu-kvm/CVE-2022-2962.nopatch
  SPECS/qemu-kvm/qemu-kvm.spec
Labels: security, Packaging, 1.0-dev

#3888 kernel: Address CVE-2022-1204, CVE-2022-1882, CVE-2022-1973, CVE-2022-2503, CVE-2022-2785, CVE-2022-2873, CVE-2022-2991, CVE-2022-33743, CVE-2022-33744, CVE-2022-36946
  SPECS/kernel/CVE-2022-1204.nopatch
  SPECS/kernel/CVE-2022-1882.nopatch
  SPECS/kernel/CVE-2022-1973.nopatch
  SPECS/kernel/CVE-2022-2503.nopatch
  SPECS/kernel/CVE-2022-2785.nopatch
  SPECS/kernel/CVE-2022-2873.nopatch
  SPECS/kernel/CVE-2022-2991.nopatch
  SPECS/kernel/CVE-2022-33743.nopatch
  SPECS/kernel/CVE-2022-33744.nopatch
  SPECS/kernel/CVE-2022-36946.nopatch
Labels: security, Packaging, 1.0-dev

#3879 address CVE-2022-39227
  SPECS/python-jwt/CVE-2022-39227.nopatch
  SPECS/python-jwt/python-jwt.spec
Labels: security, Packaging, main

#3889 libbpf: bump version to 1.0.1
  SPECS/libbpf/libbpf.signatures.json
  SPECS/libbpf/libbpf.spec
  cgmanifest.json
Labels: main

#3911 python3: patch CVE-2015-20107.
  SPECS/python3/CVE-2015-20107.patch
  SPECS/python3/python3.spec
Labels: security, Packaging, 1.0-dev

#3890 Add support for blobfuse2
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/blobfuse2/blobfuse2.signatures.json
  SPECS/blobfuse2/blobfuse2.spec
  cgmanifest.json
Labels: main

#3863 kernel-uvm: move to SPECS-EXTENDED
  SPECS-EXTENDED/kernel-uvm/config
  SPECS-EXTENDED/kernel-uvm/kernel-uvm.signatures.json
  SPECS-EXTENDED/kernel-uvm/kernel-uvm.spec
Labels: main

#3860 kernel-mshv: move from SPECS to SPECS-EXTENDED
  SPECS-EXTENDED/kernel-mshv/cbl-mariner-ca-20211013.pem
  SPECS-EXTENDED/kernel-mshv/config
  SPECS-EXTENDED/kernel-mshv/kernel-mshv.signatures.json
  SPECS-EXTENDED/kernel-mshv/kernel-mshv.spec
Labels: main

#3894 Move bind server config files to base package from utils package
  SPECS/bind/bind.spec
Labels: Packaging, main

#3915 Add runtime requirement on iana-etc to fping
  SPECS/fping/fping.spec
Labels: Packaging, 1.0-dev

#3780 kata : add patch to avoid memory hotplug timeout, fix systemd service
  SPECS/kata-containers/0005-Merged-PR-9956-shim-avoid-memory-hotplug-timeout.patch
  SPECS/kata-containers/kata-containers.signatures.json
  SPECS/kata-containers/kata-containers.spec
  SPECS/kata-containers/kata-osbuilder.sh
Labels: Packaging, main

#3887 livepatch spec generation: unifying naming with other core specs
  toolkit/scripts/livepatching/generate_livepatch-signed_spec.sh
  toolkit/scripts/livepatching/generate_livepatch_spec.sh
  toolkit/scripts/livepatching/template_livepatch.spec
  toolkit/scripts/livepatching/update_livepatches.sh
Labels: Tools, main

#3926 Upgrade wayland to 1.21.0 to fix CVE-2021-3782
  SPECS/wayland/wayland.signatures.json
  SPECS/wayland/wayland.spec
  cgmanifest.json
Labels: main

#3928 python2: patch CVE-2015-20107.
  SPECS/python2/CVE-2015-20107.patch
  SPECS/python2/python2.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#3936 Add large file support to unzip
  SPECS/unzip/CVE-2008-0888.nopatch
  SPECS/unzip/unzip.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3922 dracut, systemd, systemtap: fix log file paths.
  SPECS/dracut/dracut.spec
  SPECS/systemd/systemd-bootstrap.spec
  SPECS/systemd/systemd.spec
  SPECS/systemtap/systemtap.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3931 cryptsetup: update v2.3.7 to fix CVE-2021-4122
  SPECS/cryptsetup/cryptsetup.signatures.json
  SPECS/cryptsetup/cryptsetup.spec
  cgmanifest.json
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, 1.0-dev

#3929 fix CVE-2021-3975
  SPECS/libvirt/CVE-2021-3975.patch
  SPECS/libvirt/libvirt.spec
Labels: security, Packaging, 1.0-dev

#3945 Bump Mariner Release number for October 2022 Update
  SPECS/mariner-release/mariner-release.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#3937 Add python-astunparse package to Mariner
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/python-astunparse/python-astunparse.signatures.json
  SPECS/python-astunparse/python-astunparse.spec
  SPECS/python-astunparse/python3.9.patch
  cgmanifest.json
Labels: main

#3943 Patch gnutls to fix CVE-2021-4209
  SPECS/gnutls/CVE-2021-4209.patch
  SPECS/gnutls/gnutls.spec
Labels: security, Packaging, 1.0-dev

#3944 Patch libtiff to fix CVE 2022 2953
  SPECS/libtiff/CVE-2022-2953.patch
  SPECS/libtiff/libtiff.spec
Labels: security, Packaging, 1.0-dev

#3951 python-absl-py, python-astunparse: adding missing spec tags + clean-up.
  SPECS/python-absl-py/python-absl-py.spec
  SPECS/python-astunparse/python-astunparse.spec
Labels: Packaging, main

#3950 mariner_release: bumping version for October release.
  SPECS/mariner-release/mariner-release.spec
Labels: Packaging, main

#3920 Fix cloud-init mariner variant not set properly
  SPECS/cloud-init/add-mariner-distro-support.patch
  SPECS/cloud-init/cloud-init.spec
Labels: Packaging, main

#3952 add libyang 2 to mariner SPECs
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/libyang/libyang.signatures.json
  SPECS/libyang/libyang.spec
  cgmanifest.json
Labels: main

#3918 Overwrite 99-dhcp-en.network for marketplace img
  toolkit/imageconfigs/additionalconfigs/configure-image.sh
Labels: Schema, 1.0-dev

#3965 Resolve terraform CVE-2021-36230
  SPECS/terraform/CVE-2018-9057.nopatch
  SPECS/terraform/terraform.signatures.json
  SPECS/terraform/terraform.spec
  cgmanifest.json
Labels: main

#3919 Add Instruction to filter gpg-pubkey from rpm cmd's output.
  toolkit/docs/how_it_works/5_misc.md
Labels: documentation, main

#3974 sos: patch CVE-2022-2806
  SPECS/sos/CVE-2022-2806.patch
  SPECS/sos/sos.spec
Labels: Packaging, 1.0-dev

#3775 Create missing systemd accounts
  SPECS/filesystem/filesystem.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#4002 Resolve unbound CVE-2022-3204
  SPECS/unbound/unbound.signatures.json
  SPECS/unbound/unbound.spec
  cgmanifest.json
Labels: main

#4006 maven.spec: using macro instead of hard-coded source URL.
  SPECS/maven/maven.spec
Labels: Packaging, main

#4022 Mitigation fix for attended ionstallation regression
  toolkit/tools/imagegen/attendedinstaller/views/diskview/manualpartitionwidget/manualpartitionwidget.go
Labels: Tools, main

#4024 Support Mariner 1.0 build on Mariner 2.0 host
  toolkit/tools/pkggen/worker/create_worker_chroot.sh
Labels: Tools, 1.0-dev

#4025 [2.0] Rebuild worker chroot rpm db only when necessary
  toolkit/tools/pkggen/worker/create_worker_chroot.sh
Labels: Tools, main

#4028 Resolve aspell CVE-2019-25051
  SPECS/aspell/CVE-2019-25051.patch
  SPECS/aspell/aspell.spec
Labels: security, Packaging, main

#3954 livepatch: updating macros and template to preserve signatures.
  .github/workflows/validate-cg-manifest.sh
  SPECS/mariner-rpm-macros/macros
  SPECS/mariner-rpm-macros/mariner-rpm-macros.signatures.json
  SPECS/mariner-rpm-macros/mariner-rpm-macros.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/livepatching/template_livepatch-signed.spec
Labels: main

#3963 livepatch: CVE-2022-34918, kernel 5.15.48.1-4.cm2
  SPECS-SIGNED/livepatch-5.15.48.1-4.cm2-signed/livepatch-5.15.48.1-4.cm2-signed.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/livepatch-5.15.48.1-4.cm2/CVE-2022-34918.patch
  SPECS/livepatch-5.15.48.1-4.cm2/config-5.15.48.1-4.cm2
  SPECS/livepatch-5.15.48.1-4.cm2/livepatch-5.15.48.1-4.cm2.signatures.json
  SPECS/livepatch-5.15.48.1-4.cm2/livepatch-5.15.48.1-4.cm2.spec
  SPECS/livepatch-5.15.48.1-4.cm2/mariner-5.15.48.1-4.cm2.pem
  cgmanifest.json
Labels: main

#4026 1.0 toolkit: skip ARCHIVE_TOOL on extraction
  toolkit/scripts/pkggen.mk
  toolkit/scripts/toolchain.mk
Labels: Tools, 1.0-dev

#4027 Add logrotate conf entry for rsyslog to prevent logs growing too large
  SPECS/rsyslog/rsyslog.conf
  SPECS/rsyslog/rsyslog.logrotate
  SPECS/rsyslog/rsyslog.signatures.json
  SPECS/rsyslog/rsyslog.spec
Labels: Packaging, 1.0-dev

#4023 Add logrotate conf entry for rsyslog to prevent logs growing too large
  SPECS/rsyslog/rsyslog.logrotate
  SPECS/rsyslog/rsyslog.signatures.json
  SPECS/rsyslog/rsyslog.spec
Labels: Packaging, main

#4030 Fix gpg key import in worker chroot
  toolkit/tools/pkggen/worker/create_worker_chroot.sh
Labels: Tools, main

#4041 Fix rsyslog.logrotate signature
  SPECS/rsyslog/rsyslog.signatures.json
Labels: Packaging, main

#4038 Remove autodetected Go modules in toolkit/tools/cgmanifest.json
  .github/pull_request_template.md
  toolkit/tools/cgmanifest.json
Labels: Tools, main

#4031 qemu: nopatch CVE-2022-26354
  SPECS/qemu-kvm/CVE-2022-26354.nopatch
  SPECS/qemu-kvm/qemu-kvm.spec
Labels: Packaging, 1.0-dev

#4034 Revert TokyoCabinet URL; Upgrade Tidy to 5.8.0; Remove 'ming' from SPECS-EXTENDED
  .github/workflows/validate-cg-manifest.sh
  SPECS-EXTENDED/ming/ming-multilib.patch
  SPECS-EXTENDED/ming/ming-parallel-make.patch
  SPECS-EXTENDED/ming/ming-perl.patch
  SPECS-EXTENDED/ming/ming-pr145.patch
  SPECS-EXTENDED/ming/ming-version.patch
  SPECS-EXTENDED/ming/ming.signatures.json
  SPECS-EXTENDED/ming/ming.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/tidy/tidy.signatures.json
  SPECS/tidy/tidy.spec
  SPECS/tokyocabinet/tokyocabinet.spec
  cgmanifest.json
Labels: main

#4042 cpptest: add package version 1.1.2
  SPECS-EXTENDED/cpptest/cpptest.signatures.json
  SPECS-EXTENDED/cpptest/cpptest.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4052 Add krb5.conf to resolve pam_krb5 ptest failure
  SPECS/krb5/krb5.conf
  SPECS/krb5/krb5.signatures.json
  SPECS/krb5/krb5.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: ptest, main

#4045 Add python package python-google-auth-oauthlib and move its extended dependencies to the core
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/python-click/python-click.signatures.json
  SPECS/python-click/python-click.spec
  SPECS/python-google-auth-oauthlib/python-google-auth-oauthlib.signatures.json
  SPECS/python-google-auth-oauthlib/python-google-auth-oauthlib.spec
  SPECS/python-requests-oauthlib/python-requests-oauthlib.signatures.json
  SPECS/python-requests-oauthlib/python-requests-oauthlib.spec
  cgmanifest.json
Labels: main

#4037 Update kernel-rt config to build with new glibc-static changes
  SPECS-EXTENDED/kernel-rt/config
  SPECS-EXTENDED/kernel-rt/kernel-rt.signatures.json
Labels: main

#4032 Move wireless-regdb and iw to Mariner core repo to resolve failure to load regulatory.db
  SPECS-EXTENDED/iw/iw.signatures.json
  SPECS/iw/iw.signatures.json
  SPECS/iw/iw.spec
  SPECS/wireless-regdb/85-regulatory.rules
  SPECS/wireless-regdb/setregdomain
  SPECS/wireless-regdb/setregdomain.1
  SPECS/wireless-regdb/wireless-regdb.signatures.json
  SPECS/wireless-regdb/wireless-regdb.spec
  cgmanifest.json
  toolkit/imageconfigs/packagelists/azurevm-packages.json
Labels: main

#4021 dbus: add provides `dbus-x11` & drop metapackage
  SPECS-EXTENDED/dbus-x11/dbus-x11.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/dbus/dbus.spec
  toolkit/scripts/check_entangled_specs.py
Labels: main, specs-extended

#4046 Fix chroot cleanup scripts
  toolkit/scripts/pkggen.mk
  toolkit/scripts/toolkit.mk
Labels: Tools, main

#4053 Fix SPEC file import information from CentOS as MIT
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
Labels: Packaging, main

#4060 Update documentation with 2.0 related information and misc. fixes
  README.md
  toolkit/docs/building/building.md
  toolkit/docs/how_it_works/0_intro.md
Labels: main

#4065 Update Mariner 1.0 Release for October 2022 Update 2
  SPECS/mariner-release/mariner-release.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#4019 add Microsoft GPG keys to installer env
  toolkit/resources/imageconfigs/packagelists/iso-initrd-packages.json
Labels: main

#4073 patch 1.0 - CVE-2022-3570 for vuln. in libtiff package
  SPECS/libtiff/CVE-2022-3570.patch
  SPECS/libtiff/libtiff.spec
Labels: Packaging, 1.0-dev

#4043 libcroco: add package version 0.6.13
  SPECS-EXTENDED/libcroco/libcroco.signatures.json
  SPECS-EXTENDED/libcroco/libcroco.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4082 Revert "[AUTOPATCHER-CORE] nodejs upgrade to version 16.17.1 - CVE-2022-32213 - "
  SPECS/nodejs/nodejs.signatures.json
  SPECS/nodejs/nodejs.spec
  cgmanifest.json
Labels: main

#4074 Updated 4 `rubygem-*` packages to obsolete older versions of `ruby`.
  SPECS/rubygem-minitest/rubygem-minitest.spec
  SPECS/rubygem-power_assert/rubygem-power_assert.spec
  SPECS/rubygem-rake/rubygem-rake.spec
  SPECS/rubygem-test-unit/rubygem-test-unit.spec
Labels: Packaging, main

#4085 Support Mariner 1.0 build on Mariner 2.0 host (#4024)
  toolkit/tools/pkggen/worker/create_worker_chroot.sh
Labels: Tools

#4088 Updating `libtasn1` to 4.19.0 to fix CVE-2021-46848.
  SPECS/libtasn1/libtasn1.signatures.json
  SPECS/libtasn1/libtasn1.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#4087 Upgrading `nodejs` to version 16.17.1.
  SPECS/nodejs/nodejs.signatures.json
  SPECS/nodejs/nodejs.spec
  cgmanifest.json
Labels: main

#4089 Change npm_version to 8.15.0 to reflect the actual version of npm bun…
  SPECS/nodejs/nodejs.spec
Labels: Packaging, main

#4091 Updated `mariner-release` for October update.
  SPECS/mariner-release/mariner-release.spec
Labels: Packaging, main

#4096 Fix manifest checks with RPM 4.18
  toolkit/scripts/toolchain/check_manifests.sh
Labels: Tools, main

#4005 Adding sriov-network-device-plugin spec file
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/sriov-network-device-plugin/sriov-network-device-plugin.signatures.json
  SPECS/sriov-network-device-plugin/sriov-network-device-plugin.spec
  cgmanifest.json
Labels: main

#4101 NoPatches kernel to fix CVE-2022-3541, CVE-2022-3544
  SPECS/kernel/CVE-2022-3541.nopatch
  SPECS/kernel/CVE-2022-3544.nopatch
Labels: security, Packaging, main

#4107 [main] Add kernel-drivers-gpu package
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/hyperv-daemons/hyperv-daemons.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#4108 Updated ptests to use a specific version of 'pytest'.
  SPECS/python-cffi/python-cffi.spec
  SPECS/python-execnet/python-execnet.spec
  SPECS/python-pytest-forked/python-pytest-forked.spec
  SPECS/python-pytest-mock/python-pytest-mock.spec
Labels: Packaging, main

#4113 cairomm: add package version 1.12.0
  SPECS-EXTENDED/cairomm/cairomm.signatures.json
  SPECS-EXTENDED/cairomm/cairomm.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4109 Add obsoletes between qemu-common, qemu-virtiofsd
  SPECS/qemu/qemu.spec
Labels: Packaging, main

#4115 NoPatch Kernel to fix CVE-2022-3541, CVE-2022-3543, CVE-2022-3544, CVE-2022-3595
  SPECS/kernel/CVE-2022-3541.nopatch
  SPECS/kernel/CVE-2022-3543.nopatch
  SPECS/kernel/CVE-2022-3544.nopatch
  SPECS/kernel/CVE-2022-3595.nopatch
Labels: security, Packaging, 1.0-dev

#4117 libtar: add nopatches for CVE-2021-33644 and CVE-2021-33646
  SPECS/libtar/CVE-2021-33644.nopatch
  SPECS/libtar/CVE-2021-33646.nopatch
Labels: security, Packaging, 1.0-dev

#4123 Updated test dependencies to increase stability.
  SPECS/perl-CGI/perl-CGI.spec
  SPECS/python-pytest-benchmark/python-pytest-benchmark.spec
  SPECS/python-requests/python-requests.spec
Labels: Packaging, main

#4097 include kexec-tools in marketplace image
  toolkit/imageconfigs/packagelists/azurevm-packages.json
Labels: Schema, main

#4112 libtasn1: patch CVE-2021-46848
  SPECS/libtasn1/CVE-2021-46848.patch
  SPECS/libtasn1/libtasn1.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#4122 Enable TCP Congestion Control modules
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#4079 Upgrade openssh to 8.9p1 to fix CVE-2021-36368
  SPECS/openssh/openssh.signatures.json
  SPECS/openssh/openssh.spec
  cgmanifest.json
Labels: 1.0-dev

#4126 redis: patch for CVE-2022-3647
  SPECS/redis/CVE-2022-3647.patch
  SPECS/redis/redis.spec
Labels: Packaging, main

#4075 Add nopatches for libtar cves CVE-2021-33644 CVE-2021-33646
  SPECS/libtar/CVE-2021-33644.nopatch
  SPECS/libtar/CVE-2021-33646.nopatch
Labels: security, Packaging, main

#4127 Upgrade cassandra version to 4.0.7
  SPECS-EXTENDED/cassandra/cassandra.signatures.json
  SPECS-EXTENDED/cassandra/cassandra.spec
  cgmanifest.json
Labels: main

#4128 [main] Revert nginx to stable version 1.22.1
  SPECS/nginx/nginx.signatures.json
  SPECS/nginx/nginx.spec
  cgmanifest.json
Labels: main

#4118 Disable apparmor LSM at boot time
  toolkit/imageconfigs/marketplace-gen1.json
  toolkit/imageconfigs/marketplace-gen2-aarch64.json
  toolkit/imageconfigs/marketplace-gen2.json
Labels: Schema, 1.0-dev

#4129 libtasn1: fix spec to actually apply patches
  SPECS/libtasn1/CVE-2021-46848.patch
  SPECS/libtasn1/libtasn1.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, 1.0-dev

#4134 Bumped `mariner-release` for the full October release.
  SPECS/mariner-release/mariner-release.spec
Labels: Packaging, main
