Repository microsoft/azurelinux, pull requests merged in 2022-01, with the labels that each got.

#1822 Add config to create qcow image
  toolkit/tools/roast/formats/qcow.go
  toolkit/tools/roast/roast.go
Labels: Tools

#1839 Avoid starting the `check-restart` service on reboot
  SPECS/check-restart/check-restart.service
  SPECS/check-restart/check-restart.signatures.json
  SPECS/check-restart/check-restart.spec
  SPECS/check-restart/check-restart.timer
Labels: Packaging

#1850 [main] iptables: Update to 1.8.7
  SPECS/iptables/iptables.signatures.json
  SPECS/iptables/iptables.spec
  cgmanifest.json
Labels: Packaging

#1826 [main] Making `qemu` build for ARM64.
  SPECS/qemu/qemu.spec
Labels: Packaging

#1847 [main] Replace generated dependencies on java-headless with java
  SPECS-EXTENDED/bsh/bsh.spec
  SPECS-EXTENDED/flute/flute.spec
  SPECS-EXTENDED/jakarta-commons-httpclient/jakarta-commons-httpclient.spec
  SPECS-EXTENDED/jss/jss.spec
  SPECS-EXTENDED/lasso/lasso.spec
  SPECS-EXTENDED/openmpi/openmpi.spec
  SPECS-EXTENDED/sblim-cim-client2/sblim-cim-client2.spec
  SPECS-EXTENDED/tomcat/tomcat.spec
  SPECS-EXTENDED/tomcatjss/tomcatjss.spec
  SPECS/javapackages-tools/javapackages-tools.spec
  SPECS/javapackages-tools/remove-epoch-from-java-requires.patch
  SPECS/javapackages-tools/remove-headless-from-java-requires.patch
  cgmanifest.json
Labels: Packaging

#1856 [1.0-dev] Make dstat use Python 3 and fix implicit dependencies
  SPECS/dstat/dstat.spec
  SPECS/dstat/fix-py3-deprecation-warning.patch
Labels: Packaging

#1862 [main] Update openldap configure flags to disable rpath
  SPECS/openldap/openldap.spec
Labels: Packaging

#1872 Fix broken link in docs/how_it_works/0_intro.md
  toolkit/docs/how_it_works/0_intro.md
Labels: documentation

#1864 [main] Fixing `libvirt` and `lvm2` builds.
  SPECS/libvirt/libvirt.spec
  SPECS/lvm2/lvm2.spec
  cgmanifest.json
Labels: Packaging

#1888 Fixed libgd test failures in 2.3.3
  SPECS/gd/gd.spec
Labels: Packaging

#1898 Upgrading Parted to v3.4
  SPECS/parted/parted.signatures.json
  SPECS/parted/parted.spec
  cgmanifest.json
Labels: Packaging

#1897 kernel: Address CVE-2021-45485
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel-hyperv/kernel-hyperv.spec
  SPECS/kernel/CVE-2021-45485.nopatch
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#1912 [main] Exclude module_info.ld from kernel-signed
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
Labels: Packaging

#1915 [main] installutils: Fix user ssh directory permissions when key empty
  toolkit/tools/imagegen/installutils/installutils.go
Labels: Tools

#1936 Fix package signatures
  SPECS/bash-completion/bash-completion.signatures.json
  SPECS/catch/catch.signatures.json
  SPECS/chkconfig/chkconfig.signatures.json
Labels: Packaging

#1881 Enable kernel to support building/installing Intel SGX Driver
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel-hyperv/kernel-hyperv.spec
  SPECS/kernel/0003-export-mmput_async.patch
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#1945 Skipping flaky `invalid_metadata` test.
  SPECS/mysql/mysql.spec
Labels: Packaging

#1956 chkconfig: mask check section which depends on beakerlibs
  SPECS/chkconfig/chkconfig.spec
Labels: Packaging

#1955 Fix moby-runc BuildRequires
  SPECS/moby-runc/moby-runc.spec
Labels: Packaging

#1962 [main] Optimize mount cleanup script
  toolkit/scripts/safeunmount.sh
Labels: Tools

#1975 Lua no patch for CVE-2021-43519 in Mariner 1.0
  SPECS/lua/CVE-2021-43519.nopatch
Labels: security

#1980 lttng-consume: disable tests to fix build break
  SPECS/lttng-consume/lttng-consume.spec
Labels: Packaging

#2003 Updating tool message.
  toolkit/scripts/license_map.py
Labels: Tools

#2013 [main] WALinuxAgent add python3-distro as Requires
  SPECS/WALinuxAgent/WALinuxAgent.spec
Labels: Packaging

#1999 [main] [core] iotop: Use python3 instead of python2
  SPECS/iotop/iotop-itervalues.patch
  SPECS/iotop/iotop-use-py3.patch
  SPECS/iotop/iotop.spec
Labels: Packaging

#2016 [2.0] Add python3-distro to azurevm-packages packagelist
  toolkit/imageconfigs/packagelists/azurevm-packages.json
Labels: Schema

#2019 [main] [core] Fix autofs packaging with regards to init directory
  SPECS/autofs/autofs.spec
Labels: Packaging

#2032 kernel-signed: workaround errant .build-id file
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
Labels: Packaging

#2039 [main] Adding a missing `return` in `pkggragh.go`.
  toolkit/tools/internal/pkggraph/pkggraph.go
Labels: Tools

#2040 [main] Fix graphviz build break and update libpq signature
  SPECS/graphviz/graphviz.spec
  SPECS/libpq/libpq.signatures.json
Labels: Packaging
