Repository microsoft/azurelinux, pull requests merged in 2022-12, with the labels that each got.

#4331 Update Blobfuse2 version to 2.0.0
  SPECS/blobfuse2/blobfuse2.signatures.json
  SPECS/blobfuse2/blobfuse2.spec
  cgmanifest.json
Labels: main

#4334 Enable http2 support in nginx
  SPECS/nginx/nginx.spec
Labels: Packaging, main

#4328 Fix incorrect systemd operation during image build
  toolkit/tools/imagegen/configuration/networkconfig.go
Labels: Tools, Schema, main

#4336 Patch `libarchive` for CVE-2022-36227
  SPECS/libarchive/CVE-2022-36227.patch
  SPECS/libarchive/libarchive.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, main

#4338 Patch `libarchive` for CVE-2022-36227
  SPECS/libarchive/CVE-2022-36227.patch
  SPECS/libarchive/libarchive.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, 1.0-dev

#4335 Patch libxml2 for CVE-2022-40303
  SPECS/libxml2/CVE-2022-40303.patch
  SPECS/libxml2/libxml2.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#4339 Update Mariner Release for December 2022 Update
  SPECS/mariner-release/mariner-release.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#4340 Update Mariner Release for December 2022 Update
  SPECS/mariner-release/mariner-release.spec
Labels: Packaging, main

#4280 Nopatch CVE-2022-40768 and CVE-2021-4037 for kernel
  SPECS/kernel/CVE-2021-4037.nopatch
  SPECS/kernel/CVE-2022-40768.nopatch
Labels: security, Packaging, 1.0-dev

#4344 Patch libxml2 for CVE-2022-40304
  SPECS/libxml2/CVE-2022-40304.patch
  SPECS/libxml2/libxml2.spec
Labels: Packaging, 1.0-dev

#4337 Add Tensorflow to CBL-Mariner
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/python-markdown/python-markdown.signatures.json
  SPECS/python-markdown/python-markdown.spec
  SPECS/python-tidy/python-tidy.signatures.json
  SPECS/python-tidy/python-tidy.spec
  SPECS/python-wrapt/python-wrapt.signatures.json
  SPECS/python-wrapt/python-wrapt.spec
  SPECS/tensorflow/tensorflow.signatures.json
  SPECS/tensorflow/tensorflow.spec
  cgmanifest.json
Labels: main

#4345 Aditjha/main/grubenv
  toolkit/resources/assets/grub2/grub.cfg
  toolkit/resources/assets/grub2/grubenv
  toolkit/resources/imageconfigs/iso_initrd.json
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/imager/imager.go
Labels: main

#4277 Increase Marketplace image size to 5GB
  toolkit/imageconfigs/marketplace-gen2.json
Labels: Schema, main

#4348 Add package xmlrpc-c version 1.54.06
  SPECS-EXTENDED/xmlrpc-c/0001-xmlrpc_server_abyss-use-va_args-properly.patch
  SPECS-EXTENDED/xmlrpc-c/xmlrpc-c.signatures.json
  SPECS-EXTENDED/xmlrpc-c/xmlrpc-c.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#4317 add ephemeral disk warning
  SPECS/WALinuxAgent/WALinuxAgent.signatures.json
  SPECS/WALinuxAgent/WALinuxAgent.spec
  SPECS/WALinuxAgent/ephemeral-disk-warning
  SPECS/WALinuxAgent/ephemeral-disk-warning.conf
  SPECS/WALinuxAgent/ephemeral-disk-warning.service
Labels: Packaging, 1.0-dev

#4254 Add ephemeral-disk-warning.service
  SPECS/WALinuxAgent/WALinuxAgent.signatures.json
  SPECS/WALinuxAgent/WALinuxAgent.spec
  SPECS/WALinuxAgent/ephemeral-disk-warning
  SPECS/WALinuxAgent/ephemeral-disk-warning.conf
  SPECS/WALinuxAgent/ephemeral-disk-warning.service
Labels: Packaging, main

#4286 Reverted invalid livepatch spec change.
  SPECS-SIGNED/livepatch-5.15.48.1-4.cm2-signed/livepatch-5.15.48.1-4.cm2-signed.spec
Labels: Packaging, main

#4354 Upgrade Blobfuse2 to 2.0.1
  SPECS/blobfuse2/blobfuse2.signatures.json
  SPECS/blobfuse2/blobfuse2.spec
  cgmanifest.json
Labels: main

#4367 Fix CVE-2022-41880: Update TensorFlow to 2.11.0
  SPECS/bazel/bazel.signatures.json
  SPECS/bazel/bazel.spec
  SPECS/tensorflow/tensorflow.signatures.json
  SPECS/tensorflow/tensorflow.spec
  cgmanifest.json
Labels: Packaging

#4305 apache-commons-compress: Fix package install failure due to missing runtime dependency
  SPECS-EXTENDED/apache-commons-compress/apache-commons-compress.spec
Labels: main, specs-extended

#4371 Patch python3 for CVE-2022-37454
  SPECS/python3/CVE-2022-37454.patch
  SPECS/python3/python3.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#4232 update generation 2 boot order during iso installation
  toolkit/tools/imagegen/attendedinstaller/attendedinstaller.go
  toolkit/tools/imagegen/configuration/configuration.go
  toolkit/tools/imagegen/configuration/configuration_test.go
  toolkit/tools/imagegen/configuration/systemconfig.go
  toolkit/tools/imagegen/configuration/systemconfig_test.go
  toolkit/tools/liveinstaller/liveinstaller.go
Labels: Tools, main

#4369 Enable hibernation in kernel
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#4378 Update heimdal for CVE-2022-41916
  SPECS/heimdal/autoconf-2.70-fix.patch
  SPECS/heimdal/fix_test_rand_build_failure.patch
  SPECS/heimdal/heimdal-configure.patch
  SPECS/heimdal/heimdal-python3.patch
  SPECS/heimdal/heimdal.signatures.json
  SPECS/heimdal/heimdal.spec
  cgmanifest.json
Labels: main

#4379 Patch python3 for CVE-2022-45061
  SPECS/python3/CVE-2022-45061.patch
  SPECS/python3/python3.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#4390 demo/tutorial wording changes
  toolkit/README.md
  toolkit/docs/building/building.md
Labels: main

#4395 Nopatch several CVEs for kernel
  SPECS/kernel/CVE-2022-1204.nopatch
  SPECS/kernel/CVE-2022-2785.nopatch
  SPECS/kernel/CVE-2022-3344.nopatch
  SPECS/kernel/CVE-2022-3586.nopatch
  SPECS/kernel/CVE-2022-3595.nopatch
  SPECS/kernel/CVE-2022-3910.nopatch
  SPECS/kernel/CVE-2022-40768.nopatch
  SPECS/kernel/CVE-2022-4127.nopatch
  SPECS/kernel/CVE-2022-41849.nopatch
  SPECS/kernel/CVE-2022-41850.nopatch
  SPECS/kernel/CVE-2022-43945.nopatch
Labels: security, Packaging, main

#4178 Add support for qcow2 output images
  toolkit/tools/roast/formats/qcow.go
  toolkit/tools/roast/roast.go
Labels: main

#4393 Patch python3 for CVE-2022-42919
  SPECS/python3/CVE-2022-42919.patch
  SPECS/python3/python3.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#4394 Patch emacs for CVE-2022-45939
  SPECS/emacs/CVE-2022-45939.patch
  SPECS/emacs/emacs.spec
Labels: Packaging, main

#4400 Update: TensorFlow correct package name
  SPECS/tensorflow/tensorflow.spec
Labels: Packaging, main

#4392 patch gnutls CVE-2022-2509
  SPECS/gnutls/CVE-2022-2509.patch
  SPECS/gnutls/gnutls.spec
Labels: Packaging, 1.0-dev

#4401 Nopatch kernel CVE-2022-3910, CVE-2022-4127, CVE-2022-41849, CVE-2022-43945, CVE-2022-4586
  SPECS/kernel/CVE-2022-3910.nopatch
  SPECS/kernel/CVE-2022-4127.nopatch
  SPECS/kernel/CVE-2022-41849.nopatch
  SPECS/kernel/CVE-2022-43945.nopatch
  SPECS/kernel/CVE-2022-45869.nopatch
Labels: security, Packaging, 1.0-dev

#4399 Update strongswan for CVE-2022-40617
  SPECS/strongswan/strongswan.signatures.json
  SPECS/strongswan/strongswan.spec
  cgmanifest.json
Labels: main

#4381 Add toolkit ccache support with USE_CCACHE
  SPECS/mariner-rpm-macros/macros
  SPECS/mariner-rpm-macros/mariner-rpm-macros.signatures.json
  SPECS/mariner-rpm-macros/mariner-rpm-macros.spec
  toolkit/Makefile
  toolkit/docs/building/building.md
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/pkggen.mk
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
  toolkit/scripts/tools.mk
  toolkit/tools/internal/rpm/rpm.go
  toolkit/tools/pkgworker/pkgworker.go
  toolkit/tools/scheduler/buildagents/chrootagent.go
  toolkit/tools/scheduler/buildagents/definition.go
  toolkit/tools/scheduler/scheduler.go
Labels: main

#4405 revert apparmor disable change
  toolkit/imageconfigs/marketplace-gen1.json
  toolkit/imageconfigs/marketplace-gen2-aarch64.json
  toolkit/imageconfigs/marketplace-gen2.json
Labels: Schema, 1.0-dev

#4406 Patch libconfuse for CVE-2022-40320
  SPECS/libconfuse/CVE-2022-40320.patch
  SPECS/libconfuse/libconfuse.spec
Labels: Packaging, main

#4389 add patch for glib CVE-2021-3800
  SPECS/glib/CVE-2021-3800.patch
  SPECS/glib/glib.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#4377 Adding in the hwdata and gawk dependencies
  SPECS/sriov-network-device-plugin/sriov-network-device-plugin.spec
Labels: Packaging, main

#4415 Bump Mariner 2.0 Release for December 2022 Update 2
  SPECS/mariner-release/mariner-release.spec
Labels: Packaging, main

#4407 k3s: Update the vendor tarball with the corrected versions of the dependencies
  SPECS/k3s/k3s-1.23.8.signatures.json
  SPECS/k3s/k3s-1.23.8.spec
  SPECS/k3s/k3s-1.24.3.signatures.json
  SPECS/k3s/k3s-1.24.3.spec
  SPECS/k3s/k3s.signatures.json
  SPECS/k3s/k3s.spec
  cgmanifest.json
Labels: Packaging, main

#4417 Bump Mariner 1.0 Release version for December Update 2
  SPECS/mariner-release/mariner-release.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#4396 Extended Boost with the `boost_stacktrace_backtrace` library.
  SPECS/boost/boost.spec
  SPECS/gcc/gcc.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/resources/manifests/package/update_manifests.sh
Labels: main

#4388 Add compiler-rt package for clang options like code coverage to work
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/compiler-rt/compiler-rt.signatures.json
  SPECS/compiler-rt/compiler-rt.spec
  cgmanifest.json
Labels: Packaging, main

#4413 add patch for Unbound CVE-2022-3204
  SPECS/unbound/CVE-2022-3204.patch
  SPECS/unbound/unbound.spec
Labels: Packaging, 1.0-dev

#4215 Added `selinux-policy` macros.
  SPECS/selinux-policy/macros.selinux-policy
  SPECS/selinux-policy/selinux-policy.signatures.json
  SPECS/selinux-policy/selinux-policy.spec
Labels: Packaging, main

#4420 Fixed updating from `ca-certificates-microsoft` to `ca-certificates`.
  SPECS/ca-certificates/ca-certificates.spec
  SPECS/prebuilt-ca-certificates-base/prebuilt-ca-certificates-base.spec
  SPECS/prebuilt-ca-certificates/prebuilt-ca-certificates.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#4386 Added the Linux Test Project kernel testing tools.
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/ltp/generate_submodules_tarball.sh
  SPECS/ltp/ltp.signatures.json
  SPECS/ltp/ltp.spec
  cgmanifest.json
Labels: main

#4433 Removed TDNF's dependency on RPM.
  SPECS/mariner-repos/mariner-repos.spec
  SPECS/tdnf/tdnf.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#4436 update CH to v28.0, kernel-mshv to v5.15.80
  SPECS-EXTENDED/kernel-mshv/0001-mshv-Don-t-use-same-function-signature-as-KVM.patch
  SPECS-EXTENDED/kernel-mshv/kernel-mshv.signatures.json
  SPECS-EXTENDED/kernel-mshv/kernel-mshv.spec
  SPECS/cloud-hypervisor/cloud-hypervisor.signatures.json
  SPECS/cloud-hypervisor/cloud-hypervisor.spec
  SPECS/initramfs/initramfs.spec
  cgmanifest.json
Labels: main

#4435 Add libnetfilter_log SPEC to Mariner
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/libnetfilter_log/libnetfilter_log-sysheader.patch
  SPECS/libnetfilter_log/libnetfilter_log.signatures.json
  SPECS/libnetfilter_log/libnetfilter_log.spec
  cgmanifest.json
Labels: main

#4326 Reduce initrd image size in Mariner 2.0
  SPECS/kpmcore/kpmcore.spec
  SPECS/linux-firmware/linux-firmware.spec
  SPECS/qt5-qtbase/qt5-qtbase.spec
  SPECS/qt5-qtdeclarative/qt5-qtdeclarative.spec
  SPECS/qt5-qtsvg/qt5-qtsvg.spec
  SPECS/qt5-qttools/qt5-qttools.spec
  cgmanifest.json
  toolkit/resources/imageconfigs/iso_initrd.json
  toolkit/resources/imageconfigs/packagelists/iso-initrd-packages.json
  toolkit/resources/imageconfigs/postinstallscripts/iso_initrd/cleanup.sh
Labels: main

#4439 Fix CVE-2022-23471 for moby-containerd
  SPECS/moby-containerd/CVE-2022-23471.patch
  SPECS/moby-containerd/moby-containerd.spec
Labels: Packaging, 1.0-dev

#4289 Add package suitesparse version 5.4.0
  SPECS-EXTENDED/suitesparse/suitesparse.signatures.json
  SPECS-EXTENDED/suitesparse/suitesparse.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4434 Upgrade ruby to version 3.1.3 to resolve CVE-2021-33621
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/ruby/get_gem_versions.sh
  SPECS/ruby/patch1-rb.patch
  SPECS/ruby/patch2-rb.patch
  SPECS/ruby/patch3-rb.patch
  SPECS/ruby/patch4-rb.patch
  SPECS/ruby/ruby.signatures.json
  SPECS/ruby/ruby.spec
  SPECS/rubygem-bundler/rubygem-bundler.signatures.json
  SPECS/rubygem-bundler/rubygem-bundler.spec
  cgmanifest.json
Labels: Packaging, main

#4442 Add patch to sqlite to resolve CVE-2022-46908
  SPECS/sqlite/CVE-2022-46908.patch
  SPECS/sqlite/sqlite.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, main

#4441 nodejs: add reference to artistic 2.0 license
  SPECS/nodejs/nodejs.spec
Labels: Packaging, main

#4440 Optimize toolchain rpm download
  toolkit/scripts/toolchain.mk
Labels: Tools, main

#4452 Fix rubygem-bundler provides with obsoletes
  SPECS/ruby/ruby.spec
Labels: Packaging, main

#4459 Removed libbacktrace.a from the default `gcc` package.
  SPECS/gcc/gcc.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#4106 Moving php-pear to core & adding php-pecl-zip
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/php-pear/cleanup.php
  SPECS/php-pear/install-pear.php
  SPECS/php-pear/macros.pear
  SPECS/php-pear/pear.sh
  SPECS/php-pear/peardev.sh
  SPECS/php-pear/pecl.sh
  SPECS/php-pear/php-pear.signatures.json
  SPECS/php-pear/php-pear.spec
  SPECS/php-pecl-zip/php-pecl-zip.signatures.json
  SPECS/php-pecl-zip/php-pecl-zip.spec
  cgmanifest.json
Labels: main

#4460 Correct typo in overview
  toolkit/docs/building/building.md
Labels: documentation, main

#4454 Add iwd package version 1.22
  SPECS-EXTENDED/iwd/iwd.signatures.json
  SPECS-EXTENDED/iwd/iwd.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4111 lensfun: add package version 0.3.2
  SPECS-EXTENDED/lensfun/0001-Only-require-glib-2.40-when-tests-are-build-without-.patch
  SPECS-EXTENDED/lensfun/0038-Only-use-proper-C-new-and-delete-syntax-for-object-c.patch
  SPECS-EXTENDED/lensfun/0058-Use-database-in-source-directory-while-running-tests.patch
  SPECS-EXTENDED/lensfun/0059-Patch-47-respect-DESTDIR-when-installing-python-stuf.patch
  SPECS-EXTENDED/lensfun/0060-Various-CMake-patches-from-the-mailing-list.patch
  SPECS-EXTENDED/lensfun/0113-Added-std-namespace-to-isnan.patch
  SPECS-EXTENDED/lensfun/0866-Pull-isnan-into-std-namespace-include-cmath-not-math.patch
  SPECS-EXTENDED/lensfun/lensfun-0.3.2-INSTALL_HELPER_SCRIPTS.patch
  SPECS-EXTENDED/lensfun/lensfun.signatures.json
  SPECS-EXTENDED/lensfun/lensfun.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4463 Fix for CVE-2022-41717
  SPECS/audit/audit.spec
  SPECS/blobfuse/blobfuse.spec
  SPECS/cni/cni.spec
  SPECS/coredns/coredns-1.8.0.spec
  SPECS/coredns/coredns-1.8.4.spec
  SPECS/coredns/coredns-1.8.6.spec
  SPECS/cri-tools/cri-tools.spec
  SPECS/etcd/etcd-3.4.13.spec
  SPECS/etcd/etcd-3.5.0.spec
  SPECS/etcd/etcd-3.5.1.spec
  SPECS/flannel/flannel.spec
  SPECS/glide/glide.spec
  SPECS/go-md2man/go-md2man.spec
  SPECS/gobject-introspection/gobject-introspection.spec
  SPECS/golang/CVE-2022-41717.patch
  SPECS/golang/golang-1.17.spec
  SPECS/golang/golang.spec
  SPECS/helm/helm.spec
  SPECS/libnvidia-container/libnvidia-container.spec
  SPECS/moby-buildx/moby-buildx.spec
  SPECS/moby-cli/moby-cli.spec
  SPECS/moby-containerd/moby-containerd.spec
  SPECS/moby-engine/moby-engine.spec
  SPECS/moby-runc/moby-runc.spec
  SPECS/node-problem-detector/node-problem-detector.spec
  SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec
  SPECS/telegraf/telegraf.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#4476 Bump Mariner 2.0 Release for December Update 3
  SPECS/mariner-release/mariner-release.spec
Labels: Packaging, main

#4477 Bump Mariner 1.0 Release for December Update 3
  SPECS/mariner-release/mariner-release.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#4474 qemu: Patch CVE-2022-3872
  SPECS/qemu/CVE-2022-3872.patch
  SPECS/qemu/qemu.spec
Labels: Packaging, main

#4482 Made sure `rpm` is included in all base images.
  SPECS/core-packages/core-packages.spec
Labels: Packaging, 1.0-dev

#4468 Specify tox ver. to not use 4.0.0+ to correct some python package tests
  SPECS/pyproject-rpm-macros/pyproject-rpm-macros.spec
  SPECS/python-coverage/python-coverage.spec
  SPECS/python-nocasedict/python-nocasedict.spec
  SPECS/python-pbr/python-pbr.spec
  SPECS/python-prettytable/python-prettytable.spec
  SPECS/python-pynacl/python-pynacl.spec
  SPECS/python-tqdm/python-tqdm.spec
  SPECS/python-twisted/python-twisted.spec
  SPECS/python-virtualenv/python-virtualenv.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, main

#4483 Improved `ltp` package clean-up.
  SPECS/ltp/ltp.spec
Labels: Packaging, main

#4475 Patch moby-containerd to add ptrace readby and tracedby to default AppArmor profile
  SPECS/moby-containerd/add_ptrace_readby_tracedby_to_apparmor.patch
  SPECS/moby-containerd/moby-containerd.spec
Labels: Packaging, main

#4473 Enable Generic Target Core Mod in kernel
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#4462 Clear Kernel CVE-1999-0656 and CVE 2007 4998
  SPECS/kernel-hci/CVE-1999-0656.nopatch
  SPECS/kernel-hci/CVE-2007-4998.npatch
  SPECS/kernel/CVE-1999-0656.nopatch
  SPECS/kernel/CVE-2007-4998.nopatch
Labels: Packaging, main

#4456 Add a comment to ensure scan vendors are contacted before any rpm que…
  toolkit/tools/imagegen/installutils/installutils.go
Labels: Tools, main

#4487 helm: Patch CVE-2022-23525, CVE-2022-23526
  SPECS/helm/CVE-2022-23525.patch
  SPECS/helm/CVE-2022-23526.patch
  SPECS/helm/helm.spec
Labels: Packaging, main

#4486 Patch curl to resolve CVE-2022-43551 and CVE-2022-43552
  SPECS/curl/CVE-2022-43551.patch
  SPECS/curl/CVE-2022-43552.patch
  SPECS/curl/curl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#4480 Add libreport package version 2.13.1
  SPECS-EXTENDED/libreport/0001-gui-wizard-gtk-Fix-segfault.patch
  SPECS-EXTENDED/libreport/libreport.signatures.json
  SPECS-EXTENDED/libreport/libreport.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4493 qemu-kvm: patch CVE-2022-3872
  SPECS/qemu-kvm/CVE-2022-3872.patch
  SPECS/qemu-kvm/qemu-kvm.spec
Labels: Packaging, 1.0-dev

#4495 Patch qemu-kvm to fix CVE-2021-4207
  SPECS/qemu-kvm/CVE-2021-4207.patch
  SPECS/qemu-kvm/qemu-kvm.spec
Labels: Packaging, 1.0-dev

#4494 Patch helm to fix CVE fix CVE-2022-23525 and CVE-2022-23526
  SPECS/helm/CVE-2022-23525.patch
  SPECS/helm/CVE-2022-23526.patch
  SPECS/helm/helm.spec
Labels: Packaging, 1.0-dev

#4484 qemu: Patched CVE-2021-3929, CVE-2021-4207
  SPECS/qemu/CVE-2021-3929.patch
  SPECS/qemu/CVE-2021-4207.patch
  SPECS/qemu/qemu.spec
Labels: security, Packaging, main

#4502 kubevirt: Upgrade to 0.58.0
  SPECS/kubevirt/disks-images-provider.yaml
  SPECS/kubevirt/kubevirt.signatures.json
  SPECS/kubevirt/kubevirt.spec
  cgmanifest.json
Labels: Packaging, main

#4503 Add package libwpd version 0.10.3
  SPECS-EXTENDED/libwpd/libwpd-gcc11.patch
  SPECS-EXTENDED/libwpd/libwpd.signatures.json
  SPECS-EXTENDED/libwpd/libwpd.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4504 Patch CVE-2021-3929 in qemu-kvm
  SPECS/qemu-kvm/CVE-2021-3929.patch
  SPECS/qemu-kvm/qemu-kvm.spec
Labels: Packaging, 1.0-dev

#4509 Fix kernel-hci CVE-2007-4998.nopatch
  SPECS/kernel-hci/CVE-2007-4998.nopatch
Labels: security, Packaging, main

#4505 Add package libucil & libunicap
  SPECS-EXTENDED/libucil/libucil-0.9.10-include-alsa.patch
  SPECS-EXTENDED/libucil/libucil-0.9.10-leaks.patch
  SPECS-EXTENDED/libucil/libucil-0.9.10-warnings.patch
  SPECS-EXTENDED/libucil/libucil-0.9.8-bz627890.patch
  SPECS-EXTENDED/libucil/libucil.signatures.json
  SPECS-EXTENDED/libucil/libucil.spec
  SPECS-EXTENDED/libunicap/libunicap-0.9.12-arraycmp.patch
  SPECS-EXTENDED/libunicap/libunicap-0.9.12-datadirname.patch
  SPECS-EXTENDED/libunicap/libunicap-0.9.12-gcc10.patch
  SPECS-EXTENDED/libunicap/libunicap-0.9.12-includes.patch
  SPECS-EXTENDED/libunicap/libunicap-0.9.12-memerrs.patch
  SPECS-EXTENDED/libunicap/libunicap-0.9.12-videodev.patch
  SPECS-EXTENDED/libunicap/libunicap-0.9.12-warnings.patch
  SPECS-EXTENDED/libunicap/libunicap-bz641623.patch
  SPECS-EXTENDED/libunicap/libunicap-bz642118.patch
  SPECS-EXTENDED/libunicap/libunicap-filter.sh
  SPECS-EXTENDED/libunicap/libunicap.signatures.json
  SPECS-EXTENDED/libunicap/libunicap.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4506 Add package libosinfo, osinfo-db & osinfo-db-tools
  SPECS-EXTENDED/libosinfo/libosinfo.signatures.json
  SPECS-EXTENDED/libosinfo/libosinfo.spec
  SPECS-EXTENDED/osinfo-db-tools/osinfo-db-tools.signatures.json
  SPECS-EXTENDED/osinfo-db-tools/osinfo-db-tools.spec
  SPECS-EXTENDED/osinfo-db/osinfo-db-20221130.tar.xz.asc
  SPECS-EXTENDED/osinfo-db/osinfo-db.signatures.json
  SPECS-EXTENDED/osinfo-db/osinfo-db.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4364 libtheora: Add package version 1.1.1
  SPECS-EXTENDED/libtheora/libtheora.signatures.json
  SPECS-EXTENDED/libtheora/libtheora.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4516 nopatch CVE-2022-4515 for ctags in 2.0
  SPECS/ctags/CVE-2022-4515.nopatch
Labels: security, Packaging, main

#4507 Patch grub2 CVE-2022-2601
  SPECS-SIGNED/grub2-efi-binary-signed/grub2-efi-binary-signed.spec
  SPECS/grub2/CVE-2022-2601.patch
  SPECS/grub2/grub2.spec
Labels: Packaging, 1.0-dev
