Repository microsoft/azurelinux, pull requests merged in 2022-05, with the labels that each got.

#2915 python-hs-dbus-signature: drop BR on `pytest` & `hypothesis` to enable ptest
  SPECS-EXTENDED/python-hs-dbus-signature/python-hs-dbus-signature.spec
Labels: ptest, main, specs-extended

#2916 python-flake8: pip install latest deps & fix check section to enable ptest
  SPECS-EXTENDED/python-flake8/python-flake8.spec
Labels: ptest, main, specs-extended

#2918 python-jwcrypto: add BR on `pip` to enable ptest
  SPECS-EXTENDED/python-jwcrypto/python-jwcrypto.spec
Labels: ptest, main, specs-extended

#2919 python-into-dbus-python: pip install latest deps to enable ptest
  SPECS-EXTENDED/python-into-dbus-python/python-into-dbus-python.spec
Labels: ptest, main, specs-extended

#2917 python-justbytes: use `py.test` instead of `py.test-3` to enable ptest
  SPECS-EXTENDED/python-justbytes/python-justbytes.spec
  cgmanifest.json
Labels: ptest, main, specs-extended

#2922 Update qemu to 6.2.0
  SPECS/qemu/0001-acpi-fix-QEMU-crash-when-started-with-SLIC-table.patch
  SPECS/qemu/0001-sgx-stub-fix.patch
  SPECS/qemu/0001-target-i386-add-missing-bits-to-CR4_RESERVED_MASK.patch
  SPECS/qemu/0001-tools-virtiofsd-Add-rseq-syscall-to-the-seccomp-allo.patch
  SPECS/qemu/0002-virtiofsd-Do-not-support-blocking-flock.patch
  SPECS/qemu/CVE-2021-20255.patch
  SPECS/qemu/CVE-2022-0358.patch
  SPECS/qemu/CVE-2022-1050.patch
  SPECS/qemu/CVE-2022-26354.patch
  SPECS/qemu/qemu.signatures.json
  SPECS/qemu/qemu.spec
  cgmanifest.json
Labels: Packaging, main

#2914 [main] Updating CGmanifest verification tools source URLs.
  .github/workflows/validate-cg-manifest.sh
  SPECS-EXTENDED/geronimo-specs/geronimo-specs.spec
  SPECS-EXTENDED/jdom2/jdom2.spec
  SPECS-EXTENDED/libiodbc/libiodbc.spec
  SPECS-EXTENDED/python-pyroute2/python-pyroute2.spec
  SPECS-EXTENDED/python-templated-dictionary/python-templated-dictionary.spec
  SPECS-EXTENDED/rpm-mpi-hooks/rpm-mpi-hooks.spec
  SPECS/antlr/antlr.spec
  SPECS/grubby/grubby.spec
  SPECS/java-cup/java-cup-bootstrap.spec
  SPECS/java-cup/java-cup.spec
  SPECS/lcms2/0017-Upgrade-Visual-studio-2017-15.8.patch
  SPECS/lcms2/lcms2.signatures.json
  SPECS/lcms2/lcms2.spec
  SPECS/nss/nss.spec
  SPECS/numad/numad.spec
  SPECS/objectweb-asm/objectweb-asm.spec
  SPECS/ocaml-num/ocaml-num.spec
  SPECS/openssl/openssl.spec
  SPECS/python-filelock/python-filelock.spec
  SPECS/python-pytest-cov/python-pytest-cov.spec
  SPECS/python-pywbem/python-pywbem.spec
  SPECS/python-repoze-lru/python-repoze-lru.spec
  SPECS/python-requests/python-requests.spec
  SPECS/python-sphinxcontrib-websupport/python-sphinxcontrib-websupport.spec
  SPECS/python-yamlloader/python-yamlloader.spec
  SPECS/re2/re2.spec
  SPECS/rt-setup/rt-setup.spec
  SPECS/rtctl/rtctl.spec
  SPECS/selinux-policy/selinux-policy.spec
  SPECS/sgabios/sgabios.spec
  SPECS/usbip/usbip.spec
  SPECS/words/words.spec
  SPECS/yajl/yajl.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#2931 python-uamqp: drop BR on pytest, six & pip install deps to enable ptest
  SPECS-EXTENDED/python-uamqp/python-uamqp.spec
Labels: ptest, main, specs-extended

#2932 python-sniffio: use `py.test` instead of `py.test-3` to enable ptest
  SPECS-EXTENDED/python-sniffio/python-sniffio.spec
Labels: ptest, main, specs-extended

#2933 python-mccabe: drop BR on pytest & pip install latest deps to enable ptest
  SPECS-EXTENDED/python-mccabe/python-mccabe.spec
Labels: ptest, main, specs-extended

#2947 Removing `rpm` calls from `tdnf` scripts.
  SPECS/tdnf/tdnf.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#2948 Add lib files to rubygems from source
  SPECS-EXTENDED/rubygem-semantic_puppet/rubygem-semantic_puppet.spec
  SPECS/rubygem-concurrent-ruby/rubygem-concurrent-ruby.spec
Labels: main

#2949 Drop old lines from StreamOutput if full
  toolkit/tools/internal/logger/log.go
Labels: Tools, main

#2952 Fix cassandra package install and uninstall issues
  SPECS-EXTENDED/cassandra/cassandra.spec
Labels: main

#2955 Remove vim to include by default in marketplace mariner images
  toolkit/imageconfigs/marketplace-gen1.json
  toolkit/imageconfigs/marketplace-gen2-aarch64.json
  toolkit/imageconfigs/marketplace-gen2.json
  toolkit/imageconfigs/packagelists/marketplace-tools-packages.json
Labels: Schema, main

#2940 python-requests-kerberos: use `py.test` instead of `py.test-3` to enable ptest
  SPECS-EXTENDED/python-requests-kerberos/python-requests-kerberos.spec
Labels: ptest, main, specs-extended

#2937 selinux-policy: Add additional patches from containers and kubernetes testing.
  SPECS/selinux-policy/0017-Add-cloud-init.patch
  SPECS/selinux-policy/0018-Add-compatibility-for-container-selinux.patch
  SPECS/selinux-policy/0019-systemd-Remove-systemd-run-domain.patch
  SPECS/selinux-policy/0020-unconfined-Add-missing-capability2-perms.patch
  SPECS/selinux-policy/0021-lvm-Updates-for-multipath-LVM.patch
  SPECS/selinux-policy/0022-locallogin-Use-init-file-descriptors.patch
  SPECS/selinux-policy/0023-systemd-Misc-fixes.patch
  SPECS/selinux-policy/0024-isns-Updates-from-testing.patch
  SPECS/selinux-policy/0025-container-docker-Fixes-for-containerd-and-kubernetes.patch
  SPECS/selinux-policy/0026-devices-Add-type-for-SAS-management-devices.patch
  SPECS/selinux-policy/0027-devices-Add-file-context-for-dev-vhost-vsock.patch
  SPECS/selinux-policy/0028-Add-dac_read_search-perms.patch
  SPECS/selinux-policy/0029-iptables-Ioctl-cgroup-dirs.patch
  SPECS/selinux-policy/selinux-policy.spec
Labels: Packaging, main

#2951 kernel: Address CVE-2022-0330, CVE-2022-26558, CVE-2021-4197, CVE-2021-4150, CVE-2020-35501
  SPECS/kernel/CVE-2020-35501.nopatch
  SPECS/kernel/CVE-2021-4150.nopatch
  SPECS/kernel/CVE-2021-4197.nopatch
  SPECS/kernel/CVE-2022-0330.nopatch
  SPECS/kernel/CVE-2022-26558.nopatch
  SPECS/kernel/kernel.spec
Labels: Packaging, 1.0-dev

#2938 Fixed ansible CVE-2021-3620 with upgrade to 2.9.27
  SPECS/ansible/ansible.signatures.json
  SPECS/ansible/ansible.spec
  cgmanifest.json
Labels: 1.0-dev

#2953 Create util-linux-libs RPM package with libraries
  SPECS/systemd/systemd.spec
  SPECS/util-linux/util-linux.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#2956 Fix leading spaces in /etc/nsswitch.conf
  SPECS/glibc/glibc.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#2959 Add gzip and sed to base container image
  SPECS/core-packages/core-packages.spec
Labels: Packaging, main

#2967 Add util-linux-devel into pkgggen_core
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
Labels: main

#2960 Update python-google-auth
  SPECS/python-google-auth/python-google-auth.signatures.json
  SPECS/python-google-auth/python-google-auth.spec
  cgmanifest.json
Labels: main

#2965 Remove libpq package
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/libpq/libpq-10.3-rpm-pgsql.patch
  SPECS/libpq/libpq-10.3-var-run-socket.patch
  SPECS/libpq/libpq-12.1-symbol-versioning.patch
  SPECS/libpq/libpq.signatures.json
  SPECS/libpq/libpq.spec
  SPECS/postgresql/postgresql.spec
  cgmanifest.json
Labels: main

#2961 Remove unnecessary files in toolchain_from_container.tar.gz
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
  toolkit/scripts/toolchain/create_toolchain_in_container.sh
Labels: Tools, main

#2966 toolchain: Remove wget
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/resources/manifests/package/update_manifests.sh
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
Labels: main

#2971 mariadb: Fix mariadb-connector-c conflicts
  SPECS/mariadb/mariadb.spec
Labels: Packaging, main

#2969 Upgraded zlib to 1.2.12 to fix CVE-2018-25032
  SPECS/zlib/zlib.signatures.json
  SPECS/zlib/zlib.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/toolchain-remote-wget-list
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
Labels: 1.0-dev

#2958 Update systemd to build in release mode
  SPECS/systemd/systemd-bootstrap.spec
  SPECS/systemd/systemd.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#2964 [RFC] msft-golang: add package for `microsoft/go`
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/msft-golang/go14_bootstrap_aarch64.patch
  SPECS/msft-golang/msft-golang.signatures.json
  SPECS/msft-golang/msft-golang.spec
  cgmanifest.json
Labels: main

#2972 qemu: Remove multiboot_dma.bin from x86_64 files during aarch64 builds
  SPECS/qemu/qemu.spec
Labels: Packaging, main

#2849 [main] Enable kickstart partition parsing in Mariner
  toolkit/docs/formats/imageconfig.md
  toolkit/tools/imageconfigvalidator/imageconfigvalidator.go
  toolkit/tools/imagegen/configuration/parse_partition.go
  toolkit/tools/imagegen/configuration/parse_partition_test.go
  toolkit/tools/imagegen/configuration/partition.go
  toolkit/tools/imagegen/configuration/systemconfig.go
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/imager/imager.go
  toolkit/tools/isomaker/maker.go
Labels: Tools, main

#2978 No-Patch CVE-2018-9057
  SPECS/terraform/CVE-2018-9057.nopatch
Labels: security, Packaging, main

#2979 Altered Dockerfile for toolchain build to avoid build warning
  toolkit/scripts/toolchain/container/Dockerfile
Labels: Tools, 1.0-dev

#2980 [main] Re-Reenable systemd hardening flags in logrotate
  SPECS/logrotate/logrotate.spec
Labels: Packaging, main

#2973 Fixed several CVEs in qemu-kvm
  SPECS/qemu-kvm/CVE-2021-20257.patch
  SPECS/qemu-kvm/CVE-2021-20295.nopatch
  SPECS/qemu-kvm/CVE-2021-3638.patch
  SPECS/qemu-kvm/CVE-2021-3748.patch
  SPECS/qemu-kvm/CVE-2022-1050.nopatch
  SPECS/qemu-kvm/qemu-kvm.spec
Labels: Packaging, 1.0-dev

#2988 Creating SELinux core config for SELinux BVT
  toolkit/imageconfigs/core-efi-selinux.json
Labels: Schema, main

#2987 upgrade gdb to 11.2
  SPECS/gdb/gdb.signatures.json
  SPECS/gdb/gdb.spec
  cgmanifest.json
Labels: Packaging, main

#2986 toolkit: Update toolkit version linker argument for new module path
  toolkit/scripts/tools.mk
Labels: Tools, main

#2985 Update download-packages.sh script to support 2.0 repo
  toolkit/scripts/download-packages.sh
Labels: Tools, main

#2989 Fix openssl CVE-2022-1292
  SPECS/openssl/CVE-2022-1292.patch
  SPECS/openssl/openssl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#2996 [main] Update kernel to v5.15.37, fix CVE, enable IFB config
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/hyperv-daemons/hyperv-daemons.signatures.json
  SPECS/hyperv-daemons/hyperv-daemons.spec
  SPECS/kernel-headers/kernel-headers.signatures.json
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/CVE-2021-4095.nopatch
  SPECS/kernel/CVE-2022-0500.nopatch
  SPECS/kernel/CVE-2022-0998.nopatch
  SPECS/kernel/CVE-2022-28796.nopatch
  SPECS/kernel/CVE-2022-29582.nopatch
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/Dockerfile
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
  toolkit/scripts/toolchain/container/toolchain_build_temp_tools.sh
Labels: main

#2991 cockpit: Address CVE-2021-3660 and CVE-2021-3698
  SPECS/cockpit/CVE-2021-3660.patch
  SPECS/cockpit/CVE-2021-3698.patch
  SPECS/cockpit/cockpit.spec
Labels: Packaging, 1.0-dev

#2997 openssl: address CVE-2022-1292
  SPECS/openssl/CVE-2022-1292.patch
  SPECS/openssl/openssl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3005 [1.0] Update rubygem-elasticsearch to v8.2.0 to resolve CVE-2021-22144, 2021-22134
  SPECS/rubygem-elasticsearch/rubygem-elasticsearch.signatures.json
  SPECS/rubygem-elasticsearch/rubygem-elasticsearch.spec
  cgmanifest.json
Labels: Packaging, 1.0-dev

#3003 [1.0] freetype: patch CVE-2022-27404
  SPECS/freetype/CVE-2022-27404.patch
  SPECS/freetype/freetype.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, 1.0-dev

#2995 quota: add quota package
  SPECS-EXTENDED/quota/quota-4.05-COPYING-Update-mailing-address.patch
  SPECS-EXTENDED/quota/quota-4.05-Fix-ignoring-disabled-quotas.patch
  SPECS-EXTENDED/quota/quota-4.05-Make-a-directory-for-quota_nld-PID-file-configurable.patch
  SPECS-EXTENDED/quota/quota-4.05-Make-messages-about-failures-for-NFS-consistent-with.patch
  SPECS-EXTENDED/quota/quota-4.05-Revert-configure.ac-fix-pkg_check_modules-calls.patch
  SPECS-EXTENDED/quota/quota-4.05-quotacheck-Skip-checking-of-filesystems-with-hidded-.patch
  SPECS-EXTENDED/quota/quota-4.05-quotaops-Do-not-leak-dquot-structures-on-failure.patch
  SPECS-EXTENDED/quota/quota-4.05-quotaops-Do-not-return-partial-list-from-getprivs.patch
  SPECS-EXTENDED/quota/quota-4.05-quotaops-Make-error-string-translatable.patch
  SPECS-EXTENDED/quota/quota-4.05-rpc-Clarify-error-message-when-cannot-connect-to-rpc.patch
  SPECS-EXTENDED/quota/quota-4.05-setquota-Report-failure-to-obtain-quota-information.patch
  SPECS-EXTENDED/quota/quota-4.05-warnquota-Clarify-that-CC_TO-gets-resolved-through-L.patch
  SPECS-EXTENDED/quota/quota-4.05-warnquota-Fix-help-text.patch
  SPECS-EXTENDED/quota/quota-4.05-warnquota-Free-LDAP-error-message.patch
  SPECS-EXTENDED/quota/quota-4.05-warnquota-Initialize-all-members-of-a-configparams-s.patch
  SPECS-EXTENDED/quota/quota-4.05-warnquota-Print-also-additional-error-info-for-LDAP-.patch
  SPECS-EXTENDED/quota/quota-4.05-warnquota-Properly-detect-LDAP-errors.patch
  SPECS/quota/quota-4.03-Validate-upper-bound-of-RPC-port.patch
  SPECS/quota/quota-4.06-Drop-sys-cdefs.h-usage.patch
  SPECS/quota/quota-4.06-common.c-fix-strncat-usage.patch
  SPECS/quota/quota-4.06-quota_nld-Initialize-sa_mask-when-registering-PID-fi.patch
  SPECS/quota/quota-4.06-quotacheck-Remove-a-dead-code-from-process_file.patch
  SPECS/quota/quota-4.06-quotacheck-quotaon-Always-display-message-about-depr.patch
  SPECS/quota/quota-4.06-quotaio_xfs-Warn-when-large-kernel-timestamps-cannot.patch
  SPECS/quota/quota-4.06-quotaops-fix-compilation-warning.patch
  SPECS/quota/quota-4.06-quotasys.c-fix-strncpy-usage.patch
  SPECS/quota/quota-4.06-warnquota-configuration-tunes.patch
  SPECS/quota/quota.signatures.json
  SPECS/quota/quota.spec
  SPECS/quota/quota_nld.service
  SPECS/quota/quota_nld.sysconfig
  SPECS/quota/rpc-rquotad.service
  SPECS/quota/rpc-rquotad.sysconfig
  cgmanifest.json
Labels: Packaging, main

#3002 Remove python3 as a runtime dep for nodejs
  SPECS/nodejs/nodejs.spec
Labels: Packaging, main

#3001 Add the sdbus-cpp package to Mariner
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/sdbus-cpp/sdbus-cpp.signatures.json
  SPECS/sdbus-cpp/sdbus-cpp.spec
  cgmanifest.json
Labels: Packaging, main

#3006 freetype: address CVE-2022-27404
  SPECS/freetype/CVE-2022-27404.patch
  SPECS/freetype/freetype.spec
Labels: Packaging, main

#3009 [main] [CVEs] Nopatch kernel CVEs
  SPECS/kernel/CVE-2022-1015.nopatch
  SPECS/kernel/CVE-2022-1048.nopatch
  SPECS/kernel/CVE-2022-1195.nopatch
  SPECS/kernel/CVE-2022-1353.nopatch
  SPECS/kernel/CVE-2022-29968.nopatch
  SPECS/kernel/kernel.spec
Labels: Packaging, main

#3015 grub.cfg: disable unprivileged bpfs in kernel cmdline
  toolkit/resources/assets/grub2/grub.cfg
  toolkit/resources/assets/isomaker/iso_root_static_files/boot/grub2/grub.cfg
Labels: main

#2714 Add missing `rpmbuild` dependencies
  SPECS/rpm/rpm.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, main

#3022 Update libepoxy to 1.5.10
  SPECS/libepoxy/libepoxy.signatures.json
  SPECS/libepoxy/libepoxy.spec
  cgmanifest.json
Labels: main

#3016 Updating tooling to Go 1.17.
  toolkit/tools/go.mod
  toolkit/tools/go.sum
Labels: Tools, main

#3017 toolkit: gomod: bump go version `1.13` -> `1.17`
  toolkit/tools/go.mod
Labels: Tools, 1.0-dev

#3021 kernel: Update to 5.10.116.1
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/hyperv-daemons/hyperv-daemons.signatures.json
  SPECS/hyperv-daemons/hyperv-daemons.spec
  SPECS/kernel-headers/kernel-headers.signatures.json
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel-hyperv/config
  SPECS/kernel-hyperv/kernel-hyperv.signatures.json
  SPECS/kernel-hyperv/kernel-hyperv.spec
  SPECS/kernel/CVE-2022-0494.nopatch
  SPECS/kernel/CVE-2022-1015.nopatch
  SPECS/kernel/CVE-2022-1048.nopatch
  SPECS/kernel/CVE-2022-1195.nopatch
  SPECS/kernel/CVE-2022-1353.nopatch
  SPECS/kernel/CVE-2022-29582.nopatch
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/Dockerfile
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
  toolkit/scripts/toolchain/container/toolchain_build_temp_tools.sh
Labels: 1.0-dev

#2911 toolchain: Remove mariner-release package
  SPECS/supermin/supermin.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/resources/manifests/package/update_manifests.sh
  toolkit/scripts/imggen.mk
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
  toolkit/tools/internal/tdnf/tdnf.go
  toolkit/tools/internal/tdnf/tdnf_test.go
  toolkit/tools/pkgworker/pkgworker.go
Labels: main

#3028 filesystem: add input handling for {forward,backward}-word
  SPECS/filesystem/filesystem.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3024 Overwrite 99-dhcp-en.network for marketplace img
  toolkit/imageconfigs/additionalconfigs/configure-image.sh
Labels: Schema, main

#3018 cpio: address CVE-2021-38185
  SPECS/cpio/CVE-2021-38185.patch
  SPECS/cpio/cpio.spec
  toolkit/.gitignore
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/Dockerfile
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
  toolkit/scripts/toolchain/create_toolchain_in_container.sh
Labels: main

#3030 cracklib: remove /usr/sbin/packer symlink due to conflict
  SPECS/cracklib/cracklib.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#3029 Adding core-efi-selinux.json image config
  toolkit/imageconfigs/core-efi-selinux.json
Labels: Schema, 1.0-dev

#3033 Bump Mariner 1.0 Release for May 2022 Update
  SPECS/mariner-release/mariner-release.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#3034 lua: Patch CVE-2022-28805
  SPECS/lua/CVE-2022-28805.patch
  SPECS/lua/lua.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3037 vim: Update to 8.2.4925 to address CVE-2022-1381, CVE-2022-1420, CVE-2022-1616, CVE-2022-1619, CVE-2022-1620, CVE-2022-1621, CVE-2022-1629
  SPECS/vim/vim.signatures.json
  SPECS/vim/vim.spec
  cgmanifest.json
Labels: Packaging, main

#3040 Bump Mariner 2.0 Release for May 2022 Update
  SPECS/mariner-release/mariner-release.spec
Labels: Packaging, main

#3039 dnf-plugins-core: Add patch to fix wrong boot time
  SPECS/dnf-plugins-core/Fix-wrong-boot-time-RhBug-1960437.patch
  SPECS/dnf-plugins-core/dnf-plugins-core.spec
Labels: Packaging, 1.0-dev

#3042 qemu: add patch for CVE-2022-26353
  SPECS/qemu/CVE-2022-26353.patch
  SPECS/qemu/qemu.spec
Labels: Packaging, main

#3043 haproxy: Add nopatch for CVE-2022-0711
  SPECS/haproxy/CVE-2022-0711.nopatch
  SPECS/haproxy/haproxy.spec
Labels: Packaging, main

#3045 kernel: Add nopatch for CVE-2022-29968
  SPECS/kernel/CVE-2022-29968.nopatch
  SPECS/kernel/kernel.spec
Labels: Packaging, 1.0-dev

#3048 kernel configs to bring down boot time for initrd
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3046 Update libxml2 to 2.9.14 to address CVE-2022-29824
  SPECS/libxml2/libxml2.signatures.json
  SPECS/libxml2/libxml2.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3032 update libwpe and wpebackend fdo
  SPECS-EXTENDED/libwpe/libwpe.signatures.json
  SPECS-EXTENDED/libwpe/libwpe.spec
  SPECS-EXTENDED/wpebackend-fdo/wpebackend-fdo.signatures.json
  SPECS-EXTENDED/wpebackend-fdo/wpebackend-fdo.spec
  cgmanifest.json
Labels: main

#3057 Fix signature for wpebackend-fdo
  SPECS-EXTENDED/wpebackend-fdo/wpebackend-fdo.signatures.json
Labels: main

#3049 Address CVE-2021-30560 with libxslt patch
  SPECS/libxslt/CVE-2021-30560.patch
  SPECS/libxslt/libxslt.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3055 Update zsh to v5.9 to address CVE-2021-45444
  SPECS/zsh/0001-Skipping-test-if-ran-as-superuser.patch
  SPECS/zsh/zsh.signatures.json
  SPECS/zsh/zsh.spec
  cgmanifest.json
Labels: main

#3038 Limit module_info.ld inclusion in LDFLAGS from mariner-rpm-macros
  SPECS/mariner-rpm-macros/gen-ld-script.sh
  SPECS/mariner-rpm-macros/macros
  SPECS/mariner-rpm-macros/mariner-rpm-macros.signatures.json
  SPECS/mariner-rpm-macros/mariner-rpm-macros.spec
  SPECS/perl/perl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
  toolkit/tools/internal/rpm/rpm.go
  toolkit/tools/pkgworker/pkgworker.go
Labels: main

#3054 Update rsyslog to v8.2204.1 to address CVE-2022-24903
  SPECS/rsyslog/rsyslog.signatures.json
  SPECS/rsyslog/rsyslog.spec
  cgmanifest.json
Labels: main

#3050 Address libxslt CVE-2021-30560
  SPECS/libxslt/CVE-2021-30560.patch
  SPECS/libxslt/libxslt.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#3053 Address rsyslog CVE-2022-24903
  SPECS/rsyslog/CVE-2022-24903.patch
  SPECS/rsyslog/rsyslog.spec
Labels: Packaging, 1.0-dev

#3060 fix iotop python3-curses dependency
  SPECS/iotop/iotop.spec
Labels: Packaging, main

#3061 Upgrade curl version to 7.83.0
  SPECS/curl/curl.signatures.json
  SPECS/curl/curl.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3047 selinux-policy: Fixes from baremetal testing.
  SPECS/selinux-policy/0021-lvm-Updates-for-multipath-LVM.patch
  SPECS/selinux-policy/0030-container-allow-containers-to-manipulate-own-fds.patch
  SPECS/selinux-policy/0031-devices-Add-type-for-infiniband-devices.patch
  SPECS/selinux-policy/0032-storage-Add-fc-for-dev-ng-n-devices.patch
  SPECS/selinux-policy/0033-files-Add-prerequisite-access-for-files_mounton_non_.patch
  SPECS/selinux-policy/0034-files-Make-etc_runtime_t-a-config-file.patch
  SPECS/selinux-policy/0035-systemd-Fixes-for-coredumps-in-containers.patch
  SPECS/selinux-policy/0036-container-Allow-container-engines-to-connect-to-http.patch
  SPECS/selinux-policy/0037-container-Getattr-generic-device-nodes.patch
  SPECS/selinux-policy/0038-application-Allow-apps-to-use-init-fds.patch
  SPECS/selinux-policy/selinux-policy.spec
Labels: Packaging

#3062 `SPECS-EXTENDED` regression fixes: `efi-rpm-macros`, `libftdi`, and `python-mccabe`.
  SPECS-EXTENDED/efi-rpm-macros/efi-rpm-macros.signatures.json
  SPECS-EXTENDED/efi-rpm-macros/efi-rpm-macros.spec
  SPECS-EXTENDED/libftdi/libftdi-1.5-fix_pkgconfig_path.patch
  SPECS-EXTENDED/libftdi/libftdi-cmake_swig.patch
  SPECS-EXTENDED/libftdi/libftdi.signatures.json
  SPECS-EXTENDED/libftdi/libftdi.spec
  SPECS-EXTENDED/python-mccabe/python-mccabe.spec
  cgmanifest.json
Labels: main

#3063 Update kernel source to 5.15.41.1 to address CVE-2022-28893, CVE-2022-29581
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/hyperv-daemons/hyperv-daemons.signatures.json
  SPECS/hyperv-daemons/hyperv-daemons.spec
  SPECS/kernel-headers/kernel-headers.signatures.json
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/CVE-2020-35501.nopatch
  SPECS/kernel/CVE-2022-28893.nopatch
  SPECS/kernel/CVE-2022-29581.nopatch
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/Dockerfile
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
  toolkit/scripts/toolchain/container/toolchain_build_temp_tools.sh
  toolkit/scripts/update_kernel.sh
Labels: main

#3067 Update pcre2 to v10.40 to address CVE-2022-1586, CVE-2022-1587
  SPECS/pcre2/pcre2.signatures.json
  SPECS/pcre2/pcre2.spec
  cgmanifest.json
Labels: main

#3066 Add Mariner 2.0 ISO Download and reflect changes from 1.0
  README.md
Labels: main

#3056 Reduce base RPM package size, re-add in container image
  SPECS/core-packages/core-packages.spec
  SPECS/rpm/rpm.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#2994 Add iana-etc as runtime dep for fping
  SPECS/fping/fping.spec
Labels: Packaging, main

#3068 Apply patches for pcre2 CVEs CVE-2022-1586, CVE-2022-1587
  SPECS/pcre2/CVE-2022-1586.patch
  SPECS/pcre2/CVE-2022-1587.patch
  SPECS/pcre2/pcre2.spec
  cgmanifest.json
Labels: Packaging, 1.0-dev

#3064 Require glibc-iconv for unixODBC
  SPECS/unixODBC/unixODBC.spec
Labels: Packaging, main

#3070 Restore cert-manager package
  SPECS/cert-manager/cert-manager.spec
Labels: Packaging, main

#3027 Adding usrsctp package
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/usrsctp/usrsctp.signatures.json
  SPECS/usrsctp/usrsctp.spec
  cgmanifest.json
Labels: Packaging, main

#3078 mariadb: Upgrade to 10.3.35 to fix 20 CVEs
  SPECS/mariadb/mariadb.signatures.json
  SPECS/mariadb/mariadb.spec
  cgmanifest.json
Labels: 1.0-dev

#3069 Upgrade kernel to V5.10.117.1, Addressing CVE-2022-28893
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/hyperv-daemons/hyperv-daemons.signatures.json
  SPECS/hyperv-daemons/hyperv-daemons.spec
  SPECS/kernel-headers/kernel-headers.signatures.json
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel-hyperv/config
  SPECS/kernel-hyperv/kernel-hyperv.signatures.json
  SPECS/kernel-hyperv/kernel-hyperv.spec
  SPECS/kernel/CVE-2022-28893.nopatch
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/Dockerfile
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
  toolkit/scripts/toolchain/container/toolchain_build_temp_tools.sh
Labels: 1.0-dev
