Repository microsoft/azurelinux, pull requests merged in 2022-07, with the labels that each got.

#3282 Update Vim to 8.2.5172 to fix CVE-2022-2175, CVE-2022-2182
  SPECS/vim/vim.signatures.json
  SPECS/vim/vim.spec
  cgmanifest.json
Labels: main

#3285 Add Github cli gh SPEC
  SPECS-EXTENDED/fish/fish-3.1.2.tar.gz.asc
  SPECS-EXTENDED/fish/fish.signatures.json
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/fish/fish.signatures.json
  SPECS/fish/fish.spec
  SPECS/gh/gh.signatures.json
  SPECS/gh/gh.spec
  cgmanifest.json
Labels: main

#3283 kernel: address CVEs CVE-2022-1652, CVE-2022-32981
  SPECS/kernel/CVE-2022-1652.nopatch
  SPECS/kernel/CVE-2022-32981.nopatch
Labels: security, Packaging, main

#3287 Use --no-clobber for toolchain downloads
  toolkit/scripts/toolchain.mk
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
Labels: Tools, main

#3286 python3: Remove Windows execuatables, add add'l provides
  SPECS/python3/python3.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3294 qemu: ship missing `efi*rom` & `pxe*rom` romfiles
  SPECS/qemu/qemu.spec
Labels: Packaging, main

#3297 Add azcopy and dcos-cli SPECS
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/azcopy/azcopy.signatures.json
  SPECS/azcopy/azcopy.spec
  SPECS/dcos-cli/dcos-cli.signatures.json
  SPECS/dcos-cli/dcos-cli.spec
  cgmanifest.json
Labels: main

#3267 Adding git to the requirements doc install instructions
  toolkit/docs/building/prerequisites-ubuntu.md
Labels: documentation, main

#3292 Switch to HTTPS source for `autoconf213`
  SPECS/autoconf213/autoconf213.spec
  cgmanifest.json
Labels: main

#3278 Add DELTA_BUILD toolkit variable
  toolkit/Makefile
  toolkit/docs/building/building.md
  toolkit/scripts/pkggen.mk
  toolkit/tools/scheduler/scheduler.go
  toolkit/tools/scheduler/schedulerutils/initializegraph.go
  toolkit/tools/scheduler/schedulerutils/preparerequest.go
Labels: main

#3223 Bug fix for `ResolveCompetingPackages` when building on RPM-based distro
  toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
  toolkit/tools/internal/rpm/rpm.go
Labels: Tools, main

#3281 cloud-init: patch for CVE-2022-2084
  SPECS/cloud-init/CVE-2022-2084.patch
  SPECS/cloud-init/cloud-init.spec
Labels: Packaging, main

#3299 qemu: fix build break on aarch64
  SPECS/qemu/qemu.spec
Labels: Packaging, main

#3302 Fix kernel-rt build break
  SPECS/kernel-rt/kernel-rt.spec
Labels: Packaging, main

#3301 Update fish to 3.5.0 to resolve CVE-2022-20001
  SPECS-EXTENDED/python-argcomplete/python-argcomplete.spec
  SPECS/fish/fish.signatures.json
  SPECS/fish/fish.spec
  SPECS/gh/gh.spec
  cgmanifest.json
Labels: main

#3298 add the intel-ipsec-mb package
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/intel-ipsec-mb/intel-ipsec-mb.signatures.json
  SPECS/intel-ipsec-mb/intel-ipsec-mb.spec
  cgmanifest.json
Labels: main

#3323 msopenjdk-11: Upgrade to 11.0.15+10-LTS-1
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
Labels: main

#3322 Add intel-pf-bb-config package
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/intel-pf-bb-config/intel-pf-bb-config.signatures.json
  SPECS/intel-pf-bb-config/intel-pf-bb-config.spec
  cgmanifest.json
Labels: main

#3328 Fix bad interpreter error when run pip3
  SPECS/python3/python3.spec
Labels: Packaging, 1.0-dev

#3333 python3: Additionally fix shabang for pip3.7 script
  SPECS/python3/python3.spec
Labels: Packaging, 1.0-dev

#3325 Added patch for CVE-2021-4206 to qemu-kvm
  SPECS/qemu-kvm/CVE-2021-4206.patch
  SPECS/qemu-kvm/qemu-kvm.spec
Labels: Packaging, 1.0-dev

#3335 backported redis 6.2.7 to 1.0 to fix CVE-2021-24736
  SPECS/redis/disable_active_defrag_big_keys.patch
  SPECS/redis/redis.signatures.json
  SPECS/redis/redis.spec
  cgmanifest.json
Labels: 1.0-dev

#3336 Move su from shadow-utils to util-linux
  SPECS/shadow-utils/shadow-utils.signatures.json
  SPECS/shadow-utils/shadow-utils.spec
  SPECS/util-linux/su
  SPECS/util-linux/util-linux.signatures.json
  SPECS/util-linux/util-linux.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3337 Refresh Mariner Release for July Update
  SPECS/mariner-release/mariner-release.spec
Labels: Packaging, 1.0-dev

#3338 Revert "msopenjdk-11: Upgrade to 11.0.15+10-LTS-1 (#3323)"
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
Labels: main

#3339 python3: Fix bad shabang for easy_install
  SPECS/python3/python3.spec
Labels: Packaging, 1.0-dev

#3340 disabled spuriously failing defrag test in redis
  SPECS/redis/disable_defrag_test.patch
  SPECS/redis/redis.spec
Labels: Packaging, 1.0-dev

#3342 Only build crash-gcore-command on x86_64
  SPECS/crash-gcore-command/crash-gcore-command.spec
Labels: Packaging, main

#3344 Bump Mariner 2.0 Release for July 2022 Update
  SPECS/mariner-release/mariner-release.spec
Labels: Packaging, main

#3343 Updated vim to 8.2.5172 to fix CVEs
  SPECS/vim/vim.signatures.json
  SPECS/vim/vim.spec
  cgmanifest.json
Labels: 1.0-dev

#3341 Updating `pygobject3` to fix ptest.
  SPECS/pygobject3/pygobject3.spec
Labels: Packaging, 1.0-dev

#3345 `libftdi`: disabling docs building to stabilize the build.
  SPECS-EXTENDED/libftdi/libftdi.spec
Labels: main

#3331 selinux-policy: Minor fixes for groupadd, systemd-cgroups, hv_utils.
  SPECS/selinux-policy/0040-usermanage-Add-sysctl-access-for-groupadd-to-get-num.patch
  SPECS/selinux-policy/0041-systemd-systemd-cgroups-reads-kernel.cap_last_cap-sy.patch
  SPECS/selinux-policy/0042-kernel-hv_utils-shutdown-on-systemd-systems.patch
  SPECS/selinux-policy/selinux-policy.spec
Labels: Packaging, main

#3352 [1.0] Add clang-libs subpackage to clang specfile
  SPECS/clang/clang.spec
Labels: Packaging

#3008 Add network configuration for unattended ISO install
  toolkit/docs/formats/imageconfig.md
  toolkit/tools/go.mod
  toolkit/tools/go.sum
  toolkit/tools/imagegen/configuration/configuration_test.go
  toolkit/tools/imagegen/configuration/networkconfig.go
  toolkit/tools/imagegen/configuration/networkconfig_test.go
  toolkit/tools/imagegen/configuration/systemconfig.go
  toolkit/tools/imagegen/configuration/systemconfig_test.go
  toolkit/tools/imagegen/configuration/testdata/test_configuration.json
  toolkit/tools/imagegen/installutils/installutils.go
Labels: Tools, main

#3353 README: Add 2.0 quickstart workflow badge
  README.md
Labels: main

#3358 coreutils: Fix flaky env-signal-handler test
  SPECS/coreutils/CVE-2013-0221.nopatch
  SPECS/coreutils/CVE-2013-0222.nopatch
  SPECS/coreutils/CVE-2013-0223.nopatch
  SPECS/coreutils/CVE-2016-2781.nopatch
  SPECS/coreutils/coreutils.spec
  SPECS/coreutils/fix_test_env_signal_handler.patch
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3356 cloud-init: pip install `test-requirements.txt` to enable ptest
  SPECS/cloud-init/cloud-init.spec
Labels: Packaging, main

#3357 mc, python3, vim: Fix unversioned python shebangs
  SPECS/mc/mc.spec
  SPECS/python3/cgi3.patch
  SPECS/python3/python3.spec
  SPECS/vim/vim.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3362 Add upstream patch to python-attrs to fix mypy tests
  SPECS/python-attrs/fix-mypy-tests.patch
  SPECS/python-attrs/python-attrs.spec
Labels: Packaging, main

#3364 unbound: build with libevent to fix libreswan
  SPECS/unbound/unbound.spec
Labels: Packaging, main

#3363 Upgrade vim version to 9.0.0050 to fix CVEs: 2022-2257, 2022-2264, 2022-2284, 2022-2285, 2022-2286, 2022-2287
  SPECS/vim/vim.signatures.json
  SPECS/vim/vim.spec
  cgmanifest.json
Labels: main

#3366 Upgrade vim version to 9.0.0050 to fix CVEs: 2022-2257, 2022-2264, 2022-2284, 2022-2285, 2022-2286, 2022-2287
  SPECS/vim/vim.signatures.json
  SPECS/vim/vim.spec
  cgmanifest.json
Labels: 1.0-dev

#3318 Upgrade kernel to v5.10.128.1 adressing CVE-2022-32296, CVE-2022-1652, CVE-2022-1786, CVE-2022-0854, CVE-2021-20194, CVE-2021-32078, CVE-2021-37159
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/hyperv-daemons/hyperv-daemons.signatures.json
  SPECS/hyperv-daemons/hyperv-daemons.spec
  SPECS/kernel-headers/kernel-headers.signatures.json
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel-hyperv/config
  SPECS/kernel-hyperv/kernel-hyperv.signatures.json
  SPECS/kernel-hyperv/kernel-hyperv.spec
  SPECS/kernel/CVE-2021-20194.nopatch
  SPECS/kernel/CVE-2021-32078.nopatch
  SPECS/kernel/CVE-2021-37159.nopatch
  SPECS/kernel/CVE-2022-0854.nopatch
  SPECS/kernel/CVE-2022-1652.nopatch
  SPECS/kernel/CVE-2022-1786.nopatch
  SPECS/kernel/CVE-2022-32296.nopatch
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/Dockerfile
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
  toolkit/scripts/toolchain/container/toolchain_build_temp_tools.sh
Labels: 1.0-dev

#3376 Fix opensc non-check build by disabling unit tests
  SPECS/opensc/opensc.spec
Labels: Packaging, main

#3365 Add nopatch for mcpp CVE-2019-14274
  SPECS/mcpp/CVE-2019-14274.nopatch
Labels: security, Packaging, main

#3384 Upgrade git to 2.33.4 to address CVE-2022-29187
  SPECS/git/git.signatures.json
  SPECS/git/git.spec
  cgmanifest.json
Labels: main

#3371 lua: Patch CVE-2022-33099
  SPECS/lua/CVE-2022-33099.patch
  SPECS/lua/lua.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3388 Fix libtiff CVEs: 2022-2056, 2022-2057, 2022-2058
  SPECS/libtiff/CVE-2022-2056.patch
  SPECS/libtiff/CVE-2022-2057.nopatch
  SPECS/libtiff/CVE-2022-2058.nopatch
  SPECS/libtiff/libtiff.spec
Labels: Packaging, main

#3389 Fix libtiff CVEs: 2022-2056, 2022-2057, 2022-2058
  SPECS/libtiff/CVE-2022-2056.patch
  SPECS/libtiff/CVE-2022-2057.nopatch
  SPECS/libtiff/CVE-2022-2058.nopatch
  SPECS/libtiff/libtiff.spec
Labels: Packaging, 1.0-dev

#3390 Promote fio, nbd, libnbd to base repo
  SPECS-EXTENDED/fio/fio-3.29-link-t-io_uring-with-libaio.patch
  SPECS-EXTENDED/fio/fio-3.29-use-LDFLAGS-for-dynamic-engines.patch
  SPECS-EXTENDED/fio/fio.signatures.json
  SPECS/fio/fio.signatures.json
  SPECS/fio/fio.spec
  SPECS/libnbd/libnbd.signatures.json
  SPECS/libnbd/libnbd.spec
  SPECS/nbd/nbd-server.service
  SPECS/nbd/nbd-server.sysconfig
  SPECS/nbd/nbd.signatures.json
  SPECS/nbd/nbd.spec
  cgmanifest.json
Labels: main

#3391 Set default SOURCE_URL in Makefile
  toolkit/Makefile
  toolkit/docs/building/building.md
Labels: documentation, main, DevEx

#3387 [1.0] [CVEs] Patch CVE-2022-3733 in Python2
  SPECS/python2/CVE-2021-3733.patch
  SPECS/python2/python2.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#3397 selinux-policy: Fixes for interactive container use.
  SPECS/selinux-policy/0043-Container-Minor-fixes-from-interactive-container-use.patch
  SPECS/selinux-policy/selinux-policy.spec
Labels: Packaging, main

#3399 kernel: Address cve-2022-34494 and cve-2022-34495
  SPECS/kernel/CVE-2022-34494.nopatch
  SPECS/kernel/CVE-2022-34495.nopatch
Labels: security, Packaging, 1.0-dev

#3400 Maven: For aarch64 builds
  SPECS/maven/maven.signatures.json
  SPECS/maven/maven.spec
Labels: Packaging, main

#3379 [1.0] Add Source repos for base, update, ui, preview and preview-ui
  SPECS/mariner-repos/mariner-official-base.repo
  SPECS/mariner-repos/mariner-official-update.repo
  SPECS/mariner-repos/mariner-preview.repo
  SPECS/mariner-repos/mariner-repos.signatures.json
  SPECS/mariner-repos/mariner-repos.spec
  SPECS/mariner-repos/mariner-ui-preview.repo
  SPECS/mariner-repos/mariner-ui.repo
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, 1.0-dev

#3378 [2.0] Add Source repos for base, extended
  SPECS/mariner-repos/mariner-debuginfo-preview.repo
  SPECS/mariner-repos/mariner-debuginfo.repo
  SPECS/mariner-repos/mariner-extended-debuginfo-preview.repo
  SPECS/mariner-repos/mariner-extended-debuginfo.repo
  SPECS/mariner-repos/mariner-extended-preview.repo
  SPECS/mariner-repos/mariner-extended.repo
  SPECS/mariner-repos/mariner-official-base.repo
  SPECS/mariner-repos/mariner-official-preview.repo
  SPECS/mariner-repos/mariner-repos.signatures.json
  SPECS/mariner-repos/mariner-repos.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, main

#3392 Adding sed as a post install requirement in the vim spec
  SPECS/vim/vim.spec
Labels: Packaging, main

#3398 Add missing dependencies to rpm-build
  SPECS/rpm/rpm.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#2999 argparse-manpage: pip install latest deps to enable ptest
  SPECS-EXTENDED/argparse-manpage/argparse-manpage.spec
Labels: ptest, main, specs-extended

#3404 added package: sysbench
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/sysbench/sysbench.signatures.json
  SPECS/sysbench/sysbench.spec
  cgmanifest.json
  toolkit/scripts/spec_source_attributions.py
Labels: main

#3361 Add second grub efi binary without specifying the prefix directory
  SPECS-SIGNED/grub2-efi-binary-signed/grub2-efi-binary-signed.spec
  SPECS/grub2/grub2.spec
Labels: Packaging, main

#3178 Add Cassandra Reaper Spec in Mariner.
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/reaper/Readme
  SPECS/reaper/reaper.signatures.json
  SPECS/reaper/reaper.spec
  SPECS/reaper/reaper_build_caches.sh
  cgmanifest.json
Labels: main

#3355 Add spec for libgdiplus and promote giflib, libexif to base repo
  SPECS-EXTENDED/libexif/CVE-2020-0181-CVE-2020-0198.patch
  SPECS-EXTENDED/libexif/CVE-2020-0452.patch
  SPECS-EXTENDED/libexif/libexif.signatures.json
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/giflib/giflib.signatures.json
  SPECS/giflib/giflib.spec
  SPECS/giflib/giflib_quantize.patch
  SPECS/libexif/libexif.signatures.json
  SPECS/libexif/libexif.spec
  SPECS/libgdiplus/libgdiplus.signatures.json
  SPECS/libgdiplus/libgdiplus.spec
  cgmanifest.json
Labels: main

#3395 Update `e2fsprogs`: running tests in a single thread to make them more consistent.
  SPECS/e2fsprogs/e2fsprogs.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3401 Add ability to build quickly by packing a subset of RPMs
  toolkit/Makefile
  toolkit/docs/building/building.md
  toolkit/scripts/srpm_pack.mk
  toolkit/scripts/utils.mk
Labels: main

#3393 [main] Resolve grub2 CVE-2021-3981
  SPECS-SIGNED/grub2-efi-binary-signed/grub2-efi-binary-signed.spec
  SPECS/grub2/0167-restore-umask-for-grub-config.patch
  SPECS/grub2/grub2.spec
Labels: Packaging, main

#3409 Add cpupower and turbostat to kernel-tools
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#2998 python-pytest-subtests: drop BR on pytest & pip install latest deps to enable ptest
  SPECS-EXTENDED/python-pytest-subtests/python-pytest-subtests.spec
  cgmanifest.json
Labels: ptest, main, specs-extended

#3413 python-requests-toolbelt: pip install latest deps to enable ptest
  SPECS-EXTENDED/python-requests-toolbelt/python-requests-toolbelt.spec
Labels: ptest, main, specs-extended

#3000 python-pytest-timeout: drop BR on pytest and install latest deps to enable ptest
  SPECS-EXTENDED/python-pytest-timeout/python-pytest-timeout.spec
  cgmanifest.json
Labels: ptest, main, specs-extended

#3407 SELinux backport for (interactive container use, fds manipulation and minor fixes)
  SPECS/selinux-policy/0039-unconfined-Manage-own-fds.patch
  SPECS/selinux-policy/0040-usermanage-Add-sysctl-access-for-groupadd-to-get-num.patch
  SPECS/selinux-policy/0041-systemd-systemd-cgroups-reads-kernel.cap_last_cap-sy.patch
  SPECS/selinux-policy/0042-kernel-hv_utils-shutdown-on-systemd-systems.patch
  SPECS/selinux-policy/0043-Container-Minor-fixes-from-interactive-container-use.patch
  SPECS/selinux-policy/selinux-policy.spec
Labels: Packaging, 1.0-dev

#3410 [2.0] Resolve protobuf-c CVE-2022-33070
  SPECS/protobuf-c/CVE-2022-33070.patch
  SPECS/protobuf-c/protobuf-c.spec
Labels: Packaging, main

#3411 Updated `perl-Sys-Virt`, `pyproject-rpm-macros`, and `python-flit`: fixing ptests.
  SPECS-EXTENDED/perl-XML-XPath/perl-XML-XPath.signatures.json
  SPECS/perl-CPAN-Changes/perl-CPAN-Changes.signatures.json
  SPECS/perl-CPAN-Changes/perl-CPAN-Changes.spec
  SPECS/perl-XML-XPath/perl-XML-XPath.signatures.json
  SPECS/perl-XML-XPath/perl-XML-XPath.spec
  SPECS/pyproject-rpm-macros/pyproject-rpm-macros.spec
  SPECS/python-flit/python-flit.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3416 Revert "Add Cassandra Reaper Spec in Mariner. (#3178)"
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/reaper/Readme
  SPECS/reaper/reaper.signatures.json
  SPECS/reaper/reaper.spec
  SPECS/reaper/reaper_build_caches.sh
  cgmanifest.json
Labels: main

#3415 Kernel upgrade to version 5.15.55.1
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/hyperv-daemons/hyperv-daemons.signatures.json
  SPECS/hyperv-daemons/hyperv-daemons.spec
  SPECS/kernel-headers/kernel-headers.signatures.json
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/CVE-2022-2318.nopatch
  SPECS/kernel/CVE-2022-34918.nopatch
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3418 Fix podman installation and feature functionality issues
  SPECS-EXTENDED/containernetworking-plugins/containernetworking-plugins.signatures.json
  SPECS-EXTENDED/containernetworking-plugins/containernetworking-plugins.spec
  SPECS-EXTENDED/podman/podman.signatures.json
  SPECS-EXTENDED/podman/podman.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/conmon/conmon.signatures.json
  SPECS/conmon/conmon.spec
  SPECS/libcontainers-common/containers.conf
  SPECS/libcontainers-common/libcontainers-common.signatures.json
  SPECS/libcontainers-common/libcontainers-common.spec
  SPECS/libcontainers-common/mounts.conf
  SPECS/libcontainers-common/storage.conf
  SPECS/netavark/netavark.signatures.json
  SPECS/netavark/netavark.spec
  cgmanifest.json
Labels: main

#3405 Add pam_krb5 to Mariner
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/pam_krb5/0001-Drop-module-long-test.patch
  SPECS/pam_krb5/pam_krb5.signatures.json
  SPECS/pam_krb5/pam_krb5.spec
  cgmanifest.json
Labels: main

#3426 Adding umoci package to SPECS-extended
  SPECS-EXTENDED/umoci/umoci.signatures.json
  SPECS-EXTENDED/umoci/umoci.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#3417 python-whoosh: pip install `wheel` in %check section to enable ptest
  SPECS-EXTENDED/python-whoosh/python-whoosh.signatures.json
  SPECS-EXTENDED/python-whoosh/python-whoosh.spec
  cgmanifest.json
Labels: ptest, main, specs-extended

#3431 kernel: update to 5.10.131.1
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/hyperv-daemons/hyperv-daemons.signatures.json
  SPECS/hyperv-daemons/hyperv-daemons.spec
  SPECS/kernel-headers/kernel-headers.signatures.json
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel-hyperv/config
  SPECS/kernel-hyperv/kernel-hyperv.signatures.json
  SPECS/kernel-hyperv/kernel-hyperv.spec
  SPECS/kernel/CVE-2022-2318.nopatch
  SPECS/kernel/CVE-2022-34918.nopatch
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/Dockerfile
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
  toolkit/scripts/toolchain/container/toolchain_build_temp_tools.sh
Labels: 1.0-dev

#3434 Add ctags SPEC to Mariner
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/ctags/ctags.signatures.json
  SPECS/ctags/ctags.spec
  cgmanifest.json
Labels: main

#3437 libreswan: move to SPECS along with dependencies
  SPECS/ldns/ldns-1.7.0-Update-for-SWIG-4.patch
  SPECS/ldns/ldns-1.7.0-multilib.patch
  SPECS/ldns/ldns-1.7.0-parse-limit.patch
  SPECS/ldns/ldns-1.7.0-realloc.patch
  SPECS/ldns/ldns.signatures.json
  SPECS/ldns/ldns.spec
  SPECS/libreswan/libreswan.signatures.json
  SPECS/libreswan/libreswan.spec
  SPECS/perl-Capture-Tiny/perl-Capture-Tiny.signatures.json
  SPECS/perl-Capture-Tiny/perl-Capture-Tiny.spec
  SPECS/perl-Devel-CheckLib/perl-Devel-CheckLib.signatures.json
  SPECS/perl-Devel-CheckLib/perl-Devel-CheckLib.spec
  SPECS/perl-Mock-Config/perl-Mock-Config.signatures.json
  SPECS/perl-Mock-Config/perl-Mock-Config.spec
Labels: Packaging, main

#3438 Remove the patches to update to python3
  SPECS/libhugetlbfs/0006-huge_page_setup_helper-python3-convert.patch
  SPECS/libhugetlbfs/libhugetlbfs.spec
Labels: Packaging, main

#3432 [2.0] Update blobfuse version to 1.4.4
  SPECS/blobfuse/blobfuse.signatures.json
  SPECS/blobfuse/blobfuse.spec
  cgmanifest.json
Labels: main

#3444 Updating `mariner-release` version for July update 2.
  SPECS/mariner-release/mariner-release.spec
Labels: Packaging, main

#3433 perl-File-Find-Object-Rule: add BR on `perl(blib)` to enable ptest
  SPECS-EXTENDED/perl-File-Find-Object-Rule/perl-File-Find-Object-Rule.spec
Labels: ptest, main, specs-extended

#3441 Bring back "Add Cassandra Reaper Spec in Mariner".
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/reaper/Readme
  SPECS/reaper/reaper.signatures.json
  SPECS/reaper/reaper.spec
  SPECS/reaper/reaper_build_caches.sh
  cgmanifest.json
Labels: main

#3436 Add skopeo package to SPECS
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/skopeo/skopeo.signatures.json
  SPECS/skopeo/skopeo.spec
  cgmanifest.json
Labels: main

#3303 Adding xxhash SPEC to Mariner
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/xxhash/xxhash.signatures.json
  SPECS/xxhash/xxhash.spec
  cgmanifest.json
Labels: main

#3304 Moving symlinks spec from SPECS-EXTENDED to SPECS directory.
  SPECS/symlinks/symlinks-LICENSE.txt
  SPECS/symlinks/symlinks.signatures.json
  SPECS/symlinks/symlinks.spec
  cgmanifest.json
Labels: Packaging, main

#3308 Adding python-retrying SPEC in CBL-Mariner
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/python-retrying/python-retrying.signatures.json
  SPECS/python-retrying/python-retrying.spec
  cgmanifest.json
Labels: main

#3319 Move python-click to SPECS folder and bump version to 8.0.4 based on fedora 36 imprt.
  SPECS-EXTENDED/python-click/python-click.signatures.json
  SPECS/python-click/python-click.signatures.json
  SPECS/python-click/python-click.spec
  cgmanifest.json
Labels: main

#3320 Adding python-cassandra-driver Spec in CBL-Mariner.
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/python-cassandra-driver/python-cassandra-driver.signatures.json
  SPECS/python-cassandra-driver/python-cassandra-driver.spec
  cgmanifest.json
Labels: main

#3321 Adding python-botocore Spec in CBL-Mariner
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/python-botocore/python-botocore.signatures.json
  SPECS/python-botocore/python-botocore.spec
  cgmanifest.json
Labels: main

#3440 ucx: move to SPECS
  SPECS/ucx/ucx.signatures.json
  SPECS/ucx/ucx.spec
Labels: Packaging, main

#3448 Update python-jinja2 to v2.11.3 to fix CVE-2020-28493
  SPECS/python-jinja2/python-jinja2.signatures.json
  SPECS/python-jinja2/python-jinja2.spec
  cgmanifest.json
Labels: 1.0-dev

#3443 Update postgresql to v12.8 to fix CVE-2021-3677
  SPECS/postgresql/postgresql.signatures.json
  SPECS/postgresql/postgresql.spec
  cgmanifest.json
Labels: 1.0-dev

#3451 fixed ptest issue with sysbench.
  SPECS/sysbench/enable-python3.patch
  SPECS/sysbench/sysbench.spec
Labels: Packaging, main

#3449 perl-Crypt-SSLeay: add BR on `perl(Test::More)` & `perl(Bytes::Random::Secure)` to enable ptest
  SPECS/perl-Crypt-SSLeay/perl-Crypt-SSLeay.spec
Labels: Packaging, ptest, main

#3450 perl-File-Which: add BR on `perl-{(Env),(ExtUtils::MakeMaker),(Test::More)}` to enable ptest
  SPECS/perl-File-Which/perl-File-Which.spec
Labels: Packaging, ptest, main

#3445 perl-Object-Deadly: add an explicit BR on `perl(English)` to enable ptest
  SPECS-EXTENDED/perl-Object-Deadly/perl-Object-Deadly.spec
Labels: ptest, main, specs-extended

#3420 ofed-scripts: initial import
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/ofed-scripts/ofed-scripts.signatures.json
  SPECS/ofed-scripts/ofed-scripts.spec
  cgmanifest.json
  toolkit/scripts/spec_source_attributions.py
Labels: main

#3447 python-testscenarios: add BR on `pip` to enable ptest
  SPECS-EXTENDED/python-testscenarios/python-testscenarios.spec
Labels: ptest, main, specs-extended

#3446 python-requests-mock: switch to `tox` for testing
  SPECS-EXTENDED/python-requests-mock/0001-tox-add-py39-environment.patch
  SPECS-EXTENDED/python-requests-mock/python-requests-mock.spec
Labels: ptest, main, specs-extended

#3204 Fix network access check during package repo file generation
  toolkit/tools/internal/network/network.go
Labels: Tools, Schema, main

#3455 Revert "Adding python-cassandra-driver Spec in CBL-Mariner. (#3320)"
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/python-cassandra-driver/python-cassandra-driver.signatures.json
  SPECS/python-cassandra-driver/python-cassandra-driver.spec
  cgmanifest.json
Labels: main

#3457 Revert "Adding python-botocore Spec in CBL-Mariner (#3321)"
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/python-botocore/python-botocore.signatures.json
  SPECS/python-botocore/python-botocore.spec
  cgmanifest.json
Labels: main

#3456 Revert "Move python-click to SPECS folder and bump version to 8.0.4 b…
  SPECS-EXTENDED/python-click/python-click.signatures.json
  SPECS-EXTENDED/python-click/python-click.spec
  SPECS/python-click/python-click.signatures.json
  cgmanifest.json
Labels: main

#3412 Fixes the k3s install to allow VHDX integration.
  SPECS/k3s/install.patch
  SPECS/k3s/k3s.spec
Labels: Packaging, main

#3454 Update nodejs to v14.20.0 to fix CVEs 2022-32213, 2022-32214, 2022-32215
  SPECS/nodejs/nodejs.signatures.json
  SPECS/nodejs/nodejs.spec
  cgmanifest.json
Labels: 1.0-dev

#3421 perftest: Initial import into Mariner
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/perftest/perftest.signatures.json
  SPECS/perftest/perftest.spec
  cgmanifest.json
Labels: main

#3423 knem: initial import
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/knem/knem.signatures.json
  SPECS/knem/knem.spec
  cgmanifest.json
Labels: main

#3425 mlx-bootctl: intial import
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/mlx-bootctl/mlx-bootctl.signatures.json
  SPECS/mlx-bootctl/mlx-bootctl.spec
  cgmanifest.json
Labels: main

#3424 mlnx-ofa_kernel and mlx-tools: inital import
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/mlnx-ofa_kernel/mlnx-ofa_kernel.signatures.json
  SPECS/mlnx-ofa_kernel/mlnx-ofa_kernel.spec
  SPECS/mlnx-tools/mlnx-tools.signatures.json
  SPECS/mlnx-tools/mlnx-tools.spec
  cgmanifest.json
Labels: main

#3461 Remove unneeded provides for grub2-efi-binary-noprefix
  SPECS-SIGNED/grub2-efi-binary-signed/grub2-efi-binary-signed.spec
  SPECS/grub2/grub2.spec
Labels: Packaging, main
