Repository microsoft/azurelinux, pull requests merged in 2022-06, with the labels that each got.

#3082 Adding run-time dependencies for `perl-Crypt-SSLeay`.
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/perl-Bytes-Random-Secure/perl-Bytes-Random-Secure.signatures.json
  SPECS/perl-Bytes-Random-Secure/perl-Bytes-Random-Secure.spec
  SPECS/perl-Crypt-Random-Seed/perl-Crypt-Random-Seed.signatures.json
  SPECS/perl-Crypt-Random-Seed/perl-Crypt-Random-Seed.spec
  SPECS/perl-Devel-StackTrace/perl-Devel-StackTrace.signatures.json
  SPECS/perl-Devel-StackTrace/perl-Devel-StackTrace.spec
  SPECS/perl-Math-Random-ISAAC/perl-Math-Random-ISAAC.signatures.json
  SPECS/perl-Math-Random-ISAAC/perl-Math-Random-ISAAC.spec
  SPECS/perl-Module-Install-AuthorTests/LICENSE.PTR
  SPECS/perl-Module-Install-AuthorTests/perl-Module-Install-AuthorTests.signatures.json
  SPECS/perl-Module-Install-AuthorTests/perl-Module-Install-AuthorTests.spec
  SPECS/perl-Module-Install-Repository/LICENSE.PTR
  SPECS/perl-Module-Install-Repository/Module-Install-Repository-0.06-Fix-building-on-Perl-without-dot-in-INC.patch
  SPECS/perl-Module-Install-Repository/perl-Module-Install-Repository.signatures.json
  SPECS/perl-Module-Install-Repository/perl-Module-Install-Repository.spec
  SPECS/perl-Test-LeakTrace/LICENSE.PTR
  SPECS/perl-Test-LeakTrace/perl-Test-LeakTrace.signatures.json
  SPECS/perl-Test-LeakTrace/perl-Test-LeakTrace.spec
  SPECS/perl-Test-NoWarnings/perl-Test-NoWarnings.signatures.json
  SPECS/perl-Test-NoWarnings/perl-Test-NoWarnings.spec
  cgmanifest.json
Labels: main

#3075 ruby: Upgrade to 2.6.10 to fix CVE-2022-28739
  SPECS/ruby/ruby.signatures.json
  SPECS/ruby/ruby.spec
  cgmanifest.json
Labels: 1.0-dev

#3089 node-problem-detector: Add explicit check/run-time dependencies on mariner-release
  SPECS/node-problem-detector/node-problem-detector.spec
Labels: Packaging, main

#3081 selinux-policy: (backport) additional container/kubernetes patches + fixes from baremetal testing.
  SPECS/selinux-policy/0017-Add-cloud-init.patch
  SPECS/selinux-policy/0018-Add-compatibility-for-container-selinux.patch
  SPECS/selinux-policy/0019-systemd-Remove-systemd-run-domain.patch
  SPECS/selinux-policy/0020-unconfined-Add-missing-capability2-perms.patch
  SPECS/selinux-policy/0021-lvm-Updates-for-multipath-LVM.patch
  SPECS/selinux-policy/0022-locallogin-Use-init-file-descriptors.patch
  SPECS/selinux-policy/0023-systemd-Misc-fixes.patch
  SPECS/selinux-policy/0024-isns-Updates-from-testing.patch
  SPECS/selinux-policy/0025-container-docker-Fixes-for-containerd-and-kubernetes.patch
  SPECS/selinux-policy/0026-devices-Add-type-for-SAS-management-devices.patch
  SPECS/selinux-policy/0027-devices-Add-file-context-for-dev-vhost-vsock.patch
  SPECS/selinux-policy/0028-Add-dac_read_search-perms.patch
  SPECS/selinux-policy/0029-iptables-Ioctl-cgroup-dirs.patch
  SPECS/selinux-policy/0030-container-allow-containers-to-manipulate-own-fds.patch
  SPECS/selinux-policy/0031-devices-Add-type-for-infiniband-devices.patch
  SPECS/selinux-policy/0032-storage-Add-fc-for-dev-ng-n-devices.patch
  SPECS/selinux-policy/0033-files-Add-prerequisite-access-for-files_mounton_non_.patch
  SPECS/selinux-policy/0034-files-Make-etc_runtime_t-a-config-file.patch
  SPECS/selinux-policy/0035-systemd-Fixes-for-coredumps-in-containers.patch
  SPECS/selinux-policy/0036-container-Allow-container-engines-to-connect-to-http.patch
  SPECS/selinux-policy/0037-container-Getattr-generic-device-nodes.patch
  SPECS/selinux-policy/0038-application-Allow-apps-to-use-init-fds.patch
  SPECS/selinux-policy/selinux-policy.spec
Labels: Packaging, 1.0-dev

#3093 openldap: fix CVE-2022-29155
  SPECS/openldap/CVE-2022-29155.patch
  SPECS/openldap/openldap.spec
Labels: Packaging, main

#3092 ntfs-3g: Updating to 2022.5.17 to fix CVE-2021-46790
  SPECS/ntfs-3g/ntfs-3g.signatures.json
  SPECS/ntfs-3g/ntfs-3g.spec
  cgmanifest.json
Labels: main

#3096 hyperv-daemons/hypervkvpd.service: fix service ordering
  SPECS/hyperv-daemons/hyperv-daemons.spec
  SPECS/hyperv-daemons/hypervkvpd.service
Labels: Packaging, main

#3099 `prebuilt-ca-certificates`: adding `Provides` for `*-microsoft` and `*-mozilla`.
  SPECS/ca-certificates/ca-certificates.spec
  SPECS/prebuilt-ca-certificates-base/prebuilt-ca-certificates-base.spec
  SPECS/prebuilt-ca-certificates/prebuilt-ca-certificates.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#3100 [main] `prebuilt-ca-certificates`: adding `Provides` for `*-microsoft` and `*-mozilla`.
  SPECS/ca-certificates/ca-certificates.spec
  SPECS/prebuilt-ca-certificates-base/prebuilt-ca-certificates-base.spec
  SPECS/prebuilt-ca-certificates/prebuilt-ca-certificates.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3101 ARM64 `buildah` and `edk2` blocked packages fix.
  SPECS-EXTENDED/edk2/edk2.spec
  SPECS/ostree/ostree.spec
Labels: main

#3103 `php`: adding a patch to build with updated `gd`.
  SPECS-EXTENDED/php/php-7.4.14-gd.patch
  SPECS-EXTENDED/php/php.spec
Labels: main

#2957 python-mutagen: drop BR on pytest & pip install latests deps to enable ptest
  SPECS-EXTENDED/python-mutagen/python-mutagen.spec
Labels: ptest, main, specs-extended

#3102 moby-runc: Upgrade to 1.1.2 to fix CVE-2022-29162
  SPECS/moby-runc/moby-runc.signatures.json
  SPECS/moby-runc/moby-runc.spec
  cgmanifest.json
Labels: main

#3035 ruby: remove bundled gems, add provides for default gems
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/ruby/ruby.spec
  SPECS/rubygem-bigdecimal/rubygem-bigdecimal.spec
  SPECS/rubygem-bundler/rubygem-bundler.spec
  SPECS/rubygem-concurrent-ruby/rubygem-concurrent-ruby.spec
  SPECS/rubygem-hoe/rubygem-hoe.spec
  SPECS/rubygem-io-console/rubygem-io-console.signatures.json
  SPECS/rubygem-io-console/rubygem-io-console.spec
  SPECS/rubygem-json/rubygem-json.signatures.json
  SPECS/rubygem-json/rubygem-json.spec
  SPECS/rubygem-minitest/minitest.gemspec
  SPECS/rubygem-minitest/rubygem-minitest.signatures.json
  SPECS/rubygem-minitest/rubygem-minitest.spec
  SPECS/rubygem-mocha/rubygem-mocha.spec
  SPECS/rubygem-openssl/rubygem-openssl.signatures.json
  SPECS/rubygem-openssl/rubygem-openssl.spec
  SPECS/rubygem-power_assert/rubygem-power_assert.signatures.json
  SPECS/rubygem-power_assert/rubygem-power_assert.spec
  SPECS/rubygem-psych/rubygem-psych.signatures.json
  SPECS/rubygem-psych/rubygem-psych.spec
  SPECS/rubygem-rake/rubygem-rake.signatures.json
  SPECS/rubygem-rake/rubygem-rake.spec
  SPECS/rubygem-rdoc/remove_files_from_gitignore.patch
  SPECS/rubygem-rdoc/rubygem-rdoc.signatures.json
  SPECS/rubygem-rdoc/rubygem-rdoc.spec
  SPECS/rubygem-stringio/rubygem-stringio.signatures.json
  SPECS/rubygem-stringio/rubygem-stringio.spec
  SPECS/rubygem-test-unit/rubygem-test-unit.signatures.json
  SPECS/rubygem-test-unit/rubygem-test-unit.spec
  cgmanifest.json
Labels: main

#3080 kernel: Remove Smack LSM support from kernel
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3091 Mingheren/kernel smack update 1.0
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#3107 `kernel`: enabling livepatching.
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3109 Fix signature of hypervkvpd.service
  SPECS/hyperv-daemons/hyperv-daemons.signatures.json
Labels: Packaging, main

#3112 `vim`: updating to version 8.2.5064 to fix CVE-2022-1851, CVE-2022-1886, and CVE-2022-1898.
  SPECS/vim/vim.signatures.json
  SPECS/vim/vim.spec
  cgmanifest.json
Labels: main

#3115 `vim`: updating to version 8.2.5064 to fix CVE-2022-1851, CVE-2022-1886, and CVE-2022-1898.
  SPECS/vim/vim.signatures.json
  SPECS/vim/vim.spec
  cgmanifest.json
Labels: 1.0-dev

#3059 Updating `.gitignore` to ignore default sources download directory.
  .gitignore
Labels: Tools, main

#3117 td-agent: Bump ruby version requirement to 2.6.10
  SPECS/td-agent/td-agent.patch
  SPECS/td-agent/td-agent.spec
Labels: Packaging, 1.0-dev

#3119 `subversion`: updating to 1.14.2 to fix CVE-2021-28544.
  SPECS/subversion/subversion.signatures.json
  SPECS/subversion/subversion.spec
  cgmanifest.json
Labels: main

#3122 kernel: silencing ptp_kvm failure during boot
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3125 [1.0] Add parameters to distroless manifest
  toolkit/tools/imagegen/installutils/installutils.go
Labels: Tools, 1.0-dev

#2766 Commonize toolchain rpm extract flows
  toolkit/scripts/pkggen.mk
  toolkit/scripts/toolchain.mk
  toolkit/scripts/tools.mk
  toolkit/scripts/utils.mk
  toolkit/tools/internal/pkggraph/pkggraph.go
Labels: Tools, main

#2925 [main] Add custom package repo definitions in image configuration
  toolkit/tools/imagegen/configuration/configuration_test.go
  toolkit/tools/imagegen/configuration/packagerepo.go
  toolkit/tools/imagegen/configuration/packagerepo_test.go
  toolkit/tools/imagegen/configuration/systemconfig.go
  toolkit/tools/imagegen/configuration/systemconfig_test.go
  toolkit/tools/imagegen/configuration/testdata/test_configuration.json
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/internal/network/network.go
  toolkit/tools/isomaker/maker.go
Labels: Tools, main

#3133 Bump Mariner Release version for Jun 2022 update
  SPECS/mariner-release/mariner-release.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#3126 disable smack in kernel-rt
  SPECS/kernel-rt/config
  SPECS/kernel-rt/kernel-rt.signatures.json
  SPECS/kernel-rt/kernel-rt.spec
Labels: Packaging, main

#3127 Update moby-containerd to 1.6.6+azure to fix CVE-2022-31030
  SPECS/moby-containerd/CVE-2022-23648.patch
  SPECS/moby-containerd/generate-sources.sh
  SPECS/moby-containerd/moby-containerd.signatures.json
  SPECS/moby-containerd/moby-containerd.spec
  cgmanifest.json
Labels: 1.0-dev

#3130 `lua`: patching CVE-2021-44647.
  SPECS/lua/CVE-2021-44647.patch
  SPECS/lua/lua.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3132 `util-linux`: updating to 2.37.4 to fix CVE-2022-0563.
  SPECS/util-linux/util-linux.signatures.json
  SPECS/util-linux/util-linux.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/toolchain-remote-wget-list
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
Labels: main

#3131 Add packer tool SPEC and remove packer symlink in cracklib-dicts conflicts with packer tool
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/cracklib/cracklib.spec
  SPECS/packer/packer.signatures.json
  SPECS/packer/packer.spec
  cgmanifest.json
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3134 Nopatching CVE-2009-1890 as this is not in Apache version 2.4.53
  SPECS/httpd/CVE-2009-1890.nopatch
Labels: security, Packaging, 1.0-dev

#3135 Upgrade terraform version to 1.2.2
  SPECS/cracklib/cracklib.spec
  SPECS/packer/packer.spec
  SPECS/terraform/terraform.signatures.json
  SPECS/terraform/terraform.spec
  cgmanifest.json
Labels: main

#3140 Bump Mariner Release for Incremental CVE Fixes
  SPECS/mariner-release/mariner-release.spec
Labels: Packaging, main

#3136 Fix clamav
  SPECS/clamav/clamav.spec
Labels: Packaging, main

#3143 `ruby-augeas`: fixing build by adding missing BR.
  SPECS-EXTENDED/ruby-augeas/ruby-augeas.spec
  cgmanifest.json
Labels: main

#3147 Updating `.gitignore` and removing an archive.
  .gitignore
  SPECS-EXTENDED/t1lib/t1lib_5.1.2-3.diff.gz
Labels: main

#2963 Record build state into a CSV
  toolkit/scripts/pkggen.mk
  toolkit/tools/scheduler/scheduler.go
  toolkit/tools/scheduler/schedulerutils/printresults.go
Labels: Tools, main

#3104 cloud-init: uprev to 22.2
  SPECS/cloud-init/add-mariner-distro-support.patch
  SPECS/cloud-init/cloud-init.signatures.json
  SPECS/cloud-init/cloud-init.spec
  cgmanifest.json
Labels: Packaging, main

#3138 `bind`: updating to 9.16.29 to fix CVE-2021-25219.
  SPECS/bind/CVE-2019-6470.nopatch
  SPECS/bind/CVE-2020-8623.nopatch
  SPECS/bind/bind-9.10-dist-native-pkcs11.patch
  SPECS/bind/bind-9.14-config-pkcs11.patch
  SPECS/bind/bind.signatures.json
  SPECS/bind/bind.spec
  cgmanifest.json
Labels: main

#3148 Upgrade exiv2 to 0.27.5 to fix CVE-2019-13504 CVE-2019-17402 CVE-2019…
  SPECS-EXTENDED/exiv2/exiv2.signatures.json
  SPECS-EXTENDED/exiv2/exiv2.spec
  cgmanifest.json
Labels: main

#3123 Update SymCrypt and SCOSSL SPEC files to latest
  SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.signatures.json
  SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.spec
  SPECS/SymCrypt/SymCrypt.signatures.json
  SPECS/SymCrypt/SymCrypt.spec
  cgmanifest.json
Labels: Packaging, main

#3157 [1.0-dev] Revert "Update moby-containerd to 1.6.6+azure to fix CVE-2022-31030 (…
  SPECS/moby-containerd/CVE-2022-23648.patch
  SPECS/moby-containerd/generate-sources.sh
  SPECS/moby-containerd/moby-containerd.signatures.json
  SPECS/moby-containerd/moby-containerd.spec
  cgmanifest.json
Labels: 1.0-dev

#3141 add missing e2fsprogs dep to cloud-init
  SPECS/cloud-init/cloud-init.spec
Labels: Packaging, main

#3156 add distroless RPM manifest format to toolchain doc
  toolkit/docs/how_it_works/5_misc.md
Labels: documentation, main

#3152 libtiff: bump version to 4.4.0 to address CVE-2022-1622 & CVE-2022-1623
  SPECS/libtiff/CVE-2022-0561.patch
  SPECS/libtiff/CVE-2022-0562.patch
  SPECS/libtiff/CVE-2022-0865.patch
  SPECS/libtiff/CVE-2022-0891.patch
  SPECS/libtiff/CVE-2022-0907.patch
  SPECS/libtiff/CVE-2022-0908.patch
  SPECS/libtiff/CVE-2022-0909.patch
  SPECS/libtiff/CVE-2022-0924.patch
  SPECS/libtiff/CVE-2022-1056.nopatch
  SPECS/libtiff/CVE-2022-22844.patch
  SPECS/libtiff/libtiff.signatures.json
  SPECS/libtiff/libtiff.spec
  cgmanifest.json
Labels: security, main

#3153 tools: gomod: bump gonum to 0.11.0 to fix segfault in `graph/iterator.(*mapIter).next`
  toolkit/tools/go.mod
  toolkit/tools/go.sum
Labels: Tools, main

#3154 libarchive: bump version to 3.6.1 to address CVE-2022-26280
  SPECS/libarchive/libarchive.signatures.json
  SPECS/libarchive/libarchive.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, main

#3166 Fix util-linux source unpacking in raw toolchain
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
Labels: Tools, main

#3168 Add emacs SPEC to Mariner
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/emacs/emacs.signatures.json
  SPECS/emacs/emacs.spec
  cgmanifest.json
Labels: main

#3155 logrotate: bump version to 3.20.1 to address CVE-2022-1348
  SPECS/logrotate/logrotate.signatures.json
  SPECS/logrotate/logrotate.spec
  cgmanifest.json
Labels: security, main

#3159 [1.0] Upgrade ncurses to 6.3 to fix CVE-2022-29458
  SPECS/ncurses/CVE-2021-39537.patch
  SPECS/ncurses/ncurses.signatures.json
  SPECS/ncurses/ncurses.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#3160 [2.0] Upgrade ncurses to 6.3 to fix CVE-2022-29458
  SPECS/ncurses/CVE-2021-39537.patch
  SPECS/ncurses/ncurses.signatures.json
  SPECS/ncurses/ncurses.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3151 Update Wireshark 3.4.14 to fix CVE-2021-4181 CVE-2021-4182 CVE-2021-4184 CVE-2021-4185 CVE-2021-4186 CVE-2021-4190 CVE-2021-22207 CVE-2021-22222 CVE-2021-22235 CVE-2021-39920 CVE-2021-39921 CVE-2021-39922 CVE-2021-39923 CVE-2021-39924 CVE-2021-39925 CVE-2021-39926 CVE-2021-39928 CVE-2021-39929 CVE-2022-0581 CVE-2022-0582 CVE-2022-0583 CVE-2022-0585 CVE-2022-0586
  SPECS-EXTENDED/wireshark/SIGNATURES-3.4.4.txt
  SPECS-EXTENDED/wireshark/wireshark.signatures.json
  SPECS-EXTENDED/wireshark/wireshark.spec
  cgmanifest.json
Labels: main

#3165 Upgrade libxml2 to 2.9.14 to fix CVE-2022-29824
  SPECS/libxml2/libxml2.signatures.json
  SPECS/libxml2/libxml2.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#3167 toolchain: Remove nspr package
  SPECS/nspr/nspr.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/resources/manifests/package/update_manifests.sh
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
  toolkit/scripts/toolchain/container/toolchain-remote-wget-list
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
Labels: main

#3169 [1.0-dev] Fix openssl packages test failure
  SPECS/openssl/openssl-1.1.1-update-expired-cert.patch
  SPECS/openssl/openssl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#3012 Add pxe-boot support in Mariner installer
  toolkit/resources/imageconfigs/additionalfiles/iso_initrd/root/runliveinstaller
  toolkit/resources/imageconfigs/packagelists/iso-initrd-packages.json
Labels: main

#3144 [main] Update kernel to 5.15.45.1; kernel-rt to 5.15.44.1
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/hyperv-daemons/hyperv-daemons.signatures.json
  SPECS/hyperv-daemons/hyperv-daemons.spec
  SPECS/kernel-headers/kernel-headers.signatures.json
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel-rt/config
  SPECS/kernel-rt/kernel-rt.signatures.json
  SPECS/kernel-rt/kernel-rt.spec
  SPECS/kernel-rt/patch-5.15.44-rt46.patch
  SPECS/kernel/CVE-2022-32250.nopatch
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/Dockerfile
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
  toolkit/scripts/toolchain/container/toolchain_build_temp_tools.sh
  toolkit/scripts/update_kernel.sh
Labels: main

#3171 Adding `kpatch` package and updating `kernel.spec`.
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel-rt/kernel-rt.spec
  SPECS/kernel/kernel.spec
  SPECS/kpatch/kpatch.signatures.json
  SPECS/kpatch/kpatch.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3173 qemu: address CVE-2021-4206
  SPECS/qemu/CVE-2021-4206.patch
  SPECS/qemu/qemu.spec
Labels: security, Packaging, main

#3172 redis: bump version to 6.2.7 to address CVE-2022-24736
  SPECS/redis/redis.signatures.json
  SPECS/redis/redis.spec
  cgmanifest.json
Labels: security, main

#3177 telegraf: bump version to 1.23.0
  SPECS/telegraf/telegraf.signatures.json
  SPECS/telegraf/telegraf.spec
  cgmanifest.json
Labels: security, main

#3176 selinux-policy: Allow unconfined domains to manipulate their own fds.
  SPECS/selinux-policy/0039-unconfined-Manage-own-fds.patch
  SPECS/selinux-policy/selinux-policy.spec
Labels: Packaging, main

#3180 zsh: Fix package install by fixing shebang lines in included scripts
  SPECS/zsh/fix-script-shebangs.patch
  SPECS/zsh/zsh.spec
Labels: Packaging, main

#3181 filesystem: Fix issues when upgrading in container
  SPECS/filesystem/filesystem.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3184 Fix build errors caused by ncurses 6.3 upgrade
  SPECS/gfs2-utils/fix-format-security.patch
  SPECS/gfs2-utils/gfs2-utils.spec
  SPECS/gptfdisk/fix-format-security.patch
  SPECS/gptfdisk/gptfdisk.spec
  SPECS/irqbalance/fix-format-security.patch
  SPECS/irqbalance/irqbalance.spec
Labels: Packaging, main

#3191 Fix ARM64 Build Break
  SPECS/kpatch/kpatch.spec
Labels: Packaging, main

#3192 t1lib: Fix SRPM packing
  SPECS-EXTENDED/t1lib/t1lib.spec
  SPECS-EXTENDED/t1lib/t1lib_5.1.2-3.patch
  cgmanifest.json
Labels: main

#3190 Restore link to documentation in readme
  README.md
Labels: main

#3149 mariner-rpm-macros: utilize other macros
  SPECS/mariner-rpm-macros/macros
  SPECS/mariner-rpm-macros/mariner-rpm-macros.signatures.json
  SPECS/mariner-rpm-macros/mariner-rpm-macros.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3201 dpkg: bump version to 1.20.10 to address CVE-2022-1664
  SPECS-EXTENDED/dpkg/dpkg.signatures.json
  SPECS-EXTENDED/dpkg/dpkg.spec
  cgmanifest.json
Labels: main, specs-extended

#3199 php: remove stale entries from `signatures.json`
  SPECS-EXTENDED/php/php.signatures.json
Labels: main, specs-extended

#3188 Update kernel to v5.15.48.1
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/hyperv-daemons/hyperv-daemons.signatures.json
  SPECS/hyperv-daemons/hyperv-daemons.spec
  SPECS/kernel-headers/kernel-headers.signatures.json
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/Dockerfile
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
  toolkit/scripts/toolchain/container/toolchain_build_temp_tools.sh
  toolkit/scripts/update_kernel.sh
Labels: main

#3187 core-packages: Remove nspr, nss-libs from base container image
  SPECS/core-packages/core-packages.spec
Labels: Packaging, main

#3194 Upgrade uclibc-ng to 1.0.41 to fix CVE-2022-30295
  SPECS/uclibc-ng/CVE-2021-43523.patch
  SPECS/uclibc-ng/uclibc-ng.signatures.json
  SPECS/uclibc-ng/uclibc-ng.spec
  cgmanifest.json
Labels: 1.0-dev

#3150 Add libreswan to SPECS-EXTENDED
  SPECS-EXTENDED/libreswan/libreswan.signatures.json
  SPECS-EXTENDED/libreswan/libreswan.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#3200 Resolve /etc/my.cnf conflict
  SPECS/mariadb-connector-c/mariadb-connector-c.spec
  cgmanifest.json
Labels: Packaging, main

#3205 kernel: nopatch CVE-2022-1966, 2022-1998, 2022-32296
  SPECS/kernel/CVE-2022-1966.nopatch
  SPECS/kernel/CVE-2022-1998.nopatch
  SPECS/kernel/CVE-2022-32296.nopatch
Labels: security, Packaging, main

#3186 audit: Remove requirement on base package from libs subpackage
  SPECS/audit/audit.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, main

#3203 Upgrade curl to fix CVE-2022-27779, CVE-2022-27780, CVE-2022-27781, C…
  SPECS/curl/curl.signatures.json
  SPECS/curl/curl.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3202 python3: Upgrade to 3.9.13
  SPECS/python3/python3.signatures.json
  SPECS/python3/python3.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/toolchain-remote-wget-list
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
  toolkit/scripts/toolchain/container/toolchain_build_temp_tools.sh
Labels: main

#3206 ncurses: introduce patch to gptfdisk & irqbalance to fix build with ncurses-6.3
  SPECS/gptfdisk/fix-format-security.patch
  SPECS/gptfdisk/gptfdisk.spec
  SPECS/irqbalance/fix-format-security.patch
  SPECS/irqbalance/irqbalance.spec
Labels: Packaging, 1.0-dev

#3193 Upgrade ncurses to 6.3 [patch 20220612] to fix CVE-2022-29458
  SPECS/ncurses/CVE-2022-29458.nopatch
  SPECS/ncurses/ncurses.signatures.json
  SPECS/ncurses/ncurses.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/toolchain-remote-wget-list
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
  toolkit/scripts/toolchain/container/toolchain_build_temp_tools.sh
Labels: 1.0-dev

#3209 [1.0] Build moby-containerd with mod=vendor and upgrade to version 1.6.6+azure to resolve CVE-2022-31030
  SPECS/moby-containerd/CVE-2022-23648.patch
  SPECS/moby-containerd/Makefile.patch
  SPECS/moby-containerd/generate-sources.sh
  SPECS/moby-containerd/moby-containerd.signatures.json
  SPECS/moby-containerd/moby-containerd.spec
  cgmanifest.json
Labels: Packaging, 1.0-dev

#3213 git: added less to runtime Requires
  SPECS/git/git.spec
Labels: Packaging, main

#3110 util-linux: add buildrequires libcap-ng-devel
  SPECS/libcap-ng/libcap-ng.spec
  SPECS/util-linux/util-linux.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/resources/manifests/package/update_manifests.sh
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
Labels: main

#3216 kernel: Update to 5.10.123.1
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/hyperv-daemons/hyperv-daemons.signatures.json
  SPECS/hyperv-daemons/hyperv-daemons.spec
  SPECS/kernel-headers/kernel-headers.signatures.json
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel-hyperv/config
  SPECS/kernel-hyperv/kernel-hyperv.signatures.json
  SPECS/kernel-hyperv/kernel-hyperv.spec
  SPECS/kernel/CVE-2022-1011.nopatch
  SPECS/kernel/CVE-2022-1966.nopatch
  SPECS/kernel/CVE-2022-1998.nopatch
  SPECS/kernel/CVE-2022-32250.nopatch
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/Dockerfile
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
  toolkit/scripts/toolchain/container/toolchain_build_temp_tools.sh
Labels: 1.0-dev

#3215 Add patch for libcdio to build with ncurses 6.3
  SPECS-EXTENDED/libcdio/fix_format_security.patch
  SPECS-EXTENDED/libcdio/libcdio.spec
Labels: main

#3217 CODEOWNERS: Require admin approval for raw toolchain changes
  .github/CODEOWNERS
Labels: main

#3212 Build Break: Update iptraf-ng to resolve -Werror=format-security compilation failures
  SPECS-EXTENDED/iptraf-ng/0001-BUGFIX-fix-Floating-point-exception-in-tcplog_flowra.patch
  SPECS-EXTENDED/iptraf-ng/0002-Makefile-add-Werror-format-security.patch
  SPECS-EXTENDED/iptraf-ng/0003-fix-segfault-in-adding-interface.patch
  SPECS-EXTENDED/iptraf-ng/iptraf-ng.signatures.json
  SPECS-EXTENDED/iptraf-ng/iptraf-ng.spec
  cgmanifest.json
Labels: main

#3218 Add command line tool jx SPEC
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/jx/jx.signatures.json
  SPECS/jx/jx.spec
  cgmanifest.json
Labels: main

#3183 emacs: nopatch CVE-2007-6109
  SPECS/emacs/CVE-2007-6109.nopatch
  SPECS/emacs/emacs.spec
Labels: security, Packaging, main

#3222 numatop: Fix format-security errors caused by ncurses-6.3 upgrade
  SPECS-EXTENDED/numatop/fix-format-security.patch
  SPECS-EXTENDED/numatop/numatop.spec
Labels: main

#3221 update versions of mtr and iptstate pkgs
  SPECS-EXTENDED/iptstate/iptstate-2.2.6-no_debug.patch
  SPECS-EXTENDED/iptstate/iptstate-2.2.6-rhbz599181.patch
  SPECS-EXTENDED/iptstate/iptstate.signatures.json
  SPECS-EXTENDED/iptstate/iptstate.spec
  SPECS-EXTENDED/mtr/mtr.signatures.json
  SPECS-EXTENDED/mtr/mtr.spec
  cgmanifest.json
Labels: main

#3219 `openssl`: patch CVE-2022-2068
  SPECS/openssl/CVE-2022-2068.patch
  SPECS/openssl/openssl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, main

#3224 Patch openssl to fix CVE-2022-2068
  SPECS/openssl/CVE-2022-2068.patch
  SPECS/openssl/openssl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#3226 `libxslt`: nopatch CVE-2022-29824
  SPECS/libxslt/CVE-2022-29824.nopatch
  SPECS/libxslt/libxslt.spec
Labels: security, Packaging, main

#3158 Update clamav to 0.105.0
  SPECS/clamav/clamav.signatures.json
  SPECS/clamav/clamav.spec
  cgmanifest.json
Labels: main

#3228 update rubygem-elasticsearch to fix CVE-2022-23712
  SPECS/rubygem-elasticsearch/rubygem-elasticsearch.signatures.json
  SPECS/rubygem-elasticsearch/rubygem-elasticsearch.spec
  cgmanifest.json
Labels: 1.0-dev

#3229 `mysql`: update to version 8.0.29 to fix 17 CVEs
  SPECS/mysql/mysql.signatures.json
  SPECS/mysql/mysql.spec
  cgmanifest.json
Labels: security, main

#3230 `moby-containerd`: upgrade to version 1.6.6 to fix CVE-2022-31030
  SPECS/moby-containerd/moby-containerd.signatures.json
  SPECS/moby-containerd/moby-containerd.spec
  cgmanifest.json
Labels: security, main

#3227 Enabling Vgem driver in kernel
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3185 toolchain: Add ability to partially rehydrate from upstream repos
  toolkit/Makefile
  toolkit/docs/building/building.md
  toolkit/scripts/toolchain.mk
  toolkit/scripts/toolchain/build_mariner_toolchain.sh
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
  toolkit/scripts/toolchain/list_toolchain_specs.sh
Labels: main

#3234 Nopatch CVE-2022-29824 the libxslt issue is fixed by libxml2 patch
  SPECS/libxslt/CVE-2022-29824.nopatch
Labels: security, Packaging, 1.0-dev

#3233 Added patch to fix compilation with ncurses 6.3__2.13-3
  SPECS-EXTENDED/powertop/0001-ncurses.patch
  SPECS-EXTENDED/powertop/powertop.spec
Labels: main

#3237 upgrade python-jwt to 2.4.0 to fix 2022-29217
  SPECS/python-jwt/python-jwt.signatures.json
  SPECS/python-jwt/python-jwt.spec
  cgmanifest.json
Labels: 1.0-dev

#3238 `libinput`: upgrade to version 1.21.0 for CVE-2022-1215
  SPECS/libinput/libinput.signatures.json
  SPECS/libinput/libinput.spec
  cgmanifest.json
Labels: security, Packaging, main

#3240 `uclibc-ng`: upgrade to 1.0.41 to fix CVE-2022-30295
  SPECS/uclibc-ng/uclibc-ng.signatures.json
  SPECS/uclibc-ng/uclibc-ng.spec
  cgmanifest.json
Labels: security, Packaging, main

#3241 Print all unsolvable nodes blocking subgraph
  toolkit/tools/scheduler/schedulerutils/depsolver.go
Labels: Tools, main

#3242 Bump Mariner Release for Mariner 1.0 June Update 2
  SPECS/mariner-release/mariner-release.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#3243 Bump Mariner Release version for Mariner 2.0 June Update 2
  SPECS/mariner-release/mariner-release.spec
Labels: Packaging, main

#3235 `usrsctp`: nopatch CVE-2019-20503
  SPECS/usrsctp/CVE-2019-20503.nopatch
Labels: security, Packaging, main

#3245 Add cf-cli SPEC to Mariner
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/cf-cli/cf-cli.signatures.json
  SPECS/cf-cli/cf-cli.spec
  cgmanifest.json
Labels: main

#3036 K3s spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/k3s/k3s.signatures.json
  SPECS/k3s/k3s.spec
  SPECS/k3s/vendor_build.patch
  cgmanifest.json
  toolkit/scripts/spec_source_attributions.py
Labels: Packaging

#3246 [1.0] Use core sources folder for toolchain
  toolkit/scripts/toolchain/container/toolchain-remote-wget-list
  toolkit/scripts/toolchain/create_toolchain_in_container.sh
Labels: Tools, 1.0-dev

#3247 [2.0] Use core sources folder for toolchain
  toolkit/scripts/toolchain/create_toolchain_in_container.sh
Labels: Tools, main

#3254 Upgrade to moby-runc version 1.1.2 to fix CVE-2022-29162
  SPECS/moby-runc/generate-sources.sh
  SPECS/moby-runc/moby-runc.signatures.json
  SPECS/moby-runc/moby-runc.spec
  cgmanifest.json
Labels: 1.0-dev

#3256 gd: fix test
  SPECS/gd/gd.spec
Labels: Packaging, main

#3253 Mark mcpp CVE-2019-14274 as fixed
  SPECS/mcpp/mcpp.spec
  SPECS/mcpp/patch.mcpp.2.7.2
Labels: Packaging, main

#3251 `python-sphinxcontrib-*`: fixing 3 failing ptests.
  SPECS/python-sphinxcontrib-htmlhelp/python-sphinxcontrib-htmlhelp.spec
  SPECS/python-sphinxcontrib-htmlhelp/test_htmlhelp_path_fix.patch
  SPECS/python-sphinxcontrib-jsmath/python-sphinxcontrib-jsmath.spec
  SPECS/python-sphinxcontrib-jsmath/test_jsmath_path_fix.patch
  SPECS/python-sphinxcontrib-qthelp/python-sphinxcontrib-qthelp.spec
  SPECS/python-sphinxcontrib-qthelp/test_qthelp_path_fix.patch
Labels: Packaging, main

#3260 Upgrade Vim version to 8.2.5154 to fix CVEs
  SPECS/vim/vim.signatures.json
  SPECS/vim/vim.spec
  cgmanifest.json
Labels: 1.0-dev

#3259 Upgrade python3 to 3.7.13 to resolve CVE-2019-12900
  SPECS/python3/fix-xml-tests-expat.patch
  SPECS/python3/python3.signatures.json
  SPECS/python3/python3.spec
  cgmanifest.json
  toolkit/scripts/toolchain/container/toolchain-remote-wget-list
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
  toolkit/scripts/toolchain/container/toolchain_build_temp_tools.sh
Labels: 1.0-dev

#3264 kernel: enable virtio config, add vmlinuz symlink, enable verbose log
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3248 Add msgpack package
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/msgpack/msgpack.signatures.json
  SPECS/msgpack/msgpack.spec
  cgmanifest.json
Labels: main

#3266 Upgrade logrotate to 3.20.0 to fix CVE-2022-1348
  SPECS/logrotate/logrotate.signatures.json
  SPECS/logrotate/logrotate.spec
  cgmanifest.json
Labels: 1.0-dev

#3268 Upgrade libtiff version to 4.4.0 to fix CVE-2022-0908
  SPECS/libtiff/CVE-2020-35522.patch
  SPECS/libtiff/CVE-2020-35523.patch
  SPECS/libtiff/CVE-2020-35524.patch
  SPECS/libtiff/CVE-2022-0561.patch
  SPECS/libtiff/CVE-2022-0562.patch
  SPECS/libtiff/CVE-2022-0891.patch
  SPECS/libtiff/libtiff.signatures.json
  SPECS/libtiff/libtiff.spec
  cgmanifest.json
Labels: 1.0-dev

#3108 Add swap partition entry to /etc/fstab
  toolkit/tools/imagegen/configuration/parse_partition.go
  toolkit/tools/imagegen/configuration/parse_partition_test.go
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/imager/imager.go
Labels: Tools, main

#3257 Add retry logic in runliveinstaller to ensure network access during pxe boot
  toolkit/resources/imageconfigs/additionalfiles/iso_initrd/root/runliveinstaller
Labels: main

#3258 Introducing `mariner_rpmspec` function.
  .github/workflows/validate-cg-manifest.sh
  toolkit/scripts/rpmops.sh
  toolkit/scripts/update_spec.sh
Labels: main

#3252 patch qemu-kvm for CVE-2021-3750
  SPECS/qemu-kvm/CVE-2021-3750.patch
  SPECS/qemu-kvm/qemu-kvm.spec
Labels: Packaging, 1.0-dev

#3271 Update Ubuntu version to 22.04 for CGmanifest check.
  .github/workflows/check-package-cgmanifest.yml
Labels: main

#3270 coreutils: Build arch binary
  SPECS/coreutils/coreutils.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3250 `prebuilt-ca-certificates*`: adding `Conflicts: ca-certificates-shared`
  SPECS/ca-certificates/ca-certificates.spec
  SPECS/prebuilt-ca-certificates-base/prebuilt-ca-certificates-base.spec
  SPECS/prebuilt-ca-certificates/prebuilt-ca-certificates.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3263 Upgrade Vim version to 8.2.5154 to fix CVEs (cherry-pick from 1.0-dev)
  SPECS/vim/vim.signatures.json
  SPECS/vim/vim.spec
  cgmanifest.json
Labels: main

#3255 Added patch to fix compilation with ncurses 6.3 for hunspell and liboping
  SPECS-EXTENDED/hunspell/hunspell-1.7.0-print-format.patch
  SPECS-EXTENDED/hunspell/hunspell.spec
  SPECS-EXTENDED/liboping/liboping-1.10-fix-format-ncurses63.patch
  SPECS-EXTENDED/liboping/liboping.spec
  cgmanifest.json
Labels: main

#3279 `abseil-cpp`: removing GTest workarounds.
  SPECS/abseil-cpp/abseil-cpp.signatures.json
  SPECS/abseil-cpp/abseil-cpp.spec
  SPECS/abseil-cpp/disabling_invalid_tests.patch
  SPECS/abseil-cpp/gtest_build_fix.patch
  SPECS/grpc/grpc.spec
  SPECS/gtest/gtest.signatures.json
  SPECS/gtest/gtest.spec
  cgmanifest.json
Labels: main

#3277 Upgrade libjpeg-turbo version 2.1.2 to fix CVE-2021-46822
  SPECS/libjpeg-turbo/CVE-2018-19664.patch
  SPECS/libjpeg-turbo/CVE-2018-20330.patch
  SPECS/libjpeg-turbo/CVE-2020-17541.patch
  SPECS/libjpeg-turbo/libjpeg-turbo.signatures.json
  SPECS/libjpeg-turbo/libjpeg-turbo.spec
  cgmanifest.json
Labels: 1.0-dev
