Repository microsoft/azurelinux, pull requests merged in 2022-09, with the labels that each got.

#3652 python-ntlm-auth: add BR on `pip` & drop BR on `pytest` to enable ptest
  SPECS-EXTENDED/python-ntlm-auth/python-ntlm-auth.spec
Labels: ptest, main, specs-extended

#3655 kata-containers: remove acrn config for arm64
  SPECS/kata-containers/kata-containers.spec
Labels: Packaging, main

#3654 `python3`: fix CVE-2021-28861
  SPECS/python3/CVE-2021-28861.patch
  SPECS/python3/python3.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, main

#3672 add patch for Glibc to fix CVE-2021-3999
  SPECS/glibc/CVE-2021-3999.patch
  SPECS/glibc/glibc.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#3623 added arm64 support for node-problem-detector which is needed to supp…
  SPECS/node-problem-detector/001-remove_arch_specific_makefile_logic.patch
  SPECS/node-problem-detector/001-remove_arm64_build.patch
  SPECS/node-problem-detector/002-add_mariner_OSVersion.patch
  SPECS/node-problem-detector/002-remove_windows_build.patch
  SPECS/node-problem-detector/node-problem-detector.spec
Labels: Packaging, main

#3677 libguestfs: require qemu-img package instead of binary
  SPECS/libguestfs/libguestfs.spec
Labels: Packaging, main

#3675 `colord`: fix CVE-2021-42523
  SPECS/colord/CVE-2021-42523.patch
  SPECS/colord/colord.spec
Labels: security, main

#3676 `binutils`: fix CVE-2022-38533
  SPECS/binutils/CVE-2022-38533.patch
  SPECS/binutils/binutils.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, main

#3673 add patch for python3 to fix CVE-2021-28861
  SPECS/python3/CVE-2021-28861.patch
  SPECS/python3/python3.spec
Labels: security, Packaging, 1.0-dev

#3674 `virglrenderer`: fix CVE-2022-0135
  .github/workflows/validate-cg-manifest.sh
  SPECS/virglrenderer/CVE-2022-0135.patch
  SPECS/virglrenderer/virglrenderer.signatures.json
  SPECS/virglrenderer/virglrenderer.spec
  cgmanifest.json
Labels: security, Packaging, main

#3612 Match Guest and Host cgroup setup and expose required devices from kata
  SPECS/kata-containers/0001-Merged-PR-9607-Allow-10-seconds-for-VM-creation-star.patch
  SPECS/kata-containers/0002-Merged-PR-9671-Wait-for-a-possibly-slow-Guest.patch
  SPECS/kata-containers/0003-Merged-PR-9805-Add-support-for-MSHV.patch
  SPECS/kata-containers/0004-Merged-PR-9806-Fix-enable_debug-for-hypervisor.clh.patch
  SPECS/kata-containers/kata-containers.signatures.json
  SPECS/kata-containers/kata-containers.spec
  SPECS/kata-containers/kata-osbuilder-generate.service
  SPECS/kata-containers/kata-osbuilder.sh
Labels: Packaging, main

#3653 Introduce kernel-uvm package
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/kernel-uvm/config
  SPECS/kernel-uvm/kernel-uvm.signatures.json
  SPECS/kernel-uvm/kernel-uvm.spec
  cgmanifest.json
Labels: Packaging, main

#3694 kata-containers : set DEFSANDBOXCGROUPONLY to false
  SPECS/kata-containers/kata-containers.spec
Labels: Packaging, main

#3681 Add patch for openvswtich to fix CVE-2021-3905
  SPECS/openvswitch/CVE-2021-3905
  SPECS/openvswitch/openvswitch.spec
Labels: security, Packaging, 1.0-dev

#3686 libtar: Pull misc Fedora patches, fix CVE-2021-33643, CVE-2021-33644, CVE-2021-33645, CVE-2021-33646
  SPECS/libtar/libtar-1.2.11-mem-deref.patch
  SPECS/libtar/libtar-1.2.20-CVE-2021-33643-CVE-2021-33644.patch
  SPECS/libtar/libtar-1.2.20-CVE-2021-33645-CVE-2021-33646.patch
  SPECS/libtar/libtar-1.2.20-fix-resource-leaks.patch
  SPECS/libtar/libtar-1.2.20-static-analysis.patch
  SPECS/libtar/libtar-gen-debuginfo.patch
  SPECS/libtar/libtar.spec
Labels: security, Packaging, main

#3687 livepatching-subscription: add package for livepatches management
  .github/workflows/validate-cg-manifest.sh
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/livepatching/livepatching.service
  SPECS/livepatching/livepatching.signatures.json
  SPECS/livepatching/livepatching.spec
  SPECS/livepatching/livepatching.systemd
Labels: main

#3700 Upgrade vim to 9.0.0348 to fix CVEs
  SPECS/vim/vim.signatures.json
  SPECS/vim/vim.spec
  cgmanifest.json
Labels: security, 1.0-dev

#3703 Qemu-kvm nopatch CVE-2022-0358
  SPECS/qemu-kvm/CVE-2022-0358.nopatch
  SPECS/qemu-kvm/qemu-kvm.spec
Labels: security, Packaging, 1.0-dev

#3695 Build Rust as a stable release and disable unstable features
  SPECS-EXTENDED/ripgrep/ripgrep.spec
  SPECS/clamav/clamav.spec
  SPECS/cloud-hypervisor/cloud-hypervisor.spec
  SPECS/librsvg2/librsvg2.spec
  SPECS/mozjs/mozjs.spec
  SPECS/rpm-ostree/rpm-ostree.spec
  SPECS/rust/rust.spec
Labels: main

#3679 kernel: Add 32bit time syscall support
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#3696 qemu: Patch CVE-2021-4158
  SPECS/qemu/CVE-2021-4158.patch
  SPECS/qemu/qemu.spec
Labels: security, Packaging, main

#3707 nopatching kernel CVE-2022-2959, CVE-2022-2938, CVE-2021-3736, CVE-2021-4155, CVE-2022-0168
  SPECS/kernel/CVE-2021-3736.nopatch
  SPECS/kernel/CVE-2021-4155.nopatch
  SPECS/kernel/CVE-2022-0168.nopatch
  SPECS/kernel/CVE-2022-2938.nopatch
  SPECS/kernel/CVE-2022-2959.nopatch
Labels: security, Packaging, 1.0-dev

#3706 Add preinstall/postuninstall requirement on shadow-utils to clamav
  SPECS/clamav/clamav.spec
Labels: Packaging, main

#3708 update rubygem-faraday to v.2.5.2
  SPECS/rubygem-faraday/rubygem-faraday.signatures.json
  SPECS/rubygem-faraday/rubygem-faraday.spec
  cgmanifest.json
Labels: main

#3698 libtar: Fixup spec formatting, remove .la files, remove explicit provides
  SPECS/libtar/libtar.spec
Labels: Packaging, main

#3699 audiofile: disable check section to fix ptest pipeline break
  SPECS-EXTENDED/audiofile/audiofile.spec
Labels: ptest, main, specs-extended

#3715 Upgrade ceph to 16.2.10 to fix CVE-2022-0670
  SPECS/ceph/ceph.signatures.json
  SPECS/ceph/ceph.spec
  cgmanifest.json
Labels: 1.0-dev

#3716 Fixes for libtar CVE-2021-33643 CVE-2021-33644 CVE-2021-33645 CVE-2021-33646
  SPECS/libtar/libtar-1.2.11-mem-deref.patch
  SPECS/libtar/libtar-1.2.20-CVE-2021-33643-CVE-2021-33644.patch
  SPECS/libtar/libtar-1.2.20-CVE-2021-33645-CVE-2021-33646.patch
  SPECS/libtar/libtar-1.2.20-fix-resource-leaks.patch
  SPECS/libtar/libtar-1.2.20-static-analysis.patch
  SPECS/libtar/libtar-gen-debuginfo.patch
  SPECS/libtar/libtar.spec
Labels: Packaging, 1.0-dev

#3719 Upgrade gzip version to 1.12 to fix CVE-2022-1271
  SPECS/gzip/gzip.signatures.json
  SPECS/gzip/gzip.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#3720 Upgrade vim version to 9.0.0360 to fix CVE-2022-3099
  SPECS/vim/vim.signatures.json
  SPECS/vim/vim.spec
  cgmanifest.json
Labels: 1.0-dev

#3722 Update the openvswitch patch name
  SPECS/openvswitch/CVE-2021-3905.patch
  SPECS/openvswitch/openvswitch.spec
Labels: Packaging, 1.0-dev

#3711 Add emacs-filesystem subpackage
  SPECS/emacs/emacs.spec
Labels: Packaging, main

#3723 [2.0] Update mariner-release for September CVE release
  SPECS/mariner-release/mariner-release.spec
Labels: Packaging, main

#3300 initial kernel config changes for criu
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, main

#3726 libvirt: require qemu-img package instead of binary
  SPECS/libvirt/libvirt.spec
Labels: Packaging, main

#3721 Add multus v3.8 rpm
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/multus/multus.signatures.json
  SPECS/multus/multus.spec
  cgmanifest.json
Labels: main

#3727 fix br in libvirt (#3726)
  SPECS/libvirt/libvirt.spec
Labels: Packaging

#3731 livepatching: make exclusive to x86_64.
  SPECS/livepatching/livepatching.spec
Labels: Packaging, main

#3717 Upgrade python to 3.9.14 to fix CVE-2020-10735
  SPECS/python3/CVE-2021-28861.patch
  SPECS/python3/python3.signatures.json
  SPECS/python3/python3.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, main

#3735 Upgrade libjpeg-turbo version to 2.1.4 to fix CVE-2020-35538
  SPECS/libjpeg-turbo/libjpeg-turbo.signatures.json
  SPECS/libjpeg-turbo/libjpeg-turbo.spec
  cgmanifest.json
Labels: 1.0-dev

#3736 Fix for rpm CVE-2021-3521
  SPECS/rpm/CVE-2021-3521.patch
  SPECS/rpm/rpm.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, 1.0-dev

#3684 perl-namespace-clean: add BR on perl-debugger to enable ptest
  SPECS-EXTENDED/perl-namespace-clean/perl-namespace-clean.spec
Labels: ptest, main, specs-extended

#3737 python-kdcproxy: add BR on python-pip and drop BR on pytest to enable ptest
  SPECS-EXTENDED/python-kdcproxy/python-kdcproxy.spec
  cgmanifest.json
Labels: ptest, main, specs-extended

#3738 lasso: bump version to 2.8.0 to fix ptest
  SPECS-EXTENDED/lasso/0005-tests-use-self-generated-certificate-to-sign-federat.patch
  SPECS-EXTENDED/lasso/0006-Fix-ECP-signature-not-found-error-when-only-assertio.patch
  SPECS-EXTENDED/lasso/0007-PAOS-Do-not-populate-Destination-attribute.patch
  SPECS-EXTENDED/lasso/0008-Explicitly-define-tests-cases-and-add-them-to-tests.patch
  SPECS-EXTENDED/lasso/build-scripts-py3-compatible.patch
  SPECS-EXTENDED/lasso/duplicate-python-LogoutTestCase.patch
  SPECS-EXTENDED/lasso/lasso.signatures.json
  SPECS-EXTENDED/lasso/lasso.spec
  SPECS-EXTENDED/lasso/use-specified-python-interpreter.patch
  SPECS-EXTENDED/lasso/versioned-python-configure.patch
  cgmanifest.json
Labels: ptest, main, specs-extended

#3739 perl-Config-IniFiles: add BR on `perl(blib)` to enable ptest
  SPECS-EXTENDED/perl-Config-IniFiles/perl-Config-IniFiles.spec
Labels: ptest, main, specs-extended

#3742 Create modules folder for UVM kernel
  SPECS/kernel-uvm/kernel-uvm.spec
Labels: Packaging, main

#3678 mock: add BR on `python3-pip` & drop un-needed deps to enable ptest
  SPECS-EXTENDED/mock/mock.spec
Labels: ptest, main, specs-extended

#3624 Updates to kernel-rt package (5.15.55.1)
  SPECS/kernel-rt/config
  SPECS/kernel-rt/kernel-rt.signatures.json
  SPECS/kernel-rt/kernel-rt.spec
  SPECS/kernel-rt/patch-5.15.55-rt48.patch
  cgmanifest.json
Labels: Packaging, main

#3713 Security changes to meet Azure security baseline
  SPECS-SIGNED/grub2-efi-binary-signed/grub2-efi-binary-signed.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/asc/asc.spec
  SPECS/calamares/calamares.signatures.json
  SPECS/calamares/calamares.spec
  SPECS/calamares/users.conf
  SPECS/cronie/cronie.spec
  SPECS/filesystem/filesystem.spec
  SPECS/grub2/grub2.spec
  SPECS/mariner-release/mariner-release.spec
  SPECS/openssh/openssh.spec
  SPECS/rsyslog/rsyslog.conf
  SPECS/rsyslog/rsyslog.signatures.json
  SPECS/rsyslog/rsyslog.spec
  SPECS/shadow-utils/login-defs
  SPECS/shadow-utils/pam.d/system-auth
  SPECS/shadow-utils/shadow-utils.signatures.json
  SPECS/shadow-utils/shadow-utils.spec
  SPECS/util-linux/su
  SPECS/util-linux/util-linux.signatures.json
  SPECS/util-linux/util-linux.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/tools/imagegen/installutils/installutils.go
Labels: main

#3683 Skip compression on rpm/srpm archives
  toolkit/scripts/pkggen.mk
  toolkit/scripts/toolchain.mk
  toolkit/scripts/toolchain/build_mariner_toolchain.sh
Labels: main

#3714 mariadb - fix upgrade by adding shadow-utils pre/postun requirement
  SPECS/mariadb/mariadb.spec
Labels: Packaging, main

#3688 Fix errors when installing reaper RPM in CBL-Mariner
  SPECS/reaper/reaper.spec
Labels: Packaging, main

#3705 adjust crashkernel param based on available ram
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel-rt/kernel-rt.spec
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3712 grub2: add patch for reseting grub_errno
  SPECS-SIGNED/grub2-efi-binary-signed/grub2-efi-binary-signed.spec
  SPECS/grub2/0170-fix-memory-alloc-errno-reset.patch
  SPECS/grub2/grub2.spec
Labels: Packaging, main

#3754 selinux-policy: Fix issue with preinst on systems that do not have selinux-policy.
  SPECS/selinux-policy/selinux-policy.spec
Labels: Packaging, main

#3728 kube-vip-cloud-provider: add package
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/kube-vip-cloud-provider/kube-vip-cloud-provider.signatures.json
  SPECS/kube-vip-cloud-provider/kube-vip-cloud-provider.spec
  cgmanifest.json
Labels: main

#3733 kernel: enable CONFIG_VFAT_FS
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3777 revert cloud-init dependency
  SPECS/cloud-init/add-mariner-distro-support.patch
  SPECS/cloud-init/cloud-init.spec
Labels: Packaging, main

#3710 Add explicit provides for tcl(abi)
  SPECS/tcl/tcl.spec
Labels: Packaging, main

#3765 libtiff: Patch CVE-2022-2953
  SPECS/libtiff/CVE-2022-2953.patch
  SPECS/libtiff/libtiff.spec
Labels: security, Packaging, main

#3755 Upgrade libjpeg-turbo version to 2.1.4 to fix CVE-2020-35538
  SPECS/libjpeg-turbo/libjpeg-turbo.signatures.json
  SPECS/libjpeg-turbo/libjpeg-turbo.spec
  cgmanifest.json
Labels: security, main

#3773 Replace NumPy spec %py3_install macro
  SPECS/numpy/numpy.spec
Labels: Packaging, main

#3779 Added nopatch to libtirpc for CVE-2021-46828
  SPECS/libtirpc/CVE-2021-46828.nopatch
Labels: security, Packaging, main

#3778 update mariner-release to 2.0-21
  SPECS/mariner-release/mariner-release.spec
Labels: Packaging, main

#3781 Merge updates for September 2.0 release 2
  SPECS/cloud-init/add-mariner-distro-support.patch
  SPECS/cloud-init/cloud-init.spec
  SPECS/libtirpc/CVE-2021-46828.nopatch
  SPECS/mariner-release/mariner-release.spec
Labels: Packaging

#3709 Add portmap to rpcbind provides
  SPECS/rpcbind/rpcbind.spec
Labels: Packaging, main

#3734 toolkit: added RPMs snapshots.
  toolkit/Makefile
  toolkit/scripts/srpm_pack.mk
  toolkit/scripts/toolkit.mk
  toolkit/scripts/tools.mk
  toolkit/scripts/utils.mk
  toolkit/tools/internal/rpm/rpm.go
  toolkit/tools/pkg/rpmssnapshot/rpmssnapshot.go
  toolkit/tools/rpmssnapshot/rpmssnapshot.go
Labels: Tools, main

#3725 libbpf: bump version to 1.0.0
  SPECS/libbpf/libbpf.signatures.json
  SPECS/libbpf/libbpf.spec
  SPECS/qemu/0001-ebpf-replace-deprecated-bpf_program__set_socket_filt.patch
  SPECS/qemu/qemu.spec
  cgmanifest.json
Labels: main

#3682 KeysInUse-OpenSSL: reintroduce keysinuseutil & simplify package install
  SPECS/KeysInUse-OpenSSL/KeysInUse-OpenSSL.spec
Labels: Packaging, main

#3785 blobfuse: bump version to 1.4.5
  SPECS/blobfuse/blobfuse.signatures.json
  SPECS/blobfuse/blobfuse.spec
  cgmanifest.json
Labels: main

#3799 expat: patch CVE-2022-40674
  SPECS/expat/CVE-2022-40674.patch
  SPECS/expat/expat.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security

#3806 gzip: version update CVE-2022-1271
  SPECS/gzip/gzip.signatures.json
  SPECS/gzip/gzip.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3805 Upgrade ncurses to 6.3 [patch 20220612] to fix CVE-2022-29458 (#3193)
  SPECS/ncurses/CVE-2022-29458.nopatch
  SPECS/ncurses/ncurses.signatures.json
  SPECS/ncurses/ncurses.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3763 Update sos to 4.4 to fix patch CVE-2022-2806
  SPECS/sos/sos.signatures.json
  SPECS/sos/sos.spec
  cgmanifest.json
Labels: security, Packaging, main

#3768 virglrenderer: Patch CVE-2022-0175
  SPECS/virglrenderer/CVE-2022-0175.patch
  SPECS/virglrenderer/virglrenderer.spec
Labels: security, Packaging, main

#3804 expat: minor upgrade to 2.4.9 to fix CVE-2022-40674
  SPECS/expat/expat.signatures.json
  SPECS/expat/expat.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#3697 rpm: Upgrade to 4.18.0-rc1 to resolve CVE-2021-3521, CVE-2021-35938 and CVE-2021-35939
  SPECS/grubby/0014-Fix-build-RPM-418.patch
  SPECS/grubby/grubby.spec
  SPECS/openscap/openscap.spec
  SPECS/openscap/support_rpm_418.patch
  SPECS/rpm/fix_RPM_GNUC_DEPRECATED_headers.patch
  SPECS/rpm/remove-docs-from-makefile.patch
  SPECS/rpm/rpm.signatures.json
  SPECS/rpm/rpm.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, main

#3814 kernel mshv: copy vmlinuz to efi partition
  SPECS/kernel-mshv/kernel-mshv.spec
Labels: Packaging, main

#3783 Enable kernel config CONFIG_NETFILTER_XT_TARGET_TRACE as a module
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3819 msft-golang - upgrade to 1.19.1-1
  SPECS/msft-golang/msft-golang.signatures.json
  SPECS/msft-golang/msft-golang.spec
  cgmanifest.json
Labels: main

#3816 pyflakes: bump version to 2.5.0 to fix ptest
  SPECS-EXTENDED/pyflakes/pyflakes.signatures.json
  SPECS-EXTENDED/pyflakes/pyflakes.spec
  cgmanifest.json
Labels: ptest, main, specs-extended

#3812 kernel: Add 32bit time syscall support
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3767 Adding grubenv file by default.
  toolkit/resources/assets/grub2/grub.cfg
  toolkit/resources/assets/grub2/grubenv
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/imager/imager.go
Labels: main

#3618 New spec file for local-path-provisioner
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/local-path-provisioner/local-path-provisioner.signatures.json
  SPECS/local-path-provisioner/local-path-provisioner.spec
  cgmanifest.json
Labels: main

#3826 kernel: Add SCSI logging facility
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3825 python-mako: version update CVE-2022-40023
  SPECS/python-mako/python-mako.signatures.json
  SPECS/python-mako/python-mako.spec
  cgmanifest.json
Labels: main

#3828 python-mako: Updating to 1.2.2 to fix CVE-2022-40023
  SPECS/python-mako/python-mako.signatures.json
  SPECS/python-mako/python-mako.spec
  cgmanifest.json
Labels: 1.0-dev

#3830 Bump Mariner 2.0 Release for Accumulated September Update 3
  SPECS/mariner-release/mariner-release.spec
Labels: Packaging, main

#3832 Clear CVE's against finger source
  SPECS/finger/CVE-1999-0150.nopatch
  SPECS/finger/CVE-1999-0612.nopatch
Labels: security, Packaging, 1.0-dev

#3831 Mitigate ARM64 Image Build
  toolkit/tools/imagegen/installutils/installutils.go
Labels: Tools, main

#3837 xmlsec1: update to 1.2.34 to fix openscap build break
  SPECS/xmlsec1/xmlsec1.signatures.json
  SPECS/xmlsec1/xmlsec1.spec
  cgmanifest.json
Labels: main

#3843 toolkit.mk: fix `clean-rpms-snapshot` target.
  toolkit/scripts/toolkit.mk
Labels: Tools, main

#3565 Add option to build a package for a specific architecture
  toolkit/Makefile
  toolkit/docs/building/building.md
  toolkit/scripts/pkggen.mk
  toolkit/tools/internal/rpm/rpm.go
  toolkit/tools/internal/rpm/rpm_test.go
  toolkit/tools/pkg/rpmssnapshot/rpmssnapshot.go
  toolkit/tools/pkgworker/pkgworker.go
  toolkit/tools/scheduler/buildagents/chrootagent.go
  toolkit/tools/scheduler/buildagents/definition.go
  toolkit/tools/scheduler/buildagents/testagent.go
  toolkit/tools/scheduler/schedulerutils/buildworker.go
  toolkit/tools/specreader/specreader.go
  toolkit/tools/srpmpacker/srpmpacker.go
Labels: Tools, main

#3852 kernel: Address CVE-2022-1976, CVE-2022-2905, CVE-2022-2977, CVE-2022-3078, CVE-2022-3170, CVE-2022-4030
  SPECS/kernel/CVE-2022-1976.nopatch
  SPECS/kernel/CVE-2022-2905.nopatch
  SPECS/kernel/CVE-2022-2977.nopatch
  SPECS/kernel/CVE-2022-3078.nopatch
  SPECS/kernel/CVE-2022-3170.nopatch
  SPECS/kernel/CVE-2022-40307.nopatch
Labels: security, Packaging, main

#3833 msft-golang: drop explicit VERSION in build
  SPECS/msft-golang/msft-golang.spec
Labels: Packaging, main

#3838 mlocate: introduce patch to fix deep heirarchy ptest
  SPECS/mlocate/0001-tests-updatedb-reduce-heirarchy-to-300-from-950.patch
  SPECS/mlocate/mlocate.spec
Labels: Packaging, ptest, 1.0-dev

#3786 Enable csi-driver-lvm in Mariner.
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/csi-driver-lvm/csi-driver-lvm.signatures.json
  SPECS/csi-driver-lvm/csi-driver-lvm.spec
  cgmanifest.json
Labels: main

#3853 rpmops.sh: load missed macro files
  toolkit/scripts/rpmops.sh
Labels: Tools, main

#3859 Added links where promised (rebased)
  README.md
Labels: main

#3604 Add UEFI support in Mariner partition parser
  toolkit/tools/imagegen/attendedinstaller/views/diskview/autopartitionwidget/autopartitionwidget.go
  toolkit/tools/imagegen/attendedinstaller/views/diskview/diskview.go
  toolkit/tools/imagegen/attendedinstaller/views/diskview/manualpartitionwidget/manualpartitionwidget.go
  toolkit/tools/imagegen/configuration/parse_partition.go
  toolkit/tools/imagegen/configuration/parse_partition_test.go
  toolkit/tools/imagegen/configuration/partition.go
  toolkit/tools/imagegen/diskutils/diskutils.go
  toolkit/tools/liveinstaller/liveinstaller.go
Labels: Tools, main

#3369 livepatching: add automation for livepatch packages.
  SPECS/kpatch/kpatch.spec
  SPECS/kpatch/mariner_update.patch
  toolkit/scripts/bump_kernel_release.sh
  toolkit/scripts/livepatching/generate_livepatch-signed_spec.sh
  toolkit/scripts/livepatching/generate_livepatch_spec.sh
  toolkit/scripts/livepatching/template_livepatch-signed.spec
  toolkit/scripts/livepatching/template_livepatch.spec
  toolkit/scripts/livepatching/update_livepatches.sh
  toolkit/scripts/specs/specs_tools.sh
  toolkit/scripts/update_spec.sh
Labels: Packaging, main

#3869 Revert grubenv changes
  toolkit/resources/assets/grub2/grub.cfg
  toolkit/resources/assets/grub2/grubenv
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/imager/imager.go
Labels: main

#3862 kernel-rt: move to SPECS-EXTENDED
  SPECS-EXTENDED/kernel-rt/cbl-mariner-ca-20211013.pem
  SPECS-EXTENDED/kernel-rt/config
  SPECS-EXTENDED/kernel-rt/kernel-rt.signatures.json
  SPECS-EXTENDED/kernel-rt/kernel-rt.spec
  SPECS-EXTENDED/kernel-rt/patch-5.15.55-rt48.patch
  SPECS-EXTENDED/kernel-rt/realtime-with-memcg.patch
  SPECS-EXTENDED/kernel-rt/sha512hmac-openssl.sh
  toolkit/imageconfigs/core-efi-rt.json
  toolkit/imageconfigs/full-rt.json
  toolkit/scripts/update_kernel.sh
Labels: main

#3871 fix build break due to missing python-mako dependencies
  SPECS/python-mako/python-mako.spec
Labels: Packaging, main

#3870 Add CVE-2018-25032 nopatch file to python3
  SPECS/python3/CVE-2018-25032.nopatch
Labels: security, Packaging, 1.0-dev

#3866 Split csi-driver-lvm binaries to two packages.
  SPECS/csi-driver-lvm/csi-driver-lvm.spec
Labels: Packaging, main

#3815 Add initial support for finalizeImage
  toolkit/docs/formats/imageconfig.md
  toolkit/tools/imagegen/attendedinstaller/_manualrun/manualrun.go
  toolkit/tools/imagegen/attendedinstaller/views/installationview/installationview.go
  toolkit/tools/imagegen/configuration/configuration.go
  toolkit/tools/imagegen/configuration/configuration_test.go
  toolkit/tools/imagegen/configuration/systemconfig.go
  toolkit/tools/imagegen/configuration/testdata/test_configuration.json
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/imager/imager.go
  toolkit/tools/isomaker/maker.go
Labels: Tools, main

#3873 Kernel CVE - nopatch kernel CVES CVE-2021-3669, CVE-2022-0171, CVE-2022-1016, CVE-2022-1882, CVE-2022-2873, CVE-2022-39842
  SPECS/kernel/CVE-2021-3669.nopatch
  SPECS/kernel/CVE-2022-0171.nopatch
  SPECS/kernel/CVE-2022-1016.nopatch
  SPECS/kernel/CVE-2022-1882.nopatch
  SPECS/kernel/CVE-2022-2873.nopatch
  SPECS/kernel/CVE-2022-39842.nopatch
Labels: security, Packaging, main

#3875 toolbox: add missing `signatures.json` file
  SPECS-EXTENDED/toolbox/toolbox.signatures.json
Labels: main, specs-extended

#3877 python-mako: revert to 1.0.7, patch CVE-2022-40023.
  SPECS/python-mako/CVE-2022-40023.patch
  SPECS/python-mako/python-mako.signatures.json
  SPECS/python-mako/python-mako.spec
  cgmanifest.json
Labels: 1.0-dev

#3876 Upgrade cassandra version to 4.0.6
  SPECS-EXTENDED/cassandra/cassandra.signatures.json
  SPECS-EXTENDED/cassandra/cassandra.spec
  cgmanifest.json
Labels: main, specs-extended

#3881 Add CVE-2022-39227 nopatch file for python-jwt
  SPECS/python-jwt/CVE-2022-39227.nopatch
  SPECS/python-jwt/python-jwt.spec
Labels: security, Packaging, 1.0-dev
