Repository microsoft/azurelinux, pull requests merged in 2022-02, with the labels that each got.

#2047 Upgrade yaml-cpp to v0.7.0
  SPECS/yaml-cpp/CVE-2017-5950.patch
  SPECS/yaml-cpp/CVE-2018-20573.nopatch
  SPECS/yaml-cpp/CVE-2018-20574.nopatch
  SPECS/yaml-cpp/CVE-2019-6285.nopatch
  SPECS/yaml-cpp/CVE-2019-6292.nopatch
  SPECS/yaml-cpp/yaml-cpp-include_dir.patch
  SPECS/yaml-cpp/yaml-cpp-static.patch
  SPECS/yaml-cpp/yaml-cpp.signatures.json
  SPECS/yaml-cpp/yaml-cpp.spec
  cgmanifest.json
Labels: Packaging

#2059 [main] Removing missed `--noscripts` option when building the worker chroot.
  toolkit/tools/pkggen/worker/create_worker_chroot.sh
Labels: Tools

#2064 prometheus: fix ptest build
  SPECS/prometheus/0001-Fixed-TestChunkDiskMapper_WriteChunk_Chunk_IterateCh.patch
  SPECS/prometheus/prometheus.spec
Labels: Packaging

#2062 [main] update fmt to 8.1.1
  SPECS/fmt/fmt.signatures.json
  SPECS/fmt/fmt.spec
  cgmanifest.json
Labels: Packaging

#2065 libstoragemgmt: fix ptest build break
  SPECS/libstoragemgmt/libstoragemgmt.spec
Labels: Packaging

#2078 iproute: add explicit BR on sudo & libmnl-devel to fix ptest
  SPECS/iproute/iproute.spec
Labels: Packaging

#2079 memcached: add explict BR on perl-{FindBin,lib,fields} to fix ptest
  SPECS/memcached/memcached.spec
Labels: Packaging

#2101 [main] cleanup spec files for mesa-LibGLU and librsvg2
  SPECS/librsvg2/librsvg2.spec
  SPECS/mesa-libGLU/mesa-libGLU.spec
Labels: Packaging

#2095 brotli: use `make` instead of `ctest` to enable ptest
  SPECS/brotli/brotli.spec
Labels: Packaging

#2093 gd: add explicit BR on fontawesome-fonts to enable ptest
  SPECS/gd/gd.spec
Labels: Packaging

#2086 pango: use %meson_test to fix ptest failure
  SPECS/pango/0001-skip-tests-which-are-known-to-fail.patch
  SPECS/pango/pango.spec
Labels: Packaging

#2117 [main] polkit: patch for CVE-2021-4034
  SPECS/polkit/CVE-2021-4034.patch
  SPECS/polkit/polkit.spec
Labels: Packaging

#2119 make kernel-rt ExclusiveArch x86_64
  SPECS/kernel-rt/kernel-rt.spec
Labels: Packaging

#2121 [main] [core] pciutils: Require libs subpackage from main package
  SPECS/pciutils/pciutils.spec
Labels: Packaging

#2135 python-websocket-client: pip install 'six' & 'unittest2' to enable ptest
  SPECS/python-websocket-client/python-websocket-client.spec
Labels: Packaging

#2137 virtualenv: add an explict BR on 'pip' to enable ptest
  SPECS/python-virtualenv/python-virtualenv.spec
Labels: Packaging

#2139 python-pyvmomi: add an explicit BR on `pip` to enable ptest
  SPECS/python-pyvmomi/python-pyvmomi.spec
Labels: Packaging

#2150 [main] [core] Remove python2 from git
  SPECS/git/git.spec
Labels: Packaging

#2151 [main] [core] Remove python2 build option from graphviz
  SPECS/graphviz/graphviz.spec
Labels: Packaging

#2161 python-execnet: use `py39` as tox environment to enable ptest
  SPECS/python-execnet/python-execnet.spec
Labels: Packaging

#2162 python-imagesize: remove stray `popd` to enable ptest
  SPECS/python-imagesize/python-imagesize.spec
Labels: Packaging

#2163 python-mistune: add an explicit BR on 'pip' to enable ptest
  SPECS/python-mistune/python-mistune.spec
Labels: Packaging

#2164 python-oauthlib: install 'wheel' to enable ptest
  SPECS/python-oauthlib/python-oauthlib.spec
Labels: Packaging

#2157 [1.0] shim: update shim bootloader
  SPECS-SIGNED/grub2-efi-binary-signed/grub2-efi-binary-signed.spec
  SPECS/grub2/grub2.spec
  SPECS/shim-unsigned-x64/Don-t-call-QueryVariableInfo-on-EFI-1.10-machines.patch
  SPECS/shim-unsigned-x64/Fix-a-broken-file-header-on-ia32.patch
  SPECS/shim-unsigned-x64/Fix-handling-of-ignore_db-and-user_insecure_mode.patch
  SPECS/shim-unsigned-x64/Relax-the-check-for-import_mok_state.patch
  SPECS/shim-unsigned-x64/cbl-mariner-ca-20210127.der
  SPECS/shim-unsigned-x64/cbl-mariner-ca-20211013.der
  SPECS/shim-unsigned-x64/mok-allocate-MOK-config-table-as-BootServicesData.patch
  SPECS/shim-unsigned-x64/shim-another-attempt-to-fix-load-options-handling.patch
  SPECS/shim-unsigned-x64/shim-unsigned-x64.signatures.json
  SPECS/shim-unsigned-x64/shim-unsigned-x64.spec
  SPECS/shim/shim.signatures.json
  SPECS/shim/shim.spec
Labels: Packaging

#2105 Updated python-bcrypt to 3.2.0
  SPECS/python-bcrypt/python-bcrypt.signatures.json
  SPECS/python-bcrypt/python-bcrypt.spec
  cgmanifest.json
Labels: Packaging

#2173 [main] shim: update shim bootloader
  SPECS-SIGNED/grub2-efi-binary-signed/grub2-efi-binary-signed.spec
  SPECS/grub2/grub2.spec
  SPECS/shim-unsigned-x64/Don-t-call-QueryVariableInfo-on-EFI-1.10-machines.patch
  SPECS/shim-unsigned-x64/Fix-a-broken-file-header-on-ia32.patch
  SPECS/shim-unsigned-x64/Fix-handling-of-ignore_db-and-user_insecure_mode.patch
  SPECS/shim-unsigned-x64/Relax-the-check-for-import_mok_state.patch
  SPECS/shim-unsigned-x64/cbl-mariner-ca-20210127.der
  SPECS/shim-unsigned-x64/cbl-mariner-ca-20211013.der
  SPECS/shim-unsigned-x64/mok-allocate-MOK-config-table-as-BootServicesData.patch
  SPECS/shim-unsigned-x64/shim-another-attempt-to-fix-load-options-handling.patch
  SPECS/shim-unsigned-x64/shim-unsigned-x64.signatures.json
  SPECS/shim-unsigned-x64/shim-unsigned-x64.spec
  SPECS/shim/shim.signatures.json
  SPECS/shim/shim.spec
Labels: Packaging

#2179 python-bcrypt: add an explicit BR on 'pip' to enable ptest
  SPECS/python-bcrypt/python-bcrypt.spec
Labels: Packaging

#2180 Upgrade python ntplib to 0.4.0
  SPECS/python-ntplib/LICENSE.PTR
  SPECS/python-ntplib/python-ntplib.signatures.json
  SPECS/python-ntplib/python-ntplib.spec
  cgmanifest.json
Labels: Packaging

#2176 [1.0-dev] Upgrading MariaDB to v10.3.32 for 3 CVEs
  SPECS/mariadb/cmake_3.21.4_fix.patch
  SPECS/mariadb/generate_source_tarball.sh
  SPECS/mariadb/mariadb.signatures.json
  SPECS/mariadb/mariadb.spec
  cgmanifest.json
Labels: Packaging

#2194 [main] update json-glib to v1.6.6
  SPECS/json-glib/Remove-references-to-mesontest-binary.patch
  SPECS/json-glib/json-glib.signatures.json
  SPECS/json-glib/json-glib.spec
  cgmanifest.json
Labels: Packaging

#2182 python-twisted: use `py39` as tox environment to enable ptest
  SPECS/python-twisted/python-twisted.spec
Labels: Packaging

#2184 python-pycparser: use correct test file path to enable ptest
  SPECS/python-pycparser/python-pycparser.spec
Labels: Packaging

#2185 libmspack: use `make -k check` to enable ptest
  SPECS/libmspack/libmspack.spec
Labels: Packaging

#2198 m2crypto: skip testing TLS1 & a non FIPS test to enable ptest
  SPECS/m2crypto/0001-skip-test_tls1_nok-which-cant-be-run-in-FIPS.patch
  SPECS/m2crypto/m2crypto.spec
Labels: Packaging

#2199 python-repoze-lru: use `py39` as tox env to enable ptest
  SPECS/python-repoze-lru/python-repoze-lru.spec
Labels: Packaging

#2186 add 00-fix-lttng-live-array-access.patch to babeltrace2
  SPECS/babeltrace2/00-fix-lttng-live-array-access.patch
  SPECS/babeltrace2/babeltrace2.spec
Labels: Packaging

#2207 python-attrs: use `py39` as tox env to enable ptest
  SPECS/python-attrs/python-attrs.spec
Labels: Packaging

#2210 python-zope-interface: add an explicit BR on 'pip' to enable ptest
  SPECS/python-zope-interface/python-zope-interface.spec
Labels: Packaging

#2214 python-routes: use `py39` as tox environment to enable ptest
  SPECS/python-routes/python-routes.spec
Labels: Packaging

#2208 python-certifi: use `%pytest` to enable ptest
  SPECS/python-certifi/python-certifi.spec
Labels: Packaging

#2224 Skip "Microsoft" repo for non-amd64 architectures
  toolkit/scripts/analysis.mk
Labels: Tools

#2225 [main] Fixing `at.spec` function calls.
  SPECS/at/at.spec
Labels: Packaging

#2232 [main] Fixing `pyproject-rpm-macros`.
  SPECS/pyproject-rpm-macros/macros.pyproject
  SPECS/pyproject-rpm-macros/pyproject-rpm-macros.signatures.json
Labels: Packaging

#2234 Add cloud-init-azure-kvp to azurevm package list
  toolkit/imageconfigs/packagelists/azurevm-packages.json
Labels: Schema

#2235 Sync 2.0 azurevm-packages with 1.0
  toolkit/imageconfigs/packagelists/azurevm-packages.json
Labels: Schema

#2227 [1.0] [CVEs] Nopatch openssl CVE-2021-4160
  SPECS/openssl/CVE-2021-4160.nopatch
  SPECS/openssl/openssl.spec
Labels: Packaging

#2226 Clarifying certificates' configuration docs.
  toolkit/docs/security/ca-certificates.md
Labels: documentation

#2241 [main] [core] Fix double packaging of python3-py
  SPECS/python-py/python-py.spec
Labels: Packaging

#2246 [main] Clarifying certificate configuration. (CP of #2226)
  toolkit/docs/security/ca-certificates.md
Labels: documentation

#2251 pcaudiolib: fix signature.json
  SPECS/pcaudiolib/pcaudiolib.signatures.json
Labels: Packaging

#2240 [main] [core] Prevent empty python-lxml RPM from being produced
  SPECS/python-lxml/python-lxml.spec
Labels: Packaging

#2256 [main] [core] Remove python2 from ansible, llvm, syslog-ng packages
  SPECS/ansible/ansible.spec
  SPECS/llvm/llvm.spec
  SPECS/syslog-ng/syslog-ng.spec
Labels: Packaging

#2260 [main] [core] Remove python2 from kf5-ki18n, heimdal, libvirt
  SPECS/heimdal/heimdal-7.5.0-explicit-python2.patch
  SPECS/heimdal/heimdal-python3.patch
  SPECS/heimdal/heimdal.spec
  SPECS/kf5-ki18n/kf5-ki18n.spec
  SPECS/libvirt/libvirt.spec
Labels: Packaging

#2264 [main] [core] Remove python2 from scons, libserf
  SPECS/libserf/libserf-python3.patch
  SPECS/libserf/libserf.spec
  SPECS/scons/scons.spec
Labels: Packaging

#2266 [main] [core] Remove python2 from subversion, OpenIPMI packages
  SPECS/OpenIPMI/OpenIPMI-py39.patch
  SPECS/OpenIPMI/OpenIPMI.spec
  SPECS/subversion/subversion.spec
Labels: Packaging

#2268 [main] [core] Fix ceph build with snappy >= 1.1.9
  SPECS/ceph/ceph-snappy-fix
  SPECS/ceph/ceph.spec
Labels: Packaging

#2270 [1.0] [CVEs] Patch strongswan CVE-2021-45079
  SPECS/strongswan/CVE-2021-45079.patch
  SPECS/strongswan/strongswan.spec
Labels: Packaging

#2281 libcacard: add an explicit BR on `softhsm` & `opensc` to enable ptest
  SPECS/libcacard/libcacard.spec
Labels: Packaging

#2278 libaio: introduce patch to fix gcc-11 bug to enable ptest
  SPECS/libaio/fix-gcc11-bug-and-parity-with-upstream.patch
  SPECS/libaio/libaio.spec
Labels: Packaging

#2279 autogen: add an explicit BR on `perl(lib)` to fix build & enable ptest
  SPECS/autogen/autogen.spec
  cgmanifest.json
Labels: Packaging

#2280 nss: add subpackage `nss-tools` & drop `Provides: nss-tools`
  SPECS/nss/nss.spec
Labels: Packaging

#2285 meson: add explicit BR's & drop un-needed BR's to enable ptest
  SPECS/meson/meson.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#2284 golang inherit ENV proxy settings
  toolkit/tools/internal/network/network.go
Labels: Tools

#2286 golang: inherit proxy settings
  toolkit/tools/internal/network/network.go
Labels: Tools

#2289 [1.0] Add cloud-init patches to support preprovisioned VMs
  SPECS/cloud-init/apply-netconfig-every-boot.patch
  SPECS/cloud-init/cloud-init.spec
  SPECS/cloud-init/update-metadata-on-BOOT_NEW_INSTANCE.patch
Labels: Packaging

#2340 openssl-pkcs11: move BR on doxygen out of the `%{with_check}` gate to fix build
  SPECS/openssl-pkcs11/openssl-pkcs11.spec
Labels: Packaging

#2325 [main] Moving remaining `libvirt-*` packages into `SPECS`.
  SPECS/libvirt-dbus/libvirt-dbus.signatures.json
  SPECS/libvirt-dbus/libvirt-dbus.spec
  SPECS/libvirt-glib/libvirt-glib-4.0.0-cast-align.patch
  SPECS/libvirt-glib/libvirt-glib.signatures.json
  SPECS/libvirt-glib/libvirt-glib.spec
  SPECS/libvirt-python/libvirt-python.signatures.json
  SPECS/libvirt-python/libvirt-python.spec
  SPECS/libvirt/libvirt.spec
  SPECS/lzop/lzop.signatures.json
  SPECS/lzop/lzop.spec
  SPECS/radvd/radvd-double_free_ifacelist.patch
  SPECS/radvd/radvd-endianess.patch
  SPECS/radvd/radvd-nodaemon_manpage,patch
  SPECS/radvd/radvd-stderr_logging.patch
  SPECS/radvd/radvd-tmpfs.conf
  SPECS/radvd/radvd-werror.patch
  SPECS/radvd/radvd.signatures.json
  SPECS/radvd/radvd.spec
Labels: Packaging

#2348 ocaml: introduce patch to remove unused var to enable ptest
  SPECS/ocaml/0004-remove-unused-var-in-alloc_aync_stubs.patch
  SPECS/ocaml/ocaml.spec
Labels: Packaging

#2035 Initial SymCrypt + SymCrypt-OpenSSL integration
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.signatures.json
  SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.spec
  SPECS/SymCrypt/SymCrypt.signatures.json
  SPECS/SymCrypt/SymCrypt.spec
  SPECS/openssl/openssl-1.1.1-fips-SymCrypt.patch
  SPECS/openssl/openssl.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging
