Repository microsoft/azurelinux, pull requests merged in 2022-03, with the labels that each got.

#2358 kernel: Update input aarch64 config file
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
Labels: Packaging

#2359 [main] ModemManager fix for failing p-test
  SPECS/ModemManager/ModemManager.spec
Labels: Packaging

#2354 [main] Fix glibmm check
  SPECS/glibmm/glibmm.spec
Labels: Packaging

#2367 Add openssh dependency for git
  SPECS/git/git.spec
Labels: Packaging

#2363 fix utf8proc ptest
  SPECS/utf8proc/utf8proc.spec
Labels: Packaging

#2283 Re-add `tini-static` package
  SPECS/glibc/glibc.spec
  SPECS/moby-engine/moby-engine.spec
  SPECS/tini/tini.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#2371 perl-JSON: add an explicit BR on `perl(Tie::Array)` to enable ptest
  SPECS/perl-JSON/perl-JSON.spec
Labels: Packaging

#2381 perl-CPAN-Meta-Check: add an explicit BR on `perl(Test::Deep)` to enable ptest
  SPECS/perl-CPAN-Meta-Check/perl-CPAN-Meta-Check.spec
Labels: Packaging

#2383 [1.0-dev] python3: Add patch to fix XML tests with newer expat
  SPECS/python3/fix-xml-tests-expat.patch
  SPECS/python3/python3.spec
Labels: Packaging

#2396 [main] Resolve missing comment on tboot
  SPECS/tboot/tboot.spec
Labels: Packaging

#2391 Generate rpm manifests for distroless container images
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/internal/shell/shell.go
Labels: Tools

#2394 python-botocore: drop un-needed BRs & switch to tox to enable ptest
  SPECS/python-botocore/python-botocore.spec
Labels: Packaging

#2400 tboot: fix signatures.json
  SPECS/tboot/tboot.signatures.json
Labels: Packaging

#2398 Generate rpm manifests for distroless container images (main)
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/internal/shell/shell.go
Labels: Tools

#2122 Enable JIT feature on supported architectures
  SPECS/pcre/pcre.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#2411 [main] Temporarily make SymCrypt exclusivearch x86_64
  SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.spec
  SPECS/SymCrypt/SymCrypt.spec
Labels: Packaging

#2412 Update ToolkitVersion to RELEASE_VERSION at compile time
  toolkit/scripts/tools.mk
  toolkit/tools/internal/exe/exe.go
Labels: Tools

#2409 nlohmann-json: add an explicit BR on `git` to enable ptest
  SPECS/nlohmann-json/nlohmann-json.spec
Labels: Packaging, ptest

#2404 libxslt: drop fuzz testing to enable ptest
  SPECS/libxslt/libxslt.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: ptest

#2402 c-ares: refactor check section to enable ptest
  SPECS/c-ares/c-ares.spec
Labels: Packaging, ptest

#2405 libstoragemgmt: add an explicit BR on `git` to enable ptest
  SPECS/libstoragemgmt/libstoragemgmt.spec
Labels: Packaging, ptest

#2390 Fix rust ptest
  SPECS/rust/rust.spec
Labels: Packaging, ptest

#2393 fix python-wheel ptest
  SPECS/python-wheel/python-wheel.spec
Labels: Packaging, ptest

#2406 Fix sphinxcontrib websupport ptest
  SPECS/python-sphinxcontrib-websupport/add_deps_in_tox.patch
  SPECS/python-sphinxcontrib-websupport/python-sphinxcontrib-websupport.signatures.json
  SPECS/python-sphinxcontrib-websupport/python-sphinxcontrib-websupport.spec
  cgmanifest.json
Labels: ptest

#2429 Restart containerd service 10 sec after crash
  SPECS/moby-containerd/containerd.service
  SPECS/moby-containerd/moby-containerd.signatures.json
  SPECS/moby-containerd/moby-containerd.spec
Labels: Packaging

#2430 [main] correcting libcacard ptest build requirement.
  SPECS/libcacard/libcacard.spec
Labels: Packaging

#2385 [main] Enable NO_IOMMU kernel flag.
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#2423 openssl: add an explicit BR on `perl{(Test::Harness), (Math::BigInt)}` to enable ptest
  SPECS/openssl/openssl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: ptest

#2427 git: add explicit BRs & skip `send-email` tests to enable ptest
  SPECS/git/git.spec
Labels: Packaging, ptest

#2422 python-jsonschema: bump version to 3.2.0 & switch to tox to enable ptest
  SPECS/python-jsonschema/python-jsonschema.signatures.json
  SPECS/python-jsonschema/python-jsonschema.spec
  cgmanifest.json
Labels: ptest

#2222 gawk: generate locale `en_US.iso88591` in `%check` section to enable ptest
  SPECS/gawk/gawk.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: ptest

#2428 fillup: introduce patch to enable ptest
  SPECS/fillup/fillup-test-create-DIFFERENCE-dir-before-testing.patch
  SPECS/fillup/fillup.spec
Labels: Packaging, ptest

#2433 kernel: Address CVE-2021-4090, CVE-2021-4093, CVE-2022-25265, CVE-2021-20320, CVE-2021-20321, CVE-2022-0382, CVE-2022-0617
  SPECS/kernel/CVE-2021-20320.nopatch
  SPECS/kernel/CVE-2021-20321.nopatch
  SPECS/kernel/CVE-2021-4090.nopatch
  SPECS/kernel/CVE-2021-4093.nopatch
  SPECS/kernel/CVE-2022-0382.nopatch
  SPECS/kernel/CVE-2022-0617.nopatch
  SPECS/kernel/CVE-2022-25265.nopatch
  SPECS/kernel/kernel.spec
Labels: Packaging

#2437 [main] Remove envoy-source
  SPECS/envoy/envoy.spec
Labels: Packaging

#2443 [1.0-dev] Fix td-agent build break
  SPECS/td-agent/td-agent.patch
  SPECS/td-agent/td-agent.spec
Labels: Packaging

#2438 Update packages: ccache chrony cronie curl
  SPECS/ccache/ccache.signatures.json
  SPECS/ccache/ccache.spec
  SPECS/chrony/chrony-packettest.patch
  SPECS/chrony/chrony-service-helper.patch
  SPECS/chrony/chrony.signatures.json
  SPECS/chrony/chrony.spec
  SPECS/chrony/sys-linux-testfix.patch
  SPECS/cronie/cronie.signatures.json
  SPECS/cronie/cronie.spec
  SPECS/curl/CVE-2021-22897.patch
  SPECS/curl/CVE-2021-22898.patch
  SPECS/curl/CVE-2021-22901.patch
  SPECS/curl/CVE-2021-22922.nopatch
  SPECS/curl/CVE-2021-22923.nopatch
  SPECS/curl/CVE-2021-22924.patch
  SPECS/curl/CVE-2021-22925.patch
  SPECS/curl/curl.signatures.json
  SPECS/curl/curl.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: ptest

#2425 fix python-sphinx_rtd_theme ptest
  SPECS/python-sphinx_rtd_theme/python-sphinx_rtd_theme.spec
Labels: Packaging, ptest

#2435 toolkit only - use local /run folder in chroot instead of mounted tmpfs
  toolkit/tools/internal/buildpipeline/buildpipeline.go
Labels: Tools

#2448 Upgrade Sudo to 1.9.10
  SPECS/sudo/sudo.signatures.json
  SPECS/sudo/sudo.spec
  cgmanifest.json
Labels: Packaging

#2407 fix tox-current-env ptest
  SPECS/python-tox-current-env/python-tox-current-env.spec
Labels: Packaging, ptest

#2461 kernel: Address CVE-2022-0847
  SPECS/kernel/CVE-2022-0847.nopatch
  SPECS/kernel/kernel.spec
Labels: Packaging

#2464 kernel: cherry-pick CVE nopatches
  SPECS/kernel/CVE-2021-20320.nopatch
  SPECS/kernel/CVE-2021-20321.nopatch
  SPECS/kernel/CVE-2021-4090.nopatch
  SPECS/kernel/CVE-2021-4093.nopatch
  SPECS/kernel/CVE-2022-0382.nopatch
  SPECS/kernel/CVE-2022-0617.nopatch
  SPECS/kernel/CVE-2022-0847.nopatch
  SPECS/kernel/CVE-2022-25265.nopatch
  SPECS/kernel/kernel.spec
Labels: Packaging

#2228 [main] upgrade mariadb to v10.6.7
  SPECS/mariadb/cmake_3.21.4_fix.patch
  SPECS/mariadb/generate_source_tarball.sh
  SPECS/mariadb/mariadb.signatures.json
  SPECS/mariadb/mariadb.spec
  cgmanifest.json
Labels: Packaging, ptest

#2457 fix python pynacl ptest
  SPECS/python-pynacl/fix_average_value_hypothesis_error.patch
  SPECS/python-pynacl/fix_import_unlimited_error.patch
  SPECS/python-pynacl/python-pynacl.spec
Labels: Packaging, ptest

#2465 Bootstrap toolchain build with mariner container
  toolkit/scripts/toolchain/cgmanifest.json
  toolkit/scripts/toolchain/container/Dockerfile
  toolkit/scripts/toolchain/container/version-check-container.sh
Labels: Tools

#2481 libpq, postgresql: gate `--with-ldap` with `%{with_check}` to enable build
  SPECS/libpq/libpq.spec
  SPECS/postgresql/postgresql.spec
Labels: Packaging

#2491 [1.0] Installing missing dependencies for `libxml2`.
  SPECS/libxml2/libxml2.spec
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
Labels: Tools

#2505 Fix boot issue with pam
  SPECS/pam/pam.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#2472 [1.0] Nopatching CVE-2022-25634 in `qt5-qtsvg`.
  SPECS/qt5-qtsvg/CVE-2022-25634.nopatch
  SPECS/qt5-qtsvg/qt5-qtsvg.spec
Labels: Packaging

#2494 [1.0] kernel: Address CVE-2021-3656, CVE-2021-3609, CVE-2021-3744
  SPECS/kernel/CVE-2021-3609.nopatch
  SPECS/kernel/CVE-2021-3656.nopatch
  SPECS/kernel/CVE-2021-3744.nopatch
  SPECS/kernel/kernel.spec
Labels: Packaging

#2525 qemu-kvm: address CVE-2021-{3607, 3608, 3930, 3947, 4145}
  SPECS/qemu-kvm/CVE-2021-3607.patch
  SPECS/qemu-kvm/CVE-2021-3608.patch
  SPECS/qemu-kvm/CVE-2021-3930.patch
  SPECS/qemu-kvm/CVE-2021-3947.nopatch
  SPECS/qemu-kvm/CVE-2021-4145.nopatch
  SPECS/qemu-kvm/qemu-kvm.spec
Labels: security, Packaging, 1.0-dev

#2537 Fix build issue with audit and shadow-utils
  SPECS/audit/audit.spec
  SPECS/bubblewrap/bubblewrap.spec
  SPECS/shadow-utils/shadow-utils.spec
Labels: Packaging

#2544 [main] msopenjdk-11: Upgrade to 11.0.14.1+1-LTS-31207
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
Labels: main

#2503 [main] Promote libsodium to core and upgrade python-pynacl to 1.5.0
  SPECS/libsodium/libsodium.signatures.json
  SPECS/libsodium/libsodium.spec
  SPECS/python-pynacl/python-pynacl.signatures.json
  SPECS/python-pynacl/python-pynacl.spec
  cgmanifest.json
Labels: ptest

#2502 python-frozendict: Upgrade to 2.3.0
  SPECS/python-frozendict/fix_imports_for_python3_9.patch
  SPECS/python-frozendict/import_from_abc_first.patch
  SPECS/python-frozendict/python-frozendict.signatures.json
  SPECS/python-frozendict/python-frozendict.spec
  cgmanifest.json
Labels: ptest

#2492 [main] python-netifaces: Upgrade to 0.11.0
  SPECS/python-netifaces/python-netifaces.signatures.json
  SPECS/python-netifaces/python-netifaces.spec
  cgmanifest.json
Labels: ptest

#2488 [main] python-ecdsa: Upgrade to 0.17.0
  SPECS/python-ecdsa/disable_nist192_test.patch
  SPECS/python-ecdsa/python-ecdsa.signatures.json
  SPECS/python-ecdsa/python-ecdsa.spec
  cgmanifest.json
Labels: ptest

#2542 Update polkit to disable man-pages
  SPECS/polkit/polkit.spec
Labels: Packaging, main

#2504 fakeroot: update `relax_tartest.patch` to enable ptest
  SPECS/fakeroot/fakeroot.spec
  SPECS/fakeroot/relax_tartest.patch
Labels: Packaging, ptest, main

#2480 autoconf: add an explicit BR on `perl(File::Find)` to enable ptest
  SPECS/autoconf/autoconf.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: ptest, main

#2533 bind: bump version to 9.16.27 to address CVE-2021-25220 & CVE-2022-0396
  SPECS/bind/bind.signatures.json
  SPECS/bind/bind.spec
  cgmanifest.json
Labels: security, Packaging, 1.0-dev

#2500 [main] Re-Enable envoy v1.14.4 in Mariner
  SPECS/envoy/0001-build-Use-Go-from-host.patch
  SPECS/envoy/0002-build-update-several-go-dependencies-11581.patch
  SPECS/envoy/0002-disable-wee8-mismatched-new-delete-warning.patch
  SPECS/envoy/0003-build-Add-explicit-requirement-on-rules_cc.patch
  SPECS/envoy/0004-build-Use-new-bazel.patch
  SPECS/envoy/0005-fix-gcc11-compiler-issue.patch
  SPECS/envoy/envoy.signatures.json
  SPECS/envoy/envoy.spec
  cgmanifest.json
Labels: main

#2539 [main] Restoring more extended specs.
  SPECS-EXTENDED/ORBit2/ORBit2-2.14.3-multilib.patch
  SPECS-EXTENDED/ORBit2/ORBit2-2.14.3-ref-leaks.patch
  SPECS-EXTENDED/ORBit2/ORBit2-allow-deprecated.patch
  SPECS-EXTENDED/ORBit2/ORBit2-make-j-safety.patch
  SPECS-EXTENDED/ORBit2/ORBit2.signatures.json
  SPECS-EXTENDED/ORBit2/ORBit2.spec
  SPECS-EXTENDED/nfs4-acl-tools/nfs4-acl-tools.signatures.json
  SPECS-EXTENDED/nfs4-acl-tools/nfs4-acl-tools.spec
  SPECS-EXTENDED/orangefs/orangefs-autotools-2.71.patch
  SPECS-EXTENDED/orangefs/orangefs.signatures.json
  SPECS-EXTENDED/orangefs/orangefs.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#2518 [main] Patching CVE-2022-0778 in `openssl`.
  SPECS/openssl/CVE-2022-0778.patch
  SPECS/openssl/openssl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#2547 Modify pam to use Recommends for runtime dependencies
  SPECS/pam/pam.spec
Labels: Packaging, main

#2442 Bug 38383347: vmtoolsd.service should only run on VMware
  SPECS/open-vm-tools/open-vm-tools.spec
Labels: Packaging, main

#2512 [main] iperf3: Update to 3.11
  SPECS/iperf3/disablepg.patch
  SPECS/iperf3/iperf3.signatures.json
  SPECS/iperf3/iperf3.spec
  cgmanifest.json
Labels: main

#2543 [main] toolchain: Remove alsa-lib
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/resources/manifests/package/update_manifests.sh
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
Labels: main

#2485 Upgrade nodejs to 16.14.0
  SPECS/nodejs/clean-source-tarball.sh
  SPECS/nodejs/disable-tlsv1-tlsv1-1.patch
  SPECS/nodejs/nodejs.signatures.json
  SPECS/nodejs/nodejs.spec
  SPECS/nodejs/patch_tls_nodejs14.patch
  cgmanifest.json
Labels: main

#2515 [main] upgrading libarchive to v3.6.0
  SPECS/libarchive/0001-test_write_disk_secure-properly-check-if-lchmod-is-s.patch
  SPECS/libarchive/libarchive.signatures.json
  SPECS/libarchive/libarchive.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/toolchain-remote-wget-list
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
Labels: main

#2534 [main] fix toolchain pkgs - coreutils, file
  SPECS/coreutils/coreutils.spec
  SPECS/coreutils/skip_test_if_run_as_root.patch
  SPECS/file/file.spec
  SPECS/file/fix_xz_mime_type_reporting.patch
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: ptest, main

#2535 libtiff: backport patches from upstream to fix CVE-2022-0561 & CVE-2022-0562
  SPECS/libtiff/CVE-2022-0561.patch
  SPECS/libtiff/CVE-2022-0562.patch
  SPECS/libtiff/CVE-2022-0891.patch
  SPECS/libtiff/libtiff.spec
Labels: security, Packaging, 1.0-dev

#2522 python-*: use `py%{python3_version_nodots}` instead of `py39` as tox env
  SPECS/python-attrs/python-attrs.spec
  SPECS/python-botocore/python-botocore.spec
  SPECS/python-cherrypy/python-cherrypy.spec
  SPECS/python-coverage/python-coverage.spec
  SPECS/python-execnet/python-execnet.spec
  SPECS/python-jinja2/python-jinja2.spec
  SPECS/python-mako/python-mako.spec
  SPECS/python-pbr/python-pbr.spec
  SPECS/python-pytest-cov/python-pytest-cov.spec
  SPECS/python-repoze-lru/python-repoze-lru.spec
  SPECS/python-requests/python-requests.spec
  SPECS/python-routes/python-routes.spec
  SPECS/python-tox-current-env/python-tox-current-env.spec
  SPECS/python-twisted/python-twisted.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, ptest, main

#2531 Update cppunit to v1.15.1
  SPECS/cppunit/cppunit.signatures.json
  SPECS/cppunit/cppunit.spec
  cgmanifest.json
Labels: main

#2498 upgrade libburn libfastjson libgudev libisoburn libisofs libcap-ng libconfini
  SPECS/libburn/libburn.signatures.json
  SPECS/libburn/libburn.spec
  SPECS/libcap-ng/libcap-ng.signatures.json
  SPECS/libcap-ng/libcap-ng.spec
  SPECS/libconfini/libconfini.signatures.json
  SPECS/libconfini/libconfini.spec
  SPECS/libfastjson/libfastjson.signatures.json
  SPECS/libfastjson/libfastjson.spec
  SPECS/libgudev/libgudev.signatures.json
  SPECS/libgudev/libgudev.spec
  SPECS/libisoburn/libisoburn.signatures.json
  SPECS/libisoburn/libisoburn.spec
  SPECS/libisofs/libisofs.signatures.json
  SPECS/libisofs/libisofs.spec
  cgmanifest.json
Labels: main

#2519 ugrade libcgroup - fix missing requires in gtest-devel
  SPECS/gtest/gtest.spec
  SPECS/libcgroup/libcgroup-0.37-chmod.patch
  SPECS/libcgroup/libcgroup-0.40.rc1-coverity.patch
  SPECS/libcgroup/libcgroup-0.40.rc1-fread.patch
  SPECS/libcgroup/libcgroup-0.40.rc1-templates-fix.patch
  SPECS/libcgroup/libcgroup-0.40.rc1.patch
  SPECS/libcgroup/libcgroup-0.41-CVE-2018-14348.patch
  SPECS/libcgroup/libcgroup-0.41-api.c-fix-order-of-memory-subsystem-parameters.patch
  SPECS/libcgroup/libcgroup-0.41-api.c-preserve-dirty-flag.patch
  SPECS/libcgroup/libcgroup-0.41-api.c-support-for-setting-multiline-values-in-contro.patch
  SPECS/libcgroup/libcgroup-0.41-change-cgroup-of-threads.patch
  SPECS/libcgroup/libcgroup-0.41-fix-infinite-loop.patch
  SPECS/libcgroup/libcgroup-0.41-fix-log-level.patch
  SPECS/libcgroup/libcgroup-0.41-lex.patch
  SPECS/libcgroup/libcgroup-0.41-prevent-buffer-overflow.patch
  SPECS/libcgroup/libcgroup-0.41-size-of-controller-values.patch
  SPECS/libcgroup/libcgroup-0.41-tasks-file-warning.patch
  SPECS/libcgroup/libcgroup.signatures.json
  SPECS/libcgroup/libcgroup.spec
  SPECS/libcgroup/no-googletests.patch
  cgmanifest.json
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#2550 [main] Fixes to `SPECS-EXTENDED`.
  SPECS-EXTENDED/alsa-firmware/alsa-firmware.signatures.json
  SPECS-EXTENDED/alsa-firmware/alsa-firmware.spec
  SPECS-EXTENDED/babl/babl.spec
  SPECS-EXTENDED/catatonit/catatonit.signatures.json
  SPECS-EXTENDED/catatonit/catatonit.spec
  SPECS-EXTENDED/spice-vdagent/0001-vdagentd-work-around-GLib-s-fork-issues.patch
  SPECS-EXTENDED/spice-vdagent/0002-vdagentd-init-static-uinput-before-fork.patch
  SPECS-EXTENDED/spice-vdagent/spice-vdagent.signatures.json
  SPECS-EXTENDED/spice-vdagent/spice-vdagent.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#2556 [main] pyasn1-modules: Upgrade to 0.2.8
  SPECS/pyasn1-modules/pyasn1-modules.signatures.json
  SPECS/pyasn1-modules/pyasn1-modules.spec
  cgmanifest.json
Labels: main

#2526 libvirt: patch CVE-2021-3631 & CVE-2021-3667
  SPECS/libvirt/CVE-2021-3631.patch
  SPECS/libvirt/CVE-2021-3667.patch
  SPECS/libvirt/libvirt.spec
Labels: security, Packaging, 1.0-dev

#2554 c-ares: drop all `LiveSearch` DNS lookup tests to enable ptest
  SPECS/c-ares/c-ares.spec
Labels: Packaging, ptest, main

#2558 kernel: Address CVE-2021-3640, CVE-2021-3739, CVE-2022-0492, CVE-2022-0516, CVE-2021-3732, CVE-2022-0433, CVE-2021-4095
  SPECS/kernel/CVE-2021-3640.nopatch
  SPECS/kernel/CVE-2021-3732.nopatch
  SPECS/kernel/CVE-2021-3739.nopatch
  SPECS/kernel/CVE-2021-4095.nopatch
  SPECS/kernel/CVE-2022-0433.nopatch
  SPECS/kernel/CVE-2022-0492.nopatch
  SPECS/kernel/CVE-2022-0516.nopatch
  SPECS/kernel/kernel.spec
Labels: Packaging, 1.0-dev

#2560 [main] Regression fixes in `SPECS-EXTENDED`.
  SPECS-EXTENDED/GConf2/GConf2.spec
  SPECS-EXTENDED/accountsservice/accountsservice.spec
  SPECS-EXTENDED/gcr/gcr.spec
  SPECS-EXTENDED/gom/gom.spec
  SPECS-EXTENDED/graphene/graphene.spec
  SPECS-EXTENDED/iio-sensor-proxy/iio-sensor-proxy.spec
  SPECS-EXTENDED/keybinder3/keybinder3.spec
  SPECS-EXTENDED/libbytesize/libbytesize.spec
  SPECS-EXTENDED/libdazzle/libdazzle.spec
  SPECS-EXTENDED/libgexiv2/libgexiv2.spec
  SPECS-EXTENDED/libgit2-glib/libgit2-glib.spec
  SPECS-EXTENDED/libgxps/libgxps.spec
  SPECS-EXTENDED/libical/libical.spec
  SPECS-EXTENDED/libiptcdata/libiptcdata.signatures.json
  SPECS-EXTENDED/libiptcdata/libiptcdata.spec
  SPECS-EXTENDED/libjcat/libjcat.spec
  SPECS-EXTENDED/libldm/libldm.spec
  SPECS-EXTENDED/libmodulemd1/libmodulemd1.spec
  SPECS-EXTENDED/libpeas/libpeas.spec
  SPECS-EXTENDED/libraqm/libraqm.spec
  SPECS-EXTENDED/libucil/libucil-0.9.10-include-alsa.patch
  SPECS-EXTENDED/libucil/libucil-0.9.10-leaks.patch
  SPECS-EXTENDED/libucil/libucil-0.9.10-warnings.patch
  SPECS-EXTENDED/libucil/libucil-0.9.8-bz627890.patch
  SPECS-EXTENDED/libucil/libucil.signatures.json
  SPECS-EXTENDED/libucil/libucil.spec
  SPECS-EXTENDED/libunicap/libunicap-0.9.12-arraycmp.patch
  SPECS-EXTENDED/libunicap/libunicap-0.9.12-datadirname.patch
  SPECS-EXTENDED/libunicap/libunicap-0.9.12-gcc10.patch
  SPECS-EXTENDED/libunicap/libunicap-0.9.12-includes.patch
  SPECS-EXTENDED/libunicap/libunicap-0.9.12-memerrs.patch
  SPECS-EXTENDED/libunicap/libunicap-0.9.12-videodev.patch
  SPECS-EXTENDED/libunicap/libunicap-0.9.12-warnings.patch
  SPECS-EXTENDED/libunicap/libunicap-bz641623.patch
  SPECS-EXTENDED/libunicap/libunicap-bz642118.patch
  SPECS-EXTENDED/libunicap/libunicap-filter.sh
  SPECS-EXTENDED/libunicap/libunicap.signatures.json
  SPECS-EXTENDED/libunicap/libunicap.spec
  SPECS-EXTENDED/libwnck3/libwnck3.spec
  SPECS-EXTENDED/libxmlb/libxmlb.spec
  SPECS-EXTENDED/orc/orc.spec
  SPECS-EXTENDED/switcheroo-control/switcheroo-control.spec
  SPECS-EXTENDED/unique3/unique3.spec
  SPECS-EXTENDED/upower/upower.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#2561 [1.0] Backport systemd dhcp fix and enable netplan
  SPECS/cloud-init/apply-netconfig-every-boot.patch
  SPECS/cloud-init/cloud-init.signatures.json
  SPECS/cloud-init/cloud-init.spec
  SPECS/cloud-init/mariner-21.4.patch
  SPECS/cloud-init/networkd.patch
  SPECS/cloud-init/update-metadata-on-BOOT_NEW_INSTANCE.patch
  SPECS/systemd/Backport-fix-dhcp-routes.patch
  SPECS/systemd/systemd-bootstrap.spec
  SPECS/systemd/systemd.spec
  cgmanifest.json
  toolkit/imageconfigs/packagelists/azurevm-packages.json
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#2557 upgrade leveldb to 1.23
  SPECS/leveldb/0001-Allow-leveldbjni-build.patch
  SPECS/leveldb/0002-Added-a-DB-SuspendCompations-and-DB-ResumeCompaction.patch
  SPECS/leveldb/0003-allow-Get-calls-to-avoid-copies-into-std-string.patch
  SPECS/leveldb/0004-bloom_test-failure-on-big-endian-archs.patch
  SPECS/leveldb/0006-revert-no-rtti.patch
  SPECS/leveldb/0007-detect-system-gtest.patch
  SPECS/leveldb/leveldb.signatures.json
  SPECS/leveldb/leveldb.spec
  cgmanifest.json
Labels: main

#2567 [main] Fixing `ModemManager` build.
  SPECS/ModemManager/ModemManager.spec
Labels: Packaging, main

#2562 Update httpd to 2.4.53 to fix CVE-2022-22719, CVE-2022-22720, CVE-2022-22721, CVE-2022-23943
  SPECS/httpd/httpd-2.4.52-blfs_layout-1.patch
  SPECS/httpd/httpd-2.4.53-blfs_layout-3.patch
  SPECS/httpd/httpd.signatures.json
  SPECS/httpd/httpd.spec
  cgmanifest.json
Labels: 1.0-dev

#2497 package iscsi-init.service with iscsi-initiator-utils
  SPECS/iscsi-initiator-utils/iscsi-initiator-utils.spec
Labels: Packaging, main

#2559 Upgraded python-mock to 4.0.3
  SPECS/python-mock/python-mock.signatures.json
  SPECS/python-mock/python-mock.spec
  cgmanifest.json
Labels: main

#2571 Modify pam to require audit-libs
  SPECS/pam/pam.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, main

#2566 python-uamqp: fix typo in BR
  SPECS-EXTENDED/python-uamqp/python-uamqp.spec
Labels: main

#2564 golang: bump version to 1.16.15 to address CVE-2022-24921
  SPECS/audit/audit.spec
  SPECS/blobfuse/blobfuse.spec
  SPECS/cni/cni.spec
  SPECS/coredns/coredns-1.7.0.spec
  SPECS/coredns/coredns-1.8.0.spec
  SPECS/coredns/coredns-1.8.4.spec
  SPECS/cri-tools/cri-tools.spec
  SPECS/etcd/etcd-3.4.13.spec
  SPECS/etcd/etcd-3.5.0.spec
  SPECS/flannel/flannel.spec
  SPECS/glide/glide.spec
  SPECS/go-md2man/go-md2man.spec
  SPECS/gobject-introspection/gobject-introspection.spec
  SPECS/golang/golang-1.16.signatures.json
  SPECS/golang/golang-1.16.spec
  SPECS/helm/helm.spec
  SPECS/moby-buildx/moby-buildx.spec
  SPECS/moby-cli/moby-cli.spec
  SPECS/moby-containerd/moby-containerd.spec
  SPECS/moby-engine/moby-engine.spec
  SPECS/moby-runc/moby-runc.spec
  SPECS/node-problem-detector/node-problem-detector.spec
  SPECS/nvidia-container-runtime/nvidia-container-runtime.spec
  SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec
  SPECS/telegraf/telegraf.spec
  cgmanifest.json
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#2538 [main] [kernel] [CVEs] Address kernel CVEs
  SPECS/kernel/CVE-1999-0524.nopatch
  SPECS/kernel/CVE-2008-4609.nopatch
  SPECS/kernel/CVE-2010-0298.nopatch
  SPECS/kernel/CVE-2010-4563.nopatch
  SPECS/kernel/CVE-2011-0640.nopatch
  SPECS/kernel/CVE-2021-3743.nopatch
  SPECS/kernel/CVE-2022-0492.nopatch
  SPECS/kernel/CVE-2022-26966.nopatch
  SPECS/kernel/kernel.spec
Labels: Packaging, main

#2570 [main] bmake: add patch to disable broken tests
  SPECS/bmake/bmake.spec
  SPECS/bmake/remove-inconsistent-time-tests.patch
Labels: Packaging, main

#2552 kernel: Disable fw loader fallback
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel-hyperv/config
  SPECS/kernel-hyperv/kernel-hyperv.signatures.json
  SPECS/kernel-hyperv/kernel-hyperv.spec
  SPECS/kernel/config
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, 1.0-dev

#2546 Use lz4 compression in systemd instead of zstd
  SPECS/systemd/systemd-bootstrap.spec
  SPECS/systemd/systemd.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#2573 [main][SPECS-EXTENDED] Fixing `fio` and `nbdkit`.
  SPECS-EXTENDED/fio/fio-3.29-link-t-io_uring-with-libaio.patch
  SPECS-EXTENDED/fio/fio-3.29-use-LDFLAGS-for-dynamic-engines.patch
  SPECS-EXTENDED/fio/fio.signatures.json
  SPECS-EXTENDED/fio/fio.spec
  SPECS-EXTENDED/iio-sensor-proxy/iio-sensor-proxy.spec
  SPECS-EXTENDED/ldns/ldns.spec
  SPECS-EXTENDED/nbdkit/nbdkit.spec
  cgmanifest.json
Labels: main

#2548 [main] Aligning `openssl` versions across toolchain build phases.
  toolkit/scripts/toolchain/container/toolchain-remote-wget-list
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
Labels: Tools, main

#2578 Fix snappy so it does not provide gtest/gmock headers and binaries
  SPECS/leveldb/leveldb.spec
  SPECS/snappy/detect_system_gtest.patch
  SPECS/snappy/snappy.spec
Labels: Packaging, main

#2201 [main] Add compressed firmware support
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel-rt/config
  SPECS/kernel-rt/kernel-rt.signatures.json
  SPECS/kernel-rt/kernel-rt.spec
  SPECS/kernel/config
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#2579 Fix libmetalink manifest issues
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/update_manifests.sh
Labels: main

#2577 enable containerd service restart
  SPECS/moby-containerd/containerd.service
  SPECS/moby-containerd/moby-containerd.signatures.json
  SPECS/moby-containerd/moby-containerd.spec
Labels: Packaging, main

#2580 Fix URL for toolchain patch lua-5.4.3-shared_library-1.patch
  toolkit/scripts/toolchain/container/toolchain-remote-wget-list
Labels: Tools, main

#2574 Port cloud-init ovf_is_accessible DataSourceAzure.py fix
  SPECS/cloud-init/azureds-set-ovf_is_accesible.patch
  SPECS/cloud-init/cloud-init.spec
Labels: Packaging, 1.0-dev

#2569 [main] Updating and fixing `fakeroot`.
  SPECS/fakeroot/also-wrap-stat-library-call.patch
  SPECS/fakeroot/debian_eglibc-fts-without-LFS.patch
  SPECS/fakeroot/fakeroot.signatures.json
  SPECS/fakeroot/fakeroot.spec
  SPECS/fakeroot/glibc_2.33_fix.patch
  SPECS/fakeroot/po4a.patch
  SPECS/fakeroot/relax_tartest.patch
  cgmanifest.json
Labels: main

#2584 Modify installutils to install audit-libs before systemd
  toolkit/tools/imagegen/installutils/installutils.go
Labels: Tools

#2585 Update vim to 8.2.4563 to fix CVE-2022-0943
  SPECS/vim/vim.signatures.json
  SPECS/vim/vim.spec
  cgmanifest.json
Labels: 1.0-dev

#2582 Enable Symcrypt Detection Patch in OpenSSL
  SPECS/openssl/openssl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#2586 Update systemd to requires(pre) audit-libs
  SPECS/systemd/systemd.spec
Labels: main

#2583 Upgrade openvswitch to 2.17.0
  SPECS/openvswitch/openvswitch.signatures.json
  SPECS/openvswitch/openvswitch.spec
  cgmanifest.json
Labels: main

#2555 Add pam configs for util-linux's runuser
  SPECS/util-linux/runuser
  SPECS/util-linux/runuser-l
  SPECS/util-linux/util-linux.signatures.json
  SPECS/util-linux/util-linux.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, Tools, main

#2588 Update python-werkzeug to 2.0.3
  SPECS/python-werkzeug/python-werkzeug.signatures.json
  SPECS/python-werkzeug/python-werkzeug.spec
  cgmanifest.json
Labels: main

#2589 Update python-yamlloader to 1.1.0
  SPECS/python-yamlloader/python-yamlloader.signatures.json
  SPECS/python-yamlloader/python-yamlloader.spec
  cgmanifest.json
Labels: main

#2590 Update python-zope-interface to 5.4.0
  SPECS/python-zope-interface/python-zope-interface.signatures.json
  SPECS/python-zope-interface/python-zope-interface.spec
  cgmanifest.json
Labels: main

#2530 [main] upgrading libdnet to v1.14
  SPECS/libdnet/libdnet.signatures.json
  SPECS/libdnet/libdnet.spec
  cgmanifest.json
Labels: main

#2591 [main] Updating `python-pytest-*` packages.
  SPECS/python-pytest-benchmark/python-pytest-benchmark.signatures.json
  SPECS/python-pytest-benchmark/python-pytest-benchmark.spec
  SPECS/python-pytest-forked/python-pytest-forked.signatures.json
  SPECS/python-pytest-forked/python-pytest-forked.spec
  SPECS/python-pytest-mock/python-pytest-mock.signatures.json
  SPECS/python-pytest-mock/python-pytest-mock.spec
  SPECS/python-pytest-mock/skip_broken_tests_since_3.6.1.patch
  SPECS/python-pytest-xdist/python-pytest-xdist.signatures.json
  SPECS/python-pytest-xdist/python-pytest-xdist.spec
  cgmanifest.json
Labels: main

#2592 [main] Adding missing links to 'pytest' inside `python3-pytest`.
  SPECS/pytest/pytest.spec
Labels: Packaging, main

#2594 Update powershell to 7.2.2 to resolve CVE-2020-8927
  SPECS/powershell/powershell.signatures.json
  SPECS/powershell/powershell.spec
  cgmanifest.json
Labels: 1.0-dev

#2593 Update nvme-cli spec and remove broken tests
  SPECS/nvme-cli/nvme-cli.spec
Labels: Packaging, ptest, main

#2596 Fix python-werkzeug url
  SPECS/python-werkzeug/python-werkzeug.spec
Labels: Packaging, main

#2597 Upgrade python-snowballstemmer
  SPECS/python-snowballstemmer/python-snowballstemmer.signatures.json
  SPECS/python-snowballstemmer/python-snowballstemmer.spec
  cgmanifest.json
Labels: main

#2598 Upgrade python-routes to 2.5.1
  SPECS/python-routes/python-routes.signatures.json
  SPECS/python-routes/python-routes.spec
  cgmanifest.json
Labels: main

#2595 [main] Updating `python-sphinx*` packages.
  SPECS/python-sphinx-theme-alabaster/python-sphinx-theme-alabaster.signatures.json
  SPECS/python-sphinx-theme-alabaster/python-sphinx-theme-alabaster.spec
  SPECS/python-sphinx-theme-py3doc-enhanced/python-sphinx-theme-py3doc-enhanced.signatures.json
  SPECS/python-sphinx-theme-py3doc-enhanced/python-sphinx-theme-py3doc-enhanced.spec
  SPECS/python-sphinx_rtd_theme/python-sphinx_rtd_theme-html5shiv.patch
  SPECS/python-sphinx_rtd_theme/python-sphinx_rtd_theme-unbundle-fonts.patch
  SPECS/python-sphinx_rtd_theme/python-sphinx_rtd_theme.signatures.json
  SPECS/python-sphinx_rtd_theme/python-sphinx_rtd_theme.spec
  SPECS/python-sphinxcontrib-websupport/python-sphinxcontrib-websupport.signatures.json
  SPECS/python-sphinxcontrib-websupport/python-sphinxcontrib-websupport.spec
  cgmanifest.json
Labels: main

#2575 Add RPM spec for terraform
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/terraform/terraform.signatures.json
  SPECS/terraform/terraform.spec
  cgmanifest.json
Labels: main

#2601 Build rubygems with ruby to fix build error in pipeline
  SPECS/ruby/ruby.spec
Labels: Packaging, main

#2605 [main] shadow-utils: Add requires `libpwquality`
  SPECS/shadow-utils/shadow-utils.spec
Labels: Packaging, main

#2540 [1.0-dev] Backport: SELinux policy updates and SELinux size reduction for policy base
  SPECS/selinux-policy/0005-systemd-Add-systemd-homed-and-systemd-userdbd.patch
  SPECS/selinux-policy/0006-systemd-ssh-Crypto-sysctl-use.patch
  SPECS/selinux-policy/0007-systemd-Additional-fixes-for-fs-getattrs.patch
  SPECS/selinux-policy/0008-systemd-Updates-for-generators-and-kmod-static-nodes.patch
  SPECS/selinux-policy/0009-Add-containers-policy.patch
  SPECS/selinux-policy/modules_targeted.conf
  SPECS/selinux-policy/selinux-policy.signatures.json
  SPECS/selinux-policy/selinux-policy.spec
  toolkit/imageconfigs/packagelists/selinux-full.json
Labels: 1.0-dev

#2599 upgrade python-urllib3 python-virtualenv python-wcwidth python-websocket-client
  SPECS/python-urllib3/CVE-2021-33503.patch
  SPECS/python-urllib3/python-urllib3.signatures.json
  SPECS/python-urllib3/python-urllib3.spec
  SPECS/python-virtualenv/python-virtualenv.signatures.json
  SPECS/python-virtualenv/python-virtualenv.spec
  SPECS/python-wcwidth/python-wcwidth.signatures.json
  SPECS/python-wcwidth/python-wcwidth.spec
  SPECS/python-websocket-client/python-websocket-client.signatures.json
  SPECS/python-websocket-client/python-websocket-client.spec
  cgmanifest.json
Labels: main

#2609 [main] Add netplan support to cloud-init
  SPECS/cloud-init/cloud-init.spec
  SPECS/cloud-init/mariner-22.1.patch
  toolkit/imageconfigs/packagelists/azurevm-packages.json
Labels: main

#2607 [main] Upgrading `python-pytest-xdist` to 2.5.0.
  SPECS-EXTENDED/python-flit/python-flit.signatures.json
  SPECS-EXTENDED/python-pluggy/python-pluggy.signatures.json
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/python-flit-core/python-flit-core.signatures.json
  SPECS/python-flit-core/python-flit-core.spec
  SPECS/python-flit/classifiers.lst
  SPECS/python-flit/python-flit.signatures.json
  SPECS/python-flit/python-flit.spec
  SPECS/python-pluggy/python-pluggy.signatures.json
  SPECS/python-pluggy/python-pluggy.spec
  SPECS/python-pytest-xdist/python-pytest-xdist.signatures.json
  SPECS/python-pytest-xdist/python-pytest-xdist.spec
  SPECS/python-setuptools_scm/python-setuptools_scm.signatures.json
  SPECS/python-setuptools_scm/python-setuptools_scm.spec
  SPECS/python-tomli/python-tomli.signatures.json
  SPECS/python-tomli/python-tomli.spec
  cgmanifest.json
  toolkit/scripts/check_entangled_specs.py
Labels: main

#2614 Use golang >= 1.17.1 with terraform
  SPECS/terraform/terraform.spec
Labels: Packaging, main

#2612 Upgrade python-tqdm to version 4.63.1
  SPECS/python-tqdm/python-tqdm.signatures.json
  SPECS/python-tqdm/python-tqdm.spec
  cgmanifest.json
Labels: main

#2611 Upgrade python-twisted to 22.2.0
  SPECS/python-twisted/disable_multicast_test.patch
  SPECS/python-twisted/extra_dependency.patch
  SPECS/python-twisted/no_packet.patch
  SPECS/python-twisted/python-twisted.signatures.json
  SPECS/python-twisted/python-twisted.spec
  cgmanifest.json
Labels: main

#2613 perl-generators: add an explicit BR on `perl(ExtUtils::MakeMaker)` to enable ptest
  SPECS/perl-generators/perl-generators.spec
Labels: Packaging, main

#2587 selinux-policy: Additional policy fixes for enforcing core images.
  SPECS/selinux-policy/0004-Set-default-login-to-unconfined_u.patch
  SPECS/selinux-policy/0010-domain-Allow-lockdown-for-all-domains.patch
  SPECS/selinux-policy/0011-systemd-Drop-systemd_detect_virt_t.patch
  SPECS/selinux-policy/0012-fstools-Handle-resizes-of-the-root-filesystem.patch
  SPECS/selinux-policy/0013-mount-Get-the-attributes-of-all-filesystems.patch
  SPECS/selinux-policy/0014-systemd-Misc-updates.patch
  SPECS/selinux-policy/0015-rpm-Add-dnf-and-tdnf-labeling.patch
  SPECS/selinux-policy/0016-logging-Change-to-systemd-interface-for-tmpfilesd.patch
  SPECS/selinux-policy/0017-Add-cloud-init.patch
  SPECS/selinux-policy/selinux-policy.spec
Labels: Packaging, main

#2549 [main] update wayland to 1.20.0 and wayland-protocols to 1.25
  SPECS/wayland-protocols/wayland-protocols.signatures.json
  SPECS/wayland-protocols/wayland-protocols.spec
  SPECS/wayland/0001-Idle-loop-thread-safe-fix.patch
  SPECS/wayland/wayland.signatures.json
  SPECS/wayland/wayland.spec
  cgmanifest.json
Labels: main

#2616 [1.0-dev] [backport] Adding libselinux BR to find/coreutils for SELinux support
  SPECS/coreutils/coreutils.spec
  SPECS/findutils/findutils.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#2623 python-execnet: Upgrade to 1.9.0
  SPECS/python-execnet/python-execnet.signatures.json
  SPECS/python-execnet/python-execnet.spec
  cgmanifest.json
Labels: main

#2622 python-remoto: Upgrade to 1.2.1
  SPECS/python-remoto/python-remoto.signatures.json
  SPECS/python-remoto/python-remoto.spec
  cgmanifest.json
Labels: main

#2621 python-simplejson: Upgrade to 3.17.6
  SPECS/python-simplejson/python-simplejson.signatures.json
  SPECS/python-simplejson/python-simplejson.spec
  cgmanifest.json
Labels: main

#2626 Bump Mariner 1.0 Release version for 3rd March Update
  SPECS/mariner-release/mariner-release.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#2604 Remove python2 support from Mariner
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/mariner-rpm-macros/macros.pybytecompile
  SPECS/mariner-rpm-macros/macros.python-srpm
  SPECS/mariner-rpm-macros/macros.python2
  SPECS/mariner-rpm-macros/mariner-rpm-macros.signatures.json
  SPECS/mariner-rpm-macros/mariner-rpm-macros.spec
  SPECS/mercurial/mercurial.spec
  SPECS/python-pip/python-pip.signatures.json
  SPECS/python-pip/python-pip.spec
  SPECS/python-setuptools/python-setuptools.signatures.json
  SPECS/python-setuptools/python-setuptools.spec
  SPECS/python-six/python-six.spec
  SPECS/python2/CVE-2007-4559.nopatch
  SPECS/python2/CVE-2013-1753.nopatch
  SPECS/python2/CVE-2015-5652.nopatch
  SPECS/python2/CVE-2017-17522.nopatch
  SPECS/python2/CVE-2017-18207.patch
  SPECS/python2/CVE-2019-18348.nopatch
  SPECS/python2/CVE-2019-20907.patch
  SPECS/python2/CVE-2019-9674.nopatch
  SPECS/python2/CVE-2020-26116.patch
  SPECS/python2/CVE-2020-27619.patch
  SPECS/python2/CVE-2021-23336.patch
  SPECS/python2/Replace-unsupported-TLS-methods.patch
  SPECS/python2/added-pyopenssl-ipaddress-certificate-validation.patch
  SPECS/python2/cgi.patch
  SPECS/python2/python2-support-mariner-platform.patch
  SPECS/python2/python2.signatures.json
  SPECS/python2/python2.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#2615 [main] Adjusting `ruby` provides across subpackages.
  SPECS/ruby/ruby.spec
Labels: Packaging, main

#2629 python-atomicwrites: Upgrade to 1.4.0
  SPECS/python-atomicwrites/python-atomicwrites.signatures.json
  SPECS/python-atomicwrites/python-atomicwrites.spec
  cgmanifest.json
Labels: main

#2624 kernel: Address CVE-2022-1016
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/hyperv-daemons/CVE-2022-1016.patch
  SPECS/hyperv-daemons/hyperv-daemons.spec
  SPECS/kernel-headers/CVE-2022-1016.patch
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel-hyperv/CVE-2022-1016.patch
  SPECS/kernel-hyperv/kernel-hyperv.spec
  SPECS/kernel/CVE-2022-1016.patch
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#2631 Bump mariner 2.0 Release number for preview F Image
  SPECS/mariner-release/mariner-release.spec
  toolkit/Makefile
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#2630 [main] Migrating specs to enable `libguestfs` build from `SPECS`, part 1.
  SPECS/dietlibc/dietlibc-insecure-defpath.patch
  SPECS/dietlibc/dietlibc.signatures.json
  SPECS/dietlibc/dietlibc.spec
  SPECS/dnf-plugins-core/dnf-plugins-core.signatures.json
  SPECS/dnf-plugins-core/dnf-plugins-core.spec
  SPECS/grubby/0001-remove-the-old-crufty-u-boot-support.patch
  SPECS/grubby/0002-Change-return-type-in-getRootSpecifier.patch
  SPECS/grubby/0003-Add-btrfs-subvolume-support-for-grub2.patch
  SPECS/grubby/0004-Add-tests-for-btrfs-support.patch
  SPECS/grubby/0005-Use-system-LDFLAGS.patch
  SPECS/grubby/0006-Honor-sbindir.patch
  SPECS/grubby/0007-Make-installkernel-to-use-kernel-install-scripts-on-.patch
  SPECS/grubby/0008-Add-usr-libexec-rpm-sort.patch
  SPECS/grubby/0009-Improve-man-page-for-info-option.patch
  SPECS/grubby/0010-Fix-GCC-warnings-about-possible-string-truncations-a.patch
  SPECS/grubby/0011-Fix-stringop-overflow-warning.patch
  SPECS/grubby/0012-Fix-maybe-uninitialized-warning.patch
  SPECS/grubby/0013-Fix-build-RPM-416.patch
  SPECS/grubby/95-kernel-hooks.install
  SPECS/grubby/grubby-bls
  SPECS/grubby/grubby.in
  SPECS/grubby/grubby.signatures.json
  SPECS/grubby/grubby.spec
  SPECS/grubby/installkernel-bls
  SPECS/grubby/installkernel.in
  SPECS/hivex/0001-Win-Hivex-Regedit-Accept-CRLF-line-endings.patch
  SPECS/hivex/0002-Win-Hivex-Regedit-Ignore-comments.patch
  SPECS/hivex/hivex.signatures.json
  SPECS/hivex/hivex.spec
  SPECS/ocaml-findlib/bytes-lib-detection.patch
  SPECS/ocaml-findlib/ocaml-findlib.signatures.json
  SPECS/ocaml-findlib/ocaml-findlib.spec
  SPECS/ocaml-ocamlbuild/ocaml-ocamlbuild.signatures.json
  SPECS/ocaml-ocamlbuild/ocaml-ocamlbuild.spec
  SPECS/perl-Devel-Symdump/perl-Devel-Symdump.signatures.json
  SPECS/perl-Devel-Symdump/perl-Devel-Symdump.spec
  SPECS/perl-IO-stringy/perl-IO-stringy.signatures.json
  SPECS/perl-IO-stringy/perl-IO-stringy.spec
  SPECS/perl-Pod-Coverage/LICENSE.PTR
  SPECS/perl-Pod-Coverage/Pod-Coverage-0.23-Do-not-search-.-lib-by-pod_cover.patch
  SPECS/perl-Pod-Coverage/perl-Pod-Coverage.signatures.json
  SPECS/perl-Pod-Coverage/perl-Pod-Coverage.spec
  SPECS/perl-Test-Pod-Coverage/LICENSE.PTR
  SPECS/perl-Test-Pod-Coverage/perl-Test-Pod-Coverage.signatures.json
  SPECS/perl-Test-Pod-Coverage/perl-Test-Pod-Coverage.spec
  SPECS/perl-Test-Pod/perl-Test-Pod.signatures.json
  SPECS/perl-Test-Pod/perl-Test-Pod.spec
  SPECS/python-nose2/python-nose2.signatures.json
  SPECS/python-nose2/python-nose2.spec
  SPECS/rubygem-rake/rubygem-rake.signatures.json
  SPECS/rubygem-rake/rubygem-rake.spec
  SPECS/supermin/supermin-find-requires
  SPECS/supermin/supermin-mariner.patch
  SPECS/supermin/supermin.attr
  SPECS/supermin/supermin.signatures.json
  SPECS/supermin/supermin.spec
Labels: Packaging, main

#2628 Sanitize toolchain manifests and add verification check
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/resources/manifests/package/update_manifests.sh
  toolkit/scripts/toolchain.mk
Labels: main

#2635 python-responses: Upgrade to 0.20.0
  SPECS/python-responses/python-responses.signatures.json
  SPECS/python-responses/python-responses.spec
  cgmanifest.json
Labels: main

#2641 [main] Adding `--assumeyes` for TDNF calls.
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
Labels: Tools, main

#2620 Update Mariner SPEC files with latest SymCrypt and SCOSSL source
  SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.signatures.json
  SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.spec
  SPECS/SymCrypt/SymCrypt.signatures.json
  SPECS/SymCrypt/SymCrypt.spec
  cgmanifest.json
Labels: main
