Repository microsoft/azurelinux, pull requests merged in 2022-11, with the labels that each got.

#4156 Patch CVE-2022-35737 in sqlite
  SPECS/sqlite/CVE-2022-35737.patch
  SPECS/sqlite/sqlite.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#4155 Upgrade golang to 1.18.8 to fix CVE-2022-2879, CVE-2022-2880, CVE-2022-41715, CVE-2022-27664, CVE-2022-32190
  SPECS/audit/audit.spec
  SPECS/blobfuse/blobfuse.spec
  SPECS/cni/cni.spec
  SPECS/coredns/coredns-1.8.0.spec
  SPECS/coredns/coredns-1.8.4.spec
  SPECS/coredns/coredns-1.8.6.spec
  SPECS/cri-tools/cri-tools.spec
  SPECS/etcd/etcd-3.4.13.spec
  SPECS/etcd/etcd-3.5.0.spec
  SPECS/etcd/etcd-3.5.1.spec
  SPECS/flannel/flannel.spec
  SPECS/glide/glide.spec
  SPECS/go-md2man/go-md2man.spec
  SPECS/gobject-introspection/gobject-introspection.spec
  SPECS/golang/golang.signatures.json
  SPECS/golang/golang.spec
  SPECS/helm/helm.spec
  SPECS/libnvidia-container/libnvidia-container.spec
  SPECS/moby-buildx/moby-buildx.spec
  SPECS/moby-cli/moby-cli.spec
  SPECS/moby-containerd/moby-containerd.spec
  SPECS/moby-engine/moby-engine.spec
  SPECS/moby-runc/moby-runc.spec
  SPECS/node-problem-detector/node-problem-detector.spec
  SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec
  SPECS/telegraf/telegraf.spec
  cgmanifest.json
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#4154 Toolkit: Set CGO_ENABLED=0 when building go tools
  toolkit/scripts/tools.mk
Labels: Tools, 1.0-dev

#4159 Toolkit: set CGO_ENABLED=0 (2.0)
  toolkit/scripts/tools.mk
Labels: Tools, main

#4162 Fixed flaky tests in 'python-into-dbus-python'.
  SPECS-EXTENDED/python-into-dbus-python/python-into-dbus-python.spec
Labels: main

#4161 Updating `rust` test deps to include 'glibc-static'.
  SPECS/kubevirt/kubevirt.spec
  SPECS/rust/rust.spec
Labels: Packaging, main

#4167 kernel: Address CVEs 2022-3521, 2022-3542, 2022-3586, 2022-3594, 2022-41850
  SPECS/kernel/CVE-2022-3521.nopatch
  SPECS/kernel/CVE-2022-3542.nopatch
  SPECS/kernel/CVE-2022-3586.nopatch
  SPECS/kernel/CVE-2022-3594.nopatch
  SPECS/kernel/CVE-2022-41850.nopatch
Labels: security, Packaging, 1.0-dev

#4166 Fixed cgmanifest validation's dependency on lua.
  .github/workflows/validate-cg-manifest.sh
Labels: main

#4142 Fix typo in CVE-2018-1000097 patch filename in sharutils to ensure detection by CVE tooling
  SPECS/sharutils/CVE-2018-1000097.patch
  SPECS/sharutils/sharutils.spec
Labels: Packaging, main

#4169 Upgraded blobfuse2 to preview 4
  SPECS/blobfuse2/blobfuse2.signatures.json
  SPECS/blobfuse2/blobfuse2.spec
  cgmanifest.json
Labels: main

#4173 Fixed printing built RPMs from spec.
  toolkit/tools/internal/rpm/rpm.go
  toolkit/tools/internal/rpm/rpm_test.go
  toolkit/tools/internal/rpm/testdata/no_default_package.spec
Labels: Tools, main

#4168 Add perl-Authen-SASL and perl-IO-Socket-SSL as requires to git to enable git send-email
  SPECS/git/git.spec
  SPECS/perl-Authen-SASL/Authen-SASL-RT85294-Fix-WRITE.patch
  SPECS/perl-Authen-SASL/LICENSE.PTR
  SPECS/perl-Authen-SASL/perl-Authen-SASL.signatures.json
  SPECS/perl-Authen-SASL/perl-Authen-SASL.spec
  SPECS/perl-GSSAPI/perl-GSSAPI.signatures.json
  SPECS/perl-GSSAPI/perl-GSSAPI.spec
Labels: Packaging, main

#4114 Add package `imake` v1.0.8
  SPECS-EXTENDED/imake/imake-1.0.2-abort.patch
  SPECS-EXTENDED/imake/imake.signatures.json
  SPECS-EXTENDED/imake/imake.spec
  SPECS-EXTENDED/imake/xorg-cf-files-1.0.2-redhat.patch
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4171 glog: Add package version 0.3.5
  SPECS-EXTENDED/glog/glog.signatures.json
  SPECS-EXTENDED/glog/glog.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#4189 Updated `sudo` to version 1.9.12p1 to fix CVE-2022-43995.
  SPECS/sudo/sudo.signatures.json
  SPECS/sudo/sudo.spec
  cgmanifest.json
Labels: 1.0-dev

#4183 Fixed `cgmanfiest.json` PR check to support Mariner LUA scripts.
  .github/workflows/validate-cg-manifest.sh
Labels: main

#4191 Fix misspelling of targeted
  toolkit/docs/building/building.md
Labels: documentation, main

#4190 Patched `libtiff` to fix CVE-2022s: 3597, 3598, 3599, 3626, and 3627.
  SPECS/libtiff/CVE-2020-35521.nopatch
  SPECS/libtiff/CVE-2022-3597.patch
  SPECS/libtiff/CVE-2022-3598.nopatch
  SPECS/libtiff/CVE-2022-3599.patch
  SPECS/libtiff/CVE-2022-3626.nopatch
  SPECS/libtiff/CVE-2022-3627.nopatch
  SPECS/libtiff/libtiff.spec
Labels: Packaging, 1.0-dev

#4194 Bump Mariner Release version for off-cycle CVE fixes
  SPECS/mariner-release/mariner-release.spec
Labels: Packaging, main

#4195 Bump Mariner Release For Nov 2022 Update
  SPECS/mariner-release/mariner-release.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#4149 Fix python-six test to use explicit version 7.1.3
  SPECS/python-six/python-six.spec
Labels: Packaging, 1.0-dev

#4203 Revert "Add package `imake` v1.0.8 (#4114)"
  SPECS-EXTENDED/imake/imake-1.0.2-abort.patch
  SPECS-EXTENDED/imake/imake.signatures.json
  SPECS-EXTENDED/imake/imake.spec
  SPECS-EXTENDED/imake/xorg-cf-files-1.0.2-redhat.patch
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#4209 NoPatches kernel to fix CVE-2022-3594, CVE-2022-3542
  SPECS/kernel/CVE-2022-3542.nopatch
  SPECS/kernel/CVE-2022-3594.nopatch
Labels: security, Packaging, main

#4208 Add: Python package python3-grpcio
  SPECS/grpc/generate_source_tarball.sh
  SPECS/grpc/grpc.signatures.json
  SPECS/grpc/grpc.spec
  cgmanifest.json
Labels: Packaging, main

#4206 Upgrade screen upgrade to 4.9.0 to fix CVE-2021-26937
  SPECS-EXTENDED/screen/screen-4.8.0-expand-d_xtermosc.patch
  SPECS-EXTENDED/screen/screen-4.9.0-braille.patch
  SPECS-EXTENDED/screen/screen.signatures.json
  SPECS-EXTENDED/screen/screen.spec
  cgmanifest.json
Labels: main

#4061 Add python-gast package to CBL-Mariner
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/python-gast/python-gast.signatures.json
  SPECS/python-gast/python-gast.spec
  cgmanifest.json
Labels: main

#4076 add python package python-typing-extensions
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/python-typing-extensions/python-typing-extensions.signatures.json
  SPECS/python-typing-extensions/python-typing-extensions.spec
  cgmanifest.json
Labels: main

#4090 Add python package opt-einsum
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/python-opt-einsum/python-opt-einsum.signatures.json
  SPECS/python-opt-einsum/python-opt-einsum.spec
  cgmanifest.json
Labels: main

#4212 Reverted "Add: Python package python3-grpcio (#4208)"
  SPECS/grpc/generate_source_tarball.sh
  SPECS/grpc/grpc.signatures.json
  SPECS/grpc/grpc.spec
  cgmanifest.json
Labels: main

#4105 add python package google-pasta
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/python-google-pasta/python-google-pasta.signatures.json
  SPECS/python-google-pasta/python-google-pasta.spec
  cgmanifest.json
Labels: main

#4084 add python-flatbuffers package to Mariner
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/flatbuffers/flatbuffers.signatures.json
  SPECS/flatbuffers/flatbuffers.spec
  cgmanifest.json
Labels: main

#4211 Updated toolkit's package resolution to accept installed packages.
  toolkit/tools/internal/pkggraph/pkggraph.go
  toolkit/tools/internal/rpm/rpm.go
  toolkit/tools/internal/sliceutils/sliceutils.go
  toolkit/tools/internal/sliceutils/sliceutils_test.go
  toolkit/tools/scheduler/schedulerutils/buildworker.go
  toolkit/tools/scheduler/schedulerutils/graphbuildstate.go
Labels: Tools, main

#4163 Move nbdkit and its dependent packages from Extended to Core
  SPECS-EXTENDED/nbdkit/nbdkit.signatures.json
  SPECS/buildah/buildah.signatures.json
  SPECS/buildah/buildah.spec
  SPECS/catatonit/catatonit.signatures.json
  SPECS/catatonit/catatonit.spec
  SPECS/containernetworking-plugins/containernetworking-plugins.signatures.json
  SPECS/containernetworking-plugins/containernetworking-plugins.spec
  SPECS/go-rpm-macros/fixing_ldflags_for_mariner.patch
  SPECS/go-rpm-macros/go-rpm-macros.signatures.json
  SPECS/go-rpm-macros/go-rpm-macros.spec
  SPECS/nbdkit/nbdkit-find-provides
  SPECS/nbdkit/nbdkit.attr
  SPECS/nbdkit/nbdkit.signatures.json
  SPECS/nbdkit/nbdkit.spec
  SPECS/podman/podman.signatures.json
  SPECS/podman/podman.spec
  SPECS/slirp4netns/slirp4netns.signatures.json
  SPECS/slirp4netns/slirp4netns.spec
  cgmanifest.json
Labels: main

#4202 upgrade sudo to version 1.9.12p1
  SPECS/sudo/sudo.signatures.json
  SPECS/sudo/sudo.spec
  cgmanifest.json
Labels: main

#4219 Add python package python-libclang
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/python-libclang/python-libclang.signatures.json
  SPECS/python-libclang/python-libclang.spec
  cgmanifest.json
Labels: main

#4207 Upgraded `python3-twisted` to 22.10.0 to fix CVE-2022-39348.
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/python-twisted/python-twisted.spec
  SPECS/python3-twisted/disable_multicast_test.patch
  SPECS/python3-twisted/python3-twisted.signatures.json
  SPECS/python3-twisted/python3-twisted.spec
  cgmanifest.json
Labels: Packaging, 1.0-dev

#4224 change binary install location in coreutils package
  SPECS/coreutils/coreutils.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#4099 Update cloud-hypervisor to v27.0.60, kernel-mshv to v5.15.72, kata to v3.0.0
  SPECS-EXTENDED/kernel-mshv/0001-mshv-Don-t-use-same-function-signature-as-KVM.patch
  SPECS-EXTENDED/kernel-mshv/kernel-mshv.signatures.json
  SPECS-EXTENDED/kernel-mshv/kernel-mshv.spec
  SPECS/cloud-hypervisor/cloud-hypervisor.signatures.json
  SPECS/cloud-hypervisor/cloud-hypervisor.spec
  SPECS/cloud-hypervisor/config.toml
  SPECS/kata-containers/0001-Merged-PR-9607-Allow-10-seconds-for-VM-creation-star.patch
  SPECS/kata-containers/0005-Merged-PR-9956-shim-avoid-memory-hotplug-timeout.patch
  SPECS/kata-containers/kata-containers.signatures.json
  SPECS/kata-containers/kata-containers.spec
  SPECS/kata-containers/runtime-Re-generate-the-client-code.patch
  SPECS/kata-containers/runtime-Support-for-AMD-SEV-SNP-VMs.patch
  SPECS/kata-containers/runtime-clh-Use-the-new-API-to-boot-with-TDX-firmware-td-shim.patch
  SPECS/kata-containers/versions-Update-Cloud-Hypervisor.patch
  cgmanifest.json
Labels: Packaging, main

#4239 grpc: fix right of generate_source_tarball.sh
  SPECS/grpc/generate_source_tarball.sh
Labels: Packaging, main

#4236 Removed deprecated APIs from Python RPM macros.
  SPECS/mariner-rpm-macros/macros.python
  SPECS/mariner-rpm-macros/macros.python3
  SPECS/mariner-rpm-macros/mariner-rpm-macros.signatures.json
  SPECS/mariner-rpm-macros/mariner-rpm-macros.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3958 mariner-release: add %{dist} macro to persistent macro file.
  SPECS/mariner-rpm-macros/macros.dist
  SPECS/mariner-rpm-macros/mariner-rpm-macros.signatures.json
  SPECS/mariner-rpm-macros/mariner-rpm-macros.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, main

#4220 add python h5py package
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/hdf5/h5comp
  SPECS/hdf5/hdf5-LD_LIBRARY_PATH.patch
  SPECS/hdf5/hdf5-build.patch
  SPECS/hdf5/hdf5-gfortran12.patch
  SPECS/hdf5/hdf5-wrappers.patch
  SPECS/hdf5/hdf5.signatures.json
  SPECS/hdf5/hdf5.spec
  SPECS/hostname/gpl-2.0.txt
  SPECS/hostname/hostname-rh.patch
  SPECS/hostname/hostname.signatures.json
  SPECS/hostname/hostname.spec
  SPECS/hostname/nis-domainname
  SPECS/hostname/nis-domainname.service
  SPECS/libaec/libaec.signatures.json
  SPECS/libaec/libaec.spec
  SPECS/liblzf/liblzf-3.6-autoconf-20140314.patch
  SPECS/liblzf/liblzf.signatures.json
  SPECS/liblzf/liblzf.spec
  SPECS/python-cached_property/0001-Disable-checks-broken-with-freezegun-0.3.11-131.patch
  SPECS/python-cached_property/267.patch
  SPECS/python-cached_property/python-cached_property.signatures.json
  SPECS/python-cached_property/python-cached_property.spec
  SPECS/python-h5py/h5py-3.7.0-ppc-float128.patch
  SPECS/python-h5py/python-h5py.signatures.json
  SPECS/python-h5py/python-h5py.spec
  SPECS/python-pkgconfig/python-pkgconfig.signatures.json
  SPECS/python-pkgconfig/python-pkgconfig.spec
  SPECS/time/time-1.8-Prefer-clock_gettime-CLOCK_MONOTONIC.patch
  SPECS/time/time-1.9-Improve-info-directory-index-entry-description.patch
  SPECS/time/time.signatures.json
  SPECS/time/time.spec
  cgmanifest.json
Labels: main

#4247 add prebuilt-ca-certificates and tzdata to 2.0 distroless minimal container
  SPECS/distroless-packages/distroless-packages.spec
Labels: Packaging, main

#4248 add prebuilt-ca-certificates and tzdata to 1.0 distroless minimal container
  SPECS/distroless-packages/distroless-packages.spec
Labels: Packaging, 1.0-dev

#4217 kernel-hci: Add kernel-hci-drivers-gpu package; Enable modules for TCP Congestion Algorithms
  SPECS/kernel-hci/config
  SPECS/kernel-hci/kernel-hci.signatures.json
  SPECS/kernel-hci/kernel-hci.spec
Labels: Packaging, main

#4251 sysstat: nopatch CVE-2022-39377 (N/A)
  SPECS/sysstat/CVE-2022-39377.nopatch
Labels: security, Packaging, 1.0-dev

#4241 Mitigate CVE-2020-35505 by disabling qemu emulation for am53c974 devi…
  SPECS/qemu-kvm/CVE-2020-35505.patch
  SPECS/qemu-kvm/qemu-kvm.spec
Labels: Packaging, 1.0-dev

#4255 Revert coretuils change
  SPECS/coreutils/coreutils.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#4260 libtiff patch CVE-2022-3970
  SPECS/libtiff/CVE-2022-3970.patch
  SPECS/libtiff/libtiff.spec
Labels: Packaging, 1.0-dev

#4204 Libtiff patch
  SPECS/libtiff/CVE-2022-3597.patch
  SPECS/libtiff/CVE-2022-3598.nopatch
  SPECS/libtiff/CVE-2022-3599.patch
  SPECS/libtiff/CVE-2022-3626.nopatch
  SPECS/libtiff/CVE-2022-3627.nopatch
  SPECS/libtiff/CVE-2022-3970.patch
  SPECS/libtiff/libtiff.spec
Labels: Packaging, main

#4261 Fixed `python-twisted` binaries conflicts.
  SPECS/python3-twisted/python3-twisted.spec
Labels: Packaging, 1.0-dev

#4264 Patch buildah for CVE-2022-27651
  SPECS/buildah/CVE-2022-27651.patch
  SPECS/buildah/buildah.spec
Labels: Packaging, main

#4256 Patched `systemd` to fix CVE-2022-3821
  SPECS/systemd/CVE-2022-3821.patch
  SPECS/systemd/systemd-bootstrap.spec
  SPECS/systemd/systemd.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, main

#4266 Bump Mariner Release version for off-cycle CVE fixes
  SPECS/mariner-release/mariner-release.spec
Labels: Packaging, main

#4273 Enable modules for TCP Congestion Algorithms; Add kernel-hci-drivers-…
  SPECS/kernel-hci/config
  SPECS/kernel-hci/kernel-hci.spec
Labels: Packaging

#4274 Updated toolkit's package resolution to accept installed packages. (#4211)
  toolkit/tools/internal/pkggraph/pkggraph.go
  toolkit/tools/internal/rpm/rpm.go
  toolkit/tools/internal/sliceutils/sliceutils.go
  toolkit/tools/internal/sliceutils/sliceutils_test.go
  toolkit/tools/scheduler/schedulerutils/buildworker.go
  toolkit/tools/scheduler/schedulerutils/graphbuildstate.go
Labels: Tools

#4276 systemd: patch CVE-2022-3821
  SPECS/systemd/CVE-2022-3821.patch
  SPECS/systemd/systemd.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#4267 Removed explicit `initrd` target from the toolkit.
  toolkit/scripts/imggen.mk
Labels: Tools, main

#4285 Patched CVE-2019-17362 in `libtomcrypt`.
  SPECS-EXTENDED/libtomcrypt/CVE-2019-17362.patch
  SPECS-EXTENDED/libtomcrypt/libtomcrypt.spec
Labels: main

#4288 Upgraded `sysstat` to version 12.7.1 to fix CVE-2022-39377.
  SPECS/sysstat/sysstat.signatures.json
  SPECS/sysstat/sysstat.spec
  cgmanifest.json
Labels: main

#4292 toolchain: Build coreutils and findutils after libselinux.
  SPECS/coreutils/coreutils.spec
  SPECS/findutils/findutils.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
Labels: main

#4281 Updated `openslp` to fix CVE-2016-7567, CVE-2017-17833, and CVE-2019-5544.
  SPECS-EXTENDED/openslp/CVE-2016-7567.patch
  SPECS-EXTENDED/openslp/CVE-2017-17833.patch
  SPECS-EXTENDED/openslp/CVE-2019-5544.patch
  SPECS-EXTENDED/openslp/openslp.spec
Labels: main

#4284 Split out 'doc' subpackage from Rust.
  SPECS/rust/rust.spec
Labels: Packaging, main

#4303 Patch `mutt` CVE-2021-32055
  SPECS-EXTENDED/mutt/CVE-2021-32055.patch
  SPECS-EXTENDED/mutt/mutt.spec
Labels: security, main, specs-extended

#4294 cglib: Fix package install failure due to missing runtime dependency
  SPECS-EXTENDED/cglib/cglib.spec
Labels: main

#4293 adcli: Add package version 0.9.2
  SPECS-EXTENDED/adcli/adcli.signatures.json
  SPECS-EXTENDED/adcli/adcli.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#4291 ORBit2: Add package version 2.14.19
  SPECS-EXTENDED/ORBit2/ORBit2-2.14.3-multilib.patch
  SPECS-EXTENDED/ORBit2/ORBit2-2.14.3-ref-leaks.patch
  SPECS-EXTENDED/ORBit2/ORBit2-allow-deprecated.patch
  SPECS-EXTENDED/ORBit2/ORBit2-make-j-safety.patch
  SPECS-EXTENDED/ORBit2/ORBit2.signatures.json
  SPECS-EXTENDED/ORBit2/ORBit2.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#4318 Update gRPC python package to make it exclusive to AMD64
  SPECS/grpc/grpc.spec
Labels: Packaging, main

#4332 Livepatched CVE-2022-3543 in kernel 5.15.77.1-1.cm2.
  SPECS-SIGNED/livepatch-5.15.77.1-1.cm2-signed/livepatch-5.15.77.1-1.cm2-signed.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/kpatch/kpatch.signatures.json
  SPECS/kpatch/kpatch.spec
  SPECS/kpatch/mariner_update.patch
  SPECS/livepatch-5.15.77.1-1.cm2/CVE-2022-3543.patch
  SPECS/livepatch-5.15.77.1-1.cm2/livepatch-5.15.77.1-1.cm2.spec
  cgmanifest.json
Labels: main

#4287 Upgraded `libntlm` to version 1.6 to fix CVE-2019-17455.
  .github/workflows/check-package-cgmanifest.yml
  SPECS-EXTENDED/libntlm/libntlm.signatures.json
  SPECS-EXTENDED/libntlm/libntlm.spec
  cgmanifest.json
Labels: main
