Repository microsoft/azurelinux, pull requests merged in 2022-08, with the labels that each got.

#3368 Fix test failure in OpenSSL
  SPECS/openssl/openssl-1.1.1-load-default-engines.patch
  SPECS/openssl/openssl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, main

#3466 Remove Cassandra Reaper Spec in Mariner
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/reaper/Readme
  SPECS/reaper/reaper.signatures.json
  SPECS/reaper/reaper.spec
  SPECS/reaper/reaper_build_caches.sh
  cgmanifest.json
Labels: main

#3467 Migrate nfs4-acl-tools, authd, iptraf, freeipmi, lldpd, ksh and postfix from SPECS-EXTENDED to SPECS
  SPECS/authd/auth.socket
  SPECS/authd/auth@.service
  SPECS/authd/authd.signatures.json
  SPECS/authd/authd.spec
  SPECS/freeipmi/bmc-watchdog.service
  SPECS/freeipmi/freeipmi.signatures.json
  SPECS/freeipmi/freeipmi.spec
  SPECS/freeipmi/ipmidetectd.service
  SPECS/freeipmi/ipmiseld.service
  SPECS/iptraf-ng/iptraf-ng-logrotate.conf
  SPECS/iptraf-ng/iptraf-ng-tmpfiles.conf
  SPECS/iptraf-ng/iptraf-ng.signatures.json
  SPECS/iptraf-ng/iptraf-ng.spec
  SPECS/ksh/dotkshrc
  SPECS/ksh/ksh-1.0.0-beta.1-fix-build.patch
  SPECS/ksh/ksh-1.0.0-beta.1-regre-tests.patch
  SPECS/ksh/ksh.signatures.json
  SPECS/ksh/ksh.spec
  SPECS/ksh/kshcomp.conf
  SPECS/ksh/kshrc.rhs
  SPECS/lldpd/lldpd-el6.init
  SPECS/lldpd/lldpd-el7.service
  SPECS/lldpd/lldpd-fedora.service
  SPECS/lldpd/lldpd-fedora.sysconfig
  SPECS/lldpd/lldpd-tmpfiles
  SPECS/lldpd/lldpd.signatures.json
  SPECS/lldpd/lldpd.spec
  SPECS/nfs4-acl-tools/nfs4-acl-tools.signatures.json
  SPECS/nfs4-acl-tools/nfs4-acl-tools.spec
  SPECS/postfix/README-Postfix-SASL-RedHat.txt
  SPECS/postfix/pflogsumm-1.1.5-datecalc.patch
  SPECS/postfix/pflogsumm-1.1.5-ipv6-warnings-fix.patch
  SPECS/postfix/pflogsumm-1.1.5-syslog-name-underscore-fix.patch
  SPECS/postfix/postfix-3.3.3-alternatives.patch
  SPECS/postfix/postfix-3.4.0-files.patch
  SPECS/postfix/postfix-3.4.0-large-fs.patch
  SPECS/postfix/postfix-3.4.4-chroot-example-fix.patch
  SPECS/postfix/postfix-3.5.0-config.patch
  SPECS/postfix/postfix-3.6.2-glibc-234-build-fix.patch
  SPECS/postfix/postfix-3.6.2-whitespace-name-fix.patch
  SPECS/postfix/postfix-chroot-update
  SPECS/postfix/postfix-etc-init.d-postfix
  SPECS/postfix/postfix-pam.conf
  SPECS/postfix/postfix-sasl.conf
  SPECS/postfix/postfix.aliasesdb
  SPECS/postfix/postfix.service
  SPECS/postfix/postfix.signatures.json
  SPECS/postfix/postfix.spec
Labels: Packaging, main

#3469 Add nopatches for ldns CVES CVE-2017-1000231, CVE-2017-1000232
  SPECS/ldns/CVE-2017-1000231.nopatch
  SPECS/ldns/CVE-2017-1000232.nopatch
Labels: security, Packaging, main

#3478 Upgrade fluent-bit version to latest 1.9.6
  SPECS/fluent-bit/fluent-bit.signatures.json
  SPECS/fluent-bit/fluent-bit.spec
  cgmanifest.json
Labels: main

#3465 kernel: turn on CONFIG_BLK_DEV_ZONED
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, main

#3482 Add nopatch for python-mistune cve CVE-2022-34749
  SPECS/python-mistune/CVE-2022-34749.nopatch
Labels: security, Packaging, 1.0-dev

#3484 kernel: turn on landlock
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3490 Upgrade cassandra version to 4.0.5
  SPECS-EXTENDED/cassandra/Readme
  SPECS-EXTENDED/cassandra/cassandra.signatures.json
  SPECS-EXTENDED/cassandra/cassandra.spec
  cgmanifest.json
Labels: main

#3489 Updating `mariner-release` for the August release.
  SPECS/mariner-release/mariner-release.spec
Labels: Packaging, main

#3491 Update mariner-release for August 1.0 release
  SPECS/mariner-release/mariner-release.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, 1.0-dev

#3408 Promote bluez, libicall, and libell to base repo
  SPECS/bluez/0001-build-Always-define-confdir-and-statedir.patch
  SPECS/bluez/0001-hog-Fix-read-order-of-attributes-rediffed.patch
  SPECS/bluez/0001-obex-Use-GLib-helper-function-to-manipulate-paths.patch
  SPECS/bluez/0002-Use-g_memdup2-everywhere.patch
  SPECS/bluez/0002-hog-Add-input-queue-while-uhid-device-has-not-been-c-rediffed.patch
  SPECS/bluez/0002-systemd-Add-PrivateTmp-and-NoNewPrivileges-options.patch
  SPECS/bluez/0003-systemd-Add-more-filesystem-lockdown.patch
  SPECS/bluez/0004-systemd-More-lockdown.patch
  SPECS/bluez/bluez.gitignore
  SPECS/bluez/bluez.signatures.json
  SPECS/bluez/bluez.spec
  SPECS/libell/libell.signatures.json
  SPECS/libell/libell.spec
  SPECS/libical/libical.signatures.json
  SPECS/libical/libical.spec
Labels: Packaging, main

#3476 Update nodejs to v16.16.0 to address cves: CVEs CVE-2022-32213 CVE-2022-32214 CVE-2022-32215
  SPECS/nodejs/clean-source-tarball.sh
  SPECS/nodejs/nodejs.signatures.json
  SPECS/nodejs/nodejs.spec
  cgmanifest.json
Labels: main

#3477 Add nopatch for python-mistune cve CVE-2022-34749
  SPECS/python-mistune/CVE-2022-34749.nopatch
Labels: security, Packaging, main

#3473 perl-Test-Deep: promote to SPECS to fix ptest for `perl-CPAN-Meta-Check`
  SPECS/perl-CPAN-Meta-Check/perl-CPAN-Meta-Check.spec
  SPECS/perl-Test-Deep/LICENSE.PTR
  SPECS/perl-Test-Deep/perl-Test-Deep.signatures.json
  SPECS/perl-Test-Deep/perl-Test-Deep.spec
Labels: Packaging, ptest, main

#3458 perl-File-HomeDir: add BR on `perl-{(ExtUtils::MakeMaker),(Test::More)}` to enable ptest
  SPECS/perl-File-HomeDir/perl-File-HomeDir.spec
Labels: Packaging, ptest, main

#3459 perl-JSON-Any: add BR on `perl(ExtUtils::MakeMaker)` & `cpan` to enable ptest
  SPECS/perl-JSON-Any/perl-JSON-Any.spec
Labels: Packaging, ptest, main

#3472 perl-DBD-SQLite: add BR on `perl(Test::More)` & `perl(Digest::MD5)` to fix ptest
  SPECS/perl-DBD-SQLite/perl-DBD-SQLite.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, ptest, main

#3471 perl-Path-Class: add BR on `perl-{(Test),(Test::More),(Perl::OSType)}` to enable ptest
  SPECS/perl-Path-Class/perl-Path-Class.spec
Labels: Packaging, ptest, main

#3464 perl-libintl: add BR on `perl-{(ExtUtils::MakeMaker),(Test)}` to enable ptest
  SPECS/perl-libintl-perl/perl-libintl-perl.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, ptest, main

#3462 perl-generators: add BR on `perl(Fedora::VSP)` to fix ptest build
  SPECS/perl-generators/perl-generators.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, ptest, main

#3452 perl-Pod-POM: add BR on `perl(FindBin)` to enable ptest
  SPECS-EXTENDED/perl-Pod-POM/perl-Pod-POM.spec
Labels: ptest, main, specs-extended

#3501 Building reaper only for x86_64 architecture
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/reaper/Readme
  SPECS/reaper/reaper.signatures.json
  SPECS/reaper/reaper.spec
  SPECS/reaper/reaper_build_caches.sh
  cgmanifest.json
Labels: main

#3502 Enable CONFIG_VFIO_NOIOMMU in RT Kernel
  SPECS/kernel-rt/config
  SPECS/kernel-rt/kernel-rt.spec
Labels: Packaging, main

#3485 update cloud-init service to add sysinit.target dependency
  SPECS/cloud-init/add-mariner-distro-support.patch
  SPECS/cloud-init/cloud-init.spec
Labels: Packaging, main

#3503 Kernel CVE - nopatch kernel CVES 2022-2380, 2022-33743, 2021-4135, 2022-33744
  SPECS/kernel/CVE-2021-4135.nopatch
  SPECS/kernel/CVE-2022-2380.nopatch
  SPECS/kernel/CVE-2022-33743.nopatch
  SPECS/kernel/CVE-2022-33744.nopatch
Labels: security, Packaging, main

#3504 Update kernel-rt config
  SPECS/kernel-rt/config
  SPECS/kernel-rt/kernel-rt.spec
  SPECS/kernel-rt/realtime-with-memcg.patch
Labels: Packaging, main

#3499 perl-DBI: add BR on `perl(blib)` & `perl(Test::More)` to fix ptest
  SPECS/perl-DBI/perl-DBI.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, ptest, main

#3500 perl-YAML-Tiny: add BR on `perl(JSON::PP)` & `perl(Test::More)` to fix ptest
  SPECS/perl-YAML-Tiny/perl-YAML-Tiny.spec
Labels: Packaging, ptest, main

#3506 perl-Exporter-Tiny: add BR on `perl(Test::More)` to fix ptest
  SPECS/perl-Exporter-Tiny/perl-Exporter-Tiny.spec
Labels: Packaging, ptest, main

#3505 Enable CONFIG_PCI_PF_STUB in Mariner RT kernel.
  SPECS/kernel-rt/config
  SPECS/kernel-rt/kernel-rt.spec
Labels: Packaging, main

#3507 perl-IO-Socket-SSL: add BR on `perl(ExtUtils::MakeMaker)` & check deps to enable ptest
  SPECS/perl-IO-Socket-SSL/perl-IO-Socket-SSL.spec
Labels: Packaging, ptest, main

#3498 tools: safechroot: TestInitializeShouldCreateChroot: fix if condition
  toolkit/tools/internal/safechroot/safechroot_test.go
Labels: Tools, main

#3508 perl-Test-Warnings: add BR on `perl(Test::More)` to enable ptest
  SPECS/perl-Test-Warnings/perl-Test-Warnings.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: ptest, main

#3497 Update ceph to v16.2.10 to address CVE-2022-0670
  SPECS/ceph/ceph-snappy-fix
  SPECS/ceph/ceph.signatures.json
  SPECS/ceph/ceph.spec
  cgmanifest.json
Labels: security, main

#3511 python-pexpect: disable flaky `spawn_uses_env` test.
  SPECS/python-pexpect/python-pexpect.spec
Labels: Packaging, ptest, main

#3518 perl-Object-Accessor: add BR on `perl(ExtUtils::MakeMaker)` & check deps to enable ptest
  SPECS/perl-Object-Accessor/perl-Object-Accessor.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, ptest, main

#3513 Update gnupg2 to 2.3.7 to resolve CVE-2022-34903
  SPECS/gnupg2/gnupg2.signatures.json
  SPECS/gnupg2/gnupg2.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, main

#3512 Update gnutls to 3.7.7 to resolve CVE-2022-2509
  SPECS/gnutls/gnutls.signatures.json
  SPECS/gnutls/gnutls.spec
  cgmanifest.json
Labels: security, main

#3516 busybox: patch CVE-2022-30065
  SPECS/busybox/CVE-2022-30065.patch
  SPECS/busybox/ash-fix-use-after-free-in-bash-pattern-substitution.patch
  SPECS/busybox/ash-fix-use-after-free-in-pattern-substituon-code.patch
  SPECS/busybox/awk-input-numbers-are-never-octal-or-hex-only-progra.patch
  SPECS/busybox/busybox.spec
Labels: security, Packaging, main

#3517 freetype: bump version to 2.12.1 to address CVE-2022-{27405,27406}
  SPECS/freetype/CVE-2022-27404.patch
  SPECS/freetype/freetype.signatures.json
  SPECS/freetype/freetype.spec
  cgmanifest.json
Labels: security, main

#3521 e2fsprogs: patch CVE-2022-1304
  SPECS/e2fsprogs/CVE-2019-5188.patch
  SPECS/e2fsprogs/CVE-2022-1304.patch
  SPECS/e2fsprogs/e2fsprogs.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, main

#3514 curl: update to version 7.84.0 to fix CVE-2022-32207.
  SPECS/curl/CVE-2021-22897.patch
  SPECS/curl/CVE-2021-22898.patch
  SPECS/curl/CVE-2021-22901.patch
  SPECS/curl/CVE-2021-22922.nopatch
  SPECS/curl/CVE-2021-22923.nopatch
  SPECS/curl/CVE-2021-22924.patch
  SPECS/curl/CVE-2021-22925.patch
  SPECS/curl/CVE-2021-22926.nopatch
  SPECS/curl/CVE-2021-22945.patch
  SPECS/curl/CVE-2021-22946.patch
  SPECS/curl/CVE-2021-22947.patch
  SPECS/curl/CVE-2022-22576.patch
  SPECS/curl/CVE-2022-27774.patch
  SPECS/curl/CVE-2022-27775.patch
  SPECS/curl/CVE-2022-27776-supplemental.patch
  SPECS/curl/CVE-2022-27776.patch
  SPECS/curl/curl.signatures.json
  SPECS/curl/curl.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, 1.0-dev

#3515 vim: update version to 9.0.0181 to fix CVEs 2022-2522, 2022-2571, 2022-2580, 2022-2581.
  SPECS/vim/vim.signatures.json
  SPECS/vim/vim.spec
  cgmanifest.json
Labels: security, 1.0-dev

#3524 freetype: update to version 2.12.1 to fix CVEs 2022-27405 and 2022-27406
  SPECS/freetype/CVE-2022-27404.patch
  SPECS/freetype/freetype.signatures.json
  SPECS/freetype/freetype.spec
  cgmanifest.json
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#3496 Add containerized-data-importer to mariner
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/containerized-data-importer/containerized-data-importer.signatures.json
  SPECS/containerized-data-importer/containerized-data-importer.spec
  cgmanifest.json
Labels: main

#3530 toolchain: update steps to build with latest `libarchive`.
  toolkit/scripts/toolchain/container/toolchain-remote-wget-list
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
Labels: Tools, main

#3529 libarchive: update to version 3.6.1 to fix CVE-2021-36976.
  SPECS/libarchive/libarchive.signatures.json
  SPECS/libarchive/libarchive.spec
  cgmanifest.json
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/toolchain-remote-wget-list
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
Labels: security, 1.0-dev

#3526 perl-DBIx-Simple: add BR on `perl(Test::More)` to fix ptest
  SPECS/perl-DBIx-Simple/perl-DBIx-Simple.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: ptest, main

#3525 perl-JSON-XS: add BR on `perl(ExtUtils::MakeMaker)` & `perl(Test::*)` to enable ptest
  SPECS/perl-JSON-XS/perl-JSON-XS.spec
Labels: Packaging, ptest, main

#3527 xterm: bump version to 372 to address CVE-2021-27135
  SPECS-EXTENDED/xterm/xterm-defaults.patch
  SPECS-EXTENDED/xterm/xterm-desktop.patch
  SPECS-EXTENDED/xterm/xterm-man-paths.patch
  SPECS-EXTENDED/xterm/xterm.signatures.json
  SPECS-EXTENDED/xterm/xterm.spec
  cgmanifest.json
Labels: security, main, specs-extended

#3533 Fix signature file for kernel-rt
  SPECS/kernel-rt/kernel-rt.signatures.json
Labels: Packaging, main

#3430 Move nss_wrapper to SPECS folder as build dependency for libssh
  SPECS-EXTENDED/nss_wrapper/nss_wrapper-1.1.11.tar.gz.asc
  SPECS-EXTENDED/nss_wrapper/nss_wrapper.signatures.json
  SPECS/nss_wrapper/nss_wrapper.signatures.json
  SPECS/nss_wrapper/nss_wrapper.spec
  cgmanifest.json
Labels: main

#3429 Move pam_wrapper to SPECS folder as build dependency for libssh
  SPECS-EXTENDED/pam_wrapper/pam_wrapper-1.1.3.tar.gz.asc
  SPECS-EXTENDED/pam_wrapper/pam_wrapper.signatures.json
  SPECS/pam_wrapper/pam_wrapper.signatures.json
  SPECS/pam_wrapper/pam_wrapper.spec
  cgmanifest.json
Labels: main

#3428 Move socket_wrapper to SPECS folder as build dependency for libssh
  SPECS-EXTENDED/socket_wrapper/socket_wrapper-1.2.4.tar.gz.asc
  SPECS-EXTENDED/socket_wrapper/socket_wrapper.signatures.json
  SPECS/socket_wrapper/socket_wrapper.signatures.json
  SPECS/socket_wrapper/socket_wrapper.spec
  cgmanifest.json
Labels: main

#3427 Move uid_wrapper to SPECS folder as build dependency for libssh
  SPECS-EXTENDED/uid_wrapper/0001-pkg-config-Fix-installation-path.patch
  SPECS-EXTENDED/uid_wrapper/uid_wrapper-1.2.7-cmake-config-fix-installation-path.patch
  SPECS-EXTENDED/uid_wrapper/uid_wrapper-1.2.7.tar.gz.asc
  SPECS-EXTENDED/uid_wrapper/uid_wrapper.signatures.json
  SPECS/uid_wrapper/uid_wrapper.signatures.json
  SPECS/uid_wrapper/uid_wrapper.spec
  cgmanifest.json
Labels: main

#3537 zlib: patch CVE-2022-37434
  SPECS/zlib/CVE-2022-37434.patch
  SPECS/zlib/Fix-extra-field-processing-bug-that-dereferences-NULL.patch
  SPECS/zlib/zlib.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, main

#3544 unbound: bump version to 1.16.2 to address CVE-2022-30698
  SPECS/unbound/unbound.signatures.json
  SPECS/unbound/unbound.spec
  cgmanifest.json
Labels: security, main

#3541 m2crypto: patch CVE-2020-25657
  SPECS/m2crypto/CVE-2020-25657.patch
  SPECS/m2crypto/m2crypto.spec
Labels: security, Packaging, main

#3540 libtiff: patch CVE-2022-34526
  SPECS/libtiff/CVE-2022-34526.patch
  SPECS/libtiff/libtiff.spec
Labels: security, Packaging, main

#3539 sqlite: bump version to 3.39.2 to address CVE-2022-35737
  SPECS/sqlite/CVE-2021-36690.patch
  SPECS/sqlite/sqlite.signatures.json
  SPECS/sqlite/sqlite.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, main

#3538 rsync: bump version to 3.2.5 to address CVE-2022-29154
  SPECS/rsync/CVE-2020-14387.patch
  SPECS/rsync/rsync.signatures.json
  SPECS/rsync/rsync.spec
  cgmanifest.json
Labels: security, main

#3532 openssl: align with 2.0 state.
  SPECS/openssl/openssl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3548 Patch CVE-2022-37434 in zlib
  SPECS/zlib/CVE-2022-37434.patch
  SPECS/zlib/zlib.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#3551 Bump exempi release to rebuild with zlib's CVE-2022-37434 fix
  SPECS-EXTENDED/exempi/exempi.spec
Labels: main

#3536 lldpd: bump version to 1.0.14 to address CVE-2020-27827
  SPECS/lldpd/lldpd.signatures.json
  SPECS/lldpd/lldpd.spec
  cgmanifest.json
Labels: security, main

#3553 [2.0] Bump mariner-release for August update 2
  SPECS/mariner-release/mariner-release.spec
Labels: Packaging, main

#3552 mariner-release: bump `Release` tag for August Update 2.
  SPECS/mariner-release/mariner-release.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#3556 kernel: nopatch CVE-2022-1012.
  SPECS/kernel/CVE-2022-1012.nopatch
Labels: security, Packaging, main

#3555 kernel: nopatch CVE-2022-1012.
  SPECS/kernel/CVE-2022-1012.nopatch
Labels: security, Packaging, 1.0-dev

#3567 kernel: Address CVE-2021-4135 CVE-2022-2380 CVE-2022-1158
  SPECS/kernel/CVE-2021-4135.nopatch
  SPECS/kernel/CVE-2022-1158.nopatch
  SPECS/kernel/CVE-2022-2380.nopatch
Labels: security, Packaging, 1.0-dev

#3571 Fix npm version in nodejs.spec
  SPECS/nodejs/nodejs.spec
Labels: Packaging, main

#3564 Kernel upgrade to version 5.15.60.2
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/hyperv-daemons/hyperv-daemons.signatures.json
  SPECS/hyperv-daemons/hyperv-daemons.spec
  SPECS/kernel-headers/kernel-headers.signatures.json
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/CVE-2022-1973.nopatch
  SPECS/kernel/CVE-2022-2503.nopatch
  SPECS/kernel/CVE-2022-36879.nopatch
  SPECS/kernel/CVE-2022-36946.nopatch
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3535 perl-YAML: add BR on `perl(ExtUtils::MakeMaker)` & `cpan` to enable ptest
  SPECS/perl-YAML/perl-YAML.spec
Labels: Packaging, ptest, main

#3534 perl-Fedora-VSP: add BR on `perl(Test::More)` to fix ptest
  SPECS/perl-Fedora-VSP/perl-Fedora-VSP.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, ptest, main

#3570 Remove refs to sqlite CVE-2021-36690.patch
  toolkit/.gitignore
  toolkit/scripts/toolchain/container/Dockerfile
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
  toolkit/scripts/toolchain/create_toolchain_in_container.sh
Labels: main

#3562 Upgrade go 1.17 to 1.17.13 to fix 15 CVEs
  SPECS/golang/golang-1.17.signatures.json
  SPECS/golang/golang-1.17.spec
  cgmanifest.json
Labels: 1.0-dev

#3561 Upgrade go 1.18 to 1.18.5 to fix ten CVEs
  SPECS/audit/audit.spec
  SPECS/blobfuse/blobfuse.spec
  SPECS/cni/cni.spec
  SPECS/coredns/coredns-1.8.0.spec
  SPECS/coredns/coredns-1.8.4.spec
  SPECS/coredns/coredns-1.8.6.spec
  SPECS/cri-tools/cri-tools.spec
  SPECS/etcd/etcd-3.4.13.spec
  SPECS/etcd/etcd-3.5.0.spec
  SPECS/etcd/etcd-3.5.1.spec
  SPECS/flannel/flannel.spec
  SPECS/glide/glide.spec
  SPECS/go-md2man/go-md2man.spec
  SPECS/gobject-introspection/gobject-introspection.spec
  SPECS/golang/golang.signatures.json
  SPECS/golang/golang.spec
  SPECS/helm/helm.spec
  SPECS/libnvidia-container/libnvidia-container.spec
  SPECS/moby-buildx/moby-buildx.spec
  SPECS/moby-cli/moby-cli.spec
  SPECS/moby-containerd/moby-containerd.spec
  SPECS/moby-engine/moby-engine.spec
  SPECS/moby-runc/moby-runc.spec
  SPECS/node-problem-detector/node-problem-detector.spec
  SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec
  SPECS/telegraf/telegraf.spec
  cgmanifest.json
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#3572 kernel: Update to 5.10.133.1
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/hyperv-daemons/hyperv-daemons.signatures.json
  SPECS/hyperv-daemons/hyperv-daemons.spec
  SPECS/kernel-headers/kernel-headers.signatures.json
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel-hyperv/config
  SPECS/kernel-hyperv/kernel-hyperv.signatures.json
  SPECS/kernel-hyperv/kernel-hyperv.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/Dockerfile
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
  toolkit/scripts/toolchain/container/toolchain_build_temp_tools.sh
Labels: 1.0-dev

#3574 Upgrade vim to 9.0.0228 to fix seven CVEs
  SPECS/vim/vim.signatures.json
  SPECS/vim/vim.spec
  cgmanifest.json
Labels: 1.0-dev

#3577 xdelta: run `%check` section via a non-root user to fix ptest build
  SPECS-EXTENDED/xdelta/xdelta.spec
Labels: ptest, main, specs-extended

#3578 perl-Try-Tiny: add BR on `perl(Test::More)` to fix ptest build
  SPECS/perl-Try-Tiny/perl-Try-Tiny.spec
Labels: Packaging, ptest, main

#3579 flac: bump version to 1.3.4 & run `%check` as non-root to fix ptest
  SPECS-EXTENDED/flac/flac.signatures.json
  SPECS-EXTENDED/flac/flac.spec
  cgmanifest.json
Labels: ptest, main, specs-extended

#3576 Update cloud-hypervisor to v26.0 and rust to v1.62.1
  SPECS/cloud-hypervisor/cloud-hypervisor.signatures.json
  SPECS/cloud-hypervisor/cloud-hypervisor.spec
  SPECS/cloud-hypervisor/config.toml
  SPECS/rust/rust.signatures.json
  SPECS/rust/rust.spec
  cgmanifest.json
Labels: main

#3580 Upgrade vim to 9.0.0232 to fix 13 CVEs
  SPECS/vim/vim.signatures.json
  SPECS/vim/vim.spec
  cgmanifest.json
Labels: main

#3586 Update helm version 3.9.3
  SPECS/helm/CVE-2021-21303.patch
  SPECS/helm/CVE-2021-32690.patch
  SPECS/helm/helm.signatures.json
  SPECS/helm/helm.spec
  cgmanifest.json
Labels: main

#3581 cppcheck: fix `testrunner` binary path to fix ptest build
  SPECS-EXTENDED/cppcheck/cppcheck.spec
Labels: ptest, main, specs-extended

#3584 openssl - nopatch CVE-2022-2097 since only for 32-bit x86 platforms
  SPECS/openssl/CVE-2022-2097.nopatch
Labels: security, Packaging, main

#3597 qemu : fix CVE-2022-35414
  SPECS/qemu/CVE-2022-35414.patch
  SPECS/qemu/qemu.spec
Labels: security, Packaging, main

#3575 Update cert-manager to v1.7.3.
  SPECS/cert-manager/Fix-dependency-checksum.patch
  SPECS/cert-manager/Fix-os-WriteFile.patch
  SPECS/cert-manager/cert-manager.signatures.json
  SPECS/cert-manager/cert-manager.spec
  cgmanifest.json
Labels: Packaging, main

#3588 Add kata-containers
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/kata-containers/0002-Merged-PR-9607-Allow-10-seconds-for-VM-creation-star.patch
  SPECS/kata-containers/0003-Merged-PR-9671-Wait-for-a-possibly-slow-Guest.patch
  SPECS/kata-containers/15-dracut.conf
  SPECS/kata-containers/50-kata
  SPECS/kata-containers/kata-containers.signatures.json
  SPECS/kata-containers/kata-containers.spec
  SPECS/kata-containers/kata-osbuilder-generate.service
  SPECS/kata-containers/kata-osbuilder.sh
  cgmanifest.json
Labels: main

#3594 ccache: add symlinks to ccache
  SPECS/ccache/ccache.spec
Labels: main

#3592 perl-Module-Build: add BR on `perl(ExtUtils::*)` & `cpan` to enable ptest
  SPECS/perl-Module-Build/perl-Module-Build.spec
Labels: Packaging, ptest, main

#3589 perl-NetAddr-IP: add BR on `perl-{(Autoloader), (Test::More)}` to enable ptest
  SPECS/perl-NetAddr-IP/perl-NetAddr-IP.spec
Labels: Packaging, ptest, main

#3590 perl-List-MoreUtils: add BR on `perl-{(Math::Trig),(Test::More),(Tie::Array)}` to enable ptest
  SPECS/perl-List-MoreUtils/perl-List-MoreUtils.spec
Labels: Packaging, ptest, main

#3591 perl-Module-ScanDeps: add BR on `perl-{(CPAN::*),(FindBin),(Test::More)}` to enable ptest
  SPECS/perl-Module-ScanDeps/perl-Module-ScanDeps.spec
Labels: Packaging, ptest, main

#3583 libxml2 and python-lxml: fix CVE-2022-2309
  SPECS/libxml2/libxml2.signatures.json
  SPECS/libxml2/libxml2.spec
  SPECS/python-lxml/python-lxml.signatures.json
  SPECS/python-lxml/python-lxml.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3598 rubygem-yajl-ruby: fix CVE 2022 24795
  SPECS/rubygem-yajl-ruby/CVE-2022-24795.patch
  SPECS/rubygem-yajl-ruby/rubygem-yajl-ruby.spec
Labels: security, Packaging, main

#3605 perl-Net-SSLeay: add missing BRs & skip two failing tests
  SPECS/perl-Net-SSLeay/0001-local-tests-skip-2-failing-tests.patch
  SPECS/perl-Net-SSLeay/perl-Net-SSLeay.spec
Labels: Packaging, ptest, main

#3607 openssl : nopatch CVE-2022-2097 since against 32 bit platform only
  SPECS/openssl/CVE-2022-2097.nopatch
Labels: security, Packaging, 1.0-dev

#3599 Patch CVE-2021-46828 in libtirpc
  SPECS/libtirpc/CVE-2021-46828.patch
  SPECS/libtirpc/libtirpc.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#3608 qemu-kvm : fix CVE-2022-35414
  SPECS/qemu-kvm/CVE-2022-35414.patch
  SPECS/qemu-kvm/qemu-kvm.spec
Labels: Packaging, 1.0-dev

#3610 libxml2, python-lxml : fix CVE-2022-2309
  SPECS/libxml2/CVE-2022-2309.patch
  SPECS/libxml2/libxml2.spec
  SPECS/python-lxml/CVE-2022-2309.patch
  SPECS/python-lxml/python-lxml.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#3547 systemd-sysusers fsync patch
  SPECS/systemd/add-fsync-sysusers-passwd.patch
  SPECS/systemd/systemd-bootstrap.signatures.json
  SPECS/systemd/systemd-bootstrap.spec
  SPECS/systemd/systemd.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#3587 Enable package repo generation and network config for non-kickstart like ISO installation
  toolkit/docs/formats/imageconfig.md
  toolkit/tools/imagegen/configuration/networkconfig.go
  toolkit/tools/imagegen/installutils/installutils.go
Labels: Tools, main

#3566 Short-hand name for containerized-data-importer
  SPECS/containerized-data-importer/containerized-data-importer.spec
Labels: Packaging, main

#3603 Add an additional chrony config with updated version
  toolkit/imageconfigs/additionalconfigs/chrony.cfg
  toolkit/imageconfigs/marketplace-gen1.json
  toolkit/imageconfigs/marketplace-gen2-aarch64.json
  toolkit/imageconfigs/marketplace-gen2.json
Labels: Schema, main

#3614 Fix networkconfig test case
  toolkit/tools/imagegen/configuration/networkconfig_test.go
Labels: Tools, Schema, main

#3616 perl-Unicode-LineBreak: add BR on `perl(FindBin)` to fix ptest build
  SPECS-EXTENDED/perl-Unicode-LineBreak/perl-Unicode-LineBreak.spec
Labels: ptest, main, specs-extended

#3617 libsemanage: Do not ignore /root.
  SPECS/libsemanage/libsemanage.signatures.json
  SPECS/libsemanage/libsemanage.spec
  SPECS/libsemanage/semanage.conf
Labels: Packaging, main

#3619 Fix file mode on toolchain scripts
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
  toolkit/scripts/toolchain/container/toolchain_build_temp_tools.sh
Labels: Tools, 1.0-dev

#3611 Add ypbind package to Mariner
  SPECS-EXTENDED/nss_nis/nss_nis.signatures.json
  SPECS-EXTENDED/yp-tools/yp-tools.signatures.json
  SPECS-EXTENDED/ypbind/ypbind-2.4-gettext_version.patch
  SPECS-EXTENDED/ypbind/ypbind-systemdso.patch
  SPECS-EXTENDED/ypbind/ypbind.signatures.json
  SPECS/nss_nis/nss_nis.conf
  SPECS/nss_nis/nss_nis.signatures.json
  SPECS/nss_nis/nss_nis.spec
  SPECS/yp-tools/yp-tools-2.12-adjunct.patch
  SPECS/yp-tools/yp-tools-2.12-crypt.patch
  SPECS/yp-tools/yp-tools-2.12-hash.patch
  SPECS/yp-tools/yp-tools-4.2.2-strict-prototypes.patch
  SPECS/yp-tools/yp-tools-4.2.3-yppasswd.patch
  SPECS/yp-tools/yp-tools.signatures.json
  SPECS/yp-tools/yp-tools.spec
  SPECS/ypbind/nis.sh
  SPECS/ypbind/ypbind-1.11-gettextdomain.patch
  SPECS/ypbind/ypbind-2.5-helpman.patch
  SPECS/ypbind/ypbind-post-waitbind
  SPECS/ypbind/ypbind-pre-setdomain
  SPECS/ypbind/ypbind.service
  SPECS/ypbind/ypbind.signatures.json
  SPECS/ypbind/ypbind.spec
  cgmanifest.json
Labels: main

#3620 nopatching kernel CVE-2022-1651, CVE-2022-1671
  SPECS/kernel/CVE-2022-1651.nopatch
  SPECS/kernel/CVE-2022-1671.nopatch
Labels: security, Packaging, 1.0-dev

#3621 python-suds: add BR on `python3-pip` & drop `python3-pytest` to enable ptest
  SPECS-EXTENDED/python-suds/python-suds.spec
Labels: ptest, main, specs-extended

#3622 python-tornado: bump version to 6.2.0
  SPECS-EXTENDED/python-tornado/python-tornado.signatures.json
  SPECS-EXTENDED/python-tornado/python-tornado.spec
  cgmanifest.json
Labels: ptest, main, specs-extended

#3631 dpkd: bump version to 21.11.2 to address CVE-2022-2132
  SPECS/dpdk/dpdk.signatures.json
  SPECS/dpdk/dpdk.spec
  cgmanifest.json
Labels: security, main

#3628 Fix freshclam db download for clamav
  SPECS/clamav/clamav.spec
Labels: Packaging, 1.0-dev

#3629 kernel: Address CVE-2022-36123
  SPECS/kernel/CVE-2022-36123.nopatch
Labels: security, Packaging, 1.0-dev

#3637 selinux-policy: Various fixes.
  SPECS/selinux-policy/0044-systemd-Minor-coredump-fixes.patch
  SPECS/selinux-policy/0045-rpm-Minor-fixes.patch
  SPECS/selinux-policy/0046-init-Allow-nnp-nosuid-transitions-from-systemd-initr.patch
  SPECS/selinux-policy/0047-selinuxutil-Semanage-reads-policy-for-export.patch
  SPECS/selinux-policy/0048-sysnetwork-ifconfig-searches-debugfs.patch
  SPECS/selinux-policy/0049-usermanage-Add-dac_read_search-to-useradd.patch
  SPECS/selinux-policy/0050-Temp-kubernetes-fix.patch
  SPECS/selinux-policy/selinux-policy.spec
Labels: Packaging, main

#3638 Kernel upgrade to version 5.15.63.1 - branch main
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/hyperv-daemons/hyperv-daemons.signatures.json
  SPECS/hyperv-daemons/hyperv-daemons.spec
  SPECS/kernel-headers/kernel-headers.signatures.json
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/CVE-2022-1158.nopatch
  SPECS/kernel/CVE-2022-36123.nopatch
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#3643 `vim`: upgrade to 9.0.0325 to fix CVE-2022-2980, CVE-2022-2982, CVE-2…
  SPECS/vim/vim.signatures.json
  SPECS/vim/vim.spec
  cgmanifest.json
Labels: security, main

#3640 upgrade vim to fix CVE-2022-2982, CVE-2022-2946
  SPECS/vim/vim.signatures.json
  SPECS/vim/vim.spec
  cgmanifest.json
Labels: security, Packaging, 1.0-dev

#3645 `mariadb`: update to v10.6.9 to fix CVE-2022-32091, CVE-2022-32081
  SPECS/mariadb/mariadb.signatures.json
  SPECS/mariadb/mariadb.spec
  cgmanifest.json
Labels: security, main

#3641 Add mstflint package to Mariner
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/mstflint/add-default-link-flags-for-shared-libraries.patch
  SPECS/mstflint/mstflint.signatures.json
  SPECS/mstflint/mstflint.spec
  SPECS/mstflint/replace-mlxfwreset-with-mstfwreset-in-mstflint-message.patch
  cgmanifest.json
Labels: main
