Repository microsoft/azurelinux, pull requests merged in 2022-04, with the labels that each got.

#2642 [2.0] Adding `--assumeyes` for TDNF calls. (CP of #2640) (#2641)
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
Labels: Tools

#2610 Make prometheus-node-exporter executable
  SPECS/prometheus-node-exporter/prometheus-node-exporter.spec
Labels: Packaging, main

#2645 SPECS: update multiple signature files
  SPECS/dietlibc/dietlibc.signatures.json
  SPECS/java-cup/java-cup-bootstrap.signatures.json
  SPECS/java-cup/java-cup.signatures.json
  SPECS/python-pytest-xdist/python-pytest-xdist.signatures.json
Labels: Packaging, main

#2639 python-prettytable: Upgrade to 3.2.0
  SPECS/python-prettytable/python-prettytable.signatures.json
  SPECS/python-prettytable/python-prettytable.spec
  cgmanifest.json
Labels: main

#2649 [main] Reverting `python-pytest-xdist` signature change.
  SPECS/python-pytest-xdist/python-pytest-xdist.signatures.json
Labels: Packaging, main

#2638 kernel: update to 5.10.109.1
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/hyperv-daemons/CVE-2022-1016.patch
  SPECS/hyperv-daemons/CVE-2022-24958.patch
  SPECS/hyperv-daemons/hyperv-daemons.signatures.json
  SPECS/hyperv-daemons/hyperv-daemons.spec
  SPECS/kernel-headers/CVE-2022-1016.patch
  SPECS/kernel-headers/CVE-2022-24958.patch
  SPECS/kernel-headers/kernel-headers.signatures.json
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel-hyperv/CVE-2022-1016.patch
  SPECS/kernel-hyperv/CVE-2022-24958.patch
  SPECS/kernel-hyperv/config
  SPECS/kernel-hyperv/kernel-hyperv.signatures.json
  SPECS/kernel-hyperv/kernel-hyperv.spec
  SPECS/kernel/CVE-2021-3772.nopatch
  SPECS/kernel/CVE-2021-4002.nopatch
  SPECS/kernel/CVE-2021-45868.nopatch
  SPECS/kernel/CVE-2022-1016.nopatch
  SPECS/kernel/CVE-2022-1016.patch
  SPECS/kernel/CVE-2022-24958.nopatch
  SPECS/kernel/CVE-2022-24958.patch
  SPECS/kernel/CVE-2022-26490.nopatch
  SPECS/kernel/CVE-2022-26878.nopatch
  SPECS/kernel/CVE-2022-26966.nopatch
  SPECS/kernel/CVE-2022-27223.nopatch
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/Dockerfile
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
  toolkit/scripts/toolchain/container/toolchain_build_temp_tools.sh
Labels: 1.0-dev

#2619 [main] Update NVIDIA user mode libraries
  SPECS/libnvidia-container/common.mk.patch
  SPECS/libnvidia-container/libnvidia-container.signatures.json
  SPECS/libnvidia-container/libnvidia-container.spec
  SPECS/libnvidia-container/libtirpc.patch
  SPECS/libnvidia-container/nvidia-modprobe.patch
  SPECS/nvidia-container-runtime/nvidia-container-runtime.signatures.json
  SPECS/nvidia-container-runtime/nvidia-container-runtime.spec
  SPECS/nvidia-container-toolkit/nvidia-container-toolkit-1.4.2.patch
  SPECS/nvidia-container-toolkit/nvidia-container-toolkit-1.9.0.patch
  SPECS/nvidia-container-toolkit/nvidia-container-toolkit.signatures.json
  SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec
  SPECS/nvidia-docker2/nvidia-docker2.signatures.json
  SPECS/nvidia-docker2/nvidia-docker2.spec
  cgmanifest.json
Labels: main

#2637 python3: Add python-unversioned-command subpackage
  SPECS/python3/python3.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/resources/manifests/package/update_manifests.sh
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
Labels: main

#2634 [main] Removing invalid dependencies from `java-cup-bootstrap`.
  SPECS/java-cup/java-cup-bootstrap.signatures.json
  SPECS/java-cup/java-cup-bootstrap.spec
  SPECS/java-cup/java-cup-classpath.patch
  SPECS/java-cup/java-cup-lr_parser-constructor.patch
  SPECS/java-cup/java-cup-no-classpath-in-manifest.patch
  SPECS/java-cup/java-cup-no-cup-no-jflex.patch
  SPECS/java-cup/java-cup.signatures.json
  SPECS/java-cup/java-cup.spec
  SPECS/jflex/jflex-bootstrap.spec
  cgmanifest.json
Labels: Packaging, main

#2647 installkernel: Fix mariner.cfg symlink
  SPECS/installkernel/installkernel
  SPECS/installkernel/installkernel.signatures.json
  SPECS/installkernel/installkernel.spec
Labels: Packaging, 1.0-dev

#2648 Remove ipv6calc
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/ipv6calc/ipv6calc.signatures.json
  SPECS/ipv6calc/ipv6calc.spec
  cgmanifest.json
  toolkit/resources/manifests/package/macros.override
Labels: main

#2659 dnf-plugins-core: Fix bad python path in cmake call
  SPECS/dnf-plugins-core/dnf-plugins-core.spec
Labels: Packaging, main

#2658 dnf-plugins-core: Fix bad python path in cmake call
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/dnf-plugins-core/dnf-plugins-core.spec
Labels: Packaging

#2653 Update Github actions and quickstart for 2.0
  .github/workflows/check-manifests.yml
  .github/workflows/check-package-cgmanifest.yml
  .github/workflows/check-spec.yml
  .github/workflows/go-test-coverage.yml
  .github/workflows/lint-specs.yml
  .github/workflows/quickstart_2.0.yml
  .github/workflows/trigger-release-build.yml
  toolkit/docs/quick_start/quickstart.md
Labels: main

#2661 [main] Fix credscan error with bind and junit
  SPECS/bind/bind.signatures.json
  SPECS/bind/bind.spec
  SPECS/bind/trusted-key.key
  SPECS/junit/build.xml
  SPECS/junit/junit.signatures.json
  SPECS/junit/junit.spec
Labels: Packaging, main

#2663 fix calamares partitioning bug
  SPECS/calamares/calamares.spec
  SPECS/calamares/round-to-full-disk-size.patch
Labels: Packaging, main

#2636 Upgrade perl to 5.34.1
  SPECS/perl-generators/perl-generators.spec
  SPECS/perl/gendep.macros
  SPECS/perl/perl-5.22.1-Provide-ExtUtils-MM-methods-as-standalone-ExtUtils-M.patch
  SPECS/perl/perl-5.33.0-Add-missing-MANIFEST-entry-from-fix-for-debugger.patch
  SPECS/perl/perl-5.33.0-After-running-an-action-in-the-debugger-turn-it-off.patch
  SPECS/perl/perl-5.33.0-Clearing-DB-action-at-the-end-is-no-longer-needed.patch
  SPECS/perl/perl-5.33.0-Fix-leak-GH-18054.patch
  SPECS/perl/perl-5.33.0-IO-Handle-Fix-a-spurious-error-reported-for-regular-.patch
  SPECS/perl/perl-5.33.0-IO-Handle-clear-the-error-on-both-input-and-output-s.patch
  SPECS/perl/perl-5.33.0-IO-Socket-UNIX-synchronize-behavior-with-module-docu.patch
  SPECS/perl/perl-5.33.0-MUTABLE_PTR-Rmv-non-standard-syntax.patch
  SPECS/perl/perl-5.33.0-Update-pod-for-SvTRUE-to-indicate-single-param-evalu.patch
  SPECS/perl/perl-5.33.0-XSUB.h-fix-MARK-and-items-variables-inside-BOOT-XSUB.patch
  SPECS/perl/perl-5.33.0-ext-XS-APItest-t-utf8_warn_base.pl-Fix-a-couple-test.patch
  SPECS/perl/perl-5.33.0-fix-C-i-obj-where-obj-is-a-lexical.patch
  SPECS/perl/perl-5.33.0-list-assign-in-list-context-honour-LHS-undef.patch
  SPECS/perl/perl-5.33.0-list-assign-in-list-context-was-over-optimising.patch
  SPECS/perl/perl-5.33.0-make-fh-error-report-errors-from-both-input-and-outp.patch
  SPECS/perl/perl-5.33.0-perl-17844-don-t-update-SvCUR-until-after-we-ve-done.patch
  SPECS/perl/perl-5.33.0-reentr.c-Buffer-sizes-for-asctime_r-ctime_r-are-smal.patch
  SPECS/perl/perl-5.33.0-reentr.c-Prevent-infinite-looping.patch
  SPECS/perl/perl-5.33.0-sv.h-Wanted-UOK-but-said-IOK.patch
  SPECS/perl/perl-5.33.1-die_unwind-global-destruction.patch
  SPECS/perl/perl-5.33.1-sort-return-foo.patch
  SPECS/perl/perl-5.34.0-Destroy-GDBM-NDBM-ODBM-SDBM-_File-objects-only-from-.patch
  SPECS/perl/perl.signatures.json
  SPECS/perl/perl.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#2660 Removing BR on `python3-pytest`.
  SPECS/python-tomli/python-tomli.spec
Labels: Packaging, main

#2662 net-tools: Remove mv command
  SPECS/net-tools/net-tools.spec
Labels: Packaging, main

#2657 Fix python-sphinx_rtd_theme ptest
  SPECS/python-sphinx_rtd_theme/python-sphinx_rtd_theme.spec
Labels: Packaging, ptest, main

#2666 [main] Fixing `ocaml*.spec` macros.
  SPECS/ocaml-cmdliner/ocaml-cmdliner.spec
  SPECS/ocaml-result/ocaml-result.spec
Labels: Packaging, main

#2667 Update python requirement in azurevm packagelist for 2.0
  toolkit/imageconfigs/packagelists/azurevm-packages.json
Labels: Schema

#2643 Adding inline PackageList for configs
  toolkit/tools/imageconfigvalidator/imageconfigvalidator_test.go
  toolkit/tools/imagegen/configuration/configuration_test.go
  toolkit/tools/imagegen/configuration/systemconfig.go
  toolkit/tools/imagegen/configuration/systemconfig_test.go
  toolkit/tools/imagegen/configuration/testdata/test_configuration.json
  toolkit/tools/imagegen/installutils/installutils.go
Labels: Tools, main

#2644 selinux-policy: Additional policy fixes for enforcing core images
  SPECS/selinux-policy/0004-Set-default-login-to-unconfined_u.patch
  SPECS/selinux-policy/0010-domain-Allow-lockdown-for-all-domains.patch
  SPECS/selinux-policy/0011-systemd-Drop-systemd_detect_virt_t.patch
  SPECS/selinux-policy/0012-fstools-Handle-resizes-of-the-root-filesystem.patch
  SPECS/selinux-policy/0013-mount-Get-the-attributes-of-all-filesystems.patch
  SPECS/selinux-policy/0014-systemd-Misc-updates.patch
  SPECS/selinux-policy/0015-rpm-Add-dnf-and-tdnf-labeling.patch
  SPECS/selinux-policy/0016-logging-Change-to-systemd-interface-for-tmpfilesd.patch
  SPECS/selinux-policy/0017-Add-cloud-init.patch
  SPECS/selinux-policy/selinux-policy.spec
Labels: Packaging, 1.0-dev

#2670 [main] Adding a workaround for the source name conflict in `ocaml-fileutils`.
  SPECS/ocaml-fileutils/ocaml-fileutils.signatures.json
  SPECS/ocaml-fileutils/ocaml-fileutils.spec
Labels: Packaging, main

#2669 [main] [ARM] Fix SymCrypt build in aarch64 by BuildRequiring clang
  SPECS/SymCrypt/SymCrypt.spec
Labels: Packaging, main

#2668 Update python requirement in azurevm packagelist for 2.0
  toolkit/imageconfigs/packagelists/azurevm-packages.json
Labels: Schema, main

#2553 Support building Mariner 2.0 on Mariner 1.0 host build machine
  toolkit/scripts/toolchain/container/Dockerfile
Labels: Tools, main

#2665 Add missing packages to toolchain
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/resources/manifests/package/update_manifests.sh
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
Labels: main

#2681 [SPECS-EXTENDED][main] Adding a missing BR in `perl-Module-Install-AutoLicense.spec`.
  SPECS-EXTENDED/perl-Module-Install-AutoLicense/perl-Module-Install-AutoLicense.spec
Labels: main

#2680 Adding missing `Obsoletes` to `systemd`.
  SPECS/systemd/systemd.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#2686 python-pyvmomi: Upgrade to latest version
  SPECS/python-pyvmomi/python-pyvmomi-make-check-fix.patch
  SPECS/python-pyvmomi/python-pyvmomi.signatures.json
  SPECS/python-pyvmomi/python-pyvmomi.spec
  cgmanifest.json
Labels: main

#2688 pygobject3: Upgrade to 3.42.0
  SPECS/pygobject3/build_without_cairo.patch
  SPECS/pygobject3/pygobject-makecheck-fixes.patch
  SPECS/pygobject3/pygobject3.signatures.json
  SPECS/pygobject3/pygobject3.spec
  cgmanifest.json
Labels: main

#2683 python-msgpack: Upgrade to 1.0.3
  SPECS/python-msgpack/python-msgpack.signatures.json
  SPECS/python-msgpack/python-msgpack.spec
  cgmanifest.json
Labels: main

#2679 [main] Migrating `libguestfs` from `SPECS-EXTENDED`.
  SPECS/libguestfs/README-replacement.in
  SPECS/libguestfs/copy-patches.sh
  SPECS/libguestfs/guestfish.sh
  SPECS/libguestfs/libguestfs-config-rpm.patch
  SPECS/libguestfs/libguestfs-file-5.40.patch
  SPECS/libguestfs/libguestfs-ocaml413compat.patch
  SPECS/libguestfs/libguestfs.signatures.json
  SPECS/libguestfs/libguestfs.spec
  SPECS/libguestfs/tdnf-build-cache.repo
  SPECS/libguestfs/yum.conf.in
  cgmanifest.json
Labels: Packaging, main

#2651 kernel: Remove hardcoded cert from kernel config
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel-hyperv/config
  SPECS/kernel-hyperv/kernel-hyperv.signatures.json
  SPECS/kernel-hyperv/kernel-hyperv.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#2682 [main] fix wayland_devel require libffi_devel
  SPECS/wayland-protocols/wayland-protocols.spec
  SPECS/wayland/wayland.spec
Labels: Packaging, main

#2677 [1.0-dev] NVIDIA user mode libraries from 2.0
  SPECS/libnvidia-container/common.mk.patch
  SPECS/libnvidia-container/libnvidia-container.signatures.json
  SPECS/libnvidia-container/libnvidia-container.spec
  SPECS/libnvidia-container/libtirpc.patch
  SPECS/libnvidia-container/nvidia-modprobe.patch
  SPECS/nvidia-container-runtime/nvidia-container-runtime.signatures.json
  SPECS/nvidia-container-runtime/nvidia-container-runtime.spec
  SPECS/nvidia-container-toolkit/nvidia-container-toolkit-1.5.1.patch
  SPECS/nvidia-container-toolkit/nvidia-container-toolkit-1.9.0.patch
  SPECS/nvidia-container-toolkit/nvidia-container-toolkit.signatures.json
  SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec
  SPECS/nvidia-docker2/nvidia-docker2.signatures.json
  SPECS/nvidia-docker2/nvidia-docker2.spec
  cgmanifest.json
Labels: Packaging, 1.0-dev

#2671 [main] Add kernel support for Dell devices
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel-rt/config
  SPECS/kernel-rt/kernel-rt.signatures.json
  SPECS/kernel-rt/kernel-rt.spec
  SPECS/kernel/config
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#2694 Bump Release for Mariner 1.0 April 2022 Update
  SPECS/mariner-release/mariner-release.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#2698 Fix ARM64 Build Break due to missing requires on edk2-aarch64
  SPECS/libguestfs/libguestfs.spec
Labels: Packaging, main

#2689 fix OpenBlas and edk2 so they build from containerized env
  SPECS-EXTENDED/edk2/edk2.spec
  SPECS-EXTENDED/openblas/No-Fortran-Build.patch
  SPECS-EXTENDED/openblas/openblas.spec
Labels: main

#2699 [main] Update kernel to v5.15.32.1
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/hyperv-daemons/hyperv-daemons.signatures.json
  SPECS/hyperv-daemons/hyperv-daemons.spec
  SPECS/kernel-headers/kernel-headers.signatures.json
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel-rt/config
  SPECS/kernel-rt/kernel-rt.signatures.json
  SPECS/kernel-rt/kernel-rt.spec
  SPECS/kernel-rt/patch-5.15.32-rt39.patch
  SPECS/kernel/CVE-2021-4002.nopatch
  SPECS/kernel/CVE-2022-0516.nopatch
  SPECS/kernel/CVE-2022-0742.nopatch
  SPECS/kernel/CVE-2022-1011.nopatch
  SPECS/kernel/CVE-2022-24958.nopatch
  SPECS/kernel/CVE-2022-26490.nopatch
  SPECS/kernel/CVE-2022-26878.nopatch
  SPECS/kernel/CVE-2022-27223.nopatch
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/Dockerfile
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
  toolkit/scripts/toolchain/container/toolchain_build_temp_tools.sh
Labels: main

#2685 Upgraded vim to fix CVE-2022-1154
  SPECS/vim/vim.signatures.json
  SPECS/vim/vim.spec
  cgmanifest.json
Labels: 1.0-dev

#2705 Remove cloud-init-vmware-guestinfo package
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/cloud-init-vmware-guestinfo/cloud-init-vmware-guestinfo.signatures.json
  SPECS/cloud-init-vmware-guestinfo/cloud-init-vmware-guestinfo.spec
  cgmanifest.json
Labels: main

#2696 installkernel: Fix mariner.cfg symlink
  SPECS/installkernel/installkernel
  SPECS/installkernel/installkernel.signatures.json
  SPECS/installkernel/installkernel.spec
Labels: Packaging, main

#2702 [1.0] Add ptp_hyperv udev rule to systemd
  SPECS/systemd/Add-ptp_hyperv-udev-rule.patch
  SPECS/systemd/systemd.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#2701 [main][SPECS-EXTENDED] Fixing `cassandra` dependencies.
  SPECS-EXTENDED/jlex/jlex.spec
  SPECS-EXTENDED/servletapi5/servletapi5.spec
Labels: main

#2346 libcap: update to 2.60
  SPECS/libcap/libcap.signatures.json
  SPECS/libcap/libcap.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/toolchain-remote-wget-list
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
Labels: main

#2712 vim: Update version to 8.2.4743 to fix CVE-2022-0408,CVE-2022-0413,CV…
  SPECS/vim/vim.signatures.json
  SPECS/vim/vim.spec
  cgmanifest.json
Labels: main

#2684 Bring rsyslog.conf in line with other distros
  SPECS/rsyslog/rsyslog.conf
  SPECS/rsyslog/rsyslog.signatures.json
  SPECS/rsyslog/rsyslog.spec
Labels: main

#2710 libdb: Patch CVE-2019-2708, Nopatch CVE-2017-3604 to CVE-2017-3617 and CVE-2020-2981
  SPECS/libdb/CVE-2017-3604.nopatch
  SPECS/libdb/CVE-2017-3605.nopatch
  SPECS/libdb/CVE-2017-3606.nopatch
  SPECS/libdb/CVE-2017-3607.nopatch
  SPECS/libdb/CVE-2017-3608.nopatch
  SPECS/libdb/CVE-2017-3609.nopatch
  SPECS/libdb/CVE-2017-3610.nopatch
  SPECS/libdb/CVE-2017-3611.nopatch
  SPECS/libdb/CVE-2017-3612.nopatch
  SPECS/libdb/CVE-2017-3613.nopatch
  SPECS/libdb/CVE-2017-3614.nopatch
  SPECS/libdb/CVE-2017-3615.nopatch
  SPECS/libdb/CVE-2017-3616.nopatch
  SPECS/libdb/CVE-2017-3617.nopatch
  SPECS/libdb/CVE-2019-2708.patch
  SPECS/libdb/CVE-2020-2981.nopatch
  SPECS/libdb/libdb.spec
Labels: Packaging, main

#2715 ruby: Do not store certain compiler flags for extension building
  SPECS/ruby/ruby.spec
Labels: Packaging, main

#2706 [main] Initial `cgmanifest.json` clean-up.
  .github/workflows/validate-cg-manifest.sh
  SPECS-EXTENDED/libecb/libecb.spec
  SPECS/expat/expat.spec
  SPECS/gnu-efi/gnu-efi.spec
  SPECS/harfbuzz/harfbuzz.spec
  SPECS/libisoburn/libisoburn.spec
  SPECS/libnl3/libnl3.spec
  SPECS/ndctl/ndctl.spec
  SPECS/pigz/pigz.spec
  SPECS/python-boto3/python-boto3.spec
  SPECS/python-linux-procfs/python-linux-procfs.signatures.json
  SPECS/python-linux-procfs/python-linux-procfs.spec
  SPECS/rapidjson/rapidjson.spec
  SPECS/sg3_utils/sg3_utils.spec
  SPECS/sgml-common/sgml-common.spec
  SPECS/tuna/tuna.signatures.json
  SPECS/tuna/tuna.spec
  SPECS/vnstat/vnstat.spec
  SPECS/xml-commons-apis/xml-commons-apis.spec
  SPECS/zchunk/zchunk.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/update_cgmanifest.py
Labels: main

#2691 [main] Updating `python-sphinx` to version 4.4.0.
  SPECS-EXTENDED/python-html5lib/collections-abc.patch
  SPECS-EXTENDED/python-html5lib/pytest4.patch
  SPECS-EXTENDED/python-html5lib/python-html5lib.signatures.json
  SPECS-EXTENDED/python-importlib-metadata/python-importlib-metadata.signatures.json
  SPECS-EXTENDED/python-importlib-metadata/python-importlib-metadata.spec
  SPECS-EXTENDED/python-zipp/python-zipp.signatures.json
  SPECS-EXTENDED/python-zipp/python-zipp.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/libvirt-glib/libvirt-glib.spec
  SPECS/python-html5lib/506.patch
  SPECS/python-html5lib/python-html5lib.signatures.json
  SPECS/python-html5lib/python-html5lib.spec
  SPECS/python-importlib-metadata/python-importlib-metadata.signatures.json
  SPECS/python-importlib-metadata/python-importlib-metadata.spec
  SPECS/python-pytest-expect/LICENSE
  SPECS/python-pytest-expect/python-pytest-expect.signatures.json
  SPECS/python-pytest-expect/python-pytest-expect.spec
  SPECS/python-sphinx/python-sphinx.signatures.json
  SPECS/python-sphinx/python-sphinx.spec
  SPECS/python-sphinxcontrib-applehelp/python-sphinxcontrib-applehelp.signatures.json
  SPECS/python-sphinxcontrib-applehelp/python-sphinxcontrib-applehelp.spec
  SPECS/python-sphinxcontrib-devhelp/python-sphinxcontrib-devhelp.signatures.json
  SPECS/python-sphinxcontrib-devhelp/python-sphinxcontrib-devhelp.spec
  SPECS/python-sphinxcontrib-htmlhelp/python-sphinxcontrib-htmlhelp.signatures.json
  SPECS/python-sphinxcontrib-htmlhelp/python-sphinxcontrib-htmlhelp.spec
  SPECS/python-sphinxcontrib-jsmath/python-sphinxcontrib-jsmath.signatures.json
  SPECS/python-sphinxcontrib-jsmath/python-sphinxcontrib-jsmath.spec
  SPECS/python-sphinxcontrib-qthelp/python-sphinxcontrib-qthelp.signatures.json
  SPECS/python-sphinxcontrib-qthelp/python-sphinxcontrib-qthelp.spec
  SPECS/python-sphinxcontrib-serializinghtml/python-sphinxcontrib-serializinghtml.spec
  SPECS/python-zipp/python-zipp.signatures.json
  SPECS/python-zipp/python-zipp.spec
  cgmanifest.json
  toolkit/scripts/download_spec_sources.sh
Labels: main

#2697 iso-initrd: Add linux-firmware package
  toolkit/resources/imageconfigs/packagelists/iso-initrd-packages-arm64.json
  toolkit/resources/imageconfigs/packagelists/iso-initrd-packages.json
Labels: main

#2708 golang: bump version to 1.17.8 to address CVE-2021-44716
  SPECS/golang/golang-1.17.signatures.json
  SPECS/golang/golang-1.17.spec
  cgmanifest.json
Labels: security, main

#2723 Add pwgen and glide packages
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/glide/glide.signatures.json
  SPECS/glide/glide.spec
  SPECS/pwgen/pwgen.signatures.json
  SPECS/pwgen/pwgen.spec
  cgmanifest.json
Labels: main

#2711 squashfs-tools: Update to version 4.5.1 to address CVE-2021-41072 and CVE-2021-40153
  SPECS/squashfs-tools/squashfs-tools.signatures.json
  SPECS/squashfs-tools/squashfs-tools.spec
  cgmanifest.json
Labels: main

#2717 Update httpd version to 2.4.53 to fix CVE CVE-2022-22720, CVE-2022-22721, CVE-2022-23943
  SPECS/httpd/httpd-2.4.52-blfs_layout-1.patch
  SPECS/httpd/httpd-2.4.53-blfs_layout-3.patch
  SPECS/httpd/httpd.signatures.json
  SPECS/httpd/httpd.spec
  cgmanifest.json
Labels: main

#2719 Nicogbg/fix strongswan CVE
  SPECS/strongswan/strongswan.signatures.json
  SPECS/strongswan/strongswan.spec
  cgmanifest.json
Labels: main

#2692 [main] add config for ARM marketplace img gen2
  toolkit/imageconfigs/marketplace-gen2-aarch64.json
Labels: Schema, main

#2678 Improving validation for disk configurations
  toolkit/tools/imagegen/configuration/configuration_test.go
  toolkit/tools/imagegen/configuration/disk.go
  toolkit/tools/imagegen/configuration/disk_test.go
Labels: Tools, main

#2722 gd: backport patch from upstream to address CVE-2021-40145
  SPECS/gd/CVE-2021-40145.patch
  SPECS/gd/gd.spec
Labels: security, Packaging, main

#2729 [main] Adding the `ksh` package.
  SPECS-EXTENDED/ksh/dotkshrc
  SPECS-EXTENDED/ksh/ksh-1.0.0-beta.1-fix-build.patch
  SPECS-EXTENDED/ksh/ksh-1.0.0-beta.1-regre-tests.patch
  SPECS-EXTENDED/ksh/ksh.signatures.json
  SPECS-EXTENDED/ksh/ksh.spec
  SPECS-EXTENDED/ksh/kshcomp.conf
  SPECS-EXTENDED/ksh/kshrc.rhs
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#2734 pciutils: Do not change libpci.so rights during install
  SPECS/pciutils/pciutils.spec
Labels: Packaging, main

#2726 [main] Fixing Ruby packages builds.
  SPECS-EXTENDED/rubygem-rspec/rubygem-rspec.spec
  SPECS/ruby/macros.rubygems
  SPECS/ruby/ruby.signatures.json
  SPECS/ruby/ruby.spec
Labels: main

#2728 [main] Updating `ntfs-3g` to 2021.8.22 to fix 21 CVEs from 2021-33285 to 2021-39263.
  SPECS/ntfs-3g/check-mftmirr.patch
  SPECS/ntfs-3g/ntfs-3g-CVE-2019-9755.patch
  SPECS/ntfs-3g/ntfs-3g-big-sectors.patch
  SPECS/ntfs-3g/ntfs-3g.signatures.json
  SPECS/ntfs-3g/ntfs-3g.spec
  SPECS/ntfs-3g/ntfsclone-full-clusters-bz1601146.patch
  cgmanifest.json
Labels: main

#2738 [main] Migrating CVE fixes for qt5 packages. (CP #1481)
  SPECS/qt5-qtbase/qt5-qtbase.signatures.json
  SPECS/qt5-qtbase/qt5-qtbase.spec
  SPECS/qt5-qtbase/xcberror_filter.patch
  SPECS/qt5-qtsvg/CVE-2018-21035.nopatch
  SPECS/qt5-qtsvg/CVE-2021-38593.nopatch
  SPECS/qt5-qtsvg/CVE-2022-25634.nopatch
  SPECS/qt5-qtsvg/qt5-qtsvg.signatures.json
  SPECS/qt5-qtsvg/qt5-qtsvg.spec
  cgmanifest.json
Labels: main

#2730 Update postgresql and vsftpd for CVE-2021-23214, CVE-2021-23222, CVE-2021-3618
  SPECS/postgresql/postgresql.signatures.json
  SPECS/postgresql/postgresql.spec
  SPECS/vsftpd/vsftpd.signatures.json
  SPECS/vsftpd/vsftpd.spec
  cgmanifest.json
Labels: main

#2731 [main] [bug] Address Constant Journald crash on Mariner 2.0
  SPECS/systemd/fix-journald-audit-logging.patch
  SPECS/systemd/systemd-bootstrap.spec
  SPECS/systemd/systemd.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#2744 move provide net-snmp-agent-lib
  SPECS/net-snmp/net-snmp.spec
Labels: Packaging, main

#2733 cassandra: cleanup signature file
  SPECS-EXTENDED/cassandra/cassandra.signatures.json
Labels: main

#2713 Adding Swap Partition Support
  toolkit/docs/formats/imageconfig.md
  toolkit/tools/imagegen/diskutils/diskutils.go
Labels: main

#2735 Make changes in aarch64 config for kernel update to v5.15.32
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
Labels: Packaging, main

#2757 Remove python-boto3, python-botocore specs
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/python-boto3/python-boto3.signatures.json
  SPECS/python-boto3/python-boto3.spec
  SPECS/python-botocore/python-botocore.signatures.json
  SPECS/python-botocore/python-botocore.spec
  cgmanifest.json
Labels: main

#2756 python-attrs: Upgrade to 21.4.0
  SPECS/python-attrs/python-attrs.signatures.json
  SPECS/python-attrs/python-attrs.spec
  cgmanifest.json
Labels: main

#2724 Update glibc to 2.35 to fix CVE-2022-23218 and CVE-2022-23219
  SPECS/glibc/0002-malloc-arena-fix.patch
  SPECS/glibc/CVE-2016-10739.patch
  SPECS/glibc/CVE-2019-19126.patch
  SPECS/glibc/CVE-2019-25013.patch
  SPECS/glibc/CVE-2019-7309.patch
  SPECS/glibc/CVE-2019-9169.patch
  SPECS/glibc/CVE-2020-10029.patch
  SPECS/glibc/CVE-2020-1752.patch
  SPECS/glibc/CVE-2020-27618.patch
  SPECS/glibc/CVE-2021-3326.patch
  SPECS/glibc/glibc-2.24-bindrsvport-blacklist.patch
  SPECS/glibc/glibc-2.28-CVE-2018-19591.patch
  SPECS/glibc/glibc-2.35-fhs-1.patch
  SPECS/glibc/glibc.signatures.json
  SPECS/glibc/glibc.spec
  SPECS/libxcrypt/libxcrypt.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/toolchain-remote-wget-list
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
  toolkit/scripts/toolchain/container/toolchain_build_temp_tools.sh
Labels: main

#2758 python-asn1crypto: Upgrade to 1.5.1
  SPECS/python-asn1crypto/python-asn1crypto.signatures.json
  SPECS/python-asn1crypto/python-asn1crypto.spec
  cgmanifest.json
Labels: main

#2747 [main] upgraded python-daemon to 2.3.0
  SPECS/python-daemon/python-daemon.signatures.json
  SPECS/python-daemon/python-daemon.spec
  cgmanifest.json
Labels: main

#2718 [main] Add PreInstallation Scripts Entry to image configs
  toolkit/docs/formats/imageconfig.md
  toolkit/tools/imagegen/attendedinstaller/_manualrun/manualrun.go
  toolkit/tools/imagegen/configuration/configuration.go
  toolkit/tools/imagegen/configuration/configuration_test.go
  toolkit/tools/imagegen/configuration/systemconfig.go
  toolkit/tools/imagegen/configuration/testdata/test_configuration.json
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/imager/imager.go
Labels: Tools, main

#2760 Reduce toolchain build time by reverting toolchain.mk modification
  toolkit/scripts/toolchain.mk
Labels: Tools, main

#2727 Reduce Mariner container image size
  SPECS/chkconfig/chkconfig.spec
  SPECS/core-packages/core-packages.spec
  SPECS/gnupg2/gnupg2.spec
  SPECS/mariner-repos/mariner-repos.spec
  SPECS/newt/newt.spec
  SPECS/rpm/rpm.spec
  SPECS/tdnf/tdnf.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#2720 Fix kernel debug build hang
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/hyperv-daemons/hyperv-daemons.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel-rt/kernel-rt.spec
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#2627 Add toolchain debug features to the depsearch tool
  toolkit/tools/depsearch/depsearch.go
  toolkit/tools/scheduler/schedulerutils/buildlist.go
Labels: Tools, main

#2673 Makefile fixes to reduce undesirable rebuild of files, clean up a chroot
  toolkit/scripts/srpm_pack.mk
  toolkit/scripts/toolchain.mk
Labels: Tools, main

#2765 Remove python-lxml debuginfo packge
  SPECS/python-lxml/python-lxml.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Tools, main

#2754 fix missed to increment release nb in previous libdb PR
  SPECS/libdb/libdb.spec
Labels: Packaging, main

#2768 Bump version for Preview-H
  SPECS/mariner-release/mariner-release.spec
  toolkit/Makefile
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#2675 Add scheduler support for prebuilt toolchain packages
  toolkit/scripts/pkggen.mk
  toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
  toolkit/tools/imagepkgfetcher/imagepkgfetcher.go
  toolkit/tools/internal/packagerepo/repocloner/repocloner.go
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
  toolkit/tools/internal/packagerepo/repoutils/repoutils.go
  toolkit/tools/internal/pkggraph/pkggraph.go
  toolkit/tools/scheduler/schedulerutils/preparerequest.go
Labels: Tools, main

#2676 Add priority queue to scheduler
  toolkit/tools/graphPreprocessor/graphPreprocessor.go
  toolkit/tools/internal/pkggraph/pkggraph.go
  toolkit/tools/scheduler/scheduler.go
  toolkit/tools/scheduler/schedulerutils/buildworker.go
Labels: Tools, main

#2767 Toolchain tooling staging branch
  SPECS/python-lxml/python-lxml.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/pkggen.mk
  toolkit/scripts/srpm_pack.mk
  toolkit/scripts/toolchain.mk
  toolkit/tools/depsearch/depsearch.go
  toolkit/tools/graphPreprocessor/graphPreprocessor.go
  toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
  toolkit/tools/imagepkgfetcher/imagepkgfetcher.go
  toolkit/tools/internal/packagerepo/repocloner/repocloner.go
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
  toolkit/tools/internal/packagerepo/repoutils/repoutils.go
  toolkit/tools/internal/pkggraph/pkggraph.go
  toolkit/tools/scheduler/scheduler.go
  toolkit/tools/scheduler/schedulerutils/buildlist.go
  toolkit/tools/scheduler/schedulerutils/buildworker.go
  toolkit/tools/scheduler/schedulerutils/graphbuildstate.go
  toolkit/tools/scheduler/schedulerutils/preparerequest.go
  toolkit/tools/scheduler/schedulerutils/printresults.go
Labels: Tools, go, main

#2739 zlib: upgrade to 1.12.2 to fix CVE-2018-25032
  SPECS/zlib/zlib.signatures.json
  SPECS/zlib/zlib.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/toolchain-remote-wget-list
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
Labels: main

#2772 python-requests_ntlm: disable check section to unblock ptest pipeline
  SPECS-EXTENDED/python-requests_ntlm/python-requests_ntlm.spec
Labels: ptest, main, specs-extended

#2771 nbd: disable check section to unblock ptest pipeline
  SPECS-EXTENDED/nbd/nbd.spec
Labels: ptest, main, specs-extended

#2755 Cameronbaird/libtiff cves
  SPECS/libtiff/CVE-2022-0561.patch
  SPECS/libtiff/CVE-2022-0562.patch
  SPECS/libtiff/CVE-2022-0865.patch
  SPECS/libtiff/CVE-2022-0891.patch
  SPECS/libtiff/CVE-2022-0907.patch
  SPECS/libtiff/CVE-2022-0908.patch
  SPECS/libtiff/CVE-2022-0909.patch
  SPECS/libtiff/CVE-2022-0924.patch
  SPECS/libtiff/CVE-2022-1056.nopatch
  SPECS/libtiff/CVE-2022-22844.patch
  SPECS/libtiff/libtiff.spec
Labels: Packaging, main

#2759 [main] kernel: fix CVE-2022-0995, 2022-1055, 2022-27666
  SPECS/kernel/CVE-2022-0995.nopatch
  SPECS/kernel/CVE-2022-1055.nopatch
  SPECS/kernel/CVE-2022-27666.nopatch
  SPECS/kernel/kernel.spec
Labels: Packaging, main

#2775 [2.0] Fix missing boringssl license reference
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
Labels: Packaging

#2769 Revert: kernel-signed: workaround errant .build-id file
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
Labels: Packaging

#2770 Remove xerces-c
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/xerces-c/xerces-c.signatures.json
  SPECS/xerces-c/xerces-c.spec
  cgmanifest.json
Labels: main

#2774 java-cup: cleanup signature files
  SPECS/java-cup/java-cup-bootstrap.signatures.json
  SPECS/java-cup/java-cup.signatures.json
Labels: Packaging, main

#2776 [main] Adding support for the `ExcludeArch` spec tag.
  .github/workflows/check-clean-stage.yml
  .github/workflows/check-package-cgmanifest.yml
  .github/workflows/check-spec.yml
  .github/workflows/lint-specs.yml
  toolkit/tools/internal/rpm/rpm.go
  toolkit/tools/internal/rpm/rpm_test.go
  toolkit/tools/internal/rpm/testdata/supported_unsupported_architectures.spec
  toolkit/tools/internal/rpm/testdata/unsupported_architectures.spec
  toolkit/tools/specreader/specreader.go
  toolkit/tools/srpmpacker/srpmpacker.go
Labels: Tools, main

#2787 [1.0] Patch xerces-c CVE-2018-1311
  SPECS/xerces-c/CVE-2018-1311.patch
  SPECS/xerces-c/xerces-c.spec
Labels: Packaging, 1.0-dev

#2786 [1.0] python-pip backport patch for CVE-2021-3572
  SPECS/python-pip/CVE-2021-3572.patch
  SPECS/python-pip/python-pip.spec
Labels: Packaging, 1.0-dev

#2736 [main] expat: update to 2.4.8 for CVE-2022-23852, CVE-2022-23990, CVE-2022-25235, CVE-2022-25236
  SPECS/expat/expat.signatures.json
  SPECS/expat/expat.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/toolchain-remote-wget-list
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
Labels: main

#2783 [1.0] Patch util-linux CVE-2022-0563
  SPECS/util-linux/CVE-2022-0563.patch
  SPECS/util-linux/util-linux.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#2777 Upgrade ruby to v3.1.2, fix CVE 2021-41817,2021-41819, build gems separately
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/ruby/patch1-rb.patch
  SPECS/ruby/patch2-rb.patch
  SPECS/ruby/patch3-rb.patch
  SPECS/ruby/patch4-rb.patch
  SPECS/ruby/ruby-2.1.0-Prevent-duplicated-paths-when-empty-version-string-i.patch
  SPECS/ruby/ruby-2.3.0-ruby_version.patch
  SPECS/ruby/ruby.signatures.json
  SPECS/ruby/ruby.spec
  SPECS/rubygem-bigdecimal/rubygem-bigdecimal.signatures.json
  SPECS/rubygem-bigdecimal/rubygem-bigdecimal.spec
  SPECS/rubygem-concurrent-ruby/remove_jar.patch
  SPECS/rubygem-concurrent-ruby/rubygem-concurrent-ruby.signatures.json
  SPECS/rubygem-concurrent-ruby/rubygem-concurrent-ruby.spec
  SPECS/rubygem-io-console/rubygem-io-console.signatures.json
  SPECS/rubygem-io-console/rubygem-io-console.spec
  SPECS/rubygem-json/rubygem-json.signatures.json
  SPECS/rubygem-json/rubygem-json.spec
  SPECS/rubygem-minitest/rubygem-minitest.signatures.json
  SPECS/rubygem-minitest/rubygem-minitest.spec
  SPECS/rubygem-mocha/rubygem-mocha.signatures.json
  SPECS/rubygem-mocha/rubygem-mocha.spec
  SPECS/rubygem-openssl/rubygem-openssl.signatures.json
  SPECS/rubygem-openssl/rubygem-openssl.spec
  SPECS/rubygem-power_assert/rubygem-power_assert.signatures.json
  SPECS/rubygem-power_assert/rubygem-power_assert.spec
  SPECS/rubygem-psych/rubygem-psych.signatures.json
  SPECS/rubygem-psych/rubygem-psych.spec
  SPECS/rubygem-rdoc/remove_files_from_gitignore.patch
  SPECS/rubygem-rdoc/rubygem-rdoc.signatures.json
  SPECS/rubygem-rdoc/rubygem-rdoc.spec
  SPECS/rubygem-test-unit/rubygem-test-unit.signatures.json
  SPECS/rubygem-test-unit/rubygem-test-unit.spec
  cgmanifest.json
Labels: main

#2779 [main][SPECS-EXTENDED] Fixing `gspell`.
  SPECS-EXTENDED/enchant2/enchant2.signatures.json
  SPECS-EXTENDED/enchant2/enchant2.spec
  SPECS-EXTENDED/enchant2/enchant_aspell.patch
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#2778 Add gnupg2 chkconfig newt lang packages to toolchain resources manifests
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/resources/manifests/package/update_manifests.sh
Labels: main

#2690 Generate marketplace gen2 ARM image
  toolkit/imageconfigs/marketplace-gen2-aarch64.json
Labels: Schema, 1.0-dev

#2790 [main] [CVEs] Fix libtiff build break
  SPECS/libtiff/libtiff.spec
Labels: Packaging, main

#2746 kernel: Address CVE-2022-1055, CVE-2022-27666, CVE-2022-0955, CVE-2021-44879
  SPECS/kernel/CVE-2021-44879.nopatch
  SPECS/kernel/CVE-2022-0955.nopatch
  SPECS/kernel/CVE-2022-1055.nopatch
  SPECS/kernel/CVE-2022-27666.nopatch
  SPECS/kernel/kernel.spec
Labels: Packaging, 1.0-dev

#2749 rsync: Address CVE-2020-14387
  SPECS/rsync/CVE-2020-14387.patch
  SPECS/rsync/rsync.spec
Labels: Packaging, main

#2788 [main] Build break workaround.
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
Labels: Tools, main

#2784 [1.0] Upgrade vsftpd to 3.0.5 to fix CVE-2021-3618
  SPECS/vsftpd/vsftpd.signatures.json
  SPECS/vsftpd/vsftpd.spec
  cgmanifest.json
Labels: 1.0-dev

#2791 mandeepsplaha/nodejs update
  SPECS/nodejs/nodejs.signatures.json
  SPECS/nodejs/nodejs.spec
  cgmanifest.json
Labels: main

#2773 pango: bump version to 1.45.5 to address CVE-2019-1010238
  SPECS/pango/0001-skip-tests-which-are-known-to-fail.patch
  SPECS/pango/pango.signatures.json
  SPECS/pango/pango.spec
  cgmanifest.json
Labels: security, Packaging, main

#2799 Remove Powershell
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/powershell/powershell.signatures.json
  SPECS/powershell/powershell.spec
  cgmanifest.json
Labels: main

#2792 [main] Reenable systemd hardening flags in logrotate
  SPECS/logrotate/logrotate.spec
Labels: Packaging, main

#2803 pycairo: Upgrade to 1.21.0
  SPECS/pycairo/pycairo.signatures.json
  SPECS/pycairo/pycairo.spec
  cgmanifest.json
Labels: main

#2804 Add provides in rubygems to fix build failure
  SPECS/rubygem-bigdecimal/rubygem-bigdecimal.spec
  SPECS/rubygem-concurrent-ruby/rubygem-concurrent-ruby.spec
  SPECS/rubygem-io-console/rubygem-io-console.spec
  SPECS/rubygem-json/rubygem-json.spec
  SPECS/rubygem-minitest/rubygem-minitest.spec
  SPECS/rubygem-mocha/rubygem-mocha.spec
  SPECS/rubygem-openssl/rubygem-openssl.spec
  SPECS/rubygem-power_assert/rubygem-power_assert.spec
  SPECS/rubygem-psych/rubygem-psych.spec
  SPECS/rubygem-rdoc/rubygem-rdoc.spec
  SPECS/rubygem-test-unit/rubygem-test-unit.spec
Labels: Packaging, main

#2800 [main] back out change in #2792
  SPECS/logrotate/logrotate.spec
Labels: Packaging, main

#2811 [1.0] busybox patch CVE-2022-28391
  SPECS/busybox/CVE-2022-28391.patch
  SPECS/busybox/busybox.spec
Labels: Packaging, 1.0-dev

#2808 avahi: Upgrade to 0.8, fix CVE-2017-6519, CVE-2021-3468, CVE-2021-3502, CVE-2021-26720
  SPECS/avahi/0001-Add-support-to-advertise-local-services-localhost-on.patch
  SPECS/avahi/CVE-2021-26720.nopatch
  SPECS/avahi/CVE-2021-3468.patch
  SPECS/avahi/CVE-2021-3502.patch
  SPECS/avahi/avahi-0.6.30-mono-libdir.patch
  SPECS/avahi/avahi.signatures.json
  SPECS/avahi/avahi.spec
  cgmanifest.json
Labels: main

#2805 Patch cpio to fix CVE-2021-38185
  SPECS/cpio/CVE-2021-38185.patch
  SPECS/cpio/cpio.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, main

#2813 firewalld: Drop package obsoletes/conflicts that don't apply to Mariner
  SPECS/firewalld/firewalld.spec
Labels: Packaging, main

#2801 numpy: Upgrade to 1.22.3
  SPECS/numpy/numpy.signatures.json
  SPECS/numpy/numpy.spec
  cgmanifest.json
Labels: main

#2815 [1.0] Patch lua CVE-2022-28805
  SPECS/lua/CVE-2020-15889.nopatch
  SPECS/lua/CVE-2020-24342.nopatch
  SPECS/lua/CVE-2021-43519.nopatch
  SPECS/lua/CVE-2022-28805.patch
  SPECS/lua/lua.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#2797 graphite2: add an explicit BR on `pip` to enable ptest
  SPECS-EXTENDED/graphite2/graphite2.spec
Labels: ptest, main, specs-extended

#2794 javapackages-tools-meata: cleanup signature file
  SPECS-EXTENDED/javapackages-tools-meta/javapackages-tools-meta.signatures.json
Labels: main, specs-extended

#2796 convmv: add an explicit BR on `perl(File::Find)` to enable ptest
  SPECS-EXTENDED/convmv/convmv.spec
Labels: ptest, main, specs-extended

#2814 Patch binutils to fix CVE-2021-45078
  SPECS/binutils/CVE-2021-45078.patch
  SPECS/binutils/binutils.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#2798 glm: skip `test-core_func_integer` to enable ptest
  SPECS-EXTENDED/glm/glm.spec
Labels: ptest, main, specs-extended

#2821 perl-B-Debug: add an explicit BR on `perl(deprecate)` to enable ptest
  SPECS-EXTENDED/perl-B-Debug/perl-B-Debug.spec
Labels: ptest, main, specs-extended

#2819 nbdkit: avoid non-zero exit from `%check` section
  SPECS-EXTENDED/nbdkit/nbdkit.spec
Labels: ptest, main, specs-extended

#2820 python-xmltodict: add an explicit BR on `pip` to enable ptest
  SPECS-EXTENDED/python-xmltodict/python-xmltodict.spec
Labels: ptest, main, specs-extended

#2817 [1.0] Update rubygem-yajl-ruby to 1.4.2 for CVE-2022-24795
  SPECS/rubygem-yajl-ruby/rubygem-yajl-ruby.signatures.json
  SPECS/rubygem-yajl-ruby/rubygem-yajl-ruby.spec
  cgmanifest.json
Labels: 1.0-dev

#2807 ncurses: Patch CVE-2021-39537
  SPECS/ncurses/CVE-2021-39537.patch
  SPECS/ncurses/ncurses.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/toolchain-remote-wget-list
Labels: main

#2780 [main] Update Unattended ISO Build Instruction
  toolkit/docs/building/building.md
  toolkit/docs/formats/imageconfig.md
  toolkit/imageconfigs/core-legacy-unattended-hyperv.json
Labels: main

#2809 Fix rubygem-rspec failure, add rubygems hpricot and rake-compiler back
  SPECS-EXTENDED/rubygem-hpricot/rubygem-hpricot.signatures.json
  SPECS-EXTENDED/rubygem-hpricot/rubygem-hpricot.spec
  SPECS-EXTENDED/rubygem-rake-compiler/rubygem-rake-compiler.signatures.json
  SPECS-EXTENDED/rubygem-rake-compiler/rubygem-rake-compiler.spec
  SPECS-EXTENDED/rubygem-rspec/rubygem-rspec.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#2806 Add `libsafec` packages to Mariner
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/libsafec/libsafec.signatures.json
  SPECS/libsafec/libsafec.spec
  cgmanifest.json
Labels: Packaging, main

#2709 Simplify OpenSSH Systemd triggers
  SPECS/openssh/blfs_systemd_fixes.patch
  SPECS/openssh/openssh.signatures.json
  SPECS/openssh/openssh.spec
Labels: Packaging, main

#2829 avahi: Add patch to fix pkgconfig requires generation on libevent
  SPECS/avahi/avahi-libevent-pc-fix.patch
  SPECS/avahi/avahi.spec
Labels: Packaging, main

#2782 change /etc/shadow permission to 000
  SPECS/shadow-utils/shadow-utils.spec
Labels: Packaging, main

#2748 Add dnf-automatic and check-restart
  .github/workflows/validate-cg-manifest.sh
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/check-restart/check-restart.service
  SPECS/check-restart/check-restart.sh
  SPECS/check-restart/check-restart.signatures.json
  SPECS/check-restart/check-restart.spec
  SPECS/check-restart/check-restart.timer
  SPECS/dnf/dnf.spec
Labels: main

#2824 openssl: Nopatching CVE-2021-4160
  SPECS/openssl/CVE-2021-4160.nopatch
Labels: security, Packaging, main

#2835 Revert: Patch cpio to fix CVE-2021-38185
  SPECS/cpio/CVE-2021-38185.patch
  SPECS/cpio/cpio.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#2833 [main] rubygems: add hoe, stringio, update psych to v4.0.3, remove dev_deps from .gemspecs
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/rubygem-hoe/hoe.gemspec
  SPECS/rubygem-hoe/rubygem-hoe.signatures.json
  SPECS/rubygem-hoe/rubygem-hoe.spec
  SPECS/rubygem-mocha/remove-missing-devdeps.patch
  SPECS/rubygem-mocha/rubygem-mocha.spec
  SPECS/rubygem-power_assert/remove-missing-devdeps.patch
  SPECS/rubygem-power_assert/rubygem-power_assert.spec
  SPECS/rubygem-psych/rubygem-psych.signatures.json
  SPECS/rubygem-psych/rubygem-psych.spec
  SPECS/rubygem-stringio/rubygem-stringio.signatures.json
  SPECS/rubygem-stringio/rubygem-stringio.spec
  SPECS/rubygem-test-unit/remove-missing-devdeps.patch
  SPECS/rubygem-test-unit/rubygem-test-unit.spec
  cgmanifest.json
Labels: main

#2832 [main] Temporarily remove envoy from Mariner
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/envoy/0001-build-Use-Go-from-host.patch
  SPECS/envoy/0002-build-update-several-go-dependencies-11581.patch
  SPECS/envoy/0003-build-Add-explicit-requirement-on-rules_cc.patch
  SPECS/envoy/0004-build-Use-new-bazel.patch
  SPECS/envoy/0005-fix-gcc11-compiler-issue.patch
  SPECS/envoy/envoy-rpmlintrc
  SPECS/envoy/envoy.signatures.json
  SPECS/envoy/envoy.spec
  cgmanifest.json
Labels: main

#2818 sqlite: Address CVE-2021-36690
  SPECS/sqlite/CVE-2021-36690.patch
  SPECS/sqlite/sqlite.spec
  toolkit/.gitignore
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/Dockerfile
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
  toolkit/scripts/toolchain/create_toolchain_in_container.sh
Labels: Packaging, main
