Repository microsoft/azurelinux, pull requests merged in 2023-07, with the labels that each got.

#5767 revert: Remove umask handling from bash.spec and change it in filesytem.spec
  SPECS/bash/bash.spec
  SPECS/filesystem/filesystem.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5756 llvm: modify LLVM_PARALLEL_COMPILE_JOBS
  SPECS/llvm/llvm.spec
  SPECS/llvm/llvm16.spec
Labels: main

#5786 Fix bogus changelog times in filesystem and bash toolchain packages
  SPECS/bash/bash.spec
  SPECS/filesystem/filesystem.spec
Labels: main

#5764 Update NVIDIA ofa_kernel SPEC
  SPECS/mlnx-ofa_kernel/mlnx-ofa_kernel.signatures.json
  SPECS/mlnx-ofa_kernel/mlnx-ofa_kernel.spec
  cgmanifest.json
Labels: main

#5784 Patch CVE-2023-31486 in perl
  SPECS/perl/CVE-2023-31486.patch
  SPECS/perl/perl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, 1.0-dev

#5779 rust: Include clippy linter tool in package
  SPECS/rust/rust.spec
Labels: main

#5787 Adding nopatch for CVE-2022-28331 for apr package
  SPECS/apr/CVE-2022-28331.nopatch
  SPECS/apr/apr.spec
Labels: security, 1.0-dev

#5790 uclibc-ng: upgrade v1.0.41 -> v1.0.43 to address CVE-2022-29503
  SPECS/uclibc-ng/uclibc-ng.signatures.json
  SPECS/uclibc-ng/uclibc-ng.spec
  cgmanifest.json
Labels: security, main

#5791 Add new package rlwrap v0.46.1
  SPECS-EXTENDED/rlwrap/rlwrap.signatures.json
  SPECS-EXTENDED/rlwrap/rlwrap.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#5792 uclibc-ng: upgrade v1.0.41 -> v1.0.43 to address CVE-2022-29503
  SPECS/uclibc-ng/uclibc-ng.signatures.json
  SPECS/uclibc-ng/uclibc-ng.spec
  cgmanifest.json
Labels: security, 1.0-dev

#5778 add patches for cloud-init CVE-2022-2084, CVE-2023-1786
  SPECS/cloud-init/CVE-2022-2084.patch
  SPECS/cloud-init/CVE-2023-1786.patch
  SPECS/cloud-init/cloud-init.spec
Labels: security, 1.0-dev

#5793 Patch CVE-2023-2650 and CVE-2023-0465 in cloud-hypervisor
  SPECS/cloud-hypervisor/CVE-2023-0465.patch
  SPECS/cloud-hypervisor/CVE-2023-2650.patch
  SPECS/cloud-hypervisor/cloud-hypervisor.signatures.json
  SPECS/cloud-hypervisor/cloud-hypervisor.spec
Labels: security, 1.0-dev

#5801 Merge cloud-init fix into 1.0 branch
  SPECS/cloud-init/CVE-2022-2084.patch
  SPECS/cloud-init/CVE-2023-1786.patch
  SPECS/cloud-init/cloud-init.spec
Labels: security

#5747 KubeVirt: Add grace period for hotplug detach when hotplug pod is deleted
  SPECS/kubevirt/Hotplug_detach_grace_period.patch
  SPECS/kubevirt/kubevirt.spec
Labels: main

#5805 Patch CVE-2023-3138 for libX11
  SPECS/libX11/CVE-2023-3138.patch
  SPECS/libX11/libX11.spec
Labels: security, main

#5808 Fix strace's sockopt-sol_netlink test for kernel >= 5.15.116.1
  SPECS/strace/strace.spec
  SPECS/strace/testfix-landlock-brackets.patch
  SPECS/strace/testfix-netlink-list-memberships.patch
Labels: main

#5789 Add CONFIGs for Mellanox Bluefield SOC in ARM64
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/mariner-required-configs.json
Labels: security, main

#5595 Enable the graphpkgfetcher to pull build nodes from upstream repos if available V2
  toolkit/docs/building/building.md
  toolkit/scripts/incremental_building.mk
  toolkit/scripts/pkggen.mk
  toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
  toolkit/tools/internal/pkggraph/pkggraph.go
  toolkit/tools/internal/timestamp/timestamp_mgr.go
  toolkit/tools/scheduler/scheduler.go
  toolkit/tools/scheduler/schedulerutils/buildlist.go
  toolkit/tools/scheduler/schedulerutils/buildworker.go
  toolkit/tools/scheduler/schedulerutils/depsolver.go
  toolkit/tools/scheduler/schedulerutils/graphbuildstate.go
  toolkit/tools/scheduler/schedulerutils/initializegraph.go
  toolkit/tools/scheduler/schedulerutils/preparerequest.go
  toolkit/tools/scheduler/schedulerutils/printresults.go
Labels: Tools, main, DevEx

#5802 Add functionality to serve stale DNS records
  SPECS/systemd/serve-stale-0001-resolved-added-serve-stale-feature-implementation-of.patch
  SPECS/systemd/serve-stale-0002-resolved-Initialize-until_valid-while-storing-negati.patch
  SPECS/systemd/systemd.spec
Labels: main

#5810 Patch CVE-2022-25883 for nodejs18
  SPECS/nodejs/CVE-2022-25883-v18.patch
  SPECS/nodejs/nodejs18.spec
Labels: security, main

#5813 Filter implicit run nodes before passing to collapse.
  toolkit/docs/how_it_works/3_package_building.md
  toolkit/tools/depsearch/depsearch.go
  toolkit/tools/graphPreprocessor/graphPreprocessor.go
  toolkit/tools/graphanalytics/graphanalytics.go
  toolkit/tools/grapher/grapher.go
  toolkit/tools/internal/pkggraph/pkggraph.go
  toolkit/tools/internal/pkggraph/pkggraph_test.go
  toolkit/tools/scheduler/scheduler.go
  toolkit/tools/scheduler/schedulerutils/buildworker.go
  toolkit/tools/scheduler/schedulerutils/graphbuildstate.go
  toolkit/tools/scheduler/schedulerutils/implicitprovides.go
  toolkit/tools/scheduler/schedulerutils/preparerequest.go
  toolkit/tools/scheduler/schedulerutils/printresults.go
Labels: main

#5821 uclibc-ng: introduce patch to fix static build
  SPECS/uclibc-ng/0001-gettimeofday-fix-static-build.patch
  SPECS/uclibc-ng/uclibc-ng.spec
Labels: 1.0-dev

#5797 Upgrade cloud-init to 23.2
  SPECS/cloud-init/CVE-2023-1786.patch
  SPECS/cloud-init/cloud-init.signatures.json
  SPECS/cloud-init/cloud-init.spec
  cgmanifest.json
Labels: security, main

#5758 Bump nodejs to 16.20.1
  SPECS/nodejs/nodejs.signatures.json
  SPECS/nodejs/nodejs.spec
  cgmanifest.json
Labels: main

#5730 Add dnf5 package to Mariner 2.0
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/dnf5/dnf5.signatures.json
  SPECS/dnf5/dnf5.spec
  SPECS/librepo/librepo.signatures.json
  SPECS/librepo/librepo.spec
  SPECS/libsolv/libsolv.signatures.json
  SPECS/libsolv/libsolv.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/spec_source_attributions.py
Labels: main

#5752 Add python-resolvelib package to support ansible-galaxy
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/ansible/ansible.spec
  SPECS/python-resolvelib/python-resolvelib.signatures.json
  SPECS/python-resolvelib/python-resolvelib.spec
  cgmanifest.json
  toolkit/scripts/spec_source_attributions.py
Labels: main

#5823 Patch CVE-2022-25883 in nodejs v16
  SPECS/nodejs/CVE-2022-25883.patch
  SPECS/nodejs/nodejs.spec
Labels: security, main

#5781 Map the expected RPMs to specs in toolchain
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
Labels: Tools, main

#5719 Package cmake modules in grpc-devel
  SPECS/grpc/grpc.spec
Labels: main

#5829 Mariner 1.0 July Update
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/apr/CVE-2022-28331.nopatch
  SPECS/apr/apr.spec
  SPECS/cloud-hypervisor/CVE-2023-0465.patch
  SPECS/cloud-hypervisor/CVE-2023-2650.patch
  SPECS/cloud-hypervisor/cloud-hypervisor.signatures.json
  SPECS/cloud-hypervisor/cloud-hypervisor.spec
  SPECS/hyperv-daemons/hyperv-daemons.signatures.json
  SPECS/hyperv-daemons/hyperv-daemons.spec
  SPECS/kernel-headers/kernel-headers.signatures.json
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel-hyperv/config
  SPECS/kernel-hyperv/kernel-hyperv.signatures.json
  SPECS/kernel-hyperv/kernel-hyperv.spec
  SPECS/kernel/CVE-2023-3090.nopatch
  SPECS/kernel/CVE-2023-3212.nopatch
  SPECS/kernel/CVE-2023-3220.nopatch
  SPECS/kernel/CVE-2023-3355.nopatch
  SPECS/kernel/CVE-2023-3357.nopatch
  SPECS/kernel/CVE-2023-3358.nopatch
  SPECS/kernel/CVE-2023-3359.nopatch
  SPECS/kernel/CVE-2023-3439.nopatch
  SPECS/kernel/CVE-2023-35788.nopatch
  SPECS/kernel/CVE-2023-35823.nopatch
  SPECS/kernel/CVE-2023-35824.nopatch
  SPECS/kernel/CVE-2023-35829.nopatch
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  SPECS/libtiff/CVE-2022-48281.patch
  SPECS/libtiff/CVE-2023-0795.patch
  SPECS/libtiff/CVE-2023-2731.patch
  SPECS/libtiff/libtiff.signatures.json
  SPECS/libtiff/libtiff.spec
  SPECS/perl/CVE-2023-31486.patch
  SPECS/perl/perl.spec
  SPECS/uclibc-ng/0001-gettimeofday-fix-static-build.patch
  SPECS/uclibc-ng/uclibc-ng.signatures.json
  SPECS/uclibc-ng/uclibc-ng.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/Dockerfile
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
  toolkit/scripts/toolchain/container/toolchain_build_temp_tools.sh
Labels: security

#5827 build nginx with http_gunzip_module
  SPECS/nginx/nginx.spec
Labels: main

#5833 Update README.md
  README.md
Labels: main

#5830 Nopatch CVE-2023-23003
  SPECS/kernel/CVE-2023-23003.nopatch
Labels: security, main

#5795 glibc: restore glibc-debuginfo package
  SPECS-EXTENDED/buildah/buildah.spec
  SPECS-EXTENDED/catatonit/catatonit.spec
  SPECS-EXTENDED/dyninst/dyninst.spec
  SPECS-EXTENDED/podman/podman.spec
  SPECS/busybox/busybox.spec
  SPECS/flannel/flannel.spec
  SPECS/glibc/glibc.spec
  SPECS/kubevirt/kubevirt.spec
  SPECS/libguestfs/libguestfs.spec
  SPECS/rust/rust.spec
  SPECS/supermin/supermin.spec
  SPECS/tini/tini.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5817 Logging built toolchain RPMs.
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
Labels: Tools, main

#5814 Remove k3s from Mariner
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/k3s/k3s-1.24.12.signatures.json
  SPECS/k3s/k3s-1.24.12.spec
  SPECS/k3s/k3s-1.24.6.signatures.json
  SPECS/k3s/k3s-1.24.6.spec
  SPECS/k3s/k3s-1.25.8.signatures.json
  SPECS/k3s/k3s-1.25.8.spec
  SPECS/k3s/k3s.signatures.json
  SPECS/k3s/k3s.spec
  SPECS/k3s/vendor_build-1.24.12.patch
  SPECS/k3s/vendor_build-1.24.6.patch
  SPECS/k3s/vendor_build-1.25.8.patch
  SPECS/k3s/vendor_build.patch
  cgmanifest.json
  toolkit/scripts/spec_source_attributions.py
Labels: main

#5826 Adding new package opencsd 1.4.0
  SPECS-EXTENDED/opencsd/opencsd.signatures.json
  SPECS-EXTENDED/opencsd/opencsd.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#5843 Revert "Filter implicit run nodes before passing to collapse. (#5813)"
  toolkit/docs/how_it_works/3_package_building.md
  toolkit/tools/depsearch/depsearch.go
  toolkit/tools/graphPreprocessor/graphPreprocessor.go
  toolkit/tools/graphanalytics/graphanalytics.go
  toolkit/tools/grapher/grapher.go
  toolkit/tools/internal/pkggraph/pkggraph.go
  toolkit/tools/internal/pkggraph/pkggraph_test.go
  toolkit/tools/scheduler/scheduler.go
  toolkit/tools/scheduler/schedulerutils/buildworker.go
  toolkit/tools/scheduler/schedulerutils/graphbuildstate.go
  toolkit/tools/scheduler/schedulerutils/implicitprovides.go
  toolkit/tools/scheduler/schedulerutils/preparerequest.go
  toolkit/tools/scheduler/schedulerutils/printresults.go
Labels: main

#5844 Revert "Enable the graphpkgfetcher to pull build nodes from upstream..."
  toolkit/docs/building/building.md
  toolkit/scripts/incremental_building.mk
  toolkit/scripts/pkggen.mk
  toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
  toolkit/tools/internal/pkggraph/pkggraph.go
  toolkit/tools/internal/timestamp/timestamp_mgr.go
  toolkit/tools/scheduler/scheduler.go
  toolkit/tools/scheduler/schedulerutils/buildlist.go
  toolkit/tools/scheduler/schedulerutils/buildworker.go
  toolkit/tools/scheduler/schedulerutils/depsolver.go
  toolkit/tools/scheduler/schedulerutils/graphbuildstate.go
  toolkit/tools/scheduler/schedulerutils/initializegraph.go
  toolkit/tools/scheduler/schedulerutils/preparerequest.go
  toolkit/tools/scheduler/schedulerutils/printresults.go
Labels: main

#5845 Revert "Fixed the `PACKAGE_CACHE_SUMMARY` build option. (#5744)"
  toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
  toolkit/tools/imagepkgfetcher/imagepkgfetcher.go
  toolkit/tools/internal/packagerepo/repocloner/repocloner.go
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
  toolkit/tools/internal/packagerepo/repoutils/repoutils.go
  toolkit/tools/internal/rpm/rpm.go
  toolkit/tools/internal/rpm/rpm_test.go
  toolkit/tools/internal/rpm/testdata/no_default_package.spec
  toolkit/tools/internal/rpm/testdata/with_epoch.spec
Labels: main

#5842 Add upstream patch for CVE-2023-35945 in nghttp2
  SPECS/nghttp2/CVE-2023-35945.patch
  SPECS/nghttp2/nghttp2.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, main

#5839 Upgrade Blobfuse2 to 2.0.4
  SPECS/blobfuse2/blobfuse2.signatures.json
  SPECS/blobfuse2/blobfuse2.spec
  cgmanifest.json
Labels: main

#5783 Extended PR checks with package builds and ptests.
  .pipelines/prchecks/PackageBuildPRCheck.yml
  .pipelines/templates/PackageBuild.yml
  .pipelines/templates/RawToolchainDownload.yml
  .pipelines/templates/ToolchainBuild.yml
  .pipelines/templates/ToolkitCheck.yml
Labels: main

#5849 Restored "Fixed the `PACKAGE_CACHE_SUMMARY` build option. (#5744)"
  toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
  toolkit/tools/imagepkgfetcher/imagepkgfetcher.go
  toolkit/tools/internal/packagerepo/repocloner/repocloner.go
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
  toolkit/tools/internal/packagerepo/repoutils/repoutils.go
  toolkit/tools/internal/rpm/rpm.go
  toolkit/tools/internal/rpm/rpm_test.go
  toolkit/tools/internal/rpm/testdata/no_default_package.spec
  toolkit/tools/internal/rpm/testdata/with_epoch.spec
Labels: main

#5852 Revert "Add CONFIGs for Mellanox Bluefield SOC in ARM64 (#5789)"
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/mariner-required-configs.json
Labels: main

#5853 hyperv-daemons: add nopatch for CVE-2023-1989, CVE-2023-1998, CVE-2023-21102, CVE-2023-25012, CVE-2023-3359
  SPECS/hyperv-daemons/CVE-2023-1989.nopatch
  SPECS/hyperv-daemons/CVE-2023-1998.nopatch
  SPECS/hyperv-daemons/CVE-2023-21102.nopatch
  SPECS/hyperv-daemons/CVE-2023-25012.nopatch
  SPECS/hyperv-daemons/CVE-2023-3359.nopatch
Labels: security, main

#5850 Nopatch kernel for CVE-2023-21102, CVE-2023-32250, CVE-2023-32254
  SPECS/kernel/CVE-2023-21102.nopatch
  SPECS/kernel/CVE-2023-32250.nopatch
  SPECS/kernel/CVE-2023-32254.nopatch
Labels: security, main

#5800 rpm: change default binary compression to zstd
  SPECS/mariner-rpm-macros/macros
  SPECS/mariner-rpm-macros/mariner-rpm-macros.signatures.json
  SPECS/mariner-rpm-macros/mariner-rpm-macros.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5742 Updated tooling to use Golang 1.19.
  .github/workflows/check-livepatches.yml
  .github/workflows/check-package-cgmanifest.yml
  .github/workflows/go-test-coverage.yml
  .github/workflows/quickstart_1.0.yml
  .github/workflows/quickstart_2.0.yml
  toolkit/tools/go.mod
  toolkit/tools/go.sum
  toolkit/tools/internal/pkggraph/pkggraph.go
  toolkit/tools/internal/rpm/rpm.go
  toolkit/tools/internal/sliceutils/sliceutils.go
  toolkit/tools/internal/sliceutils/sliceutils_test.go
  toolkit/tools/scheduler/schedulerutils/buildlist.go
  toolkit/tools/scheduler/schedulerutils/buildworker.go
  toolkit/tools/scheduler/schedulerutils/graphbuildstate.go
Labels: Tools, main

#5851 Restored "Enable the graphpkgfetcher to pull build nodes from upstream repos if available V2"
  toolkit/docs/building/building.md
  toolkit/scripts/incremental_building.mk
  toolkit/scripts/pkggen.mk
  toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
  toolkit/tools/internal/pkggraph/pkggraph.go
  toolkit/tools/internal/timestamp/timestamp_mgr.go
  toolkit/tools/scheduler/scheduler.go
  toolkit/tools/scheduler/schedulerutils/buildlist.go
  toolkit/tools/scheduler/schedulerutils/buildworker.go
  toolkit/tools/scheduler/schedulerutils/depsolver.go
  toolkit/tools/scheduler/schedulerutils/graphbuildstate.go
  toolkit/tools/scheduler/schedulerutils/initializegraph.go
  toolkit/tools/scheduler/schedulerutils/preparerequest.go
  toolkit/tools/scheduler/schedulerutils/printresults.go
Labels: main

#5858 Restored "Filter implicit run nodes before passing to collapse. (#5813)"
  toolkit/docs/how_it_works/3_package_building.md
  toolkit/tools/depsearch/depsearch.go
  toolkit/tools/graphPreprocessor/graphPreprocessor.go
  toolkit/tools/graphanalytics/graphanalytics.go
  toolkit/tools/grapher/grapher.go
  toolkit/tools/internal/pkggraph/pkggraph.go
  toolkit/tools/internal/pkggraph/pkggraph_test.go
  toolkit/tools/scheduler/scheduler.go
  toolkit/tools/scheduler/schedulerutils/buildworker.go
  toolkit/tools/scheduler/schedulerutils/graphbuildstate.go
  toolkit/tools/scheduler/schedulerutils/implicitprovides.go
  toolkit/tools/scheduler/schedulerutils/preparerequest.go
  toolkit/tools/scheduler/schedulerutils/printresults.go
Labels: main

#5854 Address CVE-2023-32250, CVE-2023-32254 with nopatches
  SPECS/kernel/CVE-2023-32250.nopatch
  SPECS/kernel/CVE-2023-32254.nopatch
Labels: security, 1.0-dev

#5869 Nopatch kernel cves: CVE-2022-41848, CVE-2022-44032, CVE-2022-44033, CVE-2022-44034, CVE-2022-45887, CVE-2022-45888, CVE-2022-45919, CVE-2022-48502, CVE-2023-0469, CVE-2023-0615, CVE-2023-2124, CVE-2023-28464, CVE-2023-28866, CVE-2023-3268, CVE-2023-3269, CVE-2023-3389, CVE-2023-35826, CVE-2023-35828
  SPECS/kernel/CVE-2022-41848.nopatch
  SPECS/kernel/CVE-2022-44032.nopatch
  SPECS/kernel/CVE-2022-44033.nopatch
  SPECS/kernel/CVE-2022-44034.nopatch
  SPECS/kernel/CVE-2022-45887.nopatch
  SPECS/kernel/CVE-2022-45888.nopatch
  SPECS/kernel/CVE-2022-45919.nopatch
  SPECS/kernel/CVE-2022-48502.nopatch
  SPECS/kernel/CVE-2023-0469.nopatch
  SPECS/kernel/CVE-2023-0615.nopatch
  SPECS/kernel/CVE-2023-2124.nopatch
  SPECS/kernel/CVE-2023-28464.nopatch
  SPECS/kernel/CVE-2023-28866.nopatch
  SPECS/kernel/CVE-2023-3268.nopatch
  SPECS/kernel/CVE-2023-3269.nopatch
  SPECS/kernel/CVE-2023-3389.nopatch
  SPECS/kernel/CVE-2023-35826.nopatch
  SPECS/kernel/CVE-2023-35828.nopatch
Labels: security, 1.0-dev

#5868 Nopatch kernel CVE-2022-41848, CVE-2022-44032, CVE-2022-44033, CVE-2022-44034, CVE-2022-45887, CVE-2022-45888, CVE-2022-45919, CVE-2023-0469, CVE-2023-0615, CVE-2023-2124, CVE-2023-28464, CVE-2023-28866, CVE-2023-3268, CVE-2023-3269, CVE-2023-3389, CVE-2023-3390, CVE-2023-35826, CVE-2023-35828
  SPECS/kernel/CVE-2022-41848.nopatch
  SPECS/kernel/CVE-2022-44032.nopatch
  SPECS/kernel/CVE-2022-44033.nopatch
  SPECS/kernel/CVE-2022-44034.nopatch
  SPECS/kernel/CVE-2022-45887.nopatch
  SPECS/kernel/CVE-2022-45888.nopatch
  SPECS/kernel/CVE-2022-45919.nopatch
  SPECS/kernel/CVE-2023-0469.nopatch
  SPECS/kernel/CVE-2023-0615.nopatch
  SPECS/kernel/CVE-2023-2124.nopatch
  SPECS/kernel/CVE-2023-28464.nopatch
  SPECS/kernel/CVE-2023-28866.nopatch
  SPECS/kernel/CVE-2023-3268.nopatch
  SPECS/kernel/CVE-2023-3269.nopatch
  SPECS/kernel/CVE-2023-3389.nopatch
  SPECS/kernel/CVE-2023-3390.nopatch
  SPECS/kernel/CVE-2023-35826.nopatch
  SPECS/kernel/CVE-2023-35828.nopatch
Labels: security, main

#5864 Update delta paths prior to implicit handling
  toolkit/tools/scheduler/scheduler.go
Labels: main

#5877 Nopatch kernel CVE-2022-45884 and CVE-2022-45886
  SPECS/kernel/CVE-2022-45884.nopatch
  SPECS/kernel/CVE-2022-45886.nopatch
Labels: security, main

#5878 Nopatch kernel CVE-2023-1295, CVE-2022-45884, and CVE-2022-45886
  SPECS/kernel/CVE-2022-45884.nopatch
  SPECS/kernel/CVE-2022-45886.nopatch
  SPECS/kernel/CVE-2023-1295.nopatch
Labels: security, 1.0-dev

#5841 Add shortest path print of unsolvable nodes when using trace level logging
  toolkit/scripts/tools.mk
  toolkit/tools/scheduler/schedulerutils/depsolver.go
  toolkit/tools/scheduler/schedulerutils/implicitprovides.go
Labels: main

#5888 Removing prometheus from prometheus-adapter and making separate *-docs packages
  SPECS/prometheus-adapter/prometheus-adapter.spec
  SPECS/prometheus/prometheus.spec
Labels: main

#5889 Fixes openssh CVE-2023-38408 and Update openssh to 8.9p1
  SPECS/openssh/CVE-2023-38408.patch
  SPECS/openssh/openssh.signatures.json
  SPECS/openssh/openssh.spec
  cgmanifest.json
Labels: security, main

#5880 Patch CVE-2023-2828 in bind
  SPECS/bind/CVE-2023-2828.patch
  SPECS/bind/bind.spec
Labels: security, main

#5882 Patch CVE-2023-2828 in bind
  SPECS/bind/CVE-2023-2828.patch
  SPECS/bind/bind.spec
Labels: security, 1.0-dev

#5893 Fix openssh CVE-2023-38408
  SPECS/openssh/CVE-2023-38408.patch
  SPECS/openssh/openssh.spec
Labels: security, 1.0-dev

#5816 Update kata-containers-cc to 0.6.0
  SPECS/kata-containers-cc/0001-Enable-using-an-igvm-file-with-cloud-hypervisor.patch
  SPECS/kata-containers-cc/kata-containers-cc.signatures.json
  SPECS/kata-containers-cc/kata-containers-cc.spec
  cgmanifest.json
Labels: main

#5900 Disabled extended ACLs for the `build` directory.
  toolkit/scripts/tools.mk
Labels: main

#5901 Fixed `ob_artifactBaseName` for RPM builds inside `PackageBuildPRCheck.yml`.
  .pipelines/prchecks/PackageBuildPRCheck.yml
Labels: main

#5765 Tweak behavior of kernel-mshv initrd; let it remain in /boot.
  SPECS/initramfs/initramfs.spec
Labels: main

#5885 kernel-hci: Add net/mlx5 patch (27) switching warn message to debug
  SPECS-SIGNED/kernel-hci-signed/kernel-hci-signed.spec
  SPECS/kernel-hci/0028-net-mlx5-Bridge-use-debug-not-warn-if-entry-not-found.patch
  SPECS/kernel-hci/kernel-hci.spec
Labels: main

#5910 Nopatch kernel for CVE-2023-38427, CVE-2023-38430, and CVE-2023-38431
  SPECS/kernel/CVE-2023-38427.nopatch
  SPECS/kernel/CVE-2023-38430.nopatch
  SPECS/kernel/CVE-2023-38431.nopatch
Labels: security, main

#5911 Nopatch kernel for CVE-2023-38426, CVE-2023-38427, CVE-2023-38428, CVE-2023-38429, CVE-2023-38430, CVE-2023-38431, CVE-2023-38432
  SPECS/kernel/CVE-2023-38426.nopatch
  SPECS/kernel/CVE-2023-38427.nopatch
  SPECS/kernel/CVE-2023-38428.nopatch
  SPECS/kernel/CVE-2023-38429.nopatch
  SPECS/kernel/CVE-2023-38430.nopatch
  SPECS/kernel/CVE-2023-38431.nopatch
  SPECS/kernel/CVE-2023-38432.nopatch
Labels: security, 1.0-dev
