Repository microsoft/azurelinux, pull requests merged in 2023-10, with the labels that each got.

#6322 kernel: nopatch CVE-2023-4921
  SPECS/kernel/CVE-2023-4921.nopatch
  SPECS/kernel/kernel.spec
Labels: main

#6323 Image customizer: Implement `PostInstallScripts` and `FinalizeImageScripts`.
  toolkit/tools/imagecustomizerapi/script.go
  toolkit/tools/imagecustomizerapi/systemconfig.go
  toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
  toolkit/tools/pkg/imagecustomizerlib/testdata/runscripts-config.yaml
  toolkit/tools/pkg/imagecustomizerlib/testdata/scripts/finalizeimagescript.sh
  toolkit/tools/pkg/imagecustomizerlib/testdata/scripts/postinstallscript.sh
Labels: main

#6325 Image Customizer: Support Hostname
  toolkit/tools/imagecustomizerapi/systemconfig.go
  toolkit/tools/imagecustomizerapi/systemconfig_test.go
  toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
  toolkit/tools/pkg/imagecustomizerlib/customizeutils_test.go
Labels: main

#6331 Added explicit BR on `libxslt-devel` to `xmlsec1.spec`.
  SPECS/xmlsec1/xmlsec1.spec
Labels: main

#6332 Add mkconfig-based template to iso installer manifest
  toolkit/resources/imageconfigs/iso_initrd.json
  toolkit/resources/imageconfigs/iso_initrd_arm64.json
Labels: main

#6267 libsprio: upgrade version 20190731 -> 20221101 to address CVE-2019-19847
  SPECS-EXTENDED/libspiro/libspiro.signatures.json
  SPECS-EXTENDED/libspiro/libspiro.spec
  cgmanifest.json
Labels: security, main, specs-extended

#6337 Update read-only-root-efi.json to remove demo credentials
  toolkit/imageconfigs/read-only-root-efi.json
Labels: main

#6338 Mandeepsplaha/patch cves against gdb
  SPECS-EXTENDED/buildah/buildah.spec
  SPECS-EXTENDED/catatonit/catatonit.spec
  SPECS-EXTENDED/dyninst/dyninst.spec
  SPECS-EXTENDED/podman/podman.spec
  SPECS/busybox/busybox.spec
  SPECS/flannel/flannel.spec
  SPECS/glibc/CVE-2023-4911.patch
  SPECS/glibc/glibc.spec
  SPECS/kubevirt/kubevirt.spec
  SPECS/libguestfs/libguestfs.spec
  SPECS/rust/rust.spec
  SPECS/supermin/supermin.spec
  SPECS/tini/tini.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#6162 Add new package hping3 - 0.0.20051105
  SPECS-EXTENDED/hping3/hping3-20051105-typo.patch
  SPECS-EXTENDED/hping3/hping3-bytesex.patch
  SPECS-EXTENDED/hping3/hping3-cflags.patch
  SPECS-EXTENDED/hping3/hping3-common.patch
  SPECS-EXTENDED/hping3/hping3-getifnamedebug.patch
  SPECS-EXTENDED/hping3/hping3-include.patch
  SPECS-EXTENDED/hping3/hping3-man.patch
  SPECS-EXTENDED/hping3/hping3.signatures.json
  SPECS-EXTENDED/hping3/hping3.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#6335 Add patch for Bluez CVE-2022-3563
  SPECS/bluez/CVE-2022-3563.patch
  SPECS/bluez/bluez.spec
Labels: security, main

#6293 Make rpms-snapshot run faster
  toolkit/tools/internal/rpm/rpm.go
  toolkit/tools/pkg/rpmssnapshot/rpmssnapshot.go
Labels: main

#6342 Only query precacher repos if one is passed in
  toolkit/scripts/precache.mk
  toolkit/tools/precacher/precacher.go
Labels: main

#6336 Image Customizer: Add/update users.
  toolkit/tools/imagecustomizerapi/systemconfig.go
  toolkit/tools/imagecustomizerapi/user.go
  toolkit/tools/imagecustomizerapi/utils.go
  toolkit/tools/imagegen/configuration/user.go
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/internal/userutils/userutils.go
  toolkit/tools/internal/userutils/userutils_test.go
  toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
  toolkit/tools/pkg/imagecustomizerlib/testdata/addusers-config.yaml
Labels: main

#6289 Removed `exit` from specs' `%check` sections.
  SPECS-EXTENDED/virt-p2v/virt-p2v.spec
  SPECS/attr/attr.spec
  SPECS/checksec/checksec.spec
  SPECS/edk2/edk2.spec
  SPECS/gcc/gcc.spec
  SPECS/gfs2-utils/gfs2-utils.spec
  SPECS/hivex/hivex.spec
  SPECS/libepoxy/libepoxy.spec
  SPECS/libisoburn/libisoburn.spec
  SPECS/openssl-pkcs11/openssl-pkcs11.spec
  SPECS/virt-what/virt-what.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#6315 Fixing `debugedit` ptests
  SPECS/debugedit/BUG-28161.patch
  SPECS/debugedit/debugedit.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: ptest, main

#6353 Image Customizer: Add to Makefile.
  toolkit/scripts/tools.mk
Labels: Tools, main

#6340 Fix kernel CVE detection issue due to bad date order in changelog
  SPECS/kernel/kernel.spec
Labels: main

#6345 re-add kubernetes in CBL-Mariner
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/coredns/coredns-1.8.0.signatures.json
  SPECS/coredns/coredns-1.8.0.spec
  SPECS/coredns/coredns-1.8.4.signatures.json
  SPECS/coredns/coredns-1.8.4.spec
  SPECS/coredns/coredns-1.8.6.signatures.json
  SPECS/coredns/coredns-1.8.6.spec
  SPECS/coredns/coredns-1.9.3.signatures.json
  SPECS/coredns/coredns.signatures.json
  SPECS/coredns/coredns.spec
  SPECS/coredns/makefile-buildoption-commitnb-1.9.patch
  SPECS/coredns/makefile-buildoption-commitnb.patch
  SPECS/etcd/CVE-2021-28235.patch
  SPECS/etcd/CVE-2023-32082-v3.5.0.patch
  SPECS/etcd/CVE-2023-32082-v3.5.3.patch
  SPECS/etcd/CVE-2023-32082.patch
  SPECS/etcd/etcd-3.5.0.signatures.json
  SPECS/etcd/etcd-3.5.1.signatures.json
  SPECS/etcd/etcd-3.5.1.spec
  SPECS/etcd/etcd-3.5.3.signatures.json
  SPECS/etcd/etcd-3.5.3.spec
  SPECS/etcd/etcd-3.5.4.signatures.json
  SPECS/etcd/etcd-3.5.4.spec
  SPECS/etcd/etcd-3.5.5.signatures.json
  SPECS/etcd/etcd-3.5.5.spec
  SPECS/etcd/etcd-3.5.6.signatures.json
  SPECS/etcd/etcd-3.5.6.spec
  SPECS/etcd/etcd.signatures.json
  SPECS/etcd/etcd.spec
  SPECS/kubernetes/CVE-2020-8554.nopatch
  SPECS/kubernetes/kubelet.service
  SPECS/kubernetes/kubernetes.signatures.json
  SPECS/kubernetes/kubernetes.spec
  cgmanifest.json
  toolkit/scripts/license_map.py
Labels: main

#6348 Updated Ubuntu requirements doc with better Golang instructions.
  toolkit/docs/building/prerequisites-ubuntu.md
  toolkit/tools/go.mod
Labels: main

#6318 cloud-init modify running order of modules
  toolkit/imageconfigs/additionalconfigs/cloud-init.cfg
Labels: main

#6341 add patches for Glibc CVE-2023-4806 and CVE-2023-5156
  SPECS-EXTENDED/buildah/buildah.spec
  SPECS-EXTENDED/catatonit/catatonit.spec
  SPECS-EXTENDED/dyninst/dyninst.spec
  SPECS-EXTENDED/podman/podman.spec
  SPECS/busybox/busybox.spec
  SPECS/flannel/flannel.spec
  SPECS/glibc/CVE-2023-4806.patch
  SPECS/glibc/CVE-2023-5156.patch
  SPECS/glibc/glibc.spec
  SPECS/kubevirt/kubevirt.spec
  SPECS/libguestfs/libguestfs.spec
  SPECS/rust/rust.spec
  SPECS/supermin/supermin.spec
  SPECS/tini/tini.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#6364 Bump kubernetes release to rebuild against glibc 2.35-6
  SPECS/kubernetes/kubernetes.spec
Labels: main

#6355 Revert "Damcilva/2.0/tools/add scheduler stuck debug code"
  toolkit/tools/scheduler/scheduler.go
Labels: main

#6359 Patch irqbalance to fix incorrect balancing behavior
  SPECS/irqbalance/fix-load-unsigned-overflow.patch
  SPECS/irqbalance/irqbalance.spec
Labels: main

#6344 Image Customizer: Add/remove packages
  toolkit/tools/go.mod
  toolkit/tools/go.sum
  toolkit/tools/imagecustomizer/main.go
  toolkit/tools/imagecustomizerapi/packagelist.go
  toolkit/tools/imagecustomizerapi/systemconfig.go
  toolkit/tools/internal/packagerepo/repomanager/rpmrepomanager/rpmrepomanager.go
  toolkit/tools/pkg/imagecustomizerlib/customizepackages.go
  toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
  toolkit/tools/pkg/imagecustomizerlib/rpmsourcesmounts.go
  toolkit/tools/pkg/imagecustomizerlib/testdata/lists/dracut-fips.yaml
  toolkit/tools/pkg/imagecustomizerlib/testdata/updatepackages-config.yaml
Labels: main

#6377 Patched `vim` for CVE-2023-5344 (CP of #6372)
  SPECS/vim/CVE-2023-5344.patch
  SPECS/vim/vim.spec
Labels: security, main

#6357 Image Customizer: Enable/disable services.
  toolkit/tools/imagecustomizerapi/service.go
  toolkit/tools/imagecustomizerapi/systemconfig.go
  toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
  toolkit/tools/pkg/imagecustomizerlib/testdata/services-config.yaml
Labels: main

#6248 Unify behavior of `USE_PREVIEW_REPO` on url and repo lists
  toolkit/Makefile
  toolkit/docs/building/building.md
Labels: Tools, main

#6099 Libcgroup create drop file folder
  SPECS/libcgroup/libcgroup.spec
Labels: main

#6385 Image Customizer: Add `Config` struct.
  toolkit/tools/imagecustomizerapi/config.go
  toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
  toolkit/tools/pkg/imagecustomizerlib/testdata/addfiles-config.yaml
  toolkit/tools/pkg/imagecustomizerlib/testdata/addusers-config.yaml
  toolkit/tools/pkg/imagecustomizerlib/testdata/runscripts-config.yaml
  toolkit/tools/pkg/imagecustomizerlib/testdata/services-config.yaml
  toolkit/tools/pkg/imagecustomizerlib/testdata/updatepackages-config.yaml
Labels: main

#6394 Update rust.spec to use ./x.py instead of x.py
  SPECS/rust/rust.spec
Labels: main

#6402 Revert "Fixing `debugedit` ptests (#6315)"
  SPECS/debugedit/BUG-28161.patch
  SPECS/debugedit/debugedit.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#6378 fix: make /media a directory
  SPECS/filesystem/filesystem.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#6403 Update nghttp2 to version 1.57.0 to fix CVE-2023-44487
  SPECS/nghttp2/CVE-2023-35945.patch
  SPECS/nghttp2/nghttp2.signatures.json
  SPECS/nghttp2/nghttp2.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#6311 Add /opt/containerd/{bin,lib} to RPMs and cherry-pick fix for systemd-hostnamed default-hostname in SELinux.
  SPECS/filesystem/filesystem.spec
  SPECS/moby-containerd/moby-containerd.spec
  SPECS/selinux-policy/0040-For-systemd-hostnamed-service-to-run.patch
  SPECS/selinux-policy/selinux-policy.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#6414 Toolkit: Use test short mode flag.
  toolkit/scripts/tools.mk
  toolkit/tools/pkg/imagecustomizerlib/customizeutils_test.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
Labels: main

#6410 Patched CVE-2023-38545, CVE-2023-38546 for `cmake` and `curl`. (CP of #6401)
  SPECS/cmake/CVE-2023-38545.patch
  SPECS/cmake/CVE-2023-38546.patch
  SPECS/cmake/cmake.spec
  SPECS/curl/CVE-2023-38545.patch
  SPECS/curl/CVE-2023-38546.patch
  SPECS/curl/curl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#6415 Patched `python` CVE-2023-24329 (CP of #6412)
  SPECS/python3/CVE-2023-24329.patch
  SPECS/python3/python3.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#6407 upgrade cloud-init to 23.3
  SPECS/cloud-init/cloud-init.signatures.json
  SPECS/cloud-init/cloud-init.spec
  SPECS/cloud-init/testGetInterfacesUnitTest.patch
  cgmanifest.json
Labels: main

#6416 Patch urllib3 CVE-2023-43804
  SPECS/python-urllib3/CVE-2023-43804.patch
  SPECS/python-urllib3/python-urllib3.spec
Labels: main

#6274 Adding package rust-cbindgen 0.24.3
  SPECS-EXTENDED/rust-cbindgen/cargo_config
  SPECS-EXTENDED/rust-cbindgen/disable-static-library.patch
  SPECS-EXTENDED/rust-cbindgen/rust-cbindgen.signatures.json
  SPECS-EXTENDED/rust-cbindgen/rust-cbindgen.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#6421 Patched CVE-2023-5441 for vim (CP of #6411)
  SPECS/vim/CVE-2023-5441.patch
  SPECS/vim/vim.spec
Labels: main

#6408 Image Customizer: Support legacy boot images.
  toolkit/tools/imagegen/diskutils/diskutils.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
Labels: main

#6409 Image Customizer: Improve safemount.
  toolkit/tools/internal/safemount/safemount.go
  toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
  toolkit/tools/pkg/imagecustomizerlib/rpmsourcesmounts.go
Labels: main

#6433 Image Customizer: Fix XFS disk handling.
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
Labels: main

#6396 SPECS/cni-plugins: update to v1.3.0 and set version while building
  SPECS/cni-plugins/cni-plugins.signatures.json
  SPECS/cni-plugins/cni-plugins.spec
  cgmanifest.json
Labels: main

#6434 Upgrade tensorflow to 2.11.1 to address CVEs (CP of #6418)
  SPECS/tensorflow/tensorflow.signatures.json
  SPECS/tensorflow/tensorflow.spec
  cgmanifest.json
Labels: main

#6435 Upgraded `keyutils` to version 1.6.3 to fix DNS a refreshing issue (CP of #6432)
  SPECS/keyutils/keyutils.signatures.json
  SPECS/keyutils/keyutils.spec
  SPECS/keyutils/tests_endianness_check_fix.patch
  cgmanifest.json
Labels: main

#6437 Image Customizer: Use absolute path for base config path.
  toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
Labels: main

#6417 Fixed toolkit missing package rebuilds.
  toolkit/tools/internal/pkggraph/pkggraph.go
  toolkit/tools/internal/pkggraph/pkggraph_test.go
Labels: main

#6329 Update go-test-coverage.yml to verify go version.
  .github/workflows/go-test-coverage.yml
Labels: main

#6439 Address kernel cves CVE-2023-39189, CVE-2023-39192, CVE-2023-39193, CVE-2023-39194, CVE-2023-42753, CVE-2023-42755
  SPECS/kernel/CVE-2023-39189.nopatch
  SPECS/kernel/CVE-2023-39192.nopatch
  SPECS/kernel/CVE-2023-39193.nopatch
  SPECS/kernel/CVE-2023-39194.nopatch
  SPECS/kernel/CVE-2023-42753.nopatch
  SPECS/kernel/CVE-2023-42755.nopatch
Labels: security, main

#6445 Image Customizer: Ensure loopback cleanly detaches.
  toolkit/tools/imagegen/diskutils/diskutils.go
  toolkit/tools/imager/imager.go
  toolkit/tools/internal/safeloopback/main_test.go
  toolkit/tools/internal/safeloopback/safeloopback.go
  toolkit/tools/internal/safeloopback/safeloopback_test.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
Labels: main

#6423 Fix CVE-2023-3817 in edk2 package
  SPECS/edk2/CVE-2023-3817.patch
  SPECS/edk2/edk2.spec
Labels: main

#6450 Add short test flag to full go-test-coverage
  toolkit/scripts/tools.mk
Labels: main

#6314 Performance Improvement: Add support for downloading/uploading ccache archives
  toolkit/Makefile
  toolkit/resources/manifests/package/ccache-configuration.json
  toolkit/scripts/pkggen.mk
  toolkit/tools/go.mod
  toolkit/tools/go.sum
  toolkit/tools/internal/azureblobstorage/azureblobstorage.go
  toolkit/tools/internal/ccachemanager/ccachemanager.go
  toolkit/tools/internal/directory/directory.go
  toolkit/tools/internal/rpm/rpm.go
  toolkit/tools/pkgworker/pkgworker.go
  toolkit/tools/scheduler/buildagents/chrootagent.go
  toolkit/tools/scheduler/buildagents/definition.go
  toolkit/tools/scheduler/buildagents/testagent.go
  toolkit/tools/scheduler/scheduler.go
  toolkit/tools/scheduler/schedulerutils/buildworker.go
Labels: Tools, main

#6452 Nopatch CVE-2023-4244 and CVE-2023-5197
  SPECS/kernel/CVE-2023-4244.nopatch
  SPECS/kernel/CVE-2023-5197.nopatch
Labels: security, main

#6390 Add the repoquerywrapper tool.
  toolkit/Makefile
  toolkit/scripts/repoquerywrapper.mk
  toolkit/scripts/tools.mk
  toolkit/scripts/update-target-if-output-changed.sh
  toolkit/tools/internal/packagerepo/repoutils/repoquery.go
  toolkit/tools/precacher/precacher.go
  toolkit/tools/repoquerywrapper/repoquerywrapper.go
Labels: main

#6454 Image Customizer: Fix TestCustomizeImageCopyFiles.
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
Labels: main

#6362 Made pipeline artifact subfolder names customizable.
  .pipelines/templates/PackageBuild.yml
  .pipelines/templates/PackageTestResultsAnalysis.yml
  .pipelines/templates/ToolchainBuild.yml
Labels: main

#6430 Image Customizer: Add support to load and unload modules
  toolkit/tools/imagecustomizerapi/module.go
  toolkit/tools/imagecustomizerapi/service.go
  toolkit/tools/imagecustomizerapi/systemconfig.go
  toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
  toolkit/tools/pkg/imagecustomizerlib/testdata/modules-config.yaml
Labels: main

#6457 Update skopeo to v1.13.3 to fix CVE-2023-33199 in rekor
  SPECS/skopeo/skopeo.signatures.json
  SPECS/skopeo/skopeo.spec
  cgmanifest.json
Labels: security, main

#6459 Giving image package fetcher access to all toolchain packages.
  toolkit/scripts/imggen.mk
Labels: main

#6441 Patch edk2 to fix CVE-2023-0465 and CVE-2023-2650
  SPECS/edk2/CVE-2023-0465.patch
  SPECS/edk2/CVE-2023-2650.patch
  SPECS/edk2/edk2.spec
Labels: security, main

#6458 update libXpm to v3.5.17 to fix CVE 2023-43789
  SPECS/libXpm/libXpm.signatures.json
  SPECS/libXpm/libXpm.spec
  cgmanifest.json
Labels: security, main

#6463 Update vim to 9.0.2010 to fix CVE-2023-5535 (CP of #6453)
  SPECS/vim/CVE-2023-5344.patch
  SPECS/vim/CVE-2023-5441.patch
  SPECS/vim/vim.signatures.json
  SPECS/vim/vim.spec
  cgmanifest.json
Labels: security, main

#6460 Add sodiff to Fasttrack builds and PR checks
  .pipelines/prchecks/PackageBuildPRCheck.yml
  .pipelines/templatesWithCheckout/SodiffCheck.yml
  toolkit/Makefile
  toolkit/scripts/analysis.mk
  toolkit/scripts/sodiff/mariner-sodiff.sh
Labels: main

#6462 CCache failure should not fail the build + Allow in-place updates of remote artifacts
  toolkit/tools/internal/ccachemanager/ccachemanager.go
  toolkit/tools/pkgworker/pkgworker.go
  toolkit/tools/scheduler/scheduler.go
Labels: main

#6365 Kata-CC: UVM - Enable encfs sidecar container
  SPECS/kernel-uvm-cvm/config
  SPECS/kernel-uvm-cvm/kernel-uvm-cvm.signatures.json
  SPECS/kernel-uvm-cvm/kernel-uvm-cvm.spec
  SPECS/kernel-uvm/config
  SPECS/kernel-uvm/kernel-uvm.signatures.json
  SPECS/kernel-uvm/kernel-uvm.spec
Labels: main

#6474 libXpm: set CVE-2023-43788 as fixed through version update
  SPECS/libXpm/libXpm.spec
Labels: main

#6451 Update gawk to v5.1.1 to fix CVE 2023-4156
  SPECS/gawk/gawk.signatures.json
  SPECS/gawk/gawk.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/toolchain-remote-wget-list
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
  toolkit/scripts/toolchain/container/toolchain_build_temp_tools.sh
Labels: main

#6480 cmake: patch vendored nghttp2 for cve-2023-44487
  SPECS/cmake/cmake.spec
  SPECS/cmake/cve-2023-44487.patch
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, main

#6472 Image Customizer: Handle separate boot partition.
  toolkit/tools/imagegen/diskutils/diskutils.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
Labels: main

#6481 Bump libcontainers-common release to rebuild with updated version of Go for cve-2023-44487
  SPECS/libcontainers-common/libcontainers-common.spec
Labels: main

#6491 Remove error from sodiff to unblock main builds
  toolkit/scripts/sodiff/mariner-sodiff.sh
Labels: main

#6387 Move cherry-pick automation to ADO
  .github/CODEOWNERS
  .github/workflows/cherry-pick.yml
  .pipelines/cherrypick/CherryPick.yml
  toolkit/scripts/cherry_pick.sh
Labels: main

#6560 Add Perl-Net-IP package to extended specs
  SPECS-EXTENDED/perl-Net-IP/Net-IP-1.26-rt60439.patch
  SPECS-EXTENDED/perl-Net-IP/Net-IP-1.26-shellbang.patch
  SPECS-EXTENDED/perl-Net-IP/perl-Net-IP.signatures.json
  SPECS-EXTENDED/perl-Net-IP/perl-Net-IP.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#6493 libnbd: patch CVE-2023-5215
  SPECS/libnbd/CVE-2023-5215.patch
  SPECS/libnbd/libnbd.spec
Labels: security, main

#6503 Patch hdf5 to address CVE-2021-37501
  SPECS/hdf5/CVE-2021-37501.patch
  SPECS/hdf5/hdf5.spec
Labels: security

#6565 Remove additional error logic from sodiff-check command
  toolkit/scripts/analysis.mk
Labels: main

#6572 Increase image size for baremetal and qemu guest to 4GB
  toolkit/imageconfigs/baremetal.json
  toolkit/imageconfigs/qemu-guest.json
Labels: main

#6574 Nopatch CVE-2023-23000, CVE-2023-23039, CVE-2023-26242, CVE-2023-32252, CVE-2023-32257, CVE-2023-32258, CVE-2023-33951, CVE-2023-33952, CVE-2023-37453, CVE-2023-42754, CVE-2023-42756, CVE-2023-45871, CVE-2023-4611, CVE-2023-5345
  SPECS/kernel/CVE-2023-23000.nopatch
  SPECS/kernel/CVE-2023-23039.nopatch
  SPECS/kernel/CVE-2023-26242.nopatch
  SPECS/kernel/CVE-2023-32252.nopatch
  SPECS/kernel/CVE-2023-32257.nopatch
  SPECS/kernel/CVE-2023-32258.nopatch
  SPECS/kernel/CVE-2023-33951.nopatch
  SPECS/kernel/CVE-2023-33952.nopatch
  SPECS/kernel/CVE-2023-37453.nopatch
  SPECS/kernel/CVE-2023-42754.nopatch
  SPECS/kernel/CVE-2023-42756.nopatch
  SPECS/kernel/CVE-2023-45871.nopatch
  SPECS/kernel/CVE-2023-4611.nopatch
  SPECS/kernel/CVE-2023-5345.nopatch
  toolkit/scripts/mariner-required-configs.json
Labels: security, main

#6579 containerized-rpmbuild: Build image if missing
  toolkit/scripts/containerized-build/create_container_build.sh
Labels: main, DevEx

#6494 systemd: enable zstd support in journald
  SPECS/systemd/mariner-2-do-not-default-zstd-journal-files-for-backwards-compatibility.patch
  SPECS/systemd/systemd.spec
Labels: main

#6443 Image config: Fix for when no user password is specified.
  toolkit/docs/building/prerequisites-mariner.md
  toolkit/docs/building/prerequisites-ubuntu.md
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/internal/userutils/main_test.go
  toolkit/tools/internal/userutils/userutils.go
  toolkit/tools/internal/userutils/userutils_test.go
  toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
Labels: main

#6559 httpd: upgrade 2.4.56 -> 2.4.58 to address CVE-2023-45802, CVE-2023-43622 & CVE-2023-31122
  SPECS/httpd/httpd.signatures.json
  SPECS/httpd/httpd.spec
  cgmanifest.json
Labels: security, main

#6380 fix: Enable lzo, snappy, zstd support in crash
  SPECS/crash/crash-printk-fix.patch
  SPECS/crash/crash.spec
  SPECS/crash/lzo_snappy_zstd.patch
Labels: main

#6581 Call setfacl on chroot directories
  toolkit/scripts/tools.mk
  toolkit/scripts/utils.mk
Labels: main

#6496 Image Customizer: Add documentation.
  toolkit/tools/imagecustomizer/README.md
  toolkit/tools/imagecustomizer/docs/cli.md
  toolkit/tools/imagecustomizer/docs/configuration.md
Labels: main

#6582 Enable CONFIG_BINFMT_MISC in ARM64
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/mariner-required-configs.json
Labels: main

#6578 kubernetes: upgrade to 1.28.3 to address CVE-2023-44487 and CVE-2023-…
  SPECS/kubernetes/kubernetes.signatures.json
  SPECS/kubernetes/kubernetes.spec
  cgmanifest.json
Labels: main

#6596 Revert "Call setfacl on chroot directories"
  toolkit/scripts/tools.mk
  toolkit/scripts/utils.mk
Labels: main

#6562 Fix freeradius installation issues
  SPECS-EXTENDED/freeradius/freeradius.spec
Labels: main

#6601 Patch CVE-2023-45853 for boost
  SPECS/boost/CVE-2023-45853.patch
  SPECS/boost/boost.spec
Labels: security

#6068 Bumping sudo to version 1.9.14p3
  SPECS/sudo/sudo.signatures.json
  SPECS/sudo/sudo.spec
  cgmanifest.json
Labels: main

#6600 Patch CVE-2023-45853 for tcl
  SPECS/tcl/CVE-2023-45853.patch
  SPECS/tcl/tcl.spec
Labels: security

#6611 Fix zlib CVE-2023-45853
  SPECS/zlib/CVE-2023-45853.patch
  SPECS/zlib/zlib.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#6610 Nopatch CVE-2023-5345 and CVE-2023-4622 for hyperv-daemons
  SPECS/hyperv-daemons/CVE-2023-4622.nopatch
  SPECS/hyperv-daemons/CVE-2023-5345.nopatch
Labels: security, main

#6469 Patch grub2 to fix CVE-2021-3695, CVE-2021-3696, CVE-2021-3697, CVE-2022-28733, CVE-2022-28734, CVE-2022-28735, CVE-2022-28736
  SPECS-SIGNED/grub2-efi-binary-signed/grub2-efi-binary-signed.spec
  SPECS/grub2/0173-loader-efi-chainloader-Simplify-the-loader-state.patch
  SPECS/grub2/0174-commands-boot-Add-API-to-pass-context-to-loader.patch
  SPECS/grub2/0175-loader-efi-chainloader-Use-grub_loader_set_ex.patch
  SPECS/grub2/0176-kern-efi-sb-Reject-non-kernel-files-in-the-shim_lock.patch
  SPECS/grub2/0177-kern-file-Do-not-leak-device_name-on-error-in-grub_f.patch
  SPECS/grub2/0178-video-readers-png-Abort-sooner-if-a-read-operation-f.patch
  SPECS/grub2/0179-video-readers-png-Refuse-to-handle-multiple-image-he.patch
  SPECS/grub2/0180-video-readers-png-Drop-greyscale-support-to-fix-heap.patch
  SPECS/grub2/0181-video-readers-png-Avoid-heap-OOB-R-W-inserting-huff-.patch
  SPECS/grub2/0182-video-readers-png-Sanity-check-some-huffman-codes.patch
  SPECS/grub2/0183-video-readers-jpeg-Abort-sooner-if-a-read-operation-.patch
  SPECS/grub2/0184-video-readers-jpeg-Do-not-reallocate-a-given-huff-ta.patch
  SPECS/grub2/0185-video-readers-jpeg-Refuse-to-handle-multiple-start-o.patch
  SPECS/grub2/0186-video-readers-jpeg-Block-int-underflow-wild-pointer-.patch
  SPECS/grub2/0187-normal-charset-Fix-array-out-of-bounds-formatting-un.patch
  SPECS/grub2/0188-net-ip-Do-IP-fragment-maths-safely.patch
  SPECS/grub2/0189-net-netbuff-Block-overly-large-netbuff-allocs.patch
  SPECS/grub2/0190-net-dns-Fix-double-free-addresses-on-corrupt-DNS-res.patch
  SPECS/grub2/0191-net-dns-Don-t-read-past-the-end-of-the-string-we-re-.patch
  SPECS/grub2/0192-net-tftp-Prevent-a-UAF-and-double-free-from-a-failed.patch
  SPECS/grub2/0193-net-tftp-Avoid-a-trivial-UAF.patch
  SPECS/grub2/0194-net-http-Do-not-tear-down-socket-if-it-s-already-bee.patch
  SPECS/grub2/0195-net-http-Fix-OOB-write-for-split-http-headers.patch
  SPECS/grub2/0196-net-http-Error-out-on-headers-with-LF-without-CR.patch
  SPECS/grub2/0197-fs-f2fs-Do-not-read-past-the-end-of-nat-journal-entr.patch
  SPECS/grub2/0198-fs-f2fs-Do-not-read-past-the-end-of-nat-bitmap.patch
  SPECS/grub2/0199-fs-f2fs-Do-not-copy-file-names-that-are-too-long.patch
  SPECS/grub2/0200-fs-btrfs-Fix-several-fuzz-issues-with-invalid-dir-it.patch
  SPECS/grub2/0201-fs-btrfs-Fix-more-ASAN-and-SEGV-issues-found-with-fu.patch
  SPECS/grub2/0202-fs-btrfs-Fix-more-fuzz-issues-related-to-chunks.patch
  SPECS/grub2/grub2.signatures.json
  SPECS/grub2/grub2.spec
  SPECS/grub2/sbat.csv.in
Labels: main

#6606 workflow: install golang 1.20
  .github/workflows/quickstart_2.0.yml
Labels: main

#6584 toolchain: fix with_check handling
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
Labels: main

#6567 Update libtiff to v4.6.0 to fix CVE 2023-40745 and 2023-41175
  SPECS/libtiff/libtiff.signatures.json
  SPECS/libtiff/libtiff.spec
  cgmanifest.json
Labels: main

#6615 Fix zhash CVE-2023-46228
  SPECS/zchunk/CVE-2023-46228.patch
  SPECS/zchunk/zchunk.spec
Labels: main

#6616 cronie: fix pam/crond file contents
  SPECS/cronie/cronie.spec
Labels: main

#6613 Image Customizer: Add tool version.
  toolkit/scripts/build_tag.mk
  toolkit/scripts/tools.mk
  toolkit/tools/imagecustomizer/main.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
Labels: main

#6577 Fix zlib CVE-2023-45853 in cloud-hypervisor
  SPECS/cloud-hypervisor/CVE-2023-45853.patch
  SPECS/cloud-hypervisor/cloud-hypervisor.spec
Labels: security

#6449 selinux-policy: Silence io.containerd.internal.v1.opt denial noise.
  SPECS/selinux-policy/0041-docker-Silence-io.containerd.internal.v1.opt-opt-con.patch
  SPECS/selinux-policy/selinux-policy.spec
Labels: main

#6467 Update libX11 to v1.8.7 to fix CVEs 2023-43785, 2023-43786 and 2023-43787
  SPECS/libX11/CVE-2023-3138.patch
  SPECS/libX11/libX11-race-condition.patch
  SPECS/libX11/libX11.signatures.json
  SPECS/libX11/libX11.spec
  SPECS/xorg-x11-proto-devel/xorg-x11-proto-devel.signatures.json
  SPECS/xorg-x11-proto-devel/xorg-x11-proto-devel.spec
  cgmanifest.json
Labels: security, main

#6583 toolkit: Add timestamp arguments to build_mariner_toolchain.sh
  toolkit/Makefile
  toolkit/scripts/chroot.mk
  toolkit/scripts/timestamp.mk
  toolkit/scripts/toolchain.mk
  toolkit/scripts/tools.mk
  toolkit/tools/bldtracker/bldtracker.go
Labels: main

#6632 Imager: Fix for when user password is empty.
  toolkit/tools/imagegen/installutils/installutils.go
Labels: main

#6629 Patch CVE-2023-45853 for rust
  SPECS/rust/CVE-2023-45853.patch
  SPECS/rust/rust.spec
Labels: main

#6630 Add wget replacement go-downloader
  toolkit/scripts/srpm_pack.mk
  toolkit/scripts/toolchain.mk
  toolkit/scripts/tools.mk
  toolkit/tools/downloader/downloader.go
Labels: main

#6618 libdrm 2.4.115 PyYAML gteq 5.0
  SPECS/PyYAML/ConstructorError_fix.patch
  SPECS/PyYAML/PyYAML-CVE-2017-18342.patch
  SPECS/PyYAML/PyYAML-lib3-CVE-2017-18342.patch
  SPECS/PyYAML/PyYAML.signatures.json
  SPECS/PyYAML/PyYAML.spec
  SPECS/PyYAML/change_default_loader.patch
  SPECS/libdrm/libdrm.signatures.json
  SPECS/libdrm/libdrm.spec
  cgmanifest.json
Labels: main

#6623 Add single transaction for image package cloner
  toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
  toolkit/tools/imagepkgfetcher/imagepkgfetcher.go
  toolkit/tools/internal/packagerepo/repocloner/repocloner.go
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
  toolkit/tools/internal/packagerepo/repoutils/repoutils.go
Labels: main

#6637 Bugfix: Correctly Return Rootfs Partition Instead of Boot Partition
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
Labels: main

#6638 go-downloader: handle --no-clobber correctly without explicit dst
  toolkit/tools/downloader/downloader.go
Labels: main
