Repository microsoft/azurelinux, pull requests merged in 2023-01, with the labels that each got.

#4306 apache-commons-beanutils: Add package version 1.9.4
  SPECS-EXTENDED/apache-commons-beanutils/apache-commons-beanutils-fix-build-version.patch
  SPECS-EXTENDED/apache-commons-beanutils/apache-commons-beanutils.signatures.json
  SPECS-EXTENDED/apache-commons-beanutils/apache-commons-beanutils.spec
  SPECS-EXTENDED/apache-commons-beanutils/jdk11.patch
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4309 apache-commons-dbcp: Add package version 2.1.1
  SPECS-EXTENDED/apache-commons-dbcp/apache-commons-dbcp-javadoc.patch
  SPECS-EXTENDED/apache-commons-dbcp/apache-commons-dbcp-sourcetarget.patch
  SPECS-EXTENDED/apache-commons-dbcp/apache-commons-dbcp.signatures.json
  SPECS-EXTENDED/apache-commons-dbcp/apache-commons-dbcp.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4310 apache-commons-digester: Add package version 2.1
  SPECS-EXTENDED/apache-commons-digester/apache-commons-digester-build.xml
  SPECS-EXTENDED/apache-commons-digester/apache-commons-digester.signatures.json
  SPECS-EXTENDED/apache-commons-digester/apache-commons-digester.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4311 apache-commons-jexl: Add package version 2.1.1
  SPECS-EXTENDED/apache-commons-jexl/0001-Port-to-current-javacc.patch
  SPECS-EXTENDED/apache-commons-jexl/001-Fix-tests.patch
  SPECS-EXTENDED/apache-commons-jexl/apache-commons-jexl-javadoc.patch
  SPECS-EXTENDED/apache-commons-jexl/apache-commons-jexl.signatures.json
  SPECS-EXTENDED/apache-commons-jexl/apache-commons-jexl.spec
  SPECS-EXTENDED/apache-commons-jexl/build.xml
  SPECS-EXTENDED/apache-commons-jexl/common.xml
  SPECS-EXTENDED/apache-commons-jexl/jexl2-compat-build.xml
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4312 apache-commons-pool: Add package version 1.6
  SPECS-EXTENDED/apache-commons-pool/apache-commons-pool.signatures.json
  SPECS-EXTENDED/apache-commons-pool/apache-commons-pool.spec
  SPECS-EXTENDED/apache-commons-pool/commons-pool-1.6-sourcetarget.patch
  SPECS-EXTENDED/apache-commons-pool/jakarta-commons-pool-build.patch
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4313 apache-commons-pool2: Add package version 2.4.2
  SPECS-EXTENDED/apache-commons-pool2/apache-commons-pool2.signatures.json
  SPECS-EXTENDED/apache-commons-pool2/apache-commons-pool2.spec
  SPECS-EXTENDED/apache-commons-pool2/jakarta-commons-pool-build.patch
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4314 apache-commons-vfs2: Add package version 2.2
  SPECS-EXTENDED/apache-commons-vfs2/0001_exlcude_abstractclass_from_test.patch
  SPECS-EXTENDED/apache-commons-vfs2/0002_remove_ftpFile_providers.patch
  SPECS-EXTENDED/apache-commons-vfs2/apache-commons-vfs2.signatures.json
  SPECS-EXTENDED/apache-commons-vfs2/apache-commons-vfs2.spec
  SPECS-EXTENDED/apache-commons-vfs2/build.xml
  SPECS-EXTENDED/apache-commons-vfs2/common.xml
  SPECS-EXTENDED/apache-commons-vfs2/commons-vfs2-build.xml
  SPECS-EXTENDED/apache-commons-vfs2/commons-vfs2-examples-build.xml
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4315 apache-commons-validator: Add package version 1.5.0
  SPECS-EXTENDED/apache-commons-validator/apache-commons-validator.signatures.json
  SPECS-EXTENDED/apache-commons-validator/apache-commons-validator.spec
  SPECS-EXTENDED/apache-commons-validator/commons-validator-1.5.0-locale.patch
  SPECS-EXTENDED/apache-commons-validator/commons-validator-1.5.0-srcencoding.patch
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4496 Enabled helm self checks
  SPECS/helm/helm.spec
Labels: Packaging, main

#4531 Revert "Patch CVE-2021-3929 in qemu-kvm"
  SPECS/qemu-kvm/CVE-2021-3929.patch
  SPECS/qemu-kvm/qemu-kvm.spec
Labels: Packaging, 1.0-dev

#4363 lv2: Add package version 1.18.8
  SPECS-EXTENDED/lv2/lv2.signatures.json
  SPECS-EXTENDED/lv2/lv2.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4359 python-rdflib: Add package version 6.2.0
  SPECS-EXTENDED/python-rdflib/python-rdflib.signatures.json
  SPECS-EXTENDED/python-rdflib/python-rdflib.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4360 libsamplerate: Add package version 0.2.2
  SPECS-EXTENDED/libsamplerate/libsamplerate.signatures.json
  SPECS-EXTENDED/libsamplerate/libsamplerate.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4361 sratom: Add package version 0.6.10
  SPECS-EXTENDED/sratom/sratom.signatures.json
  SPECS-EXTENDED/sratom/sratom.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4362 fftw: Add package version 3.3.10
  SPECS-EXTENDED/fftw/fftw.signatures.json
  SPECS-EXTENDED/fftw/fftw.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4365 cdparanoia: Add package version 10.2
  SPECS-EXTENDED/cdparanoia/010_build_system.patch
  SPECS-EXTENDED/cdparanoia/050_all_build_only_shared_libraries.patch
  SPECS-EXTENDED/cdparanoia/cdparanoia-III-01-typos-and-spelling.patch
  SPECS-EXTENDED/cdparanoia/cdparanoia-III-05-gcc4.3.patch
  SPECS-EXTENDED/cdparanoia/cdparanoia-III-06-endian.patch
  SPECS-EXTENDED/cdparanoia/cdparanoia-III-c++.patch
  SPECS-EXTENDED/cdparanoia/cdparanoia-III-ide_majors.patch
  SPECS-EXTENDED/cdparanoia/cdparanoia.signatures.json
  SPECS-EXTENDED/cdparanoia/cdparanoia.spec
  SPECS-EXTENDED/cdparanoia/config-guess-sub-update.patch
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4366 lilv: Add package version 0.24.14
  SPECS-EXTENDED/lilv/lilv.signatures.json
  SPECS-EXTENDED/lilv/lilv.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4373 gstreamer1-plugins-base: Add package version 1.20.4
  SPECS-EXTENDED/gstreamer1-plugins-base/0001-missing-plugins-Remove-the-mpegaudioversion-field.patch
  SPECS-EXTENDED/gstreamer1-plugins-base/0002-remove-missing-symbol-from-libs.patch
  SPECS-EXTENDED/gstreamer1-plugins-base/gstreamer1-plugins-base.signatures.json
  SPECS-EXTENDED/gstreamer1-plugins-base/gstreamer1-plugins-base.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4423 libcanberra: Add package version 0.30
  SPECS-EXTENDED/libcanberra/0001-gtk-Don-t-assume-all-GdkDisplays-are-GdkX11Displays-.patch
  SPECS-EXTENDED/libcanberra/libcanberra.signatures.json
  SPECS-EXTENDED/libcanberra/libcanberra.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#4424 pipewire: Add package version 0.3.60
  SPECS-EXTENDED/pipewire/0001-Build-media-session-from-local-tarbal.patch
  SPECS-EXTENDED/pipewire/pipewire.signatures.json
  SPECS-EXTENDED/pipewire/pipewire.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#4425 pulseaudio: Add package version 16.1
  SPECS-EXTENDED/pulseaudio/pulseaudio-11.1-autospawn_disable.patch
  SPECS-EXTENDED/pulseaudio/pulseaudio-autostart.patch
  SPECS-EXTENDED/pulseaudio/pulseaudio.signatures.json
  SPECS-EXTENDED/pulseaudio/pulseaudio.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#4426 SDL2: Add package version 1.24.0
  SPECS-EXTENDED/SDL2/SDL2-2.0.22-prefer-wayland.patch
  SPECS-EXTENDED/SDL2/SDL2-2.0.9-khrplatform.patch
  SPECS-EXTENDED/SDL2/SDL2.signatures.json
  SPECS-EXTENDED/SDL2/SDL2.spec
  SPECS-EXTENDED/SDL2/SDL_config.h
  SPECS-EXTENDED/SDL2/SDL_revision.h
  SPECS-EXTENDED/SDL2/multilib.patch
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#4428 cdrdao: Add package version 1.2.4
  SPECS-EXTENDED/cdrdao/cdrdao-1.2.4-ax_pthread.patch
  SPECS-EXTENDED/cdrdao/cdrdao-1.2.4-wformat-security.patch
  SPECS-EXTENDED/cdrdao/cdrdao.signatures.json
  SPECS-EXTENDED/cdrdao/cdrdao.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#4429 libao: Add package version 1.2.0
  SPECS-EXTENDED/libao/0001-ao_pulse.c-fix-latency-calculation.patch
  SPECS-EXTENDED/libao/d5221655dfd1a2156aa6be83b5aadea7c1e0f5bd.diff
  SPECS-EXTENDED/libao/libao-nanosleep.patch
  SPECS-EXTENDED/libao/libao.signatures.json
  SPECS-EXTENDED/libao/libao.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#4430 linuxconsoletools: Add package version 1.8.1
  SPECS-EXTENDED/linuxconsoletools/linuxconsoletools.signatures.json
  SPECS-EXTENDED/linuxconsoletools/linuxconsoletools.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#4524 libmikmod: Add package version 3.3.11.1
  SPECS-EXTENDED/libmikmod/libmikmod-64bit.patch
  SPECS-EXTENDED/libmikmod/libmikmod-cflags.patch
  SPECS-EXTENDED/libmikmod/libmikmod-multilib.patch
  SPECS-EXTENDED/libmikmod/libmikmod.signatures.json
  SPECS-EXTENDED/libmikmod/libmikmod.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#4534 Patch CVE-2022-40897 in python-setuptools
  SPECS/python-setuptools/CVE-2022-40897.patch
  SPECS/python-setuptools/python-setuptools.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, 1.0-dev

#4544 Patch CVE-2022-47629 in libksba
  SPECS/libksba/CVE-2022-47629.patch
  SPECS/libksba/libksba.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, 1.0-dev

#4489 TensorFlow: add missing deps
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/keras/keras.signatures.json
  SPECS/keras/keras.spec
  SPECS/python-distlib/python-distlib.signatures.json
  SPECS/python-distlib/python-distlib.spec
  SPECS/python-platformdirs/python-platformdirs.signatures.json
  SPECS/python-platformdirs/python-platformdirs.spec
  SPECS/python-tensorboard-plugin-wit/python-tensorboard-plugin-wit.signatures.json
  SPECS/python-tensorboard-plugin-wit/python-tensorboard-plugin-wit.spec
  SPECS/python-tensorboard/python-tensorboard.signatures.json
  SPECS/python-tensorboard/python-tensorboard.spec
  SPECS/python-tensorflow-estimator/python-tensorflow-estimator.signatures.json
  SPECS/python-tensorflow-estimator/python-tensorflow-estimator.spec
  SPECS/python-tensorflow-io-gcs-filesystem/python-tensorflow-io-gcs-filesystem.signatures.json
  SPECS/python-tensorflow-io-gcs-filesystem/python-tensorflow-io-gcs-filesystem.spec
  SPECS/python-virtualenv/python-virtualenv.spec
  SPECS/tensorflow/tensorflow.spec
  cgmanifest.json
Labels: main

#4533 Increasing marketplace images os disk size to 5GB
  toolkit/imageconfigs/marketplace-gen1.json
  toolkit/imageconfigs/marketplace-gen2-aarch64.json
Labels: Schema, main

#4545 aide: add aide package
  SPECS/aide/README.quickstart
  SPECS/aide/aide-0.15-syslog-format.patch
  SPECS/aide/aide-0.16-Use-LDADD-for-adding-curl-library-to-the-linker-comm.patch
  SPECS/aide/aide-0.16-crash-elf.patch
  SPECS/aide/aide-0.16-crypto-disable-haval-and-others.patch
  SPECS/aide/aide-0.16b1-fipsfix.patch
  SPECS/aide/aide-0.16rc1-man.patch
  SPECS/aide/aide.conf
  SPECS/aide/aide.logrotate
  SPECS/aide/aide.signatures.json
  SPECS/aide/aide.spec
  SPECS/aide/coverity.patch
  cgmanifest.json
Labels: Packaging, main

#4511 grub2: patch CVE-2022-2601 in 2.0
  SPECS-SIGNED/grub2-efi-binary-signed/grub2-efi-binary-signed.spec
  SPECS/grub2/CVE-2022-2601.patch
  SPECS/grub2/grub2.spec
Labels: Packaging, main

#4553 Bump Mariner Release for January 2023 Update
  SPECS/mariner-release/mariner-release.spec
Labels: Packaging, main

#4554 Bump Mariner for January Update
  SPECS/mariner-release/mariner-release.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#4561 Revert TensorFlow commit "0d513161236c642111c5251f4217d4ba7e63bcc3"
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/keras/keras.signatures.json
  SPECS/keras/keras.spec
  SPECS/python-distlib/python-distlib.signatures.json
  SPECS/python-distlib/python-distlib.spec
  SPECS/python-platformdirs/python-platformdirs.signatures.json
  SPECS/python-platformdirs/python-platformdirs.spec
  SPECS/python-tensorboard-plugin-wit/python-tensorboard-plugin-wit.signatures.json
  SPECS/python-tensorboard-plugin-wit/python-tensorboard-plugin-wit.spec
  SPECS/python-tensorboard/python-tensorboard.signatures.json
  SPECS/python-tensorboard/python-tensorboard.spec
  SPECS/python-tensorflow-estimator/python-tensorflow-estimator.signatures.json
  SPECS/python-tensorflow-estimator/python-tensorflow-estimator.spec
  SPECS/python-tensorflow-io-gcs-filesystem/python-tensorflow-io-gcs-filesystem.signatures.json
  SPECS/python-tensorflow-io-gcs-filesystem/python-tensorflow-io-gcs-filesystem.spec
  SPECS/python-virtualenv/python-virtualenv.spec
  SPECS/tensorflow/tensorflow.spec
  cgmanifest.json
Labels: main

#4563 Patch CVE-2022-42898 in krb5
  SPECS/krb5/CVE-2022-42898.patch
  SPECS/krb5/krb5.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, 1.0-dev

#4571 Rmaharjan/add tensorflow commit
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/keras/keras.signatures.json
  SPECS/keras/keras.spec
  SPECS/python-distlib/python-distlib.signatures.json
  SPECS/python-distlib/python-distlib.spec
  SPECS/python-platformdirs/python-platformdirs.signatures.json
  SPECS/python-platformdirs/python-platformdirs.spec
  SPECS/python-tensorboard-plugin-wit/python-tensorboard-plugin-wit.signatures.json
  SPECS/python-tensorboard-plugin-wit/python-tensorboard-plugin-wit.spec
  SPECS/python-tensorboard/python-tensorboard.signatures.json
  SPECS/python-tensorboard/python-tensorboard.spec
  SPECS/python-tensorflow-estimator/python-tensorflow-estimator.signatures.json
  SPECS/python-tensorflow-estimator/python-tensorflow-estimator.spec
  SPECS/python-virtualenv/python-virtualenv.spec
  SPECS/tensorflow/tensorflow.spec
  cgmanifest.json
Labels: main

#4548 libomxil-bellagio: Add package version 0.9.3
  SPECS-EXTENDED/libomxil-bellagio/bellagio-0.9.3-dynamicloader-linking.patch
  SPECS-EXTENDED/libomxil-bellagio/bellagio-0.9.3-parallel-build.patch
  SPECS-EXTENDED/libomxil-bellagio/bellagio-0.9.3-segfault-on-removeFromWaitResource.patch
  SPECS-EXTENDED/libomxil-bellagio/libomxil-bellagio-0.9.3-fix_Werror.patch
  SPECS-EXTENDED/libomxil-bellagio/libomxil-bellagio-0.9.3-memcpy.patch
  SPECS-EXTENDED/libomxil-bellagio/libomxil-bellagio-0.9.3-nodoc.patch
  SPECS-EXTENDED/libomxil-bellagio/libomxil-bellagio-0.9.3-unused.patch
  SPECS-EXTENDED/libomxil-bellagio/libomxil-bellagio-0.9.3-valgrind_register.patch
  SPECS-EXTENDED/libomxil-bellagio/libomxil-bellagio.signatures.json
  SPECS-EXTENDED/libomxil-bellagio/libomxil-bellagio.spec
  SPECS-EXTENDED/libomxil-bellagio/omxil_version.patch
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#4350 CGroupsV2 Toggle Optionality for Mariner 2.0 Images
  toolkit/resources/assets/grub2/grub.cfg
  toolkit/tools/imagegen/configuration/cgroup.go
  toolkit/tools/imagegen/configuration/cgroup_test.go
  toolkit/tools/imagegen/configuration/kernelcommandline.go
  toolkit/tools/imagegen/configuration/kernelcommandline_test.go
  toolkit/tools/imagegen/installutils/installutils.go
Labels: main

#4574 create script to generate vendored modules tarball for etcd and coredns
  SPECS/coredns/generate_source_tarball.sh
  SPECS/etcd/generate_source_tarball.sh
Labels: Packaging, main

#4585 Add Microsoft repo to PACKAGE_URL_LIST
  toolkit/Makefile
Labels: main

#4584 Added missing pytest runtime dependencies
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/pytest/pytest.spec
  SPECS/python-more-itertools/python-more-itertools.signatures.json
  SPECS/python-more-itertools/python-more-itertools.spec
  cgmanifest.json
Labels: main

#4580 Disabling systemd-oomd by default in Mariner
  SPECS/systemd/systemd-bootstrap.spec
  SPECS/systemd/systemd.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#4600 Revert "Disabling systemd-oomd by default in Mariner"
  SPECS/systemd/systemd-bootstrap.spec
  SPECS/systemd/systemd.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#4579 Build curl with HTTP/2 support
  SPECS/curl/curl.spec
  SPECS/nghttp2/nghttp2.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/resources/manifests/package/update_manifests.sh
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
Labels: main

#4608 update cloud-int.cfg lock-passwd to lock_passwd
  toolkit/imageconfigs/additionalconfigs/cloud-init.cfg
Labels: Schema, main

#4578 Fix logwatch, rear and dmraid to use chronie pacakge, Remove crontabs package.
  SPECS-EXTENDED/crontabs/crontabs.signatures.json
  SPECS-EXTENDED/crontabs/crontabs.spec
  SPECS-EXTENDED/dmraid/dmraid.spec
  SPECS-EXTENDED/logwatch/logwatch.spec
  SPECS-EXTENDED/rear/rear.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#4601 Improve robustness of ISO initrd builds
  toolkit/scripts/imggen.mk
Labels: Tools, main

#4588 curl: downgrade to 7.86 to fix perl-WWW-curl and patch CVE-2022-43551
  SPECS/curl/CVE-2022-43551.patch
  SPECS/curl/curl.signatures.json
  SPECS/curl/curl.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#4181 Fix missing dependency tracking for spec sources, refactor Makefile to skip shell commands during dry-run
  toolkit/Makefile
  toolkit/docs/coding_guide/makefiles.md
  toolkit/docs/how_it_works/5_misc.md
  toolkit/scripts/build_tag.mk
  toolkit/scripts/imggen.mk
  toolkit/scripts/pkggen.mk
  toolkit/scripts/rpmops.sh
  toolkit/scripts/srpm_expand.mk
  toolkit/scripts/srpm_pack.mk
  toolkit/scripts/toolchain.mk
  toolkit/scripts/toolkit.mk
  toolkit/scripts/tools.mk
  toolkit/scripts/utils.mk
Labels: documentation, Tools, DevEx

#4582 Add package liblouis version 3.24.0
  SPECS-EXTENDED/liblouis/liblouis.signatures.json
  SPECS-EXTENDED/liblouis/liblouis.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#4641 openvswitch: upgrade to 2.15.7 to fix CVE-2022-4337, CVE-2022-4338
  SPECS/openvswitch/CVE-2021-3905.patch
  SPECS/openvswitch/openvswitch.signatures.json
  SPECS/openvswitch/openvswitch.spec
  cgmanifest.json
Labels: 1.0-dev

#4144 Upgrading prometheus from 2.36.0 to 2.37.0
  SPECS/prometheus/generate_source_tarball.sh
  SPECS/prometheus/prometheus.signatures.json
  SPECS/prometheus/prometheus.spec
  cgmanifest.json
Labels: Packaging, main

#4642 Add package libwpg version 0.3.3
  SPECS-EXTENDED/libwpg/libwpg.signatures.json
  SPECS-EXTENDED/libwpg/libwpg.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#4648 Add package zopfli version 1.0.3
  SPECS-EXTENDED/zopfli/zopfli.signatures.json
  SPECS-EXTENDED/zopfli/zopfli.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#4646 libtar: patch CVE-2021-33640
  SPECS/libtar/CVE-2021-33640.patch
  SPECS/libtar/CVE-2021-33645.nopatch
  SPECS/libtar/CVE-2021-33646.nopatch
  SPECS/libtar/libtar-1.2.20-CVE-2021-33645-CVE-2021-33646.patch
  SPECS/libtar/libtar-1.2.20-no-static-buffer.patch
  SPECS/libtar/libtar.spec
Labels: Packaging, main

#4650 Fix package installation failure for PXE boot scenario
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/imager/imager.go
Labels: Tools, main

#4657 Bump Mariner 1.0 Release for January Update 2"
  SPECS/mariner-release/mariner-release.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#4520 SDL: Add package version 1.2.15
  SPECS-EXTENDED/SDL/SDL-1.2.10-GrabNotViewable.patch
  SPECS-EXTENDED/SDL/SDL-1.2.12-multilib.patch
  SPECS-EXTENDED/SDL/SDL-1.2.15-CVE-2019-13616-validate_image_size_when_loading_BMP_files.patch
  SPECS-EXTENDED/SDL/SDL-1.2.15-CVE-2019-7572-Fix-a-buffer-overread-in-IMA_ADPCM_nib.patch
  SPECS-EXTENDED/SDL/SDL-1.2.15-CVE-2019-7572-Fix-a-buffer-overwrite-in-IMA_ADPCM_de.patch
  SPECS-EXTENDED/SDL/SDL-1.2.15-CVE-2019-7573-CVE-2019-7576-Fix-buffer-overreads-in-.patch
  SPECS-EXTENDED/SDL/SDL-1.2.15-CVE-2019-7574-Fix-a-buffer-overread-in-IMA_ADPCM_dec.patch
  SPECS-EXTENDED/SDL/SDL-1.2.15-CVE-2019-7575-Fix-a-buffer-overwrite-in-MS_ADPCM_dec.patch
  SPECS-EXTENDED/SDL/SDL-1.2.15-CVE-2019-7577-Fix-a-buffer-overread-in-MS_ADPCM_deco.patch
  SPECS-EXTENDED/SDL/SDL-1.2.15-CVE-2019-7577-Fix-a-buffer-overread-in-MS_ADPCM_nibb.patch
  SPECS-EXTENDED/SDL/SDL-1.2.15-CVE-2019-7578-Fix-a-buffer-overread-in-InitIMA_ADPCM.patch
  SPECS-EXTENDED/SDL/SDL-1.2.15-CVE-2019-7635-Reject-BMP-images-with-pixel-colors-ou.patch
  SPECS-EXTENDED/SDL/SDL-1.2.15-CVE-2019-7637-Fix-in-integer-overflow-in-SDL_Calcula.patch
  SPECS-EXTENDED/SDL/SDL-1.2.15-CVE-2019-7638-CVE-2019-7636-Refuse-loading-BMP-image.patch
  SPECS-EXTENDED/SDL/SDL-1.2.15-Fixed-bug-4108-Missing-break-statements-in-SDL_CDRes.patch
  SPECS-EXTENDED/SDL/SDL-1.2.15-Reject-2-3-5-6-7-bpp-BMP-images.patch
  SPECS-EXTENDED/SDL/SDL-1.2.15-SDL_EnableUNICODE_drops_keyboard_events.patch
  SPECS-EXTENDED/SDL/SDL-1.2.15-Use-system-glext.h.patch
  SPECS-EXTENDED/SDL/SDL-1.2.15-add_sdl_config_man.patch
  SPECS-EXTENDED/SDL/SDL-1.2.15-const_XData32.patch
  SPECS-EXTENDED/SDL/SDL-1.2.15-fix-small-errors-detected-by-coverity.patch
  SPECS-EXTENDED/SDL/SDL-1.2.15-fix_copy_paste_mistakes_in_commit_9b0e5c555c0f.patch
  SPECS-EXTENDED/SDL/SDL-1.2.15-ignore_insane_joystick_axis.patch
  SPECS-EXTENDED/SDL/SDL-1.2.15-no-default-backing-store.patch
  SPECS-EXTENDED/SDL/SDL-1.2.15-vec_perm-ppc64le.patch
  SPECS-EXTENDED/SDL/SDL.signatures.json
  SPECS-EXTENDED/SDL/SDL.spec
  SPECS-EXTENDED/SDL/SDL_config.h
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#4521 Add SDL_sound package version 1.0.3
  SPECS-EXTENDED/SDL_sound/SDL_sound.signatures.json
  SPECS-EXTENDED/SDL_sound/SDL_sound.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#4522 Add alsa-firmware package version 1.2.4
  SPECS-EXTENDED/alsa-firmware/alsa-firmware.signatures.json
  SPECS-EXTENDED/alsa-firmware/alsa-firmware.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#4523 Add alsa-plugins package version 1.2.7.1
  SPECS-EXTENDED/alsa-plugins/alsa-plugins.signatures.json
  SPECS-EXTENDED/alsa-plugins/alsa-plugins.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#4525 Add zziplib package version 0.13.72
  SPECS-EXTENDED/zziplib/zziplib.signatures.json
  SPECS-EXTENDED/zziplib/zziplib.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#4663 Fixed `mariner_rpmspec` command.
  toolkit/scripts/build_tag.mk
  toolkit/scripts/rpmops.sh
Labels: main

#4664 add golang-1.18 spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/golang/golang-1.18.signatures.json
  SPECS/golang/golang-1.18.spec
  cgmanifest.json
Labels: main

#4667 Add ISO image verification instructions
  README.md
  toolkit/docs/security/iso-image-verification.md
Labels: main

#4581 Add kernel-azure RPM
  SPECS-SIGNED/kernel-azure-signed/kernel-azure-signed.spec
  SPECS-SIGNED/kernel-azure-signed/sha512hmac-openssl.sh
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/kernel-azure/cbl-mariner-ca-20211013.pem
  SPECS/kernel-azure/config
  SPECS/kernel-azure/config_aarch64
  SPECS/kernel-azure/kernel-azure.signatures.json
  SPECS/kernel-azure/kernel-azure.spec
  SPECS/kernel-azure/sha512hmac-openssl.sh
  cgmanifest.json
  toolkit/scripts/check_entangled_specs.py
  toolkit/scripts/update_kernel.sh
Labels: main

#4666 Worked around RPM package resolution bug.
  SPECS/libkcapi/libkcapi.spec
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
Labels: Tools, main

#4673 Upgrade git to v2.33.6 to address critical CVE-2022-23521 & CVE-2022-41903
  SPECS/git/git.signatures.json
  SPECS/git/git.spec
  cgmanifest.json
Labels: main

#4676 Upgrade python-certifi to version 2022.12.07 to address CVE-2022-23491
  SPECS/python-certifi/python-certifi.signatures.json
  SPECS/python-certifi/python-certifi.spec
  cgmanifest.json
Labels: security, main

#4510 Add .gitattributes file for GitHub linguist attributes
  .gitattributes
Labels: main

#4597 packages.microsoft.com repo structure info
  SUPPORT.md
  toolkit/README.md
  toolkit/docs/building/building.md
Labels: main

#4684 Bump Mariner Release Mariner 2.0 January 2023 Update 2
  SPECS/mariner-release/mariner-release.spec
Labels: Packaging, main

#4688 Move kernel-mshv and kernel-uvm to core from extended
  SPECS/kernel-mshv/cbl-mariner-ca-20211013.pem
  SPECS/kernel-mshv/config
  SPECS/kernel-mshv/kernel-mshv.signatures.json
  SPECS/kernel-mshv/kernel-mshv.spec
  SPECS/kernel-uvm/config
  SPECS/kernel-uvm/kernel-uvm.signatures.json
  SPECS/kernel-uvm/kernel-uvm.spec
Labels: Packaging, main

#4675 openvswitch - add CVE-2021-3905.nopatch
  SPECS/openvswitch/CVE-2021-3905.nopatch
Labels: security, Packaging, 1.0-dev

#4696 add missing coredns version in cgmanifest
  cgmanifest.json
Labels: main

#4598 Add flux and influxdb2 packages to 2.0
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/flux/cargo_config
  SPECS/flux/flux.signatures.json
  SPECS/flux/flux.spec
  SPECS/flux/generate_source_tarball.sh
  SPECS/influx-cli/generate_souce_tarball.sh
  SPECS/influx-cli/influx-cli.signatures.json
  SPECS/influx-cli/influx-cli.spec
  SPECS/influxdb/config.yaml
  SPECS/influxdb/generate_source_tarball.sh
  SPECS/influxdb/influxdb-user.conf
  SPECS/influxdb/influxdb.service
  SPECS/influxdb/influxdb.signatures.json
  SPECS/influxdb/influxdb.spec
  SPECS/influxdb/influxdb.tmpfiles
  cgmanifest.json
  toolkit/scripts/check_entangled_specs.py
Labels: main

#4694 Add subscription-manager package version 1.29.30
  SPECS-EXTENDED/subscription-manager/subscription-manager.signatures.json
  SPECS-EXTENDED/subscription-manager/subscription-manager.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#4708 Revert "enable cyrus sasl"
  SPECS/openldap/openldap.spec
Labels: Packaging, main

#4713 Fix calamares bugs and update requires
  SPECS/calamares/calamares.spec
  SPECS/calamares/install-progress-bar-fix.patch
  SPECS/calamares/serialize-read-access.patch
Labels: Packaging

#4703 Upgrade git to 2.33.6 to address CVE-2022-23521 and CVE-2022-41903
  SPECS/git/CVE-2021-40330.patch
  SPECS/git/git.signatures.json
  SPECS/git/git.spec
  cgmanifest.json
Labels: security, Packaging, 1.0-dev

#4702 Patch libtar CVE-2021-33640
  SPECS/libtar/CVE-2021-33640.patch
  SPECS/libtar/CVE-2021-33645.nopatch
  SPECS/libtar/CVE-2021-33646.nopatch
  SPECS/libtar/libtar-1.2.20-CVE-2021-33645-CVE-2021-33646.patch
  SPECS/libtar/libtar-1.2.20-no-static-buffer.patch
  SPECS/libtar/libtar.spec
Labels: security, Packaging, 1.0-dev

#4714 Add cpulimit SPEC to Mariner
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/cpulimit/cpulimit-2.8-do_not_forget_version.patch
  SPECS/cpulimit/cpulimit.signatures.json
  SPECS/cpulimit/cpulimit.spec
  cgmanifest.json
Labels: main

#4612 Add bsf package version 2.4.0
  SPECS-EXTENDED/bsf/bsf-doclint-ignore.patch
  SPECS-EXTENDED/bsf/bsf-pom.xml
  SPECS-EXTENDED/bsf/bsf.signatures.json
  SPECS-EXTENDED/bsf/bsf.spec
  SPECS-EXTENDED/bsf/build-file.patch
  SPECS-EXTENDED/bsf/build.properties.patch
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4613 Add clutter-gst3 package version 3.0.27
  SPECS-EXTENDED/clutter-gst3/clutter-gst3.signatures.json
  SPECS-EXTENDED/clutter-gst3/clutter-gst3.spec
  SPECS-EXTENDED/clutter-gst3/remove-rgbx-bgrx-support.patch
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4614 Add clutter-gtk package version 1.8.4
  SPECS-EXTENDED/clutter-gtk/clutter-gtk.signatures.json
  SPECS-EXTENDED/clutter-gtk/clutter-gtk.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4615 Add clutter package version 1.26.4
  SPECS-EXTENDED/clutter/clutter.signatures.json
  SPECS-EXTENDED/clutter/clutter.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4616 Add cogl package version 1.22.8
  SPECS-EXTENDED/cogl/0001-egl-Use-eglGetPlatformDisplay-not-eglGetDisplay.patch
  SPECS-EXTENDED/cogl/0002-add-GL_ARB_shader_texture_lod-support.patch
  SPECS-EXTENDED/cogl/0003-texture-support-copy_sub_image.patch
  SPECS-EXTENDED/cogl/cogl.signatures.json
  SPECS-EXTENDED/cogl/cogl.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4617 Add jansi package version 2.4.0
  SPECS-EXTENDED/jansi/jansi-build.xml
  SPECS-EXTENDED/jansi/jansi-jni.patch
  SPECS-EXTENDED/jansi/jansi.signatures.json
  SPECS-EXTENDED/jansi/jansi.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4618 Add jline package version 2.14.6
  SPECS-EXTENDED/jline/jline-build.xml
  SPECS-EXTENDED/jline/jline-jansi2.patch
  SPECS-EXTENDED/jline/jline-java8compat.patch
  SPECS-EXTENDED/jline/jline.signatures.json
  SPECS-EXTENDED/jline/jline.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4619 Add libblockdev package version 2.28
  SPECS-EXTENDED/libblockdev/libblockdev.signatures.json
  SPECS-EXTENDED/libblockdev/libblockdev.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4620 Add tclx package version 8.4.0
  SPECS-EXTENDED/tclx/tclx-8.4-man.patch
  SPECS-EXTENDED/tclx/tclx-8.4-relid.patch
  SPECS-EXTENDED/tclx/tclx-8.4-tcl86.patch
  SPECS-EXTENDED/tclx/tclx-8.4-varinit.patch
  SPECS-EXTENDED/tclx/tclx.signatures.json
  SPECS-EXTENDED/tclx/tclx.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4621 Add tix package version 8.4.3
  SPECS-EXTENDED/tix/tix-8.4.2-link.patch
  SPECS-EXTENDED/tix/tix-8.4.3-covscan-fixes.patch
  SPECS-EXTENDED/tix/tix-8.4.3-tcl86.patch
  SPECS-EXTENDED/tix/tix.signatures.json
  SPECS-EXTENDED/tix/tix.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4622 Add vorbis-tools package version 1.4.2
  SPECS-EXTENDED/vorbis-tools/vorbis-tools-1.4.2-man-page.patch
  SPECS-EXTENDED/vorbis-tools/vorbis-tools.signatures.json
  SPECS-EXTENDED/vorbis-tools/vorbis-tools.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4623 Add wordnet package version 3.0
  SPECS-EXTENDED/wordnet/wordnet-3.0-CVE-2008-2149.patch
  SPECS-EXTENDED/wordnet/wordnet-3.0-CVE-2008-3908.patch
  SPECS-EXTENDED/wordnet/wordnet-3.0-Pass-compilation-with-Werror-format-security.patch
  SPECS-EXTENDED/wordnet/wordnet-3.0-error_message.patch
  SPECS-EXTENDED/wordnet/wordnet-3.0-fix_man.patch
  SPECS-EXTENDED/wordnet/wordnet-3.0-fix_resourcedir_path.patch
  SPECS-EXTENDED/wordnet/wordnet-3.0-libtool.patch
  SPECS-EXTENDED/wordnet/wordnet-3.0-src_stubs_c.patch
  SPECS-EXTENDED/wordnet/wordnet-3.0-use_system_tk_headers.patch
  SPECS-EXTENDED/wordnet/wordnet-3.0-wishwn_manpage.patch
  SPECS-EXTENDED/wordnet/wordnet.signatures.json
  SPECS-EXTENDED/wordnet/wordnet.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4624 Add xapian-core package version 1.4.20
  SPECS-EXTENDED/xapian-core/xapian-core.signatures.json
  SPECS-EXTENDED/xapian-core/xapian-core.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4625 Fix package tk install requires on tcl & tcl-devel
  SPECS-EXTENDED/tk/tk.spec
  cgmanifest.json
Labels: main, specs-extended

#4710 wireguard: enable wireguard kernel module
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, main

#4686 Disable systemd-oomd service & socket through 99-mariner.preset file
  SPECS/systemd/99-mariner.preset
  SPECS/systemd/systemd-bootstrap.signatures.json
  SPECS/systemd/systemd-bootstrap.spec
  SPECS/systemd/systemd.signatures.json
  SPECS/systemd/systemd.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#4709 Switch to posix compliant invocation of test in mk file
  toolkit/scripts/build_tag.mk
Labels: Tools, main
