Repository microsoft/azurelinux, pull requests merged in 2023-03, with the labels that each got.

#4965 libtiff: move nopatch files to spec folder
  SPECS/libtiff/CVE-2023-0796.nopatch
  SPECS/libtiff/CVE-2023-0797.nopatch
  SPECS/libtiff/CVE-2023-0798.nopatch
  SPECS/libtiff/CVE-2023-0799.nopatch
Labels: security, 1.0-dev

#4857 Add package geos v3.11.1
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/geos/geos.signatures.json
  SPECS/geos/geos.spec
  SPECS/geos/geos_docs.patch
  SPECS/geos/geos_gcc13.patch
  cgmanifest.json
Labels: main

#4971 Upgrade fluent-bit to 2.0.9
  SPECS/fluent-bit/fluent-bit.signatures.json
  SPECS/fluent-bit/fluent-bit.spec
  cgmanifest.json
Labels: main

#4972 Add patch to fix CVE-2023-25165
  SPECS/helm/CVE-2023-25165.patch
  SPECS/helm/helm.spec
Labels: 1.0-dev

#4913 Added new Microsoft-owned root CAs to the base set of trusted CAs.
  SPECS/ca-certificates/ca-certificates.signatures.json
  SPECS/ca-certificates/ca-certificates.spec
  SPECS/ca-certificates/cert2certdata.sh
  SPECS/ca-certificates/certdata.base.txt
  SPECS/prebuilt-ca-certificates-base/prebuilt-ca-certificates-base.spec
  SPECS/prebuilt-ca-certificates/prebuilt-ca-certificates.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#4605 Add package crypto-policies version 20200619
  SPECS-EXTENDED/crypto-policies/crypto-policies.signatures.json
  SPECS-EXTENDED/crypto-policies/crypto-policies.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4716 Add frr package version 8.4.2
  SPECS-EXTENDED/frr/0000-remove-babeld-and-ldpd.patch
  SPECS-EXTENDED/frr/0002-enable-openssl.patch
  SPECS-EXTENDED/frr/0003-disable-eigrp-crypto.patch
  SPECS-EXTENDED/frr/0004-fips-mode.patch
  SPECS-EXTENDED/frr/0005-remove-grpc-test.patch
  SPECS-EXTENDED/frr/frr-sysusers.conf
  SPECS-EXTENDED/frr/frr-tmpfiles.conf
  SPECS-EXTENDED/frr/frr.fc
  SPECS-EXTENDED/frr/frr.if
  SPECS-EXTENDED/frr/frr.signatures.json
  SPECS-EXTENDED/frr/frr.spec
  SPECS-EXTENDED/frr/frr.te
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4836 Add dleyna-connector-dbus package version 0.3.0
  SPECS-EXTENDED/dleyna-connector-dbus/dleyna-connector-dbus.signatures.json
  SPECS-EXTENDED/dleyna-connector-dbus/dleyna-connector-dbus.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4837 Add dleyna-core package version 0.6.0
  SPECS-EXTENDED/dleyna-core/dleyna-core-Don-t-remove-a-queue-more-than-once.patch
  SPECS-EXTENDED/dleyna-core/dleyna-core-Make-the-task-processor-more-robust.patch
  SPECS-EXTENDED/dleyna-core/dleyna-core.signatures.json
  SPECS-EXTENDED/dleyna-core/dleyna-core.spec
  SPECS-EXTENDED/dleyna-core/port-to-gupnp-1.6.patch
  SPECS-EXTENDED/dleyna-core/port_gupnp_1.6_context_filter.patch
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4838 Add gssdp package version 1.6.2
  SPECS-EXTENDED/gssdp/gssdp.signatures.json
  SPECS-EXTENDED/gssdp/gssdp.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4839 Add gupnp-dlna package version 0.12.0
  SPECS-EXTENDED/gupnp-dlna/gupnp-dlna.signatures.json
  SPECS-EXTENDED/gupnp-dlna/gupnp-dlna.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4840 Add gupnp-igd package version 1.2.0
  SPECS-EXTENDED/gupnp-igd/gupnp-igd.signatures.json
  SPECS-EXTENDED/gupnp-igd/gupnp-igd.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4841 Add gupnp package version 1.6.3
  SPECS-EXTENDED/gupnp/gupnp.signatures.json
  SPECS-EXTENDED/gupnp/gupnp.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4842 Add opal pakcage version 3.10.11
  SPECS-EXTENDED/opal/opal-3.10-fix-cflags.patch
  SPECS-EXTENDED/opal/opal.signatures.json
  SPECS-EXTENDED/opal/opal.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4843 Add ptlib package version 2.10.11
  SPECS-EXTENDED/ptlib/ptlib-2.10.10-mga-bison-parameter.patch
  SPECS-EXTENDED/ptlib/ptlib-2.10.11-make43.patch
  SPECS-EXTENDED/ptlib/ptlib-2.10.11-openssl11.patch
  SPECS-EXTENDED/ptlib/ptlib-2.10.11-signed_int_overflow.patch
  SPECS-EXTENDED/ptlib/ptlib-gcc5.patch
  SPECS-EXTENDED/ptlib/ptlib-gcc8.patch
  SPECS-EXTENDED/ptlib/ptlib-pkgconf-no-ldflags.patch
  SPECS-EXTENDED/ptlib/ptlib.signatures.json
  SPECS-EXTENDED/ptlib/ptlib.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4844 Add udisks2 package version 2.9.4
  SPECS-EXTENDED/udisks2/ignore-apple-boot-part.patch
  SPECS-EXTENDED/udisks2/udisks-2.10.0-doc_annotations.patch
  SPECS-EXTENDED/udisks2/udisks2.signatures.json
  SPECS-EXTENDED/udisks2/udisks2.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4964 Upgrade libtiff to 4.5.0 for CVE-2023-0796
  SPECS/libtiff/CVE-2022-2056.patch
  SPECS/libtiff/CVE-2022-2057.nopatch
  SPECS/libtiff/CVE-2022-2058.nopatch
  SPECS/libtiff/CVE-2022-2953.patch
  SPECS/libtiff/CVE-2022-3570.patch
  SPECS/libtiff/CVE-2022-3597.patch
  SPECS/libtiff/CVE-2022-3598.nopatch
  SPECS/libtiff/CVE-2022-3599.patch
  SPECS/libtiff/CVE-2022-3626.nopatch
  SPECS/libtiff/CVE-2022-3627.nopatch
  SPECS/libtiff/CVE-2022-3970.patch
  SPECS/libtiff/CVE-2022-48281.patch
  SPECS/libtiff/CVE-2023-0795.patch
  SPECS/libtiff/CVE-2023-0796.nopatch
  SPECS/libtiff/CVE-2023-0797.nopatch
  SPECS/libtiff/CVE-2023-0798.nopatch
  SPECS/libtiff/CVE-2023-0799.nopatch
  SPECS/libtiff/CVE-2023-0800.patch
  SPECS/libtiff/libtiff.signatures.json
  SPECS/libtiff/libtiff.spec
  cgmanifest.json
Labels: 1.0-dev

#4974 Add patch to fix CVE-2023-25153
  SPECS/moby-containerd/CVE-2023-25153.patch
  SPECS/moby-containerd/moby-containerd.spec
Labels: 1.0-dev

#4975 Backport patch to fix CVE-2023-24329
  SPECS/python2/CVE-2023-24329.patch
  SPECS/python2/python2.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#4854 update kernel-mshv
  SPECS/kernel-mshv/config
  SPECS/kernel-mshv/kernel-mshv.signatures.json
  SPECS/kernel-mshv/kernel-mshv.spec
  cgmanifest.json
Labels: main

#4978 Fixed `certdata.base.txt` signature.
  SPECS/ca-certificates/ca-certificates.signatures.json
Labels: main

#4976 Fixing CHECK_BUILD_RETRIES issues
  toolkit/tools/scheduler/schedulerutils/buildworker.go
Labels: main

#4979 Saulparedes/fix kernel mshv config signature
  SPECS/kernel-mshv/kernel-mshv.signatures.json
Labels: main

#4980 mariner-release: bump to version 35 for March 2023 update 1
  SPECS/mariner-release/mariner-release.spec
Labels: main

#4947 Upgrade Blobfuse2 to 2.0.2
  SPECS/blobfuse2/blobfuse2.signatures.json
  SPECS/blobfuse2/blobfuse2.spec
  cgmanifest.json
Labels: main

#4891 Skip pwd-long tests from coreutils which is failing in chroot
  SPECS/coreutils/coreutils.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/tags
Labels: 1.0-dev

#4987 Add 13 python packages
  SPECS-EXTENDED/google-api-python-client/google-api-python-client.signatures.json
  SPECS-EXTENDED/google-api-python-client/google-api-python-client.spec
  SPECS-EXTENDED/python-dbusmock/python-dbusmock.signatures.json
  SPECS-EXTENDED/python-dbusmock/python-dbusmock.spec
  SPECS-EXTENDED/python-ddt/python-ddt.signatures.json
  SPECS-EXTENDED/python-ddt/python-ddt.spec
  SPECS-EXTENDED/python-fasteners/80a3eaed75276faf21034e7e6c626fd19485ea39.patch
  SPECS-EXTENDED/python-fasteners/python-fasteners.signatures.json
  SPECS-EXTENDED/python-fasteners/python-fasteners.spec
  SPECS-EXTENDED/python-httplib2/python-httplib2.certfile.patch
  SPECS-EXTENDED/python-httplib2/python-httplib2.signatures.json
  SPECS-EXTENDED/python-httplib2/python-httplib2.spec
  SPECS-EXTENDED/python-memcached/python-memcached.signatures.json
  SPECS-EXTENDED/python-memcached/python-memcached.spec
  SPECS-EXTENDED/python-msal/python-msal.signatures.json
  SPECS-EXTENDED/python-msal/python-msal.spec
  SPECS-EXTENDED/python-msrestazure/python-msrestazure.signatures.json
  SPECS-EXTENDED/python-msrestazure/python-msrestazure.spec
  SPECS-EXTENDED/python-paramiko/0003-remove-pytest-relaxed-dep.patch
  SPECS-EXTENDED/python-paramiko/0004-remove-mock-dep.patch
  SPECS-EXTENDED/python-paramiko/python-paramiko.signatures.json
  SPECS-EXTENDED/python-paramiko/python-paramiko.spec
  SPECS-EXTENDED/python-pytest-relaxed/python-pytest-relaxed.signatures.json
  SPECS-EXTENDED/python-pytest-relaxed/python-pytest-relaxed.spec
  SPECS-EXTENDED/python-testpath/python-testpath.signatures.json
  SPECS-EXTENDED/python-testpath/python-testpath.spec
  SPECS-EXTENDED/python-waitress/generate-tarball.sh
  SPECS-EXTENDED/python-waitress/python-waitress.signatures.json
  SPECS-EXTENDED/python-waitress/python-waitress.spec
  SPECS-EXTENDED/python-yubico/0001-literal-comparison.patch
  SPECS-EXTENDED/python-yubico/python-yubico.signatures.json
  SPECS-EXTENDED/python-yubico/python-yubico.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4988 Update bootstrap toolchain
  toolkit/scripts/toolchain/container/Dockerfile
  toolkit/scripts/toolchain/container/toolchain-remote-wget-list
Labels: main

#4998 Update workflows in 1.0 to use latest Ubuntu
  .github/workflows/check-manifests.yml
  .github/workflows/check-package-cgmanifest.yml
  .github/workflows/check-spec.yml
  .github/workflows/go-test-coverage.yml
Labels: 1.0-dev

#4993 Fix patch to address CVE-2023-24329
  SPECS/python2/CVE-2023-24329.patch
  SPECS/python2/python2.spec
Labels: 1.0-dev

#5002 Bump Mariner 1.0 release for March 2023 Update
  SPECS/mariner-release/mariner-release.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#4983 Upgrade gnupg2 to v2.4.0 to address CVE-2022-3515
  SPECS/gnupg2/gnupg2.signatures.json
  SPECS/gnupg2/gnupg2.spec
  SPECS/libgpg-error/libgpg-error.signatures.json
  SPECS/libgpg-error/libgpg-error.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5001 gnutls: Apply patch to fix CVE-2023-0361
  SPECS/gnutls/CVE-2023-0361.patch
  SPECS/gnutls/gnutls.spec
Labels: main

#5005 Build with tpm2-tss to enable TPM2 support in systemd-cryptenroll/systemd-cryptsetup
  SPECS/systemd/systemd.spec
Labels: main

#4962 upgrade harfbuzz version in 1.0 to fix CVE-2023-25193
  SPECS/freetype/freetype.spec
  SPECS/harfbuzz/CVE-2023-25193.patch
  SPECS/harfbuzz/harfbuzz.signatures.json
  SPECS/harfbuzz/harfbuzz.spec
  SPECS/pango/pango.spec
  SPECS/qt5-qtbase/qt5-qtbase.spec
  cgmanifest.json
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#5003 Patch emacs to fix CVE-2022-48337
  SPECS/emacs/CVE-2022-48337.patch
  SPECS/emacs/emacs.spec
Labels: main

#5014 Build Break: Add pkg-config to harfbuzz
  SPECS/harfbuzz/harfbuzz.spec
Labels: 1.0-dev

#5016 Add package advancecomp version 2.4
  SPECS-EXTENDED/advancecomp/advancecomp.signatures.json
  SPECS-EXTENDED/advancecomp/advancecomp.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#4924 Back ported tsflags=nodocs supported into tdnf
  SPECS/tdnf/tdnf-add-support-for-tsflags-nodocs.patch
  SPECS/tdnf/tdnf.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5012 Adding freefont to graphviz
  SPECS/graphviz/graphviz.spec
Labels: main

#5015 harfbuzz: add cairo as BR to resolve build-break
  SPECS/harfbuzz/harfbuzz.spec
Labels: 1.0-dev

#5017 Add package gdisk version 1.0.9
  SPECS-EXTENDED/gdisk/gdisk-libuuid.patch
  SPECS-EXTENDED/gdisk/gdisk.signatures.json
  SPECS-EXTENDED/gdisk/gdisk.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#5020 Remove: K3s 1.23.8 from CBL-Mariner
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/k3s/k3s-1.23.8.signatures.json
  SPECS/k3s/k3s-1.23.8.spec
  SPECS/k3s/vendor_build-1.23.8.patch
  cgmanifest.json
Labels: main

#4989 Add 5 packages to extended
  SPECS-EXTENDED/gtk-vnc/gtk-vnc.signatures.json
  SPECS-EXTENDED/gtk-vnc/gtk-vnc.spec
  SPECS-EXTENDED/ibus-m17n/ibus-m17n.signatures.json
  SPECS-EXTENDED/ibus-m17n/ibus-m17n.spec
  SPECS-EXTENDED/pngcrush/pngcrush.sgml
  SPECS-EXTENDED/pngcrush/pngcrush.signatures.json
  SPECS-EXTENDED/pngcrush/pngcrush.spec
  SPECS-EXTENDED/python-oauth2client/doc-fix.patch
  SPECS-EXTENDED/python-oauth2client/docs-build-fix.patch
  SPECS-EXTENDED/python-oauth2client/keyring-remove.patch
  SPECS-EXTENDED/python-oauth2client/python-oauth2client.signatures.json
  SPECS-EXTENDED/python-oauth2client/python-oauth2client.spec
  SPECS-EXTENDED/sox/sox-14.4.2-bug_1226675_fix.patch
  SPECS-EXTENDED/sox/sox-14.4.2-bug_1480678_fix.patch
  SPECS-EXTENDED/sox/sox-14.4.2-bug_1500553_fix.patch
  SPECS-EXTENDED/sox/sox-14.4.2-bug_1500554_fix.patch
  SPECS-EXTENDED/sox/sox-14.4.2-bug_1500570_fix.patch
  SPECS-EXTENDED/sox/sox-14.4.2-bug_1510923_fix.patch
  SPECS-EXTENDED/sox/sox-14.4.2-bug_1545867_fix.patch
  SPECS-EXTENDED/sox/sox-14.4.2-fsf_address_fix.patch
  SPECS-EXTENDED/sox/sox-14.4.2-hcom_stopwrite_big_endian_bug_fix.patch
  SPECS-EXTENDED/sox/sox-14.4.2-installcheck_fix.patch
  SPECS-EXTENDED/sox/sox-14.4.2-lpc10.patch
  SPECS-EXTENDED/sox/sox-14.4.2-lsx_symbols.patch
  SPECS-EXTENDED/sox/sox.signatures.json
  SPECS-EXTENDED/sox/sox.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#5027 Add python-webtest package version 3.0.0
  SPECS-EXTENDED/python-webtest/python-webtest.signatures.json
  SPECS-EXTENDED/python-webtest/python-webtest.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#5028 Add python-stestr package version 3.2.0
  SPECS-EXTENDED/python-stestr/python-stestr.signatures.json
  SPECS-EXTENDED/python-stestr/python-stestr.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#5029 Add python-oslo-i18n package version 5.1.0
  SPECS-EXTENDED/python-oslo-i18n/python-oslo-i18n.signatures.json
  SPECS-EXTENDED/python-oslo-i18n/python-oslo-i18n.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#5026 Fix python-cherrypy ptest failing
  SPECS/python-cherrypy/python-cherrypy.spec
Labels: ptest, main

#4967 gRPC: add python binding for gRPC (python3-grpcio) for aarch64
  SPECS/grpc/grpc.spec
Labels: main

#5031 Add phodav package version 3.0
  SPECS-EXTENDED/phodav/phodav.signatures.json
  SPECS-EXTENDED/phodav/phodav.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#5032 Add pacemaker package version 2.1.5
  SPECS-EXTENDED/pacemaker/pacemaker.signatures.json
  SPECS-EXTENDED/pacemaker/pacemaker.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#5033 Add libxmlb package version 0.3.11
  SPECS-EXTENDED/libxmlb/libxmlb.signatures.json
  SPECS-EXTENDED/libxmlb/libxmlb.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#5034 Add libindicator package version 12.10.1
  SPECS-EXTENDED/libindicator/libindicator.signatures.json
  SPECS-EXTENDED/libindicator/libindicator.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#5035 Add libgovirt package version 0.3.9
  SPECS-EXTENDED/libgovirt/0001-Fix-i18n-generation.patch
  SPECS-EXTENDED/libgovirt/libgovirt.signatures.json
  SPECS-EXTENDED/libgovirt/libgovirt.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#5036 Add netsniff-ng package version 0.6.8
  SPECS-EXTENDED/netsniff-ng/netsniff-ng.signatures.json
  SPECS-EXTENDED/netsniff-ng/netsniff-ng.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#5037 Add geoclue2 package version 2.7.0
  SPECS-EXTENDED/geoclue2/geoclue2.signatures.json
  SPECS-EXTENDED/geoclue2/geoclue2.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#5038 Add booth package version 1.0
  SPECS-EXTENDED/booth/booth.signatures.json
  SPECS-EXTENDED/booth/booth.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#5039 Add GeoIP-GeoLite-data package version 2018.06
  SPECS-EXTENDED/GeoIP-GeoLite-data/GeoIP-GeoLite-data.signatures.json
  SPECS-EXTENDED/GeoIP-GeoLite-data/GeoIP-GeoLite-data.spec
  SPECS-EXTENDED/GeoIP-GeoLite-data/LICENSE
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#5045 emacs: Apply upstream patches to fix CVE-2022-48338, CVE-2022-48339
  SPECS/emacs/CVE-2022-48338.patch
  SPECS/emacs/CVE-2022-48339.patch
  SPECS/emacs/emacs.spec
Labels: main

#5052 curl: upgrade to version 7.88.1 to address CVE-2023-23914, CVE-2023-23915, CVE-2023-23916
  SPECS/curl/CVE-2022-43551.patch
  SPECS/curl/CVE-2022-43552.patch
  SPECS/curl/curl.signatures.json
  SPECS/curl/curl.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#5018 Add package pykickstart version 3.36
  SPECS-EXTENDED/pykickstart/pykickstart.signatures.json
  SPECS-EXTENDED/pykickstart/pykickstart.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#5040 Add 4 packages to extended
  SPECS-EXTENDED/gavl/gavl-1.1.1-system_libgdither.patch
  SPECS-EXTENDED/gavl/gavl.signatures.json
  SPECS-EXTENDED/gavl/gavl.spec
  SPECS-EXTENDED/libpng12/libpng12-multilib.patch
  SPECS-EXTENDED/libpng12/libpng12-pngconf.patch
  SPECS-EXTENDED/libpng12/libpng12.signatures.json
  SPECS-EXTENDED/libpng12/libpng12.spec
  SPECS-EXTENDED/libpng15/libpng15-CVE-2013-6954.patch
  SPECS-EXTENDED/libpng15/libpng15-CVE-2018-13785.patch
  SPECS-EXTENDED/libpng15/libpng15.signatures.json
  SPECS-EXTENDED/libpng15/libpng15.spec
  SPECS-EXTENDED/libpng15/pngusr.dfa
  SPECS-EXTENDED/mythes-en/mythes-en.python3.patch
  SPECS-EXTENDED/mythes-en/mythes-en.signatures.json
  SPECS-EXTENDED/mythes-en/mythes-en.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#5053 curl: upgrade to 7.88.1 to address CVE-2023-23914, CVE-2023-23915, CVE-2023-23916
  SPECS/curl/CVE-2022-43551.patch
  SPECS/curl/CVE-2022-43552.patch
  SPECS/curl/curl.signatures.json
  SPECS/curl/curl.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, main

#5055 rpm-ostree : patched vendor package hyper to fix CVE-2022-31394
  SPECS/rpm-ostree/CVE-2022-31394.patch
  SPECS/rpm-ostree/rpm-ostree.spec
Labels: main

#4949 Fixing the TestRPM-HydratedBuild pipeline to not report a toolchain error
  toolkit/Makefile
  toolkit/docs/building/building.md
  toolkit/scripts/pkggen.mk
  toolkit/tools/scheduler/scheduler.go
  toolkit/tools/scheduler/schedulerutils/graphbuildstate.go
  toolkit/tools/scheduler/schedulerutils/printresults.go
Labels: ptest, go, main

#5064 rust: update signatures to fix build break
  SPECS/rust/rust.signatures.json
Labels: 1.0-dev

#5007 Add elixir package to Mariner to support rabbitmq
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/elixir/elixir.signatures.json
  SPECS/elixir/elixir.spec
  cgmanifest.json
Labels: main

#5088 Revert "rust: update signatures to fix build break"
  SPECS/rust/rust.signatures.json
Labels: 1.0-dev

#5086 httpd: upgrade httpd to 2.4.56 to fix CVE-2023-27522, CVE-2023-25690
  SPECS/httpd/httpd.signatures.json
  SPECS/httpd/httpd.spec
  cgmanifest.json
Labels: 1.0-dev

#5089 httpd: upgrade httpd to 2.4.56 to fix CVE-2023-27522, CVE-2023-25690
  SPECS/httpd/httpd.signatures.json
  SPECS/httpd/httpd.spec
  cgmanifest.json
Labels: main

#5095 Change source0 for python-msal & python-msrestazure
  SPECS-EXTENDED/python-msal/python-msal.signatures.json
  SPECS-EXTENDED/python-msal/python-msal.spec
  SPECS-EXTENDED/python-msrestazure/python-msrestazure.signatures.json
  SPECS-EXTENDED/python-msrestazure/python-msrestazure.spec
Labels: main

#5094 systemd-bootstrap: fix CVE-2022-4415
  SPECS/systemd/systemd-bootstrap.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5092 heimdal: add patch for CVE-2022-45142
  SPECS/heimdal/CVE-2022-45142.patch
  SPECS/heimdal/heimdal.spec
Labels: main

#5093 heimdal: add patch for CVE-2022-45142
  SPECS/heimdal/CVE-2022-45142.patch
  SPECS/heimdal/heimdal.spec
Labels: 1.0-dev

#5098 moby-engine address CVE-2023-25153
  SPECS/moby-engine/CVE-2023-25153.patch
  SPECS/moby-engine/moby-engine.spec
Labels: main

#5079 python-werkzeug: fix for CVE-2023-23934
  SPECS/python-werkzeug/CVE-2023-25577.patch
  SPECS/python-werkzeug/python-werkzeug.signatures.json
  SPECS/python-werkzeug/python-werkzeug.spec
  cgmanifest.json
Labels: security, main

#5091 upgrade rust to 1.68.0, address some vendoring issues and promote libgit2 to core
  SPECS/libgit2/libgit2.signatures.json
  SPECS/libgit2/libgit2.spec
  SPECS/rust/generate_source_tarball.sh
  SPECS/rust/rust.signatures.json
  SPECS/rust/rust.spec
  cgmanifest.json
Labels: main

#4948 Add PostInstallScript entry to docs, add note to ExtraCommandLine
  toolkit/docs/formats/imageconfig.md
Labels: documentation, main

#5106 sudo: update sudo to 1.9.13p3 to fix CVE-2023-27320
  SPECS/sudo/sudo.signatures.json
  SPECS/sudo/sudo.spec
  cgmanifest.json
Labels: 1.0-dev

#5104 sudo: update sudo to 1.9.13p3 to fix CVE-2023-27320
  SPECS/sudo/sudo.signatures.json
  SPECS/sudo/sudo.spec
  cgmanifest.json
Labels: main

#5117 perl-WWW-Curl: introduce patches to work around macro bug
  SPECS/perl-WWW-Curl/WWW-Curl-4.17-Adapt-to-curl-7.87.0.patch
  SPECS/perl-WWW-Curl/WWW-Curl-4.17-Work-around-a-macro-bug-in-curl-7.87.0.patch
  SPECS/perl-WWW-Curl/perl-WWW-Curl.spec
Labels: 1.0-dev

#5112 vim: Upgrade vim to 9.0.1402 Fix CVE-2023-1264
  SPECS/vim/vim.signatures.json
  SPECS/vim/vim.spec
  cgmanifest.json
Labels: 1.0-dev

#5118 Nopatch kernel to address CVE-2023-22996, CVE-2023-22997, CVE-2023-23001, CVE-2023-23003, CVE-2023-23005, CVE-2022-1943
  SPECS/kernel/CVE-2022-1943.nopatch
  SPECS/kernel/CVE-2023-22996.nopatch
  SPECS/kernel/CVE-2023-22997.nopatch
  SPECS/kernel/CVE-2023-23001.nopatch
  SPECS/kernel/CVE-2023-23003.nopatch
  SPECS/kernel/CVE-2023-23005.nopatch
Labels: security, 1.0-dev

#4923 Adding fstrm to SPEC Extended
  SPECS-EXTENDED/fstrm/fstrm.signatures.json
  SPECS-EXTENDED/fstrm/fstrm.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#5122 rpm-ostree: introduce patch to workaround a breaking lint
  SPECS/rpm-ostree/rpm-ostree-drop-lint-which-treats-warning-as-error.patch
  SPECS/rpm-ostree/rpm-ostree.spec
Labels: main

#5121 Updated sources paths for `ca-certificates`.
  SPECS/ca-certificates/ca-certificates.spec
  SPECS/prebuilt-ca-certificates-base/prebuilt-ca-certificates-base.spec
  SPECS/prebuilt-ca-certificates/prebuilt-ca-certificates.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5128 gnupg2: add correct version of libgpg-error-devel as BR
  SPECS/gnupg2/gnupg2.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5063 Update CBL-Mariner build prerequisites
  toolkit/docs/building/prerequisites-mariner.md
  toolkit/docs/building/prerequisites-ubuntu.md
Labels: main

#4992 Separating buildAttempts & checkAttempts in build tooling & edge case fix
  toolkit/tools/scheduler/schedulerutils/buildworker.go
Labels: main

#5134 kata-containers: integrate fix to reduce UVM memory consumption
  SPECS/kata-containers/kata-containers.spec
  SPECS/kata-containers/runtime-reduce-uvm-high-mem-footprint.patch
Labels: main

#5135 Enable wireguard as kernel module
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5141 ccache: update to 4.8
  SPECS/ccache/ccache.signatures.json
  SPECS/ccache/ccache.spec
  cgmanifest.json
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5145 Update mlnx-ofa_kernel's BuildRequires to use kernel 5.15.87.1
  SPECS/mlnx-ofa_kernel/mlnx-ofa_kernel.spec
Labels: main

#5101 Added signing stage for livepatches pipeline.
  .config/CredScanSuppressions.json
  .github/CODEOWNERS
  pipelines/common/libs/build_tools.sh
  pipelines/common/libs/file_tools.sh
  pipelines/common/libs/rpm_tools.sh
  pipelines/common/scripts/PackageSignedRPMs.sh
  pipelines/common/utilities/Configure-1ES.sh
  pipelines/common/utilities/build_tools.sh
  pipelines/livepatching/BuildLivepatch.sh
  pipelines/livepatching/BuildLivepatchSigned.sh
  pipelines/livepatching/DeployLivepatch.yml
  pipelines/livepatching/ExtractKernelModules.sh
Labels: main

#5150 Add wireguard-tools package version 1.0.20210914
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/wireguard-tools/wireguard-tools.conf
  SPECS/wireguard-tools/wireguard-tools.signatures.json
  SPECS/wireguard-tools/wireguard-tools.spec
  cgmanifest.json
Labels: main

#5153 build nginx with ngx_http_realip_module
  SPECS/nginx/nginx.spec
Labels: main

#5148 Nopatch kernel to address CVE-2022-3110, CVE-2022-3707
  SPECS/kernel/CVE-2022-3110.nopatch
  SPECS/kernel/CVE-2022-3707.nopatch
Labels: security, 1.0-dev

#5137 dnsmasq: patch CVE-2023-28450
  SPECS/dnsmasq/CVE-2023-28450.patch
  SPECS/dnsmasq/dnsmasq.spec
Labels: security, main

#5138 dnsmasq: patch CVE-2023-28450
  SPECS/dnsmasq/CVE-2023-28450.patch
  SPECS/dnsmasq/dnsmasq.spec
Labels: security, 1.0-dev

#5158 Patched `emacs` to fix CVE-2023-28617.
  SPECS/emacs/CVE-2023-28617.patch
  SPECS/emacs/emacs.spec
Labels: main

#5143 Promote atop and htop from extended to core
  SPECS/atop/9cb119713b5e6be43671fe1856fb4bd49ff91fa7.patch
  SPECS/atop/atop-2.3.0-newer-gcc.patch
  SPECS/atop/atop-sysconfig.patch
  SPECS/atop/atop.d
  SPECS/atop/atop.signatures.json
  SPECS/atop/atop.spec
  SPECS/atop/nvme_support.patch
  SPECS/htop/htop.signatures.json
  SPECS/htop/htop.spec
Labels: main

#4210 Move toolchain RPMs to a dedicated location in ./build/toolchain_rpms
  toolkit/Makefile
  toolkit/docs/building/building.md
  toolkit/resources/manifests/package/local.repo
  toolkit/scripts/imggen.mk
  toolkit/scripts/pkggen.mk
  toolkit/scripts/toolchain.mk
  toolkit/scripts/tools.mk
  toolkit/tools/depsearch/depsearch.go
  toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
  toolkit/tools/imagepkgfetcher/imagepkgfetcher.go
  toolkit/tools/internal/packagerepo/repocloner/repocloner.go
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
  toolkit/tools/internal/pkggraph/pkggraph.go
  toolkit/tools/internal/pkggraph/pkggraph_test.go
  toolkit/tools/internal/pkgjson/pkgjson.go
  toolkit/tools/internal/safechroot/safechroot.go
  toolkit/tools/pkgworker/pkgworker.go
  toolkit/tools/scheduler/buildagents/chrootagent.go
  toolkit/tools/scheduler/buildagents/definition.go
  toolkit/tools/scheduler/scheduler.go
  toolkit/tools/scheduler/schedulerutils/buildlist.go
  toolkit/tools/specreader/specreader.go
Labels: Tools, main, DevEx

#5146 Update cloud-hypervisor to v30.0, kernel-mshv to v5.15.98
  SPECS/cloud-hypervisor/cloud-hypervisor.signatures.json
  SPECS/cloud-hypervisor/cloud-hypervisor.spec
  SPECS/cloud-hypervisor/config.toml
  SPECS/kernel-mshv/config
  SPECS/kernel-mshv/kernel-mshv.signatures.json
  SPECS/kernel-mshv/kernel-mshv.spec
  cgmanifest.json
Labels: main

#4214 Prioritize already cached RPMs before using online repos
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
Labels: Tools, main, DevEx

#5162 msft-golang: bump version to 1.19.7 to address CVE-2022-41722, CVE-2022-41724, CVE-2022-41725, CVE-2022-41723, CVE-2023-24532
  SPECS/msft-golang/msft-golang.signatures.json
  SPECS/msft-golang/msft-golang.spec
  cgmanifest.json
Labels: security, main

#5168 Update old go file formatting with go-tidy-all.
  toolkit/tools/graphanalytics/graphanalytics.go
  toolkit/tools/imagegen/configuration/kernelcommandline.go
  toolkit/tools/imagegen/configuration/mountidentifier.go
  toolkit/tools/imagegen/configuration/veritydisk.go
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/internal/buildpipeline/buildpipeline.go
  toolkit/tools/internal/pkggraph/pkggraph_test.go
  toolkit/tools/internal/pkgjson/pkgjson.go
  toolkit/tools/internal/safechroot/safechroot.go
  toolkit/tools/pkg/rpmssnapshot/rpmssnapshot.go
  toolkit/tools/scheduler/schedulerutils/buildworker.go
  toolkit/tools/scheduler/schedulerutils/preparerequest.go
Labels: Tools, main

#5142 Add essential maven packages
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/google-guice/create_source_tarball.sh
  SPECS/google-guice/google-guice.signatures.json
  SPECS/google-guice/google-guice.spec
  SPECS/javapackages-bootstrap/0001-Bind-to-OpenJDK-11-for-runtime.patch
  SPECS/javapackages-bootstrap/javapackages-bootstrap-PACKAGE-LICENSING
  SPECS/javapackages-bootstrap/javapackages-bootstrap.signatures.json
  SPECS/javapackages-bootstrap/javapackages-bootstrap.spec
  SPECS/javapackages-tools/javapackages-tools.spec
  SPECS/maven-compiler-plugin/0001-plexus-languages-1.0.patch
  SPECS/maven-compiler-plugin/0002-MCOMPILER-359-Fix-for-NPE.patch
  SPECS/maven-compiler-plugin/maven-compiler-plugin.signatures.json
  SPECS/maven-compiler-plugin/maven-compiler-plugin.spec
  SPECS/maven-jar-plugin/maven-jar-plugin.signatures.json
  SPECS/maven-jar-plugin/maven-jar-plugin.spec
  SPECS/maven-resolver/0001-Remove-use-of-deprecated-SHA-1-and-MD5-algorithms.patch
  SPECS/maven-resolver/maven-resolver.signatures.json
  SPECS/maven-resolver/maven-resolver.spec
  SPECS/maven-resources-plugin/maven-resources-plugin.signatures.json
  SPECS/maven-resources-plugin/maven-resources-plugin.spec
  SPECS/maven-surefire/0001-Port-to-TestNG-6.11.patch
  SPECS/maven-surefire/0002-Disable-JUnit-4.8-test-grouping.patch
  SPECS/maven-surefire/0003-Port-to-maven-shared-utils-3.3.3.patch
  SPECS/maven-surefire/cpl-v10.html
  SPECS/maven-surefire/generate_source_tarball.sh
  SPECS/maven-surefire/maven-surefire.signatures.json
  SPECS/maven-surefire/maven-surefire.spec
  SPECS/maven-wagon/maven-wagon.signatures.json
  SPECS/maven-wagon/maven-wagon.spec
  SPECS/sisu/0001-Remove-dependency-on-glassfish-servlet-api.patch
  SPECS/sisu/sisu-OSGi-import-guava.patch
  SPECS/sisu/sisu-ignored-tests.patch
  SPECS/sisu/sisu-inject.pom
  SPECS/sisu/sisu-osgi-api.patch
  SPECS/sisu/sisu-parent.pom
  SPECS/sisu/sisu-plexus.pom
  SPECS/sisu/sisu.signatures.json
  SPECS/sisu/sisu.spec
  cgmanifest.json
Labels: main

#5178 Updated `telegraf` to 1.26.0 to fix CVE-2022-23471
  SPECS/telegraf/generate_source_tarball.sh
  SPECS/telegraf/telegraf.signatures.json
  SPECS/telegraf/telegraf.spec
  cgmanifest.json
Labels: main

#5159 Add Rabbitmq-server Package to Mariner
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/rabbitmq-server/executeRabbitMQTests.sh
  SPECS/rabbitmq-server/generate-rabbitmq-server-tarball.sh
  SPECS/rabbitmq-server/rabbitmq-server.signatures.json
  SPECS/rabbitmq-server/rabbitmq-server.spec
  SPECS/rabbitmq-server/rabbitmqHexCacheMakefile
  cgmanifest.json
Labels: main

#5183 Bump Mariner 1.0 Release For March 2023 Update 2
  SPECS/mariner-release/mariner-release.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#5172 curl: bump version to 8.0.1 to address CVE-2023-27533 to CVE-2023-27538
  SPECS/curl/curl.signatures.json
  SPECS/curl/curl.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, main

#5149 Translate and update build flow diagram into mermaid diagram
  toolkit/docs/how_it_works/0_intro.md
  toolkit/docs/how_it_works/images/flow.png
  toolkit/docs/how_it_works/images/sources/flow.dot
Labels: main

#5195 javapackages-tools: dos2unix spec to resolve build break
  SPECS/javapackages-tools/javapackages-tools.spec
Labels: main

#5169 Update contribution guide to include more detailed instructions
  CONTRIBUTING.md
Labels: main

#5192 Patching CVE-2023-0464 (openssl 1.1.1k)
  SPECS/openssl/CVE-2023-0464.patch
  SPECS/openssl/openssl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5200 Patching CVE-2023-0460 (openssl) for 1.0-dev
  SPECS/openssl/CVE-2023-0464.patch
  SPECS/openssl/openssl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#5119 Promoting 13 extended packages into core
  SPECS/apache-commons-cli/CLI-253-workaround.patch
  SPECS/apache-commons-cli/apache-commons-cli.signatures.json
  SPECS/apache-commons-cli/apache-commons-cli.spec
  SPECS/apache-commons-lang3/apache-commons-lang3.signatures.json
  SPECS/apache-commons-lang3/apache-commons-lang3.spec
  SPECS/apache-commons-lang3/build.xml
  SPECS/apache-commons-lang3/default.properties
  SPECS/apache-commons-logging/apache-commons-logging.signatures.json
  SPECS/apache-commons-logging/apache-commons-logging.spec
  SPECS/apache-commons-logging/commons-logging-1.1.3-src-junit.diff
  SPECS/apache-commons-logging/commons-logging-1.2-sourcetarget.patch
  SPECS/apache-commons-logging/commons-logging-api-1.1.pom
  SPECS/apache-commons-logging/commons-logging-manifests.patch
  SPECS/atinject/LICENSE-2.0.txt
  SPECS/atinject/MANIFEST-TCK.MF
  SPECS/atinject/MANIFEST.MF
  SPECS/atinject/atinject.signatures.json
  SPECS/atinject/atinject.spec
  SPECS/cal10n/cal10n-0.7.7-sourcetarget.patch
  SPECS/cal10n/cal10n.signatures.json
  SPECS/cal10n/cal10n.spec
  SPECS/glassfish-servlet-api/LICENSE-2.0.txt
  SPECS/glassfish-servlet-api/glassfish-servlet-api-build.properties
  SPECS/glassfish-servlet-api/glassfish-servlet-api-build.xml
  SPECS/glassfish-servlet-api/glassfish-servlet-api.signatures.json
  SPECS/glassfish-servlet-api/glassfish-servlet-api.spec
  SPECS/guava/guava-25.0-java8compat.patch
  SPECS/guava/guava.signatures.json
  SPECS/guava/guava.spec
  SPECS/hamcrest/hamcrest.spec
  SPECS/javassist/javassist-java8-compat.patch
  SPECS/javassist/javassist-osgi.patch
  SPECS/javassist/javassist.signatures.json
  SPECS/javassist/javassist.spec
  SPECS/jsr-305/NOTICE-CC-BY.txt
  SPECS/jsr-305/jsr-305-ri-build.xml
  SPECS/jsr-305/jsr-305.signatures.json
  SPECS/jsr-305/jsr-305.spec
  SPECS/junit/junit.spec
  SPECS/plexus-classworlds/plexus-classworlds-build.xml
  SPECS/plexus-classworlds/plexus-classworlds.signatures.json
  SPECS/plexus-classworlds/plexus-classworlds.spec
  SPECS/plexus-interpolation/plexus-interpolation-build.xml
  SPECS/plexus-interpolation/plexus-interpolation.signatures.json
  SPECS/plexus-interpolation/plexus-interpolation.spec
  SPECS/plexus-utils/LICENSE-2.0.txt
  SPECS/plexus-utils/plexus-utils-build.xml
  SPECS/plexus-utils/plexus-utils.signatures.json
  SPECS/plexus-utils/plexus-utils.spec
  SPECS/slf4j/LICENSE-2.0.txt
  SPECS/slf4j/build-remove-slf4j_api-binder.patch
  SPECS/slf4j/slf4j-commons-lang3.patch
  SPECS/slf4j/slf4j.signatures.json
  SPECS/slf4j/slf4j.spec
  cgmanifest.json
Labels: main
