Repository microsoft/azurelinux, pull requests merged in 2023-04, with the labels that each got.

#5202 Updated packages with a BR on `libtiff`.
  SPECS-EXTENDED/libgxps/libgxps.spec
  SPECS-EXTENDED/netpbm/netpbm.spec
  SPECS-EXTENDED/openjpeg2/openjpeg2.spec
  SPECS/gd/gd.spec
  SPECS/gdk-pixbuf2/gdk-pixbuf2.spec
  SPECS/lcms2/lcms2.spec
  SPECS/libgdiplus/libgdiplus.spec
  SPECS/libtiff/libtiff.spec
  SPECS/libwebp/libwebp.spec
Labels: main

#5194 R: fix build with curl >= 8.0.0
  SPECS/R/0001-configure-fix-compilation-with-curl-8.0.0.patch
  SPECS/R/R.spec
Labels: main

#5170 Enable CONFIG_NET_CLS_FLOWER as module
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5203 Adding maven-local xmvn and othe packages
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/hamcrest/hamcrest.spec
  SPECS/javapackages-tools/javapackages-tools.spec
  SPECS/maven/maven.spec
  SPECS/plexus-cipher/plexus-cipher.signatures.json
  SPECS/plexus-cipher/plexus-cipher.spec
  SPECS/plexus-containers/LICENSE-2.0.txt
  SPECS/plexus-containers/LICENSE.MIT
  SPECS/plexus-containers/plexus-containers.signatures.json
  SPECS/plexus-containers/plexus-containers.spec
  SPECS/plexus-sec-dispatcher/LICENSE-2.0.txt
  SPECS/plexus-sec-dispatcher/plexus-sec-dispatcher-pom.patch
  SPECS/plexus-sec-dispatcher/plexus-sec-dispatcher.signatures.json
  SPECS/plexus-sec-dispatcher/plexus-sec-dispatcher.spec
  SPECS/xmvn/xmvn.signatures.json
  SPECS/xmvn/xmvn.spec
  cgmanifest.json
Labels: main

#5215 PyTorch: Fix CVE-2022-25882 by upgrading PyTorch to 2.0.0
  SPECS/pytorch/pytorch.signatures.json
  SPECS/pytorch/pytorch.spec
  cgmanifest.json
Labels: main

#5217 cloud-hypervisor: patch vendored versionize crate to fix CVE-2023-28448
  SPECS/cloud-hypervisor/CVE-2023-28448.patch
  SPECS/cloud-hypervisor/cloud-hypervisor.spec
Labels: main

#5216 Add missing runtime dependency to sos package
  SPECS/sos/sos.spec
Labels: main

#5182 Upgrade opa to 0.50.2
  SPECS/opa/0001-Make-telemetry-opt-out.patch
  SPECS/opa/0001-Skip-tests-requiring-network.patch
  SPECS/opa/0001-Warn-users-about-WebAssembly-missing.patch
  SPECS/opa/opa.signatures.json
  SPECS/opa/opa.spec
  cgmanifest.json
Labels: main

#5223 build nginx with ngx_http_gzip_static_module
  SPECS/nginx/nginx.spec
Labels: main

#5211 Address Cloud-init ptest failure
  SPECS/cloud-init/cloud-init.spec
Labels: main

#5230 Patch xinetd with CVE-2013-4342 fix
  SPECS/xinetd/CVE-2013-4342.patch
  SPECS/xinetd/xinetd.spec
Labels: main

#5229 Patch xinetd with CVE-2013-4342
  SPECS/xinetd/CVE-2013-4342.patch
  SPECS/xinetd/xinetd.spec
Labels: 1.0-dev

#5231 msft-golang: upgrade to 1.19.8 to address CVE-2023-24534, CVE-2023-24536, CVE-2023-24537, CVE-2023-24538
  SPECS/msft-golang/msft-golang.signatures.json
  SPECS/msft-golang/msft-golang.spec
  cgmanifest.json
Labels: security, main

#5147 kernel-uvm: consume dom0 source
  SPECS/kata-containers/kata-containers.spec
  SPECS/kata-containers/kata-osbuilder.sh
  SPECS/kernel-uvm/config
  SPECS/kernel-uvm/kernel-uvm.signatures.json
  SPECS/kernel-uvm/kernel-uvm.spec
  cgmanifest.json
Labels: main

#5191 kernel-mshv: add back config
  SPECS/kernel-mshv/config
  SPECS/kernel-mshv/kernel-mshv.signatures.json
  SPECS/kernel-mshv/kernel-mshv.spec
Labels: main

#5213 Updated livepatch spec template to print more logs.
  toolkit/scripts/livepatching/template_livepatch.spec
Labels: main

#5233 Fix unattended flag handling
  toolkit/scripts/imggen.mk
Labels: main

#5225 Updating maven3 to match maven changes
  SPECS/maven/maven.spec
  SPECS/maven/maven3.spec
Labels: main

#5240 kata-containers: update kata-osbuilder.sh signature
  SPECS/kata-containers/kata-containers.signatures.json
Labels: main

#5237 Patch cloud-hypervisor for CVE-2023-28448 in vendored versionize crate
  SPECS/cloud-hypervisor/CVE-2023-28448.patch
  SPECS/cloud-hypervisor/cloud-hypervisor.spec
Labels: 1.0-dev

#5238 Fix CVE-2021-35516 and CVE-2021-35517 by upgrading common-compress to 1.21 in javapackages-boostrap
  SPECS/javapackages-bootstrap/0001-Remove-usage-of-ArchiveStreamFactory.patch
  SPECS/javapackages-bootstrap/ignore.upstream.patch.txt
  SPECS/javapackages-bootstrap/javapackages-bootstrap.signatures.json
  SPECS/javapackages-bootstrap/javapackages-bootstrap.spec
Labels: main

#5241 Enable loadable modules and -devel subpackage for kernel-uvm
  SPECS/kernel-uvm/config
  SPECS/kernel-uvm/kernel-uvm.signatures.json
  SPECS/kernel-uvm/kernel-uvm.spec
Labels: main

#4846 Add dracut-megaraid package
  SPECS/dracut/dracut.signatures.json
  SPECS/dracut/dracut.spec
  SPECS/dracut/megaraid.conf
  SPECS/initramfs/initramfs.spec
Labels: main

#5239 Fixing `UNATTENDED_INSTALLER` argument.
  toolkit/scripts/imggen.mk
Labels: 1.0-dev

#5249 Bump Mariner 2.0 Release for April 2023 Update
  SPECS/mariner-release/mariner-release.spec
Labels: main

#5250 Fix Mariner Release Bump
  SPECS/mariner-release/mariner-release.spec
Labels: main

#5176 Don't make go modules owned by root
  toolkit/scripts/tools.mk
Labels: Tools, go, main, DevEx

#5242 clang-16 and llvm-16: add new SPECS
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/clang/clang-16.signatures.json
  SPECS/clang/clang-16.spec
  SPECS/llvm/llvm-16.signatures.json
  SPECS/llvm/llvm-16.spec
  cgmanifest.json
Labels: main

#5247 Add missing pytorch runtime dependencies
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/python-mpmath/python-mpmath-1.0.0-sphinx.patch
  SPECS/python-mpmath/python-mpmath.signatures.json
  SPECS/python-mpmath/python-mpmath.spec
  SPECS/python-networkx/python-networkx-doc.patch
  SPECS/python-networkx/python-networkx-test.patch
  SPECS/python-networkx/python-networkx.signatures.json
  SPECS/python-networkx/python-networkx.spec
  SPECS/pytorch/pytorch.spec
  SPECS/sympy/sympy-circuitplot.patch
  SPECS/sympy/sympy.signatures.json
  SPECS/sympy/sympy.spec
  cgmanifest.json
Labels: main

#5246 Add kata-containers-cc package
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/kata-containers-cc/containerd-for-cc-override.conf
  SPECS/kata-containers-cc/kata-containers-cc.signatures.json
  SPECS/kata-containers-cc/kata-containers-cc.spec
  SPECS/kata-containers-cc/mariner-coco-build-uvm-image.service
  SPECS/kata-containers-cc/mariner-coco-build-uvm-image.sh
  SPECS/kata-containers-cc/pause-image.service
  SPECS/kata-containers-cc/pause-image.sh
  SPECS/kata-containers-cc/runtime.yaml
  cgmanifest.json
Labels: main

#5198 Adding XFS as a root filesystem type
  SPECS-SIGNED/grub2-efi-binary-signed/grub2-efi-binary-signed.spec
  SPECS/grub2/grub2.spec
  SPECS/initramfs/fscks.conf
  SPECS/initramfs/initramfs.signatures.json
  SPECS/initramfs/initramfs.spec
  toolkit/docs/building/prerequisites-mariner.md
  toolkit/docs/building/prerequisites-ubuntu.md
  toolkit/docs/formats/imageconfig.md
  toolkit/resources/imageconfigs/packagelists/iso-initrd-packages-arm64.json
  toolkit/resources/imageconfigs/packagelists/iso-initrd-packages.json
  toolkit/tools/imagegen/diskutils/diskutils.go
  toolkit/tools/imagegen/installutils/installutils.go
Labels: main

#5272 Patched containerd version to address CVE-2023-25173 and CVE-2023-25153 | Upgrade k3s
  SPECS/k3s/k3s-1.25.5.signatures.json
  SPECS/k3s/k3s-1.25.5.spec
  SPECS/k3s/k3s.signatures.json
  SPECS/k3s/k3s.spec
Labels: main

#5276 Livepatched CVE-2023-1281 in kernel 5.15.94.1-1.cm2.
  SPECS-SIGNED/livepatch-5.15.94.1-1.cm2-signed/livepatch-5.15.94.1-1.cm2-signed.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/livepatch-5.15.94.1-1.cm2/CVE-2023-1281.patch
  SPECS/livepatch-5.15.94.1-1.cm2/livepatch-5.15.94.1-1.cm2.spec
Labels: main

#5280 Fix uninstallation of InfluxDB package
  SPECS/influxdb/influxdb.spec
Labels: main

#5285 openssl: patch CVE-2023-0465 and CVE-2023-0466
  SPECS/openssl/CVE-2023-0465.patch
  SPECS/openssl/CVE-2023-0466.patch
  SPECS/openssl/openssl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5212 Adding pip requirements and small readme file to toolchain scripts
  .github/workflows/check-entangled-specs.yml
  .github/workflows/check-livepatches.yml
  .github/workflows/check-spec.yml
  .github/workflows/check-static-glibc.yml
  toolkit/scripts/requirements.txt
Labels: main

#5293 Run go-fmt on toolkit
  toolkit/tools/imagegen/configuration/kernelcommandline.go
  toolkit/tools/imagegen/configuration/veritydisk.go
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/internal/buildpipeline/buildpipeline.go
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
  toolkit/tools/internal/pkggraph/pkggraph.go
  toolkit/tools/internal/pkggraph/pkggraph_test.go
  toolkit/tools/internal/pkgjson/pkgjson.go
  toolkit/tools/internal/safechroot/safechroot.go
Labels: 1.0-dev

#5283 Enable NVME_TCP and NVME_RDMA modules
  SPECS-SIGNED/kernel-hci-signed/kernel-hci-signed.spec
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-hci/config
  SPECS/kernel-hci/kernel-hci.signatures.json
  SPECS/kernel-hci/kernel-hci.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5294 moby-runc: Upgrade to 1.1.5 to fix CVE-2023-28642, CVE-2023-27561, CVE-2023-25809
  SPECS/moby-runc/generate-sources.sh
  SPECS/moby-runc/moby-runc.signatures.json
  SPECS/moby-runc/moby-runc.spec
  cgmanifest.json
Labels: 1.0-dev

#5287 Cloud-init disable root
  toolkit/imageconfigs/additionalconfigs/cloud-init.cfg
Labels: 1.0-dev

#5278 Add an explicit constraint on llvm-devel < 16.0.0 for bcc, ldd & mesa
  SPECS/bcc/bcc.spec
  SPECS/lld/lld.spec
  SPECS/mesa/mesa.spec
Labels: main

#5292 Enable CONFIG_HIST_TRIGGERS in kernel
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5296 Remove epoch from some spec files
  SPECS/maven-resolver/maven-resolver.spec
  SPECS/sisu/sisu.spec
Labels: main

#5298 Revert Add kata-containers-cc package (#5246)
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/kata-containers-cc/containerd-for-cc-override.conf
  SPECS/kata-containers-cc/kata-containers-cc.signatures.json
  SPECS/kata-containers-cc/kata-containers-cc.spec
  SPECS/kata-containers-cc/mariner-coco-build-uvm-image.service
  SPECS/kata-containers-cc/mariner-coco-build-uvm-image.sh
  SPECS/kata-containers-cc/pause-image.service
  SPECS/kata-containers-cc/pause-image.sh
  SPECS/kata-containers-cc/runtime.yaml
  cgmanifest.json
Labels: main

#5299 Also pass toolchain dir to external package cache fetcher
  toolkit/scripts/imggen.mk
Labels: main

#5302 Bump Mariner 1.0 release for April 2023 update
  SPECS/mariner-release/mariner-release.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#5300 Rename clang-16 to clang16 and llvm-16 to llvm16
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/bcc/bcc.spec
  SPECS/clang/clang16.signatures.json
  SPECS/clang/clang16.spec
  SPECS/lld/lld.spec
  SPECS/llvm/llvm16.signatures.json
  SPECS/llvm/llvm16.spec
  SPECS/mesa/mesa.spec
  cgmanifest.json
Labels: main

#5308 Upgrade bundled njs version in nginx to 0.7.12 to fix CVE-2020-19692, CVE-2020-19695
  SPECS/nginx/nginx.signatures.json
  SPECS/nginx/nginx.spec
Labels: security, 1.0-dev

#5309 Upgrade bundled njs version in nginx to 0.7.12 to fix CVE-2020-19692, CVE-2020-19695
  SPECS/nginx/nginx.signatures.json
  SPECS/nginx/nginx.spec
Labels: security, main

#5307 Fix CVE-2021-45985 in package lua
  SPECS/lua/CVE-2021-45985.patch
  SPECS/lua/lua.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5282 Enable serial console for ISO installer
  toolkit/resources/assets/isomaker/iso_root_arch-dependent_files/amd64/isolinux/isolinux.cfg
  toolkit/resources/assets/isomaker/iso_root_arch-dependent_files/arm64/isolinux/isolinux.cfg
  toolkit/resources/assets/isomaker/iso_root_static_files/boot/grub2/grub.cfg
Labels: main

#5199 Add QUICKBUILD flags for fast auto build
  toolkit/Makefile
  toolkit/docs/building/building.md
  toolkit/scripts/incremental_building.mk
  toolkit/scripts/toolchain.mk
  toolkit/scripts/toolchain/build_mariner_toolchain.sh
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
  toolkit/scripts/toolchain/container/Dockerfile
  toolkit/scripts/toolchain/create_toolchain_in_container.sh
  toolkit/scripts/toolchain/toolchain_clean.sh
Labels: Tools, main, DevEx

#5161 azurevm-packages: Add grubby to package list
  toolkit/imageconfigs/packagelists/azurevm-packages.json
Labels: main

#5314 Update chrony.conf in Marketplace to follow time sync recommendations…
  toolkit/imageconfigs/additionalconfigs/chrony.cfg
Labels: main

#5197 selinux-policy: Add rules for cloud-init and iptables.
  SPECS/selinux-policy/0036-iptables-Support-Mariner-non-standard-config-locatio.patch
  SPECS/selinux-policy/0037-cloudinit-Add-permissions-derived-from-sysadm.patch
  SPECS/selinux-policy/0038-systemd-Fix-run-systemd-shutdown-handling.patch
  SPECS/selinux-policy/0039-modutils-Temporary-fix-for-mkinitrd-dracut.patch
  SPECS/selinux-policy/selinux-policy.spec
Labels: main

#5208 Add new pkg uchardet to SPECS-EXTENDED
  SPECS-EXTENDED/uchardet/uchardet.signatures.json
  SPECS-EXTENDED/uchardet/uchardet.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/cmake/cmake.signatures.json
  SPECS/cmake/cmake.spec
  SPECS/cmake/macros.cmake
  SPECS/leveldb/leveldb.spec
  cgmanifest.json
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5310 Add runtime requirements to gcovr package
  SPECS/gcovr/gcovr.spec
Labels: main

#5317 Upgrading k3s: From 1.24.6 to 1.25.8 to 1.26.3 on SPEC change
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/k3s/k3s-1.25.5.signatures.json
  SPECS/k3s/k3s-1.25.8.signatures.json
  SPECS/k3s/k3s-1.25.8.spec
  SPECS/k3s/k3s.signatures.json
  SPECS/k3s/k3s.spec
  SPECS/k3s/vendor_build-1.25.8.patch
  SPECS/k3s/vendor_build.patch
  cgmanifest.json
Labels: main

#5318 Fix CVE-2021-45985 on memcached and ntopng
  SPECS/memcached/CVE-2021-45985.patch
  SPECS/memcached/memcached.spec
  SPECS/ntopng/CVE-2021-45985.patch
  SPECS/ntopng/ntopng.spec
Labels: main

#5301 Disable recomputing build-ids for kernel debuginfo packages
  SPECS-EXTENDED/kernel-rt/kernel-rt.spec
  SPECS-SIGNED/kernel-azure-signed/kernel-azure-signed.spec
  SPECS-SIGNED/kernel-hci-signed/kernel-hci-signed.spec
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-azure/kernel-azure.spec
  SPECS/kernel-hci/kernel-hci.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5333 Nopatch kernel for CVE-2023-0179, CVE-2023-0386, CVE-2023-0590, CVE-2023-1249, CVE-2023-1252, CVE-2023-1652, CVE-2023-1838, CVE-2023-1855, CVE-2023-25012, CVE-2023-30456, CVE-2022-4379
  SPECS/kernel/CVE-2022-3707.nopatch
  SPECS/kernel/CVE-2022-4095.nopatch
  SPECS/kernel/CVE-2022-4379.nopatch
  SPECS/kernel/CVE-2023-0179.nopatch
  SPECS/kernel/CVE-2023-0386.nopatch
  SPECS/kernel/CVE-2023-0590.nopatch
  SPECS/kernel/CVE-2023-1249.nopatch
  SPECS/kernel/CVE-2023-1252.nopatch
  SPECS/kernel/CVE-2023-1652.nopatch
  SPECS/kernel/CVE-2023-1838.nopatch
  SPECS/kernel/CVE-2023-1855.nopatch
  SPECS/kernel/CVE-2023-25012.nopatch
  SPECS/kernel/CVE-2023-30456.nopatch
Labels: security, main

#5329 Nopatch kernel for CVE-2021-3923, CVE-2023-0179, CVE-2023-0590, CVE-2023-1249, CVE-2023-1252, CVE-2023-1838, CVE-2023-30456
  SPECS/kernel/CVE-2021-3923.nopatch
  SPECS/kernel/CVE-2023-0179.nopatch
  SPECS/kernel/CVE-2023-0590.nopatch
  SPECS/kernel/CVE-2023-1249.nopatch
  SPECS/kernel/CVE-2023-1252.nopatch
  SPECS/kernel/CVE-2023-1838.nopatch
  SPECS/kernel/CVE-2023-30456.nopatch
Labels: security, 1.0-dev

#5338 Patch CVE-2021-28235 for etcd packages
  SPECS/etcd/CVE-2021-28235.patch
  SPECS/etcd/etcd-3.5.0.spec
  SPECS/etcd/etcd-3.5.1.spec
  SPECS/etcd/etcd-3.5.3.spec
  SPECS/etcd/etcd-3.5.4.spec
  SPECS/etcd/etcd-3.5.5.spec
  SPECS/etcd/etcd-3.5.6.spec
Labels: main

#5337 Fix CVE 2022 37601 on webpack loader-utils integrated with webpack
  SPECS/reaper/CVE-2022-37601.patch
  SPECS/reaper/reaper.spec
Labels: main

#5139 Add the mstflint Kernel Module
  SPECS-SIGNED/kernel-mstflint-signed/kernel-mstflint-signed.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/mstflint/mstflint.spec
  toolkit/scripts/check_entangled_specs.py
Labels: main

#5341 Updated SPEC to not include bundled zlib to fix CVE-2018-25032
  SPECS/ccache/ccache.spec
Labels: 1.0-dev

#5320 Patch nmap to fix CVE-2018-25032
  SPECS/nmap/nmap.spec
  SPECS/nmap/update_zlib_1.2.12.patch
Labels: 1.0-dev

#5312 Upgrade nmap to version 7.93 to fix CVE-2018-25032
  SPECS/nmap/nmap.signatures.json
  SPECS/nmap/nmap.spec
  SPECS/nmap/remove_openssl_macro.patch
  cgmanifest.json
Labels: main

#5324 Upgrade erlang to 25.2 to fix CVE-2018-25032
  SPECS/erlang/erlang.signatures.json
  SPECS/erlang/erlang.spec
  cgmanifest.json
Labels: 1.0-dev

#5346 Revert "Upgrade erlang to 25.2 to fix CVE-2018-25032 (#5324)"
  SPECS/erlang/erlang.signatures.json
  SPECS/erlang/erlang.spec
  cgmanifest.json
Labels: 1.0-dev

#5295 [NODEJS]: Add nodejs18.spec to support nodejs 18
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/nodejs/nodejs18.signatures.json
  SPECS/nodejs/nodejs18.spec
  cgmanifest.json
Labels: main

#5345 toolkit: Add warning when RPM filename mismatch is detected
  toolkit/tools/internal/packagerepo/repomanager/rpmrepomanager/rpmrepomanager.go
Labels: main

#5354 Patch CVE-2022-2989 in podman
  SPECS-EXTENDED/podman/CVE-2022-2989.patch
  SPECS-EXTENDED/podman/podman.spec
Labels: main

#5352 Make python2 use system zlib to fix CVE-2018-25032
  SPECS/python2/python2.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#5355 Patch CVE-2022-3165 in qemu
  SPECS/qemu/CVE-2022-3165.patch
  SPECS/qemu/qemu.spec
Labels: main

#5356 Bump for Mariner 2.0 April 2023 Update 2
  SPECS/mariner-release/mariner-release.spec
Labels: main

#5357 Remove branch status table from readme
  README.md
Labels: main

#5359 RI 2.0 changes back to main
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/livepatch-5.15.102.1-3.cm2/config-5.15.102.1-3.cm2
  SPECS/livepatch-5.15.102.1-3.cm2/livepatch-5.15.102.1-3.cm2.signatures.json
  SPECS/livepatch-5.15.102.1-3.cm2/livepatch-5.15.102.1-3.cm2.spec
  SPECS/livepatch-5.15.102.1-3.cm2/mariner-5.15.102.1-3.cm2.pem
  SPECS/vim/vim.signatures.json
  cgmanifest.json
Labels: main

#5343 toolchain: update to use msopenjdk-11.0.18-1
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
Labels: main

#5364 Nopatch kernel for CVE-2023-1829, CVE-2023-1989, CVE-2023-1990
  SPECS/kernel/CVE-2023-1829.nopatch
  SPECS/kernel/CVE-2023-1989.nopatch
  SPECS/kernel/CVE-2023-1990.nopatch
Labels: security, main

#5332 upgrade boost to version 1.82.0
  SPECS/boost/CVE-2018-25032.patch
  SPECS/boost/boost.spec
Labels: 1.0-dev

#5331 Patch embedded zlib package within boost to fix CVE 2018-25032
  SPECS/boost/CVE-2018-25032.patch
  SPECS/boost/boost.spec
Labels: security, main

#5366 Increase amd64 market place image EFI boot partition size
  toolkit/imageconfigs/marketplace-gen2.json
Labels: main

#5369 Increase aarch64 EFI boot partition size
  toolkit/imageconfigs/marketplace-gen2-aarch64.json
Labels: main

#5370 Use kernel header to query the kernel version
  SPECS-SIGNED/kernel-mstflint-signed/kernel-mstflint-signed.spec
Labels: main

#5082 moby-compose: add package v2.17.2
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/moby-compose/generate_source_tarball.sh
  SPECS/moby-compose/moby-compose.signatures.json
  SPECS/moby-compose/moby-compose.spec
  cgmanifest.json
Labels: main

#5361 Adding new version of k3s --> 1.24.12
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/k3s/k3s-1.24.12.signatures.json
  SPECS/k3s/k3s-1.24.12.spec
  SPECS/k3s/vendor_build-1.24.12.patch
  cgmanifest.json
Labels: main

#5373 Nopatch Kernel for CVE-2022-4095, CVE-2022-4379, CVE-2023-1855, CVE-2023-1989, CVE-2023-1990, CVE-2023-25012
  SPECS/kernel/CVE-2022-4095.nopatch
  SPECS/kernel/CVE-2022-4379.nopatch
  SPECS/kernel/CVE-2023-1855.nopatch
  SPECS/kernel/CVE-2023-1989.nopatch
  SPECS/kernel/CVE-2023-1990.nopatch
  SPECS/kernel/CVE-2023-25012.nopatch
Labels: security, 1.0-dev

#5378 update signature for nodejs18 source tar
  SPECS/nodejs/nodejs18.signatures.json
Labels: main

#5365 Add kata-containers-cc
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/kata-containers-cc/containerd-for-cc-override.conf
  SPECS/kata-containers-cc/kata-containers-cc.signatures.json
  SPECS/kata-containers-cc/kata-containers-cc.spec
  SPECS/kata-containers-cc/mariner-coco-build-uvm-image.sh
  SPECS/kata-containers-cc/mariner-coco-build-uvm-rootfs.sh
  cgmanifest.json
Labels: main

#5402 Fix: patch CVE-2023-24607 for qt5-qtbase
  SPECS/qt5-qtbase/CVE-2023-24607.patch
  SPECS/qt5-qtbase/qt5-qtbase.spec
Labels: 1.0-dev

#5401 Add 3pm extension to perl-File-Which, perl-File-HomeDir, and perl-List-MoreUtils following update to perl man3 naming change
  SPECS/perl-File-HomeDir/perl-File-HomeDir.spec
  SPECS/perl-File-Which/perl-File-Which.spec
  SPECS/perl-List-MoreUtils/perl-List-MoreUtils.spec
Labels: 1.0-dev

#5389 Patch erlang for CVE-2018-25032
  SPECS/erlang/CVE-2018-25032.patch
  SPECS/erlang/erlang.spec
Labels: 1.0-dev

#5405 Bump Release for April 2023 Update 2
  SPECS/mariner-release/mariner-release.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#5412 fix: upgrade git to 2.33.8 to address CVE-2023-25652 and CVE-2023-29007
  SPECS/git/git.signatures.json
  SPECS/git/git.spec
  cgmanifest.json
Labels: 1.0-dev

#5411 fix: upgrade git to 2.33.8 to address CVE-2023-25652 and CVE-2023-29007
  SPECS/git/git.signatures.json
  SPECS/git/git.spec
  cgmanifest.json
Labels: main

#5406 Enable TLS, Dell drivers, and supporting config options
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5291 Upgrade kata-containers to version 3.1.0
  SPECS/kata-containers/0001-Merged-PR-9607-Allow-10-seconds-for-VM-creation-star.patch
  SPECS/kata-containers/kata-containers.signatures.json
  SPECS/kata-containers/kata-containers.spec
  SPECS/kata-containers/runtime-Re-generate-the-client-code.patch
  SPECS/kata-containers/runtime-Support-for-AMD-SEV-SNP-VMs.patch
  SPECS/kata-containers/runtime-clh-Use-the-new-API-to-boot-with-TDX-firmware-td-shim.patch
  SPECS/kata-containers/runtime-reduce-uvm-high-mem-footprint.patch
  SPECS/kata-containers/versions-Update-Cloud-Hypervisor.patch
  cgmanifest.json
Labels: main

#5419 Nopatch kernel for CVE-2023-1872, CVE-2023-22997, CVE-2023-23005
  SPECS/kernel/CVE-2023-1872.nopatch
  SPECS/kernel/CVE-2023-22997.nopatch
  SPECS/kernel/CVE-2023-23005.nopatch
Labels: security, main

#5408 zlib: bump version to 1.2.13 to address java exception
  SPECS/zlib/CVE-2022-37434.patch
  SPECS/zlib/Fix-extra-field-processing-bug-that-dereferences-NULL.patch
  SPECS/zlib/zlib.signatures.json
  SPECS/zlib/zlib.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, main

#5413 Fix cgmanifest ordering
  cgmanifest.json
Labels: main

#5414 Fix perl-WWW-Curl tests by adding check-time requirements
  SPECS/perl-WWW-Curl/perl-WWW-Curl.spec
Labels: main

#5400 Fix: patch CVE-2023-24607 for qt5-qtbase
  SPECS/qt5-qtbase/CVE-2023-24607.patch
  SPECS/qt5-qtbase/qt5-qtbase.spec
Labels: security, main

#5426 Nopatch kernel for CVE-2023-1382, CVE-2023-2008, CVE-2023-30772
  SPECS/kernel/CVE-2023-1382.nopatch
  SPECS/kernel/CVE-2023-2008.nopatch
  SPECS/kernel/CVE-2023-30772.nopatch
Labels: security, main

#5416 Enable DRM_AMDGPU
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5427 mstflint: fix signature issue
  SPECS-SIGNED/kernel-mstflint-signed/kernel-mstflint-signed.spec
Labels: main
