Repository microsoft/azurelinux, pull requests merged in 2023-02, with the labels that each got.

#4700 Patch mozjs60 to address CVE-2023-22895
  SPECS/mozjs60/CVE-2023-22895.patch
  SPECS/mozjs60/mozjs60.spec
Labels: security, Packaging, 1.0-dev

#4704 Upgrade etcd to 3.4.23 to address CVE-2022-3064
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/etcd/etcd-3.4.23.signatures.json
  SPECS/etcd/etcd-3.4.23.spec
  cgmanifest.json
Labels: security, Packaging, 1.0-dev

#4718 Let openldap depend on cyrus-sasl
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/cyrus-sasl-ldap/cyrus-sasl-ldap.signatures.json
  SPECS/cyrus-sasl-ldap/cyrus-sasl-ldap.spec
  SPECS/cyrus-sasl/cyrus-sasl.spec
  SPECS/openldap/openldap.spec
  cgmanifest.json
  toolkit/scripts/check_entangled_specs.py
Labels: security, Packaging, main

#4519 Add package liboggz version 1.1.1
  SPECS-EXTENDED/liboggz/liboggz-1.1.1-multilib.patch
  SPECS-EXTENDED/liboggz/liboggz.signatures.json
  SPECS-EXTENDED/liboggz/liboggz.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4733 Fixing influxdb and influx-cli build
  SPECS/influx-cli/influx-cli.spec
  SPECS/influxdb/influxdb.spec
Labels: Packaging, main

#4711 Add python3-enchant to Mariner
  SPECS-EXTENDED/python-enchant/python-enchant.signatures.json
  SPECS-EXTENDED/python-enchant/python-enchant.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#4732 Patched pkgconf to address CVE-2023-24056
  SPECS/pkgconf/CVE-2023-24056.patch
  SPECS/pkgconf/pkgconf.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, main

#4749 Add missing grubenv file path to iso_initrd_arm64.json to allow passing kernel options to ARM images
  toolkit/resources/imageconfigs/iso_initrd_arm64.json
Labels: main

#4651 Add package libdeflate version 1.9
  SPECS-EXTENDED/libdeflate/libdeflate.signatures.json
  SPECS-EXTENDED/libdeflate/libdeflate.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#4609 Add package libofa version 0.9.3
  SPECS-EXTENDED/libofa/libofa-0.9.3-curl.patch
  SPECS-EXTENDED/libofa/libofa-0.9.3-gcc41.patch
  SPECS-EXTENDED/libofa/libofa-0.9.3-gcc44.patch
  SPECS-EXTENDED/libofa/libofa-0.9.3-gcc47.patch
  SPECS-EXTENDED/libofa/libofa-0.9.3-pkgconfig.patch
  SPECS-EXTENDED/libofa/libofa.signatures.json
  SPECS-EXTENDED/libofa/libofa.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#4753 [1.0] Resolve vim CVE-2023-0433
  SPECS/vim/CVE-2023-0433.patch
  SPECS/vim/vim.spec
Labels: Packaging, 1.0-dev

#4762 Revert "Let openldap depend on cyrus-sasl (#4718)"
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/cyrus-sasl-ldap/cyrus-sasl-ldap.signatures.json
  SPECS/cyrus-sasl-ldap/cyrus-sasl-ldap.spec
  SPECS/cyrus-sasl/cyrus-sasl.spec
  SPECS/openldap/openldap.spec
  cgmanifest.json
  toolkit/scripts/check_entangled_specs.py
Labels: main

#4761 [1.0] Resolve dbus CVE-2022-42010, CVE-2022-42011, CVE-2022-42012
  SPECS/dbus/CVE-2022-42010.patch
  SPECS/dbus/CVE-2022-42011.patch
  SPECS/dbus/CVE-2022-42012.patch
  SPECS/dbus/dbus.spec
Labels: Packaging, 1.0-dev

#4760 libsmi: move from extended to core
  SPECS/libsmi/CVE-2010-2891.patch
  SPECS/libsmi/IETF-MIB-LICENSE.txt
  SPECS/libsmi/libsmi-0.4.8-format-security-fix.patch
  SPECS/libsmi/libsmi-0.4.8-symbols-clash.patch
  SPECS/libsmi/libsmi-0.4.8-wget111.patch
  SPECS/libsmi/libsmi.signatures.json
  SPECS/libsmi/libsmi.spec
  SPECS/libsmi/smi.conf
  cgmanifest.json
Labels: Packaging, main

#4754 Patch CVE-2022-40897 in python3-setuptools
  SPECS/python3/CVE-2022-40897.patch
  SPECS/python3/python3.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#4764 [1.0] Resolve cmake CVE-2022-43551
  SPECS/cmake/CVE-2022-43551.patch
  SPECS/cmake/cmake.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#4720 whois command need /etc/services to work
  SPECS-EXTENDED/whois/whois.signatures.json
  SPECS-EXTENDED/whois/whois.spec
  cgmanifest.json
Labels: main

#4765 [1.0] Resolve redis CVE-2022-35977, CVE-2023-22458
  SPECS/redis/CVE-2022-35977.patch
  SPECS/redis/CVE-2023-22458.patch
  SPECS/redis/redis.spec
Labels: Packaging, 1.0-dev

#4726 [1.0] Resolve tpm2-tss CVE-2023-22745
  SPECS/tpm2-tss/CVE-2023-22745.patch
  SPECS/tpm2-tss/tpm2-tss.spec
Labels: Packaging, 1.0-dev

#4769 influxdb: fix build break
  SPECS/influx-cli/influx-cli.spec
  SPECS/influxdb/influxdb.spec
Labels: main

#4763 Resolve CVE-2022-43551 in bundled curl in cmake
  SPECS/cmake/CVE-2022-43551.patch
  SPECS/cmake/cmake.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#4775 [1.0] Modify toolchain build order to resolve cmake build failure
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
Labels: 1.0-dev

#4774 Patch util-linux to add patch to prevent cdrom probe on Azure VMs
  SPECS/util-linux/libblkid-src-probe-check-for-ENOMEDIUM.patch
  SPECS/util-linux/util-linux.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#4790 Bump Mariner 2.0 Release for Feb 2023 Update
  SPECS/mariner-release/mariner-release.spec
Labels: main

#4777 Update apr-util to 1.6.3 for CVE-2022-25147
  SPECS/apr-util/apr-util.signatures.json
  SPECS/apr-util/apr-util.spec
  cgmanifest.json
Labels: main

#4786 Update apr-util to 1.6.3 for CVE-2022-25147
  SPECS/apr-util/apr-util.signatures.json
  SPECS/apr-util/apr-util.spec
  cgmanifest.json
Labels: 1.0-dev

#4793 Nopatch kernel to address CVE-2022-41218, CVE-2022-42328, CVE-2022-42329, CVE-2022-4662, CVE-2023-0266, CVE-2023-0468, CVE-2023-23559
  SPECS/kernel/CVE-2022-41218.nopatch
  SPECS/kernel/CVE-2022-42328.nopatch
  SPECS/kernel/CVE-2022-42329.nopatch
  SPECS/kernel/CVE-2022-4662.nopatch
  SPECS/kernel/CVE-2023-0266.nopatch
  SPECS/kernel/CVE-2023-0468.nopatch
  SPECS/kernel/CVE-2023-23559.nopatch
Labels: security, main

#4781 Patch CVE-2022-4304, CVE-2022-4450, CVE-2023-0215, CVE-2023-0286 in openssl
  SPECS/openssl/CVE-2022-4304.patch
  SPECS/openssl/CVE-2022-4450.patch
  SPECS/openssl/CVE-2023-0215.patch
  SPECS/openssl/CVE-2023-0286.patch
  SPECS/openssl/openssl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#4780 Patch CVE-2022-4304, CVE-2022-4450, CVE-2023-0215, CVE-202333286 in openssl
  SPECS/openssl/CVE-2022-4304.patch
  SPECS/openssl/CVE-2022-4450.patch
  SPECS/openssl/CVE-2023-0215.patch
  SPECS/openssl/CVE-2023-0286.patch
  SPECS/openssl/openssl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#4784 Update httpd to version 2.4.55 for CVE-2022-36760
  SPECS/httpd/httpd-2.4.53-blfs_layout-3.patch
  SPECS/httpd/httpd.signatures.json
  SPECS/httpd/httpd.spec
  cgmanifest.json
Labels: 1.0-dev

#4592 scotch: Add package version 6.1.2
  SPECS-EXTENDED/scotch/scotch-Makefile.shared.inc.in
  SPECS-EXTENDED/scotch/scotch-gfortran.patch
  SPECS-EXTENDED/scotch/scotch-ldflags.patch
  SPECS-EXTENDED/scotch/scotch.signatures.json
  SPECS-EXTENDED/scotch/scotch.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#4789 Update GitHub workflows to use latest Ubuntu
  .github/workflows/check-manifests.yml
  .github/workflows/go-test-coverage.yml
Labels: main

#4611 Add package libcmpiutil version 0.5.7
  SPECS-EXTENDED/libcmpiutil/libcmpiutil-0.5.6-cast-align.patch
  SPECS-EXTENDED/libcmpiutil/libcmpiutil.signatures.json
  SPECS-EXTENDED/libcmpiutil/libcmpiutil.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#4806 Nopatch kernel for CVE-2022-4139 and CVE-2022-47940
  SPECS/kernel/CVE-2022-4139.nopatch
  SPECS/kernel/CVE-2022-47940.nopatch
Labels: security, main

#4809 Updated `ltp` to version 20230127.
  SPECS/ltp/ltp.signatures.json
  SPECS/ltp/ltp.spec
  cgmanifest.json
Labels: main

#4798 K3s: Bump k3s v1.24.3 to v1.24.6
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/k3s/k3s-1.24.3.signatures.json
  SPECS/k3s/k3s-1.24.6.signatures.json
  SPECS/k3s/k3s-1.24.6.spec
  SPECS/k3s/vendor_build-1.24.6.patch
  cgmanifest.json
Labels: main

#4785 docs: Make clearer how REPO_LIST is to be used
  toolkit/docs/building/building.md
Labels: main

#4813 Nopatch hyperv-daemons for CVE-2022-27666
  SPECS/hyperv-daemons/CVE-2022-27666.nopatch
Labels: security, main

#4804 redis: update to 6.2.9 for CVE-2022-35977 and CVE-2023-22458
  SPECS/redis/redis.signatures.json
  SPECS/redis/redis.spec
  cgmanifest.json
Labels: security, main

#4805 Patch libtiff for CVE-2022-48281
  SPECS/libtiff/CVE-2022-48281.patch
  SPECS/libtiff/libtiff.spec
Labels: security, main

#4807 Patch tpm2-tss for CVE-2023-22745
  SPECS/tpm2-tss/CVE-2023-22745.patch
  SPECS/tpm2-tss/tpm2-tss.spec
Labels: security, main

#4808 Update sudo to 1.9.12p2 to address CVE-2023-22809
  SPECS/sudo/sudo.signatures.json
  SPECS/sudo/sudo.spec
  cgmanifest.json
Labels: security, main

#4817 podman: update to build with golang 1.18
  SPECS-EXTENDED/podman/podman.spec
Labels: main

#4799 libksba: CVE-2022-3515
  SPECS/libksba/CVE-2022-3515.patch
  SPECS/libksba/libksba.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#4800 tmux: CVE 2022 47016
  SPECS/tmux/CVE-2022-47016.patch
  SPECS/tmux/tmux.spec
Labels: 1.0-dev

#4812 Patch binutils for CVE-2022-4285
  SPECS/binutils/CVE-2022-4285.patch
  SPECS/binutils/binutils.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#4828 Nopatch redis for CVE-2022-3647
  SPECS/redis/CVE-2022-3647.nopatch
  SPECS/redis/CVE-2022-3647.patch
Labels: security, main

#4818 Nopatch hyperv-daemons for CVE-2023-0266, CVE-2022-0742, CVE-2022-27666
  SPECS/hyperv-daemons/CVE-2022-0742.nopatch
  SPECS/hyperv-daemons/CVE-2022-27666.nopatch
  SPECS/hyperv-daemons/CVE-2023-0266.nopatch
Labels: security, 1.0-dev

#4820 Nopatch kernel to address CVE-2023-0266
  SPECS/kernel/CVE-2023-0266.nopatch
Labels: security, 1.0-dev

#4691 Update cloud-hypervisor to v29.0, kernel-mshv to v5.15.86
  SPECS/cloud-hypervisor/cloud-hypervisor.signatures.json
  SPECS/cloud-hypervisor/cloud-hypervisor.spec
  SPECS/cloud-hypervisor/config.toml
  SPECS/kernel-mshv/config
  SPECS/kernel-mshv/kernel-mshv.signatures.json
  SPECS/kernel-mshv/kernel-mshv.spec
  cgmanifest.json
Labels: Packaging, main

#4717 Add libappstream-glib and elinks to Mariner
  SPECS-EXTENDED/elinks/0000-elinks-0.15.0-ssl-noegd.patch
  SPECS-EXTENDED/elinks/0001-elinks-0.15.1-utf_8_io-default.patch
  SPECS-EXTENDED/elinks/0004-elinks-0.15.0-sysname.patch
  SPECS-EXTENDED/elinks/0005-elinks-0.15.0-xterm.patch
  SPECS-EXTENDED/elinks/0006-elinks-0.16.0-libidn2.patch
  SPECS-EXTENDED/elinks/elinks-0.11.0-getaddrinfo.patch
  SPECS-EXTENDED/elinks/elinks-0.12pre6-list_is_singleton.patch
  SPECS-EXTENDED/elinks/elinks.conf
  SPECS-EXTENDED/elinks/elinks.signatures.json
  SPECS-EXTENDED/elinks/elinks.spec
  SPECS-EXTENDED/libappstream-glib/libappstream-glib.signatures.json
  SPECS-EXTENDED/libappstream-glib/libappstream-glib.spec
  SPECS-EXTENDED/rpmlint/rpmlint.config
  SPECS-EXTENDED/rpmlint/rpmlint.signatures.json
  SPECS-EXTENDED/rpmlint/rpmlint.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/hdf5/hdf5.signatures.json
  SPECS/hostname/hostname.signatures.json
  SPECS/python-cached_property/python-cached_property.signatures.json
  SPECS/python-h5py/python-h5py.signatures.json
  cgmanifest.json
Labels: main

#4821 Patch mariadb for CVE-2022-47015
  SPECS/mariadb/CVE-2022-47015.patch
  SPECS/mariadb/mariadb.spec
Labels: main

#4833 Fixing influx-cli-bash-completion package conflicting with bash-completion
  SPECS/influx-cli/influx-cli.spec
Labels: main

#4834 podman: revert to release 5
  SPECS-EXTENDED/podman/podman.spec
Labels: main

#4768 Add an upstream patch to kubevirt to fix an SELinux issue
  SPECS/kubevirt/fgetxattr-for-relabel.patch
  SPECS/kubevirt/kubevirt.spec
Labels: main

#4827 unzip: CVE 2021 4217
  SPECS/unzip/CVE-2021-4217.patch
  SPECS/unzip/unzip.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#4830 Patch tmux for CVE-2022-47016
  SPECS/tmux/CVE-2022-47016.patch
  SPECS/tmux/tmux.spec
Labels: main

#4829 Disable INIT_ON_FREE Kernel config
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#4832 set disable_root true in cloud-init.cfg
  toolkit/imageconfigs/additionalconfigs/cloud-init.cfg
Labels: main

#4723 smartmontools: Move from SPECS-EXTENDED to SPECS
  SPECS/smartmontools/drivedb.h
  SPECS/smartmontools/smartdnotify
  SPECS/smartmontools/smartmontools-5.38-defaultconf.patch
  SPECS/smartmontools/smartmontools.signatures.json
  SPECS/smartmontools/smartmontools.spec
  SPECS/smartmontools/smartmontools.sysconf
  cgmanifest.json
Labels: Packaging, main

#4814 Add package squid v5.7
  SPECS-EXTENDED/squid/cache_swap.sh
  SPECS-EXTENDED/squid/perl-requires-squid.sh
  SPECS-EXTENDED/squid/squid-3.0.STABLE1-perlpath.patch
  SPECS-EXTENDED/squid/squid-3.1.0.9-location.patch
  SPECS-EXTENDED/squid/squid-3.5.9-include-guards.patch
  SPECS-EXTENDED/squid/squid-4.0.11-config.patch
  SPECS-EXTENDED/squid/squid-5.0.5-build-errors.patch
  SPECS-EXTENDED/squid/squid-5.0.5-symlink-lang-err.patch
  SPECS-EXTENDED/squid/squid-5.7-ip-bind-address-no-port.patch
  SPECS-EXTENDED/squid/squid.logrotate
  SPECS-EXTENDED/squid/squid.nm
  SPECS-EXTENDED/squid/squid.pam
  SPECS-EXTENDED/squid/squid.service
  SPECS-EXTENDED/squid/squid.signatures.json
  SPECS-EXTENDED/squid/squid.spec
  SPECS-EXTENDED/squid/squid.sysconfig
  SPECS-EXTENDED/squid/squid.sysusers
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4757 add pytorch pkg to mariner
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/pytorch/generate_source_tarball.sh
  SPECS/pytorch/pytorch.signatures.json
  SPECS/pytorch/pytorch.spec
  cgmanifest.json
  toolkit/scripts/spec_source_attributions.py
Labels: main

#4845 Upgrade Cython to 0.29.33 to fix failing package tests
  SPECS/Cython/Cython.signatures.json
  SPECS/Cython/Cython.spec
  cgmanifest.json
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#4855 Bump Release for Mariner 1.0 Feb Update 2
  SPECS/mariner-release/mariner-release.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#4851 Upgrade package apr to 1.7.2 to fix CVE-2022-24963
  SPECS/apr/apr.signatures.json
  SPECS/apr/apr.spec
  cgmanifest.json
Labels: security, main

#4849 [1.0] Upgrade redis to 6.2.9 to resolve CVE-2022-35977 and CVE-2023-22458
  SPECS/redis/CVE-2022-35977.patch
  SPECS/redis/CVE-2022-3647.patch
  SPECS/redis/CVE-2023-22458.patch
  SPECS/redis/redis.signatures.json
  SPECS/redis/redis.spec
  cgmanifest.json
Labels: 1.0-dev

#4788 qemu: Add, don't delete, romfiles when building for aarch64
  SPECS/qemu/qemu.spec
Labels: main

#4802 grub2: CVE-2022-3775
  SPECS-SIGNED/grub2-efi-binary-signed/grub2-efi-binary-signed.spec
  SPECS/grub2/CVE-2022-3775.patch
  SPECS/grub2/grub2.spec
Labels: 1.0-dev

#4822 libconfuse: CVE-2022-40320
  SPECS/libconfuse/CVE-2022-40320.patch
  SPECS/libconfuse/libconfuse.spec
Labels: 1.0-dev

#4824 helm: CVE-2022-23524
  SPECS/helm/CVE-2022-23524.patch
  SPECS/helm/helm.spec
Labels: 1.0-dev

#4826 syslog-ng: CVE-2022-38725
  SPECS/syslog-ng/CVE-2022-38725.patch
  SPECS/syslog-ng/syslog-ng.spec
Labels: 1.0-dev

#4874 Patch helm for CVE-2023-25165
  SPECS/helm/CVE-2023-25165.patch
  SPECS/helm/helm.spec
Labels: security, main

#4852 Fix build-break for libappstream-glib
  SPECS-EXTENDED/libappstream-glib/libappstream-glib.spec
Labels: main, specs-extended

#4871 Install vmlinux with root executable permissions
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#4882 Nopatch kernel to address CVE-2022-36280, CVE-2022-41218, CVE-2022-4139, CVE-2022-42328, CVE-2022-42329, CVE-2022-4662, CVE-2023-23559
  SPECS/kernel/CVE-2022-36280.nopatch
  SPECS/kernel/CVE-2022-41218.nopatch
  SPECS/kernel/CVE-2022-4139.nopatch
  SPECS/kernel/CVE-2022-42328.nopatch
  SPECS/kernel/CVE-2022-42329.nopatch
  SPECS/kernel/CVE-2022-4662.nopatch
  SPECS/kernel/CVE-2023-23559.nopatch
Labels: security, 1.0-dev

#4883 Add authbind SPEC to Mariner
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/authbind/authbind-makefile-fixes.patch
  SPECS/authbind/authbind.signatures.json
  SPECS/authbind/authbind.spec
  cgmanifest.json
Labels: main

#4886 Fixed livepatch PR check.
  .github/workflows/check-livepatches.yml
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/livepatch-5.15.92.1-2.cm2/config-5.15.92.1-2.cm2
  SPECS/livepatch-5.15.92.1-2.cm2/livepatch-5.15.92.1-2.cm2.signatures.json
  SPECS/livepatch-5.15.92.1-2.cm2/livepatch-5.15.92.1-2.cm2.spec
  SPECS/livepatch-5.15.92.1-2.cm2/mariner-5.15.92.1-2.cm2.pem
  cgmanifest.json
Labels: main

#4879 Patch less with CVE-2022-46663
  SPECS/less/CVE-2022-46663.patch
  SPECS/less/less.spec
Labels: security, main

#4876 libtiff: CVE 2023-0800
  SPECS/libtiff/CVE-2023-0800.patch
  SPECS/libtiff/libtiff.spec
Labels: security, 1.0-dev

#4892 Fix podman build-break
  SPECS-EXTENDED/podman/podman.signatures.json
  SPECS-EXTENDED/podman/podman.spec
Labels: main, specs-extended

#4604 Add package openrdate version 1.2
  SPECS-EXTENDED/openrdate/openrdate.signatures.json
  SPECS-EXTENDED/openrdate/openrdate.spec
  SPECS-EXTENDED/openrdate/openrdate_sysctl.patch
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#4547 bolt: Add package version 0.9.2
  SPECS-EXTENDED/bolt/bolt.signatures.json
  SPECS-EXTENDED/bolt/bolt.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#4549 libgdither: Add package version 0.6
  SPECS-EXTENDED/libgdither/libgdither-0.6-default.patch
  SPECS-EXTENDED/libgdither/libgdither-0.6-gavl.patch
  SPECS-EXTENDED/libgdither/libgdither-0.6-ldflags.patch
  SPECS-EXTENDED/libgdither/libgdither.signatures.json
  SPECS-EXTENDED/libgdither/libgdither.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#4583 Add package rcs version 5.10.1
  SPECS-EXTENDED/rcs/rcs.signatures.json
  SPECS-EXTENDED/rcs/rcs.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#4823 strongswan: CVE 2022 40617
  SPECS/strongswan/CVE-2022-40617.patch
  SPECS/strongswan/strongswan.spec
Labels: 1.0-dev

#4870 upgrade cloud-init to 22.4
  SPECS/cloud-init/CVE-2022-2084.patch
  SPECS/cloud-init/add-mariner-distro-support.patch
  SPECS/cloud-init/cloud-init.signatures.json
  SPECS/cloud-init/cloud-init.spec
  cgmanifest.json
Labels: main

#4751 Parse %check section when RUN_CHECK=y to add %check passing as a requirement
  toolkit/Makefile
  toolkit/docs/building/building.md
  toolkit/scripts/pkggen.mk
  toolkit/tools/scheduler/scheduler.go
  toolkit/tools/scheduler/schedulerutils/buildworker.go
Labels: Tools, main

#4899 kernel-hci: Install vmlinux with root executable permissions
  SPECS-SIGNED/kernel-hci-signed/kernel-hci-signed.spec
  SPECS/kernel-hci/kernel-hci.spec
Labels: main

#4898 kernel-azure: Install vmlinux with root executable permissions
  SPECS-SIGNED/kernel-azure-signed/kernel-azure-signed.spec
  SPECS/kernel-azure/kernel-azure.spec
Labels: main

#4897 [1.0] kernel, kernel-hyperv: Install vmlinux with root executable permissions
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel-hyperv/kernel-hyperv.spec
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#4867 prometheus-adapter: Adding to core packages
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/prometheus-adapter/generate_source_tarball.sh
  SPECS/prometheus-adapter/prometheus-adapter.signatures.json
  SPECS/prometheus-adapter/prometheus-adapter.spec
  cgmanifest.json
Labels: main

#4900 kernel-mshv: Install vmlinux with root executable permissions
  SPECS/kernel-mshv/kernel-mshv.spec
Labels: main

#4905 Bump haproxy version to 2.4.22 for CVE-2023-25725
  SPECS/haproxy/haproxy.signatures.json
  SPECS/haproxy/haproxy.spec
  cgmanifest.json
Labels: main

#4908 Documentation for CGroup toggle in toolkit/docs/formats/imageconfig.md to generate Mariner images with cgroupv2
  toolkit/docs/formats/imageconfig.md
Labels: main

#4912 Ignored `ccache` directory.
  .gitignore
Labels: main

#4869 Livepatched 5.15.87.1-1. CVEs: 2022-47929, 2023-0266, 2023-0394.
  SPECS-SIGNED/livepatch-5.15.87.1-1.cm2-signed/livepatch-5.15.87.1-1.cm2-signed.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/livepatch-5.15.87.1-1.cm2/CVE-2022-47929.patch
  SPECS/livepatch-5.15.87.1-1.cm2/CVE-2023-0266.patch
  SPECS/livepatch-5.15.87.1-1.cm2/CVE-2023-0394.patch
  SPECS/livepatch-5.15.87.1-1.cm2/livepatch-5.15.87.1-1.cm2.spec
Labels: main

#4894 cyrus-sasl: bump release
  SPECS/cyrus-sasl-bootstrap/cyrus-sasl-bootstrap.spec
  SPECS/cyrus-sasl/cyrus-sasl.spec
Labels: main

#4914 Enable adb-generic-tools in mstflint build config
  SPECS/mstflint/mstflint.spec
Labels: main

#4917 patch python cryptography for CVE-2023-23931
  SPECS/python-cryptography/CVE-2023-23931.patch
  SPECS/python-cryptography/python-cryptography.spec
Labels: 1.0-dev

#4922 [1.0] Update wget URL for mariner-nvidia.repo
  toolkit/docs/nvidia/nvidia.md
Labels: 1.0-dev

#4920 [2.0] Fix URL to mariner-nvidia.repo
  toolkit/docs/nvidia/nvidia.md
Labels: main

#4921 Upgrade telegraf to 1.25.2 to fix several vendored CVEs
  SPECS/telegraf/telegraf.signatures.json
  SPECS/telegraf/telegraf.spec
  cgmanifest.json
Labels: main

#4877 libtiff: CVE 2023-0795
  CVE-2023-0796.nopatch
  CVE-2023-0797.nopatch
  CVE-2023-0798.nopatch
  CVE-2023-0799.nopatch
  SPECS/libtiff/CVE-2023-0795.patch
  SPECS/libtiff/libtiff.spec
Labels: security, 1.0-dev

#4925 Bump mariner-release for February 2023 Release 3
  SPECS/mariner-release/mariner-release.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#4918 add patch Harbuzz CVE-2023-25193
  SPECS/harfbuzz/CVE-2023-25193.patch
  SPECS/harfbuzz/harfbuzz.spec
Labels: main

#4927 add patch for python-werkzeug CVE-2023-25577
  SPECS/python-werkzeug/CVE-2023-25577.patch
  SPECS/python-werkzeug/python-werkzeug.spec
Labels: main

#4868 kernel-hci: Add QinQ patches
  SPECS-SIGNED/kernel-hci-signed/kernel-hci-signed.spec
  SPECS/kernel-hci/0022-net-mlx5-Bridge-refactor-groups-sizes-and-indices.patch
  SPECS/kernel-hci/0023-net-mlx5-Bridge-rename-filter-fg-to-vlan_filter.patch
  SPECS/kernel-hci/0024-net-mlx5-Bridge-extract-VLAN-push-pop-actions-creati.patch
  SPECS/kernel-hci/0025-net-mlx5-Bridge-implement-infrastructure-for-VLAN-pr.patch
  SPECS/kernel-hci/0026-net-mlx5-Bridge-implement-QinQ-support.patch
  SPECS/kernel-hci/kernel-hci.spec
Labels: main

#4937 Patch python3 to address CVE-2023-24329
  SPECS/python3/CVE-2023-24329.patch
  SPECS/python3/python3.spec
Labels: security, 1.0-dev

#4878 Upgrade erlang to version 25.2 to support rabbitmq
  SPECS/erlang/erlang.signatures.json
  SPECS/erlang/erlang.spec
  cgmanifest.json
Labels: main

#4953 Revert "[AUTOPATCHER-CORE] Upgrade moby-containerd to 1.6.18 to fix CVE-2023-25173, CVE-2023-25153 - "
  SPECS/moby-containerd/CVE-2022-23471.patch
  SPECS/moby-containerd/moby-containerd.signatures.json
  SPECS/moby-containerd/moby-containerd.spec
  cgmanifest.json
Labels: 1.0-dev

#4950 Patch gnutls to address CVE-2023-0361
  SPECS/gnutls/CVE-2023-0361.patch
  SPECS/gnutls/gnutls.spec
Labels: 1.0-dev

#4904 Add package mksh v59c
  SPECS-EXTENDED/mksh/dot-mkshrc
  SPECS-EXTENDED/mksh/mksh.signatures.json
  SPECS-EXTENDED/mksh/mksh.spec
  SPECS-EXTENDED/mksh/rtchecks.expected
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#4903 Patch libtiff for CVE-2023-0795(to 0799) and CVE-2023-0800(to 0804)
  SPECS/libtiff/CVE-2023-0795.patch
  SPECS/libtiff/CVE-2023-0796.nopatch
  SPECS/libtiff/CVE-2023-0797.nopatch
  SPECS/libtiff/CVE-2023-0798.nopatch
  SPECS/libtiff/CVE-2023-0799.nopatch
  SPECS/libtiff/CVE-2023-0800.patch
  SPECS/libtiff/CVE-2023-0801.nopatch
  SPECS/libtiff/CVE-2023-0802.nopatch
  SPECS/libtiff/CVE-2023-0803.nopatch
  SPECS/libtiff/CVE-2023-0804.nopatch
  SPECS/libtiff/libtiff.spec
Labels: security, main

#4928 Added a build pipeline for livepatches.
  pipelines/common/utilities/Configure-1ES.sh
  pipelines/common/utilities/build_tools.sh
  pipelines/livepatching/BuildLivepatch.sh
  pipelines/livepatching/DeployLivepatch.yml
Labels: main

#4956 Fix package install error for buildah
  SPECS-EXTENDED/buildah/buildah.spec
Labels: main

#4957 Move -lib obsoletes to correct subpackage and remove AutoProv: No in cyrus-sasl-bootstrap to address build break
  SPECS/cyrus-sasl-bootstrap/cyrus-sasl-bootstrap.spec
  SPECS/cyrus-sasl/cyrus-sasl.spec
Labels: main

#4958 Add patch to fix CVE-2023-25173
  SPECS/moby-containerd/CVE-2023-25173.patch
  SPECS/moby-containerd/moby-containerd.spec
Labels: 1.0-dev

#4919 kernel-uvm: enable Hyper-V enlightenments
  SPECS/kernel-uvm/config
  SPECS/kernel-uvm/kernel-uvm.signatures.json
  SPECS/kernel-uvm/kernel-uvm.spec
Labels: main
