Repository microsoft/azurelinux, pull requests merged in 2023-09, with the labels that each got.

#6127 Fix parsing of releases containing '_'
  toolkit/tools/pkg/rpmssnapshot/rpmssnapshot.go
  toolkit/tools/pkg/rpmssnapshot/rpmssnapshot_test.go
Labels: main

#6120 feat: add Azure Marketplace Gen1 FIPS definition
  toolkit/imageconfigs/marketplace-gen1-fips.json
Labels: main

#6102 feat: add Azure Marketplace Gen2 FIPS definition
  toolkit/imageconfigs/marketplace-gen2-fips.json
Labels: main

#6126 Making sure we always create gzip file.
  toolkit/scripts/toolchain/build_mariner_toolchain.sh
Labels: main

#5572 Grapher resolves cyclic dependencies from remote repos
  toolkit/Makefile
  toolkit/scripts/pkggen.mk
  toolkit/tools/depsearch/depsearch.go
  toolkit/tools/grapher/grapher.go
  toolkit/tools/internal/pkggraph/pkggraph.go
  toolkit/tools/internal/pkggraph/pkggraph_test.go
  toolkit/tools/scheduler/scheduler.go
  toolkit/tools/scheduler/schedulerutils/implicitprovides.go
Labels: main

#6118 Bump gopkg.in/yaml.v3 to 3.0.0 to address CVE-2022-28948
  toolkit/tools/go.mod
  toolkit/tools/go.sum
Labels: security, main

#6132 Not to pass toolchainManifest to grapher and clean grapher worker during workplan clean
  toolkit/scripts/pkggen.mk
  toolkit/tools/grapher/grapher.go
Labels: main

#6131 Nopatch kernel for CVE-2023-4389, CVE-2023-32247
  SPECS/kernel/CVE-2023-32247.nopatch
  SPECS/kernel/CVE-2023-4389.nopatch
Labels: security, main

#6129 Disabled missing ptest dependencies for 7 extended specs.
  SPECS-EXTENDED/PyGreSQL/PyGreSQL.spec
  SPECS-EXTENDED/ibus-table/ibus-table.spec
  SPECS-EXTENDED/libpmemobj-cpp/libpmemobj-cpp.spec
  SPECS-EXTENDED/libuser/libuser.spec
  SPECS-EXTENDED/perl-Color-RGB-Util/perl-Color-RGB-Util.spec
  SPECS-EXTENDED/pybind11/pybind11.spec
  SPECS-EXTENDED/python-msrestazure/python-msrestazure.spec
  cgmanifest.json
Labels: main

#6133 Limited running `setfacl` to package builds
  toolkit/scripts/containerized-build.mk
  toolkit/scripts/pkggen.mk
  toolkit/scripts/utils.mk
Labels: main

#6142 Mitigating build failures in SPECS-EXTENDED during tests.
  SPECS-EXTENDED/ibus-table/ibus-table.spec
  SPECS-EXTENDED/libpmemobj-cpp/libpmemobj-cpp.spec
Labels: main

#6141 Enabled PR checks for the fast-track branches.
  .github/workflows/check-clean-stage.yml
  .github/workflows/check-entangled-specs.yml
  .github/workflows/check-kernel-config.yml
  .github/workflows/check-license-map.yml
  .github/workflows/check-livepatches.yml
  .github/workflows/check-manifests.yml
  .github/workflows/check-package-cgmanifest.yml
  .github/workflows/check-spec.yml
  .github/workflows/check-static-glibc.yml
  .github/workflows/go-test-coverage.yml
  .github/workflows/lint-specs.yml
Labels: main

#6158 Upgrade fetchmail 6.4.8 -> 6.4.22 to address CVE-2021-39272 & CVE-2021-36386
  SPECS-EXTENDED/fetchmail/fetchmail.signatures.json
  SPECS-EXTENDED/fetchmail/fetchmail.spec
  cgmanifest.json
Labels: security, main, specs-extended

#6147 Upgrade screen 4.9.0 -> 4.9.1 to address CVE-2023-24626
  SPECS-EXTENDED/screen/screen-4.3.1-crypt.patch
  SPECS-EXTENDED/screen/screen-4.3.1-libs.patch
  SPECS-EXTENDED/screen/screen-4.3.1-screenrc.patch
  SPECS-EXTENDED/screen/screen-4.3.1-suppress_remap.patch
  SPECS-EXTENDED/screen/screen-4.9.0-braille.patch
  SPECS-EXTENDED/screen/screen-E3.patch
  SPECS-EXTENDED/screen/screen.signatures.json
  SPECS-EXTENDED/screen/screen.spec
  cgmanifest.json
Labels: security, main, specs-extended

#6146 Upgrade xterm 372 -> 380 to address CVE-2022-45063 & CVE-2023-40359
  SPECS-EXTENDED/xterm/xterm-defaults.patch
  SPECS-EXTENDED/xterm/xterm-desktop.patch
  SPECS-EXTENDED/xterm/xterm-man-paths.patch
  SPECS-EXTENDED/xterm/xterm.signatures.json
  SPECS-EXTENDED/xterm/xterm.spec
  cgmanifest.json
Labels: security, main, specs-extended

#6144 Update blobfuse2 to 2.1.0
  SPECS/blobfuse2/blobfuse2.signatures.json
  SPECS/blobfuse2/blobfuse2.spec
  cgmanifest.json
Labels: main

#6104 Upgrade dovecot to 2.3.20 to address CVEs
  SPECS-EXTENDED/dovecot/dovecot-2.1.10-waitonline.patch
  SPECS-EXTENDED/dovecot/dovecot-2.2.20-initbysystemd.patch
  SPECS-EXTENDED/dovecot/dovecot-2.3.11-bigkey.patch
  SPECS-EXTENDED/dovecot/dovecot.signatures.json
  SPECS-EXTENDED/dovecot/dovecot.spec
  cgmanifest.json
Labels: main

#6159 Upgrade mod_auth_openidc 2.4.2.1 -> 2.4.14.2 to address CVE-2021-20718, CVE-2021-39191, CVE-2022-23527, CVE-2023-28625
  SPECS-EXTENDED/mod_auth_openidc/mod_auth_openidc.signatures.json
  SPECS-EXTENDED/mod_auth_openidc/mod_auth_openidc.spec
  cgmanifest.json
Labels: security, main, specs-extended

#6134 Upgrade opensc to 0.23.0 to fix CVE-2021-34193
  SPECS/opensc/CVE-2023-2977.patch
  SPECS/opensc/opensc-0.23.0-pinpad.patch
  SPECS/opensc/opensc.signatures.json
  SPECS/opensc/opensc.spec
  cgmanifest.json
Labels: security, main

#6113 Added ptest results parsing to the `PackageBuild` template
  .pipelines/prchecks/PackageBuildPRCheck.yml
  .pipelines/templates/PackageBuild.yml
  .pipelines/templates/PackageTestResultsAnalysis.yml
  toolkit/tools/scheduler/schedulerutils/buildworker.go
Labels: main

#6165 workflows: bump version of actions/checkout 3 -> 4
  .github/workflows/check-clean-stage.yml
  .github/workflows/check-entangled-specs.yml
  .github/workflows/check-kernel-config.yml
  .github/workflows/check-license-map.yml
  .github/workflows/check-livepatches.yml
  .github/workflows/check-manifests.yml
  .github/workflows/check-package-cgmanifest.yml
  .github/workflows/check-spec.yml
  .github/workflows/check-static-glibc.yml
  .github/workflows/cherry-pick.yml
  .github/workflows/go-test-coverage.yml
  .github/workflows/lint-specs.yml
  .github/workflows/quickstart_1.0.yml
  .github/workflows/quickstart_2.0.yml
Labels: main

#6174 User/bfjelds/buildah CVE 2022 2990
  SPECS-EXTENDED/buildah/CVE-2022-2990.patch
  SPECS-EXTENDED/buildah/buildah.spec
Labels: security, main, specs-extended

#6175 Made `PipAuthenticate` artifact feeds optional for package test analysis.
  .pipelines/templates/PackageBuild.yml
Labels: main

#6177 Upgrade advancecomp 2.4 -> 2.5 to address CVE-2023-2961
  SPECS-EXTENDED/advancecomp/advancecomp.signatures.json
  SPECS-EXTENDED/advancecomp/advancecomp.spec
  cgmanifest.json
Labels: security, main, specs-extended

#6170 Upgrade usbguard 1.0.0->1.1.0 to address CVE-2019-25058
  SPECS-EXTENDED/usbguard/usbguard.signatures.json
  SPECS-EXTENDED/usbguard/usbguard.spec
  cgmanifest.json
Labels: security, main, specs-extended

#6167 Upgrade tang 7 -> 14 to address CVE-2023-1672
  SPECS-EXTENDED/tang/0001-Move-build-system-to-meson.patch
  SPECS-EXTENDED/tang/0002-Move-key-handling-to-tang-itself.patch
  SPECS-EXTENDED/tang/tang.signatures.json
  SPECS-EXTENDED/tang/tang.spec
  SPECS-EXTENDED/tang/tang.sysusers
  cgmanifest.json
Labels: security, main, specs-extended

#6171 Fixing python-more-itertools tests
  SPECS/python-more-itertools/python-more-itertools.spec
Labels: main

#6183 Switched the PR check pipeline to grab agent pools from a shared group.
  .pipelines/prchecks/PackageBuildPRCheck.yml
Labels: main

#6191 Apply fixes to vim for CVE-2023-4734 CVE-2023-4735 CVE-2023-4736
  SPECS/vim/CVE-2023-3896.patch
  SPECS/vim/vim.signatures.json
  SPECS/vim/vim.spec
  cgmanifest.json
Labels: security, main

#6189 bump frr to 8.5.3 for CVE-2023-41358 CVE-2023-41359 CVE-2023-41360
  SPECS/frr/CVE-2023-31490.patch
  SPECS/frr/frr.signatures.json
  SPECS/frr/frr.spec
  cgmanifest.json
Labels: security, main

#6188 Update welcome text
  toolkit/scripts/containerized-build/resources/setup_functions.sh
  toolkit/scripts/containerized-build/resources/welcome.txt
Labels: main, DevEx

#6192 fix docker command
  toolkit/scripts/containerized-build/create_container_build.sh
Labels: main, DevEx

#6182 cmake patch for CVE-2023-35495
  SPECS/cmake/CVE-2023-35945.patch
  SPECS/cmake/cmake.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, main

#6186 Address nodejs CVEs 32002 32006 32559
  SPECS/nodejs/CVE-2022-25883-v18.patch
  SPECS/nodejs/nodejs.signatures.json
  SPECS/nodejs/nodejs.spec
  SPECS/nodejs/nodejs18.signatures.json
  SPECS/nodejs/nodejs18.spec
  cgmanifest.json
Labels: security, main

#6193 patch libtommath for CVE-2023-36328
  SPECS-EXTENDED/libtommath/CVE-2023-36328.patch
  SPECS-EXTENDED/libtommath/libtommath.spec
Labels: security, main

#6194 patch tcl for CVE-2023-36328
  SPECS/tcl/CVE-2023-36328.patch
  SPECS/tcl/tcl.spec
  cgmanifest.json
Labels: security, main

#6187 Upgrade wireshark 3.4.16 -> 4.0.8 to address 27 CVEs
  SPECS-EXTENDED/wireshark/wireshark-0002-Customize-permission-denied-error.patch
  SPECS-EXTENDED/wireshark/wireshark-0003-fix-string-overrun-in-plugins-profinet.patch
  SPECS-EXTENDED/wireshark/wireshark-0004-Restore-Fedora-specific-groups.patch
  SPECS-EXTENDED/wireshark/wireshark-0005-Fix-paths-in-a-wireshark.desktop-file.patch
  SPECS-EXTENDED/wireshark/wireshark-0006-Move-tmp-to-var-tmp.patch
  SPECS-EXTENDED/wireshark/wireshark-0007-cmakelists.patch
  SPECS-EXTENDED/wireshark/wireshark-0008-glib2-g_strdup-build.patch
  SPECS-EXTENDED/wireshark/wireshark-0009-fix-asn2wrs-cmake.patch
  SPECS-EXTENDED/wireshark/wireshark-0010-ripemd-fips-core-dump.patch
  SPECS-EXTENDED/wireshark/wireshark-0011-manage-interfaces-crash.patch
  SPECS-EXTENDED/wireshark/wireshark.signatures.json
  SPECS-EXTENDED/wireshark/wireshark.spec
  cgmanifest.json
Labels: security, main, specs-extended

#6180 nodejs: CVE-2023-35945
  SPECS/nodejs/CVE-2023-35945-v18.patch
  SPECS/nodejs/CVE-2023-35945.patch
  SPECS/nodejs/nodejs.spec
  SPECS/nodejs/nodejs18.spec
Labels: security, main

#6161 Upgrade libmicrohttpd 0.9.71 -> 0.9.76 to address CVE-2023-27371
  SPECS-EXTENDED/libmicrohttpd/libmicrohttpd.signatures.json
  SPECS-EXTENDED/libmicrohttpd/libmicrohttpd.spec
  cgmanifest.json
Labels: security, main, specs-extended

#6163 Upgrade opencryptoki 3.13.0 -> 3.17.0 to address CVE-2021-3798
  SPECS-EXTENDED/opencryptoki/opencryptoki.signatures.json
  SPECS-EXTENDED/opencryptoki/opencryptoki.spec
  cgmanifest.json
Labels: security, main, specs-extended

#6164 Upgrade flac 1.3.4 -> 1.4.3 to address CVE-2020-22219
  SPECS-EXTENDED/flac/flac.signatures.json
  SPECS-EXTENDED/flac/flac.spec
  cgmanifest.json
Labels: security, main, specs-extended

#6150 Adds libgeotiff package to specs-extended
  SPECS-EXTENDED/libgeotiff/libgeotiff.signatures.json
  SPECS-EXTENDED/libgeotiff/libgeotiff.spec
  SPECS-EXTENDED/libgeotiff/libgeotiff_cmake.patch
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#6195 Bump the bind version to 9.16.37 to fix CVE-2022-3924, CVE-2022-3094, CVE-2022-3736
  SPECS/bind/bind.signatures.json
  SPECS/bind/bind.spec
  cgmanifest.json
Labels: security, main

#6181 Fix `librelp` tests by adding `glibc-debuginfo`
  SPECS/librelp/librelp.spec
Labels: main

#6149 Add freexl package to specs-extended
  SPECS-EXTENDED/freexl/freexl.signatures.json
  SPECS-EXTENDED/freexl/freexl.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#6173 create SOURCES_DIR
  toolkit/scripts/containerized-build/resources/setup_functions.sh
Labels: main, DevEx

#6136 make tools in parallel
  toolkit/scripts/containerized-build/create_container_build.sh
Labels: main, DevEx

#6125 containerized rpmbuild: fix make target for worker chroot
  toolkit/scripts/containerized-build/create_container_build.sh
Labels: main, DevEx

#6205 Patch CVE-2023-41910 in lldpd package
  SPECS/lldpd/CVE-2023-41910.patch
  SPECS/lldpd/lldpd.spec
Labels: security, main

#6210 Resolve vim CVE-2023-4738, CVE-2023-4750, CVE-2023-4781, CVE-2023-4752 and CVE-2023-4733
  SPECS/vim/vim.signatures.json
  SPECS/vim/vim.spec
  cgmanifest.json
Labels: security, main

#6215 Upgrade imaptest 20210305 to 20210511
  SPECS-EXTENDED/imaptest/imaptest.signatures.json
  SPECS-EXTENDED/imaptest/imaptest.spec
  cgmanifest.json
Labels: main

#6143 Cleaned-up invalid edges from duplicate nodes.
  toolkit/scripts/tools.mk
  toolkit/tools/grapher/grapher.go
Labels: main

#6217 Removed 'exit 1' from 'supermin'.
  SPECS/supermin/supermin.spec
Labels: main

#6137 Add custom build mount
  toolkit/scripts/containerized-build.mk
  toolkit/scripts/containerized-build/create_container_build.sh
Labels: main, DevEx

#6138 Use space as delimiter for multiple extra mounts
  toolkit/scripts/containerized-build.mk
  toolkit/scripts/containerized-build/create_container_build.sh
Labels: main, DevEx

#6218 Patch CVE-2023-41910 in lldpd package (#6205 cherry-pick)
  SPECS/lldpd/CVE-2023-41910.patch
  SPECS/lldpd/lldpd.spec
Labels: security

#6220 Nopatch kernel to fix CVE-2023-4208, CVE-2023-4622
  SPECS/kernel/CVE-2023-4208.nopatch
  SPECS/kernel/CVE-2023-4622.nopatch
Labels: security, main

#6213 gcc: add patch for CVE-2023-4039
  SPECS/gcc/CVE-2023-4039.patch
  SPECS/gcc/gcc.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/Dockerfile
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
  toolkit/scripts/toolchain/container/toolchain_build_temp_tools.sh
  toolkit/scripts/toolchain/create_toolchain_in_container.sh
Labels: security, main

#6225 libguestfs: remove toolchain package requirements to fix build break
  SPECS/libguestfs/libguestfs.spec
Labels: main

#6179 Upgrade wavpack: 5.4.0 -> 5.6.0 to address CVE-2021-44269 & CVE-2022-2476
  SPECS-EXTENDED/wavpack/wavpack.signatures.json
  SPECS-EXTENDED/wavpack/wavpack.spec
  cgmanifest.json
Labels: security, main, specs-extended

#6214 Patch libssh2 to address CVE-2020-22218
  SPECS/libssh2/CVE-2020-22218.patch
  SPECS/libssh2/libssh2.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, main

#6157 Adds libkml package to specs-extended
  SPECS-EXTENDED/libkml/0001-Fix-build-failure-due-to-failure-to-convert-pointer-.patch
  SPECS-EXTENDED/libkml/0002-Fix-mistaken-use-of-std-cerr-instead-of-std-endl.patch
  SPECS-EXTENDED/libkml/0003-Fix-python-tests.patch
  SPECS-EXTENDED/libkml/0004-Correctly-build-and-run-java-test.patch
  SPECS-EXTENDED/libkml/fragile_test.patch
  SPECS-EXTENDED/libkml/libkml-bundle-minizip.patch
  SPECS-EXTENDED/libkml/libkml.signatures.json
  SPECS-EXTENDED/libkml/libkml.spec
  SPECS-EXTENDED/libkml/libkml_crypth.patch
  SPECS-EXTENDED/libkml/libkml_dont-bytecompile.patch
  SPECS-EXTENDED/libkml/libkml_mingw.patch
  SPECS-EXTENDED/libkml/libkml_test_strcmp.patch
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#6154 Adds hdf package to specs-extended
  SPECS-EXTENDED/hdf/h4comp
  SPECS-EXTENDED/hdf/hdf-4.2.4-sparc.patch
  SPECS-EXTENDED/hdf/hdf-aarch64.patch
  SPECS-EXTENDED/hdf/hdf-arm.patch
  SPECS-EXTENDED/hdf/hdf-build.patch
  SPECS-EXTENDED/hdf/hdf-destdir.patch
  SPECS-EXTENDED/hdf/hdf-examplesdir.patch
  SPECS-EXTENDED/hdf/hdf-ppc.patch
  SPECS-EXTENDED/hdf/hdf-ppc64le.patch
  SPECS-EXTENDED/hdf/hdf-s390.patch
  SPECS-EXTENDED/hdf/hdf.signatures.json
  SPECS-EXTENDED/hdf/hdf.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#6227 containerized-rpmbuild: add arch to welcome txt
  toolkit/scripts/containerized-build/create_container_build.sh
  toolkit/scripts/containerized-build/resources/welcome.txt
Labels: main

#6054 Add SliceToSet() to sliceutils
  toolkit/tools/depsearch/depsearch.go
  toolkit/tools/internal/sliceutils/sliceutils.go
  toolkit/tools/internal/sliceutils/sliceutils_test.go
  toolkit/tools/scheduler/schedulerutils/buildlist.go
  toolkit/tools/scheduler/schedulerutils/graphbuildstate.go
Labels: main

#6226 Upgrade exiv2 0.27.5 -> 0.28.0
  SPECS-EXTENDED/exiv2/exiv2.signatures.json
  SPECS-EXTENDED/exiv2/exiv2.spec
  SPECS-EXTENDED/libgexiv2/libgexiv2.signatures.json
  SPECS-EXTENDED/libgexiv2/libgexiv2.spec
  cgmanifest.json
Labels: security, main, specs-extended

#6172 createrepo in all repos defined in local.repo
  toolkit/scripts/containerized-build/resources/setup_functions.sh
Labels: Tools, main, DevEx

#6229 containerized-rpmbuild: use folder definitions from Makefile
  toolkit/scripts/containerized-build.mk
  toolkit/scripts/containerized-build/create_container_build.sh
Labels: Tools, main, DevEx

#6231 re2c: upgrade to version 2.0 to fix CVE-2018-21232
  SPECS-EXTENDED/re2c/re2c.signatures.json
  SPECS-EXTENDED/re2c/re2c.spec
  cgmanifest.json
Labels: security, main, specs-extended

#6199 Added a toolkit check for required tooling.
  toolkit/scripts/tools.mk
Labels: main

#6050 Remove default CONFIG_FILE=
  .github/workflows/quickstart_1.0.yml
  .github/workflows/quickstart_2.0.yml
  toolkit/Makefile
  toolkit/docs/building/building.md
Labels: main

#6100 Use the PIC'ed version of libiberty.a static object
  SPECS/binutils/binutils.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#6237 Revert "Added a toolkit check for required tooling. (#6199)"
  toolkit/scripts/tools.mk
Labels: main

#6155 Adds netcdf package to specs-extended
  SPECS-EXTENDED/netcdf/netcdf-plugin.patch
  SPECS-EXTENDED/netcdf/netcdf.signatures.json
  SPECS-EXTENDED/netcdf/netcdf.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#6236 Fix systemd/systemd-bootstrap confusion by adding explicit requires
  SPECS-EXTENDED/gnome-desktop-testing/gnome-desktop-testing.spec
  SPECS-EXTENDED/iio-sensor-proxy/iio-sensor-proxy.spec
  SPECS-EXTENDED/iwd/iwd.spec
  SPECS-EXTENDED/pacemaker/pacemaker.spec
  SPECS-EXTENDED/samba/samba.spec
  SPECS-EXTENDED/systemd-bootchart/systemd-bootchart.spec
  cgmanifest.json
Labels: main

#6178 Upgrade fapolicyd 1.0.2 -> 1.3.2 to address CVE-2022-1117
  SPECS-EXTENDED/fapolicyd/fapolicyd-magic-override.patch
  SPECS-EXTENDED/fapolicyd/fapolicyd.signatures.json
  SPECS-EXTENDED/fapolicyd/fapolicyd.spec
  SPECS-EXTENDED/fapolicyd/selinux.patch
  cgmanifest.json
Labels: security, main, specs-extended

#6240 Upgrade python-ldap 3.3.1 -> 3.4.0 to address CVE-2021-46823
  SPECS-EXTENDED/python-ldap/python-ldap.signatures.json
  SPECS-EXTENDED/python-ldap/python-ldap.spec
  cgmanifest.json
Labels: security, main, specs-extended

#6124 set starting directory based on mode
  toolkit/scripts/containerized-build/create_container_build.sh
  toolkit/scripts/containerized-build/resources/mariner.Dockerfile
Labels: Tools, main, DevEx

#6223 Updated usage of `pip` in the package build template.
  .pipelines/templates/PackageBuild.yml
  .pipelines/templates/PackageTestResultsAnalysis.yml
Labels: main

#6244 Re-enable tests for gnutls, jna, libsoup, strongswan
  toolkit/resources/manifests/package/macros.override
Labels: main

#5982 Mariner Image Customizer boilerplate
  .github/workflows/go-test-coverage.yml
  toolkit/tools/go.mod
  toolkit/tools/imagecustomizer/main.go
  toolkit/tools/imagecustomizerapi/README.md
  toolkit/tools/imagecustomizerapi/fileconfig.go
  toolkit/tools/imagecustomizerapi/fileconfig_test.go
  toolkit/tools/imagecustomizerapi/filepermissions.go
  toolkit/tools/imagecustomizerapi/filepermissions_test.go
  toolkit/tools/imagecustomizerapi/systemconfig.go
  toolkit/tools/imagecustomizerapi/systemconfig_test.go
  toolkit/tools/imagecustomizerapi/utils.go
  toolkit/tools/imagecustomizerapi/utils_test.go
  toolkit/tools/imagegen/diskutils/diskutils.go
  toolkit/tools/internal/safechroot/safechroot.go
  toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
  toolkit/tools/pkg/imagecustomizerlib/customizeutils_test.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
  toolkit/tools/pkg/imagecustomizerlib/main_test.go
  toolkit/tools/pkg/imagecustomizerlib/testdata/addfiles-config.yaml
  toolkit/tools/pkg/imagecustomizerlib/testdata/files/a.txt
Labels: main

#6239 Address CVE-2023-29383 in shadow-utils
  SPECS/shadow-utils/CVE-2023-29383.patch
  SPECS/shadow-utils/shadow-utils.spec
Labels: security, main

#6242 Add SPDX license guidance to spec guidelines check
  toolkit/scripts/check_spec_guidelines.py
Labels: main

#6258 Upgrade mutt 2.0.5 -> 2.2.12 to address CVEs
  SPECS-EXTENDED/mutt/CVE-2021-32055.patch
  SPECS-EXTENDED/mutt/CVE-2023-4874.patch
  SPECS-EXTENDED/mutt/mutt-1.9.4-lynx_no_backscapes.patch
  SPECS-EXTENDED/mutt/mutt-2.2.12-lynx_no_backscapes.patch
  SPECS-EXTENDED/mutt/mutt-2.2.12-system_certs.patch
  SPECS-EXTENDED/mutt/mutt.signatures.json
  SPECS-EXTENDED/mutt/mutt.spec
  cgmanifest.json
Labels: main

#6259 Make CONFIG_FILE default assignment consistent
  toolkit/Makefile
Labels: main

#6260 Disable unreliable test
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
Labels: main

#6200 Add `help` target to toolkit Makefile
  toolkit/Makefile
  toolkit/docs/building/building.md
  toolkit/scripts/containerized-build.mk
  toolkit/scripts/help.mk
  toolkit/scripts/imggen.mk
  toolkit/scripts/incremental_building.mk
  toolkit/scripts/pkggen.mk
  toolkit/scripts/srpm_expand.mk
  toolkit/scripts/srpm_pack.mk
  toolkit/scripts/toolchain.mk
  toolkit/scripts/toolkit.mk
  toolkit/scripts/tools.mk
Labels: main

#6243 Get go tools unit tests to pass in VSCode
  toolkit/tools/imagegen/configuration/networkconfig.go
  toolkit/tools/imagegen/configuration/networkconfig_test.go
  toolkit/tools/imagegen/installutils/installutils_test.go
  toolkit/tools/internal/safechroot/safechroot_test.go
  toolkit/tools/internal/timestamp/timestamp_test.go
Labels: main

#6263 Nopatch kernel for CVE-2023-0160, CVE-2023-4273, CVE-2023-4394 and CV…
  SPECS/kernel/CVE-2023-0160.nopatch
  SPECS/kernel/CVE-2023-4273.nopatch
  SPECS/kernel/CVE-2023-4394.nopatch
  SPECS/kernel/CVE-2023-4569.nopatch
Labels: security, main

#6230 Add gdal package to specs-extended
  SPECS-EXTENDED/gdal/cpl-config.h
  SPECS-EXTENDED/gdal/gdal-config
  SPECS-EXTENDED/gdal/gdal.signatures.json
  SPECS-EXTENDED/gdal/gdal.spec
  SPECS-EXTENDED/gdal/gdal_utils.patch
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#6169 Upgrade freeradius 3.0.21 -> 3.2.3 to address 2 CVEs
  SPECS-EXTENDED/freeradius/fix-error-for-expansion-of-macro-in-thread.h.patch
  SPECS-EXTENDED/freeradius/freeradius-Use-system-crypto-policy-by-default.patch
  SPECS-EXTENDED/freeradius/freeradius-no-buildtime-cert-gen.patch
  SPECS-EXTENDED/freeradius/freeradius.signatures.json
  SPECS-EXTENDED/freeradius/freeradius.spec
  SPECS-EXTENDED/freeradius/freeradius.sysusers
  cgmanifest.json
Labels: main

#5968 Update KeysInUse-OpenSSL package to 0.3.4
  SPECS/KeysInUse-OpenSSL/KeysInUse-OpenSSL.signatures.json
  SPECS/KeysInUse-OpenSSL/KeysInUse-OpenSSL.spec
  cgmanifest.json
Labels: main

#6257 Upgrade libvorbis 1.3.6->1.3.7 to address CVE-2018-10392 CVE-2018-10393
  SPECS-EXTENDED/libvorbis/libvorbis-1.3.6-git.patch
  SPECS-EXTENDED/libvorbis/libvorbis.signatures.json
  SPECS-EXTENDED/libvorbis/libvorbis.spec
  cgmanifest.json
Labels: security, main, specs-extended

#5989 feat: Enable grub2-mkconfig generation of grub config
  SPECS-SIGNED/grub2-efi-binary-signed/grub2-efi-binary-signed.spec
  SPECS-SIGNED/kernel-azure-signed/kernel-azure-signed.spec
  SPECS-SIGNED/kernel-hci-signed/kernel-hci-signed.spec
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/grub2/grub2.signatures.json
  SPECS/grub2/grub2.spec
  SPECS/grub2/macros.grub2
  SPECS/kernel-azure/kernel-azure.spec
  SPECS/kernel-hci/kernel-hci.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel-mshv/50_mariner_mshv.cfg
  SPECS/kernel-mshv/kernel-mshv.signatures.json
  SPECS/kernel-mshv/kernel-mshv.spec
  SPECS/kernel/kernel.spec
  toolkit/resources/assets/grub2/grub
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/tools/imagegen/installutils/installutils.go
Labels: main

#6056 Add shell.ExecuteInDirectory()
  toolkit/tools/internal/shell/shell.go
Labels: main

#6055 Resolve Golang warnings, fix text output in depsearch.
  toolkit/tools/depsearch/depsearch.go
  toolkit/tools/internal/pkggraph/pkggraph_test.go
Labels: main

#6278 Skip TestCustomizeImageEmptyConfig test
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
Labels: main

#6285 Bump openmpi version to rebuild with pmix for CVE-2023-41915
  SPECS/openmpi/openmpi.spec
Labels: main

#6284 docs: nvidia: update pmc link to 2.0
  toolkit/docs/nvidia/nvidia.md
Labels: documentation, main

#6268 Made package test name configurable.
  .pipelines/prchecks/PackageBuildPRCheck.yml
  .pipelines/templates/PackageBuild.yml
  .pipelines/templates/PackageTestResultsAnalysis.yml
Labels: main

#6288 Reverted "Cleaned-up invalid edges from duplicate nodes. #6143"
  toolkit/tools/grapher/grapher.go
Labels: main

#6291 Restored "Cleaned-up invalid edges from duplicate nodes. #6143"
  toolkit/tools/grapher/grapher.go
Labels: main

#6272 Disabled ACLs for toolchain builds.
  toolkit/scripts/containerized-build.mk
  toolkit/scripts/pkggen.mk
  toolkit/scripts/toolchain.mk
  toolkit/scripts/utils.mk
Labels: main

#6279 Cloud init datasource bug
  SPECS/cloud-init/cloud-init.spec
  SPECS/cloud-init/overrideDatasourceDetection.patch
Labels: main

#6287 Allow scheduler to update cached implicit nodes
  toolkit/tools/scheduler/schedulerutils/implicitprovides.go
Labels: main

#6052 Add handy graph make targest, fix go-deps circular dependnecy, fix clean-input-srpms
  toolkit/scripts/pkggen.mk
  toolkit/scripts/srpm_pack.mk
  toolkit/scripts/tools.mk
Labels: main

#6262 Make safeunmount.sh run in parallel
  toolkit/scripts/pkggen.mk
  toolkit/scripts/safeunmount.sh
Labels: main

#6290 Damcilva/2.0/tools/add scheduler stuck debug code
  toolkit/tools/scheduler/scheduler.go
Labels: main

#6216 Add a fallback lazy mode to chroot unmount
  toolkit/tools/go.mod
  toolkit/tools/go.sum
  toolkit/tools/internal/safechroot/safechroot.go
Labels: main

#6228 Support repofiles in precacher tool
  toolkit/scripts/precache.mk
  toolkit/tools/precacher/precacher.go
Labels: Tools, main

#6198 Upgrade rust to 1.72.0 to resolve CVE-2023-38497, CVE-2023-40030
  SPECS-EXTENDED/ripgrep/ripgrep.spec
  SPECS/clamav/clamav.signatures.json
  SPECS/clamav/clamav.spec
  SPECS/cloud-hypervisor/cloud-hypervisor.spec
  SPECS/flux/0001-libflux-unblock-build-by-allowing-warnings.patch
  SPECS/flux/flux.spec
  SPECS/influxdb/influxdb.spec
  SPECS/kata-containers-cc/0001-tardev-snapshotter-enable-feature-impl_trait_in_asso.patch
  SPECS/kata-containers-cc/drop-mut-for-variables-that-are-not-mutated.patch
  SPECS/kata-containers-cc/kata-containers-cc.spec
  SPECS/kata-containers/drop-mut-for-variables-that-are-not-mutated.patch
  SPECS/kata-containers/kata-containers.spec
  SPECS/librsvg2/librsvg2.spec
  SPECS/mozjs/mozjs.spec
  SPECS/netavark/netavark.spec
  SPECS/rpm-ostree/rpm-ostree.spec
  SPECS/rust/CVE-2023-27477.patch
  SPECS/rust/generate_source_tarball.sh
  SPECS/rust/rust.signatures.json
  SPECS/rust/rust.spec
  cgmanifest.json
Labels: security, main

#6282 Do not repeat the assets mount point directory name.
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/imager/imager.go
Labels: main

#6316 Genericize partition functions
  toolkit/tools/imagegen/configuration/partitionsetting.go
  toolkit/tools/imagegen/configuration/systemconfig.go
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/imager/imager.go
Labels: main

#6317 Added `gtk-doc` dependencies to the chroot.
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
Labels: main

#6312 Update sriov to v3.5.1
  SPECS/sriov-network-device-plugin/sriov-network-device-plugin.signatures.json
  SPECS/sriov-network-device-plugin/sriov-network-device-plugin.spec
  cgmanifest.json
Labels: main

#6252 Imgcustomizer: Discover partitions using grub.cfg and fstab files
  toolkit/tools/imagecustomizerapi/fileconfig.go
  toolkit/tools/imagecustomizerapi/filepermissions.go
  toolkit/tools/imagecustomizerapi/systemconfig.go
  toolkit/tools/imagegen/diskutils/diskutils.go
  toolkit/tools/imagegen/diskutils/fstab.go
  toolkit/tools/internal/safemount.go/safemount.go
  toolkit/tools/pkg/imagecustomizerlib/customizeutils_test.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
  toolkit/tools/pkg/imagecustomizerlib/main_test.go
Labels: main

#6307 QEMU guest & BareMetal image definitions
  toolkit/imageconfigs/baremetal.json
  toolkit/imageconfigs/packagelists/baremetal-packages.json
  toolkit/imageconfigs/packagelists/qemu-guest-packages.json
  toolkit/imageconfigs/qemu-guest.json
Labels: main
