Repository microsoft/azurelinux, pull requests merged in 2023-06, with the labels that each got.

#5608 Fix occasional test failure in timestamp test
  toolkit/tools/internal/timestamp/timestamp_test.go
Labels: main

#5604 Upgrade python3 to 3.7.16 to address CVE-2022-42929 and CVE-2022-45061
  SPECS/python3/CVE-2015-20107.patch
  SPECS/python3/CVE-2021-28861.patch
  SPECS/python3/CVE-2022-37454.patch
  SPECS/python3/python3.signatures.json
  SPECS/python3/python3.spec
  cgmanifest.json
  toolkit/scripts/toolchain/container/toolchain-remote-wget-list
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
  toolkit/scripts/toolchain/container/toolchain_build_temp_tools.sh
Labels: 1.0-dev

#5611 Fix extra line continuation in cryptsetup build spec
  SPECS/cryptsetup/cryptsetup.spec
Labels: main

#5613 Remove timestamp code from scheduler
  toolkit/tools/scheduler/scheduler.go
  toolkit/tools/scheduler/schedulerutils/buildworker.go
Labels: main

#5597 Upgrading cdi to v1.55.0
  SPECS/containerized-data-importer/containerized-data-importer.signatures.json
  SPECS/containerized-data-importer/containerized-data-importer.spec
  cgmanifest.json
Labels: main

#5598 Install known-good pytest for python-click package test
  SPECS/python-click/python-click.spec
Labels: main

#5616 llvm: limit 2 compile jobs in parallel
  SPECS/llvm/llvm.spec
  SPECS/llvm/llvm16.spec
Labels: main

#5524 [main] update libdrm to 2.4.114
  SPECS/libdrm/README.rst
  SPECS/libdrm/libdrm-2.4.0-no-bc.patch
  SPECS/libdrm/libdrm.signatures.json
  SPECS/libdrm/libdrm.spec
  cgmanifest.json
Labels: main

#5619 Nopatch kernel for CVE-2022-4696, CVE-2023-1382, CVE-2023-1859, CVE-2023-2006, CVE-2023-2008, CVE-2023-2162, CVE-2023-2166, CVE-2023-2177, CVE-2023-2194, CVE-2023-2513, CVE-2023-28328
  SPECS/kernel/CVE-2022-4696.nopatch
  SPECS/kernel/CVE-2023-1382.nopatch
  SPECS/kernel/CVE-2023-1859.nopatch
  SPECS/kernel/CVE-2023-2006.nopatch
  SPECS/kernel/CVE-2023-2008.nopatch
  SPECS/kernel/CVE-2023-2162.nopatch
  SPECS/kernel/CVE-2023-2166.nopatch
  SPECS/kernel/CVE-2023-2177.nopatch
  SPECS/kernel/CVE-2023-2194.nopatch
  SPECS/kernel/CVE-2023-2513.nopatch
  SPECS/kernel/CVE-2023-28328.nopatch
Labels: security, 1.0-dev

#5617 Patch Python 2.7.18 for CVE-2022-45061
  SPECS/python2/CVE-2022-45061.patch
  SPECS/python2/python2.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#5612 Patch gnupg2 CVE-2022-34903
  SPECS/gnupg2/CVE-2022-34903.patch
  SPECS/gnupg2/gnupg2.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#5600 Align mariner_cmdline_mshv with old linuxloader's config
  SPECS/kernel-mshv/kernel-mshv.spec
Labels: main

#5609 Allow DHCP6 related packets through firewall
  SPECS/iptables/ip6save
  SPECS/iptables/iptables.signatures.json
  SPECS/iptables/iptables.spec
Labels: main

#5630 Documentation: Update recommended golang version
  toolkit/docs/building/prerequisites-mariner.md
  toolkit/docs/building/prerequisites-ubuntu.md
Labels: main

#5628 Resolve CVE-2018-25032 in openjdk8
  SPECS/openjdk8/openjdk8.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, 1.0-dev

#5636 qt5-qtsvg: fix file format for CVE-2023-32573 patch
  SPECS/qt5-qtsvg/CVE-2023-32573.patch
Labels: security, 1.0-dev

#5620 Adding networkd-dispatcher SPEC
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/networkd-dispatcher/networkd-dispatcher.signatures.json
  SPECS/networkd-dispatcher/networkd-dispatcher.spec
  cgmanifest.json
Labels: main

#5510 Add fonts-rpm-macros to Mariner
  SPECS-EXTENDED/fonts-rpm-macros/fonts-rpm-macros-omit-foundry-in-family.patch
  SPECS-EXTENDED/fonts-rpm-macros/fonts-rpm-macros.signatures.json
  SPECS-EXTENDED/fonts-rpm-macros/fonts-rpm-macros.spec
  SPECS-EXTENDED/fonts-rpm-macros/update_for_mariner.patch
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#5632 Patch cmake vendored curl for CVE-2023-23914
  SPECS/cmake/CVE-2023-23914-0001-share-add-sharing-of-HSTS-cache-among-handles.patch
  SPECS/cmake/CVE-2023-23914-0002-hsts-handle-adding-the-same-host-name-again.patch
  SPECS/cmake/cmake.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5634 Upgrade c-ares for CVE-2023-32067, CVE-2023-31130, and CVE-2023-31147
  SPECS/c-ares/c-ares.signatures.json
  SPECS/c-ares/c-ares.spec
  SPECS/grpc/grpc.spec
  SPECS/nodejs/nodejs.spec
  cgmanifest.json
Labels: security, 1.0-dev

#5638 Resolve CVE-2023-0464 in edk2's bundled openssl
  SPECS/edk2/CVE-2023-0464.patch
  SPECS/edk2/edk2.spec
Labels: main

#5639 Patch curl to address CVE-2023-28322
  SPECS/curl/CVE-2023-28322.patch
  SPECS/curl/curl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#5607 Add flag to disable PMC repository
  toolkit/Makefile
  toolkit/docs/building/building.md
  toolkit/scripts/imggen.mk
  toolkit/scripts/pkggen.mk
  toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
  toolkit/tools/imagepkgfetcher/imagepkgfetcher.go
  toolkit/tools/internal/packagerepo/repocloner/repocloner.go
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
Labels: main

#5648 Patch cmake vendored curl for CVE-2023-28322
  SPECS/cmake/CVE-2023-28322-lib-unify-the-upload-method-handling.patch
  SPECS/cmake/cmake.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5646 Fix strace tests by adding patch to account for newer kernel
  SPECS/strace/strace.spec
  SPECS/strace/testfix-landlock-brackets.patch
Labels: main

#5643 Upgrade debootstrap to 1.0.128+nmu2 and promote to base repo
  SPECS-EXTENDED/debootstrap/debootstrap.signatures.json
  SPECS/debootstrap/debootstrap.signatures.json
  SPECS/debootstrap/debootstrap.spec
  cgmanifest.json
Labels: main

#5642 Patch curl to address CVE-2023-28322
  SPECS/curl/CVE-2023-28322.patch
  SPECS/curl/curl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5649 timestamp: Make timestamp flag optional for go tools
  toolkit/tools/grapher/grapher.go
  toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
  toolkit/tools/imageconfigvalidator/imageconfigvalidator.go
  toolkit/tools/imagepkgfetcher/imagepkgfetcher.go
  toolkit/tools/imager/imager.go
  toolkit/tools/internal/timestamp/timestamp_mgr.go
  toolkit/tools/roast/roast.go
  toolkit/tools/scheduler/scheduler.go
  toolkit/tools/specreader/specreader.go
  toolkit/tools/srpmpacker/srpmpacker.go
Labels: main

#5644 Patch CVE-2023-2650 in OpenSSL
  SPECS/openssl/CVE-2023-2650.patch
  SPECS/openssl/openssl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, main

#5650 Created an initial pipeline for the new PR checks.
  .pipelines/PackageBuildPRCheck.yml
  .pipelines/common/libs/build_tools.sh
  .pipelines/common/libs/file_tools.sh
  .pipelines/common/libs/rpm_tools.sh
  .pipelines/common/scripts/PackageSignedRPMs.sh
  .pipelines/livepatching/BuildLivepatch.sh
  .pipelines/livepatching/BuildLivepatchSigned.sh
  .pipelines/livepatching/DeployLivepatch.yml
  .pipelines/livepatching/ExtractKernelModules.sh
  .pipelines/templates/PackageBuild.yml
  .pipelines/templates/ToolchainBuild.yml
Labels: main

#5641 Patch haproxy for CVE-2023-25725
  SPECS/haproxy/CVE-2023-25725-http-properly-reject-empty-http-header-.patch
  SPECS/haproxy/haproxy.spec
Labels: 1.0-dev

#5645 Patch CVE-2023-2650 in OpenSSL
  SPECS/openssl/CVE-2023-2650.patch
  SPECS/openssl/openssl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, 1.0-dev

#5654 Patch CVE-2022-3775 in grub2
  SPECS-SIGNED/grub2-efi-binary-signed/grub2-efi-binary-signed.spec
  SPECS/grub2/CVE-2022-3775.patch
  SPECS/grub2/grub2.spec
Labels: main

#5587 Refactor graphpkgfetcher in preparation for delta feature
  toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
  toolkit/tools/imagepkgfetcher/imagepkgfetcher.go
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
Labels: Tools, main

#5667 Patch CVE-2023-2977 in opensc
  SPECS/opensc/CVE-2023-2977.patch
  SPECS/opensc/opensc.spec
Labels: main

#5668 Patch CVE-2023-2977 in opensc
  SPECS/opensc/CVE-2023-2977.patch
  SPECS/opensc/opensc.spec
Labels: 1.0-dev

#5660 Fix against race condition in unattended install
  toolkit/resources/imageconfigs/additionalfiles/iso_initrd/root/runliveinstaller
  toolkit/scripts/imggen.mk
Labels: main

#5671 Patch CVE-2023-32681 in python-requests
  SPECS/python-requests/CVE-2023-32681.patch
  SPECS/python-requests/python-requests.spec
Labels: main

#5672 Patch CVE-2023-32681 in python-requests
  SPECS/python-requests/CVE-2023-32681.patch
  SPECS/python-requests/python-requests.spec
Labels: 1.0-dev

#5658 Patch openssh handling of smartcard details for CVE-2023-28531
  SPECS/openssh/CVE-2023-28531-upstream-include-destination-constraints-for-smartca.patch
  SPECS/openssh/openssh.spec
Labels: 1.0-dev

#5679 Patch CVE-2023-31975 in yasm
  SPECS/yasm/CVE-2023-31975.patch
  SPECS/yasm/yasm.spec
Labels: security, main

#5681 Patch CVE-2023-31975 in yasm
  SPECS/yasm/CVE-2023-31975.patch
  SPECS/yasm/yasm.spec
Labels: security, 1.0-dev

#5678 Registering /usr/local/sbin within filesystem package
  SPECS/filesystem/filesystem.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5676 [1.0] Fix qt5-qtbase CVE-2023-36762
  SPECS/qt5-qtbase/CVE-2023-32762.patch
  SPECS/qt5-qtbase/qt5-qtbase.spec
Labels: 1.0-dev

#5669 Fix qt5-qtbase CVE-2023-32762
  SPECS/qt5-qtbase/CVE-2023-32762.patch
  SPECS/qt5-qtbase/qt5-qtbase.spec
Labels: main

#5688 toolkit: exclude ccache directory from cleanup
  toolkit/tools/internal/buildpipeline/buildpipeline.go
  toolkit/tools/pkgworker/pkgworker.go
Labels: main

#5686 Fix qt5-qtbase CVE-2023-32763
  SPECS/qt5-qtbase/CVE-2023-32763.patch
  SPECS/qt5-qtbase/qt5-qtbase.spec
Labels: main

#5685 [1.0] Fix qt5-qtbase CVE-2023-32763
  SPECS/qt5-qtbase/CVE-2023-32763.patch
  SPECS/qt5-qtbase/qt5-qtbase.spec
Labels: 1.0-dev

#5691 Patch CVE-2023-2650 in cloud-hypervisor
  SPECS/cloud-hypervisor/CVE-2023-2650.patch
  SPECS/cloud-hypervisor/cloud-hypervisor.signatures.json
  SPECS/cloud-hypervisor/cloud-hypervisor.spec
Labels: 1.0-dev

#5698 Patch CVE-2023-34411 in mozjs60
  SPECS/mozjs60/CVE-2023-34411.patch
  SPECS/mozjs60/mozjs60.spec
Labels: 1.0-dev

#5677 Toolkit: Add MAX_CPU flag to limit number of CPUS used for package building
  toolkit/Makefile
  toolkit/docs/building/building.md
  toolkit/scripts/incremental_building.mk
  toolkit/scripts/pkggen.mk
  toolkit/tools/internal/rpm/rpm.go
  toolkit/tools/pkgworker/pkgworker.go
  toolkit/tools/scheduler/buildagents/chrootagent.go
  toolkit/tools/scheduler/buildagents/definition.go
  toolkit/tools/scheduler/scheduler.go
Labels: main

#5701 Patch CVE-2023-33460.patch in yajl
  SPECS/yajl/CVE-2023-33460.patch
  SPECS/yajl/yajl.spec
Labels: main

#5702 Patch CVE-2023-33460.patch in yajl
  SPECS/yajl/CVE-2023-33460.patch
  SPECS/yajl/yajl.spec
Labels: 1.0-dev

#5705 Patch tdnf to include SELECTION_DOTARCH libsolv flag for package query/install
  SPECS/tdnf/tdnf-dotarch.patch
  SPECS/tdnf/tdnf.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5700 Patch QEMU to fix CVE-2021-3750
  SPECS/qemu/CVE-2021-3750.patch
  SPECS/qemu/qemu.spec
Labels: main

#5696 Resolve libcap CVE-2023-2602 and CVE-2023-2603
  SPECS/libcap/CVE-2023-2602.patch
  SPECS/libcap/CVE-2023-2603.patch
  SPECS/libcap/libcap.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5711 [1.0] Fix libcap CVE-2023-2603
  SPECS/libcap/CVE-2023-2603.patch
  SPECS/libcap/libcap.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#5661 iptables restart and default rulesets
  SPECS/iptables/ip4save
  SPECS/iptables/ip6save
  SPECS/iptables/iptables
  SPECS/iptables/iptables.signatures.json
  SPECS/iptables/iptables.spec
Labels: main

#5605 Add specarchchecker tool to allow arch validation
  toolkit/scripts/toolkit.mk
  toolkit/scripts/tools.mk
  toolkit/tools/internal/rpm/rpm.go
  toolkit/tools/pkg/rpmssnapshot/rpmssnapshot.go
  toolkit/tools/pkg/simpletoolchroot/simpletoolchroot.go
  toolkit/tools/pkg/specarchchecker/specarchchecker.go
  toolkit/tools/pkgworker/pkgworker.go
  toolkit/tools/rpmssnapshot/rpmssnapshot.go
  toolkit/tools/specarchchecker/specarchchecker.go
  toolkit/tools/specreader/specreader.go
  toolkit/tools/srpmpacker/srpmpacker.go
Labels: Tools, ptest, main

#5530 Add workflow to check for required kernel configs
  .github/workflows/check-kernel-config.yml
  toolkit/scripts/check_new_kernel_configs.py
  toolkit/scripts/check_required_kernel_configs.py
  toolkit/scripts/kernel_sources_analysis.py
  toolkit/scripts/mariner-required-configs.json
Labels: main

#5714 Upgrade msft-golang to fix CVE-2023-29404
  SPECS/msft-golang/msft-golang.signatures.json
  SPECS/msft-golang/msft-golang.spec
  cgmanifest.json
Labels: main

#5718 Minor fix of typo in libcap spec changelog
  SPECS/libcap/libcap.spec
Labels: main

#5710 Switched to GitOps.ResourceManagement from FabricBot.
  .github/fabricbot.json
  .github/policies/resourceManagement.yml
Labels: main

#5687 Added delta toolchain build to automated PR check
  .pipelines/PackageBuildPRCheck.yml
  .pipelines/livepatching/BuildLivepatch.sh
  .pipelines/livepatching/BuildLivepatchSigned.sh
  .pipelines/prchecks/PackageBuildPRCheck.yml
  .pipelines/templates/RawToolchainDownload.yml
  .pipelines/templates/ToolchainBuild.yml
Labels: main

#5666 Update Skopeo to 1.12
  SPECS/skopeo/skopeo.signatures.json
  SPECS/skopeo/skopeo.spec
  cgmanifest.json
Labels: main

#5723 Added extended specs to GitOps config.
  .github/policies/resourceManagement.yml
Labels: main

#5704 add patch for CVE-2023-1786 cloud-init
  SPECS/cloud-init/CVE-2023-1786.patch
  SPECS/cloud-init/cloud-init.spec
Labels: 1.0-dev

#5722 Upgrade golang to 1.19.10 to address CVE-2023-24540, CVE-2023-29402, CVE-2023-29403, CVE-2023-29404, CVE-2023-29405
  SPECS/audit/audit.spec
  SPECS/blobfuse/blobfuse.spec
  SPECS/cni/cni.spec
  SPECS/coredns/coredns-1.8.0.spec
  SPECS/coredns/coredns-1.8.4.spec
  SPECS/coredns/coredns-1.8.6.spec
  SPECS/cri-tools/cri-tools.spec
  SPECS/etcd/etcd-3.4.23.spec
  SPECS/etcd/etcd-3.5.0.spec
  SPECS/etcd/etcd-3.5.1.spec
  SPECS/flannel/flannel.spec
  SPECS/glide/glide.spec
  SPECS/go-md2man/go-md2man.spec
  SPECS/gobject-introspection/gobject-introspection.spec
  SPECS/golang/golang.signatures.json
  SPECS/golang/golang.spec
  SPECS/helm/helm.spec
  SPECS/libnvidia-container/libnvidia-container.spec
  SPECS/moby-buildx/moby-buildx.spec
  SPECS/moby-cli/moby-cli.spec
  SPECS/moby-containerd/moby-containerd.spec
  SPECS/moby-engine/moby-engine.spec
  SPECS/moby-runc/moby-runc.spec
  SPECS/node-problem-detector/node-problem-detector.spec
  SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec
  SPECS/telegraf/telegraf.spec
  cgmanifest.json
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#5716 systemd: Enable audit integration.
  SPECS/systemd/systemd.spec
Labels: main

#5728 toolchain: use latest 2.0 Mariner container for bootstrap build
  toolkit/scripts/toolchain/cgmanifest.json
  toolkit/scripts/toolchain/container/Dockerfile
Labels: main

#5733 Remove duplicate systemd parameters from kernel-mshv cfg
  SPECS/kernel-mshv/kernel-mshv.spec
Labels: main

#5736 Revert "Patch CVE-2023-2650 in cloud-hypervisor"
  SPECS/cloud-hypervisor/CVE-2023-2650.patch
  SPECS/cloud-hypervisor/cloud-hypervisor.signatures.json
  SPECS/cloud-hypervisor/cloud-hypervisor.spec
Labels: security, 1.0-dev

#5732 Add package fsverity-utils
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/fsverity-utils/fsverity-utils.signatures.json
  SPECS/fsverity-utils/fsverity-utils.spec
  cgmanifest.json
Labels: main

#5734 Fix CVE-2023-2454 by upgrading postgresql to 12.15
  SPECS/postgresql/postgresql.signatures.json
  SPECS/postgresql/postgresql.spec
  cgmanifest.json
Labels: 1.0-dev

#5693 rpm: remove unnecessary brp-strip scripts
  SPECS/mariner-rpm-macros/macros
  SPECS/mariner-rpm-macros/mariner-rpm-macros.signatures.json
  SPECS/mariner-rpm-macros/mariner-rpm-macros.spec
  SPECS/rpm/brp-strip-debug-symbols
  SPECS/rpm/brp-strip-unneeded
  SPECS/rpm/rpm.signatures.json
  SPECS/rpm/rpm.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5657 Enable CONFIG_IP_VS_MH module
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/mariner-required-configs.json
Labels: main

#5717 Patching graphviz dot to png error
  SPECS/freefont/freefont.spec
  SPECS/graphviz/graphviz.spec
Labels: main

#5640 toolkit: add feature to profile & trace to have better diagnostics
  toolkit/Makefile
  toolkit/scripts/imggen.mk
  toolkit/scripts/pkggen.mk
  toolkit/scripts/profile.mk
  toolkit/scripts/srpm_pack.mk
  toolkit/scripts/utils.mk
  toolkit/tools/grapher/grapher.go
  toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
  toolkit/tools/imageconfigvalidator/imageconfigvalidator.go
  toolkit/tools/imagepkgfetcher/imagepkgfetcher.go
  toolkit/tools/imager/imager.go
  toolkit/tools/internal/exe/exe.go
  toolkit/tools/pkg/profile/profile.go
  toolkit/tools/roast/roast.go
  toolkit/tools/scheduler/scheduler.go
  toolkit/tools/specreader/specreader.go
  toolkit/tools/srpmpacker/srpmpacker.go
Labels: main

#5726 edk2: Add nvram-template mapping to ovmf x64 config
  SPECS/edk2/60-edk2-ovmf-x64-amdsev.json
  SPECS/edk2/60-edk2-ovmf-x64-inteltdx.json
  SPECS/edk2/edk2.spec
Labels: main

#5745 containerized-data-importer: Add nbkdit as a dependency for the importer
  SPECS/containerized-data-importer/containerized-data-importer.spec
Labels: main

#5603 Enable dm-verity in kernel-uvm
  SPECS/kernel-uvm/config
  SPECS/kernel-uvm/kernel-uvm.signatures.json
  SPECS/kernel-uvm/kernel-uvm.spec
Labels: main

#5755 edk2: fix signatures.json
  SPECS/edk2/edk2.signatures.json
Labels: main

#5743 Nopatch kernel for CVE-2022-48425, CVE-2023-1859, CVE-2023-2002, CVE-…
  SPECS/kernel/CVE-2022-48425.nopatch
  SPECS/kernel/CVE-2023-1859.nopatch
  SPECS/kernel/CVE-2023-2002.nopatch
  SPECS/kernel/CVE-2023-22995.nopatch
  SPECS/kernel/CVE-2023-3111.nopatch
  SPECS/kernel/CVE-2023-3141.nopatch
Labels: security, main

#5762 Included `curl` and `grep` in all core packages.
  SPECS/core-packages/core-packages.spec
Labels: main

#5757 add patch for Mozjs CVE
  SPECS/mozjs/CVE-2022-48285.patch
  SPECS/mozjs/mozjs.spec
Labels: security, main

#5741 add patch for Mozjs60 CVE
  SPECS/mozjs60/CVE-2022-48285.patch
  SPECS/mozjs60/mozjs60.spec
Labels: security, 1.0-dev

#5749 Upgrade kata-containers-cc to version 0.4.2
  SPECS/kata-containers-cc/0001-Enable-using-an-igvm-file-with-cloud-hypervisor.patch
  SPECS/kata-containers-cc/kata-containers-cc.signatures.json
  SPECS/kata-containers-cc/kata-containers-cc.spec
  SPECS/kata-containers-cc/mariner-coco-build-uvm-image.sh
  SPECS/kata-containers-cc/mariner-coco-build-uvm.sh
  cgmanifest.json
Labels: main

#5754 Enable dbus audit logs.
  SPECS/dbus/dbus.spec
Labels: main

#5735 selinux-policy: Fix issues in patches.
  SPECS/selinux-policy/0037-cloudinit-Add-permissions-derived-from-sysadm.patch
  SPECS/selinux-policy/0039-modutils-Temporary-fix-for-mkinitrd-dracut.patch
  SPECS/selinux-policy/selinux-policy.spec
Labels: main

#5746 Unified `fmt.Error` formatting with Go's conventions.
  toolkit/tools/imageconfigvalidator/imageconfigvalidator.go
  toolkit/tools/imagegen/configuration/disk.go
  toolkit/tools/imagegen/configuration/disk_test.go
  toolkit/tools/imagegen/configuration/kernelcommandline.go
  toolkit/tools/imagegen/configuration/kernelcommandline_test.go
  toolkit/tools/imagegen/configuration/packagerepo.go
  toolkit/tools/imagegen/configuration/parse_partition.go
  toolkit/tools/imagegen/configuration/systemconfig.go
  toolkit/tools/imagegen/configuration/systemconfig_test.go
  toolkit/tools/imagegen/diskutils/diskutils.go
  toolkit/tools/imagegen/diskutils/verity.go
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/internal/rpm/rpm.go
  toolkit/tools/internal/storage/storage.go
  toolkit/tools/internal/timestamp/timestamp.go
  toolkit/tools/pkg/profile/profile.go
  toolkit/tools/roast/formats/ova.go
  toolkit/tools/specreader/specreader.go
Labels: main

#5776 June 2023 Update 3 - 1.0
  SPECS/audit/audit.spec
  SPECS/blobfuse/blobfuse.spec
  SPECS/cloud-init/CVE-2023-1786.patch
  SPECS/cloud-init/cloud-init.spec
  SPECS/cni/cni.spec
  SPECS/coredns/coredns-1.8.0.spec
  SPECS/coredns/coredns-1.8.4.spec
  SPECS/coredns/coredns-1.8.6.spec
  SPECS/cri-tools/cri-tools.spec
  SPECS/etcd/etcd-3.4.23.spec
  SPECS/etcd/etcd-3.5.0.spec
  SPECS/etcd/etcd-3.5.1.spec
  SPECS/flannel/flannel.spec
  SPECS/glide/glide.spec
  SPECS/go-md2man/go-md2man.spec
  SPECS/gobject-introspection/gobject-introspection.spec
  SPECS/golang/golang.signatures.json
  SPECS/golang/golang.spec
  SPECS/helm/helm.spec
  SPECS/kernel/CVE-2023-3159.nopatch
  SPECS/kernel/CVE-2023-3161.nopatch
  SPECS/kernel/CVE-2023-34256.nopatch
  SPECS/libcap/CVE-2023-2603.patch
  SPECS/libcap/libcap.spec
  SPECS/libnvidia-container/libnvidia-container.spec
  SPECS/mariner-release/mariner-release.spec
  SPECS/moby-buildx/moby-buildx.spec
  SPECS/moby-cli/moby-cli.spec
  SPECS/moby-containerd/moby-containerd.spec
  SPECS/moby-engine/moby-engine.spec
  SPECS/moby-runc/moby-runc.spec
  SPECS/mozjs60/CVE-2022-48285.patch
  SPECS/mozjs60/CVE-2023-34411.patch
  SPECS/mozjs60/mozjs60.spec
  SPECS/node-problem-detector/node-problem-detector.spec
  SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec
  SPECS/postgresql/postgresql.signatures.json
  SPECS/postgresql/postgresql.spec
  SPECS/telegraf/telegraf.spec
  SPECS/yajl/CVE-2023-33460.patch
  SPECS/yajl/yajl.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security

#5777 Add patch for cloud-init CVE-2023-1786
  SPECS/cloud-init/CVE-2023-1786.patch
  SPECS/cloud-init/cloud-init.spec
Labels: security, main

#5744 Fixed the `PACKAGE_CACHE_SUMMARY` build option.
  toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
  toolkit/tools/imagepkgfetcher/imagepkgfetcher.go
  toolkit/tools/internal/packagerepo/repocloner/repocloner.go
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
  toolkit/tools/internal/packagerepo/repoutils/repoutils.go
  toolkit/tools/internal/rpm/rpm.go
  toolkit/tools/internal/rpm/rpm_test.go
  toolkit/tools/internal/rpm/testdata/no_default_package.spec
  toolkit/tools/internal/rpm/testdata/with_epoch.spec
Labels: Tools, main
