Repository microsoft/azurelinux, pull requests merged in 2023-08, with the labels that each got.

#5906 Updated `pcre2` to version 10.42 to fix CVE-2022-41409.
  SPECS/pcre2/pcre2.signatures.json
  SPECS/pcre2/pcre2.spec
  cgmanifest.json
Labels: main

#5872 Promote rlwrap to SPECS
  SPECS/rlwrap/rlwrap.signatures.json
  SPECS/rlwrap/rlwrap.spec
Labels: main

#5871 Promote opencsd to SPECS
  SPECS/opencsd/opencsd.signatures.json
  SPECS/opencsd/opencsd.spec
Labels: main

#5870 Add new package libtraceevent v1.7.2
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/libtraceevent/libtraceevent.signatures.json
  SPECS/libtraceevent/libtraceevent.spec
  cgmanifest.json
Labels: main

#5896 kernel: update mellanox configuratoins for bluefield2
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/mariner-required-configs.json
Labels: main

#5919 Updated `iperf3` to 3.14 to fix CVE-2023-38403.
  SPECS/iperf3/iperf3.signatures.json
  SPECS/iperf3/iperf3.spec
  cgmanifest.json
Labels: main

#5917 Add patch to fix CVE-2022-47085 in rpm-ostree
  SPECS/rpm-ostree/CVE-2022-47085.patch
  SPECS/rpm-ostree/rpm-ostree.spec
Labels: security, main

#5922 Fix Bug 45595561: Remove .bazelversion file
  SPECS/keras/keras.spec
  SPECS/python-tensorboard/python-tensorboard.spec
  SPECS/tensorflow/tensorflow.spec
Labels: bug, main

#5925 Upgrade Blobfuse2 to 2.0.5
  SPECS/blobfuse2/blobfuse2.signatures.json
  SPECS/blobfuse2/blobfuse2.spec
  cgmanifest.json
Labels: main

#5127 Add protobuf check section
  SPECS/protobuf/protobuf.spec
Labels: main

#5904 Fix a bug in applying earlier patches in dhcp
  SPECS/dhcp/dhcp.spec
Labels: security, 1.0-dev

#5892 Fix a bug in applying earlier patches in dhcp
  SPECS/dhcp/dhcp.spec
Labels: security, main

#5918 gmp: adds c++ support in gmp-devel sub-package
  SPECS/gmp/gmp.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5928 Address hyperv-daemons CVE-2023-38409 CVE-2023-38432
  SPECS/hyperv-daemons/CVE-2023-38409.nopatch
  SPECS/hyperv-daemons/CVE-2023-38432.nopatch
Labels: security, main

#5913 nginx: configure with `--with-compat` to enable dynamic modules compatibility
  SPECS/nginx/nginx.spec
Labels: main

#5937 Patch reaper for CVE-2018-11694 in libsass module
  SPECS/reaper/CVE-2018-11694.patch
  SPECS/reaper/reaper.spec
Labels: security, main

#5923 qt5-qtbase: Add patch for CVE-2023-33285, CVE-2023-37369, CVE-2023-38197
  SPECS/qt5-qtbase/CVE-2023-33285.patch
  SPECS/qt5-qtbase/CVE-2023-37369.patch
  SPECS/qt5-qtbase/CVE-2023-38197.patch
  SPECS/qt5-qtbase/qt5-qtbase.spec
Labels: security, main

#5905 Disabled extended ACLs for whole projects.
  toolkit/scripts/tools.mk
  toolkit/scripts/utils.mk
Labels: main

#5855 Add containerized rpmbuild to toolkit
  toolkit/Makefile
  toolkit/scripts/containerized-build.mk
  toolkit/scripts/containerized-build/create_container_build.sh
  toolkit/scripts/containerized-build/resources/local_repo
  toolkit/scripts/containerized-build/resources/mariner.Dockerfile
  toolkit/scripts/containerized-build/resources/setup_functions.sh
  toolkit/scripts/containerized-build/resources/welcome.txt
  toolkit/scripts/toolchain/toolchain_clean.sh
Labels: main

#5940 Readme for containerized-rpmbuild
  toolkit/docs/building/developer-tools.md
Labels: main

#5941 Merge additional changes for August update
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/livepatch-5.15.122.1-2.cm2/config-5.15.122.1-2.cm2
  SPECS/livepatch-5.15.122.1-2.cm2/livepatch-5.15.122.1-2.cm2.signatures.json
  SPECS/livepatch-5.15.122.1-2.cm2/livepatch-5.15.122.1-2.cm2.spec
  SPECS/livepatch-5.15.122.1-2.cm2/mariner-5.15.122.1-2.cm2.pem
  SPECS/mariner-release/mariner-release.spec
  SPECS/qt5-qtbase/CVE-2023-33285.patch
  SPECS/qt5-qtbase/CVE-2023-37369.patch
  SPECS/qt5-qtbase/CVE-2023-38197.patch
  SPECS/qt5-qtbase/qt5-qtbase.spec
  SPECS/reaper/CVE-2018-11694.patch
  SPECS/reaper/reaper.spec
  cgmanifest.json
  toolkit/Makefile
  toolkit/docs/building/developer-tools.md
  toolkit/scripts/containerized-build.mk
  toolkit/scripts/containerized-build/create_container_build.sh
  toolkit/scripts/containerized-build/resources/local_repo
  toolkit/scripts/containerized-build/resources/mariner.Dockerfile
  toolkit/scripts/containerized-build/resources/setup_functions.sh
  toolkit/scripts/containerized-build/resources/welcome.txt
  toolkit/scripts/toolchain/toolchain_clean.sh
  toolkit/scripts/tools.mk
  toolkit/scripts/utils.mk
Labels: security

#5939 Made `python-certifi` stop using its bundled certificates to fix CVE-2023-37920.
  SPECS/python-certifi/certifi-2022.12.07-use-system-cert.patch
  SPECS/python-certifi/python-certifi.signatures.json
  SPECS/python-certifi/python-certifi.spec
  cgmanifest.json
Labels: main

#5955 Upgrade curl to 8.2.1 to address CVE-2023-32001
  SPECS/curl/CVE-2023-28322.patch
  SPECS/curl/curl.signatures.json
  SPECS/curl/curl.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, main

#5953 Refactor randomization to have const input strings
  toolkit/tools/imagegen/attendedinstaller/uitext/uitext.go
  toolkit/tools/imagegen/attendedinstaller/views/diskview/manualpartitionwidget/manualpartitionwidget.go
  toolkit/tools/imagegen/attendedinstaller/views/hostnameview/hostnameview.go
  toolkit/tools/imagegen/diskutils/verity.go
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/internal/randomization/randomization.go
Labels: main

#5951 kernel-hci: Update config to enable DM multipath Kernel configurations.
  SPECS-SIGNED/kernel-hci-signed/kernel-hci-signed.spec
  SPECS/kernel-hci/config
  SPECS/kernel-hci/kernel-hci.signatures.json
  SPECS/kernel-hci/kernel-hci.spec
Labels: main

#5907 Extend `AdditionalFiles` config
  toolkit/docs/formats/imageconfig.md
  toolkit/tools/imagegen/configuration/configuration.go
  toolkit/tools/imagegen/configuration/configuration_test.go
  toolkit/tools/imagegen/configuration/fileconfig.go
  toolkit/tools/imagegen/configuration/fileconfig_test.go
  toolkit/tools/imagegen/configuration/filepermissions.go
  toolkit/tools/imagegen/configuration/filepermissions_test.go
  toolkit/tools/imagegen/configuration/systemconfig.go
  toolkit/tools/imagegen/configuration/systemconfig_test.go
  toolkit/tools/imagegen/configuration/testdata/test_configuration.json
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/imagegen/installutils/installutils_test.go
  toolkit/tools/imagegen/installutils/testdata/a.txt
  toolkit/tools/imager/imager.go
  toolkit/tools/internal/ptrutils/ptrutils.go
  toolkit/tools/internal/safechroot/safechroot.go
  toolkit/tools/isomaker/maker.go
Labels: main

#5952 Add lld16 package to Mariner
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/lld/lld16.signatures.json
  SPECS/lld/lld16.spec
  cgmanifest.json
Labels: main

#5950 Use sparse raw image file
  toolkit/tools/imagegen/diskutils/diskutils.go
Labels: main

#5958 Add requires for glibc-debuginfo to valgrind spec
  SPECS/valgrind/valgrind.spec
Labels: main

#5961 Updated package building pipeline templates to support external repos.
  .pipelines/prchecks/PackageBuildPRCheck.yml
  .pipelines/templates/PackageBuild.yml
  .pipelines/templates/ToolchainBuild.yml
  toolkit/Makefile
  toolkit/docs/building/building.md
  toolkit/scripts/pkggen.mk
  toolkit/scripts/toolchain/build_mariner_toolchain.sh
  toolkit/scripts/tools.mk
Labels: main

#5947 opentelemetry-cpp: add package v1.10.0
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/opentelemetry-cpp/opentelemetry-cpp.signatures.json
  SPECS/opentelemetry-cpp/opentelemetry-cpp.spec
  cgmanifest.json
Labels: main

#5971 Add python-cstruct package
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/python-cstruct/python-cstruct.signatures.json
  SPECS/python-cstruct/python-cstruct.spec
  cgmanifest.json
Labels: main

#5967 Restored the `cache` subdirectory.
  toolkit/scripts/pkggen.mk
  toolkit/scripts/tools.mk
Labels: main

#5972 Enable CONFIG_BLK_DEV_NBD module
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/mariner-required-configs.json
Labels: main

#5960 Add hard check on go version
  toolkit/scripts/tools.mk
Labels: main

#5979 Clarified handling of rich dependencies and unified package string parsing.
  toolkit/docs/how_it_works/3_package_building.md
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/internal/pkgjson/pkgjson.go
  toolkit/tools/internal/pkgjson/pkgjson_test.go
  toolkit/tools/specreader/specreader.go
Labels: main

#5988 Added tool name to printed logs.
  toolkit/tools/go.mod
  toolkit/tools/go.sum
  toolkit/tools/internal/logger/log.go
  toolkit/tools/internal/logger/writerhook.go
Labels: main

#5975 nginx: configure with `--with-stream_ssl_module` to enable support for stream proxy server with SSL/TLS
  SPECS/nginx/nginx.spec
Labels: main

#5976 Add new package xerces-c v3.2.4
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/xerces-c/xerces-c.signatures.json
  SPECS/xerces-c/xerces-c.spec
  cgmanifest.json
Labels: main

#5986 Fix CVE-2023-37460 by patching plexus-archiver
  SPECS/javapackages-bootstrap/CVE-2023-37460.patch
  SPECS/javapackages-bootstrap/javapackages-bootstrap.spec
Labels: security

#5987 add patch for cloud-init TestGetInterfaces mock test failure
  SPECS/cloud-init/cloud-init.spec
  SPECS/cloud-init/testGetInterfacesUnitTest.patch
Labels: main

#5995 Revert "Fix CVE-2023-37460 by patching plexus-archiver"
  SPECS/javapackages-bootstrap/CVE-2023-37460.patch
  SPECS/javapackages-bootstrap/javapackages-bootstrap.spec
Labels: security

#5996 Fix CVE-2023-36617 by patching plexus-archiver
  SPECS/javapackages-bootstrap/CVE-2023-37460.patch
  SPECS/javapackages-bootstrap/javapackages-bootstrap.spec
Labels: security, main

#5886 Make the release tag static once calculated
  toolkit/scripts/build_tag.mk
  toolkit/scripts/imggen.mk
Labels: Tools, main

#5992 Update ruby default uri to 0.12.2 and bundled uri to 0.10.3 and fix CVE-2023-36617
  SPECS/ruby/CVE-2023-36617.patch
  SPECS/ruby/ruby.spec
Labels: security, main

#5998 Patch CVE-2023-3896
  SPECS/vim/CVE-2023-3896.patch
  SPECS/vim/vim.spec
Labels: security, main

#5999 Patch CVE-2023-3896 vulnerability in vim
  SPECS/vim/CVE-2023-3896.patch
  SPECS/vim/vim.spec
Labels: security, 1.0-dev

#5997 Bump curl to 8.2.1 to address CVE-2023-32001
  SPECS/curl/CVE-2023-28322.patch
  SPECS/curl/curl.signatures.json
  SPECS/curl/curl.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, 1.0-dev

#6008 Fix CVE-2023-39533: update msft-golang to use 1.19.12 which contains fix
  SPECS/msft-golang/msft-golang.signatures.json
  SPECS/msft-golang/msft-golang.spec
  cgmanifest.json
Labels: security, main

#5863 Resolved cyclic ptest dependencies
  toolkit/Makefile
  toolkit/docs/building/building.md
  toolkit/scripts/pkggen.mk
  toolkit/scripts/toolkit.mk
  toolkit/scripts/utils.mk
  toolkit/tools/graphPreprocessor/graphPreprocessor.go
  toolkit/tools/graphanalytics/graphanalytics.go
  toolkit/tools/grapher/grapher.go
  toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
  toolkit/tools/imagepkgfetcher/imagepkgfetcher.go
  toolkit/tools/internal/pkggraph/cyclefind.go
  toolkit/tools/internal/pkggraph/pkggraph.go
  toolkit/tools/internal/pkggraph/pkggraph_test.go
  toolkit/tools/internal/pkgjson/pkgjson.go
  toolkit/tools/internal/rpm/rpm.go
  toolkit/tools/internal/rpm/rpm_test.go
  toolkit/tools/internal/rpm/testdata/no_default_package_or_check.spec
  toolkit/tools/internal/rpm/testdata/with_epoch_and_check.spec
  toolkit/tools/pkg/specarchchecker/specarchchecker.go
  toolkit/tools/pkgworker/pkgworker.go
  toolkit/tools/scheduler/buildagents/chrootagent.go
  toolkit/tools/scheduler/buildagents/definition.go
  toolkit/tools/scheduler/buildagents/testagent.go
  toolkit/tools/scheduler/scheduler.go
  toolkit/tools/scheduler/schedulerutils/buildlist.go
  toolkit/tools/scheduler/schedulerutils/buildworker.go
  toolkit/tools/scheduler/schedulerutils/depsolver.go
  toolkit/tools/scheduler/schedulerutils/graphbuildstate.go
  toolkit/tools/scheduler/schedulerutils/implicitprovides.go
  toolkit/tools/scheduler/schedulerutils/initializegraph.go
  toolkit/tools/scheduler/schedulerutils/preparerequest.go
  toolkit/tools/scheduler/schedulerutils/printresults.go
  toolkit/tools/specarchchecker/specarchchecker.go
  toolkit/tools/specreader/specreader.go
Labels: main

#6011 Fix CVE-2023-0286 by removing bundled openssl from reaper and adding openssl-devel as a BR
  SPECS/reaper/reaper.signatures.json
  SPECS/reaper/reaper.spec
Labels: main

#5994 Adding python module pyrpm spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/python-pyrpm/python-pyrpm.signatures.json
  SPECS/python-pyrpm/python-pyrpm.spec
  cgmanifest.json
Labels: main

#6020 docs: add `acl` as an install prerequisite
  toolkit/docs/building/prerequisites-mariner.md
  toolkit/docs/building/prerequisites-ubuntu.md
Labels: documentation, main

#6001 golang: bump golang 1.19.12 -> 1.20.7
  SPECS/golang/golang.signatures.json
  SPECS/golang/golang.spec
  SPECS/golang/permit-requests-with-invalid-header.patch
  SPECS/moby-cli/moby-cli.signatures.json
  SPECS/moby-cli/moby-cli.spec
  SPECS/moby-containerd/moby-containerd.signatures.json
  SPECS/moby-containerd/moby-containerd.spec
  SPECS/moby-engine/moby-engine.signatures.json
  SPECS/moby-engine/moby-engine.spec
  SPECS/moby-runc/moby-runc.signatures.json
  SPECS/moby-runc/moby-runc.spec
  cgmanifest.json
Labels: main

#6024 Apply patch CVE-2023-2650 in OpenSSL
  SPECS/openssl/CVE-2023-2650.patch
  SPECS/openssl/openssl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, main

#6027 Add patch to openssl for CVE-2023-3817
  SPECS/openssl/CVE-2023-3817.patch
  SPECS/openssl/openssl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, main

#6030 Nopatch kernel for CVE-2023-1206, CVE-2023-2860, CVE-2023-3567, CVE-2…
  SPECS/kernel/CVE-2023-1206.nopatch
  SPECS/kernel/CVE-2023-2860.nopatch
  SPECS/kernel/CVE-2023-32248.nopatch
  SPECS/kernel/CVE-2023-3567.nopatch
  SPECS/kernel/CVE-2023-3812.nopatch
  SPECS/kernel/CVE-2023-4004.nopatch
  SPECS/kernel/CVE-2023-4128.nopatch
  SPECS/kernel/CVE-2023-4132.nopatch
  SPECS/kernel/CVE-2023-4194.nopatch
Labels: security, main

#5699 ipset systemd unit file points to a non existent service file
  SPECS/ipset/ipset.service
  SPECS/ipset/ipset.signatures.json
  SPECS/ipset/ipset.spec
Labels: main

#5931 Add better backoff, semaphore to packer
  toolkit/tools/internal/retry/retry.go
  toolkit/tools/internal/retry/retry_test.go
  toolkit/tools/srpmpacker/srpmpacker.go
Labels: main

#5924 Make specreader tool run in parallel with graphpkgfetcher tool.
  toolkit/scripts/pkggen.mk
  toolkit/tools/internal/packlist/packagelist.go
  toolkit/tools/specreader/specreader.go
  toolkit/tools/srpmpacker/srpmpacker.go
Labels: main

#6012 nginx: add otel_ngx_module subpackage
  SPECS/nginx/nginx.signatures.json
  SPECS/nginx/nginx.spec
  cgmanifest.json
Labels: main

#5963 Xfsprogs update1
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/inih/inih.signatures.json
  SPECS/inih/inih.spec
  SPECS/xfsprogs/xfsprogs.signatures.json
  SPECS/xfsprogs/xfsprogs.spec
  cgmanifest.json
Labels: main

#6031 Patch rust for CVE-2023-3817
  SPECS/rust/rust.spec
Labels: security, main

#5993 Limit cascading rebuilds in the scheduler
  toolkit/docs/building/building.md
  toolkit/scripts/incremental_building.mk
  toolkit/scripts/pkggen.mk
  toolkit/scripts/utils.mk
  toolkit/tools/scheduler/scheduler.go
  toolkit/tools/scheduler/schedulerutils/buildworker.go
  toolkit/tools/scheduler/schedulerutils/graphbuildstate.go
  toolkit/tools/scheduler/schedulerutils/preparerequest.go
Labels: main

#5653 Conditionally load kernel-mshv variables in grub if they are installed.
  toolkit/resources/assets/grub2/grub.cfg
Labels: main

#6037 Revision bump bpftrace to rebuild with binutils 2.36.1
  SPECS/bpftrace/bpftrace.spec
Labels: 1.0-dev

#6036 Add patch to guava for CVE-2020-8908
  SPECS/guava/CVE-2020-8908.patch
  SPECS/guava/guava.spec
Labels: security, main

#5926 Add simple pre-cache downloader
  toolkit/Makefile
  toolkit/docs/building/building.md
  toolkit/scripts/incremental_building.mk
  toolkit/scripts/pkggen.mk
  toolkit/scripts/precache.mk
  toolkit/scripts/tools.mk
  toolkit/tools/internal/file/file.go
  toolkit/tools/precacher/precacher.go
Labels: main

#6040 Fix retry backoff sleep non-determinism
  toolkit/tools/internal/retry/retry.go
Labels: main

#6035 toolkit: containerized-build: add vim & git in the build env
  toolkit/scripts/containerized-build/resources/mariner.Dockerfile
Labels: main, DevEx

#6041 Patch etcd and bump fuzzing for CVE-2023-32082
  SPECS/etcd/CVE-2023-32082-v3.5.0.patch
  SPECS/etcd/CVE-2023-32082-v3.5.3.patch
  SPECS/etcd/CVE-2023-32082.patch
  SPECS/etcd/etcd-3.5.0.spec
  SPECS/etcd/etcd-3.5.1.spec
  SPECS/etcd/etcd-3.5.3.spec
  SPECS/etcd/etcd-3.5.4.spec
  SPECS/etcd/etcd-3.5.5.spec
  SPECS/etcd/etcd-3.5.6.spec
Labels: security, main

#6022 Adds package CharLS to SPECS-EXTENDED
  SPECS-EXTENDED/CharLS/CharLS.signatures.json
  SPECS-EXTENDED/CharLS/CharLS.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#6058 Skipping test node creation for duplicate nodes.
  toolkit/tools/grapher/grapher.go
Labels: main

#6017 Updated the PR check pipeline
  .pipelines/livepatching/DeployLivepatch.yml
  .pipelines/prchecks/PackageBuildPRCheck.yml
  .pipelines/templates/PackageBuild.yml
  .pipelines/templates/RawToolchainDownload.yml
  .pipelines/templates/ToolchainBuild.yml
  .pipelines/templates/ToolkitCheck.yml
  toolkit/scripts/pkggen.mk
  toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
Labels: main

#6074 Fixed image build issues with packages lacking tests.
  toolkit/tools/scheduler/schedulerutils/buildlist.go
Labels: security, main

#6044 toolkit: generate image_pkg_manifest.json with image builds
  toolkit/scripts/imggen.mk
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/imager/imager.go
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
  toolkit/tools/internal/safechroot/safechroot.go
  toolkit/tools/internal/tdnf/tdnf.go
Labels: main

#6081 CVE-2022-36648: QEMU fix
  SPECS/qemu/CVE-2022-36648.patch
  SPECS/qemu/qemu.spec
Labels: security, main

#6046 heimdal: address CVE-2022-42898
  SPECS/heimdal/0001-lib-krb5-krb5_pac_parse-mem-leak-if-pac_header_size-.patch
  SPECS/heimdal/0002-kdc-Check-generate_pac-return-code.patch
  SPECS/heimdal/0003-kdc-avoid-re-encoding-KDC-REQ-BODY.patch
  SPECS/heimdal/CVE-2022-42898.patch
  SPECS/heimdal/heimdal.spec
Labels: security, main

#6086 workflows: use curl with TLSv1_2 to fix cgmanifest check
  .github/workflows/validate-cg-manifest.sh
Labels: main

#6060 Add cfitsio package to SPECS-EXTENDED
  SPECS-EXTENDED/cfitsio/cfitsio-ldflags.patch
  SPECS-EXTENDED/cfitsio/cfitsio-noversioncheck.patch
  SPECS-EXTENDED/cfitsio/cfitsio-pkgconfig.patch
  SPECS-EXTENDED/cfitsio/cfitsio-remove-rpath.patch
  SPECS-EXTENDED/cfitsio/cfitsio.signatures.json
  SPECS-EXTENDED/cfitsio/cfitsio.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#6075 Add new EnableFIPS image configuration option
  toolkit/docs/formats/imageconfig.md
  toolkit/resources/assets/grub2/grub.cfg
  toolkit/tools/imageconfigvalidator/imageconfigvalidator.go
  toolkit/tools/imagegen/configuration/kernelcommandline.go
  toolkit/tools/imagegen/configuration/kernelcommandline_test.go
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/imager/imager.go
Labels: main

#6002 fix: CVE-2022-48579 in clamav
  SPECS/clamav/CVE-2022-48579.patch
  SPECS/clamav/clamav.spec
Labels: security, main

#6079 Bump telegraf release to rebuild with go 1.20.7
  SPECS/telegraf/telegraf.spec
Labels: security, main

#6085 Fix CVE-2023-38710, CVE-2023-38711, CVE-2023-38712 in libreswan
  SPECS/libreswan/CVE-2023-38710.patch
  SPECS/libreswan/CVE-2023-38711.patch
  SPECS/libreswan/CVE-2023-38712.patch
  SPECS/libreswan/libreswan.spec
Labels: security, main

#6083 Fix CVE-2021-32292 in json-c
  SPECS/json-c/CVE-2021-32292.patch
  SPECS/json-c/json-c.spec
Labels: security, main

#6004 BugFix: httpd.conf log location incorrect
  SPECS/httpd/httpd-fix-apache-layout-log-path.patch
  SPECS/httpd/httpd.spec
Labels: main

#6072 Nopatch kernel and hyperv-daemons for CVE-2023-3439 as mctp is not enabled in CBL-Mariner
  SPECS/hyperv-daemons/CVE-2023-3439.nopatch
  SPECS/kernel/CVE-2023-3439.nopatch
  toolkit/scripts/mariner-required-configs.json
Labels: security, main

#6095 Nopatch CVE-2023-2007 for kernel
  SPECS/kernel/CVE-2023-2007.nopatch
Labels: security, main

#6080 Remove dst file on failed network download
  toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
  toolkit/tools/internal/file/file.go
  toolkit/tools/internal/file/file_test.go
  toolkit/tools/internal/network/network.go
Labels: main

#6042 Make precache also use new backoff
  toolkit/tools/precacher/precacher.go
Labels: main

#6051 make cloud-init-output.log available to serial console
  SPECS/cloud-init/cloud-init.spec
Labels: main

#6089 qt5-qtsvg: rebuild with qt5-qtbase fix for CVE-2023-37369
  SPECS/qt5-qtsvg/qt5-qtsvg.spec
Labels: main

#5898 Upgrade nvidia-container-toolkit, nvidia-container-runtime and libnvidia-container
  SPECS/libnvidia-container/libnvidia-container.signatures.json
  SPECS/libnvidia-container/libnvidia-container.spec
  SPECS/nvidia-container-runtime/nvidia-container-runtime.signatures.json
  SPECS/nvidia-container-runtime/nvidia-container-runtime.spec
  SPECS/nvidia-container-toolkit/nvidia-container-toolkit.signatures.json
  SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec
  cgmanifest.json
Labels: main

#6112 Disabled CCache for quick rebuilds.
  toolkit/Makefile
  toolkit/scripts/incremental_building.mk
Labels: main

#6043 toolkit: containerized-build: honor $SPECS_DIR instead of hard-coding
  toolkit/scripts/containerized-build.mk
  toolkit/scripts/containerized-build/create_container_build.sh
Labels: main, DevEx

#6109 Patch CVE-2022-47022 in hwloc
  SPECS/hwloc/CVE-2022-47022.patch
  SPECS/hwloc/hwloc.spec
Labels: security, main

#6062 Add libgta package to SPECS-EXTENDED
  SPECS-EXTENDED/libgta/libgta.signatures.json
  SPECS-EXTENDED/libgta/libgta.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#6063 Add package liblerc to SPECS-EXTENDED
  SPECS-EXTENDED/liblerc/liblerc.signatures.json
  SPECS-EXTENDED/liblerc/liblerc.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#6066 Add package blosc to SPECS-EXTENDED
  SPECS-EXTENDED/blosc/blosc-gcc11.patch
  SPECS-EXTENDED/blosc/blosc.signatures.json
  SPECS-EXTENDED/blosc/blosc.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#6067 Add package uriparser to SPECS-EXTENDED
  SPECS-EXTENDED/uriparser/uriparser.signatures.json
  SPECS-EXTENDED/uriparser/uriparser.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#6065 Add package qt5-qtserialport to SPECS-EXTENDED
  SPECS-EXTENDED/qt5-qtserialport/qt5-qtserialport.signatures.json
  SPECS-EXTENDED/qt5-qtserialport/qt5-qtserialport.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#6064 Add package shapelib to SPECS-EXTENDED
  SPECS-EXTENDED/shapelib/CVE-2022-0699.patch
  SPECS-EXTENDED/shapelib/c75b9281a5b9452d92e1682bdfe6019a13ed819f.diff
  SPECS-EXTENDED/shapelib/rpmlint-errors.patch
  SPECS-EXTENDED/shapelib/shapelib.signatures.json
  SPECS-EXTENDED/shapelib/shapelib.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: security, main, specs-extended
