Repository microsoft/azurelinux, pull requests merged in 2023-12, with the labels that each got.

#6391 fix: Add grub2-mkconfig macros to initramfs postrans generation
  SPECS/initramfs/initramfs.spec
  toolkit/tools/internal/resources/assets/efi/grub/grub.cfg
Labels: main

#6889 timestamp: overwrite timestamp logs on different builds
  toolkit/tools/internal/timestamp/timestamp_mgr.go
  toolkit/tools/internal/timestamp/timestamp_test.go
Labels: main

#6880 Fix backtrace parsing in ocaml-ounit
  SPECS/ocaml-ounit/fix-backtrace-parser.patch
  SPECS/ocaml-ounit/ocaml-ounit.spec
Labels: ptest, main

#6888 Remove loglevel=3 for legacy boot flow
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/mariner-required-configs.json
Labels: 3.0

#6885 CodeQL Mariner toolkit
  .pipelines/CodeQL/CodeQL.yml
  CodeQL.yml
Labels: main

#6497 fix: Package both grub2 configuration dirs in grub2-configuration.rpm
  SPECS-SIGNED/grub2-efi-binary-signed/grub2-efi-binary-signed.spec
  SPECS/grub2/grub2.spec
Labels: main

#6887 Bump gevent version to 21.1.2, add fix for CVE-2020-22217
  SPECS/python-gevent/CVE-2020-22217.patch
  SPECS/python-gevent/CVE-2023-41419.patch
  SPECS/python-gevent/fix_test_hang_on_python_3_9_and_up.patch
  SPECS/python-gevent/python-gevent-makecheck.patch
  SPECS/python-gevent/python-gevent.signatures.json
  SPECS/python-gevent/python-gevent.spec
  cgmanifest.json
Labels: main

#6875 Fix test runner invocation in future
  SPECS/future/future.spec
Labels: ptest, main

#6877 Fix wget package tests by adding missing test dep
  SPECS/wget/wget.spec
Labels: ptest, main

#6879 Skip mypy tests in python-attrs
  SPECS/python-attrs/python-attrs.spec
Labels: ptest, main

#6813 Add support for squashfs image format
  toolkit/tools/roast/formats/squashfs.go
  toolkit/tools/roast/roast.go
Labels: main

#6908 pyparted: fix gpg keyboxd issue
  SPECS-EXTENDED/pyparted/pyparted.spec
Labels: 3.0

#6814 Switched to using Mariner's `python-junit-xml`.
  .pipelines/templates/PackageBuild.yml
  .pipelines/templates/PackageTestResultsAnalysis.yml
Labels: main

#6882 Kata-CC: UVM - Enable extended attributes for tmpfs
  SPECS/kernel-uvm-cvm/config
  SPECS/kernel-uvm-cvm/kernel-uvm-cvm.signatures.json
  SPECS/kernel-uvm-cvm/kernel-uvm-cvm.spec
  SPECS/kernel-uvm/config
  SPECS/kernel-uvm/kernel-uvm.signatures.json
  SPECS/kernel-uvm/kernel-uvm.spec
Labels: main

#6910 kata-containers: drop qemu-kvm-core dependency
  SPECS/kata-containers/kata-containers.spec
Labels: main

#6899 Disable faulty test_is_writable for python-distlib
  SPECS/python-distlib/python-distlib.spec
Labels: ptest, main

#6815 Added `cross-binutils` and `kernel-cross-headers` for AMD64.
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/binutils/binutils.spec
  SPECS/binutils/disable_gold_test.patch
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#6916 Updated `ca-certificates-base`.
  SPECS/ca-certificates/ca-certificates.signatures.json
  SPECS/ca-certificates/ca-certificates.spec
  SPECS/ca-certificates/cert2certdata.sh
  SPECS/ca-certificates/certdata.base.txt
  SPECS/prebuilt-ca-certificates-base/prebuilt-ca-certificates-base.spec
  SPECS/prebuilt-ca-certificates/prebuilt-ca-certificates.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#6939 add /etc/host.conf with multi on
  SPECS/filesystem/filesystem.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#6893 Nopatch kernel for CVE-2023-1193, CVE-2023-1194
  SPECS/kernel/CVE-2023-1193.nopatch
  SPECS/kernel/CVE-2023-1194.nopatch
Labels: security, main

#6947 Revert "Added `cross-binutils` and `kernel-cross-headers` for AMD64. …
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/binutils/binutils.spec
  SPECS/binutils/disable_gold_test.patch
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#6953 Upgrade Telegraf to 1.28.5
  SPECS/telegraf/CVE-2023-46129.patch
  SPECS/telegraf/telegraf.signatures.json
  SPECS/telegraf/telegraf.spec
  cgmanifest.json
Labels: main

#6872 [3.0] Update ARM configs to match 2.0
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 3.0

#6299 feat: Allow new builds of Mariner to generate grub.cfg using grub2-mkconfig using imageconfig EnableGrubMkconfig
  toolkit/docs/formats/imageconfig.md
  toolkit/imageconfigs/packagelists/grub2-mkconfig.json
  toolkit/resources/assets/efi/grub/grub.cfg
  toolkit/tools/imageconfigvalidator/imageconfigvalidator.go
  toolkit/tools/imagegen/configuration/systemconfig.go
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/imager/imager.go
Labels: Tools, Schema, 3.0

#6943 fix: Ensure grub2-mkconfig is called after the initramfs generation.
  SPECS/initramfs/initramfs.spec
Labels: 3.0

#6821 toolkit image build: Fix make error for config files outside imageconfig directory
  toolkit/scripts/get_config_deps.sh
  toolkit/scripts/imggen.mk
Labels: main

#6958 Aligned Go package names with other ones for `ccachemanager` and `azureblobstorage`.
  toolkit/tools/internal/azureblobstorage/azureblobstorage.go
  toolkit/tools/internal/ccachemanager/ccachemanager.go
  toolkit/tools/pkgworker/pkgworker.go
  toolkit/tools/scheduler/scheduler.go
Labels: Tools, main

#6983 containerized-rpmbuild: create sources_dir correctly
  toolkit/scripts/containerized-build/resources/setup_functions.sh
Labels: main

#6950 fix: add scriptlet to workaround rpm transaction limitation to update /media symlink to directory
  SPECS/filesystem/filesystem.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#6969 feat: change default hidepid setting to be opt-in
  toolkit/docs/formats/imageconfig.md
  toolkit/tools/imagegen/configuration/configuration_test.go
  toolkit/tools/imagegen/configuration/systemconfig.go
  toolkit/tools/imagegen/configuration/testdata/test_configuration.json
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/imager/imager.go
Labels: 3.0

#6982 [2.0] libgcrypt: upgrade to 1.10.3
  SPECS/libgcrypt/libgcrypt.signatures.json
  SPECS/libgcrypt/libgcrypt.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#6968 fix: preserve yum backend on tdnf package upgrade
  SPECS/tdnf/tdnf.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#6985 Image Customizer: Refresh initrd when partitions are customized
  toolkit/tools/pkg/imagecustomizerlib/customizepackages.go
  toolkit/tools/pkg/imagecustomizerlib/customizepartitions.go
  toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
Labels: main

#7006 Zwan/libpcap static
  SPECS/libpcap/libpcap.spec
Labels: main

#7002 update edk2
  SPECS/edk2/edk2.spec
  SPECS/edk2/improve-safety-of-DH.patch
Labels: main

#6972 clamav: Fix resetting of user and group on package update
  SPECS/clamav/clamav.spec
Labels: main

#7023 Remove 1.0 ISO link from README.md
  README.md
Labels: main

#6881 Image Customizer: Add support for kernel command-line
  toolkit/tools/imagecustomizer/docs/configuration.md
  toolkit/tools/imagecustomizerapi/config.go
  toolkit/tools/imagecustomizerapi/config_test.go
  toolkit/tools/imagecustomizerapi/kernelcommandline.go
  toolkit/tools/imagecustomizerapi/systemconfig.go
  toolkit/tools/imagecustomizerapi/systemconfig_test.go
  toolkit/tools/pkg/imagecustomizerlib/customizeboot.go
  toolkit/tools/pkg/imagecustomizerlib/customizepartitionsfilecopy.go
  toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
  toolkit/tools/pkg/imagecustomizerlib/imageutils.go
  toolkit/tools/pkg/imagecustomizerlib/testdata/commandline-config.yaml
  toolkit/tools/pkg/imagecustomizerlib/testdata/partitions-config.yaml
  toolkit/tools/pkg/imagecustomizerlib/typeConversion.go
Labels: main

#6995 Add quotatool package to Mariner
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/quotatool/09695c944947d804cbe3b5c7e2c854953984413e.patch
  SPECS/quotatool/58cdec3cdc6ae94864891a4e179ad68d4d136864.patch
  SPECS/quotatool/ad6944baaa73cf6230f9a2bef2399b31c2130547.patch
  SPECS/quotatool/af27842d1a6640d932407999ceec57f54a225a78.patch
  SPECS/quotatool/ca68628de86d18fda67ebcc4191c2b37891ed36e.patch
  SPECS/quotatool/quotatool.signatures.json
  SPECS/quotatool/quotatool.spec
  cgmanifest.json
Labels: main

#6833 [3.0] Add cpupower.service to kernel-tools
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/cpupower
  SPECS/kernel/cpupower.service
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 3.0

#7018 fix: Adding patch to netplan to force bring up devices with no IP addresses
  SPECS/netplan/force-bringup-interface-no-ipadd.patch
  SPECS/netplan/netplan.spec
Labels: main

#7038 libpng: update to v1.6.40
  SPECS/libpng/libpng-fix-pngtest-random-failures.patch
  SPECS/libpng/libpng.signatures.json
  SPECS/libpng/libpng.spec
  cgmanifest.json
Labels: 3.0

#7034 Image Customizer: Fix ext4 formatting
  toolkit/tools/imagegen/diskutils/diskutils.go
  toolkit/tools/imager/imager.go
  toolkit/tools/internal/safemount/safemount_test.go
  toolkit/tools/pkg/imagecustomizerlib/imageutils.go
Labels: main

#7052 Address hyperv-daemon CVE-2023-6111 and CVE-2023-5972
  SPECS/hyperv-daemons/CVE-2023-5972.nopatch
  SPECS/hyperv-daemons/CVE-2023-6111.nopatch
Labels: security, main

#7042 Upgrade libnftnl to 1.2.6
  SPECS/libnftnl/libnftnl.signatures.json
  SPECS/libnftnl/libnftnl.spec
  cgmanifest.json
Labels: 3.0

#7044 Enable user-based event tracing
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/scripts/mariner-required-configs.json
Labels: 3.0

#7046 Upgrade usbutils to 017
  SPECS/usbutils/usbutils.signatures.json
  SPECS/usbutils/usbutils.spec
  cgmanifest.json
Labels: 3.0

#7068 Sudo ldap netgroup_query bug fix patch
  SPECS/sudo/disable-newgroup-query-when-netgroup-base-is-not-set.patch
  SPECS/sudo/sudo.spec
Labels: main

#7012 move docbook2X package from Extended to Core
  SPECS/docbook2X/docbook2X.signatures.json
  SPECS/docbook2X/docbook2X.spec
Labels: main

#7015 Move perl-IPC-Run from Extended to Core
  SPECS/perl-IPC-Run/perl-IPC-Run.signatures.json
  SPECS/perl-IPC-Run/perl-IPC-Run.spec
Labels: main

#7025 Move perl-IO-String from extended to core
  SPECS/perl-IO-String/perl-IO-String.signatures.json
  SPECS/perl-IO-String/perl-IO-String.spec
Labels: main

#7028 Move package perl-Devel-CheckBin from extended to core
  SPECS/perl-Devel-CheckBin/perl-Devel-CheckBin.signatures.json
  SPECS/perl-Devel-CheckBin/perl-Devel-CheckBin.spec
Labels: main

#7027 Move package perl-Sub-Name from Extended to core
  SPECS/perl-Sub-Name/perl-Sub-Name.signatures.json
  SPECS/perl-Sub-Name/perl-Sub-Name.spec
Labels: main

#7026 Move package perl-Class-Accessor from extended to core
  SPECS/perl-Class-Accessor/perl-Class-Accessor.signatures.json
  SPECS/perl-Class-Accessor/perl-Class-Accessor.spec
Labels: main

#7016 Add package perl-Time-Duration to mariner
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/perl-Time-Duration/perl-Time-Duration.signatures.json
  SPECS/perl-Time-Duration/perl-Time-Duration.spec
  cgmanifest.json
Labels: main

#7029 Fix CVE-2020-8694, CVE-2020-8695 and CVE-2020-12912
  SPECS/moby-cli/moby-cli.signatures.json
  SPECS/moby-cli/moby-cli.spec
  SPECS/moby-containerd/moby-containerd.signatures.json
  SPECS/moby-containerd/moby-containerd.spec
  SPECS/moby-engine/moby-engine.signatures.json
  SPECS/moby-engine/moby-engine.spec
  cgmanifest.json
Labels: security, main

#7054 Update libXrandr to v1.5.3
  SPECS/libXrandr/libXrandr.signatures.json
  SPECS/libXrandr/libXrandr.spec
  cgmanifest.json
Labels: 3.0

#7055 Update libXrender to v0.9.11
  SPECS/libXrender/libXrender.signatures.json
  SPECS/libXrender/libXrender.spec
  cgmanifest.json
Labels: 3.0

#7063 ci: update kata codeowner packages
  .github/CODEOWNERS
Labels: main

#7070 Sudo ldap netgroup_query bug fix patch
  SPECS/sudo/disable-newgroup-query-when-netgroup-base-is-not-set.patch
  SPECS/sudo/sudo.spec
Labels: 3.0

#7053 Add Kata meta-package
  .github/workflows/validate-cg-manifest.sh
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/kata-packages-uvm/kata-packages-uvm.spec
Labels: main

#7013 Image Customizer: Support for partition extraction - raw, raw-zstd
  toolkit/tools/imagecustomizer/docs/cli.md
  toolkit/tools/imagecustomizer/docs/configuration.md
  toolkit/tools/imagecustomizer/main.go
  toolkit/tools/imagegen/diskutils/diskutils.go
  toolkit/tools/pkg/imagecustomizerlib/extractpartitions.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
Labels: main

#7074 Update libXt to v1.3.0
  SPECS/libXt/0001-xt-Work-around-a-compiler-issue-with-gcc-10.patch
  SPECS/libXt/libXt.signatures.json
  SPECS/libXt/libXt.spec
  cgmanifest.json
Labels: 3.0

#7075 Update libXtst to v1.2.4
  SPECS/libXtst/libXtst.signatures.json
  SPECS/libXtst/libXtst.spec
  cgmanifest.json
Labels: 3.0

#7051 Cherry-pick 5.15 kernel changes to 6.6
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/scripts/mariner-required-configs.json
Labels: 3.0

#7017 Add moreutils package to mariner
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/moreutils/0001-dont-overwrite-docbooxsl-path.patch
  SPECS/moreutils/0002-Use-pclose-instead-of-fclose.patch
  SPECS/moreutils/moreutils.signatures.json
  SPECS/moreutils/moreutils.spec
  cgmanifest.json
Labels: main

#7085 applying disable-newgroup-query-when-netgroup-base-is-not-set.patch
  SPECS/sudo/sudo.spec
Labels: main

#7088 fix: use autosetup macro in sudo package
  SPECS/sudo/sudo.spec
Labels: 3.0

#7069 abseil-cpp: upgrade 20220623.0 -> 20230802.1
  SPECS/abseil-cpp/abseil-cpp.signatures.json
  SPECS/abseil-cpp/abseil-cpp.spec
  cgmanifest.json
Labels: 3.0

#7071 atftp: upgrade 0.7.5 -> 0.8.0
  SPECS/atftp/atftp.signatures.json
  SPECS/atftp/atftp.spec
  cgmanifest.json
Labels: 3.0

#7072 bcc: upgrade 0.28.0 -> 0.29.1
  SPECS/bcc/bcc.signatures.json
  SPECS/bcc/bcc.spec
  cgmanifest.json
Labels: 3.0

#7066 upgrade xfsprogs and strace
  SPECS/strace/strace.signatures.json
  SPECS/strace/strace.spec
  SPECS/strace/testfix-netlink-list-memberships.patch
  SPECS/xfsprogs/xfsprogs.signatures.json
  SPECS/xfsprogs/xfsprogs.spec
  cgmanifest.json
Labels: 3.0

#7104 Patch CVE-2023-49083 in python-cryptography
  SPECS/python-cryptography/CVE-2023-49083.patch
  SPECS/python-cryptography/python-cryptography.spec
  SPECS/pytorch/pytorch.spec
Labels: main

#7079 Update libxml++ to v5.0.3
  SPECS/libxml++/libxml++.signatures.json
  SPECS/libxml++/libxml++.spec
  cgmanifest.json
Labels: 3.0

#7086 Upgrade kernel-mos to 5.15.143.1
  SPECS-SIGNED/kernel-mos-signed/kernel-mos-signed.spec
  SPECS/kernel-mos/config
  SPECS/kernel-mos/kernel-mos.signatures.json
  SPECS/kernel-mos/kernel-mos.spec
  cgmanifest.json
Labels: main

#6809 imagecustomizer: initial dm-verity enablement by nbd.
  toolkit/tools/imagecustomizer/docs/configuration.md
  toolkit/tools/imagecustomizerapi/idtype.go
  toolkit/tools/imagecustomizerapi/idtype_test.go
  toolkit/tools/imagecustomizerapi/systemconfig.go
  toolkit/tools/imagecustomizerapi/verity.go
  toolkit/tools/imagecustomizerapi/verity_partition.go
  toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
  toolkit/tools/pkg/imagecustomizerlib/customizeverity.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
  toolkit/tools/pkg/imagecustomizerlib/partitionutils.go
Labels: main

#7080 Update libxfce4util to v4.19.2
  SPECS/libxfce4util/libxfce4util.signatures.json
  SPECS/libxfce4util/libxfce4util.spec
  cgmanifest.json
Labels: 3.0

#7067 Upgrade libaio from 0.3.112 to 0.3.113
  SPECS/libaio/fix-gcc11-bug-and-parity-with-upstream.patch
  SPECS/libaio/libaio.signatures.json
  SPECS/libaio/libaio.spec
  cgmanifest.json
Labels: 3.0

#7077 Update libxshmfence to v1.3.2
  SPECS/libxshmfence/libxshmfence.signatures.json
  SPECS/libxshmfence/libxshmfence.spec
  cgmanifest.json
Labels: 3.0

#7076 Update libXau to v1.0.11
  SPECS/libXau/libXau.signatures.json
  SPECS/libXau/libXau.spec
  cgmanifest.json
Labels: 3.0

#7091 ci: add codeowners for toolkit folders
  .github/CODEOWNERS
Labels: main

#7097 Patch CVE-2023-45866 in bluez
  SPECS/bluez/CVE-2023-45866.patch
  SPECS/bluez/bluez.spec
Labels: security, main

#7096 Move package catch1 from extended to core
  SPECS/catch1/catch1-sigstksz.patch
  SPECS/catch1/catch1.signatures.json
  SPECS/catch1/catch1.spec
Labels: main

#7098 Move package leatherman from extended to core
  SPECS/leatherman/leatherman-1.12.4-shared_nowide.patch
  SPECS/leatherman/leatherman-gcc11.patch
  SPECS/leatherman/leatherman.signatures.json
  SPECS/leatherman/leatherman.spec
  SPECS/leatherman/system-catch.patch
Labels: main

#7100 Move rubygem-thor from extended to core
  SPECS/rubygem-thor/rubygem-thor.signatures.json
  SPECS/rubygem-thor/rubygem-thor.spec
Labels: main

#7106 Move ruby-augeas from Extended to Core
  SPECS/ruby-augeas/ruby-augeas.signatures.json
  SPECS/ruby-augeas/ruby-augeas.spec
Labels: main

#7107 Move rubygem-deep_merge from Extended to Core
  SPECS/rubygem-deep_merge/rubygem-deep_merge.signatures.json
  SPECS/rubygem-deep_merge/rubygem-deep_merge.spec
Labels: main

#7103 Move rubygem-hocon from Extended to Core
  SPECS/rubygem-hocon/rubygem-hocon.signatures.json
  SPECS/rubygem-hocon/rubygem-hocon.spec
Labels: main

#7099 Move cpp-hocon from extended to core
  SPECS/cpp-hocon/cpp-hocon.signatures.json
  SPECS/cpp-hocon/cpp-hocon.spec
Labels: main

#7108 Move rubygem-puppet-resource_api from Extended to Core
  SPECS/rubygem-puppet-resource_api/rubygem-puppet-resource_api.signatures.json
  SPECS/rubygem-puppet-resource_api/rubygem-puppet-resource_api.spec
Labels: main

#7114 Remove patches no longer needed in 6.6
  SPECS/kernel/perf_bpf_test_add_nonnull_argument.patch
  SPECS/kernel/pthread_stack_min_int_cast.patch
Labels: 3.0

#7083 Update liburing to v2.5
  SPECS/liburing/0001-spec-bump-version-to-2.0.patch
  SPECS/liburing/0002-spec-add-explicit-build-dependency-on-make.patch
  SPECS/liburing/0003-test-get-rid-of-x86_64-isms-in-the-test-code.patch
  SPECS/liburing/0004-examples-ucontext-cp.c-cope-with-variable-SIGSTKSZ.patch
  SPECS/liburing/liburing.signatures.json
  SPECS/liburing/liburing.spec
  cgmanifest.json
Labels: 3.0

#7056 Add Backport for installonlypkgs to tdnf for Mariner 2.0
  SPECS/tdnf/tdnf-add-installonlypkgs-config.patch
  SPECS/tdnf/tdnf-installonlypkgs.patch
  SPECS/tdnf/tdnf.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#6819 Set OOMScoreAdjust to -999 for containerd
  SPECS/moby-containerd/containerd.service
  SPECS/moby-containerd/moby-containerd.signatures.json
  SPECS/moby-containerd/moby-containerd.spec
Labels: main

#7121 Set OOMScoreAdjust to -999 for containerd-cc
  SPECS/moby-containerd-cc/containerd.service
  SPECS/moby-containerd-cc/moby-containerd-cc.signatures.json
  SPECS/moby-containerd-cc/moby-containerd-cc.spec
Labels: main

#7116 ci: update codeowners for kata packages and toolkit
  .github/CODEOWNERS
Labels: 3.0

#7065 fix: upgrade cloud-init to v23.4.1
  SPECS/cloud-init/cloud-init.signatures.json
  SPECS/cloud-init/cloud-init.spec
  SPECS/cloud-init/overrideDatasourceDetection.patch
  cgmanifest.json
Labels: main

#7118 Patch CVE-2023-46218 mysql
  SPECS/mysql/CVE-2023-46218.patch
  SPECS/mysql/mysql.spec
Labels: security, main

#7120 Update libunistring to v1.1
  SPECS/libunistring/libunistring.signatures.json
  SPECS/libunistring/libunistring.spec
  cgmanifest.json
Labels: 3.0

#7124 ansible: update to v2.14.12 to fix CVE-2023-5764
  SPECS/ansible/ansible.signatures.json
  SPECS/ansible/ansible.spec
  cgmanifest.json
Labels: main

#7125 openssh: patch CVE-2023-51384 and CVE-2023-51385
  SPECS/openssh/CVE-2023-51384.patch
  SPECS/openssh/CVE-2023-51385.patch
  SPECS/openssh/openssh.spec
Labels: main

#7134 dbus: Update to v1.15.6 to fix CVE-2023-34969
  SPECS/dbus/dbus.signatures.json
  SPECS/dbus/dbus.spec
  cgmanifest.json
Labels: main

#7138 postgresql: update to v14.10 to fix CVE-2023-5868, CVE-2023-5869 and CVE-2023-5870
  SPECS/postgresql/postgresql.signatures.json
  SPECS/postgresql/postgresql.spec
  cgmanifest.json
Labels: main
