Repository microsoft/azurelinux, pull requests merged in 2023-11, with the labels that each got.

#6644 go-downloader: abort immediately on 404 errors
  toolkit/scripts/toolchain.mk
  toolkit/tools/downloader/downloader.go
Labels: main

#6628 Patch CVE-2023-45322 in libxml2
  SPECS/libxml2/CVE-2023-45322.patch
  SPECS/libxml2/libxml2.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#6642 Replace the sample username and password with user replaceable values
  toolkit/docs/quick_start/quickstart.md
  toolkit/resources/assets/meta-user-data/user-data
Labels: main

#6654 Patch snappy to fix build with RTTI enabled
  SPECS/snappy/build-with-rtti.patch
  SPECS/snappy/snappy.spec
Labels: main

#6650 containerized-rpmbuild: Add extra_packages option
  toolkit/docs/building/developer-tools.md
  toolkit/scripts/containerized-build.mk
  toolkit/scripts/containerized-build/create_container_build.sh
  toolkit/scripts/containerized-build/resources/mariner.Dockerfile
Labels: main

#6661 systemd: Add missing Requires on zstd-libs
  SPECS/systemd/systemd.spec
Labels: main

#6660 Switch ccache to use azure managed identity.
  toolkit/tools/internal/azureblobstorage/azureblobstorage.go
  toolkit/tools/internal/ccachemanager/ccachemanager.go
Labels: main

#6665 Add kata-containers-cc patch to retain uvm dependencies
  SPECS/kata-containers-cc/kata-containers-cc.spec
  SPECS/kata-containers-cc/keep-uvm-rootfs-dependencies.patch
Labels: main

#6668 No password: Use `*` instead of `!`.
  toolkit/tools/internal/userutils/userutils.go
  toolkit/tools/internal/userutils/userutils_test.go
Labels: main

#6666 upgrade mysql to 8.0.34
  SPECS/mysql/mysql.signatures.json
  SPECS/mysql/mysql.spec
  cgmanifest.json
Labels: main

#6675 Clarify that passwords are not permitted for production use in meta user data configuration file
  toolkit/resources/assets/meta-user-data/user-data
Labels: main

#6651 Nopatch kernel CVE-2023-2430, CVE-2023-3338, CVE-2023-39191, CVE-2023-42752 ...
  SPECS/kernel/CVE-2023-2430.nopatch
  SPECS/kernel/CVE-2023-3338.nopatch
  SPECS/kernel/CVE-2023-39191.nopatch
  SPECS/kernel/CVE-2023-42752.nopatch
Labels: security, main

#6677 Clarify login instructions
  toolkit/docs/quick_start/quickstart.md
Labels: main

#6682 Use embedded binary resources for grub templates.
  toolkit/docs/formats/imageconfig.md
  toolkit/resources/imageconfigs/iso_initrd.json
  toolkit/resources/imageconfigs/iso_initrd_arm64.json
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/imager/imager.go
  toolkit/tools/internal/file/file.go
  toolkit/tools/internal/resources/assets/efi/grub/grub.cfg
  toolkit/tools/internal/resources/assets/efi/grub/grubEncrypt.cfg
  toolkit/tools/internal/resources/assets/grub2/grub
  toolkit/tools/internal/resources/assets/grub2/grub.cfg
  toolkit/tools/internal/resources/assets/grub2/grubenv
  toolkit/tools/internal/resources/resources.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
  toolkit/tools/pkg/imagecustomizerlib/main_test.go
Labels: main

#6446 Add tdnf remove cache script and run it for marketplace images
  toolkit/imageconfigs/additionalconfigs/configure-systemd-networkd.sh
  toolkit/imageconfigs/marketplace-gen1-fips.json
  toolkit/imageconfigs/marketplace-gen1.json
  toolkit/imageconfigs/marketplace-gen2-aarch64.json
  toolkit/imageconfigs/marketplace-gen2-fips.json
  toolkit/imageconfigs/marketplace-gen2.json
  toolkit/imageconfigs/postinstallscripts/remove-tdnf-cache.sh
Labels: main

#6685 Image Customizer: Move partition utils into their own file.
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
  toolkit/tools/pkg/imagecustomizerlib/partitionutils.go
Labels: main

#6603 [3.0] Upgrade kernel to 6.1.58.1
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/hyperv-daemons/hyperv-daemons.signatures.json
  SPECS/hyperv-daemons/hyperv-daemons.spec
  SPECS/kernel-headers/kernel-headers.signatures.json
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  SPECS/strace/strace.signatures.json
  SPECS/strace/strace.spec
  SPECS/strace/testfix-landlock-brackets.patch
  SPECS/systemd/systemd.spec
  SPECS/systemd/update-cifs-for-kernel-headers-6.1.patch
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 3.0

#6687 Add retry workaround when Package Installation fail.
  .pipelines/templates/PackageTestResultsAnalysis.yml
Labels: main

#6690 fix wrong rights for toolkit/imageconfigs/additionalconfigs/configure…
  toolkit/imageconfigs/additionalconfigs/configure-systemd-networkd.sh
Labels: main

#6691 fix wrong rights for toolkit/imageconfigs/postinstallscripts/remove-tdnf-cache.sh
  toolkit/imageconfigs/postinstallscripts/remove-tdnf-cache.sh
Labels: main

#6692 Add debug to PR check to debug intermittent issue
  .pipelines/prchecks/PackageBuildPRCheck.yml
Labels: main, DevEx

#6659 containerized-build: Add option to keep container
  toolkit/docs/building/developer-tools.md
  toolkit/scripts/containerized-build.mk
  toolkit/scripts/containerized-build/create_container_build.sh
Labels: main

#6564 Upgrade kata-containers-cc to 0.6.2
  SPECS/kata-containers-cc/0001-tardev-snapshotter-enable-feature-impl_trait_in_asso.patch
  SPECS/kata-containers-cc/drop-mut-for-variables-that-are-not-mutated.patch
  SPECS/kata-containers-cc/kata-containers-cc.signatures.json
  SPECS/kata-containers-cc/kata-containers-cc.spec
  cgmanifest.json
Labels: main

#5798 Support N+1 goal nodes for scheduler
  toolkit/Makefile
  toolkit/docs/building/building.md
  toolkit/scripts/pkggen.mk
  toolkit/scripts/toolchain.mk
  toolkit/scripts/utils.mk
  toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
  toolkit/tools/internal/pkggraph/pkggraph.go
  toolkit/tools/internal/pkggraph/pkggraph_test.go
  toolkit/tools/scheduler/scheduler.go
  toolkit/tools/scheduler/schedulerutils/initializegraph.go
Labels: Tools, ptest, main

#6696 Added CredScan exception for doc and test sample secrets.
  .config/CredScanSuppressions.json
Labels: main

#6313 Update multus to v4.0.2
  SPECS/multus/multus.signatures.json
  SPECS/multus/multus.spec
  cgmanifest.json
Labels: main

#6706 Using separate buffer per analyzed spec in `rpmssnapshot.go`.
  toolkit/tools/pkg/rpmssnapshot/rpmssnapshot.go
Labels: main

#6639 Cosmetic change with chrony removed references to NetworkManager
  SPECS/chrony/chrony.spec
Labels: main

#6707 Sparse disk creation bug fix.
  toolkit/tools/imagegen/diskutils/diskutils.go
Labels: main

#6708 Fix safechoot unmount ordering.
  toolkit/tools/internal/safechroot/safechroot.go
Labels: main

#6658 Upgrade Blobfuse2 to 2.1.1
  SPECS/blobfuse2/blobfuse2.signatures.json
  SPECS/blobfuse2/blobfuse2.spec
  cgmanifest.json
Labels: main

#6711 Switch ccache to using compiler content instead of its modified time.
  SPECS/mariner-rpm-macros/macros
  SPECS/mariner-rpm-macros/mariner-rpm-macros.signatures.json
  SPECS/mariner-rpm-macros/mariner-rpm-macros.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/tools/pkgworker/pkgworker.go
Labels: main

#6733 Toolkit: Improvements for UpdateFstab and CreateSparseDisk
  toolkit/tools/imagegen/diskutils/diskutils.go
  toolkit/tools/imagegen/installutils/installutils.go
Labels: main

#6721 toolkit: gomod: bump dependencies to address CVEs
  toolkit/tools/go.mod
  toolkit/tools/go.sum
Labels: security, main

#6735 Toolkit: Move `ConfigureDiskBootloader` function.
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/imager/imager.go
Labels: main

#6746 toolkit: fix user instructions on toolchain build error
  toolkit/scripts/toolchain/toolchain_verify.sh
Labels: main

#6741 toolkit: gomod: upgrade gonum 0.11.0 -> 0.14.0
  toolkit/tools/go.mod
  toolkit/tools/go.sum
  toolkit/tools/scheduler/schedulerutils/depsolver.go
Labels: main

#6714 Add kernel-mos with AMDGPU drivers
  SPECS-SIGNED/kernel-mos-signed/kernel-mos-signed.spec
  SPECS-SIGNED/kernel-mos-signed/sha512hmac-openssl.sh
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/kernel-mos/cbl-mariner-ca-20211013.pem
  SPECS/kernel-mos/config
  SPECS/kernel-mos/kernel-mos.signatures.json
  SPECS/kernel-mos/kernel-mos.spec
  SPECS/kernel-mos/nvme_multipath_default_false.patch
  SPECS/kernel-mos/pthread_stack_min_int_cast.patch
  SPECS/kernel-mos/sha512hmac-openssl.sh
  cgmanifest.json
Labels: main

#6762 Toolkit: Add retry to safemount.Close().
  toolkit/tools/internal/safemount/main_test.go
  toolkit/tools/internal/safemount/safemount.go
  toolkit/tools/internal/safemount/safemount_test.go
Labels: main

#6722 kubernetes: fix version subcommand for components
  SPECS/kubernetes/kubernetes.spec
Labels: main

#6765 update to cloud-init 23.3.3 and make cloud-init network fallback configuration work
  SPECS/cloud-init/cloud-init.signatures.json
  SPECS/cloud-init/cloud-init.spec
  SPECS/cloud-init/make_fallback_network_config_work.patch
  cgmanifest.json
Labels: 3.0

#6761 3.0 toolchain: fix breaks in ksh, boost, pyyaml, gdb, openssh
  SPECS/PyYAML/PyYAML.signatures.json
  SPECS/PyYAML/PyYAML.spec
  SPECS/boost/CVE-2018-25032.patch
  SPECS/boost/CVE-2023-45853.patch
  SPECS/boost/boost.signatures.json
  SPECS/boost/boost.spec
  SPECS/cyrus-sasl-bootstrap/cyrus-sasl-bootstrap.spec
  SPECS/cyrus-sasl/cyrus-sasl.spec
  SPECS/gdb/gdb.signatures.json
  SPECS/gdb/gdb.spec
  SPECS/ksh/ksh-1.0.0-beta.1-fix-build.patch
  SPECS/ksh/ksh.spec
  SPECS/openssh/openssh.signatures.json
  SPECS/openssh/openssh.spec
  cgmanifest.json
Labels: 3.0

#6766 fix tmux crashing bug
  SPECS/ncurses/ncurses.signatures.json
  SPECS/ncurses/ncurses.spec
  SPECS/tmux/manual-patch-to-fix-crash-due-to-change-to-ncurses.patch
  SPECS/tmux/tmux.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#6773 kernel: nopatch CVE-2023-5178
  SPECS/kernel/CVE-2023-5178.nopatch
Labels: security, main

#6777 Upgrade valgrind to 3.22.0
  SPECS/valgrind/valgrind.signatures.json
  SPECS/valgrind/valgrind.spec
  cgmanifest.json
Labels: main

#6737 Fixed signature checking for local sources to break the build on a mismatch.
  toolkit/tools/srpmpacker/srpmpacker.go
Labels: main

#6772 busybox: Enable SELinux features.
  SPECS/busybox/busybox-static.config
  SPECS/busybox/busybox.signatures.json
  SPECS/busybox/busybox.spec
  SPECS/busybox/selinux-copy-file.patch
  SPECS/busybox/selinux-cp-a.patch
Labels: main

#6763 update to systemd 254
  SPECS/systemd-bootstrap/50-security-hardening.conf
  SPECS/systemd-bootstrap/99-dhcp-en.network
  SPECS/systemd-bootstrap/99-mariner.preset
  SPECS/systemd-bootstrap/CVE-2022-3821.patch
  SPECS/systemd-bootstrap/CVE-2022-4415.patch
  SPECS/systemd-bootstrap/CVE-2022-45873.patch
  SPECS/systemd-bootstrap/add-fsync-sysusers-passwd.patch
  SPECS/systemd-bootstrap/backport-helper-util-macros.patch
  SPECS/systemd-bootstrap/fix-journald-audit-logging.patch
  SPECS/systemd-bootstrap/gpt-auto-devno-not-determined.patch
  SPECS/systemd-bootstrap/systemd-bootstrap.signatures.json
  SPECS/systemd-bootstrap/systemd-bootstrap.spec
  SPECS/systemd-bootstrap/systemd.cfg
  SPECS/systemd-bootstrap/update-cifs-for-kernel-headers-6.1.patch
  SPECS/systemd/95-disable-systemd-oomd.preset
  SPECS/systemd/mariner-2-do-not-default-zstd-journal-files-for-backwards-compatibility.patch
  SPECS/systemd/serve-stale-0001-resolved-added-serve-stale-feature-implementation-of.patch
  SPECS/systemd/serve-stale-0002-resolved-Initialize-until_valid-while-storing-negati.patch
  SPECS/systemd/systemd.signatures.json
  SPECS/systemd/systemd.spec
  cgmanifest.json
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 3.0

#6796 Fix opensc CVE-2023-4535
  SPECS/opensc/CVE-2023-4535.patch
  SPECS/opensc/opensc.spec
Labels: main

#6669 Added patch for CVE-2023-46136 to python-werkzeug
  SPECS/python-werkzeug/0001-enable-tests-in-rpm-env.patch
  SPECS/python-werkzeug/0002-disable-stat-test.patch
  SPECS/python-werkzeug/CVE-2023-46136.patch
  SPECS/python-werkzeug/python-werkzeug.signatures.json
  SPECS/python-werkzeug/python-werkzeug.spec
  cgmanifest.json
Labels: security

#6787 Patch package frr to fix CVE-2023-47234 and CVE-2023-47235
  SPECS/frr/CVE-2023-47234.patch
  SPECS/frr/CVE-2023-47235.patch
  SPECS/frr/frr.spec
Labels: main

#6807 add kernel-mos to ccache config
  toolkit/resources/manifests/package/ccache-configuration.json
Labels: main

#6732 Print more details on image fetch failures
  toolkit/tools/imagepkgfetcher/imagepkgfetcher.go
Labels: Tools, main

#6374 Print blocked node summary
  toolkit/tools/scheduler/schedulerutils/depsolver.go
Labels: Tools, main

#6640 Pass toolchain archive to make in pipeline template
  .pipelines/templates/PackageBuild.yml
Labels: Tools, main

#6805 3.0 buildrpms: fix systemd, systemd-bootstrap, gnu-efi build breaks
  SPECS/gnu-efi/gnu-efi.signatures.json
  SPECS/gnu-efi/gnu-efi.spec
  SPECS/systemd-bootstrap/systemd-bootstrap.spec
  SPECS/systemd/systemd.spec
  cgmanifest.json
Labels: 3.0

#6768 Print logs on build/test failure
  toolkit/tools/scheduler/schedulerutils/buildworker.go
Labels: main

#6811 [2.0] Update kernel, kernel-hci, kernel-azure BuildRequires to include cpio
  SPECS-SIGNED/kernel-azure-signed/kernel-azure-signed.spec
  SPECS-SIGNED/kernel-hci-signed/kernel-hci-signed.spec
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-azure/kernel-azure.spec
  SPECS/kernel-hci/kernel-hci.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#6816 Update kernel-mshv, kernel-uvm, kernel-uvm-cvm BuildRequires to inclu…
  SPECS/kernel-mshv/kernel-mshv.spec
  SPECS/kernel-uvm-cvm/kernel-uvm-cvm.spec
  SPECS/kernel-uvm/kernel-uvm.spec
Labels: main

#6370 Add ExtractNameFromRPMPath() to rpm.go
  toolkit/tools/internal/rpm/rpm.go
  toolkit/tools/internal/rpm/rpm_test.go
Labels: Tools, main

#6830 containerized-build: Add downloader to list of tools to build
  toolkit/scripts/containerized-build/create_container_build.sh
Labels: main

#6831 msft-golang: upgrade 1.20.11
  SPECS/msft-golang/msft-golang.signatures.json
  SPECS/msft-golang/msft-golang.spec
  cgmanifest.json
Labels: main

#6404 Add linuxptp v3.1.1 with High-Availability patches
  SPECS-EXTENDED/linuxptp/linuxptp.signatures.json
  SPECS/linuxptp/clknetsim-phc2sys.patch
  SPECS/linuxptp/enable-ha.patch
  SPECS/linuxptp/linuxptp-zerolength.patch
  SPECS/linuxptp/linuxptp.signatures.json
  SPECS/linuxptp/linuxptp.spec
  SPECS/linuxptp/phc2sys.service
  SPECS/linuxptp/ptp4l.conf
  SPECS/linuxptp/ptp4l.service
  SPECS/linuxptp/timemaster.conf
  SPECS/linuxptp/timemaster.service
  cgmanifest.json
Labels: main

#6826 Move package glog from Extended to Core
  SPECS/glog/glog.signatures.json
  SPECS/glog/glog.spec
Labels: main

#6841 3.0 toolchain: upgrade 9 specs
  SPECS/gnupg2/gnupg2.signatures.json
  SPECS/gnupg2/gnupg2.spec
  SPECS/itstool/itstool.signatures.json
  SPECS/itstool/itstool.spec
  SPECS/kmod/kmod.signatures.json
  SPECS/kmod/kmod.spec
  SPECS/krb5/CVE-2023-36054.patch
  SPECS/krb5/krb5.signatures.json
  SPECS/krb5/krb5.spec
  SPECS/libassuan/libassuan.signatures.json
  SPECS/libassuan/libassuan.spec
  SPECS/libcap-ng/libcap-ng.signatures.json
  SPECS/libcap-ng/libcap-ng.spec
  SPECS/libgcrypt/libgcrypt.signatures.json
  SPECS/libgcrypt/libgcrypt.spec
  SPECS/libksba/libksba.signatures.json
  SPECS/libksba/libksba.spec
  SPECS/libmpc/libmpc.signatures.json
  SPECS/libmpc/libmpc.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 3.0

#6832 3.0 toolchain: upgrade bash, cpio, chkconfig
  SPECS/bash/bash.signatures.json
  SPECS/bash/bash.spec
  SPECS/chkconfig/chkconfig.signatures.json
  SPECS/chkconfig/chkconfig.spec
  SPECS/cpio/CVE-2021-38185.patch
  SPECS/cpio/cpio.signatures.json
  SPECS/cpio/cpio.spec
  SPECS/cpio/cpio_extern_nocommon.patch
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 3.0

#6834 Nopatch kernel CVE-2023-39198
  SPECS/kernel/CVE-2023-39198.nopatch
Labels: security, main

#6829 Enable CONFIG_ARM_SMMU and CONFIG_ARM_SMMU_V3 in aarch64.
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/mariner-required-configs.json
Labels: main

#6846 Enable CONFIG_BPF_LSM
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/mariner-required-configs.json
Labels: main

#6812 Added package `python3-junit-xml`.
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/python-junit-xml/python-junit-xml.signatures.json
  SPECS/python-junit-xml/python-junit-xml.spec
  cgmanifest.json
Labels: main

#6368 Add additional functions to pkggraph.go
  toolkit/tools/internal/pkggraph/pkggraph.go
  toolkit/tools/internal/pkggraph/pkggraph_test.go
Labels: Tools, main

#6862 Joslobo/update docs from 2.0
  .github/ISSUE_TEMPLATE/questions-feedback.md
  README.md
Labels: main

#6747 Image Customizer: Implement fallback partition customization.
  toolkit/tools/imagecustomizer/docs/configuration.md
  toolkit/tools/imagecustomizerapi/boottype.go
  toolkit/tools/imagecustomizerapi/boottype_test.go
  toolkit/tools/imagecustomizerapi/config.go
  toolkit/tools/imagecustomizerapi/config_test.go
  toolkit/tools/imagecustomizerapi/disk.go
  toolkit/tools/imagecustomizerapi/disk_test.go
  toolkit/tools/imagecustomizerapi/filesystemtype.go
  toolkit/tools/imagecustomizerapi/mountidentifier.go
  toolkit/tools/imagecustomizerapi/partition.go
  toolkit/tools/imagecustomizerapi/partition_test.go
  toolkit/tools/imagecustomizerapi/partitionflag.go
  toolkit/tools/imagecustomizerapi/partitionsetting.go
  toolkit/tools/imagecustomizerapi/partitionsetting_test.go
  toolkit/tools/imagecustomizerapi/partitiontabletype.go
  toolkit/tools/imagecustomizerapi/systemconfig.go
  toolkit/tools/imagecustomizerapi/systemconfig_test.go
  toolkit/tools/internal/sliceutils/sliceutils.go
  toolkit/tools/pkg/imagecustomizerlib/customizepartitions.go
  toolkit/tools/pkg/imagecustomizerlib/customizepartitionsfilecopy.go
  toolkit/tools/pkg/imagecustomizerlib/imageConnection.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
  toolkit/tools/pkg/imagecustomizerlib/imageutils.go
  toolkit/tools/pkg/imagecustomizerlib/partitionutils.go
  toolkit/tools/pkg/imagecustomizerlib/testdata/legacyboot-config.yaml
  toolkit/tools/pkg/imagecustomizerlib/testdata/partitions-config.yaml
  toolkit/tools/pkg/imagecustomizerlib/typeConversion.go
Labels: main

#6853 Adding CUSE module for rshim interface support
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/mariner-required-configs.json
Labels: main

#6053 Print chroot-tools progress
  toolkit/tools/pkggen/worker/create_worker_chroot.sh
Labels: Tools, main

#6784 Enable SELinux labelling for targzip rootFS image formats
  toolkit/docs/formats/imageconfig.md
  toolkit/tools/imageconfigvalidator/imageconfigvalidator.go
  toolkit/tools/imagegen/configuration/kernelcommandline.go
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/imager/imager.go
  toolkit/tools/roast/formats/targzip.go
Labels: main
