Repository microsoft/azurelinux, pull requests merged in 2023-05, with the labels that each got.

#5424 Avoid JIT'd Perl in dracut to avoid SELinux errors
  SPECS/dracut/dracut.spec
  SPECS/dracut/fix-functions-Avoid-calling-grep-with-PCRE-P.patch
Labels: main

#5381 Add moby-containerd-cc
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/kata-containers-cc/containerd-for-cc-override.conf
  SPECS/kata-containers-cc/kata-containers-cc.signatures.json
  SPECS/kata-containers-cc/kata-containers-cc.spec
  SPECS/moby-containerd-cc/containerd.service
  SPECS/moby-containerd-cc/containerd.toml
  SPECS/moby-containerd-cc/moby-containerd-cc.signatures.json
  SPECS/moby-containerd-cc/moby-containerd-cc.spec
  cgmanifest.json
Labels: main

#5420 bcc: bump version to 0.27.0
  SPECS/bcc/bcc.signatures.json
  SPECS/bcc/bcc.spec
  cgmanifest.json
Labels: main

#5423 Update ncurses to version 6.4-20230408 to fix CVE-2023-29491
  SPECS/ncurses/ncurses.signatures.json
  SPECS/ncurses/ncurses.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#5393 Update ncurses to fix CVE-2023-29491
  SPECS/ncurses/ncurses.signatures.json
  SPECS/ncurses/ncurses.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5432 Fix: backport patch for CVE-2021-33391 for tidy
  SPECS/tidy/CVE-2021-33391.patch
  SPECS/tidy/tidy.spec
Labels: main

#5447 Nopatch kernel for CVE-CVE-2023-2162, CVE-2023-2166, CVE-2023-2177, CVE-2023-2194, CVE-2023-28327, CVE-2023-28328
  SPECS/kernel/CVE-2023-2162.nopatch
  SPECS/kernel/CVE-2023-2166.nopatch
  SPECS/kernel/CVE-2023-2177.nopatch
  SPECS/kernel/CVE-2023-2194.nopatch
  SPECS/kernel/CVE-2023-28327.nopatch
  SPECS/kernel/CVE-2023-28328.nopatch
Labels: security, main

#5443 openvswitch: Add patch for CVE-2023-1668
  SPECS/openvswitch/CVE-2023-1668.patch
  SPECS/openvswitch/openvswitch.spec
Labels: main

#5441 Patch fluent-bit for CVE-2021-46878 and CVE-2021-46879
  SPECS/fluent-bit/CVE-2021-46878.patch
  SPECS/fluent-bit/CVE-2021-46879.patch
  SPECS/fluent-bit/fluent-bit.spec
Labels: 1.0-dev

#5429 CODEOWNERS: Add owners for core packages
  .github/CODEOWNERS
Labels: main

#5430 Correct FRR installation macro to resolve installation errors.
  SPECS-EXTENDED/frr/frr.spec
Labels: main

#5289 Introduce hvloader package
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/acpica-tools/COPYING
  SPECS/acpica-tools/OPT_LDFLAGS.patch
  SPECS/acpica-tools/README.Fedora
  SPECS/acpica-tools/acpibin.1
  SPECS/acpica-tools/acpica-tools.signatures.json
  SPECS/acpica-tools/acpica-tools.spec
  SPECS/acpica-tools/acpidump.1
  SPECS/acpica-tools/acpiexamples.1
  SPECS/acpica-tools/acpiexec.1
  SPECS/acpica-tools/acpihelp.1
  SPECS/acpica-tools/acpinames.1
  SPECS/acpica-tools/acpisrc.1
  SPECS/acpica-tools/acpixtract.1
  SPECS/acpica-tools/arm7hl.patch
  SPECS/acpica-tools/aslcodegen.patch
  SPECS/acpica-tools/badcode.asl.result
  SPECS/acpica-tools/big-endian-v2.patch
  SPECS/acpica-tools/big-endian.patch
  SPECS/acpica-tools/converterSample.asl.result
  SPECS/acpica-tools/cve-2017-13693.patch
  SPECS/acpica-tools/cve-2017-13694.patch
  SPECS/acpica-tools/cve-2017-13695.patch
  SPECS/acpica-tools/f23-harden.patch
  SPECS/acpica-tools/facp.patch
  SPECS/acpica-tools/grammar.asl.result
  SPECS/acpica-tools/iasl.1
  SPECS/acpica-tools/int-format.patch
  SPECS/acpica-tools/mips-be-fix.patch
  SPECS/acpica-tools/ppc64le.patch
  SPECS/acpica-tools/ptr-cast.patch
  SPECS/acpica-tools/run-misc-tests.sh
  SPECS/acpica-tools/simple-64bit.patch
  SPECS/acpica-tools/str-trunc-warn.patch
  SPECS/acpica-tools/template.patch
  SPECS/acpica-tools/unaligned.patch
  SPECS/hvloader/hvloader.signatures.json
  SPECS/hvloader/hvloader.spec
  SPECS/hvloader/target-x86.txt
  SPECS/patchutils/patchutils.signatures.json
  SPECS/patchutils/patchutils.spec
  cgmanifest.json
Labels: main

#5453 Upgrade redis to 6.2.12 to fix CVE-2023-28856
  SPECS/redis/redis.signatures.json
  SPECS/redis/redis.spec
  cgmanifest.json
Labels: main

#5434 Install the bzImage for kernel-uvm
  SPECS/kernel-uvm/kernel-uvm.spec
Labels: main

#5456 Upgrade frr to 8.5.1 and promote to core specs
  SPECS-EXTENDED/frr/frr.fc
  SPECS-EXTENDED/frr/frr.if
  SPECS-EXTENDED/frr/frr.signatures.json
  SPECS-EXTENDED/frr/frr.te
  SPECS/frr/0000-remove-babeld-and-ldpd.patch
  SPECS/frr/0001-enable-openssl.patch
  SPECS/frr/0002-disable-eigrp-crypto.patch
  SPECS/frr/0003-fips-mode.patch
  SPECS/frr/0004-remove-grpc-test.patch
  SPECS/frr/frr-sysusers.conf
  SPECS/frr/frr-tmpfiles.conf
  SPECS/frr/frr.signatures.json
  SPECS/frr/frr.spec
  cgmanifest.json
Labels: main

#5458 Revert "[AUTOPATCHER-CORE] Patched shadow-utils to address CVE-2023-2…
  SPECS/shadow-utils/CVE-2023-29383.patch
  SPECS/shadow-utils/shadow-utils.spec
Labels: main

#5418 Enable nvme multipath
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5463 nodejs: use ninja to speed up build
  SPECS/nodejs/nodejs.spec
  SPECS/nodejs/nodejs18.spec
Labels: main

#5464 Nopatch kernel for CVE-2023-2006, CVE-2023-2019
  SPECS/kernel/CVE-2023-2006.nopatch
  SPECS/kernel/CVE-2023-2019.nopatch
Labels: security, main

#5473 Cblmargh/moby engine upgrade to 20.10.24 main
  SPECS/moby-engine/moby-engine.signatures.json
  SPECS/moby-engine/moby-engine.spec
  cgmanifest.json
Labels: main

#5448 Upgrade ruby-time to v0.2.2 and ruby-uri to v0.11.1 to resolve CVE-20…
  SPECS/ruby/ruby.signatures.json
  SPECS/ruby/ruby.spec
  cgmanifest.json
Labels: security, main

#5471 Promote containernetworking-plugins from extended to core
  SPECS/containernetworking-plugins/containernetworking-plugins.signatures.json
  SPECS/containernetworking-plugins/containernetworking-plugins.spec
Labels: main

#5431 Allow PackageRepo field to have configurable GPG
  toolkit/docs/formats/imageconfig.md
  toolkit/tools/imagegen/configuration/configuration_test.go
  toolkit/tools/imagegen/configuration/packagerepo.go
  toolkit/tools/imagegen/configuration/packagerepo_test.go
  toolkit/tools/imagegen/configuration/testdata/test_configuration.json
Labels: documentation, Tools, Schema, main

#5480 Revert "Promote containernetworking-plugins from extended to core"
  SPECS-EXTENDED/containernetworking-plugins/containernetworking-plugins.signatures.json
  SPECS-EXTENDED/containernetworking-plugins/containernetworking-plugins.spec
Labels: main

#5482 Add toolchainrpms to protected directory list for docker-based builds
  toolkit/tools/internal/buildpipeline/buildpipeline.go
Labels: 1.0-dev

#5479 Add toolchainrpms to protected directory list for docker-based builds
  toolkit/tools/internal/buildpipeline/buildpipeline.go
Labels: main

#5484 Renamed patch in nmap to correct format to resolve CVE-2018-25032
  SPECS/nmap/CVE-2018-25032.patch
  SPECS/nmap/nmap.spec
Labels: 1.0-dev

#5477 nlopt: add package version 2.7.1
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/nlopt/0001-CMake-Fix-guile-detection-in-Fedora.patch
  SPECS/nlopt/nlopt-2.6.2-kill_rpath.patch
  SPECS/nlopt/nlopt.signatures.json
  SPECS/nlopt/nlopt.spec
  cgmanifest.json
Labels: main

#5483 Update __Python macro to point to existing interpreter
  SPECS/mariner-rpm-macros/macros.python-srpm
  SPECS/mariner-rpm-macros/mariner-rpm-macros.signatures.json
  SPECS/mariner-rpm-macros/mariner-rpm-macros.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5490 Upgrade kata-containers-cc to 0.4.1
  SPECS/kata-containers-cc/kata-containers-cc.signatures.json
  SPECS/kata-containers-cc/kata-containers-cc.spec
  cgmanifest.json
Labels: main

#5470 Upgrade kubevirt to v0.59.0
  SPECS/kubevirt/Allocate-2-cpu-for-the-emulator-thread.patch
  SPECS/kubevirt/Cleanup-housekeeping-cgroup-on-vm-del.patch
  SPECS/kubevirt/disks-images-provider.yaml
  SPECS/kubevirt/fgetxattr-for-relabel.patch
  SPECS/kubevirt/kubevirt.signatures.json
  SPECS/kubevirt/kubevirt.spec
  cgmanifest.json
Labels: main

#5485 grubby: use dedicated installkernel package
  SPECS/grubby/grubby.signatures.json
  SPECS/grubby/grubby.spec
  SPECS/grubby/installkernel-bls
  SPECS/grubby/installkernel.in
Labels: main

#5499 Revert mstflint Kernel Driver Changes
  SPECS-SIGNED/kernel-mstflint-signed/kernel-mstflint-signed.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/mstflint/mstflint.spec
  toolkit/scripts/check_entangled_specs.py
Labels: main

#5497 Add mstflint Driver to the kernel-hci
  SPECS-SIGNED/kernel-hci-signed/kernel-hci-signed.spec
  SPECS/kernel-hci/0027-mstflint-This-driver-enables-under-the-secure-boot.patch
  SPECS/kernel-hci/config
  SPECS/kernel-hci/kernel-hci.signatures.json
  SPECS/kernel-hci/kernel-hci.spec
Labels: main

#5501 Add patch for CVE-2023-0795 in libtiff
  SPECS/libtiff/CVE-2023-0795.patch
  SPECS/libtiff/CVE-2023-0796.nopatch
  SPECS/libtiff/CVE-2023-0797.nopatch
  SPECS/libtiff/CVE-2023-0798.nopatch
  SPECS/libtiff/CVE-2023-0799.nopatch
  SPECS/libtiff/libtiff.spec
Labels: 1.0-dev

#5487 Enable CONFIG_EDAC_SKX
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5504 Revert "Enable nvme multipath (#5418)"
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5507 libtiff: patch CVE-2023-0795
  SPECS/libtiff/CVE-2023-0795.patch
  SPECS/libtiff/libtiff.spec
Labels: security, main

#5488 Patch tdnf to Retry on Failed Connection During curl Calls
  SPECS/tdnf/tdnf-increase-timeout.patch
  SPECS/tdnf/tdnf.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 1.0-dev

#5517 libtiff: add patch for CVE-2023-0801
  SPECS/libtiff/CVE-2023-0800.nopatch
  SPECS/libtiff/CVE-2023-0801.nopatch
  SPECS/libtiff/CVE-2023-0801.patch
  SPECS/libtiff/CVE-2023-0802.nopatch
  SPECS/libtiff/CVE-2023-0803.nopatch
  SPECS/libtiff/CVE-2023-0804.nopatch
  SPECS/libtiff/libtiff.spec
Labels: security, main

#5519 vim: upgrade to 9.0.1562 to address CVE-2023-2609 & CVE-2023-2610
  SPECS/vim/vim.signatures.json
  SPECS/vim/vim.spec
  cgmanifest.json
Labels: security, 1.0-dev

#5520 Fixed architecture check during spec parsing.
  SPECS-EXTENDED/toolbox/toolbox-Don-t-use-Go-s-semantic-import-versioning.patch
  SPECS-EXTENDED/toolbox/toolbox-Make-the-build-flags-match-Fedora-s-gobuild-for-PPC64.patch
  SPECS-EXTENDED/toolbox/toolbox-Make-the-build-flags-match-Fedora-s-gobuild.patch
  SPECS-EXTENDED/toolbox/toolbox.signatures.json
  SPECS-EXTENDED/toolbox/toolbox.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
  toolkit/tools/internal/rpm/rpm.go
  toolkit/tools/internal/rpm/testdata/supported_unsupported_architectures.spec
  toolkit/tools/internal/rpm/testdata/unsupported_architectures.spec
Labels: main

#5491 qt5: Upgrade to version 5.15.9
  SPECS/qt5-qtbase/10-qt5-check-opengl2.sh
  SPECS/qt5-qtbase/CVE-2022-27404.patch
  SPECS/qt5-qtbase/CVE-2022-27405.nopatch
  SPECS/qt5-qtbase/CVE-2022-27406.nopatch
  SPECS/qt5-qtbase/CVE-2022-37434.patch
  SPECS/qt5-qtbase/CVE-2023-24607.patch
  SPECS/qt5-qtbase/qt5-qtbase.signatures.json
  SPECS/qt5-qtbase/qt5-qtbase.spec
  SPECS/qt5-qtbase/qtbase-everywhere-src-5.11.1-python3.patch
  SPECS/qt5-qtbase/qtbase-everywhere-src-5.14.2-no_relocatable.patch
  SPECS/qt5-qtbase/qtbase-everywhere-src-5.15.2-libglvnd.patch
  SPECS/qt5-qtbase/qtbase-everywhere-src-5.15.6-private_api_warning.patch
  SPECS/qt5-qtbase/qtbase-hidpi_scale_at_192.patch
  SPECS/qt5-qtbase/qtbase-opensource-src-5.3.2-QTBUG-35459.patch
  SPECS/qt5-qtdeclarative/0001-Remove-unused-QPointer-QQuickPointerMask.patch
  SPECS/qt5-qtdeclarative/0002-QQmlDelegateModel-Refresh-the-view-when-a-column-is-.patch
  SPECS/qt5-qtdeclarative/0003-Fix-TapHandler-so-that-it-actually-registers-a-tap.patch
  SPECS/qt5-qtdeclarative/0004-Revert-Fix-TapHandler-so-that-it-actually-registers-.patch
  SPECS/qt5-qtdeclarative/0005-Make-sure-QQuickWidget-and-its-offscreen-window-s-sc.patch
  SPECS/qt5-qtdeclarative/0006-QQuickItem-Guard-against-cycles-in-nextPrevItemInTab.patch
  SPECS/qt5-qtdeclarative/0007-Don-t-convert-QByteArray-in-startDrag.patch
  SPECS/qt5-qtdeclarative/0008-Fix-build-after-95290f66b806a307b8da1f72f8fc2c698019.patch
  SPECS/qt5-qtdeclarative/0009-Implement-accessibility-for-QQuickWidget.patch
  SPECS/qt5-qtdeclarative/0010-Send-ObjectShow-event-for-visible-components-after-i.patch
  SPECS/qt5-qtdeclarative/0011-QQuickItem-avoid-emitting-signals-during-destruction.patch
  SPECS/qt5-qtdeclarative/0012-a11y-track-item-enabled-state.patch
  SPECS/qt5-qtdeclarative/0013-Make-QaccessibleQuickWidget-private-API.patch
  SPECS/qt5-qtdeclarative/0014-Qml-Don-t-crash-when-as-casting-to-type-with-errors.patch
  SPECS/qt5-qtdeclarative/0015-Fix-missing-glyphs-when-using-NativeRendering.patch
  SPECS/qt5-qtdeclarative/0016-Revert-Fix-missing-glyphs-when-using-NativeRendering.patch
  SPECS/qt5-qtdeclarative/0017-QQmlImportDatabase-Make-sure-the-newly-added-import-.patch
  SPECS/qt5-qtdeclarative/0018-QQuickState-when-handle-QJSValue-properties-correctl.patch
  SPECS/qt5-qtdeclarative/0019-Models-Avoid-crashes-when-deleting-cache-items.patch
  SPECS/qt5-qtdeclarative/qt-QTBUG-111935-fix-V4-jit.patch
  SPECS/qt5-qtdeclarative/qt5-qtdeclarative-gcc11.patch
  SPECS/qt5-qtdeclarative/qt5-qtdeclarative.signatures.json
  SPECS/qt5-qtdeclarative/qt5-qtdeclarative.spec
  SPECS/qt5-qtdeclarative/qtdeclarative-5.15.0-FixMaxXMaxYExtent.patch
  SPECS/qt5-qtdeclarative/qv4global_p-multilib.h
  SPECS/qt5-qtsvg/CVE-2023-32573.patch
  SPECS/qt5-qtsvg/qt5-qtsvg.signatures.json
  SPECS/qt5-qtsvg/qt5-qtsvg.spec
  SPECS/qt5-qttools/qt5-qttools.signatures.json
  SPECS/qt5-qttools/qt5-qttools.spec
  SPECS/qt5-qttools/qttools-opensource-src-5.13.2-runqttools-with-qt5-suffix.patch
  SPECS/qt5-qttools/qttools-opensource-src-5.5.0-qmake-qt5.patch
  SPECS/qt5-qttools/qttools-opensource-src-5.7-add-libatomic.patch
  SPECS/qt5-rpm-macros/qt5-rpm-macros.spec
  cgmanifest.json
Labels: main

#5527 Bump gd for libtiff update
  SPECS/gd/gd.spec
Labels: main

#5496 Fix CVE-2023-27477 by patching cranelift vulnerability that is exposed in rust
  SPECS/rust/CVE-2023-27477.patch
  SPECS/rust/rust.spec
Labels: security, main

#5502 Tobiasb/cis chronyd use chrony user
  SPECS/chrony/chrony.spec
Labels: main

#5532 Revert "nodejs: use ninja to speed up build (#5463)"
  SPECS/nodejs/nodejs.spec
  SPECS/nodejs/nodejs18.spec
Labels: main

#5521 Restored executable permissions for `squid` scripts.
  SPECS-EXTENDED/squid/perl-requires-squid.sh
  SPECS-EXTENDED/squid/squid.nm
Labels: main

#5539 Updated PR checks
  .github/workflows/check-clean-stage.yml
  .github/workflows/check-entangled-specs.yml
  .github/workflows/check-license-map.yml
  .github/workflows/check-livepatches.yml
  .github/workflows/check-manifests.yml
  .github/workflows/check-package-cgmanifest.yml
  .github/workflows/check-spec.yml
  .github/workflows/check-static-glibc.yml
  .github/workflows/go-test-coverage.yml
  .github/workflows/lint-specs.yml
  .github/workflows/quickstart_1.0.yml
  .github/workflows/quickstart_2.0.yml
Labels: main

#5505 Add rootfs partition name in gen2 market place image
  toolkit/imageconfigs/marketplace-gen2-aarch64.json
  toolkit/imageconfigs/marketplace-gen2.json
Labels: main

#5542 Fix python-pbr tests by pinning sphinx version used
  SPECS/python-pbr/python-pbr.spec
  SPECS/python-pbr/test-pin-sphinx.patch
Labels: main

#5541 Fix ocaml-ppxlib tests failure due to ocaml-sexplib0-0.15.0 changes
  SPECS/ocaml-ppxlib/ocaml-ppxlib.spec
  SPECS/ocaml-ppxlib/test-fix-sexplib0-0.15.0.patch
Labels: main

#5545 Remove zstd from package test exclusion list
  toolkit/resources/manifests/package/macros.override
Labels: ptest, main

#5551 Fix dnf-plugins-core tests by using unittests runner
  SPECS/dnf-plugins-core/dnf-plugins-core.spec
Labels: ptest, main

#5513 Upgrade cert-manager to v1.11.2
  SPECS/cert-manager/CVE-2023-25165.patch
  SPECS/cert-manager/cert-manager.signatures.json
  SPECS/cert-manager/cert-manager.spec
  cgmanifest.json
Labels: main

#5528 Remove umask handling from bash.spec and change it in filesystem.spec
  SPECS/bash/bash.spec
  SPECS/filesystem/filesystem.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5478 Upgrade lua to 5.4.4 to fix CVE-2021-44964
  SPECS/lua/CVE-2021-43519.patch
  SPECS/lua/CVE-2021-44647.patch
  SPECS/lua/CVE-2021-45985.patch
  SPECS/lua/lua-5.4.3-bug3.patch
  SPECS/lua/lua.signatures.json
  SPECS/lua/lua.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/toolchain-remote-wget-list
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
Labels: main

#5548 Pin version of hypothesis used in numpy tests to avoid test breakage
  SPECS/numpy/numpy.spec
Labels: ptest, main

#5506 Remove x86 console params from ARM-specific grub config
  toolkit/resources/assets/isomaker/iso_root_arch-dependent_files/arm64/isolinux/isolinux.cfg
Labels: main

#5564 Patch frr with CVE-2023-31490
  SPECS/frr/CVE-2023-31490.patch
  SPECS/frr/frr.spec
Labels: main

#5498 Fix CVE-2023-29194 by upgrading vitess to 16.0.2
  SPECS/vitess/0001-Add-context-to-k8s-calls.patch
  SPECS/vitess/0001-Fix-for-newer-azure-storage-blob.patch
  SPECS/vitess/0001-Fix-unit-test-error.patch
  SPECS/vitess/update-go-module-version.patch
  SPECS/vitess/vitess.signatures.json
  SPECS/vitess/vitess.spec
  cgmanifest.json
Labels: main

#5563 Update CVE-2022-37601.patch to fix multiple occurrences
  SPECS/reaper/CVE-2022-37601.patch
  SPECS/reaper/reaper.spec
Labels: main

#5573 fix: add setuid bit to necessary binaries so regular users can run them
  SPECS/shadow-utils/shadow-utils.spec
  SPECS/util-linux/util-linux.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5535 make RPM cache flat, improve tdnf arg formatting
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
  toolkit/tools/internal/packagerepo/repomanager/repomanager.go
  toolkit/tools/internal/packagerepo/repomanager/rpmrepomanager/rpmrepomanager.go
Labels: Tools, main

#5549 codeowners: Add maintainers for openssl engines
  .github/CODEOWNERS
Labels: main

#5577 Use static resource management and build using the host OpenSSL for kata-containers-cc
  SPECS/kata-containers-cc/kata-containers-cc.spec
Labels: main

#5578 Fix ISO mount retry race condition
  toolkit/resources/imageconfigs/additionalfiles/iso_initrd/root/runliveinstaller
Labels: main

#5574 Fix tobiasb/CVE-2023-28155 by patch request module in reaper
  SPECS/reaper/CVE-2023-28155.patch
  SPECS/reaper/reaper.spec
Labels: main

#5562 Fix CVE-2023-28155 by patching request module in nodejs
  SPECS/nodejs/CVE-2023-28155.patch
  SPECS/nodejs/nodejs.spec
Labels: 1.0-dev

#5290 [kernel-mshv]: Support new lxhvloader
  SPECS/kernel-mshv/0001-Implement-dom0-kernel-patch-for-loader-as-of-0524.patch
  SPECS/kernel-mshv/kernel-mshv.spec
Labels: main

#5570 Unified `*_LIST` arguments usage to accept spec names
  toolkit/docs/building/building.md
  toolkit/scripts/pkggen.mk
  toolkit/tools/depsearch/depsearch.go
  toolkit/tools/graphPreprocessor/graphPreprocessor.go
  toolkit/tools/graphanalytics/graphanalytics.go
  toolkit/tools/grapher/grapher.go
  toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
  toolkit/tools/imagepkgfetcher/imagepkgfetcher.go
  toolkit/tools/internal/pkggraph/pkggraph.go
  toolkit/tools/internal/pkggraph/pkggraph_test.go
  toolkit/tools/internal/sliceutils/sliceutils.go
  toolkit/tools/internal/sliceutils/sliceutils_test.go
  toolkit/tools/scheduler/scheduler.go
  toolkit/tools/scheduler/schedulerutils/buildlist.go
  toolkit/tools/scheduler/schedulerutils/buildworker.go
  toolkit/tools/scheduler/schedulerutils/initializegraph.go
  toolkit/tools/scheduler/schedulerutils/preparerequest.go
  toolkit/tools/srpmpacker/srpmpacker.go
Labels: main

#5540 Updated `kf5` packages to version 5.106.0.
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/calamares/calamares-partition-1.1.2-qt5gui-5.15.patch
  SPECS/calamares/calamares-partition-1.1.2.patch
  SPECS/calamares/calamares.spec
  SPECS/extra-cmake-modules/extra-cmake-modules.signatures.json
  SPECS/extra-cmake-modules/extra-cmake-modules.spec
  SPECS/kf5-kconfig/kf5-kconfig.signatures.json
  SPECS/kf5-kconfig/kf5-kconfig.spec
  SPECS/kf5-kcoreaddons/kf5-kcoreaddons.signatures.json
  SPECS/kf5-kcoreaddons/kf5-kcoreaddons.spec
  SPECS/kf5-ki18n/kf5-ki18n.signatures.json
  SPECS/kf5-ki18n/kf5-ki18n.spec
  SPECS/kf5-kwidgetsaddons/kf5-kwidgetsaddons.signatures.json
  SPECS/kf5-kwidgetsaddons/kf5-kwidgetsaddons.spec
  SPECS/kf5/kf5.signatures.json
  SPECS/kf5/kf5.spec
  SPECS/kf5/macros.kf5
  SPECS/kpmcore/kpmcore.signatures.json
  SPECS/kpmcore/kpmcore.spec
  SPECS/polkit-qt-1/polkit-qt-1.signatures.json
  SPECS/polkit-qt-1/polkit-qt-1.spec
  cgmanifest.json
Labels: main

#5586 Patch sysstat for CVE-2023-33204
  SPECS/sysstat/CVE-2023-33204.patch
  SPECS/sysstat/sysstat.spec
Labels: main

#5588 Patch libtiff for CVE-2023-2731
  SPECS/libtiff/CVE-2023-2731.patch
  SPECS/libtiff/libtiff.spec
Labels: main

#5589 Patch libtiff for CVE-2023-2731
  SPECS/libtiff/CVE-2023-2731.patch
  SPECS/libtiff/libtiff.spec
Labels: 1.0-dev

#5592 Revert "Updated `kf5` packages to version 5.106.0."
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/calamares/calamares-partition-1.1.2-qt5gui-5.15.patch
  SPECS/calamares/calamares-partition-1.1.2.patch
  SPECS/calamares/calamares.spec
  SPECS/extra-cmake-modules/extra-cmake-modules.signatures.json
  SPECS/extra-cmake-modules/extra-cmake-modules.spec
  SPECS/kf5-kconfig/kf5-kconfig.signatures.json
  SPECS/kf5-kconfig/kf5-kconfig.spec
  SPECS/kf5-kcoreaddons/kf5-kcoreaddons.signatures.json
  SPECS/kf5-kcoreaddons/kf5-kcoreaddons.spec
  SPECS/kf5-ki18n/kf5-ki18n.signatures.json
  SPECS/kf5-ki18n/kf5-ki18n.spec
  SPECS/kf5-kwidgetsaddons/kf5-kwidgetsaddons.signatures.json
  SPECS/kf5-kwidgetsaddons/kf5-kwidgetsaddons.spec
  SPECS/kf5/kf5.signatures.json
  SPECS/kf5/kf5.spec
  SPECS/kf5/macros.kf5
  SPECS/kpmcore/kpmcore.signatures.json
  SPECS/kpmcore/kpmcore.spec
  SPECS/polkit-qt-1/polkit-qt-1.signatures.json
  SPECS/polkit-qt-1/polkit-qt-1.spec
  cgmanifest.json
Labels: main

#5591 Revert "qt5: Upgrade to version 5.15.9"
  SPECS/qt5-qtbase/10-qt5-check-opengl2.sh
  SPECS/qt5-qtbase/CVE-2022-27404.patch
  SPECS/qt5-qtbase/CVE-2022-27405.nopatch
  SPECS/qt5-qtbase/CVE-2022-27406.nopatch
  SPECS/qt5-qtbase/CVE-2022-37434.patch
  SPECS/qt5-qtbase/CVE-2023-24607.patch
  SPECS/qt5-qtbase/qt5-qtbase.signatures.json
  SPECS/qt5-qtbase/qt5-qtbase.spec
  SPECS/qt5-qtbase/qtbase-everywhere-src-5.11.1-python3.patch
  SPECS/qt5-qtbase/qtbase-everywhere-src-5.14.2-no_relocatable.patch
  SPECS/qt5-qtbase/qtbase-everywhere-src-5.15.2-libglvnd.patch
  SPECS/qt5-qtbase/qtbase-everywhere-src-5.15.6-private_api_warning.patch
  SPECS/qt5-qtbase/qtbase-hidpi_scale_at_192.patch
  SPECS/qt5-qtbase/qtbase-opensource-src-5.3.2-QTBUG-35459.patch
  SPECS/qt5-qtdeclarative/0001-Remove-unused-QPointer-QQuickPointerMask.patch
  SPECS/qt5-qtdeclarative/0002-QQmlDelegateModel-Refresh-the-view-when-a-column-is-.patch
  SPECS/qt5-qtdeclarative/0003-Fix-TapHandler-so-that-it-actually-registers-a-tap.patch
  SPECS/qt5-qtdeclarative/0004-Revert-Fix-TapHandler-so-that-it-actually-registers-.patch
  SPECS/qt5-qtdeclarative/0005-Make-sure-QQuickWidget-and-its-offscreen-window-s-sc.patch
  SPECS/qt5-qtdeclarative/0006-QQuickItem-Guard-against-cycles-in-nextPrevItemInTab.patch
  SPECS/qt5-qtdeclarative/0007-Don-t-convert-QByteArray-in-startDrag.patch
  SPECS/qt5-qtdeclarative/0008-Fix-build-after-95290f66b806a307b8da1f72f8fc2c698019.patch
  SPECS/qt5-qtdeclarative/0009-Implement-accessibility-for-QQuickWidget.patch
  SPECS/qt5-qtdeclarative/0010-Send-ObjectShow-event-for-visible-components-after-i.patch
  SPECS/qt5-qtdeclarative/0011-QQuickItem-avoid-emitting-signals-during-destruction.patch
  SPECS/qt5-qtdeclarative/0012-a11y-track-item-enabled-state.patch
  SPECS/qt5-qtdeclarative/0013-Make-QaccessibleQuickWidget-private-API.patch
  SPECS/qt5-qtdeclarative/0014-Qml-Don-t-crash-when-as-casting-to-type-with-errors.patch
  SPECS/qt5-qtdeclarative/0015-Fix-missing-glyphs-when-using-NativeRendering.patch
  SPECS/qt5-qtdeclarative/0016-Revert-Fix-missing-glyphs-when-using-NativeRendering.patch
  SPECS/qt5-qtdeclarative/0017-QQmlImportDatabase-Make-sure-the-newly-added-import-.patch
  SPECS/qt5-qtdeclarative/0018-QQuickState-when-handle-QJSValue-properties-correctl.patch
  SPECS/qt5-qtdeclarative/0019-Models-Avoid-crashes-when-deleting-cache-items.patch
  SPECS/qt5-qtdeclarative/qt-QTBUG-111935-fix-V4-jit.patch
  SPECS/qt5-qtdeclarative/qt5-qtdeclarative-gcc11.patch
  SPECS/qt5-qtdeclarative/qt5-qtdeclarative.signatures.json
  SPECS/qt5-qtdeclarative/qt5-qtdeclarative.spec
  SPECS/qt5-qtdeclarative/qtdeclarative-5.15.0-FixMaxXMaxYExtent.patch
  SPECS/qt5-qtdeclarative/qv4global_p-multilib.h
  SPECS/qt5-qtsvg/CVE-2023-32573.patch
  SPECS/qt5-qtsvg/qt5-qtsvg.signatures.json
  SPECS/qt5-qtsvg/qt5-qtsvg.spec
  SPECS/qt5-qttools/qt5-qttools.signatures.json
  SPECS/qt5-qttools/qt5-qttools.spec
  SPECS/qt5-qttools/qttools-opensource-src-5.13.2-runqttools-with-qt5-suffix.patch
  SPECS/qt5-qttools/qttools-opensource-src-5.5.0-qmake-qt5.patch
  SPECS/qt5-qttools/qttools-opensource-src-5.7-add-libatomic.patch
  SPECS/qt5-rpm-macros/qt5-rpm-macros.spec
  cgmanifest.json
Labels: main

#5583 Remove influx-cli-bash-completion subpackage as duplicate and conflict with bash-completion
  SPECS/influx-cli/influx-cli.spec
Labels: main

#5500 qt5: Patch CVE-2023-24607, CVE-2023-32573
  SPECS/qt5-qtbase/CVE-2023-24607.patch
  SPECS/qt5-qtbase/qt5-qtbase.spec
  SPECS/qt5-qtsvg/CVE-2023-32573.patch
  SPECS/qt5-qtsvg/qt5-qtsvg.spec
  cgmanifest.json
Labels: security, 1.0-dev

#5593 qt5: Patch CVE-2023-24607, CVE-2023-32573
  SPECS/qt5-qtbase/CVE-2023-24607.patch
  SPECS/qt5-qtbase/qt5-qtbase.spec
  SPECS/qt5-qtsvg/CVE-2023-32573.patch
  SPECS/qt5-qtsvg/qt5-qtsvg.spec
Labels: main

#5446 Record performance of tooling using timestamps
  toolkit/Makefile
  toolkit/docs/building/building.md
  toolkit/docs/how_it_works/1_initial_prep.md
  toolkit/scripts/imggen.mk
  toolkit/scripts/pkggen.mk
  toolkit/scripts/srpm_pack.mk
  toolkit/scripts/timestamp.mk
  toolkit/scripts/timestamp.sh
  toolkit/scripts/toolchain.mk
  toolkit/scripts/toolchain/build_mariner_toolchain.sh
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
  toolkit/tools/bldtracker/bldtracker.go
  toolkit/tools/boilerplate/boilerplate.go
  toolkit/tools/boilerplate/hello/hello.go
  toolkit/tools/grapher/grapher.go
  toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
  toolkit/tools/imageconfigvalidator/imageconfigvalidator.go
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/imagepkgfetcher/imagepkgfetcher.go
  toolkit/tools/imager/imager.go
  toolkit/tools/internal/jsonutils/jsonutils.go
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
  toolkit/tools/internal/packagerepo/repoutils/repoutils.go
  toolkit/tools/internal/pkggraph/pkggraph.go
  toolkit/tools/internal/timestamp/timestamp.go
  toolkit/tools/internal/timestamp/timestamp_mgr.go
  toolkit/tools/internal/timestamp/timestamp_test.go
  toolkit/tools/pkggen/worker/create_worker_chroot.sh
  toolkit/tools/roast/roast.go
  toolkit/tools/scheduler/scheduler.go
  toolkit/tools/scheduler/schedulerutils/buildworker.go
  toolkit/tools/scheduler/schedulerutils/preparerequest.go
  toolkit/tools/specreader/specreader.go
  toolkit/tools/srpmpacker/srpmpacker.go
Labels: go, main

#5575 Patch libvirt to fix CVE-2023-2700
  SPECS/libvirt/CVE-2023-2700.patch
  SPECS/libvirt/libvirt.spec
Labels: main

#5555 Promote and upgrade nbdkit, libssh; add priv_wrapper, cryptsetup-ssh-token
  SPECS-EXTENDED/libssh/libssh-0.9.5.tar.xz.asc
  SPECS-EXTENDED/nbdkit/nbdkit.signatures.json
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/cryptsetup/cryptsetup.spec
  SPECS/libssh/libssh-0.10.5.tar.xz.asc
  SPECS/libssh/libssh.keyring
  SPECS/libssh/libssh.signatures.json
  SPECS/libssh/libssh.spec
  SPECS/libssh/libssh_client.config
  SPECS/libssh/libssh_server.config
  SPECS/nbdkit/nbdkit.signatures.json
  SPECS/nbdkit/nbdkit.spec
  SPECS/priv_wrapper/priv_wrapper-1.0.1.tar.gz.asc
  SPECS/priv_wrapper/priv_wrapper-fix-cmocka-1.1.6+-support.patch
  SPECS/priv_wrapper/priv_wrapper.keyring
  SPECS/priv_wrapper/priv_wrapper.signatures.json
  SPECS/priv_wrapper/priv_wrapper.spec
  cgmanifest.json
Labels: main

#5601 Upgrade version to 4.0.10 to address CVE-2023-30601
  SPECS-EXTENDED/cassandra/cassandra.signatures.json
  SPECS-EXTENDED/cassandra/cassandra.spec
  cgmanifest.json
Labels: main

#5584 Add nvme_multipath support and patch default to off
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  SPECS/kernel/nvme_multipath_default_false.patch
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#5582 remove python-pyvmomi component
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/python-pyvmomi/python-pyvmomi.signatures.json
  SPECS/python-pyvmomi/python-pyvmomi.spec
  cgmanifest.json
Labels: main

#5547 Update SymCrypt and SCOSSL SPECs
  SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.signatures.json
  SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.spec
  SPECS/SymCrypt/SymCrypt.signatures.json
  SPECS/SymCrypt/SymCrypt.spec
  cgmanifest.json
Labels: main

#5514 Upgrade KeysInUse-OpenSSL to 0.3.3
  SPECS/KeysInUse-OpenSSL/KeysInUse-OpenSSL.signatures.json
  SPECS/KeysInUse-OpenSSL/KeysInUse-OpenSSL.spec
  cgmanifest.json
Labels: main

#5602 Remove new cryptsetup-ssh-token package which creates circular build dependency
  SPECS/cryptsetup/cryptsetup.spec
Labels: main
