Repository microsoft/azurelinux, pull requests merged in 2024-01, with the labels that each got.

#7140 apparmor: add patches for CVE-2023-50471 and CVE-2023-50472
  SPECS/apparmor/CVE-2023-50471.patch
  SPECS/apparmor/apparmor.spec
Labels: security

#7061 Upgrade curl to 8.5.0; Addresses CVE-2023-46219
  SPECS/curl/CVE-2023-38545.patch
  SPECS/curl/CVE-2023-38546.patch
  SPECS/curl/curl.signatures.json
  SPECS/curl/curl.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 3.0

#6792 [3.0] Correctly package libgcc-devel for gcc 13.2.0
  SPECS/gcc/gcc.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 3.0

#7148 vim: upgrade version 9.0.2010 -> 9.0.2190
  SPECS/vim/vim.signatures.json
  SPECS/vim/vim.spec
  cgmanifest.json
Labels: 3.0

#7145 iperf3: upgrade version 3.14 -> 3.16
  SPECS/iperf3/iperf3.signatures.json
  SPECS/iperf3/iperf3.spec
  cgmanifest.json
Labels: 3.0

#7119 Update librdkafka to 2.3.0
  SPECS/librdkafka/librdkafka.signatures.json
  SPECS/librdkafka/librdkafka.spec
  cgmanifest.json
Labels: 3.0

#7151 Upgrade nfs-utils to 2.6.4 and libtirpc to 1.3.4
  SPECS/libtirpc/libtirpc.signatures.json
  SPECS/libtirpc/libtirpc.spec
  SPECS/nfs-utils/nfs-utils.signatures.json
  SPECS/nfs-utils/nfs-utils.spec
  cgmanifest.json
Labels: 3.0

#7171 Revert "Increase image size for baremetal and qemu guest to 4GB"
  toolkit/imageconfigs/baremetal.json
  toolkit/imageconfigs/qemu-guest.json
Labels: main

#6827 Upgrade and move libdwarf from extended to core
  SPECS-EXTENDED/libdwarf/libdwarf.signatures.json
  SPECS/libdwarf/libdwarf.signatures.json
  SPECS/libdwarf/libdwarf.spec
  SPECS/libdwarf/libdwarf_skip_test.patch
  cgmanifest.json
Labels: main

#7093 fmt: upgrade 8.1.1 -> 10.2.1
  SPECS/fmt/fmt.signatures.json
  SPECS/fmt/fmt.spec
  cgmanifest.json
Labels: 3.0

#7155 irqbalance: upgrade version 1.8.0 -> 1.9.3
  SPECS/irqbalance/fix-format-security.patch
  SPECS/irqbalance/fix-load-unsigned-overflow.patch
  SPECS/irqbalance/irqbalance.signatures.json
  SPECS/irqbalance/irqbalance.spec
  cgmanifest.json
Labels: 3.0

#7146 haproxy: upgrade version 2.4.24 -> 2.9.1
  SPECS/haproxy/haproxy.signatures.json
  SPECS/haproxy/haproxy.spec
  cgmanifest.json
Labels: 3.0

#7095 fuse3: upgrade 3.10.5 -> 3.16.2
  SPECS/fuse3/fuse3.signatures.json
  SPECS/fuse3/fuse3.spec
  cgmanifest.json
Labels: 3.0

#7188 toolkit: Fix worker chroot progress
  toolkit/tools/pkggen/worker/create_worker_chroot.sh
Labels: 3.0

#7179 Update libell to 0.61
  SPECS/libell/libell.signatures.json
  SPECS/libell/libell.spec
  cgmanifest.json
Labels: 3.0

#7207 Image Customizer: Resolves bug with SSH public key paths - support for relative path
  toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
Labels: main

#7216 Patch CVE-2023-48795 in moby-cli
  SPECS/moby-cli/CVE-2023-48795.patch
  SPECS/moby-cli/moby-cli.spec
Labels: security, main

#7199 Remove CPython from %check pip3 install in cytools
  SPECS/python-cytoolz/python-cytoolz.spec
Labels: main

#7208 Upgrade lvm2 to 2.03.23
  SPECS/lvm2/lvm2.signatures.json
  SPECS/lvm2/lvm2.spec
  cgmanifest.json
Labels: 3.0

#7169 containerized-rpmbuild: make tools only for build mode (CP #7122)
  toolkit/scripts/containerized-build/create_container_build.sh
Labels: 3.0

#7217 python-gevent: Disable flaky test failure
  SPECS/python-gevent/python-gevent.signatures.json
  SPECS/python-gevent/python-gevent.spec
  SPECS/python-gevent/tests_to_ignore.txt
Labels: main

#7218 toolkit: fix worker chroot progress [main]
  toolkit/tools/pkggen/worker/create_worker_chroot.sh
Labels: main

#7222 Revert "[AUTOPATCHER-kernel] Kernel upgrade to version 5.15.143.1 - branch main (#7048)"
  SPECS-SIGNED/kernel-azure-signed/kernel-azure-signed.spec
  SPECS-SIGNED/kernel-hci-signed/kernel-hci-signed.spec
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/hyperv-daemons/hyperv-daemons.signatures.json
  SPECS/hyperv-daemons/hyperv-daemons.spec
  SPECS/kernel-azure/config
  SPECS/kernel-azure/config_aarch64
  SPECS/kernel-azure/kernel-azure.signatures.json
  SPECS/kernel-azure/kernel-azure.spec
  SPECS/kernel-hci/0005-net-mlx5-Lag-move-lag-files-into-directory.patch
  SPECS/kernel-hci/config
  SPECS/kernel-hci/kernel-hci.signatures.json
  SPECS/kernel-hci/kernel-hci.spec
  SPECS/kernel-headers/kernel-headers.signatures.json
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/CVE-2023-46862.nopatch
  SPECS/kernel/CVE-2023-6546.nopatch
  SPECS/kernel/CVE-2023-6622.nopatch
  SPECS/kernel/CVE-2023-6931.nopatch
  SPECS/kernel/CVE-2023-6932.nopatch
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#7201 Upgrade guile from 2.0.14 to 3.0.9
  SPECS/guile/guile.signatures.json
  SPECS/guile/guile.spec
  cgmanifest.json
Labels: 3.0

#7186 [main] Revert "toolkit image build: Fix make error for config files outside …
  toolkit/scripts/get_config_deps.sh
  toolkit/scripts/imggen.mk
Labels: main

#7189 [3.0-dev] Revert "toolkit image build: Fix make error for config files outside …
  toolkit/scripts/get_config_deps.sh
  toolkit/scripts/imggen.mk
Labels: 3.0

#7221 [2.0] Fix fluent-bit CVE-2023-52284
  SPECS/fluent-bit/CVE-2023-52284.patch
  SPECS/fluent-bit/fluent-bit.spec
Labels: security, main

#7239 Add DAILY_BUILD_REPO argument to support local developer builds with daily builds
  toolkit/Makefile
Labels: main

#7213 authbind: upgrade from 2.1.2 -> 2.1.3
  SPECS/authbind/authbind.signatures.json
  SPECS/authbind/authbind.spec
  cgmanifest.json
Labels: 3.0

#7194 Update sudo to 1.9.15p5 for CVE-2023-42465
  SPECS/sudo/disable-newgroup-query-when-netgroup-base-is-not-set.patch
  SPECS/sudo/sudo.signatures.json
  SPECS/sudo/sudo.spec
  cgmanifest.json
Labels: main, fasttrack/2.0

#7248 [2.0] Fix reaper CVE-2023-26159
  SPECS/reaper/CVE-2023-26159.patch
  SPECS/reaper/reaper.spec
Labels: main

#7251 [2.0] Fix sqlite CVE-2023-7104
  SPECS/sqlite/CVE-2023-7104.patch
  SPECS/sqlite/sqlite.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#7242 upgrade freeipmi to 1.6.11.1 3.0 dev
  SPECS/freeipmi/freeipmi.signatures.json
  SPECS/freeipmi/freeipmi.spec
  cgmanifest.json
Labels: 3.0, Azure Linux 3.0

#7268 cracklib: upgrade from 2.9.7 to 2.9.11
  SPECS/cracklib/cracklib.signatures.json
  SPECS/cracklib/cracklib.spec
  cgmanifest.json
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 3.0

#7257 python-psutil: Update from 5.9.0 to 5.9.7 in Mariner 3.0
  SPECS/python-psutil/disable-tests-python-psutil.patch
  SPECS/python-psutil/python-psutil.signatures.json
  SPECS/python-psutil/python-psutil.spec
  cgmanifest.json
Labels: 3.0

#7094 freetds: upgrade 1.1.20 -> 1.4.10
  SPECS/freetds/freetds.signatures.json
  SPECS/freetds/freetds.spec
  cgmanifest.json
Labels: 3.0

#7177 at: upgrade version 3.2.2 -> 3.2.5
  SPECS/at/at-3.1.14-usePOSIXtimers.patch
  SPECS/at/at-3.2.2-make.patch
  SPECS/at/at-3.2.2-shell.patch
  SPECS/at/at-3.2.23-coverity-fix.patch
  SPECS/at/at-3.2.5-aborted-jobs.patch
  SPECS/at/at-3.2.5-mailwithhostname.patch
  SPECS/at/at-3.2.5-make.patch
  SPECS/at/at-3.2.5-nitpicks.patch
  SPECS/at/at-3.2.5-noabort.patch
  SPECS/at/at-3.2.5-pam.patch
  SPECS/at/at.signatures.json
  SPECS/at/at.spec
  cgmanifest.json
Labels: 3.0

#7192 gsm: upgrade version 1.0.19 -> 1.0.22
  SPECS/gsm/gsm-makefile.patch
  SPECS/gsm/gsm.signatures.json
  SPECS/gsm/gsm.spec
  cgmanifest.json
Labels: 3.0

#7262 workflows: bump setup-go to v5
  .github/workflows/go-test-coverage.yml
  .github/workflows/quickstart_1.0.yml
  .github/workflows/quickstart_2.0.yml
Labels: main

#7234 Bugfix - Skip Dracut Module and Mariner.cfg Update with no Verity Cfg.
  toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
  toolkit/tools/pkg/imagecustomizerlib/customizeverity.go
Labels: main

#7275 Upgrade kured to 1.14.2 for vendored go CVE-2023-39325
  SPECS/kured/kured-imagePullPolicy.patch
  SPECS/kured/kured.signatures.json
  SPECS/kured/kured.spec
  cgmanifest.json
Labels: main

#7206 Bump ca-certificates to new major version for Azl3
  SPECS/ca-certificates/ca-certificates.spec
  SPECS/prebuilt-ca-certificates-base/prebuilt-ca-certificates-base.spec
  SPECS/prebuilt-ca-certificates/prebuilt-ca-certificates.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 3.0

#7226 [2.0] Fix postfix CVE-2023-51764
  SPECS/postfix/CVE-2023-51764.patch
  SPECS/postfix/postfix.spec
Labels: security, main

#7280 Kernel upgrade to version 5.15.145.2
  SPECS-SIGNED/kernel-azure-signed/kernel-azure-signed.spec
  SPECS-SIGNED/kernel-hci-signed/kernel-hci-signed.spec
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/hyperv-daemons/hyperv-daemons.signatures.json
  SPECS/hyperv-daemons/hyperv-daemons.spec
  SPECS/kernel-azure/config
  SPECS/kernel-azure/config_aarch64
  SPECS/kernel-azure/kernel-azure.signatures.json
  SPECS/kernel-azure/kernel-azure.spec
  SPECS/kernel-hci/0005-net-mlx5-Lag-move-lag-files-into-directory.patch
  SPECS/kernel-hci/config
  SPECS/kernel-hci/kernel-hci.signatures.json
  SPECS/kernel-hci/kernel-hci.spec
  SPECS/kernel-headers/kernel-headers.signatures.json
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/mariner-required-configs.json
Labels: main

#7282 Making GitHub Actions' permissions explicit.
  .github/workflows/check-clean-stage.yml
  .github/workflows/check-entangled-specs.yml
  .github/workflows/check-kernel-config.yml
  .github/workflows/check-license-map.yml
  .github/workflows/check-livepatches.yml
  .github/workflows/check-manifests.yml
  .github/workflows/check-package-cgmanifest.yml
  .github/workflows/check-spec.yml
  .github/workflows/check-static-glibc.yml
  .github/workflows/go-test-coverage.yml
  .github/workflows/lint-specs.yml
  .github/workflows/quickstart_1.0.yml
  .github/workflows/quickstart_2.0.yml
Labels: main

#7294 fix python urllib3 test
  SPECS/python-urllib3/CVE-2023-43804.patch
  SPECS/python-urllib3/python-urllib3.spec
  SPECS/python-urllib3/urllib3_test_recent_date.patch
Labels: main

#7196 Kata-CC: Upgrade to 0.6.3
  SPECS/kata-containers-cc/kata-containers-cc.signatures.json
  SPECS/kata-containers-cc/kata-containers-cc.spec
  SPECS/kata-containers-cc/keep-uvm-rootfs-dependencies.patch
  SPECS/kata-containers-cc/mariner-coco-build-uvm.sh
  cgmanifest.json
Labels: main

#7300 Image Customizer: Use safeloopback.Loopback instead of ImageConnection for split partitions
  toolkit/tools/pkg/imagecustomizerlib/extractpartitions.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
Labels: main

#7043 Image Customizer: Fix special directories and partition customization.
  toolkit/tools/imagegen/installutils/installutils_test.go
  toolkit/tools/imager/imager.go
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
  toolkit/tools/internal/packagerepo/repoutils/repoquery.go
  toolkit/tools/internal/safechroot/safechroot.go
  toolkit/tools/internal/safechroot/safechroot_test.go
  toolkit/tools/internal/shell/shell.go
  toolkit/tools/pkg/imagecustomizerlib/customizepartitionsfilecopy.go
  toolkit/tools/pkg/imagecustomizerlib/customizeutils_test.go
  toolkit/tools/pkg/imagecustomizerlib/imageConnection.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
  toolkit/tools/pkg/imagecustomizerlib/imageutils.go
  toolkit/tools/pkg/simpletoolchroot/simpletoolchroot.go
  toolkit/tools/pkgworker/pkgworker.go
  toolkit/tools/specreader/specreader.go
  toolkit/tools/srpmpacker/srpmpacker.go
  toolkit/tools/validatechroot/validatechroot.go
Labels: main

#7272 Upgrade asciidoc to 10.2.0
  SPECS/asciidoc/asciidoc.signatures.json
  SPECS/asciidoc/asciidoc.spec
  cgmanifest.json
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 3.0

#7299 Patch erlang for CVE-2023-48795
  SPECS/elixir/elixir.spec
  SPECS/erlang/CVE-2023-48795.patch
  SPECS/erlang/erlang.spec
  SPECS/rabbitmq-server/rabbitmq-server.spec
Labels: main

#6945 Added cross-compilation `binutils` and `kernel-headers`.
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/binutils/binutils.spec
  SPECS/binutils/disable_gold_test.patch
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#7323 Image Customizer: Make either one of split partitions format and output image format required
  toolkit/tools/imagecustomizer/docs/cli.md
  toolkit/tools/imagecustomizer/main.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
Labels: main

#7305 OS Modifier (EMU): Add sshkeys to user config
  toolkit/tools/imagecustomizerapi/user.go
  toolkit/tools/imagegen/configuration/user.go
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
Labels: main

#7303 Imager: Ensure ext4 formatting is consistent across build hosts
  toolkit/tools/imagegen/diskutils/diskutils.go
  toolkit/tools/imager/imager.go
  toolkit/tools/internal/safemount/safemount_test.go
  toolkit/tools/pkg/imagecustomizerlib/imageutils.go
Labels: main

#7292 Patch libssh2 for CVE-2023-48795
  SPECS/curl/curl.spec
  SPECS/libgit2/libgit2.spec
  SPECS/libssh2/CVE-2023-48795.patch
  SPECS/libssh2/libssh2.spec
  SPECS/libvirt/libvirt.spec
  SPECS/nmap/nmap.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#7329 apply patch for CVE-2023-48795
  SPECS/cert-manager/CVE-2023-48795.patch
  SPECS/cert-manager/cert-manager.spec
Labels: main

#7336 libewf: remove package
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/libewf/libewf.signatures.json
  SPECS/libewf/libewf.spec
  cgmanifest.json
Labels: 3.0

#7273 libXmu: upgrade from 1.1.3 -> 1.1.4
  SPECS/libXmu/libXmu.signatures.json
  SPECS/libXmu/libXmu.spec
  cgmanifest.json
Labels: 3.0

#7270 xcb-proto: Upgrade version to 1.16
  SPECS/xcb-proto/xcb-proto-1.13-python39.patch
  SPECS/xcb-proto/xcb-proto.signatures.json
  SPECS/xcb-proto/xcb-proto.spec
  cgmanifest.json
Labels: 3.0

#7338 libICE: upgrade from 1.0.10 -> 1.1.1
  SPECS/libICE/libICE.signatures.json
  SPECS/libICE/libICE.spec
  cgmanifest.json
Labels: 3.0

#7339 libSM: upgrade from 1.2.3 to 1.2.4
  SPECS/libSM/libSM.signatures.json
  SPECS/libSM/libSM.spec
  cgmanifest.json
Labels: 3.0

#7340 libXinerama: Upgrade from 1.1.4 to 1.1.5
  SPECS/libXinerama/libXinerama.signatures.json
  SPECS/libXinerama/libXinerama.spec
  cgmanifest.json
Labels: 3.0

#7178 atop: upgrade version 2.6.0 -> 2.9.0
  SPECS/atop/9cb119713b5e6be43671fe1856fb4bd49ff91fa7.patch
  SPECS/atop/atop-2.3.0-newer-gcc.patch
  SPECS/atop/atop.signatures.json
  SPECS/atop/atop.spec
  SPECS/atop/format.patch
  SPECS/atop/nvme_support.patch
  cgmanifest.json
Labels: 3.0

#7337 Add epoch to libdwarf spec to fix versioning order
  SPECS/libdwarf/libdwarf.spec
Labels: fasttrack/2.0

#7330 Fixed `cloud-init` tests.
  SPECS/cloud-init/cloud-init.spec
  cgmanifest.json
Labels: main

#7269 Fix CVE-2023-50711 in cloud-hypervisor
  SPECS/cloud-hypervisor/CVE-2023-50711-versionize.patch
  SPECS/cloud-hypervisor/CVE-2023-50711-vhost.patch
  SPECS/cloud-hypervisor/CVE-2023-50711-vmm-sys-util-fix1.patch
  SPECS/cloud-hypervisor/CVE-2023-50711-vmm-sys-util-fix2-cargo.patch
  SPECS/cloud-hypervisor/cloud-hypervisor.spec
Labels: main

#7320 Fix mariadb install post script
  SPECS/mariadb/fix_symlink_location_db_install.patch
  SPECS/mariadb/mariadb.spec
Labels: main

#7159 polkit: upgrade to v123 + switch to duktape 2.7.0 as its enabled JS engine
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/duktape/duktape-2.7.0-link-against-libm.patch
  SPECS/duktape/duktape.signatures.json
  SPECS/duktape/duktape.spec
  SPECS/polkit/CVE-2021-4034.patch
  SPECS/polkit/polkit.signatures.json
  SPECS/polkit/polkit.spec
  cgmanifest.json
Labels: 3.0

#7215 Introduce Rust virtiofsd package
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/virtiofsd/config.toml
  SPECS/virtiofsd/virtiofsd.signatures.json
  SPECS/virtiofsd/virtiofsd.spec
  cgmanifest.json
Labels: main

#7181 Enable CONFIG_X86_IOPL_IOPERM
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/mariner-required-configs.json
Labels: main

#7306 Upgrade libXcomposite to version 0.4.6
  SPECS/libXcomposite/libXcomposite.signatures.json
  SPECS/libXcomposite/libXcomposite.spec
  cgmanifest.json
Labels: 3.0

#7332 Set SELinux as default LSM
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/scripts/mariner-required-configs.json
Labels: 3.0

#7115 Remove nvme multipath default off patch
  SPECS/kernel/nvme_multipath_default_false.patch
Labels: 3.0

#7180 Enable CONFIG_X86_IOPL_IOPERM
  SPECS/kernel/config
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/scripts/mariner-required-configs.json
Labels: 3.0

#7197 Kata-CC: Upgrade to 0.6.3
  SPECS/kata-containers-cc/kata-containers-cc.signatures.json
  SPECS/kata-containers-cc/kata-containers-cc.spec
  SPECS/kata-containers-cc/keep-uvm-rootfs-dependencies.patch
  SPECS/kata-containers-cc/mariner-coco-build-uvm.sh
  cgmanifest.json
Labels: fasttrack/2.0

#7311 Upgrade ding-libs to version 0.6.2
  SPECS/ding-libs/INI-Fix-detection-of-error-messages.patch
  SPECS/ding-libs/INI-Remove-definiton-of-TRACE_LEVEL.patch
  SPECS/ding-libs/INI-Silence-ini_augment-match-failures.patch
  SPECS/ding-libs/TEST-validators_ut_check-Fix-fail-with-new-glibc.patch
  SPECS/ding-libs/ding-libs.signatures.json
  SPECS/ding-libs/ding-libs.spec
  cgmanifest.json
Labels: 3.0

#7309 add memcached container files
  .pipelines/containerSourceData/memcached/Dockerfile-Memcached
  .pipelines/containerSourceData/memcached/memcached.pkg
  .pipelines/containerSourceData/scripts/BuildGoldenContainers.sh
Labels: 3.0

#7263 workflows: bump setup-go to v5 & drop 1.0 workflow
  .github/workflows/go-test-coverage.yml
  .github/workflows/quickstart_1.0.yml
  .github/workflows/quickstart_2.0.yml
Labels: 3.0

#7347 Upgrade libpciaccess to 0.17
  SPECS/libpciaccess/libpciaccess.signatures.json
  SPECS/libpciaccess/libpciaccess.spec
  cgmanifest.json
Labels: 3.0

#7349 Add patch to numad
  SPECS/numad/0001-numad_log-fix-buffer-overflow.patch
  SPECS/numad/numad.spec
Labels: 3.0

#7298 Image Customizer: remove adduser-config.yaml file as it contains password field
  .config/CredScanSuppressions.json
  toolkit/tools/pkg/imagecustomizerlib/testdata/addusers-config.yaml
  toolkit/tools/pkg/osmodifierlib/testdata/addusers-config.yaml
Labels: main

#7302 toolkit: fix finding files for imageconfig validator flag
  toolkit/scripts/get_config_deps.sh
  toolkit/scripts/imggen.mk
Labels: Tools

#7250 Upgrade iscsi-initiator-utils from 2.1.4 to 2.1.9
  SPECS/iscsi-initiator-utils/0001-meson-don-t-hide-things-with-Wno-all.patch
  SPECS/iscsi-initiator-utils/0001-unit-file-tweaks.patch
  SPECS/iscsi-initiator-utils/0002-Currently-when-iscsi.service-is-installed-it-creates.patch
  SPECS/iscsi-initiator-utils/0002-idmb_rec_write-check-for-tpgt-first.patch
  SPECS/iscsi-initiator-utils/0003-Use-DBROOT-in-iscsi-starter.-Include-iscsi-starter-i.patch
  SPECS/iscsi-initiator-utils/0003-idbm_rec_write-seperate-old-and-new-style-writes.patch
  SPECS/iscsi-initiator-utils/0004-fix-systemctl-path-in-iscsi-starter.service.patch
  SPECS/iscsi-initiator-utils/0004-idbw_rec_write-pick-tpgt-from-existing-record.patch
  SPECS/iscsi-initiator-utils/0005-improved-onboot-and-shutdown-services.patch
  SPECS/iscsi-initiator-utils/0005-update-initscripts-and-docs.patch
  SPECS/iscsi-initiator-utils/0006-iscsid.conf-Fedora-Red-Hat-defaults.patch
  SPECS/iscsi-initiator-utils/0006-use-var-for-config.patch
  SPECS/iscsi-initiator-utils/0007-Disable-Data-Digests.patch
  SPECS/iscsi-initiator-utils/0007-use-red-hat-for-name.patch
  SPECS/iscsi-initiator-utils/0008-Revert-iscsiadm-return-error-when-login-fails.patch
  SPECS/iscsi-initiator-utils/0009-Add-macros-to-release-GIL-lock.patch
  SPECS/iscsi-initiator-utils/0009-Coverity-scan-fixes.patch
  SPECS/iscsi-initiator-utils/0010-use-Red-Hat-version-string-to-match-RPM-package-vers.patch
  SPECS/iscsi-initiator-utils/0011-libiscsi-fix-discovery-request-timeout-regression.patch
  SPECS/iscsi-initiator-utils/0012-libiscsi-format-security-build-errors.patch
  SPECS/iscsi-initiator-utils/0013-libiscsi-fix-build-to-use-libopeniscsiusr.patch
  SPECS/iscsi-initiator-utils/0014-libiscsi-fix-build-against-latest-upstream-again.patch
  SPECS/iscsi-initiator-utils/0015-remove-the-offload-boot-supported-ifdef.patch
  SPECS/iscsi-initiator-utils/0017-dont-install-scripts.patch
  SPECS/iscsi-initiator-utils/0018-use-var-lib-iscsi-in-libopeniscsiusr.patch
  SPECS/iscsi-initiator-utils/0020-fix-upstream-build-breakage-of-iscsiuio-LDFLAGS.patch
  SPECS/iscsi-initiator-utils/0021-use-Red-Hat-version-string-to-match-RPM-package-vers.patch
  SPECS/iscsi-initiator-utils/0022-iscsi_if.h-replace-zero-length-array-with-flexible-a.patch
  SPECS/iscsi-initiator-utils/0023-stop-using-Werror-for-now.patch
  SPECS/iscsi-initiator-utils/0024-minor-service-file-updates.patch
  SPECS/iscsi-initiator-utils/0025-Remove-dependences-from-iscsi-init.service.patch
  SPECS/iscsi-initiator-utils/0026-fix-libpath.patch
  SPECS/iscsi-initiator-utils/0101-libiscsi.patch
  SPECS/iscsi-initiator-utils/0102-libiscsi-introduce-sessions-API.patch
  SPECS/iscsi-initiator-utils/0103-fix-libiscsi-firmware-discovery-issue-with-NULL-drec.patch
  SPECS/iscsi-initiator-utils/0104-libiscsi-build-fixes.patch
  SPECS/iscsi-initiator-utils/0201-mariner-fixes.patch
  SPECS/iscsi-initiator-utils/iscsi-initiator-utils.signatures.json
  SPECS/iscsi-initiator-utils/iscsi-initiator-utils.spec
  cgmanifest.json
Labels: 3.0

#7307 add memcached container files
  .pipelines/containerSourceData/memcached/Dockerfile-Memcached
  .pipelines/containerSourceData/memcached/memcached.pkg
  .pipelines/containerSourceData/scripts/BuildGoldenContainers.sh
Labels: main

#7350 Fix SELinux labeling of special dirs
  toolkit/tools/imagegen/installutils/installutils.go
Labels: 3.0

#7362 libnfs: upgrade version 4.0.0 -> 5.0.2
  SPECS/libnfs/libnfs.signatures.json
  SPECS/libnfs/libnfs.spec
  cgmanifest.json
Labels: 3.0

#7387 sleuthkit: upgrade to 4.12.1
  SPECS/sleuthkit/sleuthkit.signatures.json
  SPECS/sleuthkit/sleuthkit.spec
  cgmanifest.json
Labels: 3.0

#7361 git-lfs: upgrade version 3.1.4 -> 3.4.1
  SPECS/git-lfs/git-lfs.signatures.json
  SPECS/git-lfs/git-lfs.spec
  cgmanifest.json
Labels: 3.0

#7357 skopeo: upgrade version 1.13.3 -> 1.14.1 to address GHSA-jq35-85cj-fj4p
  SPECS/skopeo/skopeo.signatures.json
  SPECS/skopeo/skopeo.spec
  cgmanifest.json
Labels: security, main

#7385 environment-modules: upgrade to 5.3.1
  SPECS/environment-modules/environment-modules.signatures.json
  SPECS/environment-modules/environment-modules.spec
  cgmanifest.json
Labels: 3.0

#7158 Bump aide to 0.18.6
  SPECS/aide/aide-0.15-syslog-format.patch
  SPECS/aide/aide-0.16-Use-LDADD-for-adding-curl-library-to-the-linker-comm.patch
  SPECS/aide/aide-0.16-crash-elf.patch
  SPECS/aide/aide-0.16-crypto-disable-haval-and-others.patch
  SPECS/aide/aide-0.16b1-fipsfix.patch
  SPECS/aide/aide-0.16rc1-man.patch
  SPECS/aide/aide.signatures.json
  SPECS/aide/aide.spec
  SPECS/aide/coverity.patch
  cgmanifest.json
Labels: 3.0

#7355 Upgrade mm-common from 1.0.4 to 1.0.6
  SPECS/mm-common/mm-common.signatures.json
  SPECS/mm-common/mm-common.spec
  cgmanifest.json
Labels: 3.0

#7356 Upgrade seabios from 1.14.0 to 1.16.3
  SPECS/seabios/seabios.signatures.json
  SPECS/seabios/seabios.spec
  cgmanifest.json
Labels: 3.0

#7405 Patch autogen to build with guile 3.x
  SPECS/autogen/allow-guile-3.0.patch
  SPECS/autogen/autogen.spec
Labels: 3.0

#7359 helm: update version 3.13.2 -> 3.14.0 to address CVE-2023-44487
  SPECS/helm/helm.signatures.json
  SPECS/helm/helm.spec
  cgmanifest.json
Labels: security, fasttrack/2.0

#7389 Remove /etc/host.conf from filesystem
  SPECS/filesystem/filesystem.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#7417 Address CVE-2023-6932, CVE-2023-6817 and CVE-2023-6931
  SPECS/kernel/CVE-2023-6817.nopatch
  SPECS/kernel/CVE-2023-6931.nopatch
  SPECS/kernel/CVE-2023-6932.nopatch
Labels: security, main

#7324 redis: Update from 6.2.13 to 7.2.4 in Mariner 3.0
  SPECS/redis/disable_active_defrag_big_keys.patch
  SPECS/redis/redis.signatures.json
  SPECS/redis/redis.spec
  cgmanifest.json
Labels: 3.0

#7384 make: upgrade to 4.4.1
  SPECS/make/make.signatures.json
  SPECS/make/make.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 3.0

#7403 upgrade python-cherrypy, python-cffi, python-pytest-mock
  SPECS/python-cffi/python-cffi.signatures.json
  SPECS/python-cffi/python-cffi.spec
  SPECS/python-cherrypy/python-cherrypy.signatures.json
  SPECS/python-cherrypy/python-cherrypy.spec
  SPECS/python-pytest-mock/python-pytest-mock.signatures.json
  SPECS/python-pytest-mock/python-pytest-mock.spec
  cgmanifest.json
Labels: 3.0

#7195 Upgrade gnutls from 3.7.7 to 3.8.2
  SPECS/gnutls/CVE-2023-0361.patch
  SPECS/gnutls/gnutls.signatures.json
  SPECS/gnutls/gnutls.spec
  cgmanifest.json
Labels: 3.0

#7182 Upgrade dbus from 1.15.2 to 1.15.8
  SPECS/dbus/dbus.signatures.json
  SPECS/dbus/dbus.spec
  cgmanifest.json
Labels: 3.0

#7391 Upgrade distroless-packages to 3.0
  SPECS/distroless-packages/distroless-packages.spec
Labels: 3.0

#7165 kernel-hci: Add missing commit subject to patch 27
  SPECS-SIGNED/kernel-hci-signed/kernel-hci-signed.spec
  SPECS/kernel-hci/0028-net-mlx5-Bridge-Use-debug-instead-of-warn-if-entry-d.patch
  SPECS/kernel-hci/kernel-hci.spec
Labels: main

#7404 Upgrade rdma-core to v49.1
  SPECS/rdma-core/rdma-core.signatures.json
  SPECS/rdma-core/rdma-core.spec
  cgmanifest.json
Labels: 3.0

#7431 PyPAM: remove package
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/PyPAM/PyPAM-0.5.0-dealloc.patch
  SPECS/PyPAM/PyPAM-0.5.0-memory-errors.patch
  SPECS/PyPAM/PyPAM-0.5.0-nofree.patch
  SPECS/PyPAM/PyPAM-0.5.0-return-value.patch
  SPECS/PyPAM/PyPAM-dlopen.patch
  SPECS/PyPAM/PyPAM-python3-support.patch
  SPECS/PyPAM/PyPAM.signatures.json
  SPECS/PyPAM/PyPAM.spec
  cgmanifest.json
Labels: 3.0

#7426 python-jinja2: add patch for CVE-2024-22195
  SPECS/python-jinja2/CVE-2024-22195.patch
  SPECS/python-jinja2/python-jinja2.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, main

#7435 python-pluggy: upgrade to 1.3.0
  SPECS/python-pluggy/python-pluggy.signatures.json
  SPECS/python-pluggy/python-pluggy.spec
  cgmanifest.json
Labels: 3.0

#7428 OS modifier: fix a bug if condition to not skip processing sshkeys when sshkeypaths is empty
  toolkit/tools/imagegen/installutils/installutils.go
Labels: main

#7030 Kata-CC: Enforce a restrictive pod security policy
  SPECS/kata-containers-cc/kata-containers-cc.signatures.json
  SPECS/kata-containers-cc/kata-containers-cc.spec
  SPECS/kata-containers-cc/mariner-coco-build-uvm.sh
Labels: main

#7220 Add Mysql user with package install
  SPECS/mysql/mysql.spec
Labels: main

#7433 Upgrade c-ares to 1.25.0
  SPECS/c-ares/c-ares.signatures.json
  SPECS/c-ares/c-ares.spec
  cgmanifest.json
Labels: 3.0

#7408 nspr: upgrade from 4.30 -> 4.9.6
  SPECS/nspr/nspr.signatures.json
  SPECS/nspr/nspr.spec
  cgmanifest.json
Labels: 3.0

#7410 libfontenc: upgrade from 1.1.3 -> 1.1.7
  SPECS/libfontenc/libfontenc.signatures.json
  SPECS/libfontenc/libfontenc.spec
  cgmanifest.json
Labels: 3.0

#7411 libxcb: upgrade from 1.13.1 -> 1.16
  SPECS/libxcb/libxcb.signatures.json
  SPECS/libxcb/libxcb.spec
  cgmanifest.json
Labels: 3.0

#7255 upgrade squashfs-tools to 4.6.1 3.0-dev
  SPECS/squashfs-tools/squashfs-tools.signatures.json
  SPECS/squashfs-tools/squashfs-tools.spec
  cgmanifest.json
Labels: 3.0, Azure Linux 3.0

#7346 Upgrade libiscsi to 1.19.0
  SPECS/libiscsi/0001-Fix-compiler-warning-error-under-gcc7.patch
  SPECS/libiscsi/0002-Fix-another-compiler-warning.patch
  SPECS/libiscsi/0003-Fix-32bit-build.patch
  SPECS/libiscsi/0004-iser-Use-local-container_of-definition.patch
  SPECS/libiscsi/0005-fix-ipv6.patch
  SPECS/libiscsi/0006-fix-coverity-report.patch
  SPECS/libiscsi/libiscsi.signatures.json
  SPECS/libiscsi/libiscsi.spec
  cgmanifest.json
Labels: 3.0

#6996 Added a cross-compilation subpackage for aarch64 into `gcc`.
  SPECS/gcc/gcc.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
Labels: main

#7434 fakeroot: upgrade to 1.32.2
  SPECS/fakeroot/also-wrap-stat-library-call.patch
  SPECS/fakeroot/fakeroot-inttypes.patch
  SPECS/fakeroot/fakeroot.signatures.json
  SPECS/fakeroot/fakeroot.spec
  SPECS/fakeroot/po4a.patch
  cgmanifest.json
Labels: 3.0

#7331 mariner-3.0 - clang llvm lld lldb compilerRt upgrades
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/clang/clang.signatures.json
  SPECS/clang/clang.spec
  SPECS/clang/clang16.signatures.json
  SPECS/clang/clang16.spec
  SPECS/compiler-rt/compiler-rt.signatures.json
  SPECS/compiler-rt/compiler-rt.spec
  SPECS/lld/lld.signatures.json
  SPECS/lld/lld.spec
  SPECS/lld/lld16.signatures.json
  SPECS/lld/lld16.spec
  SPECS/lldb/0001-Silence-GCC-warnings-about-format-not-being-a-string.patch
  SPECS/lldb/lldb.signatures.json
  SPECS/lldb/lldb.spec
  SPECS/llvm/llvm-12.0.1-issue-49955-workaround.patch
  SPECS/llvm/llvm.signatures.json
  SPECS/llvm/llvm.spec
  SPECS/llvm/llvm16.signatures.json
  SPECS/llvm/llvm16.spec
  cgmanifest.json
  toolkit/scripts/check_entangled_specs.py
Labels: 3.0

#7351 Ported cross-compilation `binutils` and `kernel-headers` from `main`.
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/binutils/CVE-2021-45078.patch
  SPECS/binutils/CVE-2022-38533.patch
  SPECS/binutils/CVE-2022-4285.patch
  SPECS/binutils/binutils.spec
  SPECS/binutils/disable_gold_test.patch
  SPECS/binutils/linker-script-readonly-keyword-support.patch
  SPECS/binutils/thin_archive_descriptor.patch
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/Dockerfile
  toolkit/scripts/toolchain/create_toolchain_in_container.sh
Labels: 3.0

#7166 kernel-hci: Backport Nvidia net/mlx5 patches to support 100G BOM
  SPECS-SIGNED/kernel-hci-signed/kernel-hci-signed.spec
  SPECS/kernel-hci/0029-Revert-net-mlx5-DR-Fix-uninitialized-var-warning.patch
  SPECS/kernel-hci/0030-net-mlx5-DR-Fix-code-indentation-in-dr_ste_v1.patch
  SPECS/kernel-hci/0031-net-mlx5-DR-Fix-vport-number-data-type-to-u16.patch
  SPECS/kernel-hci/0032-net-mlx5-DR-Replace-local-WIRE_PORT-macro-with-the-e.patch
  SPECS/kernel-hci/0033-net-mlx5-DR-Add-missing-query-for-vport-0.patch
  SPECS/kernel-hci/0034-net-mlx5-DR-Align-error-messages-for-failure-to-obta.patch
  SPECS/kernel-hci/0035-net-mlx5-DR-Support-csum-recalculation-flow-table-on.patch
  SPECS/kernel-hci/0036-net-mlx5-DR-Add-support-for-SF-vports.patch
  SPECS/kernel-hci/0037-net-mlx5-DR-Increase-supported-num-of-actions-to-32.patch
  SPECS/kernel-hci/0038-net-mlx5-DR-Fix-typo-offeset-to-offset.patch
  SPECS/kernel-hci/0039-net-mlx5-DR-init_next_match-only-if-needed.patch
  SPECS/kernel-hci/0040-net-mlx5-DR-Add-check-for-unsupported-fields-in-matc.patch
  SPECS/kernel-hci/0041-net-mlx5-DR-Fix-check-for-unsupported-fields-in-matc.patch
  SPECS/kernel-hci/0042-net-mlx5-DR-Fix-error-flow-in-creating-matcher.patch
  SPECS/kernel-hci/0043-net-mlx5-DR-Fix-lower-case-macro-prefix-mlx5_-to-MLX.patch
  SPECS/kernel-hci/0044-net-mlx5-DR-Remove-unused-struct-member-in-matcher.patch
  SPECS/kernel-hci/0045-net-mlx5-DR-Add-check-for-flex-parser-ID-value.patch
  SPECS/kernel-hci/0046-net-mlx5-DR-Add-missing-reserved-fields-to-dr_match_.patch
  SPECS/kernel-hci/0047-net-mlx5-DR-Add-support-for-dumping-steering-info.patch
  SPECS/kernel-hci/0048-net-mlx5-DR-Add-support-for-UPLINK-destination-type.patch
  SPECS/kernel-hci/0049-net-mlx5-DR-Warn-on-failure-to-destroy-objects-due-t.patch
  SPECS/kernel-hci/0050-net-mlx5-Add-misc5-flow-table-match-parameters.patch
  SPECS/kernel-hci/0051-net-mlx5-DR-Add-misc5-to-match_param-structs.patch
  SPECS/kernel-hci/0052-net-mlx5-DR-Support-matching-on-tunnel-headers-0-and.patch
  SPECS/kernel-hci/0053-net-mlx5-DR-Add-support-for-matching-on-geneve_tlv_o.patch
  SPECS/kernel-hci/0054-net-mlx5-DR-Improve-steering-for-empty-or-RX-TX-only.patch
  SPECS/kernel-hci/0055-net-mlx5-DR-Ignore-modify-TTL-if-device-doesn-t-supp.patch
  SPECS/kernel-hci/0056-net-mlx5-Add-ability-to-insert-to-specific-flow-grou.patch
  SPECS/kernel-hci/0057-net-mlx5-E-Switch-reserve-and-use-same-uplink-metada.patch
  SPECS/kernel-hci/0058-net-mlx5-E-switch-remove-special-uplink-ingress-ACL-.patch
  SPECS/kernel-hci/0059-net-mlx5-E-switch-add-drop-rule-support-to-ingress-A.patch
  SPECS/kernel-hci/0060-net-mlx5-Lag-use-local-variable-already-defined-to-a.patch
  SPECS/kernel-hci/0061-net-mlx5-Lag-don-t-use-magic-numbers-for-ports.patch
  SPECS/kernel-hci/0062-net-mlx5-Lag-record-inactive-state-of-bond-device.patch
  SPECS/kernel-hci/0063-net-mlx5-Lag-offload-active-backup-drops-to-hardware.patch
  SPECS/kernel-hci/0064-net-mlx5-Add-mlx5_ifc-definitions-for-bridge-multica.patch
  SPECS/kernel-hci/0065-net-mlx5-Bridge-increase-bridge-tables-sizes.patch
  SPECS/kernel-hci/0066-net-mlx5-Bridge-move-additional-data-structures-to-p.patch
  SPECS/kernel-hci/0067-net-mlx5-Bridge-extract-code-to-lookup-parent-bridge.patch
  SPECS/kernel-hci/0068-net-mlx5-Bridge-snoop-igmp-mld-packets.patch
  SPECS/kernel-hci/0069-net-mlx5-Bridge-add-per-port-multicast-replication-t.patch
  SPECS/kernel-hci/0070-net-mlx5-Bridge-support-multicast-VLAN-pop.patch
  SPECS/kernel-hci/0071-netlink-add-support-for-formatted-extack-messages.patch
  SPECS/kernel-hci/0072-net-mlx5-Bridge-implement-mdb-offload.patch
  SPECS/kernel-hci/0073-net-mlx5-Bridge-add-tracepoints-for-multicast.patch
  SPECS/kernel-hci/0074-net-mlx5-DR-Fix-uninitialized-var-warning.patch
  SPECS/kernel-hci/0075-net-mlx5-Fix-matching-on-inner-TTC.patch
  SPECS/kernel-hci/0076-net-mlx5-Lag-fix-a-potential-Oops-with-mlx5_lag_crea.patch
  SPECS/kernel-hci/0077-net-mlx5-DR-Fix-SMFS-steering-info-dump-format.patch
  SPECS/kernel-hci/0078-net-mlx5-DR-Fix-matcher-disconnect-error-flow.patch
  SPECS/kernel-hci/0079-net-mlx5-DR-Ignore-modify-TTL-on-RX-if-device-doesn-.patch
  SPECS/kernel-hci/0080-net-mlx5-DR-Handle-eswitch-manager-and-uplink-vports.patch
  SPECS/kernel-hci/0081-net-mlx5-DR-Fix-slab-out-of-bounds-in-mlx5_cmd_dr_cr.patch
  SPECS/kernel-hci/0082-net-mlx5-Create-eswitch-debugfs-root-directory.patch
  SPECS/kernel-hci/0083-net-mlx5-Bridge-pass-net-device-when-linking-vport-t.patch
  SPECS/kernel-hci/0084-net-mlx5-Bridge-expose-FDB-state-via-debugfs.patch
  SPECS/kernel-hci/0085-net-mlx5-DR-Align-mlx5dv_dr-API-vport-action-with-FW.patch
  SPECS/kernel-hci/0086-net-mlx5-Lag-add-debugfs-to-query-hardware-lag-state.patch
  SPECS/kernel-hci/kernel-hci.spec
Labels: main

#7445 Specialcased 5XX errors during package downloads.
  toolkit/tools/downloader/downloader.go
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
  toolkit/tools/internal/retry/retry.go
  toolkit/tools/precacher/precacher.go
  toolkit/tools/srpmpacker/srpmpacker.go
Labels: main

#7477 Fix runtime dependency for python3-virtualenv
  SPECS/python-virtualenv/python-virtualenv.spec
Labels: main

#7352 containerized-rpmbuild: add 3.0
  toolkit/scripts/containerized-build/create_container_build.sh
  toolkit/scripts/containerized-build/resources/mariner-3_repo
  toolkit/scripts/containerized-build/resources/mariner.Dockerfile
  toolkit/scripts/containerized-build/resources/setup_functions.sh
Labels: 3.0

#7474 Set ownership of virtiofsd package to Kata team
  .github/CODEOWNERS
Labels: main

#7475 Added initial doc about reading error logs.
  toolkit/README.md
  toolkit/docs/how_it_works/0_intro.md
  toolkit/docs/how_it_works/5_misc.md
  toolkit/docs/how_it_works/6_logs.md
Labels: main

#7486 fish: remove package
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/fish/fish.signatures.json
  SPECS/fish/fish.spec
  cgmanifest.json
Labels: 3.0

#7482 finger: remove package
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/finger/CVE-1999-0150.nopatch
  SPECS/finger/CVE-1999-0612.nopatch
  SPECS/finger/LICENSE
  SPECS/finger/bsd-finger-time.patch
  SPECS/finger/finger.signatures.json
  SPECS/finger/finger.socket
  SPECS/finger/finger.spec
  SPECS/finger/finger@.service
  SPECS/finger/fix-manpage-typo.patch
  cgmanifest.json
Labels: 3.0

#7427 Upgrade ucx from 1.11.0 to 1.15.0
  SPECS/ucx/ucx.signatures.json
  SPECS/ucx/ucx.spec
  cgmanifest.json
Labels: 3.0

#7494 upgrade rubygem-timers to 4.3.5
  SPECS/rubygem-timers/rubygem-timers.signatures.json
  SPECS/rubygem-timers/rubygem-timers.spec
  cgmanifest.json
Labels: Azure Linux 3.0

#7211 fix: upgrade cloud-init to v23.4.1 and add patch to retain exit code for recoverable errors
  SPECS/cloud-init/Retain-exit-code-in-cloud-init-status-for-recoverabl.patch
  SPECS/cloud-init/cloud-init.signatures.json
  SPECS/cloud-init/cloud-init.spec
  SPECS/cloud-init/overrideDatasourceDetection.patch
  cgmanifest.json
Labels: main

#7363 kpatch: upgrade version 0.9.7 -> 0.9.8
  SPECS/kpatch/kpatch.signatures.json
  SPECS/kpatch/kpatch.spec
  cgmanifest.json
Labels: 3.0

#7496 Add shadow-utils as a hard dependency for mysql package
  SPECS/mysql/mysql.spec
Labels: main

#7436 Upgrade sscg from 2.6.2 to 3.0.5
  SPECS/sscg/sscg.signatures.json
  SPECS/sscg/sscg.spec
  cgmanifest.json
Labels: 3.0

#7109 Move hiera from Extended to Core
  SPECS/hiera/fix-puppetlab-paths.patch
  SPECS/hiera/hiera.signatures.json
  SPECS/hiera/hiera.spec
Labels: main

#7458 Upgrade byacc package to latest version
  SPECS/byacc/byacc.signatures.json
  SPECS/byacc/byacc.spec
  cgmanifest.json
Labels: 3.0

#7483 Update dracut to allow supressing user confirmation prompt when the liveos overlay is backed by memory.
  SPECS/dracut/allow-liveos-overlay-no-user-confirmation-prompt.patch
  SPECS/dracut/dracut.spec
Labels: main

#7465 #6996 port: Added a cross-compilation subpackage for aarch64 into gcc.
  SPECS/gcc/gcc.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
Labels: 3.0

#7495 Upgraded `ruby` to 3.3.0.
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/ruby/CVE-2023-36617.patch
  SPECS/ruby/ruby.signatures.json
  SPECS/ruby/ruby.spec
  SPECS/rubygem-bigdecimal/rubygem-bigdecimal.signatures.json
  SPECS/rubygem-bigdecimal/rubygem-bigdecimal.spec
  cgmanifest.json
Labels: 3.0

#7484 Upgrading `numpy` to 1.26.3
  SPECS/numpy/numpy.signatures.json
  SPECS/numpy/numpy.spec
  SPECS/numpy/test_fix.patch
  cgmanifest.json
Labels: 3.0

#7497 fix architecture naming scheme for daily builds in the toolkit make file
  toolkit/Makefile
Labels: 3.0

#7057 Upgrade glusterfs from 7.9 to 11.1
  SPECS/glusterfs/glusterfs.signatures.json
  SPECS/glusterfs/glusterfs.spec
  SPECS/glusterfs/include-eventtypes-always.patch
  cgmanifest.json
Labels: 3.0

#7378 Create NEW package for mariner 3.0: libtpms
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/libtpms/gpgkey-B818B9CADF9089C2D5CEC66B75AD65802A0B4211.asc
  SPECS/libtpms/libtpms-0.9.6.tar.gz.asc
  SPECS/libtpms/libtpms.signatures.json
  SPECS/libtpms/libtpms.spec
  cgmanifest.json
Labels: 3.0

#7531 upgrade harfbuzz
  SPECS/harfbuzz/CVE-2023-25193.patch
  SPECS/harfbuzz/harfbuzz.signatures.json
  SPECS/harfbuzz/harfbuzz.spec
  cgmanifest.json
Labels: 3.0

#7517 Upgrade libXext to 1.3.5
  SPECS/libXext/libXext.signatures.json
  SPECS/libXext/libXext.spec
  cgmanifest.json
Labels: 3.0

#7412 libxkbfile: upgrade from 1.1.0 to 1.1.2
  SPECS/libxkbfile/libxkbfile.signatures.json
  SPECS/libxkbfile/libxkbfile.spec
  cgmanifest.json
Labels: 3.0

#7534 containerized-build: avoid failure if lkg file does not exist
  toolkit/scripts/containerized-build/create_container_build.sh
Labels: 3.0

#7528 Updated `async` and `async-http` Ruby gems.
  SPECS/ruby/macros.rubygems
  SPECS/ruby/ruby.signatures.json
  SPECS/ruby/ruby.spec
  SPECS/rubygem-async-http/rubygem-async-http.signatures.json
  SPECS/rubygem-async-http/rubygem-async-http.spec
  SPECS/rubygem-async/rubygem-async.signatures.json
  SPECS/rubygem-async/rubygem-async.spec
  SPECS/rubygem-protocol-http/rubygem-protocol-http.spec
  SPECS/rubygem-timers/rubygem-timers.spec
  cgmanifest.json
Labels: 3.0
