Repository microsoft/azurelinux, pull requests merged in 2024-10, with the labels that each got.

#10586 Fixed spec entanglement PR check (CP: #10585)
  toolkit/scripts/check_entangled_specs.py
Labels: Tools, main

#10579 Add Valkey to 3.0
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS/valkey/valkey-conf.patch
  SPECS/valkey/valkey.signatures.json
  SPECS/valkey/valkey.spec
  cgmanifest.json
Labels: 3.0-dev

#10587 Fixed `tdnf provides` parsing to recognize epochs in package names.
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
  toolkit/tools/internal/tdnf/tdnf.go
  toolkit/tools/internal/tdnf/tdnf_test.go
Labels: Tools

#10597 Enable iptables by default
  SPECS/azurelinux-release/90-default.preset
  SPECS/azurelinux-release/azurelinux-release.signatures.json
  SPECS/azurelinux-release/azurelinux-release.spec
Labels: Packaging

#10592 Saulparedes/kata spec rebuild squash m3 pr
  SPECS/kata-containers-cc/kata-containers-cc.signatures.json
  SPECS/kata-containers-cc/kata-containers-cc.spec
  SPECS/kata-containers/kata-containers.signatures.json
Labels: Packaging

#10588 heimdal: Add backported patch for fixing CVE-2022-3116
  SPECS/heimdal/CVE-2022-3116.patch
  SPECS/heimdal/heimdal.spec
Labels: Packaging

#10611 use build type RelWithDebInfo to generate debug info with sources
  SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.spec
Labels: Packaging

#10591 Enable check section in python-platformdirs
  SPECS/python-platformdirs/python-platformdirs.spec
Labels: Packaging

#10548 Prepare October 2024 Update
  SPECS/mariner-release/mariner-release.spec
Labels: Packaging, main

#10520 minimal-os image definition.
  toolkit/imageconfigs/minimal-os.json
  toolkit/imageconfigs/packagelists/minimal-os-packages.json
Labels: Schema

#10629 Fixed toolkit's handling of RPMs with epoch values in their name
  toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
  toolkit/tools/internal/rpm/rpm.go
  toolkit/tools/internal/rpm/rpm_test.go
  toolkit/tools/scheduler/schedulerutils/preparerequest.go
Labels: Tools

#10638 Build Break: Bump dracut to rebuild with latest systemd
  SPECS/dracut/dracut.spec
Labels: Packaging

#10642 add fix for CVE-2023-48795 in kubevirt
  SPECS/kubevirt/CVE-2023-48795.patch
  SPECS/kubevirt/kubevirt.spec
Labels: Packaging

#10582 Add stable release maintainers to CODEOWNERS
  .github/CODEOWNERS
Labels: 3.0-dev

#10627 Fix CVE-2024-47191 against oath-toolkit
  SPECS/oath-toolkit/CVE-2024-47191.patch
  SPECS/oath-toolkit/oath-toolkit-2.6.9-lockfile.patch
  SPECS/oath-toolkit/oath-toolkit.spec
Labels: Packaging

#10628 Fix CVE-2024-47191 in oath-toolkit
  SPECS/oath-toolkit/CVE-2024-47191.patch
  SPECS/oath-toolkit/oath-toolkit.spec
Labels: Packaging

#10596 Resolve CVE-2024-28180 for dcos-cli and kubernetes
  SPECS/dcos-cli/CVE-2024-28180.patch
  SPECS/dcos-cli/dcos-cli.spec
  SPECS/kubernetes/CVE-2024-28180.patch
  SPECS/kubernetes/kubernetes.spec
Labels: Packaging

#10623 Resolve CVE-2024-31852 for libcxx
  SPECS/libcxx/CVE-2024-31852.patch
  SPECS/libcxx/libcxx.spec
Labels: security, Packaging, 3.0-dev

#10528 Update nvidia repo instructions with the appropriate 3.0 repofile
  toolkit/docs/nvidia/nvidia.md
Labels: documentation, 3.0-dev

#10636 Upgrade nvidia-container-toolkit to fix CVE-2024-0132 CVE-2024-0133
  SPECS/libnvidia-container/common.mk.patch
  SPECS/libnvidia-container/libnvidia-container.signatures.json
  SPECS/libnvidia-container/libnvidia-container.spec
  SPECS/libnvidia-container/libtirpc.patch
  SPECS/libnvidia-container/nvidia-modprobe.patch
  SPECS/nvidia-container-toolkit/nvidia-container-toolkit.signatures.json
  SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec
  cgmanifest.json
Labels: security, fasttrack/3.0

#10661 Disable liblastlog2 for util-linux in raw toolchain build
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
Labels: bug, Tools, 3.0

#10557 Patch CVE-2024-45590 in reaper
  SPECS/reaper/CVE-2024-45590.patch
  SPECS/reaper/reaper.spec
Labels: security, Packaging, main

#10666 Patch unbound to fix CVE-2024-33655, CVE-2024-8508, and CVE-2024-43167
  SPECS/unbound/CVE-2024-33655.patch
  SPECS/unbound/CVE-2024-43167.patch
  SPECS/unbound/CVE-2024-8508.patch
  SPECS/unbound/unbound.spec
Labels: Packaging

#10608 ImageCustomizer - Service and Overlay recommendations for Verity-enabled images.
  toolkit/tools/imagecustomizer/docs/configuration.md
  toolkit/tools/imagecustomizer/docs/verity.md
Labels: Tools

#10676 Cherrypick #10661: Disable liblastlog2 for util-linux in raw toolchain build
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
Labels: Tools

#10662 Generate log files for raw toolchain builds
  toolkit/scripts/toolchain.mk
  toolkit/scripts/toolchain/create_toolchain_in_container.sh
Labels: Tools, DevEx, 3.0-dev

#10334 gh: address CVE-2022-32149
  SPECS/gh/CVE-2022-32149.patch
  SPECS/gh/gh.spec
Labels: security, Packaging, main

#10665 Patch unbound to fix CVE-2024-43167 and CVE-2024-8508
  SPECS/unbound/CVE-2024-43167.patch
  SPECS/unbound/CVE-2024-8508.patch
  SPECS/unbound/unbound.spec
Labels: Packaging

#10719 Upgrade OpenIPMI to 2.0.36 to fix CVE-2024-42934
  SPECS/OpenIPMI/OpenIPMI.signatures.json
  SPECS/OpenIPMI/OpenIPMI.spec
  cgmanifest.json
Labels: security, 3.0-dev

#10698 Patch CVE-2022-28506 and CVE-2023-48161 in giflib
  SPECS/giflib/CVE-2022-28506.patch
  SPECS/giflib/CVE-2023-48161.patch
  SPECS/giflib/giflib.spec
Labels: security, Packaging

#10667 [2.0] Resolve dcos-cli CVE-2024-28180
  SPECS/dcos-cli/CVE-2024-28180.patch
  SPECS/dcos-cli/dcos-cli.spec
Labels: Packaging, main

#10668 [2.0] Resolve kubernetes CVE-2024-28180
  SPECS/kubernetes/CVE-2024-28180.patch
  SPECS/kubernetes/kubernetes.spec
Labels: Packaging, main

#10713 Patch python-gevent to resolve CVE-2024-25629
  SPECS/python-gevent/CVE-2024-25629.patch
  SPECS/python-gevent/python-gevent.spec
Labels: Packaging

#10689 Patch cni-plugins to resolve CVE-2023-3978
  SPECS/cni-plugins/CVE-2023-3978.patch
  SPECS/cni-plugins/cni-plugins.spec
Labels: Packaging, main

#10686 Patch influxdb to resolve CVE-2023-45288
  SPECS/influxdb/CVE-2023-45288.patch
  SPECS/influxdb/influxdb.spec
Labels: Packaging

#10708 Fix CVE-2024-47554 for apache-commons-io
  SPECS-EXTENDED/apache-commons-io/apache-commons-io-build.xml
  SPECS-EXTENDED/apache-commons-io/apache-commons-io.signatures.json
  SPECS-EXTENDED/apache-commons-io/apache-commons-io.spec
  SPECS-EXTENDED/apache-commons-io/commons-io-2.14.0-src.tar.gz.asc
  SPECS-EXTENDED/apache-commons-io/commons-io-2.8.0-src.tar.gz.asc
  cgmanifest.json
Labels: security, main

#10688 Patch CVE-2024-31449 in redis
  SPECS/redis/CVE-2024-31449.patch
  SPECS/redis/redis.spec
Labels: Packaging

#10694 Patch CVE-2022-28506 and CVE-2023-48161 in giflib
  SPECS/giflib/CVE-2022-28506.patch
  SPECS/giflib/CVE-2023-48161.patch
  SPECS/giflib/giflib.spec
Labels: security, Packaging

#10710 Upgrade OpenIPMI to 2.0.36 to fix CVE-2024-42934
  SPECS/OpenIPMI/OpenIPMI.signatures.json
  SPECS/OpenIPMI/OpenIPMI.spec
  cgmanifest.json
Labels: security, fasttrack/2.0

#10720 Patch Reaper for multiple CVEs
  SPECS/reaper/CVE-2024-43799.patch
  SPECS/reaper/CVE-2024-43800.patch
  SPECS/reaper/CVE-2024-45296.patch
  SPECS/reaper/CVE-2024-47764.patch
  SPECS/reaper/CVE-2024-48949.patch
  SPECS/reaper/reaper.spec
Labels: security, Packaging, fasttrack/2.0

#10705 Image Customizer: Move `resetPartitionsUuidsType` into `storage`.
  toolkit/tools/imagecustomizer/docs/configuration.md
  toolkit/tools/imagecustomizerapi/boottype.go
  toolkit/tools/imagecustomizerapi/config.go
  toolkit/tools/imagecustomizerapi/config_test.go
  toolkit/tools/imagecustomizerapi/partition.go
  toolkit/tools/imagecustomizerapi/storage.go
  toolkit/tools/imagecustomizerapi/storage_test.go
  toolkit/tools/pkg/imagecustomizerlib/customizebootloader.go
  toolkit/tools/pkg/imagecustomizerlib/customizeos.go
  toolkit/tools/pkg/imagecustomizerlib/customizepartitions.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
  toolkit/tools/pkg/imagecustomizerlib/testdata/newpartitionsuuids-config.yaml
Labels: Tools

#10657 Fix `pytest` so that it's actually usable.
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS/pytest/pytest.spec
  SPECS/python-iniconfig/python-iniconfig.signatures.json
  SPECS/python-iniconfig/python-iniconfig.spec
  cgmanifest.json
Labels: 3.0-dev, stable-release-shiproom

#10756 Change rm to use find to avoid deleting cache directory during snapshot cleanup
  toolkit/scripts/imggen.mk
  toolkit/scripts/pkggen.mk
Labels: Tools

#10598 MIC should clean-up cache and any system files after run
  toolkit/tools/pkg/imagecustomizerlib/customizepackages.go
  toolkit/tools/pkg/imagecustomizerlib/customizepackages_test.go
Labels: Tools

#10680 Patch vim to resolve CVE-2024-43802
  SPECS/vim/CVE-2024-43802.patch
  SPECS/vim/vim.spec
Labels: Packaging, fasttrack/2.0

#10681 Patch vim to resolve CVE-2024-43802
  SPECS/vim/CVE-2024-43802.patch
  SPECS/vim/vim.spec
Labels: security, Packaging, fasttrack/3.0

#10723 add SymCrypt-debuginfo package
  SPECS/SymCrypt/0001-add-build-flags-to-prevent-stripping-and-post-proces.patch
  SPECS/SymCrypt/0001-add-parameter-to-process_fips_module-to-specify-the-.patch
  SPECS/SymCrypt/SymCrypt.signatures.json
  SPECS/SymCrypt/SymCrypt.spec
  SPECS/SymCrypt/find-debuginfo
Labels: Packaging, stable-release-shiproom, fasttrack/3.0

#10669 [2.0] Resolve kubernetes CVE-2024-24786
  SPECS/kubernetes/CVE-2024-24786.patch
  SPECS/kubernetes/kubernetes.spec
Labels: Packaging, main

#10743 [mic][iso] Save input ISO configuration as yaml
  toolkit/tools/imagecustomizerapi/utils.go
  toolkit/tools/pkg/imagecustomizerlib/liveosisobuilder.go
  toolkit/tools/pkg/imagecustomizerlib/liveosisobuilder_test.go
  toolkit/tools/pkg/imagecustomizerlib/savedconfigs.go
Labels: Tools

#10786 iptables: Enable nftables
  SPECS/ebtables/ebtables.spec
  SPECS/iptables/iptables.spec
Labels: Packaging, 3.0-dev, stable-release-shiproom

#10739 fluent-bit: CVE-2024-26455, CVE-2024-25629
  SPECS/fluent-bit/CVE-2024-25629.patch
  SPECS/fluent-bit/CVE-2024-26455.patch
  SPECS/fluent-bit/fluent-bit.spec
Labels: Packaging, main

#10742 fluent-bit: CVE-2024-34250, CVE-2024-25629, CVE-2024-28182
  SPECS/fluent-bit/CVE-2024-25629.patch
  SPECS/fluent-bit/CVE-2024-28182.patch
  SPECS/fluent-bit/CVE-2024-34250.patch
  SPECS/fluent-bit/fluent-bit.spec
Labels: Packaging

#10800 Added directory check before cleaning-up the RPM caches.
  toolkit/scripts/imggen.mk
  toolkit/scripts/pkggen.mk
Labels: Tools

#10798 Upgrade redis to 6.2.16
  SPECS/redis/CVE-2024-31449.patch
  SPECS/redis/redis.signatures.json
  SPECS/redis/redis.spec
  cgmanifest.json
Labels: main

#10793 libpcap: Backport fixes for CVE-2024-8006
  SPECS/libpcap/CVE-2024-8006.patch
  SPECS/libpcap/libpcap.spec
Labels: Packaging, main

#10682 rubygem-async-http: remove version dependency of rubygem-protocol-http1
  SPECS/rubygem-async-http/remove-http-protocol1-dep.patch
  SPECS/rubygem-async-http/rubygem-async-http.spec
Labels: Packaging, main

#10747 php: upgrade to 8.3.12 to fix CVE-2024-8927, CVE-2024-8925
  SPECS/php/CVE-test.patch
  SPECS/php/php-8.3.12-systzdata-v25.patch
  SPECS/php/php.signatures.json
  SPECS/php/php.spec
  cgmanifest.json
Labels: Packaging

#10778 clamav: upgrade 1.0.6 -> 1.0.7
  SPECS/clamav/clamav.signatures.json
  SPECS/clamav/clamav.spec
  cgmanifest.json
Labels: security, 3.0-dev

#10774 Upgrade mysql to 8.0.40
  SPECS/mysql/CVE-2023-46218.patch
  SPECS/mysql/mysql.signatures.json
  SPECS/mysql/mysql.spec
  cgmanifest.json
Labels: fasttrack/2.0

#10684 Patch gdb 13.2 for CVE-2023-39128, CVE-2023-39129, CVE-2023-39130
  SPECS/gdb/CVE-2023-39128.patch
  SPECS/gdb/CVE-2023-39129.patch
  SPECS/gdb/CVE-2023-39130.patch
  SPECS/gdb/gdb.spec
Labels: Packaging, 3.0-dev

#10683 Patch gdb 11.2 for CVE-2023-39128, CVE-2023-39129, CVE-2023-39130
  SPECS/gdb/CVE-2023-39128.patch
  SPECS/gdb/CVE-2023-39129.patch
  SPECS/gdb/CVE-2023-39130.patch
  SPECS/gdb/gdb.spec
Labels: Packaging, main

#10729 curl: address CVE-2024-8096
  SPECS/curl/CVE-2024-8096.patch
  SPECS/curl/curl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, 3.0-dev

#10750 apr: upgrade version 1.7.4 -> 1.7.5 to address CVE-2023-49582
  SPECS/apr/apr.signatures.json
  SPECS/apr/apr.spec
  SPECS/apr/skip-known-test-failure.patch
  cgmanifest.json
Labels: security, 3.0-dev

#10749 apr: upgrade version 1.7.2 -> 1.7.5 to address CVE-2023-49582
  SPECS/apr/apr.signatures.json
  SPECS/apr/apr.spec
  SPECS/apr/skip-known-test-failure.patch
  cgmanifest.json
Labels: security, main

#10578 gnutls: upgrade 3.7.7 -> 3.7.11 to address CVE-2023-5981, CVE-2024-28835, CVE-2024-28834 & CVE-2024-0553
  SPECS/gnutls/gnutls.signatures.json
  SPECS/gnutls/gnutls.spec
  cgmanifest.json
Labels: security, main

#10656 nghttp2: address CVE-2024-28182
  SPECS/nghttp2/CVE-2024-28182.patch
  SPECS/nghttp2/nghttp2.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, main

#10731 curl: address CVE-2024-8096
  SPECS/curl/CVE-2024-8096.patch
  SPECS/curl/curl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, main

#10797 Upgrade libpcap version to 1.10.5 to fix CVE-2024-8006
  SPECS/libpcap/libpcap.signatures.json
  SPECS/libpcap/libpcap.spec
  cgmanifest.json
Labels: security, Packaging, 3.0-dev

#10808 Enable x86_amd_platform_device builtin
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS-SIGNED/kernel-uki-signed/kernel-uki-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/kernel-uki.spec
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 3.0-dev, stable-release-shiproom

#10817 Enable Intel IFS
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS-SIGNED/kernel-uki-signed/kernel-uki-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/kernel-uki.spec
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 3.0-dev

#10825 Remove Amateur Radio X.25 PLP Rose for CVE-2022-2961
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS-SIGNED/kernel-uki-signed/kernel-uki-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel-uki.spec
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 3.0-dev

#10827 Added Patch CVE-2022-25255 for qt5-qtbase
  SPECS/qt5-qtbase/CVE-2022-25255.patch
  SPECS/qt5-qtbase/qt5-qtbase.spec
Labels: Packaging

#10826 Remove Amateur Radio X.25 PLP Rose for CVE-2022-2961
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#10840 Add missing patch to fasttrack/2.0 from main
  SPECS/reaper/CVE-2024-45590.patch
Labels: security, Packaging

#10804 Toolkit: Add missing `flock` calls.
  toolkit/tools/imagegen/diskutils/diskutils.go
  toolkit/tools/pkg/imagecustomizerlib/shrinkfilesystems.go
Labels: Tools, 3.0-dev

#10849 kata-containers: only build for x86_64
  SPECS/kata-containers/kata-containers.spec
Labels: Packaging

#10789 Image Customizer: Make verity API a list.
  toolkit/tools/imagecustomizerapi/config.go
  toolkit/tools/imagecustomizerapi/config_test.go
  toolkit/tools/imagecustomizerapi/filesystem.go
  toolkit/tools/imagecustomizerapi/identifiedpartition.go
  toolkit/tools/imagecustomizerapi/identifiedpartition_test.go
  toolkit/tools/imagecustomizerapi/os.go
  toolkit/tools/imagecustomizerapi/os_test.go
  toolkit/tools/imagecustomizerapi/storage.go
  toolkit/tools/imagecustomizerapi/storage_test.go
  toolkit/tools/imagecustomizerapi/verity.go
  toolkit/tools/imagecustomizerapi/verity_test.go
  toolkit/tools/pkg/imagecustomizerlib/bootcustomizer.go
  toolkit/tools/pkg/imagecustomizerlib/customizeos.go
  toolkit/tools/pkg/imagecustomizerlib/customizeverity.go
  toolkit/tools/pkg/imagecustomizerlib/customizeverity_test.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
  toolkit/tools/pkg/imagecustomizerlib/partitionutils.go
  toolkit/tools/pkg/imagecustomizerlib/shrinkfilesystems.go
  toolkit/tools/pkg/imagecustomizerlib/testdata/verity-config.yaml
  toolkit/tools/pkg/imagecustomizerlib/testdata/verity-partition-labels.yaml
  toolkit/tools/pkg/imagecustomizerlib/typeConversion.go
Labels: Tools

#10693 dracut: make tpm2-tss an optional dependency of systemd-pcrphase
  SPECS/dracut/0014-fix-systemd-pcrphase-in-hostonly-mode-do-not-try-to-include-systemd-pcrphase.patch
  SPECS/dracut/0015-fix-systemd-pcrphase-make-tpm2-tss-an-optional-dependency.patch
  SPECS/dracut/dracut.spec
Labels: Packaging

#10851 kernel-mshv: Increase build verbosity
  SPECS/kernel-mshv/kernel-mshv.spec
Labels: Packaging

#10777 Upgraded vim to 9.1.0791 to fix several CVEs
  SPECS/vim/CVE-2024-22667.patch
  SPECS/vim/CVE-2024-41957.patch
  SPECS/vim/CVE-2024-41965.patch
  SPECS/vim/CVE-2024-43374.patch
  SPECS/vim/CVE-2024-43802.patch
  SPECS/vim/vim.signatures.json
  SPECS/vim/vim.spec
  cgmanifest.json
Labels: main

#10866 3.0: kata-containers: only build for x86_64 (#10849)
  SPECS/kata-containers/kata-containers.spec
Labels: Packaging

#10862 Image Customizer: Support string mountPoint
  toolkit/tools/imagecustomizer/docs/configuration.md
  toolkit/tools/imagecustomizerapi/mountpoint.go
Labels: Tools

#10885 Image Customizer: Fix ISO customization.
  toolkit/tools/pkg/imagecustomizerlib/liveosisobuilder.go
Labels: Tools

#10852 Image Customizer: Fix verity docs.
  toolkit/tools/imagecustomizer/docs/configuration.md
  toolkit/tools/imagecustomizer/docs/verity.md
Labels: Tools

#10880 Image Customizer: Set VHDX block-size to 2 MiB.
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
Labels: Tools

#10814 Revert "iptables: Enable nftables (#10786)"
  SPECS/ebtables/ebtables.spec
  SPECS/iptables/iptables.spec
Labels: Packaging

#10877 Switched `mysql` to use AZL's version of `protobuf` to fix CVE-2024-2410.
  SPECS/mysql/fix-tests-for-unsupported-chacha-ciphers.patch
  SPECS/mysql/mysql.spec
Labels: Packaging

#10882 Avahi: Fix CVE-2023-1981, add %check section
  SPECS/avahi/CVE-2023-1981.patch
  SPECS/avahi/avahi.spec
Labels: security, Packaging, ptest, 3.0-dev

#10881 Avahi: Fix CVE-2023-1981, add %check section
  SPECS/avahi/CVE-2023-1981.patch
  SPECS/avahi/avahi.spec
Labels: security, Packaging, ptest, main

#10897 Image Customizer: Fix partition creation on Ubuntu build hosts.
  toolkit/tools/pkg/imagecustomizerlib/imageutils.go
  toolkit/tools/pkg/imagecustomizerlib/partitionutils.go
  toolkit/tools/pkg/imagecustomizerlib/shrinkfilesystems.go
Labels: Tools

#10865 fix: add fedora SBAT entries to grub2
  SPECS-SIGNED/grub2-efi-binary-signed/grub2-efi-binary-signed.spec
  SPECS/grub2/grub2.signatures.json
  SPECS/grub2/grub2.spec
  SPECS/grub2/sbat.csv.in
Labels: Packaging

#10901 Revert "Image Customizer: Fix partition creation on Ubuntu build hosts."
  toolkit/tools/pkg/imagecustomizerlib/imageutils.go
  toolkit/tools/pkg/imagecustomizerlib/partitionutils.go
  toolkit/tools/pkg/imagecustomizerlib/shrinkfilesystems.go
Labels: Tools

#10902 Image Customizer: Fix partition creation on Ubuntu build hosts.
  toolkit/tools/pkg/imagecustomizerlib/imageutils.go
  toolkit/tools/pkg/imagecustomizerlib/partitionutils.go
  toolkit/tools/pkg/imagecustomizerlib/shrinkfilesystems.go
Labels: Tools
