Repository microsoft/azurelinux, pull requests merged in 2024-02, with the labels that each got.

#7587 Add dracut sub-package overlayfs. (#7432)
  SPECS/dracut/20overlayfs/module-setup.sh
  SPECS/dracut/20overlayfs/overlayfs-mount.sh
  SPECS/dracut/dracut.signatures.json
  SPECS/dracut/dracut.spec
Labels: main

#7481 Upgrade sg3_utils from 1.46 to 1.48
  SPECS/sg3_utils/sg3_utils.signatures.json
  SPECS/sg3_utils/sg3_utils.spec
  cgmanifest.json
Labels: 3.0

#7567 Upgrade tcsh to 6.24.10
  SPECS/tcsh/tcsh.signatures.json
  SPECS/tcsh/tcsh.spec
  cgmanifest.json
Labels: 3.0

#7607 hunspell-en: Upgrade to version 0.20201207
  SPECS/hunspell-en/hunspell-en-GB-LICENSE.txt
  SPECS/hunspell-en/hunspell-en-SI_and_IEC.patch
  SPECS/hunspell-en/hunspell-en-US-LICENSE.txt
  SPECS/hunspell-en/hunspell-en-buildfix.patch
  SPECS/hunspell-en/hunspell-en-calender.patch
  SPECS/hunspell-en/hunspell-en-fixbuild.patch
  SPECS/hunspell-en/hunspell-en.signatures.json
  SPECS/hunspell-en/hunspell-en.spec
  SPECS/hunspell-en/mozilla_words.patch
  SPECS/hunspell-en/perl.regex.patch
  cgmanifest.json
Labels: 3.0

#7609 intel-ipsec-mb: Upgrade to version 1.5.0
  SPECS/intel-ipsec-mb/intel-ipsec-mb.signatures.json
  SPECS/intel-ipsec-mb/intel-ipsec-mb.spec
  cgmanifest.json
Labels: 3.0

#7589 Address llvm and clang pTest and fix compiler-rt issues
  SPECS/clang/clang.spec
  SPECS/compiler-rt/compiler-rt.spec
  SPECS/llvm/llvm.spec
Labels: 3.0

#7585 systemd: do not conflict with polkit dir
  SPECS/systemd/systemd.spec
Labels: 3.0

#7560 rpm: upgrade to 4.18.1
  SPECS/rpm/define-RPM_LD_FLAGS.patch
  SPECS/rpm/rpm.signatures.json
  SPECS/rpm/rpm.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/toolchain-remote-wget-list
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
Labels: 3.0

#7581 fix cve-2022-21698 in moby-buildx
  SPECS/moby-buildx/CVE-2022-21698.patch
  SPECS/moby-buildx/moby-buildx.spec
Labels: security, fasttrack/2.0

#7575 fix cve-2022-21698 in local-path-provisioner
  SPECS/local-path-provisioner/CVE-2022-21698.patch
  SPECS/local-path-provisioner/local-path-provisioner.spec
Labels: security, fasttrack/2.0

#7524 Fix coredns CVE-2023-44487 by patching vendor tar
  SPECS/coredns/CVE-2023-44487.patch
  SPECS/coredns/coredns.signatures.json
  SPECS/coredns/coredns.spec
Labels: security, fasttrack/2.0

#7601 nbd: upgrade to 3.25
  SPECS/nbd/nbd.signatures.json
  SPECS/nbd/nbd.spec
  cgmanifest.json
Labels: 3.0

#7611 xorg-x11-util-macros: Upgrade to version 1.20.0
  SPECS/xorg-x11-util-macros/xorg-x11-util-macros.signatures.json
  SPECS/xorg-x11-util-macros/xorg-x11-util-macros.spec
  cgmanifest.json
Labels: 3.0

#7635 xorg-x11-xtrans-devel: Upgrade to version 1.5.0
  SPECS/xorg-x11-xtrans-devel/xorg-x11-xtrans-devel.signatures.json
  SPECS/xorg-x11-xtrans-devel/xorg-x11-xtrans-devel.spec
  cgmanifest.json
Labels: 3.0

#7604 Upgrade libedit to 3.1.20230828
  SPECS/libedit/libedit.signatures.json
  SPECS/libedit/libedit.spec
  cgmanifest.json
Labels: 3.0

#6649 Sort, reorder and color build summary output
  toolkit/Makefile
  toolkit/docs/building/building.md
  toolkit/scripts/chroot.mk
  toolkit/scripts/imggen.mk
  toolkit/scripts/pkggen.mk
  toolkit/scripts/precache.mk
  toolkit/scripts/repoquerywrapper.mk
  toolkit/scripts/srpm_pack.mk
  toolkit/scripts/toolkit.mk
  toolkit/tools/bldtracker/bldtracker.go
  toolkit/tools/boilerplate/boilerplate.go
  toolkit/tools/depsearch/depsearch.go
  toolkit/tools/downloader/downloader.go
  toolkit/tools/go.mod
  toolkit/tools/go.sum
  toolkit/tools/graphPreprocessor/graphPreprocessor.go
  toolkit/tools/graphanalytics/graphanalytics.go
  toolkit/tools/grapher/grapher.go
  toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
  toolkit/tools/imageconfigvalidator/imageconfigvalidator.go
  toolkit/tools/imagecustomizer/main.go
  toolkit/tools/imagepkgfetcher/imagepkgfetcher.go
  toolkit/tools/imager/imager.go
  toolkit/tools/internal/exe/exe.go
  toolkit/tools/internal/logger/log.go
  toolkit/tools/internal/logger/writerhook.go
  toolkit/tools/internal/sliceutils/sliceutils.go
  toolkit/tools/internal/sliceutils/sliceutils_test.go
  toolkit/tools/isomaker/isomaker.go
  toolkit/tools/liveinstaller/liveinstaller.go
  toolkit/tools/osmodifier/main.go
  toolkit/tools/pkgworker/pkgworker.go
  toolkit/tools/precacher/precacher.go
  toolkit/tools/repoquerywrapper/repoquerywrapper.go
  toolkit/tools/roast/roast.go
  toolkit/tools/rpmssnapshot/rpmssnapshot.go
  toolkit/tools/scheduler/scheduler.go
  toolkit/tools/scheduler/schedulerutils/buildworker.go
  toolkit/tools/scheduler/schedulerutils/printresults.go
  toolkit/tools/specarchchecker/specarchchecker.go
  toolkit/tools/specreader/specreader.go
  toolkit/tools/srpmpacker/srpmpacker.go
  toolkit/tools/validatechroot/validatechroot.go
Labels: main

#7492 Image Customizer: Add support for SELinux
  toolkit/tools/imageconfigvalidator/imageconfigvalidator.go
  toolkit/tools/imagecustomizer/docs/configuration.md
  toolkit/tools/imagecustomizerapi/kernelcommandline.go
  toolkit/tools/imagecustomizerapi/selinux.go
  toolkit/tools/imagegen/configuration/kernelcommandline.go
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/imager/imager.go
  toolkit/tools/internal/file/file.go
  toolkit/tools/internal/safechroot/safechroot.go
  toolkit/tools/pkg/imagecustomizerlib/customizeboot.go
  toolkit/tools/pkg/imagecustomizerlib/customizepartitionsfilecopy.go
  toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
  toolkit/tools/pkg/imagecustomizerlib/imageutils.go
  toolkit/tools/pkg/imagecustomizerlib/partitionutils.go
  toolkit/tools/pkg/imagecustomizerlib/testdata/selinux-disabled.yaml
  toolkit/tools/pkg/imagecustomizerlib/testdata/selinux-enforcing.yaml
  toolkit/tools/pkg/imagecustomizerlib/testdata/selinux-force-enforcing.yaml
  toolkit/tools/pkg/imagecustomizerlib/testdata/selinux-permissive.yaml
  toolkit/tools/pkg/imagecustomizerlib/typeConversion.go
  toolkit/tools/pkg/isomakerlib/isomaker.go
Labels: 3.0

#7490 SymCrypt provider initial integration
  SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.signatures.json
  SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.spec
  SPECS/SymCrypt/SymCrypt.signatures.json
  SPECS/SymCrypt/SymCrypt.spec
  SPECS/openssl/0009-Add-Kernel-FIPS-mode-flag-support.patch
  SPECS/openssl/0032-Force-fips.patch
  SPECS/openssl/openssl.spec
  cgmanifest.json
Labels: 3.0

#7636 xorg-x11-xbitmaps: Upgrade to version 1.1.3
  SPECS/xorg-x11-xbitmaps/xorg-x11-xbitmaps.signatures.json
  SPECS/xorg-x11-xbitmaps/xorg-x11-xbitmaps.spec
  cgmanifest.json
Labels: 3.0

#7670 upgrade open-vm-tools to 12.3.5 for 3.0
  SPECS/open-vm-tools/open-vm-tools.signatures.json
  SPECS/open-vm-tools/open-vm-tools.spec
  cgmanifest.json
Labels: 3.0

#7444 [3.0][ConfPods] Remove linuxloader-related logic from initramfs %file_trigger_action
  SPECS/initramfs/initramfs.spec
Labels: 3.0

#7603 quota: upgrade to 4.09
  SPECS/quota/quota-4.06-Drop-sys-cdefs.h-usage.patch
  SPECS/quota/quota-4.06-common.c-fix-strncat-usage.patch
  SPECS/quota/quota-4.06-quota_nld-Initialize-sa_mask-when-registering-PID-fi.patch
  SPECS/quota/quota-4.06-quotacheck-Remove-a-dead-code-from-process_file.patch
  SPECS/quota/quota-4.06-quotacheck-quotaon-Always-display-message-about-depr.patch
  SPECS/quota/quota-4.06-quotaio_xfs-Warn-when-large-kernel-timestamps-cannot.patch
  SPECS/quota/quota-4.06-quotaops-fix-compilation-warning.patch
  SPECS/quota/quota-4.06-quotasys.c-fix-strncpy-usage.patch
  SPECS/quota/quota.signatures.json
  SPECS/quota/quota.spec
  cgmanifest.json
Labels: 3.0

#7530 Upgrade: cairo from 1.17.4 to 1.18.0
  SPECS/cairo/cairo.signatures.json
  SPECS/cairo/cairo.spec
  cgmanifest.json
Labels: 3.0

#7659 [3.0] Upgrade syslog-ng, PyYaml and python-oauthlib
  SPECS/PyYAML/PyYAML.signatures.json
  SPECS/PyYAML/PyYAML.spec
  SPECS/python-oauthlib/python-oauthlib.signatures.json
  SPECS/python-oauthlib/python-oauthlib.spec
  SPECS/syslog-ng/remove-hardcoded-python-module-versioning.patch
  SPECS/syslog-ng/syslog-ng.signatures.json
  SPECS/syslog-ng/syslog-ng.spec
  cgmanifest.json
Labels: 3.0

#7553 Update sos to 4.6.1
  SPECS/sos/bump-version-4-6-1.patch
  SPECS/sos/sos.signatures.json
  SPECS/sos/sos.spec
  cgmanifest.json
Labels: main

#7646 fix cve-2022-21698 in moby-cli
  SPECS/moby-cli/CVE-2022-21698.patch
  SPECS/moby-cli/moby-cli.spec
Labels: security, fasttrack/2.0

#7588 munge: upgrade to 0.5.15
  SPECS/munge/munge.signatures.json
  SPECS/munge/munge.spec
  cgmanifest.json
Labels: 3.0

#7569 msft-golang: upgrade version 1.20.11 -> 1.21.6
  SPECS/msft-golang/msft-golang.signatures.json
  SPECS/msft-golang/msft-golang.spec
  cgmanifest.json
Labels: main

#7407 Add package nss-mdns
  SPECS-EXTENDED/nss-mdns/nss-mdns-local-heuristic-unit.patch
  SPECS-EXTENDED/nss-mdns/nss-mdns-local-heuristic.patch
  SPECS-EXTENDED/nss-mdns/nss-mdns.signatures.json
  SPECS-EXTENDED/nss-mdns/nss-mdns.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended

#7671 Fix llvm for BPF builds
  SPECS/llvm/llvm.spec
  SPECS/xdp-tools/xdp-tools.signatures.json
  SPECS/xdp-tools/xdp-tools.spec
  cgmanifest.json
Labels: 3.0

#7673 Upgrade nvidia-container-toolkit to 1.14.4 for AzL-3.0
  SPECS/nvidia-container-toolkit/nvidia-container-toolkit.signatures.json
  SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec
  cgmanifest.json
Labels: 3.0

#7713 Upgrade nspr; Upgrade nss
  SPECS/nspr/nspr.signatures.json
  SPECS/nspr/nspr.spec
  SPECS/nss/nss.signatures.json
  SPECS/nss/nss.spec
  cgmanifest.json
Labels: 3.0

#7704 Upgrade libdnet to 1.17.0
  SPECS/libdnet/DisableMakeCheckCases.patch
  SPECS/libdnet/libdnet.signatures.json
  SPECS/libdnet/libdnet.spec
  cgmanifest.json
Labels: 3.0

#7576 ndctl: upgrade to 78
  SPECS/iniparser/iniparser.signatures.json
  SPECS/iniparser/iniparser.spec
  SPECS/ndctl/ndctl.signatures.json
  SPECS/ndctl/ndctl.spec
  cgmanifest.json
Labels: 3.0

#7512 Upgrade ksh: 1.0.0~beta.1 -> 1.0.8
  SPECS/ksh/ksh-1.0.0-beta.1-fix-build.patch
  SPECS/ksh/ksh-1.0.0-beta.1-regre-tests.patch
  SPECS/ksh/ksh.signatures.json
  SPECS/ksh/ksh.spec
  cgmanifest.json
Labels: 3.0

#7649 fix cve-2022-21698 in moby-engine
  SPECS/moby-engine/CVE-2022-21698.patch
  SPECS/moby-engine/moby-engine.spec
Labels: security, fasttrack/2.0

#7736 Removed extra double quote in the toolkit.
  toolkit/scripts/toolkit.mk
Labels: main

#7689 fix cve-2022-21698 in node-problem-detector
  SPECS/node-problem-detector/CVE-2022-21698.patch
  SPECS/node-problem-detector/node-problem-detector.spec
Labels: fasttrack/2.0

#7732 Extended spec PR check to verify the `Distribution` tag.
  toolkit/scripts/check_spec_guidelines.py
Labels: 3.0

#7598 Upgrade re2 to 20240201 and add gbenchmark 1.8.3 for test support
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/gbenchmark/gbenchmark.signatures.json
  SPECS/gbenchmark/gbenchmark.spec
  SPECS/re2/re2.signatures.json
  SPECS/re2/re2.spec
  cgmanifest.json
Labels: 3.0

#7463 sriov-network-device-plugin: upgrade from 3.5.1 -> 3.6.2
  SPECS/sriov-network-device-plugin/sriov-network-device-plugin.signatures.json
  SPECS/sriov-network-device-plugin/sriov-network-device-plugin.spec
  cgmanifest.json
Labels: main

#6652 Fixing missing nobody user/group for nfs squash
  SPECS/nfs-utils/nfs-utils.spec
Labels: main

#7608 Upgrade iputils to 20240117
  SPECS/iputils/iputils.signatures.json
  SPECS/iputils/iputils.spec
  cgmanifest.json
Labels: 3.0

#7716 kernel-uvm-cvm: remove spec and references
  .github/CODEOWNERS
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/kata-packages-uvm/kata-packages-uvm.spec
  SPECS/kernel-uvm-cvm/config
  SPECS/kernel-uvm-cvm/kernel-uvm-cvm.signatures.json
  SPECS/kernel-uvm-cvm/kernel-uvm-cvm.spec
  SPECS/tdnf/tdnf-add-installonlypkgs-config.patch
  cgmanifest.json
Labels: main

#7738 Add copyright header if missing in shell scripts
  .pipelines/common/scripts/PackageSignedRPMs.sh
  toolkit/imageconfigs/postinstallscripts/core-container/cleanup.sh
  toolkit/resources/imageconfigs/additionalfiles/iso_initrd/root/runliveinstaller
  toolkit/resources/imageconfigs/postinstallscripts/iso_initrd/cleanup.sh
  toolkit/resources/manifests/package/update_manifests.sh
  toolkit/scripts/download-packages.sh
  toolkit/scripts/filter-packages.sh
  toolkit/scripts/sodiff/mariner-sodiff.sh
  toolkit/scripts/toolchain/check_manifests.sh
  toolkit/scripts/toolchain/list_toolchain_specs.sh
Labels: 3.0

#7687 Add cleanup script to base images
  toolkit/imageconfigs/baremetal.json
  toolkit/imageconfigs/qemu-guest.json
  toolkit/imageconfigs/scripts/cleanup.sh
Labels: main

#7753 Revert "Shift user/group creation earlier in image build for rootfs image type"
  toolkit/imageconfigs/packagelists/core-packages-image.json
  toolkit/tools/imageconfigvalidator/imageconfigvalidator.go
  toolkit/tools/imagegen/installutils/installutils.go
Labels: main

#7752 Fix pytest version for python-virtualenv
  SPECS/python-virtualenv/pin-pytest-version.patch
  SPECS/python-virtualenv/python-virtualenv.spec
Labels: main

#7740 mandoc: introduce for 3.0
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/mandoc/mandoc.signatures.json
  SPECS/mandoc/mandoc.spec
  cgmanifest.json
Labels: 3.0

#7755 Upgrade busybox to 1.36.1
  SPECS/busybox/CVE-2022-30065.patch
  SPECS/busybox/ash-fix-use-after-free-in-bash-pattern-substitution.patch
  SPECS/busybox/ash-fix-use-after-free-in-pattern-substituon-code.patch
  SPECS/busybox/awk-input-numbers-are-never-octal-or-hex-only-progra.patch
  SPECS/busybox/busybox.signatures.json
  SPECS/busybox/busybox.spec
  cgmanifest.json
Labels: 3.0

#7754 Update dtc to 1.7.0
  SPECS/dtc/dtc.signatures.json
  SPECS/dtc/dtc.spec
  cgmanifest.json
Labels: 3.0

#7741 restore autoconf213
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/autoconf213/autoconf-2.13-versioning.patch
  SPECS/autoconf213/autoconf213-destdir.patch
  SPECS/autoconf213/autoconf213-info.patch
  SPECS/autoconf213/autoconf213.signatures.json
  SPECS/autoconf213/autoconf213.spec
  SPECS/mozjs/mozjs.spec
Labels: 3.0

#7750 Upgrade libwacom package to version 2.9.0
  SPECS-EXTENDED/python-evdev/python-evdev.signatures.json
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/libwacom/libwacom.signatures.json
  SPECS/libwacom/libwacom.spec
  SPECS/python-evdev/python-evdev.signatures.json
  SPECS/python-evdev/python-evdev.spec
  SPECS/python-libevdev/python-libevdev.signatures.json
  SPECS/python-libevdev/python-libevdev.spec
  cgmanifest.json
Labels: 3.0

#7768 Upgrade libXdamage version to 1.1.6 for 3.0
  SPECS/libXdamage/libXdamage.signatures.json
  SPECS/libXdamage/libXdamage.spec
  cgmanifest.json
Labels: 3.0

#7769 Upgrade libXdmcp to version 1.1.4
  SPECS/libXdmcp/libXdmcp.signatures.json
  SPECS/libXdmcp/libXdmcp.spec
  cgmanifest.json
Labels: 3.0

#7770 Upgrade libXfixes to version 6.0.1 for Mariner 3.0
  SPECS/libXfixes/libXfixes.signatures.json
  SPECS/libXfixes/libXfixes.spec
  cgmanifest.json
Labels: 3.0

#7746 Upgrade cifs-utils to 7.0
  SPECS/cifs-utils/CVE-2022-27239.patch
  SPECS/cifs-utils/CVE-2022-29869.patch
  SPECS/cifs-utils/cifs-utils.signatures.json
  SPECS/cifs-utils/cifs-utils.spec
  cgmanifest.json
Labels: 3.0

#7772 Upgrade libXfont2 to version 2.0.6 for Mariner 3.0
  SPECS/libXfont2/libXfont2.signatures.json
  SPECS/libXfont2/libXfont2.spec
  cgmanifest.json
Labels: 3.0

#7773 Upgrade libXxf86vm to version 1.1.5 for Mariner 3.0
  SPECS/libXxf86vm/libXxf86vm.signatures.json
  SPECS/libXxf86vm/libXxf86vm.spec
  cgmanifest.json
Labels: 3.0

#7715 Upgrade createrepo_c to 1.0.3
  SPECS/createrepo_c/createrepo_c.signatures.json
  SPECS/createrepo_c/createrepo_c.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 3.0

#7771 Upgrade ctags to 6.1.0
  SPECS/ctags/ctags.signatures.json
  SPECS/ctags/ctags.spec
  cgmanifest.json
Labels: 3.0

#7778 hyperscan: upgrade from 5.4.0 to 5.4.2
  SPECS/hyperscan/hyperscan-fix-missed-symbols.patch
  SPECS/hyperscan/hyperscan.signatures.json
  SPECS/hyperscan/hyperscan.spec
  cgmanifest.json
Labels: 3.0

#7759 fix cve-2022-21698 in prometheus-process-exporter
  SPECS/prometheus-process-exporter/CVE-2022-21698.patch
  SPECS/prometheus-process-exporter/prometheus-process-exporter.spec
Labels: security, fasttrack/2.0

#7727 [3.0] Upgrade flatbuffers to v23.5.26
  SPECS/flatbuffers/flatbuffers.signatures.json
  SPECS/flatbuffers/flatbuffers.spec
  cgmanifest.json
Labels: 3.0

#7786 [CHERRYPICK FROM FASTTRACK/2.0] fix cve-2022-21698 in node-problem-detector (#7689)
  SPECS/node-problem-detector/CVE-2022-21698.patch
  SPECS/node-problem-detector/node-problem-detector.spec
Labels: main

#7785 [CHERRYPICK FROM FASTTRACK/2.0] fix cve-2022-21698 in nmi (#7681)
  SPECS/nmi/nmi.signatures.json
  SPECS/nmi/nmi.spec
  cgmanifest.json
Labels: main

#7788 Allow dracut info logs to be visible for baremetal base image
  toolkit/imageconfigs/baremetal.json
Labels: main

#7680 conntrack-tools: Update from 1.4.5 to 1.4.8 in Mariner 3.0
  SPECS/conntrack-tools/conntrack-tools.signatures.json
  SPECS/conntrack-tools/conntrack-tools.spec
  SPECS/conntrack-tools/conntrackd.conf
  cgmanifest.json
Labels: 3.0

#7766 Upgrade mariadb-connector-c package from 3.1.10 to 3.3.8
  SPECS/mariadb-connector-c/cmake_3.21.4_fix.patch
  SPECS/mariadb-connector-c/lto-type-mismatch.patch
  SPECS/mariadb-connector-c/mariadb-connector-c.signatures.json
  SPECS/mariadb-connector-c/mariadb-connector-c.spec
  cgmanifest.json
Labels: 3.0

#7748 Upgrade ed to 1.20
  SPECS/ed/ed.signatures.json
  SPECS/ed/ed.spec
  cgmanifest.json
Labels: 3.0

#7801 Upgrade python-pbr to version 6.0.0 for Mariner 3.0
  SPECS/python-pbr/python-pbr.signatures.json
  SPECS/python-pbr/python-pbr.spec
  cgmanifest.json
Labels: 3.0

#7802 Upgrade python-pecan to version 1.5.1 for Mariner 3.0
  SPECS/python-pecan/python-pecan.signatures.json
  SPECS/python-pecan/python-pecan.spec
  cgmanifest.json
Labels: 3.0

#7545 Renaming mariner-release into azurelinux-release
  .pipelines/templatesWithCheckout/SodiffCheck.yml
  SPECS-EXTENDED/subscription-manager/subscription-manager.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/azurelinux-release/azurelinux-release.spec
  SPECS/cloud-init/cloud-init.spec
  SPECS/core-packages/core-packages.spec
  SPECS/distroless-packages/distroless-packages.spec
  SPECS/kata-containers/kata-containers.spec
  SPECS/kpatch/kpatch.spec
  SPECS/libreswan/libreswan.spec
  SPECS/lsb-release/lsb-release.spec
  SPECS/node-problem-detector/node-problem-detector.spec
  SPECS/python-distro/python-distro.spec
  SPECS/rpm-ostree/rpm-ostree.spec
  SPECS/supermin/supermin.spec
  SPECS/systemd/systemd.spec
  SPECS/tdnf/tdnf-default-azurelinux-release.patch
  SPECS/tdnf/tdnf.spec
  toolkit/resources/imageconfigs/packagelists/iso-initrd-packages-arm64.json
  toolkit/resources/imageconfigs/packagelists/iso-initrd-packages.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/tools/imager/imager.go
  toolkit/tools/internal/tdnf/tdnf.go
Labels: 3.0

#7809 Cherry-picked fast-track fix for 'kube-vip-cloud-provider' (#7698).
  SPECS/kube-vip-cloud-provider/CVE-2021-44716.patch
  SPECS/kube-vip-cloud-provider/kube-vip-cloud-provider.spec
Labels: main

#7815 Fix CVE-2021-44716 (CP #7717).
  SPECS/application-gateway-kubernetes-ingress/CVE-2021-44716.patch
  SPECS/application-gateway-kubernetes-ingress/application-gateway-kubernetes-ingress.spec
  SPECS/cf-cli/CVE-2021-44716.patch
  SPECS/cf-cli/cf-cli.spec
  SPECS/csi-driver-lvm/CVE-2021-44716.patch
  SPECS/csi-driver-lvm/csi-driver-lvm.spec
  SPECS/git-lfs/CVE-2021-44716.patch
  SPECS/git-lfs/git-lfs.spec
  SPECS/jx/CVE-2021-44716.patch
  SPECS/jx/jx.spec
  SPECS/keda/CVE-2021-44716.patch
  SPECS/keda/keda.spec
  SPECS/moby-cli/CVE-2021-44716.patch
  SPECS/moby-cli/moby-cli.spec
Labels: main

#7783 refactor specreader utils into separate file
  toolkit/tools/pkg/specreaderutils/specreaderutil.go
  toolkit/tools/specreader/specreader.go
Labels: 3.0

#7781 Add upstream patch to kubevirt to force hp-volume- pod to respect blockdevices (IcM 467224770)
  SPECS/kubevirt/Hp-volume-pod-should-respect-blockdevices.patch
  SPECS/kubevirt/kubevirt.spec
Labels: main

#7640 golang: upgrade version 1.20.10 -> 1.21.6
  SPECS-EXTENDED/buildah/buildah.spec
  SPECS-EXTENDED/containernetworking-plugins/containernetworking-plugins.spec
  SPECS-EXTENDED/delve/delve.spec
  SPECS-EXTENDED/podman/podman.signatures.json
  SPECS-EXTENDED/podman/podman.spec
  SPECS-EXTENDED/umoci/umoci.spec
  SPECS/KeysInUse-OpenSSL/KeysInUse-OpenSSL.spec
  SPECS/blobfuse/blobfuse.spec
  SPECS/blobfuse2/blobfuse2.spec
  SPECS/cert-manager/cert-manager.spec
  SPECS/cni-plugins/cni-plugins.spec
  SPECS/cni/cni.spec
  SPECS/coredns/coredns.spec
  SPECS/cri-o/cri-o.spec
  SPECS/cri-tools/cri-tools.spec
  SPECS/dcos-cli/dcos-cli.spec
  SPECS/etcd/etcd.spec
  SPECS/gh/gh.spec
  SPECS/glide/glide.spec
  SPECS/go-md2man/go-md2man.spec
  SPECS/gobject-introspection/gobject-introspection.spec
  SPECS/golang/golang.signatures.json
  SPECS/golang/golang.spec
  SPECS/helm/helm.spec
  SPECS/influx-cli/influx-cli.spec
  SPECS/influxdb/influxdb.spec
  SPECS/kata-containers-cc/kata-containers-cc.spec
  SPECS/kata-containers/kata-containers.spec
  SPECS/keda/keda.spec
  SPECS/kubernetes/kubernetes.spec
  SPECS/kured/kured.spec
  SPECS/libnvidia-container/libnvidia-container.spec
  SPECS/moby-cli/moby-cli.spec
  SPECS/moby-containerd/moby-containerd.spec
  SPECS/moby-engine/moby-engine.spec
  SPECS/moby-runc/moby-runc.spec
  SPECS/multus/multus.spec
  SPECS/nmi/nmi.spec
  SPECS/node-problem-detector/node-problem-detector.spec
  SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec
  SPECS/opa/opa.spec
  SPECS/prometheus-adapter/prometheus-adapter.spec
  SPECS/prometheus-process-exporter/prometheus-process-exporter.spec
  SPECS/prometheus/prometheus.spec
  SPECS/rook/rook.spec
  SPECS/skopeo/skopeo.spec
  SPECS/sriov-network-device-plugin/sriov-network-device-plugin.spec
  SPECS/telegraf/telegraf.spec
  cgmanifest.json
Labels: main

#7823 Fixed merge leftovers in a `coredns` patch.
  SPECS/coredns/CVE-2023-44487.patch
Labels: security, main

#7826 cni-plugins: update to 1.4.0
  SPECS/cni-plugins/cni-plugins.signatures.json
  SPECS/cni-plugins/cni-plugins.spec
  cgmanifest.json
Labels: 3.0

#7827 Upgrade python-psycopg2 to version 2.9.9 for Mariner 3.0
  SPECS/python-psycopg2/python-psycopg2.signatures.json
  SPECS/python-psycopg2/python-psycopg2.spec
  cgmanifest.json
Labels: 3.0

#7828 Upgrade python-pycurl to version 7.45.2 for Mariner 3.0
  SPECS/python-pycurl/python-pycurl.signatures.json
  SPECS/python-pycurl/python-pycurl.spec
  cgmanifest.json
Labels: 3.0

#7825 Upgrade pytest-xdist to version 3.5.0 for Mariner 3.0
  SPECS/python-pytest-xdist/python-pytest-xdist.signatures.json
  SPECS/python-pytest-xdist/python-pytest-xdist.spec
  cgmanifest.json
Labels: 3.0

#7841 glibmm: update to 2.78.1
  SPECS/glibmm/glibmm.signatures.json
  SPECS/glibmm/glibmm.spec
  cgmanifest.json
Labels: 3.0

#7844 snappy: update to 1.1.10
  SPECS/snappy/snappy-inline.patch
  SPECS/snappy/snappy.signatures.json
  SPECS/snappy/snappy.spec
  cgmanifest.json
Labels: 3.0

#7838 Patched `moby-engine` CVEs: 2024-23651 and 2024-23652.
  SPECS/moby-engine/CVE-2024-23651.patch
  SPECS/moby-engine/CVE-2024-23652.patch
  SPECS/moby-engine/moby-engine.spec
Labels: security, fasttrack/2.0

#7840 Patch golang related module in moby-buildx for CVE-2021-44716
  SPECS/moby-buildx/CVE-2021-44716.patch
  SPECS/moby-buildx/moby-buildx.spec
Labels: security, fasttrack/2.0

#7668 upgrade: kured from 1.9.1 to 1.15.0
  SPECS/kured/kured-imagePullPolicy.patch
  SPECS/kured/kured.signatures.json
  SPECS/kured/kured.spec
  cgmanifest.json
Labels: 3.0

#7811 json-c: package upgrade to 0.17
  SPECS/json-c/CVE-2021-32292.patch
  SPECS/json-c/json-c.signatures.json
  SPECS/json-c/json-c.spec
  cgmanifest.json
Labels: 3.0

#7665 upgrade: vala from 0.54.6 to 0.56.14
  SPECS/vala/vala.signatures.json
  SPECS/vala/vala.spec
  cgmanifest.json
Labels: 3.0

#7667 upgrade: aspell from 0.60.8 to 0.60.8.1
  SPECS/aspell/CVE-2019-25051.patch
  SPECS/aspell/aspell-0.60.7-mp.patch
  SPECS/aspell/aspell.signatures.json
  SPECS/aspell/aspell.spec
  cgmanifest.json
Labels: 3.0

#7835 Split failing and passing tests in the summary. (#7764)
  toolkit/tools/scheduler/schedulerutils/buildworker.go
  toolkit/tools/scheduler/schedulerutils/graphbuildstate.go
  toolkit/tools/scheduler/schedulerutils/printresults.go
Labels: Tools, go, main

#7784 Fixed breaking rubygem packages.
  SPECS/rubygem-async-http/rubygem-async-http.spec
  SPECS/rubygem-async/rubygem-async.spec
  SPECS/rubygem-ffi/rubygem-ffi.spec
  SPECS/rubygem-fluent-logger/rubygem-fluent-logger.spec
  SPECS/rubygem-td/rubygem-td.spec
Labels: 3.0

#7837 Add compatibility flag to all createrepo commands
  .pipelines/containerSourceData/Dockerfile-Initial
  SPECS/fontpackages/dnf.patch
  SPECS/fontpackages/fontpackages.spec
  toolkit/scripts/containerized-build/resources/setup_functions.sh
  toolkit/tools/internal/packagerepo/repomanager/rpmrepomanager/rpmrepomanager.go
Labels: Tools, go, 3.0

#7867 Upgrade xorg-x11-xinit to 1.4.2 in Azure Linux 3.0
  SPECS/xorg-x11-xinit/Xclients
  SPECS/xorg-x11-xinit/Xsession
  SPECS/xorg-x11-xinit/xorg-x11-xinit.signatures.json
  SPECS/xorg-x11-xinit/xorg-x11-xinit.spec
  cgmanifest.json
Labels: 3.0

#7860 Upgrade python-pytest-benchmark to 4.0.0
  SPECS/python-pytest-benchmark/python-pytest-benchmark.signatures.json
  SPECS/python-pytest-benchmark/python-pytest-benchmark.spec
  cgmanifest.json
Labels: 3.0

#7881 Add --compatibility flag while updating the repo metadata
  toolkit/tools/internal/packagerepo/repomanager/rpmrepomanager/rpmrepomanager.go
Labels: 3.0

#7879 Fix the change logs to keep correct published order
  SPECS/node-problem-detector/node-problem-detector.spec
  SPECS/prometheus-process-exporter/prometheus-process-exporter.spec
  SPECS/rook/rook.spec
Labels: main

#7739 pyparsing: upgrade to 3.1.1
  SPECS/pyparsing/pyparsing.signatures.json
  SPECS/pyparsing/pyparsing.spec
  cgmanifest.json
Labels: 3.0

#7845 tuned: Update from 2.15.0 to 2.21.0 in Mariner 3.0
  SPECS/tuned/skip-gui-files.patch
  SPECS/tuned/tuned.signatures.json
  SPECS/tuned/tuned.spec
  cgmanifest.json
Labels: 3.0

#7896 libpsm2 upgrade to v12.0
  SPECS/libpsm2/libpsm2.signatures.json
  SPECS/libpsm2/libpsm2.spec
  cgmanifest.json
Labels: 3.0

#7871 Upgrading lshw to B.02.20
  SPECS/lshw/lshw.signatures.json
  SPECS/lshw/lshw.spec
  cgmanifest.json
Labels: 3.0

#7892 patch openssl with null checks against ContentInfo
  SPECS/openssl/openssl-1.1.1-add-null-checks-where-contentinfo-data-can-be-null.patch
  SPECS/openssl/openssl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#7898 libnetfilter_cthelper: Update from 1.0.0 to 1.0.1 in Mariner 3.0
  SPECS/libnetfilter_cthelper/libnetfilter_cthelper.signatures.json
  SPECS/libnetfilter_cthelper/libnetfilter_cthelper.spec
  cgmanifest.json
Labels: 3.0

#7800 tests: pin cloud-init's pytest to <8.0.0
  SPECS/cloud-init/ci-Pin-pytest-8.0.0.patch
  SPECS/cloud-init/cloud-init.spec
Labels: ptest, main

#7883 libdrm: upgrade to 2.4.120
  SPECS/libdrm/libdrm.signatures.json
  SPECS/libdrm/libdrm.spec
  cgmanifest.json
Labels: 3.0

#7882 python-zope-interface: upgrade to 6.1
  SPECS/python-zope-interface/python-zope-interface.signatures.json
  SPECS/python-zope-interface/python-zope-interface.spec
  cgmanifest.json
Labels: 3.0

#7888 Kernel: Address CVE-2023-6531
  SPECS/kernel/CVE-2023-6531.nopatch
Labels: security, main

#7897 Enable Broadcom MPI3 Storage Controller Device Driver
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/mariner-required-configs.json
Labels: main

#6942 Kata: Release v3.2.0.azl0 for both vanilla and CC based on aligned sources
  SPECS/kata-containers-cc/kata-containers-cc.signatures.json
  SPECS/kata-containers-cc/kata-containers-cc.spec
  SPECS/kata-containers/0001-Append-systemd-kernel-cmdline-params-for-initrd.patch
  SPECS/kata-containers/0001-Merged-PR-9607-Allow-10-seconds-for-VM-creation-star.patch
  SPECS/kata-containers/0001-osbuilder-Add-support-for-CBL-Mariner.patch
  SPECS/kata-containers/0002-Merged-PR-9671-Wait-for-a-possibly-slow-Guest.patch
  SPECS/kata-containers/0003-Merged-PR-9805-Add-support-for-MSHV.patch
  SPECS/kata-containers/0004-Merged-PR-9806-Fix-enable_debug-for-hypervisor.clh.patch
  SPECS/kata-containers/0005-Merged-PR-9956-shim-avoid-memory-hotplug-timeout.patch
  SPECS/kata-containers/drop-mut-for-variables-that-are-not-mutated.patch
  SPECS/kata-containers/kata-containers.signatures.json
  SPECS/kata-containers/kata-containers.spec
  SPECS/kata-containers/runtime-reduce-uvm-high-mem-footprint.patch
  cgmanifest.json
Labels: main

#7869 Re-add systemd-bootstrap obsoletes to systemd
  SPECS/systemd/systemd.spec
Labels: 3.0

#7907 Patched CVE-2021-38593 in `qt5-qtbase`.
  SPECS/qt5-qtbase/CVE-2021-38593.patch
  SPECS/qt5-qtbase/qt5-qtbase.spec
Labels: main

#7868 Add osslsigncode package
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/osslsigncode/osslsigncode.signatures.json
  SPECS/osslsigncode/osslsigncode.spec
  cgmanifest.json
Labels: main

#7908 libnetfilter_log: Update from 1.0.1 to 1.0.2 in Mariner 3.0
  SPECS/libnetfilter_log/libnetfilter_log-sysheader.patch
  SPECS/libnetfilter_log/libnetfilter_log.signatures.json
  SPECS/libnetfilter_log/libnetfilter_log.spec
  cgmanifest.json
Labels: 3.0

#7912 Upgrade xfsprogs to 6.6.0
  SPECS/xfsprogs/xfsprogs.signatures.json
  SPECS/xfsprogs/xfsprogs.spec
  cgmanifest.json
Labels: 3.0

#7921 [RFC] virtiofsd: enable build on all supported platforms
  SPECS/virtiofsd/virtiofsd.spec
Labels: main, RFC

#7543 Patch waagent.conf to add firewall rules
  SPECS/WALinuxAgent/WALinuxAgent.spec
  SPECS/WALinuxAgent/add_firewall_rules.patch
Labels: main

#7901 go-tool: pass error instead of logging utility files
  toolkit/tools/internal/file/file.go
  toolkit/tools/internal/rpm/rpm.go
  toolkit/tools/internal/safechroot/safechroot.go
Labels: Tools, 3.0

#7666 upgrade: dconf from 0.36.0 to 0.40.0
  SPECS/dconf/dconf.signatures.json
  SPECS/dconf/dconf.spec
  cgmanifest.json
Labels: 3.0

#7945 Upgrade lynx to 2.9.0
  SPECS/lynx/lynx.signatures.json
  SPECS/lynx/lynx.spec
  cgmanifest.json
Labels: 3.0

#7573 espeakup: Upgrade to version 0.90
  SPECS/espeakup/default-voice.patch
  SPECS/espeakup/espeakup.service
  SPECS/espeakup/espeakup.signatures.json
  SPECS/espeakup/espeakup.spec
  SPECS/espeakup/missing-mutex-calls.patch
  SPECS/espeakup/speaking-spaces.patch
  SPECS/espeakup/support-pauses.patch
  SPECS/espeakup/unicode-device.patch
  cgmanifest.json
Labels: 3.0

#7954 flannel: Upgrade to version 0.24.2
  SPECS/flannel/flannel.signatures.json
  SPECS/flannel/flannel.spec
  cgmanifest.json
Labels: 3.0

#7173 Introduce kernel-mshv-signed, hvloader-signed
  .github/CODEOWNERS
  SPECS-SIGNED/hvloader-signed/hvloader-signed.spec
  SPECS-SIGNED/kernel-mshv-signed/kernel-mshv-signed.spec
  SPECS-SIGNED/kernel-mshv-signed/sha512hmac-openssl.sh
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  toolkit/scripts/check_entangled_specs.py
Labels: main

#6343 feat: Introduce kernel-mshv's custom menuentry for the grub2-mkconfig flow
  SPECS/kernel-mshv/50_mariner_mshv.cfg
  SPECS/kernel-mshv/50_mariner_mshv_menuentry
  SPECS/kernel-mshv/kernel-mshv.signatures.json
  SPECS/kernel-mshv/kernel-mshv.spec
  toolkit/tools/internal/resources/assets/grub2/grub
Labels: 3.0

#7983 jna: Update from 5.10.0 to 5.14.0 in Mariner 3.0
  SPECS/jna/ant_tools_arbitrary_ow2.patch
  SPECS/jna/jna.signatures.json
  SPECS/jna/jna.spec
  SPECS/jna/jna_remove_clover_and_win32_native_jar.patch
  cgmanifest.json
Labels: 3.0

#7906 grub2: update to SBAT 4
  SPECS-SIGNED/grub2-efi-binary-signed/grub2-efi-binary-signed.spec
  SPECS/grub2/grub2.signatures.json
  SPECS/grub2/grub2.spec
  SPECS/grub2/sbat-3-0001-font-Reject-glyphs-exceeds-font-max_glyph_width-or-f.patch
  SPECS/grub2/sbat-3-0004-font-Remove-grub_font_dup_glyph.patch
  SPECS/grub2/sbat-3-0005-font-Fix-integer-overflow-in-ensure_comb_space.patch
  SPECS/grub2/sbat-3-0006-font-Fix-integer-overflow-in-BMP-index.patch
  SPECS/grub2/sbat-3-0007-font-Fix-integer-underflow-in-binary-search-of-char-.patch
  SPECS/grub2/sbat-3-0008-kern-efi-sb-Enforce-verification-of-font-files.patch
  SPECS/grub2/sbat-3-0009-fbutil-Fix-integer-overflow.patch
  SPECS/grub2/sbat-3-0011-font-Harden-grub_font_blit_glyph-and-grub_font_blit_.patch
  SPECS/grub2/sbat-3-0012-font-Assign-null_font-to-glyphs-in-ascii_font_glyph.patch
  SPECS/grub2/sbat-3-0013-normal-charset-Fix-an-integer-overflow-in-grub_unico.patch
  SPECS/grub2/sbat-4-0001-fs-ntfs-Fix-an-OOB-write-when-parsing-the-ATTRIBUTE_.patch
  SPECS/grub2/sbat-4-0002-fs-ntfs-Fix-an-OOB-read-when-reading-data-from-the-r.patch
  SPECS/grub2/sbat-4-0003-fs-ntfs-Fix-an-OOB-read-when-parsing-directory-entri.patch
  SPECS/grub2/sbat-4-0004-fs-ntfs-Fix-an-OOB-read-when-parsing-bitmaps-for-ind.patch
  SPECS/grub2/sbat-4-0005-fs-ntfs-Fix-an-OOB-read-when-parsing-a-volume-label.patch
  SPECS/grub2/sbat-4-0006-fs-ntfs-Make-code-more-readable.patch
  SPECS/grub2/sbat.csv.in
Labels: main

#7685 Upgrade and rename moby-runc to runc 1.1.12
  .github/CODEOWNERS
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/moby-runc/0001-cgroups-cpuset-fix-byte-order-while-parsing-cpuset-r.patch
  SPECS/moby-runc/moby-runc.signatures.json
  SPECS/runc/runc.signatures.json
  SPECS/runc/runc.spec
  cgmanifest.json
Labels: 3.0

#7975 moby-containerd-cc: update to v1.7.7
  SPECS/moby-containerd-cc/moby-containerd-cc.signatures.json
  SPECS/moby-containerd-cc/moby-containerd-cc.spec
  cgmanifest.json
Labels: main

#7446 Bump golang version to 1.21.6-1 and switch to Microsoft Go
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/golang/CVE-2022-41717.patch
  SPECS/golang/golang-1.18.signatures.json
  SPECS/golang/golang-1.18.spec
  SPECS/golang/golang.signatures.json
  SPECS/golang/golang.spec
  cgmanifest.json
Labels: 3.0

#8004 golang: include go.env in GOROOT
  SPECS/golang/golang.spec
Labels: main

#7916 javapackages-tools: upgrade to 6.1.0
  SPECS/javapackages-tools/javapackages-tools.signatures.json
  SPECS/javapackages-tools/javapackages-tools.spec
  cgmanifest.json
Labels: 3.0

#7961 Add new package python-sortedcontainers
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/python-sortedcontainers/python-sortedcontainers.signatures.json
  SPECS/python-sortedcontainers/python-sortedcontainers.spec
  cgmanifest.json
Labels: 3.0

#8021 golang: include go.env in GOROOT
  SPECS/golang/golang.spec
Labels: 3.0

#8054 Revert "Patch waagent.conf to add firewall rules (#7543)"
  SPECS/WALinuxAgent/WALinuxAgent.spec
  SPECS/WALinuxAgent/add_firewall_rules.patch
Labels: main

#7664 add golden containers src artifacts
  .pipelines/containerSourceData/Dockerfile-Initial
  .pipelines/containerSourceData/azurecli/Dockerfile-AzureCLI
  .pipelines/containerSourceData/azurecli/azurecli.pkg
  .pipelines/containerSourceData/base/Dockerfile-Base-Nonroot-Template
  .pipelines/containerSourceData/base/Dockerfile-Busybox-Template
  .pipelines/containerSourceData/base/Dockerfile-Distroless-Nonroot-Template
  .pipelines/containerSourceData/base/Dockerfile-Distroless-Template
  .pipelines/containerSourceData/nodejs/distroless/holdback-nodejs18.pkg
  .pipelines/containerSourceData/nodejs/distroless/nodejs18.pkg
  .pipelines/containerSourceData/prometheus/distroless/holdback-prometheus.pkg
  .pipelines/containerSourceData/prometheus/distroless/prometheus.pkg
  .pipelines/containerSourceData/prometheusadapter/distroless/holdback-prometheusadapter.pkg
  .pipelines/containerSourceData/prometheusadapter/distroless/prometheusadapter.pkg
  .pipelines/containerSourceData/python/distroless/holdback-python.pkg
  .pipelines/containerSourceData/python/distroless/python.pkg
  .pipelines/containerSourceData/scripts/BuildBaseContainers.sh
  .pipelines/containerSourceData/scripts/BuildCdiContainers.sh
  .pipelines/containerSourceData/scripts/BuildCertManagerContainers.sh
  .pipelines/containerSourceData/scripts/BuildGoldenContainer.sh
  .pipelines/containerSourceData/scripts/BuildGoldenContainers.sh
  .pipelines/containerSourceData/scripts/BuildGoldenDistrolessContainer.sh
  .pipelines/containerSourceData/scripts/BuildKubevirtContainers.sh
  .pipelines/containerSourceData/scripts/BuildMultusContainer.sh
  .pipelines/containerSourceData/scripts/BuildSriovDpContainer.sh
  .pipelines/containerSourceData/scripts/CommonFunctions.sh
  .pipelines/containerSourceData/scripts/PublishContainers.sh
Labels: main

#7858 python3: upgrade to 3.12.0
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/asciidoc/asciidoc.spec
  SPECS/firewalld/firewalld.spec
  SPECS/gpgme/gpgme.spec
  SPECS/hyperscan/hyperscan.spec
  SPECS/keras/keras.spec
  SPECS/libpwquality/libpwquality.spec
  SPECS/libpwquality/setuptools.patch
  SPECS/libsemanage/libsemanage.spec
  SPECS/libvoikko/libvoikko.spec
  SPECS/nbdkit/nbdkit.spec
  SPECS/newt/newt.spec
  SPECS/numpy/numpy.spec
  SPECS/python-conda-package-handling/python-conda-package-handling.signatures.json
  SPECS/python-conda-package-handling/python-conda-package-handling.spec
  SPECS/python-constantly/python-constantly.spec
  SPECS/python-coverage/python-coverage.spec
  SPECS/python-frozendict/python-frozendict.spec
  SPECS/python-greenlet/python-greenlet.signatures.json
  SPECS/python-greenlet/python-greenlet.spec
  SPECS/python-markdown/python-markdown.signatures.json
  SPECS/python-markdown/python-markdown.spec
  SPECS/python-opt-einsum/einsum_fix_python312.patch
  SPECS/python-opt-einsum/python-opt-einsum.spec
  SPECS/python-packaging/python-packaging.spec
  SPECS/python-pytest-expect/python-pytest-expect.spec
  SPECS/python-ruamel-yaml-clib/python-ruamel-yaml-clib.signatures.json
  SPECS/python-ruamel-yaml-clib/python-ruamel-yaml-clib.spec
  SPECS/python-setuptools/python-setuptools.signatures.json
  SPECS/python-setuptools/python-setuptools.spec
  SPECS/python-setuptools_scm/python-setuptools_scm.spec
  SPECS/python-sphinx/python-sphinx.spec
  SPECS/python-sphinx_rtd_theme/python-sphinx_rtd_theme.spec
  SPECS/python-tensorboard/python-tensorboard.spec
  SPECS/python-zstd/python-zstd.spec
  SPECS/python3/0001-gh-95231-Disable-md5-crypt-modules-if-FIPS-is-enable.patch
  SPECS/python3/CVE-2015-20107.patch
  SPECS/python3/CVE-2022-37454.patch
  SPECS/python3/CVE-2022-40897.patch
  SPECS/python3/CVE-2022-42919.patch
  SPECS/python3/CVE-2022-45061.patch
  SPECS/python3/CVE-2023-24329.patch
  SPECS/python3/pathfix.py
  SPECS/python3/python3.signatures.json
  SPECS/python3/python3.spec
  SPECS/rpm/rpm.spec
  SPECS/rt-tests/rt-tests.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
  toolkit/scripts/toolchain/container/toolchain-remote-wget-list
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
Labels: 3.0

#7957 fluent-bit: Upgrade to version 2.2.2
  SPECS/fluent-bit/fluent-bit.signatures.json
  SPECS/fluent-bit/fluent-bit.spec
  cgmanifest.json
Labels: 3.0

#7161 dpdk: update to version 23.11
  SPECS/dpdk/dpdk.signatures.json
  SPECS/dpdk/dpdk.spec
  cgmanifest.json
Labels: 3.0

#7942 Upgrade: node-problem-detector from 0.8.10 to 0.8.15
  SPECS/node-problem-detector/0001-add-Mariner-and-Azure-Linux-OS-Versions.patch
  SPECS/node-problem-detector/0001-remove-arch-specific-logic-from-makefile.patch
  SPECS/node-problem-detector/001-remove_arch_specific_makefile_logic.patch
  SPECS/node-problem-detector/002-add_mariner_OSVersion.patch
  SPECS/node-problem-detector/node-problem-detector.signatures.json
  SPECS/node-problem-detector/node-problem-detector.spec
  cgmanifest.json
Labels: 3.0

#7162 bpftrace: upgrade version 0.16.0 -> 0.19.1
  SPECS/bpftrace/bpftrace.signatures.json
  SPECS/bpftrace/bpftrace.spec
  cgmanifest.json
Labels: 3.0

#7089 build-essential: upgrade 0.1 -> 3.0
  SPECS/build-essential/build-essential.spec
Labels: 3.0

#7848 Upgrade createrepo_c to 1.0.3
  SPECS/createrepo_c/createrepo_c.signatures.json
  SPECS/createrepo_c/createrepo_c.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 3.0

#8118 change code QL default settings file name
  codeql3000.yml
Labels: main

#8128 Replace references to CBL-Mariner in documentation files with Azure linux as well as links
  CONTRIBUTING.md
  README.md
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/tboot/README.md
  SUPPORT.md
  toolkit/README.md
  toolkit/docs/building/building.md
  toolkit/docs/building/developer-tools.md
  toolkit/docs/building/prerequisites-mariner.md
  toolkit/docs/building/prerequisites-ubuntu.md
  toolkit/docs/building/prerequisites.md
  toolkit/docs/formats/imageconfig.md
  toolkit/docs/how_it_works/2_local_packages.md
  toolkit/docs/nvidia/nvidia.md
  toolkit/docs/quick_start/quickstart.md
  toolkit/docs/security/read-only-roots.md
  toolkit/docs/security/security-features.md
  toolkit/imageconfigs/full-aarch64.json
  toolkit/imageconfigs/full.json
Labels: documentation, 3.0

#7956 Add nss-mdns requested by redis team
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/authselect/authselect.signatures.json
  SPECS/authselect/authselect.spec
  SPECS/nss-mdns/nss-mdns-local-heuristic-unit.patch
  SPECS/nss-mdns/nss-mdns-local-heuristic.patch
  SPECS/nss-mdns/nss-mdns.signatures.json
  SPECS/nss-mdns/nss-mdns.spec
  cgmanifest.json
Labels: 3.0

#7316 glibc locale en_US.UTF-8 should be en_US.utf8
  SPECS-EXTENDED/buildah/buildah.spec
  SPECS-EXTENDED/catatonit/catatonit.spec
  SPECS-EXTENDED/dyninst/dyninst.spec
  SPECS-EXTENDED/podman/podman.spec
  SPECS/busybox/busybox.spec
  SPECS/flannel/flannel.spec
  SPECS/glibc/glibc.spec
  SPECS/kubernetes/kubernetes.spec
  SPECS/kubevirt/kubevirt.spec
  SPECS/libguestfs/libguestfs.spec
  SPECS/rust/rust.spec
  SPECS/supermin/supermin.spec
  SPECS/tini/tini.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 3.0

#8151 Fix tboot signatures and up the release version
  SPECS/tboot/tboot.signatures.json
  SPECS/tboot/tboot.spec
Labels: 3.0

#8154 updates containers source for marinara updates
  .pipelines/containerSourceData/scripts/BuildBaseContainers.sh
  .pipelines/containerSourceData/scripts/BuildGoldenDistrolessContainer.sh
Labels: main

#8022 openvswitch: update to version 3.3.0
  SPECS/openvswitch/CVE-2023-1668.patch
  SPECS/openvswitch/openvswitch.signatures.json
  SPECS/openvswitch/openvswitch.spec
  SPECS/openvswitch/openvswitch.sysusers
  cgmanifest.json
Labels: 3.0

#8130 Made test failures not fail the package build. (CP of #8121)
  toolkit/tools/scheduler/schedulerutils/graphbuildstate.go
  toolkit/tools/scheduler/schedulerutils/printresults.go
Labels: main
