Repository microsoft/azurelinux, pull requests merged in 2024-08, with the labels that each got.

#9906 Adding systemd service to postgresql
  SPECS/postgresql/postgresql.service
  SPECS/postgresql/postgresql.signatures.json
  SPECS/postgresql/postgresql.spec
Labels: Packaging, 3.0-dev

#9999 Remove unnecessary Requires:libselinux from coreutils to fix Circular dependency
  SPECS/coreutils/coreutils.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#9978 Image Customizer: Fixes for grub2-install.
  toolkit/tools/imagecustomizer/README.md
  toolkit/tools/imagecustomizer/container/Dockerfile.mic-container
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/pkg/imagecustomizerlib/customizepartitions_test.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
  toolkit/tools/pkg/imagecustomizerlib/testdata/legacyboot-config.yaml
Labels: Tools

#9983 Fix call to `parted mkpart`.
  toolkit/tools/imagegen/diskutils/diskutils.go
  toolkit/tools/pkg/imagecustomizerlib/customizepartitions_test.go
Labels: Tools

#10002 Image Customizer: Fix merge in 'TestCustomizeImagePartitionsLegacy'.
  toolkit/tools/pkg/imagecustomizerlib/customizepartitions_test.go
Labels: Tools

#9741 Upgrade maven to 3.8.1 to fix CVE-2021-26291 in javapackages-bootstrap
  SPECS/javapackages-bootstrap/CVE-2021-26291.patch
  SPECS/javapackages-bootstrap/javapackages-bootstrap.signatures.json
  SPECS/javapackages-bootstrap/javapackages-bootstrap.spec
Labels: security, Packaging, fasttrack/2.0

#10001 yasm: patch CVE-2021-33454 (3.0)
  SPECS/yasm/CVE-2021-33454.patch
  SPECS/yasm/yasm.spec
Labels: Packaging

#9850 protobuf: patch CVE-2022-1941
  SPECS/protobuf/CVE-2022-1941.patch
  SPECS/protobuf/protobuf.spec
Labels: Packaging

#9985 Fix duplicate file issues in harfbuzz, cyrus-sasl and rrdtool
  SPECS/cyrus-sasl-bootstrap/cyrus-sasl-bootstrap.spec
  SPECS/cyrus-sasl/cyrus-sasl.spec
  SPECS/harfbuzz/harfbuzz.spec
  SPECS/rrdtool/rrdtool.spec
Labels: Packaging

#10012 Image Customizer: Bump release version to v0.6.
  toolkit/scripts/build_tag_imagecustomizer.mk
Labels: Tools

#10010 Fix CVE-2024-6104 in skopeo with a patch - 3.0
  SPECS/skopeo/CVE-2024-6104.patch
  SPECS/skopeo/skopeo.spec
Labels: security, Packaging, 3.0-dev

#9581 azcopy: upgrade version to 10.25.1 to fix CVE-2024-35255
  SPECS/azcopy/azcopy.signatures.json
  SPECS/azcopy/azcopy.spec
  cgmanifest.json
Labels: security, Packaging, main

#10031 Bump frr to 9.1.1 to fix CVE-224-31950 & CVE-2024-31951
  SPECS/frr/frr.signatures.json
  SPECS/frr/frr.spec
  cgmanifest.json
Labels: security, 3.0-dev

#9965 Backport: Update toolkit's gonum to v0.15.0
  .github/workflows/go-test-coverage.yml
  toolkit/docs/building/prerequisites-ubuntu.md
  toolkit/tools/go.mod
  toolkit/tools/go.sum
Labels: Tools, go, main, 2.0

#10027 feat: enable USB_TMC as module
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS-SIGNED/kernel-uki-signed/kernel-uki-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/kernel-uki.spec
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 3.0-dev

#10036 Upgraded `valgrind` to version 3.22.0.
  SPECS/valgrind/valgrind.signatures.json
  SPECS/valgrind/valgrind.spec
  cgmanifest.json
Labels: Packaging

#10039 dracut: add fix for initrd not showing prompt when root device is locked
  SPECS/dracut/0013-revert-fix-crypt-unlock-encrypted-devices-by-default.patch
  SPECS/dracut/dracut.spec
Labels: Packaging

#10028 fix: correct moby-engine cherry-pick to keep consistency
  SPECS/moby-engine/moby-engine.spec
Labels: Packaging, main

#10016 fix: upgrade walinuxagent to 2.11.1.4 and add azurelinux patch
  SPECS/WALinuxAgent/0001-add-azurelinux-support.patch
  SPECS/WALinuxAgent/0002-fix-bump-version-to-2.11.8.8.patch
  SPECS/WALinuxAgent/WALinuxAgent.signatures.json
  SPECS/WALinuxAgent/WALinuxAgent.spec
  SPECS/WALinuxAgent/ephemeral-disk-warning.service
  SPECS/WALinuxAgent/fix-argument-to-goalstate.patch
  cgmanifest.json
Labels: 3.0-dev

#10008 Fix CVE-2024-6104 in prometheus by patching vendor gomodule
  SPECS/prometheus/CVE-2024-6104.patch
  SPECS/prometheus/prometheus.spec
Labels: Packaging, 3.0-dev

#9989 Fix CVE-2024-41671 and CVE-2024-41810 in 3.0 python-twisted
  SPECS/python-twisted/CVE-2024-41671.patch
  SPECS/python-twisted/CVE-2024-41810.patch
  SPECS/python-twisted/python-twisted.spec
Labels: security, Packaging, 3.0-dev

#10007 Fix CVE-2024-6104 in libcontainers-common by patching gomodule
  SPECS/libcontainers-common/CVE-2024-6104.patch
  SPECS/libcontainers-common/libcontainers-common.spec
Labels: Packaging, 3.0-dev

#9996 Fix CVE-2024-6104 in keda by patching vendor gomodule
  SPECS/keda/CVE-2024-6104.patch
  SPECS/keda/keda.spec
Labels: Packaging, 3.0-dev

#9995 Fix CVE-2024-6104 in influxdb by patching vendor gomodule
  SPECS/influxdb/CVE-2024-6104.patch
  SPECS/influxdb/influxdb.spec
Labels: Packaging, 3.0-dev

#10017 Fix CVE-2024-6104 in packer by patching the vendor golang
  SPECS/packer/CVE-2024-6104.patch
  SPECS/packer/packer.spec
Labels: Packaging

#10022 documentation: update toolkit building docs for 3.0
  toolkit/docs/building/building.md
Labels: documentation

#10041 image customizer: rename /etc/mariner-customizer-release to /etc/image-customizer-release
  toolkit/tools/imagecustomizer/docs/configuration.md
  toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
  toolkit/tools/pkg/imagecustomizerlib/customizeutils_test.go
Labels: Tools

#10056 Image Customizer: Expand legacy boot tests.
  toolkit/tools/pkg/imagecustomizerlib/customizepartitions_test.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
  toolkit/tools/pkg/imagecustomizerlib/main_test.go
Labels: Tools

#9878 feat(cloud-init): add support for azure-proxy-agent
  SPECS/cloud-init/0001-feat-azure-Add-ProvisionGuestProxyAgent-OVF-setting-.patch
  SPECS/cloud-init/0002-feat-azure-parse-ProvisionGuestProxyAgent-as-bool-51.patch
  SPECS/cloud-init/0003-feat-azure-add-support-for-azure-proxy-agent.patch
  SPECS/cloud-init/cloud-init.spec
Labels: Packaging, main, stable-release-2.0

#10055 postgresql: add requires for shadow-utils
  SPECS/postgresql/postgresql.spec
Labels: Packaging, 3.0-dev

#10050 Upgrade libtevent to build with Python 3.12
  SPECS-EXTENDED/libtevent/0003-wafsamba-Fix-few-SyntaxWarnings-caused-by-regular-ex.patch
  SPECS-EXTENDED/libtevent/libtevent.signatures.json
  SPECS-EXTENDED/libtevent/libtevent.spec
  cgmanifest.json
Labels: Packaging, 3.0-dev

#10066 dracut: add fix for initrd not showing prompt when root device is locked (#10039)
  SPECS/dracut/0013-revert-fix-crypt-unlock-encrypted-devices-by-default.patch
  SPECS/dracut/dracut.spec
Labels: Packaging

#10059 Image Customizer: Split up customizeutils.go.
  toolkit/tools/pkg/imagecustomizerlib/customizebootloader.go
  toolkit/tools/pkg/imagecustomizerlib/customizefiles.go
  toolkit/tools/pkg/imagecustomizerlib/customizefiles_test.go
  toolkit/tools/pkg/imagecustomizerlib/customizehostname.go
  toolkit/tools/pkg/imagecustomizerlib/customizehostname_test.go
  toolkit/tools/pkg/imagecustomizerlib/customizeos.go
  toolkit/tools/pkg/imagecustomizerlib/customizeselinux.go
  toolkit/tools/pkg/imagecustomizerlib/customizeselinux_test.go
  toolkit/tools/pkg/imagecustomizerlib/customizeservices.go
  toolkit/tools/pkg/imagecustomizerlib/customizeservices_test.go
  toolkit/tools/pkg/imagecustomizerlib/customizeusers.go
  toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
  toolkit/tools/pkg/imagecustomizerlib/customizeutils_test.go
  toolkit/tools/pkg/imagecustomizerlib/grubcfgutils.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
  toolkit/tools/pkg/imagecustomizerlib/partitionutils.go
  toolkit/tools/pkg/imagecustomizerlib/releasefile.go
  toolkit/tools/pkg/imagecustomizerlib/releasefile_test.go
  toolkit/tools/pkg/imagecustomizerlib/runscripts.go
Labels: Tools, 3.0-dev

#9795 Disable PR check debug mode by default.
  .pipelines/prchecks/PackageBuildPRCheck.yml
Labels: fasttrack/2.0

#10065 [mic][iso] Add curl to the list of required dependencies for iso creation.
  toolkit/tools/pkg/imagecustomizerlib/liveosisobuilder.go
  toolkit/tools/pkg/imagecustomizerlib/testdata/iso-files-and-args-config.yaml
  toolkit/tools/pkg/imagecustomizerlib/testdata/iso-os-prereqs-config.yaml
Labels: Tools

#10072 toolkit: check for parted version before setting partition type
  toolkit/tools/imagegen/diskutils/diskutils.go
Labels: Tools

#10064 nghttp2: upgrade version 1.59.0 -> 1.61.0 to address CVE-2024-28182
  SPECS/nghttp2/nghttp2.signatures.json
  SPECS/nghttp2/nghttp2.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, 3.0-dev

#10058 Bump golang version to 1.22.6-1
  SPECS/golang/golang.signatures.json
  SPECS/golang/golang.spec
  cgmanifest.json
Labels: 3.0-dev

#10074 [cherry-pick to 3.0] Add priorities to local repos
  toolkit/resources/manifests/package/local.repo
Labels: 3.0

#10082 vim: Add patch to resolve CVE-2024-41957 & CVE-2024-41965
  SPECS/vim/CVE-2024-41957.patch
  SPECS/vim/CVE-2024-41965.patch
  SPECS/vim/fix_save_unnamed_buffer_correctly.patch
  SPECS/vim/vim.spec
Labels: security, Packaging, 3.0-dev

#10053 Fix libtdb build issue by upgrading to build with Python 3.12 in 3.0
  SPECS-EXTENDED/libtdb/libtdb.signatures.json
  SPECS-EXTENDED/libtdb/libtdb.spec
  cgmanifest.json
Labels: Packaging, 3.0-dev

#10061 containerized-rpmbuild: switch up strategy for defaults and return command exit codes
  toolkit/scripts/containerized-build/create_container_build.sh
  toolkit/scripts/containerized-build/resources/azl-3_repo
  toolkit/scripts/containerized-build/resources/azl.Dockerfile
  toolkit/scripts/containerized-build/resources/macros.with-check
  toolkit/scripts/containerized-build/resources/setup_functions.sh
Labels: Tools, 3.0-dev

#10091 js-jquery: Patch CVE-2019-20149 in kind-of
  SPECS-EXTENDED/js-jquery/CVE-2019-20149.patch
  SPECS-EXTENDED/js-jquery/js-jquery.spec
Labels: Packaging

#10052 Fixed fast-track's state.
  SPECS/javapackages-bootstrap/CVE-2021-26291.patch
  SPECS/javapackages-bootstrap/javapackages-bootstrap.signatures.json
  SPECS/javapackages-bootstrap/javapackages-bootstrap.spec
  SPECS/libcontainers-common/libcontainers-common.spec
Labels: Packaging

#10020 Ignore bogus case-insensitive provides results from repocloner
  SPECS/perl-Net-SSLeay/perl-Net-SSLeay.spec
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
  toolkit/tools/internal/tdnf/tdnf.go
Labels: bug, Tools, 3.0-dev

#10094 moby-engine: remove daemon.json with backported fix
  SPECS/moby-engine/daemon.json
  SPECS/moby-engine/enable-docker-proxy-libexec-search.patch
  SPECS/moby-engine/moby-engine.signatures.json
  SPECS/moby-engine/moby-engine.spec
Labels: Packaging

#10086 js-jquery: Patch CVE-2019-20149 in kind-of
  SPECS-EXTENDED/js-jquery/CVE-2019-20149.patch
  SPECS-EXTENDED/js-jquery/js-jquery.spec
Labels: security, Packaging, main

#10084 iperf3: upgrade version 3.16 -> 3.17.1 to address CVE-2024-26306
  SPECS/iperf3/iperf3.signatures.json
  SPECS/iperf3/iperf3.spec
  cgmanifest.json
Labels: security, 3.0-dev

#10049 libtiff: Add patch to resolve CVE-2023-6277
  SPECS/libtiff/CVE-2023-6277.patch
  SPECS/libtiff/libtiff.spec
Labels: security, Packaging, 3.0-dev

#10102 Add stress-ng to SPECS-EXTENDED
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS-EXTENDED/stress-ng/stress-ng.signatures.json
  SPECS-EXTENDED/stress-ng/stress-ng.spec
  cgmanifest.json
Labels: Packaging, 3.0-dev

#9991 Fix CVE-2024-6104 in Packer by patching vendor gomodule
  SPECS/packer/CVE-2024-6104.patch
  SPECS/packer/packer.spec
Labels: Packaging, main

#9992 Fix CVE-2024-6104 in Prometheus by patching vendor gomodule
  SPECS/prometheus/CVE-2024-6104.patch
  SPECS/prometheus/prometheus.spec
Labels: Packaging, main

#9993 Fix CVE-2024-6104 in rook by patching vendor gomodule
  SPECS/rook/CVE-2024-6104.patch
  SPECS/rook/rook.spec
Labels: Packaging, main

#9986 Fix CVE-2024-6104 in cri-o by patching vendor package source
  SPECS/cri-o/CVE-2024-6104.patch
  SPECS/cri-o/cri-o.spec
Labels: Packaging, main

#9981 Fix CVE-2024-6104 in cert-manager by patching vendor package sources
  SPECS/cert-manager/CVE-2024-6104.patch
  SPECS/cert-manager/cert-manager.spec
Labels: security, Packaging, main

#9990 Fix CVE-2024-6104 in keda by patching vendor gomodule
  SPECS/keda/CVE-2024-6104.patch
  SPECS/keda/keda.spec
Labels: Packaging, main

#9987 Fix CVE-2024-6104 in influxdb by patching vendor package source
  SPECS/influxdb/CVE-2024-6104.patch
  SPECS/influxdb/influxdb.spec
Labels: Packaging, main

#10108 Fix perl(AutoLoader) capitalization for perl-NetAddr-IP BR
  SPECS/perl-NetAddr-IP/perl-NetAddr-IP.spec
Labels: Packaging, 3.0-dev

#10095 Image Customizer: Improve error message for missing filesystem entry.
  toolkit/tools/imagecustomizerapi/storage.go
  toolkit/tools/imagecustomizerapi/storage_test.go
  toolkit/tools/pkg/imagecustomizerlib/typeConversion.go
Labels: Tools

#10099 Patch CVE-2024-32884 and CVE-2024-31852 in rust
  SPECS/rust/CVE-2024-31852.patch
  SPECS/rust/CVE-2024-32884.patch
  SPECS/rust/rust.spec
Labels: security, Packaging, 3.0-dev

#10115 edk2: not apply patch with warning suppress if azl
  SPECS/edk2/edk2.spec
Labels: Packaging

#10107 busybox: address CVE-2021-42380, CVE-2023-42363, CVE-2023-42364 & CVE-2023-42365
  SPECS/busybox/CVE-2021-42380.patch
  SPECS/busybox/CVE-2023-42363.patch
  SPECS/busybox/CVE-2023-42365.patch
  SPECS/busybox/busybox.spec
Labels: security, Packaging, 3.0-dev

#10106 tpm2-tss: Bump version to 4.0.2 to resolve CVE-2024-29040
  SPECS/tpm2-tss/tpm2-tss.signatures.json
  SPECS/tpm2-tss/tpm2-tss.spec
  cgmanifest.json
Labels: security, 3.0-dev

#10048 libtiff: Add patch to resolve CVE-2023-6277
  SPECS/libtiff/CVE-2023-6277.patch
  SPECS/libtiff/libtiff.spec
Labels: security, Packaging, main

#9953 Fix CVE-2024-41110 in moby-engine
  SPECS/moby-engine/CVE-2024-41110.patch
  SPECS/moby-engine/moby-engine.spec
Labels: security, Packaging, 3.0-dev

#9956 dhcp: Patch bundled bind for CVE-2024-1737 & CVE-2024-1975.
  SPECS/dhcp/CVE-2024-1737.patch
  SPECS/dhcp/CVE-2024-1975.patch
  SPECS/dhcp/dhcp.spec
Labels: Packaging, fasttrack/2.0

#9988 Fix python-twisted CVEs CVE-2024-41671 and CVE-2024-41810 in 2.0
  SPECS/python-twisted/CVE-2024-41671.patch
  SPECS/python-twisted/CVE-2024-41810.patch
  SPECS/python-twisted/python-twisted.spec
Labels: security, Packaging, fasttrack/2.0

#10033 Patch xorg-x11-server for CVE-2024-31080, CVE-2024-31081, CVE-2024-31082 & CVE-2024-31083
  SPECS/xorg-x11-server/Avoid_possible_double-free_in_ProcRenderAddGlyphs.patch
  SPECS/xorg-x11-server/CVE-2024-31080.patch
  SPECS/xorg-x11-server/CVE-2024-31081.patch
  SPECS/xorg-x11-server/CVE-2024-31082.patch
  SPECS/xorg-x11-server/CVE-2024-31083.patch
  SPECS/xorg-x11-server/xorg-x11-server.spec
Labels: Packaging, fasttrack/2.0

#10114 Update kernel-mos to 5.15.164.1
  SPECS-SIGNED/kernel-mos-signed/kernel-mos-signed.spec
  SPECS/kernel-mos/config
  SPECS/kernel-mos/kernel-mos.signatures.json
  SPECS/kernel-mos/kernel-mos.spec
  cgmanifest.json
Labels: main

#10085 Patch rust for CVE-2024-31852 and CVE-2024-32884
  SPECS/rust/CVE-2024-31852.patch
  SPECS/rust/CVE-2024-32884.patch
  SPECS/rust/rust.spec
Labels: security, Packaging, fasttrack/2.0, 2.0

#10063 Fix for CVE 2024 25620 in cert-manager
  SPECS/cert-manager/CVE-2024-25620.patch
  SPECS/cert-manager/cert-manager.spec
Labels: security, Packaging, fasttrack/2.0

#10047 qt5-qtbase: Add patch to resolve CVE-2024-39936.
  SPECS/qt5-qtbase/CVE-2024-39936.patch
  SPECS/qt5-qtbase/qt5-qtbase-5.15-http-encrypted-signal.patch
  SPECS/qt5-qtbase/qt5-qtbase.spec
Labels: Packaging, fasttrack/2.0

#10119 Address CVE-2021-42380, CVE-2023-42363, CVE-2023-42364 & CVE-2023-42365
  SPECS/busybox/CVE-2021-42380.patch
  SPECS/busybox/CVE-2023-42363.patch
  SPECS/busybox/CVE-2023-42365.patch
  SPECS/busybox/busybox.spec
Labels: security, Packaging, fasttrack/2.0

#10037 bind: upgrade version 9.16.48 -> 9.16.50 & patch CVE-2024-1737, CVE-2024-1975 & CVE-2024-4076
  SPECS/bind/CVE-2024-1737.patch
  SPECS/bind/CVE-2024-1975.patch
  SPECS/bind/CVE-2024-4076.patch
  SPECS/bind/bind.signatures.json
  SPECS/bind/bind.spec
  cgmanifest.json
Labels: security, fasttrack/2.0

#10116 Image Customizer: Add check for installed kernel.
  toolkit/tools/pkg/imagecustomizerlib/customizeos.go
  toolkit/tools/pkg/imagecustomizerlib/installedkernelcheck.go
  toolkit/tools/pkg/imagecustomizerlib/installedkernelcheck_test.go
  toolkit/tools/pkg/imagecustomizerlib/testdata/no-kernel-config.yaml
Labels: Tools

#10135 image customizer: fix typos
  toolkit/tools/imagecustomizer/container/build-mic-container.sh
  toolkit/tools/imagecustomizer/container/run-mic-container.sh
  toolkit/tools/pkg/imagecustomizerlib/customizepackages.go
Labels: Tools

#10101 Enable xattr and acl support in coreutils.
  SPECS/coreutils/coreutils.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
Labels: 3.0-dev

#10132 Move grub2-rpm-macros to azurelinux-rpm-macros package
  SPECS-SIGNED/grub2-efi-binary-signed/grub2-efi-binary-signed.spec
  SPECS/azurelinux-rpm-macros/azurelinux-rpm-macros.signatures.json
  SPECS/azurelinux-rpm-macros/azurelinux-rpm-macros.spec
  SPECS/azurelinux-rpm-macros/macros.grub2
  SPECS/grub2/grub2.signatures.json
  SPECS/grub2/grub2.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#10046 Add missing runtime dependencies to `python-poetry-core`.
  SPECS/python-poetry-core/python-poetry-core.spec
Labels: Packaging

#10011 Upgrade `distribution-gpg-keys` to version 1.104, a more recent version that includes the Azure Linux keys.
  SPECS-EXTENDED/distribution-gpg-keys/distribution-gpg-keys.signatures.json
  SPECS-EXTENDED/distribution-gpg-keys/distribution-gpg-keys.spec
  cgmanifest.json
Labels: Packaging

#9914 Don't include epoch in rpm name when resolving conflicts
  toolkit/tools/internal/rpm/rpm.go
  toolkit/tools/internal/rpm/rpm_test.go
Labels: 3.0-dev

#10003 Fix ABI compatibiity errors between `abseil-cpp` and dependent packages.
  SPECS/abseil-cpp/abseil-cpp.spec
  SPECS/grpc/grpc.signatures.json
  SPECS/grpc/grpc.spec
  SPECS/libarrow/libarrow.spec
  SPECS/opentelemetry-cpp/opentelemetry-cpp.spec
  SPECS/protobuf/protobuf.spec
  SPECS/re2/re2.spec
Labels: Packaging

#10146 WaLinuxAgent: Package dracut setup script with WaLinuxAgent
  SPECS/WALinuxAgent/WALinuxAgent.signatures.json
  SPECS/WALinuxAgent/WALinuxAgent.spec
  SPECS/WALinuxAgent/module-setup.sh
Labels: Packaging

#10134 Image Customizer: Account for GPT footer when validating partitions.
  toolkit/tools/imagecustomizerapi/config_test.go
  toolkit/tools/imagecustomizerapi/disk.go
  toolkit/tools/imagecustomizerapi/disk_test.go
  toolkit/tools/imagecustomizerapi/disksize.go
  toolkit/tools/imagecustomizerapi/disksize_test.go
  toolkit/tools/imagecustomizerapi/storage_test.go
Labels: Tools

#10147 image customizer: test mic container script
  toolkit/tools/imagecustomizer/container/test-mic-container.sh
Labels: Tools

#10150 ImageCustomizer: Bugfix Verity dependency handling in Azl3.
  toolkit/tools/pkg/imagecustomizerlib/customizeverity.go
Labels: Tools

#10136 Patch CVE-2024-7006 in libtiff
  SPECS/libtiff/CVE-2024-7006.patch
  SPECS/libtiff/libtiff.spec
Labels: Packaging

#10153 image customizer: fix typos (#10135)
  toolkit/tools/imagecustomizer/container/build-mic-container.sh
  toolkit/tools/imagecustomizer/container/run-mic-container.sh
  toolkit/tools/pkg/imagecustomizerlib/customizepackages.go
Labels: Tools

#10139 Patch CVE-2024-7006 in libtiff
  SPECS/libtiff/CVE-2024-7006.patch
  SPECS/libtiff/libtiff.spec
Labels: Packaging

#10159 image customizer: docs for run.sh
  toolkit/tools/imagecustomizer/docs/container.md
Labels: Tools, 3.0-dev

#10158 Add patch for CVE-2024-43168 in unbound
  SPECS/unbound/CVE-2024-43168.patch
  SPECS/unbound/unbound.spec
Labels: security, Packaging, 3.0-dev

#10071 dracut: Drop dracut multiple confdirs patch
  SPECS/dracut/0007-feat-dracut.sh-support-multiple-config-dirs.patch
  SPECS/dracut/dracut.spec
Labels: Packaging

#10169 gdb: fix package tests
  SPECS/gdb/gdb.spec
Labels: Packaging, ptest, 3.0-dev

#10164 Toolkit: Respect overridden home directory for .ssh path.
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/internal/userutils/main_test.go
  toolkit/tools/internal/userutils/passwdfile.go
  toolkit/tools/internal/userutils/passwdfile_test.go
  toolkit/tools/internal/userutils/testdata/etc/passwd
  toolkit/tools/internal/userutils/userutils.go
  toolkit/tools/internal/userutils/userutils_test.go
Labels: Tools

#10177 Image Customizer: Always refresh RPM repo metadata.
  toolkit/tools/pkg/imagecustomizerlib/customizepackages.go
  toolkit/tools/pkg/imagecustomizerlib/customizepackages_test.go
Labels: Tools

#10163 Fixed `openssh` ptests.
  SPECS/openssh/openssh-8.2p1-visibility.patch
  SPECS/openssh/openssh.spec
Labels: Packaging

#10180 e2fsprogs: fix ptest
  SPECS/e2fsprogs/e2fsprogs.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: ptest, 3.0-dev

#10182 make: fix package tests
  SPECS/make/make.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: ptest, 3.0-dev

#10118 Fix for CVE-2024-25620 in cert-manager
  SPECS/cert-manager/CVE-2024-25620.patch
  SPECS/cert-manager/cert-manager.spec
Labels: security, Packaging, 3.0-dev

#10152 fix: add patch in WALinuxAgent to update setup.py to support azurelinux
  SPECS/WALinuxAgent/WALinuxAgent.spec
  SPECS/WALinuxAgent/update-setup.patch
Labels: Packaging, 3.0-dev

#10117 feat: remove kexec-tools from azure vm definition
  toolkit/imageconfigs/packagelists/azurevm-packages.json
Labels: Schema, 3.0-dev

#8976 Add new package: Mosh to spec-extended
  SPECS-EXTENDED/mosh/mosh.signatures.json
  SPECS-EXTENDED/mosh/mosh.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main, specs-extended, stable-release-2.0

#10193 vim: CVE-2024-43374 (azl 3)
  SPECS/vim/CVE-2024-43374.patch
  SPECS/vim/vim.spec
Labels: security, Packaging, 3.0-dev

#10185 fix: remove libssp files to fix avahi hang
  SPECS/avahi/avahi.spec
Labels: Packaging

#10157 Add patch for CVE-2024-43168 in unbound
  SPECS/unbound/CVE-2024-43168.patch
  SPECS/unbound/unbound.spec
Labels: security, Packaging, main

#10029 Bump frr to 8.5.5 to fix CVE-2024-31950 & CVE-2024-31951
  SPECS/frr/frr.signatures.json
  SPECS/frr/frr.spec
  cgmanifest.json
Labels: security, fasttrack/2.0

#10155 Add patch for CVE-2023-33976 in tensorflow
  SPECS/tensorflow/CVE-2023-33976.patch
  SPECS/tensorflow/tensorflow.spec
Labels: security, Packaging, fasttrack/2.0

#10133 Set ptest retries to 1 for PR package build check.
  .pipelines/prchecks/PackageBuildPRCheck.yml
  .pipelines/templates/PackageBuild.yml
  toolkit/Makefile
  toolkit/scripts/pkggen.mk
  toolkit/tools/scheduler/schedulerutils/buildworker.go
Labels: fasttrack/2.0

#10212 Revert PostGresQL
  SPECS/postgresql/postgresql.service
  SPECS/postgresql/postgresql.signatures.json
  SPECS/postgresql/postgresql.spec
Labels: Packaging

#10179 Image Customizer: Add tests for users API.
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/internal/userutils/groupfile.go
  toolkit/tools/internal/userutils/shadowfile.go
  toolkit/tools/internal/userutils/userutils.go
  toolkit/tools/pkg/imagecustomizerlib/customizeusers.go
  toolkit/tools/pkg/imagecustomizerlib/customizeusers_test.go
Labels: Tools

#10211 python3: CVE-2024-7592 (azl 3)
  SPECS/python3/CVE-2024-7592.patch
  SPECS/python3/python3.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#10209 frr: CVE-2024-44070 (azl 3)
  SPECS/frr/CVE-2024-44070.patch
  SPECS/frr/frr.spec
Labels: Packaging

#10199 Image Customizer: Be robust to lsblk and fdisk output ordering.
  toolkit/tools/pkg/imagecustomizerlib/customizepartitions_test.go
  toolkit/tools/pkg/imagecustomizerlib/extractpartitions.go
  toolkit/tools/pkg/imagecustomizerlib/partitionutils.go
  toolkit/tools/pkg/imagecustomizerlib/shrinkfilesystems.go
Labels: Tools

#10110 Add tdnf Virtual Repo Snapshot via patch
  SPECS/tdnf/tdnf.spec
  SPECS/tdnf/virtual-repo-snapshot.patch
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 3.0-dev

#10210 python3: CVE-2024-7592 (mariner 2)
  SPECS/python3/CVE-2024-7592.patch
  SPECS/python3/python3.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, main

#10217 Toolkit bugfix: update_manifest.sh group name may not allways exist
  toolkit/scripts/update_manifest.sh
Labels: Tools, 3.0-dev

#10231 containerized-rpmbuild: add container image for 3.0
  toolkit/scripts/containerized-build/create_container_build.sh
Labels: Tools, 3.0-dev

#10228 openldap: Add patch to resolve CVE-2023-2953
  SPECS/openldap/CVE-2023-2953.patch
  SPECS/openldap/openldap.spec
Labels: Packaging, fasttrack/2.0

#10208 frr: CVE-2024-44070 (mariner 2)
  SPECS/frr/CVE-2024-44070.patch
  SPECS/frr/frr.spec
Labels: Packaging, main

#10224 moby-cli: Add patch to resolve CVE-2023-45288
  SPECS/moby-cli/CVE-2023-45288.patch
  SPECS/moby-cli/moby-cli.spec
Labels: Packaging, fasttrack/2.0

#10226 jx: Add patch to resolve CVE-2023-45288
  SPECS/jx/CVE-2023-45288.patch
  SPECS/jx/jx.spec
Labels: Packaging, fasttrack/2.0

#10227 rpm-ostree: Add patch to resolve CVE-2023-26964 in vendored h2 sources
  SPECS/rpm-ostree/CVE-2023-26964.patch
  SPECS/rpm-ostree/rpm-ostree.spec
Labels: Packaging, fasttrack/2.0

#10242 libsndfile: Add patch to resolve CVE-2022-33065
  SPECS/libsndfile/CVE-2022-33065.patch
  SPECS/libsndfile/libsndfile.spec
Labels: security, Packaging, 3.0

#10222 Toolkit: Fix readdirent toolchain errors for reusable chroots
  toolkit/scripts/toolchain.mk
Labels: bug, Tools, 3.0-dev

#10070 dracut: Drop disable-xattr dracut patch, introduce config to optionally enable it
  SPECS/dracut/0002-disable-xattr.patch
  SPECS/dracut/50-noxattr.conf
  SPECS/dracut/dracut.signatures.json
  SPECS/dracut/dracut.spec
Labels: Packaging

#10240 fix: change bfq patch to select "none" scheduler as default
  SPECS-SIGNED/systemd-boot-signed/systemd-boot-signed.spec
  SPECS/systemd/systemd.spec
  SPECS/systemd/use-none-scheduler.patch
Labels: Packaging, 3.0-dev

#10251 Bump Mariner 2.0 Release for September 2024 update
  SPECS/mariner-release/mariner-release.spec
Labels: Packaging, main

#10252 Add missing shadow-utils requirement to ceph
  SPECS/ceph/ceph.spec
Labels: Packaging, main

#10245 sysstat: upgrade 12.7.4 -> 12.7.6 to address CVE-2018-19416
  SPECS/sysstat/sysstat.signatures.json
  SPECS/sysstat/sysstat.spec
  cgmanifest.json
Labels: security, 3.0-dev

#10181 libnbd: CVE-2024-7383 (azl 3)
  SPECS/libnbd/CVE-2024-7383.patch
  SPECS/libnbd/libnbd.spec
Labels: security, Packaging, 3.0-dev

#10109 Upgrade and build samba in 3.0
  SPECS-EXTENDED/samba/0001-Disable-building-smb.conf.5-in-docs-xml-wscript.patch
  SPECS-EXTENDED/samba/samba-4.12.5.tar.asc
  SPECS-EXTENDED/samba/samba.signatures.json
  SPECS-EXTENDED/samba/samba.spec
  cgmanifest.json
Labels: specs-extended, 3.0-dev

#10216 cert-manager: Address CVE-2023-3978, CVE-2024-24786, CVE-2024-28180, CVE-2023-2253
  SPECS/cert-manager/CVE-2023-2253.patch
  SPECS/cert-manager/CVE-2023-3978.patch
  SPECS/cert-manager/CVE-2024-24786.patch
  SPECS/cert-manager/CVE-2024-28180.patch
  SPECS/cert-manager/cert-manager.spec
Labels: Packaging, main

#10221 edk2: Deprecate hvloader; introduce edk2-hvloader
  .github/CODEOWNERS
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS/edk2/edk2.signatures.json
  SPECS/edk2/edk2.spec
  SPECS/edk2/hvloader-target.txt
  SPECS/hvloader/hvloader.signatures.json
  SPECS/hvloader/hvloader.spec
Labels: Packaging

#10233 port perl modules from extended to core
  SPECS/perl-B-Hooks-OP-Check/perl-B-Hooks-OP-Check.signatures.json
  SPECS/perl-B-Hooks-OP-Check/perl-B-Hooks-OP-Check.spec
  SPECS/perl-ExtUtils-Depends/perl-ExtUtils-Depends.signatures.json
  SPECS/perl-ExtUtils-Depends/perl-ExtUtils-Depends.spec
  SPECS/perl-multidimensional/perl-multidimensional.signatures.json
  SPECS/perl-multidimensional/perl-multidimensional.spec
Labels: Packaging, 3.0-dev

#10258 port perl module from extended into core: part-3
  SPECS/perl-Class-XSAccessor/perl-Class-XSAccessor.signatures.json
  SPECS/perl-Class-XSAccessor/perl-Class-XSAccessor.spec
  SPECS/perl-Devel-CheckBin/perl-Devel-CheckBin.signatures.json
  SPECS/perl-Devel-CheckBin/perl-Devel-CheckBin.spec
  SPECS/perl-Import-Into/perl-Import-Into.signatures.json
  SPECS/perl-Import-Into/perl-Import-Into.spec
  SPECS/perl-Module-Runtime/perl-Module-Runtime.signatures.json
  SPECS/perl-Module-Runtime/perl-Module-Runtime.spec
  SPECS/perl-Sub-Name/perl-Sub-Name.signatures.json
  SPECS/perl-Sub-Name/perl-Sub-Name.spec
  SPECS/perl-Sub-Quote/perl-Sub-Quote.signatures.json
  SPECS/perl-Sub-Quote/perl-Sub-Quote.spec
Labels: Packaging, 3.0-dev

#10259 move perl-indirect from extended to core
  SPECS/perl-indirect/perl-indirect.signatures.json
  SPECS/perl-indirect/perl-indirect.spec
Labels: Packaging, 3.0-dev

#10254 unbound: Add patch to resolve CVE-2024-33655
  SPECS/unbound/CVE-2024-33655.patch
  SPECS/unbound/unbound.spec
Labels: security, Packaging, 3.0-dev

#10225 jx: Add patch to resolve CVE-2023-45288
  SPECS/jx/CVE-2023-45288.patch
  SPECS/jx/jx.spec
Labels: security, Packaging, 3.0-dev

#10206 multus: Add patch to resolve CVE-2023-3978
  SPECS/multus/CVE-2023-3978.patch
  SPECS/multus/multus.spec
Labels: security, Packaging, 3.0-dev

#10255 Fix nfs-utils to build rsc.svcgssd and provide the missing rpc-gssd service
  SPECS/nfs-utils/nfs-utils.spec
Labels: Packaging, main, stable-release-2.0

#10256 Fix nfs-utils to build rsc.svcgssd and provide the missing rpc-gssd
  SPECS/nfs-utils/nfs-utils.spec
Labels: Packaging, 3.0-dev

#9994 Fix CVE-2024-6104 in cert-manager by patching vendor gomodules
  SPECS/cert-manager/CVE-2024-6104.patch
  SPECS/cert-manager/cert-manager.spec
Labels: security, Packaging, 3.0-dev

#10260 port perl module from extended into core: part-4
  SPECS/perl-Data-OptList/perl-Data-OptList.signatures.json
  SPECS/perl-Data-OptList/perl-Data-OptList.spec
  SPECS/perl-Devel-GlobalDestruction-XS/perl-Devel-GlobalDestruction-XS.signatures.json
  SPECS/perl-Devel-GlobalDestruction-XS/perl-Devel-GlobalDestruction-XS.spec
  SPECS/perl-Package-Generator/Package-Generator-1.106-old-Test-More.patch
  SPECS/perl-Package-Generator/perl-Package-Generator.signatures.json
  SPECS/perl-Package-Generator/perl-Package-Generator.spec
  SPECS/perl-Params-Util/perl-Params-Util.signatures.json
  SPECS/perl-Params-Util/perl-Params-Util.spec
  SPECS/perl-Sub-Exporter/perl-Sub-Exporter.signatures.json
  SPECS/perl-Sub-Exporter/perl-Sub-Exporter.spec
  SPECS/perl-Sub-Install/perl-Sub-Install.signatures.json
  SPECS/perl-Sub-Install/perl-Sub-Install.spec
Labels: Packaging

#10006 feat: enable USB_TMC as module
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#10247 cloud-hypervisor-cvm: Add upstream patch to prevent crash when SEV-SNP guest queries ext. att. report
  SPECS/cloud-hypervisor-cvm/0001-hypervisor-mshv-Fix-panic-when-rejecting-extended-gu.patch
  SPECS/cloud-hypervisor-cvm/cloud-hypervisor-cvm.spec
Labels: Packaging, main

#10272 port perl modules from extended into core - part 6
  SPECS/perl-Class-ISA/perl-Class-ISA.signatures.json
  SPECS/perl-Class-ISA/perl-Class-ISA.spec
  SPECS/perl-Devel-Hide/perl-Devel-Hide.signatures.json
  SPECS/perl-Devel-Hide/perl-Devel-Hide.spec
  SPECS/perl-Test-Output/perl-Test-Output.signatures.json
  SPECS/perl-Test-Output/perl-Test-Output.spec
  SPECS/perl-Test-Requires/perl-Test-Requires.signatures.json
  SPECS/perl-Test-Requires/perl-Test-Requires.spec
Labels: Packaging, 3.0-dev

#10271 port perl-IO-String from extended into core
  SPECS/perl-IO-String/perl-IO-String.signatures.json
  SPECS/perl-IO-String/perl-IO-String.spec
Labels: Packaging, 3.0-dev

#10268 move perl strictures and bareword-filehandles
  SPECS/perl-bareword-filehandles/perl-bareword-filehandles.signatures.json
  SPECS/perl-bareword-filehandles/perl-bareword-filehandles.spec
  SPECS/perl-strictures/perl-strictures.signatures.json
  SPECS/perl-strictures/perl-strictures.spec
Labels: Packaging, 3.0-dev

#10194 nginx: Address CVE-2024-7347
  SPECS/nginx/CVE-2024-7347.patch
  SPECS/nginx/nginx.spec
Labels: Packaging, 3.0-dev

#10190 nginx: Address CVE-2024-7347
  SPECS/nginx/CVE-2024-7347.patch
  SPECS/nginx/nginx.spec
Labels: Packaging, main
