Repository microsoft/azurelinux, pull requests merged in 2024-06, with the labels that each got.

#9282 upgrade rubygem-rexml to 3.2.7 to resolve CVE-2024-35176
  SPECS/rubygem-rexml/CVE-2024-35176.patch
  SPECS/rubygem-rexml/rubygem-rexml.signatures.json
  SPECS/rubygem-rexml/rubygem-rexml.spec
  cgmanifest.json
Labels: main

#9276 Patch moby-engine to address CVE-2023-44487
  SPECS/moby-engine/CVE-2023-44487.patch
  SPECS/moby-engine/moby-engine.spec
Labels: main

#9249 helm: patch cve-2024-25620
  SPECS/cert-manager/cert-manager.spec
  SPECS/helm/CVE-2024-25620.patch
  SPECS/helm/helm.spec
Labels: security, 3.0

#9265 cmake address CVE-2024-24806
  SPECS/cmake/CVE-2024-24806.patch
  SPECS/cmake/cmake.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, 3.0

#7564 Add stable release maintainers to CODEOWNERS
  .github/CODEOWNERS
Labels: main

#9259 Fix fluent-bit CVE-2024-34250 with a patch
  SPECS/fluent-bit/CVE-2024-34250.patch
  SPECS/fluent-bit/fluent-bit.spec
Labels: security, fasttrack/2.0

#9229 reaper: address CVE-2024-4068
  SPECS/reaper/CVE-2018-11694.patch
  SPECS/reaper/CVE-2022-37601.patch
  SPECS/reaper/CVE-2023-26159.patch
  SPECS/reaper/CVE-2023-28155.patch
  SPECS/reaper/reaper.signatures.json
  SPECS/reaper/reaper.spec
Labels: fasttrack/2.0

#9273 Upgrade openvswitch to 2.17.9 to fix CVE-2023-5366 and CVE-2023-3966
  SPECS/openvswitch/CVE-2023-1668.patch
  SPECS/openvswitch/openvswitch.signatures.json
  SPECS/openvswitch/openvswitch.spec
  cgmanifest.json
Labels: security, fasttrack/2.0

#9258 Patch apparmor for CVE-2024-31755
  SPECS/apparmor/CVE-2024-31755.patch
  SPECS/apparmor/apparmor.spec
Labels: security, fasttrack/2.0

#9243 Patch dhcp for CVE-2023-2828
  SPECS/dhcp/CVE-2023-2828.patch
  SPECS/dhcp/dhcp.spec
Labels: fasttrack/2.0

#9263 containerized-rpmbuild: enable azurelinux-official-base for 3.0
  toolkit/scripts/containerized-build/resources/setup_functions.sh
Labels: DevEx, 3.0

#9309 openssl: only free buffers when done
  SPECS/openssl/openssl-1.1.1-Only-free-the-read-buffers-if-we-re-not-using-them.patch
  SPECS/openssl/openssl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#9261 kata(-cc): upgrade to LSG release v2405.9.2
  SPECS-SIGNED/kernel-mshv-signed/kernel-mshv-signed.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/cloud-hypervisor-cvm/cloud-hypervisor-cvm.signatures.json
  SPECS/cloud-hypervisor-cvm/cloud-hypervisor-cvm.spec
  SPECS/cloud-hypervisor-cvm/config.toml
  SPECS/cloud-hypervisor/cloud-hypervisor.signatures.json
  SPECS/cloud-hypervisor/cloud-hypervisor.spec
  SPECS/kata-containers-cc/kata-containers-cc.signatures.json
  SPECS/kata-containers-cc/kata-containers-cc.spec
  SPECS/kata-containers/kata-containers.signatures.json
  SPECS/kata-containers/kata-containers.spec
  SPECS/kernel-mshv/config
  SPECS/kernel-mshv/kernel-mshv.signatures.json
  SPECS/kernel-mshv/kernel-mshv.spec
  SPECS/kernel-uvm/config
  SPECS/kernel-uvm/kernel-uvm.signatures.json
  SPECS/kernel-uvm/kernel-uvm.spec
  cgmanifest.json
Labels: main

#9311 Check if gpgconf is in chroot, not host env, when cleaning up chroot
  toolkit/tools/internal/safechroot/safechroot.go
Labels: bug, Tools, 3.0

#9307 Use local http server for unit tests
  toolkit/tools/internal/network/network_test.go
Labels: Tools, 3.0

#9274 ig: Bump version to v0.29.0.
  SPECS/ig/ig.signatures.json
  SPECS/ig/ig.spec
  cgmanifest.json
Labels: 3.0

#9328 Update prerequisites with jq
  toolkit/docs/building/prerequisites-mariner.md
  toolkit/docs/building/prerequisites-ubuntu.md
Labels: 3.0

#9121 Fix Fluent-bit issues #8198 and #8025
  SPECS/fluent-bit/fix_issue_8025.patch
  SPECS/fluent-bit/fluent-bit.spec
  SPECS/fluent-bit/in_emitter_fix_issue_8198.patch
Labels: main

#9294 Enable protobuf ptest
  SPECS/protobuf/protobuf.spec
Labels: 3.0

#9095 selinux-policy: Add fixes from BVT and baremetal image
  SPECS/selinux-policy/0027-systemd-Add-basic-systemd-analyze-rules.patch
  SPECS/selinux-policy/0028-cloudinit-Add-support-for-cloud-init-growpart.patch
  SPECS/selinux-policy/0029-filesystem-systemd-memory.pressure-fixes.patch
  SPECS/selinux-policy/0030-init-Add-homectl-dbus-access.patch
  SPECS/selinux-policy/0031-Temporary-workaround-for-memory.pressure-labeling-is.patch
  SPECS/selinux-policy/0032-rpm-Fixes-from-various-post-scripts.patch
  SPECS/selinux-policy/booleans_targeted.conf
  SPECS/selinux-policy/selinux-policy.signatures.json
  SPECS/selinux-policy/selinux-policy.spec
  toolkit/imageconfigs/packagelists/selinux.json
Labels: 3.0

#9358 Upgrade kernel to 5.15.158.2
  SPECS-SIGNED/kernel-azure-signed/kernel-azure-signed.spec
  SPECS-SIGNED/kernel-hci-signed/kernel-hci-signed.spec
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/hyperv-daemons/CVE-2024-35848.nopatch
  SPECS/hyperv-daemons/hyperv-daemons.signatures.json
  SPECS/hyperv-daemons/hyperv-daemons.spec
  SPECS/kernel-azure/config
  SPECS/kernel-azure/config_aarch64
  SPECS/kernel-azure/kernel-azure.signatures.json
  SPECS/kernel-azure/kernel-azure.spec
  SPECS/kernel-hci/config
  SPECS/kernel-hci/kernel-hci.signatures.json
  SPECS/kernel-hci/kernel-hci.spec
  SPECS/kernel-headers/kernel-headers.signatures.json
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/CVE-2024-26900.nopatch
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#9359 python-cryptography: Update OpenSSL version to fix CVE-2023-50782
  SPECS/python-cryptography/python-cryptography.spec
Labels: main

#9356 Update kernel-mos to 5.15.158.2
  SPECS-SIGNED/kernel-mos-signed/kernel-mos-signed.spec
  SPECS/kernel-mos/config
  SPECS/kernel-mos/kernel-mos.signatures.json
  SPECS/kernel-mos/kernel-mos.spec
  cgmanifest.json
Labels: main

#9348 Upgrade azl-compliance to version 1.0.2
  SPECS/azl-compliance/azl-compliance.signatures.json
  SPECS/azl-compliance/azl-compliance.spec
  cgmanifest.json
Labels: main

#9284 Fix CVE-2024-3154 in package cri-o
  SPECS/cri-o/CVE-2024-3154.patch
  SPECS/cri-o/cri-o.spec
Labels: main

#9325 Improve handling of preview repo files
  toolkit/.gitignore
  toolkit/Makefile
  toolkit/scripts/imggen.mk
  toolkit/scripts/pkggen.mk
  toolkit/scripts/precache.mk
  toolkit/scripts/preview.mk
  toolkit/scripts/repoquerywrapper.mk
Labels: Tools, DevEx, 3.0

#9210 Remove requirement on awk for dracut device caching
  SPECS/dracut/0012-fix-dracut-functions-avoid-awk-in-get_maj_min.patch
  SPECS/dracut/dracut.spec
Labels: bug, Packaging, 3.0

#9335 edk2: add patch for CVE-2024-1298
  SPECS/edk2/CVE-2024-1298.patch
  SPECS/edk2/edk2.spec
Labels: security, main

#9337 hvloader: add patch to resolve CVE-2024-1298
  SPECS-SIGNED/hvloader-signed/hvloader-signed.spec
  SPECS/hvloader/CVE-2024-1298.patch
  SPECS/hvloader/hvloader.spec
Labels: main

#9383 toolkit: bump azidentity 1.3.1 -> 1.6.0 to address Auth Lib Privilege
  toolkit/tools/go.mod
  toolkit/tools/go.sum
Labels: security, 3.0

#9377 php: udpate to v8.3.8 to fix CVEs
  SPECS/php/php.signatures.json
  SPECS/php/php.spec
  cgmanifest.json
Labels: security, 3.0

#9340 libarchive: add patch to resolve CVE-2024-26256
  SPECS/libarchive/CVE-2024-26256.patch
  SPECS/libarchive/libarchive.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#9369 php: update to 8.1.29 to fix CVEs
  SPECS/php/php.signatures.json
  SPECS/php/php.spec
  cgmanifest.json
Labels: security, fasttrack/2.0

#9343 Address CVE-2024-3727 by patching vendored github.com/containers/image
  SPECS/containerized-data-importer/CVE-2024-3727.patch
  SPECS/containerized-data-importer/containerized-data-importer.spec
Labels: main

#9392 Update conntrack-tools and dependency
  SPECS/conntrack-tools/conntrack-tools.signatures.json
  SPECS/conntrack-tools/conntrack-tools.spec
  SPECS/libnetfilter_conntrack/libnetfilter_conntrack.signatures.json
  SPECS/libnetfilter_conntrack/libnetfilter_conntrack.spec
  cgmanifest.json
Labels: fasttrack/2.0

#9417 kata-containers(-cc): enable sandbox_cgroup_only to support cgroupv2
  SPECS/kata-containers-cc/kata-containers-cc.spec
  SPECS/kata-containers/kata-containers.spec
Labels: 3.0

#9400 Fix ordering issues with new preview repo handling in derivative builds
  toolkit/scripts/preview.mk
Labels: 3.0

#9404 Patch CVE-2024-5742 in nano
  SPECS/nano/CVE-2024-5742.patch
  SPECS/nano/nano.spec
Labels: security, main

#9395 vte291: patch CVE-2024-37535
  SPECS/vte291/CVE-2024-37535.patch
  SPECS/vte291/vte291.spec
Labels: security, fasttrack/2.0

#9372 nodejs18: upgrade nodejs18 to 18.20.3 to fix CVE-2024-28863
  SPECS/nodejs/nodejs18.signatures.json
  SPECS/nodejs/nodejs18.spec
  cgmanifest.json
Labels: main

#9433 yasm: patch CVE-2021-33454
  SPECS/yasm/CVE-2021-33454.patch
  SPECS/yasm/yasm.spec
Labels: main

#9426 telegraf: patch CVE-2024-35255
  SPECS/telegraf/CVE-2024-35255.patch
  SPECS/telegraf/telegraf.spec
Labels: main

#9428 mysql: upgrade to 8.0.36 to fix 10 CVEs
  SPECS/mysql/mysql.signatures.json
  SPECS/mysql/mysql.spec
  cgmanifest.json
Labels: main

#9430 Remove locales from core images, add documentation on restoring locales
  toolkit/docs/formats/imageconfig.md
  toolkit/imageconfigs/core-efi.json
  toolkit/imageconfigs/core-legacy.json
Labels: documentation, 3.0

#9425 Patch bash to load startup files when invoked with '-bash'
  SPECS/bash/bash-2.03-profile.patch
  SPECS/bash/bash.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: bug, Packaging, 3.0

#9345 add script to update toolchain and package manifest
  toolkit/scripts/update_toolchain_manifest.py
Labels: DevEx, 3.0

#9466 [3.0] mariadb: patch CVE-2024-0901
  SPECS/mariadb/CVE-2024-0901.patch
  SPECS/mariadb/mariadb.spec
Labels: security, 3.0

#9467 [3.0] bluez: patch CVE-2023-50229 and CVE-2023-50230
  SPECS/bluez/CVE-2023-50229-CVE-2023-50230.patch
  SPECS/bluez/bluez.spec
Labels: security, 3.0

#9455 Fix CVE-2024-3727 in skopeo
  SPECS/skopeo/CVE-2024-3727.patch
  SPECS/skopeo/skopeo.spec
Labels: security, fasttrack/2.0

#9352 msft-golang: upgrade version 1.22.3 -> 1.22.4 to address CVE-2024-24790
  SPECS/msft-golang/msft-golang.signatures.json
  SPECS/msft-golang/msft-golang.spec
  cgmanifest.json
Labels: security, main

#9474 Address kernel CVE-2022-48670, CVE-2024-26583, CVE-2024-26584, CVE-2024-26585, CVE-2024-36023, CVE-2024-36897, CVE-2024-36902, CVE-2024-36938, CVE-2024-36971
  SPECS/kernel/CVE-2022-48670.nopatch
  SPECS/kernel/CVE-2024-26583.nopatch
  SPECS/kernel/CVE-2024-26584.nopatch
  SPECS/kernel/CVE-2024-26585.nopatch
  SPECS/kernel/CVE-2024-36023.nopatch
  SPECS/kernel/CVE-2024-36897.nopatch
  SPECS/kernel/CVE-2024-36902.nopatch
  SPECS/kernel/CVE-2024-36938.nopatch
  SPECS/kernel/CVE-2024-36971.nopatch
Labels: security, main

#9499 c-ares: update to v1.30.0 to fix CVE-2024-25629
  SPECS/c-ares/c-ares.signatures.json
  SPECS/c-ares/c-ares.spec
  cgmanifest.json
Labels: security, 3.0

#9496 Remove fapolicyd package
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS-EXTENDED/fapolicyd/fapolicyd.signatures.json
  SPECS-EXTENDED/fapolicyd/fapolicyd.spec
  cgmanifest.json
Labels: 3.0, Azure Linux 3.0

#9490 azurelinux-sysinfo: add libselinux-utils as a requirement
  SPECS/azurelinux-sysinfo/azurelinux-sysinfo.spec
Labels: 3.0

#9503 Remove isorelax project from 2.0 Extended
  SPECS-EXTENDED/isorelax/isorelax-20030108.pom
  SPECS-EXTENDED/isorelax/isorelax-build.xml
  SPECS-EXTENDED/isorelax/isorelax-java5-compatibility.patch
  SPECS-EXTENDED/isorelax/isorelax-maven-project.xml
  SPECS-EXTENDED/isorelax/isorelax-maven-project.xsd
  SPECS-EXTENDED/isorelax/isorelax.signatures.json
  SPECS-EXTENDED/isorelax/isorelax.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: main

#9492 elfutils: use more secure ptrace scope configuration by default
  SPECS/elfutils/10-ptrace-yama.conf
  SPECS/elfutils/elfutils.signatures.json
  SPECS/elfutils/elfutils.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 3.0

#9491 Image Customizer: Add SELinux tests.
  toolkit/tools/pkg/imagecustomizerlib/customizeutils_test.go
  toolkit/tools/pkg/imagecustomizerlib/testdata/partitions-selinux-enforcing.yaml
  toolkit/tools/pkg/imagecustomizerlib/testdata/selinux-enforcing-nopackages.yaml
Labels: 3.0

#9374 Upgrade vitess to v17.0.7 to fix CVE-2024-32886
  SPECS/vitess/CVE-2023-44487.patch
  SPECS/vitess/CVE-2023-45288.patch
  SPECS/vitess/vitess.signatures.json
  SPECS/vitess/vitess.spec
  cgmanifest.json
Labels: main

#9493 Remove original cloud-hypervisor package
  .github/CODEOWNERS
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS/cloud-hypervisor-cvm/cloud-hypervisor-cvm.spec
  SPECS/cloud-hypervisor/cloud-hypervisor.signatures.json
  SPECS/cloud-hypervisor/cloud-hypervisor.spec
  SPECS/cloud-hypervisor/config.toml
  cgmanifest.json
Labels: 3.0

#9494 fix: remove override_glibc logic from libxcrypt
  SPECS/libxcrypt/libxcrypt.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 3.0

#9382 toolkit: bump azidentity 1.3.1 -> 1.6.0 to address CVE-2024-35255
  toolkit/tools/go.mod
  toolkit/tools/go.sum
Labels: security, main

#9504 libarchive: update to v3.7.4 to fix CVEs 2024-26256 and 2024-37407
  SPECS/libarchive/CVE-2024-26256.patch
  SPECS/libarchive/CVE-2024-37407.patch
  SPECS/libarchive/libarchive.signatures.json
  SPECS/libarchive/libarchive.spec
  SPECS/libarchive/update-appledouble-support-directories.patch
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, 3.0

#9349 Removed 'libdb' deps from multiple packages.
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS-EXTENDED/bogofilter/bogofilter.signatures.json
  SPECS-EXTENDED/bogofilter/bogofilter.spec
  SPECS-EXTENDED/libdbi-drivers/libdbi-drivers-aarch64.patch
  SPECS-EXTENDED/libdbi-drivers/libdbi-drivers.signatures.json
  SPECS-EXTENDED/libdbi-drivers/libdbi-drivers.spec
  SPECS-EXTENDED/perl-BDB/perl-BDB.signatures.json
  SPECS-EXTENDED/perl-BDB/perl-BDB.spec
  SPECS-EXTENDED/redland/redland.signatures.json
  SPECS-EXTENDED/redland/redland.spec
  SPECS-EXTENDED/sendmail/Sendmail-sasl2.conf
  SPECS-EXTENDED/sendmail/sendmail-8.13.0-cyrus.patch
  SPECS-EXTENDED/sendmail/sendmail-8.14.3-sharedmilter.patch
  SPECS-EXTENDED/sendmail/sendmail-8.14.3-smrsh_paths.patch
  SPECS-EXTENDED/sendmail/sendmail-8.14.4-makemapman.patch
  SPECS-EXTENDED/sendmail/sendmail-8.14.8-sasl2-in-etc.patch
  SPECS-EXTENDED/sendmail/sendmail-8.14.9-noversion.patch
  SPECS-EXTENDED/sendmail/sendmail-8.14.9-pid.patch
  SPECS-EXTENDED/sendmail/sendmail-8.14.9-vacation.patch
  SPECS-EXTENDED/sendmail/sendmail-8.15.1-aliases_dir.patch
  SPECS-EXTENDED/sendmail/sendmail-8.15.1-dynamic.patch
  SPECS-EXTENDED/sendmail/sendmail-8.15.1-manpage.patch
  SPECS-EXTENDED/sendmail/sendmail-8.15.2-fix-covscan-issues.patch
  SPECS-EXTENDED/sendmail/sendmail-8.15.2-format-security.patch
  SPECS-EXTENDED/sendmail/sendmail-8.15.2-gcc-10-fix.patch
  SPECS-EXTENDED/sendmail/sendmail-8.15.2-gethostbyname2.patch
  SPECS-EXTENDED/sendmail/sendmail-8.15.2-libmilter-socket-activation.patch
  SPECS-EXTENDED/sendmail/sendmail-8.15.2-localdomain.patch
  SPECS-EXTENDED/sendmail/sendmail-8.15.2-openssl-1.1.0-ecdhe-fix.patch
  SPECS-EXTENDED/sendmail/sendmail-8.15.2-openssl-1.1.0-fix.patch
  SPECS-EXTENDED/sendmail/sendmail-8.15.2-qos.patch
  SPECS-EXTENDED/sendmail/sendmail-8.15.2-smtp-session-reuse-fix.patch
  SPECS-EXTENDED/sendmail/sendmail-8.15.2-switchfile.patch
  SPECS-EXTENDED/sendmail/sendmail-etc-mail-access
  SPECS-EXTENDED/sendmail/sendmail-etc-mail-domaintable
  SPECS-EXTENDED/sendmail/sendmail-etc-mail-local-host-names
  SPECS-EXTENDED/sendmail/sendmail-etc-mail-mailertable
  SPECS-EXTENDED/sendmail/sendmail-etc-mail-trusted-users
  SPECS-EXTENDED/sendmail/sendmail-etc-mail-virtusertable
  SPECS-EXTENDED/sendmail/sendmail-redhat.mc
  SPECS-EXTENDED/sendmail/sendmail.etc-mail-Makefile
  SPECS-EXTENDED/sendmail/sendmail.etc-mail-make
  SPECS-EXTENDED/sendmail/sendmail.nm-dispatcher
  SPECS-EXTENDED/sendmail/sendmail.pam
  SPECS-EXTENDED/sendmail/sendmail.service
  SPECS-EXTENDED/sendmail/sendmail.signatures.json
  SPECS-EXTENDED/sendmail/sendmail.spec
  SPECS-EXTENDED/sendmail/sendmail.sysconfig
  SPECS-EXTENDED/sendmail/sm-client.service
  SPECS/apr-util/apr-util-1.6.3-lmdb-support.patch
  SPECS/apr-util/apr-util.spec
  SPECS/httpd/httpd.spec
  SPECS/iproute/iproute.spec
  SPECS/libguestfs/libguestfs.spec
  SPECS/libserf/libserf.spec
  SPECS/nss/nss.spec
  SPECS/postfix/postfix.spec
  cgmanifest.json
Labels: 3.0

#9537 Deprecate old read-only root support.
  toolkit/imageconfigs/read-only-root-efi.json
  toolkit/tools/imageconfigvalidator/imageconfigvalidator_test.go
  toolkit/tools/imagegen/configuration/systemconfig_test.go
  toolkit/tools/imagegen/configuration/veritydisk.go
  toolkit/tools/imagegen/configuration/veritydisk_test.go
Labels: bug, Tools, 3.0
