Repository microsoft/azurelinux, pull requests merged in 2024-03, with the labels that each got.

#7516 imagecustomizer: initial OverlayFS enablement.
  toolkit/tools/go.mod
  toolkit/tools/go.sum
  toolkit/tools/imagecustomizerapi/identifiedpartition.go
  toolkit/tools/imagecustomizerapi/identifiedpartition_test.go
  toolkit/tools/imagecustomizerapi/overlay.go
  toolkit/tools/imagecustomizerapi/overlay_test.go
  toolkit/tools/imagecustomizerapi/systemconfig.go
  toolkit/tools/imagecustomizerapi/systemconfig_test.go
  toolkit/tools/imagecustomizerapi/verity.go
  toolkit/tools/imagecustomizerapi/verity_test.go
  toolkit/tools/pkg/imagecustomizerlib/customizeoverlay.go
  toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
Labels: 3.0

#7319 Upgrade qemu to v8.2.0
  SPECS/qemu/0001-acpi-fix-QEMU-crash-when-started-with-SLIC-table.patch
  SPECS/qemu/0001-ebpf-replace-deprecated-bpf_program__set_socket_filt.patch
  SPECS/qemu/0001-pc-bios-optionrom-Fix-pvh.img-ld-build-failure-on-fe.patch
  SPECS/qemu/0001-removed-tulip.c-from-build-process-due-to-CVE-2022-2962.patch
  SPECS/qemu/0001-sgx-stub-fix.patch
  SPECS/qemu/0001-tools-virtiofsd-Add-rseq-syscall-to-the-seccomp-allo.patch
  SPECS/qemu/0002-virtiofsd-Do-not-support-blocking-flock.patch
  SPECS/qemu/CVE-2021-20255.patch
  SPECS/qemu/CVE-2021-3750.patch
  SPECS/qemu/CVE-2021-3929.patch
  SPECS/qemu/CVE-2021-4158.patch
  SPECS/qemu/CVE-2021-4206.patch
  SPECS/qemu/CVE-2021-4207.patch
  SPECS/qemu/CVE-2022-0358.patch
  SPECS/qemu/CVE-2022-1050.patch
  SPECS/qemu/CVE-2022-26353.patch
  SPECS/qemu/CVE-2022-26354.patch
  SPECS/qemu/CVE-2022-2962.nopatch
  SPECS/qemu/CVE-2022-3165.patch
  SPECS/qemu/CVE-2022-35414.patch
  SPECS/qemu/CVE-2022-36648.patch
  SPECS/qemu/CVE-2022-3872.patch
  SPECS/qemu/CVE-2022-4144.patch
  SPECS/qemu/disable_qos_test.patch
  SPECS/qemu/fixing-glibc-struct-statx-usage.patch
  SPECS/qemu/qemu.signatures.json
  SPECS/qemu/qemu.spec
  cgmanifest.json
Labels: 3.0

#7672 wget: upgrade version 1.21.2 -> 2.1.0
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/wget/0001-src-log.c-log_init-Redirect-INFO-logs-to-stderr-with.patch
  SPECS/wget/wget.signatures.json
  SPECS/wget/wget.spec
  cgmanifest.json
Labels: 3.0

#8184 Kata-CC: upgrade kernel-uvm and kata-conatainers-cc for LSG release v2402.26.1
  SPECS/kata-containers-cc/kata-containers-cc.spec
  SPECS/kernel-uvm/config
  SPECS/kernel-uvm/kernel-uvm.signatures.json
  SPECS/kernel-uvm/kernel-uvm.spec
  cgmanifest.json
Labels: main

#8216 fix logging in rpmtool
  toolkit/tools/internal/rpm/rpm.go
  toolkit/tools/internal/rpm/rpm_test.go
Labels: Tools, 3.0

#8234 Nopatch CVE-2024-0775
  SPECS/kernel/CVE-2024-0775.nopatch
Labels: security, main

#8206 fix logging in diskutils
  toolkit/tools/imagegen/diskutils/diskutils.go
  toolkit/tools/imagegen/diskutils/encryption.go
Labels: Tools, 3.0

#8235 Cherry-pick: Write fstab file in correct order. (#8217)
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/imager/imager.go
  toolkit/tools/pkg/imagecustomizerlib/imageutils.go
Labels: main

#8244 Add patch to limit pytest-mypy-plugins version for python-attrs test
  SPECS/python-attrs/0001-add-version-limits.patch
  SPECS/python-attrs/python-attrs.spec
Labels: main

#8230 clamav: Patch CVE-2024-20328
  SPECS/clamav/CVE-2024-20328.patch
  SPECS/clamav/clamav.spec
Labels: main

#8233 xorg-x11-server: patch CVE-2024-21885
  SPECS/xorg-x11-server/CVE-2024-21885.patch
  SPECS/xorg-x11-server/xorg-x11-server.spec
Labels: main

#8265 Add missing dependency protobuf-c static subpackage.
  SPECS/protobuf-c/protobuf-c.spec
Labels: 3.0

#8218 fix logging in chroot tools
  toolkit/tools/internal/safechroot/safechroot.go
  toolkit/tools/pkg/simpletoolchroot/simpletoolchroot.go
Labels: Tools, 3.0

#8215 fix logging in tools/internal
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
  toolkit/tools/internal/pkggraph/pkggraph.go
Labels: Tools, 3.0

#7974 fix logging in imagegen-config files
  toolkit/tools/imageconfigvalidator/imageconfigvalidator_test.go
  toolkit/tools/imagegen/configuration/configuration.go
  toolkit/tools/imagegen/configuration/configuration_test.go
  toolkit/tools/imagegen/configuration/networkconfig.go
  toolkit/tools/imagegen/configuration/networkconfig_test.go
  toolkit/tools/imagegen/configuration/packagerepo.go
  toolkit/tools/imagegen/configuration/packagerepo_test.go
  toolkit/tools/imagegen/configuration/parse_partition.go
  toolkit/tools/imagegen/configuration/systemconfig.go
  toolkit/tools/imagegen/configuration/systemconfig_test.go
Labels: Tools, 3.0

#8274 revert cleaning up log directories for base image
  toolkit/imageconfigs/scripts/cleanup.sh
Labels: main

#7322 Upgrade libvirt to 10.0.0
  SPECS/glusterfs/glusterfs.spec
  SPECS/libvirt/CVE-2023-2700.patch
  SPECS/libvirt/libvirt.signatures.json
  SPECS/libvirt/libvirt.spec
  cgmanifest.json
Labels: 3.0

#8283 Remove protobuf-c static sub-package.
  SPECS/protobuf-c/protobuf-c.spec
Labels: 3.0

#8266 revert openmpi changes
  SPECS/openmpi/openmpi.spec
Labels: 3.0

#8284 azl3: upgrade libvirt-python and enable mdevctl for arm
  SPECS/libvirt-python/libvirt-python.signatures.json
  SPECS/libvirt-python/libvirt-python.spec
  SPECS/mdevctl/mdevctl.spec
  cgmanifest.json
Labels: 3.0

#8297 [main] update toolchain container bootstrap to 2.0.20240123
  toolkit/scripts/toolchain/cgmanifest.json
  toolkit/scripts/toolchain/container/Dockerfile
Labels: main

#7510 remove golang version restriction for influx-cli and influxdb
  SPECS/influx-cli/influx-cli.spec
  SPECS/influxdb/influxdb.spec
Labels: 3.0

#8298 Patch CVE-2023-52356
  SPECS/libtiff/CVE-2023-52356.patch
  SPECS/libtiff/libtiff.spec
Labels: fasttrack/2.0

#8303 Switch qemu-guest base image to kernel instead of kernel-hci
  toolkit/imageconfigs/qemu-guest.json
Labels: main

#8290 expat: patch CVE-2023-52426
  SPECS/expat/CVE-2023-52426.patch
  SPECS/expat/expat.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, main

#8247 Fix python-remoto ptest
  SPECS/python-remoto/python-remoto.spec
Labels: main

#8246 Fix python-prettytables ptest.
  SPECS/python-prettytable/python-prettytable.spec
Labels: main

#8324 python-gevent: disable c-ares module and fix CVE-2021-22931
  SPECS/python-gevent/python-gevent.spec
Labels: main

#8320 pam: patch CVE-2024-22365
  SPECS/pam/CVE-2024-22365.patch
  SPECS/pam/pam.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, main

#8253 Address kernel CVE-2015-5157, CVE-2022-2585, CVE-2022-2586, CVE-2023-50431, CVE-2023-6200, CVE-2023-6560
  SPECS/kernel/CVE-2015-5157.nopatch
  SPECS/kernel/CVE-2022-2585.nopatch
  SPECS/kernel/CVE-2022-2586.nopatch
  SPECS/kernel/CVE-2023-50431.nopatch
  SPECS/kernel/CVE-2023-6200.nopatch
  SPECS/kernel/CVE-2023-6560.nopatch
Labels: security, main

#7866 libkcapi: upgrade to 1.5.0
  SPECS/libkcapi/libkcapi.signatures.json
  SPECS/libkcapi/libkcapi.spec
  cgmanifest.json
Labels: 3.0

#8020 netavark: upgrade to 1.10.3
  SPECS/netavark/netavark.signatures.json
  SPECS/netavark/netavark.spec
  cgmanifest.json
Labels: 3.0

#7777 ig: add package v0.25.0
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/ig/generate_source_tarball.sh
  SPECS/ig/ig.signatures.json
  SPECS/ig/ig.spec
  cgmanifest.json
Labels: 3.0

#8269 python-gevent: disable c-ares module and fix CVE-2021-22931
  SPECS/python-gevent/python-gevent.spec
Labels: security, main, fasttrack/2.0

#8338 Address kernel CVE-2022-2588
  SPECS/kernel/CVE-2022-2588.nopatch
Labels: security, main

#8318 [2.0] dhcp/dhclient.conf: add option rfc3442-classless-static-routes in dhclient.conf
  SPECS/dhcp/dhcp.spec
Labels: main

#8373 fix devel package dependencies in elfutils
  SPECS/elfutils/elfutils.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 3.0

#8388 Add filesystem, random, system, program-options packages to boost
  SPECS/boost/boost.spec
Labels: 3.0

#8391 update build step and add libs pkg to gperftools
  SPECS/gperftools/gperftools.spec
Labels: 3.0

#8392 WALinuxAgent: address issues in systemd unit configuration
  SPECS/WALinuxAgent/WALinuxAgent.spec
  SPECS/azurelinux-release/90-default.preset
  SPECS/azurelinux-release/azurelinux-release.signatures.json
  SPECS/azurelinux-release/azurelinux-release.spec
Labels: 3.0

#8400 mariner 3.0 grpc upgrade
  SPECS/grpc/grpc.signatures.json
  SPECS/grpc/grpc.spec
  SPECS/grpc/grpcio-cython3.patch
  cgmanifest.json
Labels: 3.0

#8380 Fix: Signature check not handling files in subfolders
  toolkit/scripts/check_signatures.py
Labels: 3.0

#8399 systemd: force coredump to use LZ4 compression
  SPECS/systemd/mariner-2-force-use-of-lz4-for-coredump.patch
  SPECS/systemd/systemd.spec
Labels: main

#8394 kata-containers-cc: fix virtiofsd dependency
  SPECS/kata-containers-cc/kata-containers-cc.spec
Labels: main

#8474 moby-compose: fix license to ASL 2.0
  SPECS/moby-compose/moby-compose.spec
Labels: main

#6479 fix: introduce mariner_2_initrd_use_suffix kdump.conf option
  SPECS/kexec-tools/kdump-lib-initramfs.sh
  SPECS/kexec-tools/kdump.conf
  SPECS/kexec-tools/kdumpctl
  SPECS/kexec-tools/kexec-tools.signatures.json
  SPECS/kexec-tools/kexec-tools.spec
Labels: main

#8487 Remove pcre2-doc subpackage as runtime dependency for both pcre2 and pcre2-tools
  SPECS/pcre2/pcre2.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 3.0

#8447 libvirt: address CVE-2024-1441
  SPECS/libvirt/CVE-2024-1441.patch
  SPECS/libvirt/libvirt.spec
Labels: security, main

#8483 nodejs and nodejs18: Adding patch for CVE-2024-22025
  SPECS/nodejs/CVE-2024-22025.patch
  SPECS/nodejs/nodejs.spec
  SPECS/nodejs/nodejs18.spec
Labels: main

#8424 Fix py-crypto, tpm2-pytss, tpm2-pkcs11 because openssl isn't building what they expect
  SPECS/python-cryptography/0001-remove-openssl-cipher-Cipher-chacha20_poly1305.patch
  SPECS/python-cryptography/0002-remove-poly1305-tests.patch
  SPECS/python-cryptography/python-cryptography.signatures.json
  SPECS/python-cryptography/python-cryptography.spec
  SPECS/tpm2-pytss/0001-remove-tests-for-unsupported-openssl.patch
  SPECS/tpm2-pytss/tpm2-pytss.signatures.json
  SPECS/tpm2-pytss/tpm2-pytss.spec
  cgmanifest.json
Labels: 3.0

#8513 moby-engine: fix userland-proxy service failure
  SPECS/moby-engine/daemon.json
  SPECS/moby-engine/moby-engine.signatures.json
  SPECS/moby-engine/moby-engine.spec
Labels: 3.0

#8500 Bump golang version to 1.21.8-1, build version to 1.21.8-2
  SPECS/golang/golang.signatures.json
  SPECS/golang/golang.spec
  cgmanifest.json
Labels: 3.0

#8422 add patch for cloud-init pkg install error
  SPECS/cloud-init/cloud-init.spec
  SPECS/cloud-init/exec_cmd_error_handling.patch
Labels: main

#8505 Cython: fix package test by using python312 requirements
  SPECS/Cython/Cython.spec
  SPECS/Cython/fix_testcycache.patch
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 3.0

#8389 Smaller base images (baremetal & qemu-guest)
  toolkit/imageconfigs/additionalconfigs/macros.excludedocs
  toolkit/imageconfigs/baremetal.json
  toolkit/imageconfigs/packagelists/base-image-packages.json
  toolkit/imageconfigs/qemu-guest.json
  toolkit/imageconfigs/scripts/cleanup.sh
Labels: 3.0

#8419 Update Maven Packages
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/javapackages-bootstrap/0001-Bind-to-OpenJDK-11-for-runtime.patch
  SPECS/javapackages-bootstrap/0001-Remove-usage-of-ArchiveStreamFactory.patch
  SPECS/javapackages-bootstrap/CVE-2023-37460.patch
  SPECS/javapackages-bootstrap/javapackages-bootstrap-PACKAGE-LICENSING
  SPECS/javapackages-bootstrap/javapackages-bootstrap.signatures.json
  SPECS/javapackages-bootstrap/javapackages-bootstrap.spec
  SPECS/jurand/jurand.signatures.json
  SPECS/jurand/jurand.spec
  SPECS/maven-compiler-plugin/0001-plexus-languages-1.0.patch
  SPECS/maven-compiler-plugin/0002-MCOMPILER-359-Fix-for-NPE.patch
  SPECS/maven-compiler-plugin/maven-compiler-plugin.signatures.json
  SPECS/maven-compiler-plugin/maven-compiler-plugin.spec
  SPECS/maven-jar-plugin/maven-jar-plugin.signatures.json
  SPECS/maven-jar-plugin/maven-jar-plugin.spec
  SPECS/maven-resolver/0001-Remove-use-of-deprecated-SHA-1-and-MD5-algorithms.patch
  SPECS/maven-resolver/maven-resolver.signatures.json
  SPECS/maven-resolver/maven-resolver.spec
  SPECS/maven-surefire/0001-Port-to-TestNG-6.11.patch
  SPECS/maven-surefire/0001-Port-to-TestNG-7.4.0.patch
  SPECS/maven-surefire/0002-Disable-JUnit-4.8-test-grouping.patch
  SPECS/maven-surefire/0003-Port-to-maven-shared-utils-3.3.3.patch
  SPECS/maven-surefire/maven-surefire.signatures.json
  SPECS/maven-surefire/maven-surefire.spec
  SPECS/plexus-interpolation/0001-Use-PATH-env-variable-instead-of-JAVA_HOME.patch
  SPECS/plexus-interpolation/plexus-interpolation.spec
  SPECS/sisu/sisu-inject.pom
  SPECS/sisu/sisu-plexus.pom
  SPECS/sisu/sisu.signatures.json
  SPECS/sisu/sisu.spec
  cgmanifest.json
Labels: 3.0

#8529 Exclude overlayfs module from main dracut package.
  SPECS/dracut/dracut.spec
Labels: main

#8504 Fix vimrc bindings
  SPECS/vim/vim.spec
Labels: 3.0

#8527 Address kernel CVEs 2023-52434, 2023-52435
  SPECS/kernel/CVE-2023-52434.nopatch
  SPECS/kernel/CVE-2023-52435.nopatch
Labels: security, main

#8516 msft-golang: upgrade version 1.21.6 -> 1.21.8
  SPECS/msft-golang/msft-golang.signatures.json
  SPECS/msft-golang/msft-golang.spec
  cgmanifest.json
Labels: security, main

#8178 docs: Add documentation on how to add a new package.
  toolkit/README.md
  toolkit/docs/building/add-package.md
Labels: main

#8530 Upgraded `etcd` to version 3.5.12. (CP: #8477)
  SPECS/etcd/etcd.signatures.json
  SPECS/etcd/etcd.spec
  cgmanifest.json
Labels: main

#8538 explicitly add libgcc as a Requires to distroless base
  SPECS/distroless-packages/distroless-packages.spec
Labels: main

#8524 Update guava to 32.1.3 in Javapackages-bootstrap
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/javapackages-bootstrap/Internal-Java-API.patch
  SPECS/javapackages-bootstrap/guava.xml
  SPECS/javapackages-bootstrap/javapackages-bootstrap.signatures.json
  SPECS/javapackages-bootstrap/javapackages-bootstrap.spec
  SPECS/jurand/jurand.signatures.json
  SPECS/jurand/jurand.spec
  cgmanifest.json
Labels: main

#8542 Add a PR check for source signatures
  .github/workflows/check-entangled-specs.yml
  .github/workflows/check-kernel-config.yml
  .github/workflows/check-license-map.yml
  .github/workflows/check-signatures.yml
  .github/workflows/check-source-signatures.yml
  .github/workflows/check-spec.yml
  .github/workflows/check-static-glibc.yml
  .github/workflows/lint-specs.yml
Labels: Tools, github_actions, 3.0

#8546 Cython: skip long tests
  SPECS/Cython/Cython.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#8558 Address kernel CVE-2023-35827
  SPECS/kernel/CVE-2023-35827.nopatch
Labels: security, main

#8557 Upgrade kernel to 5.15.151.2
  SPECS-SIGNED/kernel-azure-signed/kernel-azure-signed.spec
  SPECS-SIGNED/kernel-hci-signed/kernel-hci-signed.spec
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/hyperv-daemons/hyperv-daemons.signatures.json
  SPECS/hyperv-daemons/hyperv-daemons.spec
  SPECS/kernel-azure/config
  SPECS/kernel-azure/config_aarch64
  SPECS/kernel-azure/kernel-azure.signatures.json
  SPECS/kernel-azure/kernel-azure.spec
  SPECS/kernel-hci/config
  SPECS/kernel-hci/kernel-hci.signatures.json
  SPECS/kernel-hci/kernel-hci.spec
  SPECS/kernel-headers/kernel-headers.signatures.json
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#8554 unixODBC: Address HIGH CVE-2024-1013
  SPECS/unixODBC/CVE-2024-1013.patch
  SPECS/unixODBC/unixODBC.spec
Labels: security, fasttrack/2.0

#8566 Fix build issues with OpenIPMI 2.0.32 in 3.0
  SPECS/OpenIPMI/OpenIPMI.spec
Labels: 3.0

#8574 Update hdf5 to v1.14.3 for AzL 3.0
  SPECS/hdf5/Fix-Werror-removal.patch
  SPECS/hdf5/hdf5-build.patch
  SPECS/hdf5/hdf5-wrappers.patch
  SPECS/hdf5/hdf5.signatures.json
  SPECS/hdf5/hdf5.spec
  SPECS/python-h5py/0001-Fix-compiling-fileobj-file-driver-with-Cython-3.0.patch
  SPECS/python-h5py/Cython-3-support.patch
  SPECS/python-h5py/python-h5py.spec
  cgmanifest.json
Labels: 3.0

#8561 move busybox build from core to golden containers
  .pipelines/containerSourceData/busybox/Dockerfile-Busybox
  .pipelines/containerSourceData/busybox/busybox.pkg
  .pipelines/containerSourceData/scripts/BuildBaseContainers.sh
  .pipelines/containerSourceData/scripts/BuildGoldenContainer.sh
Labels: main

#8567 libvirt: Address Medium CVE-2024-2496
  SPECS/libvirt/CVE-2024-2496.patch
  SPECS/libvirt/libvirt.spec
Labels: security, main

#8582 llvm: update to build with llvmgold.so
  SPECS/llvm/llvm.spec
Labels: 3.0

#8604 upgrade prometheus to 2.45.4
  SPECS/prometheus/prometheus.signatures.json
  SPECS/prometheus/prometheus.spec
  cgmanifest.json
Labels: 3.0

#8616 open-vm-tools: patch to address CVE-2023-34058 & CVE-2023-34059
  SPECS/open-vm-tools/CVE-2023-34058.patch
  SPECS/open-vm-tools/CVE-2023-34059.patch
  SPECS/open-vm-tools/open-vm-tools.spec
Labels: main

#8611 Update to jakarta-servlet v5.0.0 for AzL v3.0
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/glassfish-servlet-api/LICENSE-2.0.txt
  SPECS/glassfish-servlet-api/glassfish-servlet-api-build.properties
  SPECS/glassfish-servlet-api/glassfish-servlet-api-build.xml
  SPECS/glassfish-servlet-api/glassfish-servlet-api.signatures.json
  SPECS/glassfish-servlet-api/glassfish-servlet-api.spec
  SPECS/jakarta-servlet/jakarta-servlet.signatures.json
  SPECS/jakarta-servlet/jakarta-servlet.spec
  cgmanifest.json
Labels: 3.0

#8497 fix: enable python3 %check tests
  SPECS/python3/python3.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 3.0

#8587 Revert "[2.0] dhcp/dhclient.conf: add option rfc3442-classless-static…
  SPECS/dhcp/dhcp.spec
Labels: main

#8627 Bump Mariner Release for April 2024 update
  SPECS/mariner-release/mariner-release.spec
Labels: main

#8628 php-pecl-zip: upgrade to version 1.22.3 and fix tests
  SPECS/php-pecl-zip/php-pecl-zip.signatures.json
  SPECS/php-pecl-zip/php-pecl-zip.spec
  cgmanifest.json
Labels: ptest, 3.0
