Repository microsoft/azurelinux, pull requests merged in 2024-05, with the labels that each got.

#8866 Fixes for CVE-2023-45288.
  SPECS/blobfuse2/CVE-2023-45288.patch
  SPECS/blobfuse2/blobfuse2.spec
  SPECS/cert-manager/CVE-2023-45288.patch
  SPECS/cert-manager/cert-manager.spec
  SPECS/coredns/CVE-2023-45288.patch
  SPECS/coredns/coredns.spec
  SPECS/cri-tools/CVE-2023-45288.patch
  SPECS/cri-tools/cri-tools.spec
  SPECS/etcd/CVE-2023-45288.patch
  SPECS/etcd/etcd.spec
  SPECS/helm/CVE-2023-45288.patch
  SPECS/helm/helm.spec
  SPECS/kubernetes/CVE-2023-45288.patch
  SPECS/kubernetes/kubernetes.spec
  SPECS/kubevirt/CVE-2023-45288.patch
  SPECS/kubevirt/kubevirt.spec
  SPECS/kured/CVE-2023-45288.patch
  SPECS/kured/kured.spec
  SPECS/moby-compose/CVE-2023-45288.patch
  SPECS/moby-compose/moby-compose.spec
  SPECS/moby-containerd-cc/CVE-2023-45288.patch
  SPECS/moby-containerd-cc/moby-containerd-cc.spec
  SPECS/moby-containerd/CVE-2023-45288.patch
  SPECS/moby-containerd/moby-containerd.spec
  SPECS/moby-engine/CVE-2023-45288.patch
  SPECS/moby-engine/moby-engine.spec
  SPECS/multus/CVE-2023-45288.patch
  SPECS/multus/multus.spec
  SPECS/nmi/CVE-2023-45288.patch
  SPECS/nmi/nmi.spec
  SPECS/node-problem-detector/CVE-2023-45288.patch
  SPECS/node-problem-detector/node-problem-detector.spec
  SPECS/opa/CVE-2023-45288.patch
  SPECS/opa/opa.spec
  SPECS/packer/CVE-2023-45288.patch
  SPECS/packer/packer.spec
  SPECS/skopeo/CVE-2023-45288.patch
  SPECS/skopeo/skopeo.spec
  SPECS/sriov-network-device-plugin/CVE-2023-45288.patch
  SPECS/sriov-network-device-plugin/sriov-network-device-plugin.spec
  SPECS/telegraf/CVE-2023-45288.patch
  SPECS/telegraf/telegraf.spec
  SPECS/vitess/CVE-2023-45288.patch
  SPECS/vitess/vitess.spec
Labels: main

#8955 Address kernel CVE-2023-52447, CVE-2024-21803, CVE-2024-26587, CVE-2024-26588
  SPECS/kernel/CVE-2023-52447.nopatch
  SPECS/kernel/CVE-2024-21803.nopatch
  SPECS/kernel/CVE-2024-26587.nopatch
  SPECS/kernel/CVE-2024-26588.nopatch
Labels: security, main

#8980 Fix Ptest zchunk
  SPECS/zchunk/0000-Zstd-1.5.1-fix.patch
  SPECS/zchunk/zchunk.spec
Labels: main

#8929 Add patch in cri-o for CVE-2024-21626
  SPECS/cri-o/CVE-2023-44487.patch
  SPECS/cri-o/CVE-2024-21626.patch
  SPECS/cri-o/cri-o.spec
Labels: security, main

#8987 use docker buildx
  .pipelines/containerSourceData/scripts/BuildBaseContainers.sh
  .pipelines/containerSourceData/scripts/BuildGoldenDistrolessContainer.sh
Labels: main

#8413 frr: patch CVE-2024-27913
  SPECS/frr/CVE-2024-27913.patch
  SPECS/frr/frr.spec
Labels: main

#8992 azurelinux-sysinfo: update version for 2.0
  SPECS/azurelinux-sysinfo/azurelinux-sysinfo.spec
Labels: documentation, security, Packaging, Tools, Schema

#8688 Bump golang version to 1.21.9-1
  SPECS/golang/golang.signatures.json
  SPECS/golang/golang.spec
  cgmanifest.json
Labels: 3.0

#9002 moby-engine: add back-compat symlink for docker-proxy
  SPECS/moby-engine/moby-engine.spec
Labels: main

#9005 Kata: uprade to 3.2.0.azl1
  SPECS/kata-containers-cc/kata-containers-cc.signatures.json
  SPECS/kata-containers-cc/kata-containers-cc.spec
  SPECS/kata-containers/kata-containers.signatures.json
  SPECS/kata-containers/kata-containers.spec
  SPECS/kata-packages-uvm/kata-packages-uvm.spec
  cgmanifest.json
Labels: main

#9012 frr: patch CVE-2024-34088
  SPECS/frr/CVE-2024-27913.patch
  SPECS/frr/CVE-2024-34088.patch
  SPECS/frr/frr.spec
Labels: security, main

#9010 bluez: patch CVE-2023-50229
  SPECS/bluez/CVE-2023-50229.patch
  SPECS/bluez/bluez.spec
Labels: fasttrack/2.0

#9019 [2.0] Re-Fix telegraf CVE-2024-28110
  SPECS/telegraf/CVE-2024-28110.patch
  SPECS/telegraf/telegraf.spec
Labels: security, main

#9041 Use legacy builder for distroless golden containers
  .pipelines/containerSourceData/scripts/BuildGoldenDistrolessContainer.sh
Labels: main

#9039 Disabled keyboxd for `gnupg2`.
  SPECS/gnupg2/gnupg2.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 3.0

#9025 [2.0] Resolved regressed ansible CVE-2023-5764
  SPECS/ansible/CVE-2024-0690.patch
  SPECS/ansible/ansible.signatures.json
  SPECS/ansible/ansible.spec
  cgmanifest.json
Labels: security, main

#9027 fix: ephemeral-disk-warning service not running on boot
  SPECS/azurelinux-release/90-default.preset
  SPECS/azurelinux-release/azurelinux-release.signatures.json
  SPECS/azurelinux-release/azurelinux-release.spec
Labels: 3.0

#9044 coredns: Patched cache plugin to address CVE-2024-0874
  SPECS/coredns/CVE-2024-0874.patch
  SPECS/coredns/coredns.spec
Labels: security, main

#8895 Fixed `CODEOWNERS` group for certificates.
  .github/CODEOWNERS
Labels: main

#9073 python-chardet: upgrade to 5.2.0
  SPECS/python-chardet/chardetect.1
  SPECS/python-chardet/python-chardet.signatures.json
  SPECS/python-chardet/python-chardet.spec
  cgmanifest.json
Labels: 3.0

#9026 Move nmi from SPEC to SPEC-EXTENDED
  SPECS-EXTENDED/nmi/CVE-2023-45288.patch
  SPECS-EXTENDED/nmi/modify-go-build-option.patch
  SPECS-EXTENDED/nmi/nmi.signatures.json
  SPECS-EXTENDED/nmi/nmi.spec
Labels: main

#9051 glibc: Fix nscd breakage and patch CVE-2024-33599, CVE-2024-33600, CVE-2024-33601, CVE-2024-33602
  SPECS-EXTENDED/buildah/buildah.spec
  SPECS-EXTENDED/catatonit/catatonit.spec
  SPECS-EXTENDED/dyninst/dyninst.spec
  SPECS-EXTENDED/podman/podman.spec
  SPECS/busybox/busybox.spec
  SPECS/flannel/flannel.spec
  SPECS/glibc/CVE-2023-4806.patch
  SPECS/glibc/CVE-2023-5156.patch
  SPECS/glibc/CVE-2024-33599.patch
  SPECS/glibc/CVE-2024-33600.patch
  SPECS/glibc/CVE-2024-33601.patch
  SPECS/glibc/CVE-2024-33602.nopatch
  SPECS/glibc/get_nscd_addresses_fix_subscript_typos.patch
  SPECS/glibc/glibc.spec
  SPECS/kubernetes/kubernetes.spec
  SPECS/kubevirt/kubevirt.spec
  SPECS/libguestfs/libguestfs.spec
  SPECS/rust/rust.spec
  SPECS/supermin/supermin.spec
  SPECS/tini/tini.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, fasttrack/2.0

#9055 Update kernel-mos to 5.15.158.1
  SPECS-SIGNED/kernel-mos-signed/kernel-mos-signed.spec
  SPECS/kernel-mos/config
  SPECS/kernel-mos/kernel-mos.signatures.json
  SPECS/kernel-mos/kernel-mos.spec
  cgmanifest.json
Labels: main

#9085 glibc: Fix nscd breakage and patch CVE-2024-33599, CVE-2024-33600, CV…
  SPECS-EXTENDED/buildah/buildah.spec
  SPECS-EXTENDED/catatonit/catatonit.spec
  SPECS-EXTENDED/dyninst/dyninst.spec
  SPECS-EXTENDED/podman/podman.spec
  SPECS/busybox/busybox.spec
  SPECS/flannel/flannel.spec
  SPECS/glibc/CVE-2023-4806.patch
  SPECS/glibc/CVE-2023-5156.patch
  SPECS/glibc/CVE-2024-33599.patch
  SPECS/glibc/CVE-2024-33600.patch
  SPECS/glibc/CVE-2024-33601.patch
  SPECS/glibc/CVE-2024-33602.nopatch
  SPECS/glibc/get_nscd_addresses_fix_subscript_typos.patch
  SPECS/glibc/glibc.spec
  SPECS/kubernetes/kubernetes.spec
  SPECS/kubevirt/kubevirt.spec
  SPECS/libguestfs/libguestfs.spec
  SPECS/rust/rust.spec
  SPECS/supermin/supermin.spec
  SPECS/tini/tini.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#9082 ceph: patch multiple CVEs
  SPECS/ceph/CVE-2021-24032.patch
  SPECS/ceph/CVE-2021-28361.patch
  SPECS/ceph/CVE-2022-3650.patch
  SPECS/ceph/CVE-2022-3854.patch
  SPECS/ceph/ceph.spec
Labels: fasttrack/2.0

#8971 dhcp: fix CVE-2022-38177, CVE-2022-38178, CVE-2022-2795 for bind
  SPECS/dhcp/CVE-2022-2795.patch
  SPECS/dhcp/CVE-2022-38177.patch
  SPECS/dhcp/CVE-2022-38178.patch
  SPECS/dhcp/dhcp.spec
Labels: security, fasttrack/2.0

#9089 python-tqdm: patch CVE-2024-34062
  SPECS/python-tqdm/CVE-2024-34062.patch
  SPECS/python-tqdm/python-tqdm.spec
Labels: security, main

#9028 Update facter version to support Mariner
  SPECS-EXTENDED/facter/facter.signatures.json
  SPECS-EXTENDED/facter/facter.spec
  cgmanifest.json
Labels: main

#9117 [CHERRYPICK] azurelinux-sysinfo: fasttrack/2.0 to main
  .github/workflows/validate-cg-manifest.sh
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/azurelinux-sysinfo/azurelinux-sysinfo.service
  SPECS/azurelinux-sysinfo/azurelinux-sysinfo.signatures.json
  SPECS/azurelinux-sysinfo/azurelinux-sysinfo.spec
  SPECS/azurelinux-sysinfo/collect-sysinfo
  SPECS/azurelinux-sysinfo/sysinfo-schema-v1.json
  SPECS/azurelinux-sysinfo/sysinfo-selinuxpolicies.cil
Labels: main

#9092 Add macro for enabling frame pointers during build and enable frame pointers in glibc
  SPECS-EXTENDED/buildah/buildah.spec
  SPECS-EXTENDED/catatonit/catatonit.spec
  SPECS-EXTENDED/dyninst/dyninst.spec
  SPECS-EXTENDED/podman/podman.spec
  SPECS/azurelinux-rpm-macros/azurelinux-rpm-macros.signatures.json
  SPECS/azurelinux-rpm-macros/azurelinux-rpm-macros.spec
  SPECS/azurelinux-rpm-macros/macros
  SPECS/busybox/busybox.spec
  SPECS/flannel/flannel.spec
  SPECS/glibc/glibc.spec
  SPECS/kubernetes/kubernetes.spec
  SPECS/kubevirt/kubevirt.spec
  SPECS/libguestfs/libguestfs.spec
  SPECS/mdadm/mdadm.spec
  SPECS/qemu/qemu.spec
  SPECS/rust/rust.spec
  SPECS/supermin/supermin.spec
  SPECS/tini/tini.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 3.0

#9093 graphviz: address CVE-2023-46045 & CVE-2020-18032
  SPECS/graphviz/CVE-2023-46045.patch
  SPECS/graphviz/graphviz.spec
  SPECS/python-sphinx/python-sphinx.spec
Labels: security, main, fasttrack/2.0

#9110 pytorch: Add patch for CVE-2024-27318
  SPECS/pytorch/CVE-2024-27318.patch
  SPECS/pytorch/pytorch.spec
Labels: security, fasttrack/2.0

#9114 selinux-policy: Add fix for cloud-init growpart.
  SPECS/selinux-policy/0043-cloudinit-Add-support-for-cloud-init-growpart.patch
  SPECS/selinux-policy/booleans_targeted.conf
  SPECS/selinux-policy/selinux-policy.signatures.json
  SPECS/selinux-policy/selinux-policy.spec
Labels: main

#9105 Removing hard-coded 'with_check' from 'podman.spec'.
  SPECS-EXTENDED/podman/podman.spec
Labels: 3.0

#9125 prometheus-adapter: Fix CVE-2024-24786
  SPECS/prometheus-adapter/CVE-2024-24786.patch
  SPECS/prometheus-adapter/prometheus-adapter.spec
Labels: security, main

#9139 Update SymCrypt-OpenSSL to 1.4.3
  SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.signatures.json
  SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.spec
  cgmanifest.json
Labels: 3.0

#8925 move src tarballs to AME - mariner 2.0
  CONTRIBUTING.md
  SPECS/mariner-rpm-macros/macros
  SPECS/mariner-rpm-macros/mariner-rpm-macros.signatures.json
  SPECS/mariner-rpm-macros/mariner-rpm-macros.spec
  SPECS/maven/maven_build_caches.sh
  cgmanifest.json
  toolkit/Makefile
  toolkit/docs/building/building.md
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/build_cargo_cache.sh
  toolkit/scripts/build_go_vendor_cache.sh
Labels: main

#9113 Refractor Golden Container main
  .pipelines/containerSourceData/busybox/busybox.name
  .pipelines/containerSourceData/cdi/api.name
  .pipelines/containerSourceData/cdi/cloner.name
  .pipelines/containerSourceData/cdi/controller.name
  .pipelines/containerSourceData/cdi/importer.name
  .pipelines/containerSourceData/cdi/operator.name
  .pipelines/containerSourceData/cdi/uploadproxy.name
  .pipelines/containerSourceData/cdi/uploadserver.name
  .pipelines/containerSourceData/certmanager/acmesolver.name
  .pipelines/containerSourceData/certmanager/cainjector.name
  .pipelines/containerSourceData/certmanager/cmctl.name
  .pipelines/containerSourceData/certmanager/controller.name
  .pipelines/containerSourceData/certmanager/webhook.name
  .pipelines/containerSourceData/influxdb/influxdb.name
  .pipelines/containerSourceData/kubevirt/virt-api.name
  .pipelines/containerSourceData/kubevirt/virt-controller.name
  .pipelines/containerSourceData/kubevirt/virt-handler.name
  .pipelines/containerSourceData/kubevirt/virt-launcher.name
  .pipelines/containerSourceData/kubevirt/virt-operator.name
  .pipelines/containerSourceData/memcached/memcached.name
  .pipelines/containerSourceData/multus/multus.name
  .pipelines/containerSourceData/nginx/nginx.name
  .pipelines/containerSourceData/nodejs/distroless/holdback-nodejs.pkg
  .pipelines/containerSourceData/nodejs/distroless/nodejs.pkg
  .pipelines/containerSourceData/nodejs/nodejs.name
  .pipelines/containerSourceData/nodejs/nodejs.pkg
  .pipelines/containerSourceData/nodejs/nodejs18.pkg
  .pipelines/containerSourceData/openmpi/openmpi.name
  .pipelines/containerSourceData/php/php.name
  .pipelines/containerSourceData/postgres/postgres.name
  .pipelines/containerSourceData/prometheus/prometheus.name
  .pipelines/containerSourceData/prometheusadapter/prometheusadapter.name
  .pipelines/containerSourceData/python/python.name
  .pipelines/containerSourceData/pytorch/pytorch.name
  .pipelines/containerSourceData/rabbitmqserver/rabbitmqserver.name
  .pipelines/containerSourceData/redis/redis.name
  .pipelines/containerSourceData/ruby/ruby.name
  .pipelines/containerSourceData/rust/rust.name
  .pipelines/containerSourceData/scripts/BuildGoldenContainer.sh
  .pipelines/containerSourceData/sriovnetworkdeviceplugin/sriovnetworkdeviceplugin.name
  .pipelines/containerSourceData/telegraf/telegraf.name
  .pipelines/containerSourceData/tensorflow/tensorflow.name
Labels: main

#9119 iperf3: upgrade 3.14 -> 3.17 to address CVE-2024-26306
  SPECS/iperf3/iperf3.signatures.json
  SPECS/iperf3/iperf3.spec
  cgmanifest.json
Labels: security, main

#9108 msft-golang: upgrade 1.22.2 -> 1.22.3 to address CVE-2024-24787 & CVE-2024-24788
  SPECS/msft-golang/msft-golang.signatures.json
  SPECS/msft-golang/msft-golang.spec
  cgmanifest.json
Labels: security, main

#8875 Adding admin approval for certificate changes. (CP: #8859)
  .github/CODEOWNERS
Labels: 3.0

#6221 Namespace httpd include files into its own directory
  SPECS/httpd/httpd.spec
Labels: main

#9167 Update facter version to support Mariner
  SPECS-EXTENDED/facter/facter.signatures.json
  SPECS-EXTENDED/facter/facter.spec
  cgmanifest.json
Labels: 3.0

#9022 Bump golang version to 1.22.3-1, new bootstrap
  SPECS/golang/golang.signatures.json
  SPECS/golang/golang.spec
  cgmanifest.json
Labels: 3.0

#9066 Add patch to add network interface renaming support for CAPM3 Met
  SPECS/cloud-init/Add-Network-Interface-Renaming-Support-for-CAPM3-Met.patch
  SPECS/cloud-init/cloud-init.spec
Labels: 3.0

#9138 ruby: Patch CVE-2024-27282
  SPECS/ruby/CVE-2024-27282.patch
  SPECS/ruby/ruby.spec
Labels: main

#9153 Better document and prompt user with --no-cleanup
  toolkit/docs/building/building.md
  toolkit/tools/internal/logger/log.go
  toolkit/tools/internal/logger/log_test.go
  toolkit/tools/internal/pkggraph/pkggraph.go
  toolkit/tools/scheduler/scheduler.go
Labels: documentation, Tools, DevEx, 3.0

#9147 Sanitize licenses in core image packages
  SPECS/cmake/cmake.spec
  SPECS/cyrus-sasl-bootstrap/cyrus-sasl-bootstrap.spec
  SPECS/cyrus-sasl/cyrus-sasl.spec
  SPECS/ethtool/ethtool.spec
  SPECS/libdb/libdb.spec
  SPECS/librdkafka/librdkafka.spec
  SPECS/lmdb/lmdb.spec
  SPECS/qemu/qemu.spec
  SPECS/userspace-rcu/userspace-rcu.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, 3.0

#9135 Specialcased 5XX errors during package downloads. (CP: #7445)
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
  toolkit/tools/internal/retry/retry.go
  toolkit/tools/pkg/downloader/downloader.go
  toolkit/tools/precacher/precacher.go
  toolkit/tools/srpmpacker/srpmpacker.go
Labels: 3.0

#9195 rubygem-rexml: fix CVE-2024-35176
  SPECS/ruby/ruby.spec
  SPECS/rubygem-rexml/add-support-for-old-strscan.patch
  SPECS/rubygem-rexml/rubygem-rexml.signatures.json
  SPECS/rubygem-rexml/rubygem-rexml.spec
  cgmanifest.json
Labels: 3.0

#9193 expat: fix CVE-2024-28757
  SPECS/cmake/cmake.spec
  SPECS/expat/expat.signatures.json
  SPECS/expat/expat.spec
  SPECS/python3/python3.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 3.0

#9226 Fixed Perl automatic requires and provides.
  SPECS/perl-DBD-SQLite/perl-DBD-SQLite.spec
  SPECS/perl-DBI/perl-DBI.spec
  SPECS/perl-DBIx-Simple/perl-DBIx-Simple.spec
  SPECS/perl-Fedora-VSP/perl-Fedora-VSP.spec
  SPECS/perl-Object-Accessor/perl-Object-Accessor.spec
  SPECS/perl-Test-Warnings/perl-Test-Warnings.spec
  SPECS/perl-Text-Template/perl-Text-Template.spec
  SPECS/perl-generators/perl-generators.spec
  SPECS/perl/perl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
Labels: main

#9230 Bump Mariner 2.0 Release for June 2024 Update
  SPECS/mariner-release/mariner-release.spec
Labels: main

#9223 update python h5py to fix build break caused by recent HDF5 update
  SPECS/keras/keras.spec
  SPECS/python-h5py/h5py-3.7.0-ppc-float128.patch
  SPECS/python-h5py/python-h5py.signatures.json
  SPECS/python-h5py/python-h5py.spec
  SPECS/python-tensorflow-estimator/python-tensorflow-estimator.spec
  cgmanifest.json
Labels: main

#9154 imageconfigs: cloud-init: fix typo AureLinux -> AzureLinux
  toolkit/imageconfigs/additionalconfigs/cloud-init.cfg
Labels: 3.0

#9203 Upgrade azcopy to 10.24.0 to fix multiple security issues
  SPECS/azcopy/azcopy.signatures.json
  SPECS/azcopy/azcopy.spec
  cgmanifest.json
Labels: 3.0

#9168 cups: patch CVE-2022-26691.
  SPECS/cups/CVE-2022-26691.patch
  SPECS/cups/cups.spec
Labels: security, main

#9197 libvirt: Patch for CVE-2024-4418
  SPECS/libvirt/CVE-2024-4418.patch
  SPECS/libvirt/libvirt.spec
Labels: main

#9219 gnutls: update to v3.8.3 to fix CVE-2024-0553
  SPECS/gnutls/gnutls.signatures.json
  SPECS/gnutls/gnutls.spec
  cgmanifest.json
Labels: security, 3.0

#9172 Removing nsswitch.conf from Dockerfile for building Kubevirt Golden Containers
  .pipelines/containerSourceData/kubevirt/Dockerfile-kubevirt-virt-launcher
  SPECS/cryptsetup/cryptsetup.spec
Labels: 3.0, Azure Linux 3.0

#9213 add azl-compliance package
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/azl-compliance/azl-compliance.signatures.json
  SPECS/azl-compliance/azl-compliance.spec
  cgmanifest.json
Labels: main

#9191 [2.0] Upgrade cri-o to v1.22.3 to resolve regressed CVE-2022-0811
  SPECS/cri-o/CVE-2021-3602.patch
  SPECS/cri-o/CVE-2021-44716.patch
  SPECS/cri-o/CVE-2022-1708.patch
  SPECS/cri-o/CVE-2022-27651.patch
  SPECS/cri-o/CVE-2022-29526.patch
  SPECS/cri-o/CVE-2023-44487.patch
  SPECS/cri-o/CVE-2024-21626.patch
  SPECS/cri-o/CVE-2024-28180.patch
  SPECS/cri-o/cri-o.signatures.json
  SPECS/cri-o/cri-o.spec
  cgmanifest.json
Labels: main

#9235 [2.0] Resolve telegraf CVE-2024-27289
  SPECS/telegraf/CVE-2024-27289.patch
  SPECS/telegraf/telegraf.spec
Labels: main

#8350 ig: Bump version to v0.26.0.
  SPECS/ig/ig.signatures.json
  SPECS/ig/ig.spec
  cgmanifest.json
Labels: 3.0

#9239 moby-compose: Fix CVE-2024-24786, CVE-2024-23650, CVE-2023-2253
  SPECS/moby-compose/CVE-2023-2253.patch
  SPECS/moby-compose/CVE-2024-23650.patch
  SPECS/moby-compose/CVE-2024-24786.patch
  SPECS/moby-compose/moby-compose.spec
Labels: security, main

#9150 qtbase: upgrade to version 6.6.2 to fix CVE-2023-51714
  SPECS/qtbase/qtbase.signatures.json
  SPECS/qtbase/qtbase.spec
  cgmanifest.json
Labels: security, 3.0

#9192 helm: fix CVE-2024-26147
  SPECS/cert-manager/cert-manager.spec
  SPECS/helm/CVE-2024-26147.patch
  SPECS/helm/helm.spec
Labels: security, 3.0

#9242 add patch for rubygem-rexml CVE-2024-35176
  SPECS/rubygem-rexml/CVE-2024-35176.patch
  SPECS/rubygem-rexml/rubygem-rexml.spec
Labels: security, main

#9250 Patch nodejs18 to address CVE-2023-21100
  SPECS/nodejs/CVE-2023-21100.patch
  SPECS/nodejs/CVE-2023-42282.patch
  SPECS/nodejs/CVE-2024-22025.patch
  SPECS/nodejs/CVE-2024-24806.patch
  SPECS/nodejs/CVE-2024-27983.patch
  SPECS/nodejs/disable-tlsv1-tlsv1-1.patch
  SPECS/nodejs/nodejs18.spec
Labels: main

#9246 Enable KNI module in DPDK build
  SPECS/dpdk/dpdk.spec
Labels: main

#9201 Move rasdaemon from extended to core and upgrade to 0.8.0
  SPECS-EXTENDED/rasdaemon/rasdaemon.signatures.json
  SPECS/rasdaemon/rasdaemon.signatures.json
  SPECS/rasdaemon/rasdaemon.spec
  cgmanifest.json
Labels: 3.0

#9247 libkcapi: Package proper measurements & binary aliases in libkcapi for fips boot
  SPECS/libkcapi/fipshmac-openssl.sh
  SPECS/libkcapi/libkcapi.signatures.json
  SPECS/libkcapi/libkcapi.spec
  SPECS/libkcapi/sha512hmac-openssl.sh
Labels: bug, 3.0, Azure Linux 3.0

#9236 fluent-bit: Update to v3.0.6 to fix CVE-2024-4323
  SPECS/fluent-bit/fluent-bit.signatures.json
  SPECS/fluent-bit/fluent-bit.spec
  cgmanifest.json
Labels: security, 3.0

#9267 add patch for ruby CVE-2024-35176
  SPECS/ruby/CVE-2024-35176.patch
  SPECS/ruby/ruby.spec
Labels: main

#9268 Patch CVE-2024-26147 for cert-manager
  SPECS/cert-manager/CVE-2024-26147.patch
  SPECS/cert-manager/cert-manager.spec
Labels: main

#9270 Address kernel CVE-2022-38096, CVE-2023-47233, CVE-2023-52827, CVE-2024-25739, CVE-2024-26900, CVE-2024-26902, CVE-2024-26929, CVE-2024-26934, CVE-2024-26949, CVE-2024-26952, CVE-2024-26979, CVE-2024-27013, CVE-2024-27015, CVE-2024-27016, CVE-2024-27018, CVE-2024-27019, CVE-2024-27020, CVE-2024-35978, CVE-2024-35982, CVE-2024-35984, CVE-2024-35990, CVE-2024-35997, CVE-2024-36008
  SPECS/kernel/CVE-2022-38096.nopatch
  SPECS/kernel/CVE-2023-47233.nopatch
  SPECS/kernel/CVE-2023-52827.nopatch
  SPECS/kernel/CVE-2024-25739.nopatch
  SPECS/kernel/CVE-2024-26900.nopatch
  SPECS/kernel/CVE-2024-26902.nopatch
  SPECS/kernel/CVE-2024-26929.nopatch
  SPECS/kernel/CVE-2024-26934.nopatch
  SPECS/kernel/CVE-2024-26949.nopatch
  SPECS/kernel/CVE-2024-26952.nopatch
  SPECS/kernel/CVE-2024-26979.nopatch
  SPECS/kernel/CVE-2024-27013.nopatch
  SPECS/kernel/CVE-2024-27015.nopatch
  SPECS/kernel/CVE-2024-27016.nopatch
  SPECS/kernel/CVE-2024-27018.nopatch
  SPECS/kernel/CVE-2024-27019.nopatch
  SPECS/kernel/CVE-2024-27020.nopatch
  SPECS/kernel/CVE-2024-35978.nopatch
  SPECS/kernel/CVE-2024-35982.nopatch
  SPECS/kernel/CVE-2024-35984.nopatch
  SPECS/kernel/CVE-2024-35990.nopatch
  SPECS/kernel/CVE-2024-35997.nopatch
  SPECS/kernel/CVE-2024-36008.nopatch
Labels: security, main

#9251 Improve network behavior, use contexts instead of cancel channel
  toolkit/tools/downloader/downloader.go
  toolkit/tools/internal/network/network.go
  toolkit/tools/internal/network/network_test.go
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
  toolkit/tools/internal/retry/retry.go
  toolkit/tools/internal/retry/retry_test.go
  toolkit/tools/internal/safechroot/safechroot.go
  toolkit/tools/internal/safemount/safemount.go
  toolkit/tools/pkg/downloader/downloader.go
  toolkit/tools/pkg/specreaderutils/specreaderutil.go
  toolkit/tools/precacher/precacher.go
  toolkit/tools/srpmpacker/srpmpacker.go
Labels: Tools, 3.0

#9244 unixODBC: patch CVE-2024-1013
  SPECS/unixODBC/CVE-2024-1013.patch
  SPECS/unixODBC/unixODBC.spec
Labels: security, 3.0

#9260 python-werkzeug: Update to 3.0.3 to fix CVE-2024-34069
  SPECS/python-tensorboard/python-tensorboard.spec
  SPECS/python-werkzeug/python-werkzeug.signatures.json
  SPECS/python-werkzeug/python-werkzeug.spec
  SPECS/tensorflow/tensorflow.spec
  cgmanifest.json
Labels: security, 3.0

#9245 llvm: patch cve-2024-31852
  SPECS/clang/clang.spec
  SPECS/compiler-rt/compiler-rt.spec
  SPECS/lld/lld.spec
  SPECS/lldb/lldb.spec
  SPECS/llvm/CVE-2024-31852.patch
  SPECS/llvm/llvm.spec
  SPECS/rust/rust.spec
  SPECS/tensorflow/tensorflow.spec
Labels: security, 3.0

#9280 update and correct ruby CVE-2024035176.patch
  SPECS/ruby/CVE-2024-35176.patch
Labels: security, main
