Repository microsoft/azurelinux, pull requests merged in 2024-09, with the labels that each got.

#10172 Patch CVE-2024-29018 in moby-engine
  SPECS/moby-engine/CVE-2024-29018.patch
  SPECS/moby-engine/moby-engine.spec
Labels: Packaging, main

#10316 Add patch to fix CVE-2024-43788 in python-tensorboard
  SPECS/python-tensorboard/CVE-2024-43788.patch
  SPECS/python-tensorboard/python-tensorboard.spec
Labels: security, Packaging, 3.0-dev

#10266 upgrade perl-sub-install to v0.929
  SPECS/perl-Sub-Install/perl-Sub-Install.signatures.json
  SPECS/perl-Sub-Install/perl-Sub-Install.spec
  cgmanifest.json
Labels: 3.0-dev

#10280 port 3 perl packages from extended into core
  SPECS-EXTENDED/perl-PadWalker/perl-PadWalker.signatures.json
  SPECS-EXTENDED/perl-Test-Without-Module/perl-Test-Without-Module.signatures.json
  SPECS/perl-PadWalker/perl-PadWalker.signatures.json
  SPECS/perl-PadWalker/perl-PadWalker.spec
  SPECS/perl-Sub-Identify/perl-Sub-Identify.signatures.json
  SPECS/perl-Sub-Identify/perl-Sub-Identify.spec
  SPECS/perl-Test-Without-Module/perl-Test-Without-Module.signatures.json
  SPECS/perl-Test-Without-Module/perl-Test-Without-Module.spec
  cgmanifest.json
Labels: Packaging, 3.0-dev

#10267 port perl-Sub-Exporter-Progressive
  SPECS/perl-Sub-Exporter-Progressive/Sub-Exporter-Progressive-0.001013-old-Test-More.patch
  SPECS/perl-Sub-Exporter-Progressive/perl-Sub-Exporter-Progressive.signatures.json
  SPECS/perl-Sub-Exporter-Progressive/perl-Sub-Exporter-Progressive.spec
Labels: Packaging, 3.0-dev

#10309 add perl-Devel-Refcount
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS/perl-Devel-Refcount/perl-Devel-Refcount.signatures.json
  SPECS/perl-Devel-Refcount/perl-Devel-Refcount.spec
  cgmanifest.json
Labels: 3.0-dev

#10325 add missing vendor and distribution tags in new specs
  SPECS/perl-Match-Simple/perl-Match-Simple.spec
  SPECS/perl-Sub-Infix/perl-Sub-Infix.spec
Labels: Packaging

#10174 Update virt_launcher.cil installation path in virt-handler container
  SPECS/kubevirt/kubevirt.spec
Labels: Packaging

#10279 nss: Disable DBM backend.
  SPECS/nss/nss.spec
Labels: Packaging

#10327 add missing vendor and distribution tags to core specs
  SPECS/azure-nvme-utils/azure-nvme-utils.spec
  SPECS/ebtables/ebtables.spec
  SPECS/glslang/glslang.spec
  SPECS/kata-containers-cc/kata-containers-cc.spec
  SPECS/kata-containers/kata-containers.spec
  SPECS/libburn/libburn.spec
  SPECS/libidn2/libidn2.spec
  SPECS/libiscsi/libiscsi.spec
  SPECS/libisofs/libisofs.spec
  SPECS/libnbd/libnbd.spec
  SPECS/libnvme/libnvme.spec
  SPECS/libsafec/libsafec.spec
  SPECS/libtpms/libtpms.spec
  SPECS/libtracecmd/libtracecmd.spec
  SPECS/libtracefs/libtracefs.spec
  SPECS/libva/libva.spec
  SPECS/lujavrite/lujavrite.spec
  SPECS/mandoc/mandoc.spec
  SPECS/mdadm/mdadm.spec
  SPECS/mdevctl/mdevctl.spec
  SPECS/ocaml-camlp-streams/ocaml-camlp-streams.spec
  SPECS/opensc/opensc.spec
  SPECS/pam_krb5/pam_krb5.spec
  SPECS/perl-XML-LibXML/perl-XML-LibXML.spec
  SPECS/polkit-qt-1/polkit-qt-1.spec
  SPECS/python-decorator/python-decorator.spec
  SPECS/python-hatch-fancy-pypi-readme/python-hatch-fancy-pypi-readme.spec
  SPECS/python-kubernetes/python-kubernetes.spec
  SPECS/python-pytest-flakes/python-pytest-flakes.spec
  SPECS/python-six/python-six.spec
  SPECS/python-xlsxwriter/python-xlsxwriter.spec
  SPECS/python-zstd/python-zstd.spec
  SPECS/rpmdevtools/rpmdevtools.spec
  SPECS/shared-mime-info/shared-mime-info.spec
  SPECS/swtpm/swtpm.spec
  SPECS/sysbench/sysbench.spec
Labels: Packaging

#10299 python-packaging: fix provides
  SPECS/python-packaging/python-packaging.spec
  SPECS/python-pygments/python-pygments.spec
  SPECS/python-setuptools/python-setuptools.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
Labels: 3.0-dev

#10321 Optimizing OverlayFS module with new IFS separator and new supported mode.
  SPECS/dracut/20overlayfs/overlayfs-mount.sh
  SPECS/dracut/dracut.signatures.json
Labels: Packaging

#10326 Backport trace-cmd and dependencies from 3.0
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/libtracecmd/libtracecmd.signatures.json
  SPECS/libtracecmd/libtracecmd.spec
  SPECS/libtraceevent/libtraceevent.signatures.json
  SPECS/libtraceevent/libtraceevent.spec
  SPECS/libtracefs/libtracefs.signatures.json
  SPECS/libtracefs/libtracefs.spec
  SPECS/trace-cmd/98-trace-cmd.rules
  SPECS/trace-cmd/trace-cmd.conf
  SPECS/trace-cmd/trace-cmd.service
  SPECS/trace-cmd/trace-cmd.signatures.json
  SPECS/trace-cmd/trace-cmd.spec
  cgmanifest.json
Labels: main

#10274 Fix CVE-2022-32149 in application-gateway-kubernetes-ingress
  SPECS/application-gateway-kubernetes-ingress/CVE-2022-32149.patch
  SPECS/application-gateway-kubernetes-ingress/application-gateway-kubernetes-ingress.spec
Labels: Packaging

#10301 Fix CVE-2022-32149 in prometheus-adapter
  SPECS/prometheus-adapter/CVE-2022-32149.patch
  SPECS/prometheus-adapter/prometheus-adapter.spec
Labels: Packaging

#10302 keda: Fix CVE-2022-32149 with a patch
  SPECS/keda/CVE-2022-32149.patch
  SPECS/keda/keda.spec
Labels: Packaging

#10243 jasper: Add patch to resolve CVE-2023-51257
  SPECS/jasper/CVE-2023-51257.patch
  SPECS/jasper/jasper.spec
Labels: security, Packaging, fasttrack/2.0

#10241 libsndfile: Add patch to resolve CVE-2022-33065
  SPECS/libsndfile/CVE-2022-33065.patch
  SPECS/libsndfile/libsndfile.spec
Labels: Packaging, fasttrack/2.0

#10304 vte291: apply correct patch for cve-2024-37535 fix (CP# 10291)
  SPECS/vte291/CVE-2024-37535.patch
  SPECS/vte291/vte291.spec
Labels: Packaging

#10230 cdi: CVE-2022-41717, CVE-2022-32149, CVE-2024-28180
  SPECS/containerized-data-importer/CVE-2022-32149.patch
  SPECS/containerized-data-importer/CVE-2022-41717.patch
  SPECS/containerized-data-importer/CVE-2024-28180.patch
  SPECS/containerized-data-importer/containerized-data-importer.spec
Labels: Packaging, main

#10183 libnbd: cve-2024-7383 (mariner 2.0)
  SPECS/libnbd/CVE-2024-7383.patch
  SPECS/libnbd/libnbd.spec
Labels: security, Packaging, main

#10232 kubevirt: CVE-2022-32149 and CVE-2023-26484
  SPECS/kubevirt/CVE-2022-32149.patch
  SPECS/kubevirt/CVE-2023-26484.patch
  SPECS/kubevirt/kubevirt.spec
Labels: Packaging, main

#10192 vim: CVE-2024-43374 (mariner 2)
  SPECS/vim/CVE-2024-43374.patch
  SPECS/vim/vim.spec
Labels: security, Packaging, main

#10176 qemu: CVE-2024-24474 (mariner 2)
  SPECS/qemu/CVE-2024-24474.patch
  SPECS/qemu/qemu.spec
Labels: security, Packaging, main

#10355 Updated the `upload-artifact` GitHub Action to version 4.
  .github/workflows/go-test-coverage.yml
  .github/workflows/lint-specs.yml
Labels: main

#10344 Image Customizer: Bump version to v0.7
  toolkit/scripts/build_tag_imagecustomizer.mk
Labels: Tools

#10332 add missing tags
  SPECS/build-essential/build-essential.spec
  SPECS/rtctl/rtctl.spec
  SPECS/trace-cmd/trace-cmd.spec
  SPECS/vte291/vte291.spec
Labels: Packaging

#10283 Patch CVE-2024-3651 for python-pip
  SPECS/python-pip/CVE-2024-3651.patch
  SPECS/python-pip/python-pip.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, 3.0-dev

#10336 port more perl packages from extended
  SPECS/perl-Module-Implementation/perl-Module-Implementation.signatures.json
  SPECS/perl-Module-Implementation/perl-Module-Implementation.spec
  SPECS/perl-Perl-Destruct-Level/perl-Perl-Destruct-Level.signatures.json
  SPECS/perl-Perl-Destruct-Level/perl-Perl-Destruct-Level.spec
  SPECS/perl-Test-Taint/perl-Test-Taint.signatures.json
  SPECS/perl-Test-Taint/perl-Test-Taint.spec
Labels: Packaging

#10333 port perl-Devel-GlobalDestruction
  SPECS/perl-Devel-GlobalDestruction/perl-Devel-GlobalDestruction.signatures.json
  SPECS/perl-Devel-GlobalDestruction/perl-Devel-GlobalDestruction.spec
Labels: Packaging

#10244 sysstat: upgrade version 12.7.1 -> 12.7.6 to address CVE-2018-19416
  SPECS/sysstat/CVE-2023-33204.patch
  SPECS/sysstat/sysstat.signatures.json
  SPECS/sysstat/sysstat.spec
  cgmanifest.json
Labels: security, main

#10276 Patch CVE-2024-6923 in python3
  SPECS/python3/CVE-2024-6923.patch
  SPECS/python3/python3.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, 3.0-dev

#10184 libzip: fix package tests
  SPECS/libzip/always_generate_regression_tests.patch
  SPECS/libzip/libzip.spec
Labels: Packaging, ptest, 3.0-dev

#9874 OSModifier: Add support for updating grub
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/osmodifier/main.go
  toolkit/tools/osmodifierapi/identifiedpartition.go
  toolkit/tools/osmodifierapi/os.go
  toolkit/tools/osmodifierapi/overlay.go
  toolkit/tools/pkg/imagecustomizerlib/bootcustomizer.go
  toolkit/tools/pkg/imagecustomizerlib/bootcustomizer_test.go
  toolkit/tools/pkg/imagecustomizerlib/customizeselinux.go
  toolkit/tools/pkg/imagecustomizerlib/defaultgrubutils.go
  toolkit/tools/pkg/imagecustomizerlib/grubcfgutils.go
  toolkit/tools/pkg/osmodifierlib/modifierutils.go
  toolkit/tools/pkg/osmodifierlib/modifydefaultgrub.go
  toolkit/tools/pkg/osmodifierlib/osmodifier.go
Labels: Tools, 3.0-dev

#10363 Image Customizer: Functional tests for kernel modules API.
  toolkit/tools/pkg/imagecustomizerlib/kernelmoduleutils.go
  toolkit/tools/pkg/imagecustomizerlib/kernelmoduleutils_test.go
Labels: Tools

#10362 Fix multiple CVEs in moby-buildx package
  SPECS/moby-buildx/CVE-2021-41092.patch
  SPECS/moby-buildx/CVE-2022-41717.patch
  SPECS/moby-buildx/CVE-2023-45288.patch
  SPECS/moby-buildx/CVE-2023-48795.patch
  SPECS/moby-buildx/moby-buildx.spec
Labels: security, Packaging, fasttrack/2.0

#10379 Adding swtpmtools to list of required packages for kubevirt
  SPECS/kubevirt/kubevirt.spec
Labels: Packaging

#10374 Fix for Azure Linux 3.0 Arm64 ISO OS installation issue
  toolkit/imageconfigs/packagelists/core-packages-image-aarch64.json
Labels: Schema

#10370 toolkit: pkgbld: add ccache option & switch QUICK_REBUILD_PACKAGES=y
  toolkit/pkgbld.sh
Labels: DevEx, 3.0-dev

#10322 ig: Bump to v0.32.0.
  SPECS/ig/ig.signatures.json
  SPECS/ig/ig.spec
  cgmanifest.json
Labels: 3.0-dev

#10083 tpm2-tss: Add patch to resolve CVE-2024-29040
  SPECS/tpm2-tss/CVE-2024-29040.patch
  SPECS/tpm2-tss/tpm2-tss.spec
Labels: security, Packaging, main

#10205 multus: Add patch to resolve CVE-2023-3978
  SPECS/multus/CVE-2023-3978.patch
  SPECS/multus/multus.spec
Labels: security, Packaging, main

#10285 Add postgresql-service subpackage
  SPECS/postgresql/postgresql.service
  SPECS/postgresql/postgresql.signatures.json
  SPECS/postgresql/postgresql.spec
Labels: Packaging, 3.0-dev

#10380 Bump Go Version to 1.22.7-1
  SPECS/golang/golang.signatures.json
  SPECS/golang/golang.spec
  cgmanifest.json
Labels: 3.0-dev

#10331 Upgrade expat to 2.6.3 to fix CVE-2024-45490, CVE-2024-45491, CVE-2024-45492
  SPECS/expat/expat.signatures.json
  SPECS/expat/expat.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, 3.0-dev

#10387 azurelinux-sysinfo: add rpm as a requirement
  SPECS/azurelinux-sysinfo/azurelinux-sysinfo.spec
Labels: Packaging

#10378 [cherry-pick] vim: CVE-2024-43374 (mariner 2) (#10192)
  SPECS/vim/CVE-2024-43374.patch
  SPECS/vim/vim.spec
Labels: Packaging, main, Auto Fast-track Cherry-pick

#10377 [cherry-pick] kubevirt: CVE-2022-32149 and CVE-2023-26484 (#10232)
  SPECS/kubevirt/CVE-2022-32149.patch
  SPECS/kubevirt/CVE-2023-26484.patch
  SPECS/kubevirt/kubevirt.spec
Labels: Packaging, main, Auto Fast-track Cherry-pick

#10376 [Cherry-Pick] Fix CVE-2022-32149 in application-gateway-kubernetes-ingress (#10274)
  SPECS/application-gateway-kubernetes-ingress/CVE-2022-32149.patch
  SPECS/application-gateway-kubernetes-ingress/application-gateway-kubernetes-ingress.spec
Labels: Packaging, main, Auto Fast-track Cherry-pick

#10386 Image Customizer: Add doc for 'sshPublicKeys'.
  toolkit/tools/imagecustomizer/docs/configuration.md
Labels: Tools

#10384 Image Customizer: Rename 'fileSystems' to 'filesystems'.
  toolkit/tools/imagecustomizer/docs/configuration.md
  toolkit/tools/imagecustomizerapi/config_test.go
  toolkit/tools/imagecustomizerapi/storage.go
  toolkit/tools/pkg/imagecustomizerlib/testdata/install-package-disk-space.yaml
  toolkit/tools/pkg/imagecustomizerlib/testdata/legacyboot-config.yaml
  toolkit/tools/pkg/imagecustomizerlib/testdata/mshvkernel-config.yaml
  toolkit/tools/pkg/imagecustomizerlib/testdata/overlays-config.yaml
  toolkit/tools/pkg/imagecustomizerlib/testdata/partitions-config.yaml
  toolkit/tools/pkg/imagecustomizerlib/testdata/partitions-selinux-enforcing.yaml
  toolkit/tools/pkg/imagecustomizerlib/testdata/verity-config.yaml
Labels: Tools

#10391 msft-golang: bump version to 1.22.7 to address 3 CVEs
  SPECS/msft-golang/msft-golang.signatures.json
  SPECS/msft-golang/msft-golang.spec
  cgmanifest.json
Labels: security, fasttrack/2.0

#10383 Image Customizer: Allow omitting disk maxSize and partition start.
  toolkit/tools/imagecustomizerapi/config_test.go
  toolkit/tools/imagecustomizerapi/disk.go
  toolkit/tools/imagecustomizerapi/disk_test.go
  toolkit/tools/imagecustomizerapi/partition.go
  toolkit/tools/imagecustomizerapi/partition_test.go
  toolkit/tools/imagecustomizerapi/storage.go
  toolkit/tools/imagecustomizerapi/storage_test.go
  toolkit/tools/pkg/imagecustomizerlib/customizepartitions_test.go
  toolkit/tools/pkg/imagecustomizerlib/liveosisobuilder.go
  toolkit/tools/pkg/imagecustomizerlib/testdata/partitions-size-only-config.yaml
  toolkit/tools/pkg/imagecustomizerlib/typeConversion.go
Labels: Tools

#10419 Removing hotplug detach grace period patch from kubevirt
  SPECS/kubevirt/Hotplug_detach_grace_period.patch
  SPECS/kubevirt/kubevirt.spec
Labels: Packaging, main

#10404 Image Customizer: Add support for 'vfat' filesystem.
  toolkit/tools/imagecustomizer/docs/configuration.md
  toolkit/tools/imagecustomizerapi/filesystemtype.go
  toolkit/tools/imagecustomizerapi/storage.go
  toolkit/tools/imagecustomizerapi/storage_test.go
  toolkit/tools/imagegen/diskutils/diskutils.go
  toolkit/tools/pkg/imagecustomizerlib/testdata/partitions-selinux-enforcing.yaml
Labels: Tools

#10422 Image Customizer: Fix merge conflict.
  toolkit/tools/imagecustomizerapi/storage_test.go
Labels: Tools

#10128 Patch CVE-2024-6197 in curl
  SPECS/curl/CVE-2024-6197.patch
  SPECS/curl/curl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, 3.0-dev

#10375 Fix CVE-2022-40898 for python-wheel
  SPECS/python-wheel/CVE-2022-40898.patch
  SPECS/python-wheel/python-wheel.spec
Labels: Packaging, fasttrack/2.0

#10424 Remove exit 1 for glibc check section
  SPECS/glibc/glibc.spec
Labels: Packaging

#10398 Add patch to resolve CVE 2024 28085
  SPECS/util-linux/CVE-2024-28085.patch
  SPECS/util-linux/util-linux.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#10429 Add package libmd
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS/libmd/4F3E74F436050C10F5696574B972BF3EA4AE57A3
  SPECS/libmd/libmd-1.1.0.tar.xz.asc
  SPECS/libmd/libmd.signatures.json
  SPECS/libmd/libmd.spec
  cgmanifest.json
Labels: 3.0-dev

#10442 Enable building mokutil for aarch64
  SPECS/mokutil/mokutil.spec
Labels: Packaging

#10439 update wget with patches from fedora
  SPECS/wget/0002-normalize-path-in-url.patch
  SPECS/wget/0003-Allow-option-no-tcp-fastopen-to-work-on-Linux-kernel.patch
  SPECS/wget/0004-Disable-OCSP-by-default.patch
  SPECS/wget/0005-Accept-progress-dot-.-for-backwards-compatibility.patch
  SPECS/wget/0006-Disable-TCP-Fast-Open-by-default.patch
  SPECS/wget/wget.spec
Labels: Packaging

#10357 cloud-init add azure proxy agent
  SPECS/cloud-init/0001-feat-azure-Add-ProvisionGuestProxyAgent-OVF-setting.patch
  SPECS/cloud-init/0002-feat-azure-parse-ProvisionGuestProxyAgent-as-bool-51.patch
  SPECS/cloud-init/0003-feat-azure-add-support-for-azure-proxy-agent.patch
  SPECS/cloud-init/cloud-init.spec
Labels: Packaging, main, stable-release-2.0

#10411 Fix nfs-utils to build rsc.svcgssd and provide the missing rpc-gssd service
  SPECS/nfs-utils/nfs-utils.spec
Labels: Packaging

#10432 Backport CVE-2024-3727 fix for libcontainers-common
  SPECS/libcontainers-common/CVE-2024-3727.patch
  SPECS/libcontainers-common/libcontainers-common.spec
  SPECS/libcontainers-common/podman-CVE-2024-3727.patch
Labels: Packaging

#10443 Fix CVE-2022-32149 in cri-o
  SPECS/cri-o/CVE-2022-32149.patch
  SPECS/cri-o/cri-o.spec
Labels: Packaging

#10311 kernel-uki: drop dbus in initrd
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS-SIGNED/kernel-uki-signed/kernel-uki-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/kernel-uki-dracut.conf
  SPECS/kernel/kernel-uki.signatures.json
  SPECS/kernel/kernel-uki.spec
  SPECS/kernel/kernel.spec
Labels: documentation, security, Packaging, Tools, Schema

#10288 vte291: patch CVE-2024-37535 (CP: #10275)
  SPECS/vte291/CVE-2024-37535.patch
  SPECS/vte291/vte291.spec
Labels: Packaging

#10446 selinux-policy: Add cloud-utils-growpart fix.
  SPECS/selinux-policy/0036-fstools-Add-additional-perms-for-cloud-utils-growpar.patch
  SPECS/selinux-policy/0037-docker-Fix-dockerc-typo-in-container_engine_executab.patch
  SPECS/selinux-policy/selinux-policy.spec
Labels: Packaging, 3.0-dev

#10461 update wget to fix potential infinite loop
  SPECS/wget/fix-ssl-read-and-write-error-check.patch
  SPECS/wget/wget.spec
Labels: Packaging

#10400 Resolve CVE-2024-41946
  SPECS/ruby/ruby.signatures.json
  SPECS/ruby/ruby.spec
  cgmanifest.json
Labels: security, 3.0-dev

#10395 Creating Busybox SBOM by not deleting the rpm db
  .pipelines/containerSourceData/busybox/Dockerfile-Busybox
Labels: main

#10455 cloud-init add patch for PPS support of auzre-proxy-agent
  SPECS/cloud-init/0001-add-PPS-support-for-azure-proxy-agent.patch
  SPECS/cloud-init/cloud-init.spec
Labels: Packaging, main

#10463 Upgrade cert-manager to 1.12.13 to get upstream patches for CVE-2024-25620 and CVE-2024-26147
  SPECS/cert-manager/cert-manager.signatures.json
  SPECS/cert-manager/cert-manager.spec
  cgmanifest.json
Labels: security

#10479 ccache: remove dangling link to host-cc
  SPECS/ccache/ccache.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 3.0-dev

#10471 toolkit: scripts: use '#!/usr/bin/env python3' instead of hardcoding interpreter
  toolkit/scripts/check_entangled_specs.py
  toolkit/scripts/check_spec_guidelines.py
  toolkit/scripts/check_static_glibc.py
  toolkit/scripts/license_map.py
  toolkit/scripts/spec_source_attributions.py
  toolkit/scripts/update_cgmanifest.py
  toolkit/scripts/update_toolchain_manifest.py
Labels: Tools, 3.0-dev

#10473 [2.0] Use Toolchain RPMS when building Golden Container
  .pipelines/containerSourceData/scripts/BuildGoldenContainer.sh
Labels: main

#10466 Patch libxml2 to resolve CVE-2024-25062
  SPECS/libxml2/CVE-2024-25062.patch
  SPECS/libxml2/libxml2.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: fasttrack/2.0

#10472 OSModifier: allow two linux cmdline in grub.cfg
  toolkit/tools/pkg/imagecustomizerlib/grubcfgutils.go
  toolkit/tools/pkg/osmodifierlib/modifydefaultgrub.go
Labels: Tools

#10486 patch wget to prevent debug output from printing binary request bodies
  SPECS/wget/set-debug_skip_body-for-OCSP-requests-in-openssl-tls-provider.patch
  SPECS/wget/wget.spec
Labels: Packaging

#10465 Patch influxdb to resolve CVE-2022-32149
  SPECS/influxdb/CVE-2022-32149.patch
  SPECS/influxdb/influxdb.spec
Labels: Packaging, fasttrack/2.0

#10468 Patch xorg-x11-server for CVE-2024-0229, CVE-2024-0409 & CVE-2024-21886
  SPECS/xorg-x11-server/CVE-2024-0229.patch
  SPECS/xorg-x11-server/CVE-2024-0409.patch
  SPECS/xorg-x11-server/CVE-2024-21886.patch
  SPECS/xorg-x11-server/xorg-x11-server.spec
Labels: Packaging, fasttrack/2.0

#10493 [Cherry-pick] Update virt_launcher.cil installation path in virt-handler container
  SPECS/kubevirt/kubevirt.spec
Labels: Packaging

#10371 cni: address CVE-2022-32149
  SPECS/cni/CVE-2022-32149.patch
  SPECS/cni/cni.spec
Labels: security, Packaging, 3.0-dev

#10081 vim: Add patch to resolve CVE-2024-41957 & CVE-2024-41965.
  SPECS/vim/CVE-2024-41957.patch
  SPECS/vim/CVE-2024-41965.patch
  SPECS/vim/vim.spec
Labels: security, Packaging, main

#9909 Fix CVE-2024-6345 in setuptools
  SPECS/python-setuptools/CVE-2024-6345.patch
  SPECS/python-setuptools/python-setuptools.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, 3.0-dev

#10474 [3.0] Use Toolchain RPMS when building Golden Container
  .pipelines/containerSourceData/scripts/BuildGoldenContainer.sh
Labels: 3.0-dev

#10489 Fixes CVE-2022-32149 by backporting the fix as a patch file
  SPECS/cf-cli/CVE-2022-32149.patch
  SPECS/cf-cli/cf-cli.spec
Labels: Packaging

#10480 Fix bad interactions between timeouts and build retires
  toolkit/tools/internal/logger/log.go
  toolkit/tools/internal/shell/shell.go
  toolkit/tools/pkgworker/pkgworker.go
  toolkit/tools/scheduler/buildagents/chrootagent.go
  toolkit/tools/scheduler/buildagents/definition.go
  toolkit/tools/scheduler/buildagents/testagent.go
  toolkit/tools/scheduler/scheduler.go
  toolkit/tools/scheduler/schedulerutils/buildworker.go
Labels: bug, Tools, go, 3.0-dev

#10506 Add patch for CVE-2024-41946 to ruby and rubygem-rexml
  SPECS/ruby/CVE-2024-41946.patch
  SPECS/ruby/ruby.spec
  SPECS/rubygem-rexml/CVE-2024-41946.patch
  SPECS/rubygem-rexml/rubygem-rexml.spec
Labels: Packaging

#10503 Patch gdk-pixbuf2 for CVE-2022-48622.
  SPECS/gdk-pixbuf2/CVE-2022-48622.patch
  SPECS/gdk-pixbuf2/gdk-pixbuf2.spec
Labels: Packaging, fasttrack/2.0

#10201 Patch CVE-2024-29018 in moby-engine to fix
  SPECS/moby-engine/CVE-2024-29018.patch
  SPECS/moby-engine/moby-engine.spec
Labels: Packaging

#10469 pytorch: add patch for CVE-2024-27318, CVE-2022-1941
  SPECS/pytorch/CVE-2022-1941.patch
  SPECS/pytorch/CVE-2024-27318.patch
  SPECS/pytorch/pytorch.spec
Labels: Packaging

#10462 add edk2 patches for CVE-2022-36763, CVE-2022-36764, CVE-2022-36765, CVE-2023-45230, CVE-2023-45236, CVE-2023-45232, CVE-2023-45233, CVE-2023-45234, CVE-2023-45235, CVE-2023-45237
  SPECS/edk2/CVE-2022-36763.patch
  SPECS/edk2/CVE-2022-36764.nopatch
  SPECS/edk2/CVE-2022-36765.patch
  SPECS/edk2/CVE-2023-45230.patch
  SPECS/edk2/CVE-2023-45232.patch
  SPECS/edk2/CVE-2023-45233.nopatch
  SPECS/edk2/CVE-2023-45234.patch
  SPECS/edk2/CVE-2023-45235.patch
  SPECS/edk2/CVE-2023-45236.patch
  SPECS/edk2/CVE-2023-45237.patch
  SPECS/edk2/edk2.spec
  SPECS/edk2/fix-tpm-build-issue-from-CVE-2022-36763.patch
Labels: Packaging

#10504 Patch gdk-pixbuf2 for CVE-2022-48622
  SPECS/gdk-pixbuf2/CVE-2022-48622.patch
  SPECS/gdk-pixbuf2/gdk-pixbuf2.spec
Labels: Packaging, 3.0

#10445 Add package php-pecl-apcu to core SPECS
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS/php-pecl-apcu/apcu-panel.conf
  SPECS/php-pecl-apcu/apcu.conf.php
  SPECS/php-pecl-apcu/apcu.ini
  SPECS/php-pecl-apcu/php-pecl-apcu.signatures.json
  SPECS/php-pecl-apcu/php-pecl-apcu.spec
  cgmanifest.json
Labels: 3.0-dev

#10513 Patch CVE-2019-10906 in nodejs
  SPECS/nodejs/CVE-2019-10906.patch
  SPECS/nodejs/nodejs.spec
Labels: Packaging

#10525 swap fix-ssl-read-and-write-error-check.patch for a slightly different version from upstream
  SPECS/wget/fix-ssl-read-and-write-error-check.patch
  SPECS/wget/wget.spec
Labels: Packaging

#10512 add patch for edk2 CVE-2024-6119
  SPECS/edk2/CVE-2024-6119.patch
  SPECS/edk2/edk2.spec
Labels: Packaging

#10523 Update MIC doc to reference overlay driver and fstab for overlay feature.
  toolkit/tools/imagecustomizer/docs/configuration.md
Labels: Tools

#10518 OSModifier: Read root device from grub.cfg
  toolkit/tools/pkg/imagecustomizerlib/bootcustomizer.go
  toolkit/tools/pkg/osmodifierlib/modifydefaultgrub.go
Labels: Tools

#10475 Update openssl to 3.3.2 under cloud-hypervisor-cvm in order to address CVE-2024-6119
  SPECS/cloud-hypervisor-cvm/cloud-hypervisor-cvm.signatures.json
  SPECS/cloud-hypervisor-cvm/cloud-hypervisor-cvm.spec
  SPECS/cloud-hypervisor-cvm/upgrade-openssl-to-3.3.2-to-address-CVE-2024-6119.patch
Labels: security, Packaging

#10476 Update openssl to 3.3.2 under cloud-hypervisor-cvm in order to address CVE-2024-6119
  SPECS/cloud-hypervisor-cvm/cloud-hypervisor-cvm.signatures.json
  SPECS/cloud-hypervisor-cvm/cloud-hypervisor-cvm.spec
  SPECS/cloud-hypervisor-cvm/upgrade-openssl-to-3.3.2-to-address-CVE-2024-6119.patch
Labels: Packaging

#10531 Add Mosh to Extended packages
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS-EXTENDED/mosh/mosh.signatures.json
  SPECS-EXTENDED/mosh/mosh.spec
  cgmanifest.json
Labels: specs-extended, 3.0-dev

#10521 patch CVE-2024-6232 and CVE-2024-8088 for python3 3.0
  SPECS/python3/CVE-2024-6232.patch
  SPECS/python3/CVE-2024-8088.patch
  SPECS/python3/python3.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#10517 Image Customizer: Change additionalFiles to a list.
  toolkit/tools/imagecustomizer/docs/configuration.md
  toolkit/tools/imagecustomizerapi/additionalfile.go
  toolkit/tools/imagecustomizerapi/additionalfile_test.go
  toolkit/tools/imagecustomizerapi/additionalfilesmap.go
  toolkit/tools/imagecustomizerapi/config_test.go
  toolkit/tools/imagecustomizerapi/fileconfig.go
  toolkit/tools/imagecustomizerapi/fileconfig_test.go
  toolkit/tools/imagecustomizerapi/iso.go
  toolkit/tools/imagecustomizerapi/os.go
  toolkit/tools/imagecustomizerapi/os_test.go
  toolkit/tools/internal/file/filecopybuilder.go
  toolkit/tools/internal/safechroot/safechroot.go
  toolkit/tools/pkg/imagecustomizerlib/customizefiles.go
  toolkit/tools/pkg/imagecustomizerlib/customizefiles_test.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
  toolkit/tools/pkg/imagecustomizerlib/liveosisobuilder.go
  toolkit/tools/pkg/imagecustomizerlib/liveosisobuilder_test.go
  toolkit/tools/pkg/imagecustomizerlib/testdata/addfiles-config.yaml
  toolkit/tools/pkg/imagecustomizerlib/testdata/cloud-init-config.yaml
  toolkit/tools/pkg/imagecustomizerlib/testdata/cloud-init-iso-config.yaml
  toolkit/tools/pkg/imagecustomizerlib/testdata/infinite-file-config.yaml
  toolkit/tools/pkg/imagecustomizerlib/testdata/iso-files-and-args-config.yaml
  toolkit/tools/pkg/imagecustomizerlib/testdata/verity-config.yaml
Labels: Tools

#10540 haproxy: upgrade to 2.9.11 to fix CVE-2024-45506
  SPECS/haproxy/haproxy.signatures.json
  SPECS/haproxy/haproxy.spec
  cgmanifest.json
Labels: Packaging, 3.0-dev

#10542 Patch CVE-2024-43796 in python-tensorboard
  SPECS/python-tensorboard/CVE-2024-43796.patch
  SPECS/python-tensorboard/python-tensorboard.spec
Labels: security, Packaging, 3.0-dev

#10543 Patch CVE-2024-43796 in reaper
  SPECS/reaper/CVE-2024-43796.patch
  SPECS/reaper/reaper.spec
Labels: security, Packaging, main

#10545 openldap: enable slapd
  SPECS/openldap/openldap.spec
Labels: Packaging, 3.0-dev

#10538 Image Customizer: Fix 'TestCustomizeImagePartitionsSizeOnly' test.
  toolkit/tools/pkg/imagecustomizerlib/testdata/partitions-size-only-config.yaml
Labels: Tools

#10539 cmake: Update to 3.30.3 to fix CVE-2024-24806
  SPECS/cmake/cmake.signatures.json
  SPECS/cmake/cmake.spec
  cgmanifest.json
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#10522 apply patch to fix CVE-2024-6232 and CVE-2024-8088 for python3 2.0
  SPECS/python3/CVE-2024-6232.patch
  SPECS/python3/CVE-2024-8088.patch
  SPECS/python3/python3.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#10559 Patch CVE-2024-45590 in python-tensorboard
  SPECS/python-tensorboard/CVE-2024-45590.patch
  SPECS/python-tensorboard/python-tensorboard.spec
Labels: security, Packaging, 3.0-dev

#10562 Update README.md
  README.md
Labels: main

#10549 Image Customizer: Rename additionDirs fields.
  toolkit/tools/imagecustomizer/docs/configuration.md
  toolkit/tools/imagecustomizerapi/dirconfig.go
  toolkit/tools/imagecustomizerapi/dirconfig_test.go
  toolkit/tools/imagecustomizerapi/os_test.go
  toolkit/tools/pkg/imagecustomizerlib/customizefiles.go
  toolkit/tools/pkg/imagecustomizerlib/customizefiles_test.go
  toolkit/tools/pkg/imagecustomizerlib/testdata/adddirs-config.yaml
Labels: Tools

#10534 Image Customizer: Support filesystem-less partitions.
  toolkit/tools/imagecustomizerapi/config_test.go
  toolkit/tools/imagecustomizerapi/disk.go
  toolkit/tools/imagecustomizerapi/filesystemtype.go
  toolkit/tools/imagecustomizerapi/partition.go
  toolkit/tools/imagecustomizerapi/storage.go
  toolkit/tools/imagecustomizerapi/storage_test.go
  toolkit/tools/imagegen/diskutils/diskutils.go
  toolkit/tools/pkg/imagecustomizerlib/testdata/legacyboot-config.yaml
  toolkit/tools/pkg/imagecustomizerlib/testdata/verity-config.yaml
  toolkit/tools/pkg/imagecustomizerlib/typeConversion.go
Labels: Tools

#10567 Image Customizer: Rename 'isRootfsOverlay' to 'isInitrdOverlay'.
  toolkit/tools/imagecustomizer/docs/configuration.md
  toolkit/tools/imagecustomizerapi/overlay.go
  toolkit/tools/imagecustomizerapi/overlay_test.go
  toolkit/tools/pkg/imagecustomizerlib/customizeoverlays.go
  toolkit/tools/pkg/imagecustomizerlib/testdata/overlays-config.yaml
Labels: Tools

#10546 python-argcomplete: drop check dep BR fish to enable build
  SPECS-EXTENDED/python-argcomplete/python-argcomplete.spec
Labels: Packaging, specs-extended, 3.0-dev

#10570 python-ldap: upgrade 3.4.0 -> 3.4.4
  SPECS-EXTENDED/python-ldap/python-ldap.signatures.json
  SPECS-EXTENDED/python-ldap/python-ldap.spec
  cgmanifest.json
Labels: Packaging, ptest, specs-extended, 3.0-dev

#10572 389-ds-base: init at v3.1.0
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS-EXTENDED/389-ds-base/389-ds-base-devel.README
  SPECS-EXTENDED/389-ds-base/389-ds-base.signatures.json
  SPECS-EXTENDED/389-ds-base/389-ds-base.spec
  SPECS-EXTENDED/389-ds-base/389-ds-base.sysusers
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#10563 tensorflow: patch for CVE-2024-6232, CVE-2024-8088, CVE-2024-3651
  SPECS/tensorflow/CVE-2024-3651.patch
  SPECS/tensorflow/CVE-2024-6232.patch
  SPECS/tensorflow/CVE-2024-8088.patch
  SPECS/tensorflow/generate_tf_cache.sh
  SPECS/tensorflow/tensorflow.spec
Labels: security, Packaging, 3.0-dev

#10560 upgrade realmd version to 0.17.1
  SPECS-EXTENDED/realmd/0001-Find-NetBIOS-name-in-keytab-while-leaving.patch
  SPECS-EXTENDED/realmd/0001-Fix-issues-found-by-Coverity.patch
  SPECS-EXTENDED/realmd/0001-Fix-man-page-reference-in-systemd-service-file.patch
  SPECS-EXTENDED/realmd/0001-IPA-do-not-call-sssd-enable-logins.patch
  SPECS-EXTENDED/realmd/0001-Kerberos-fall-back-to-tcp-SRV-lookup.patch
  SPECS-EXTENDED/realmd/0001-LDAP-don-t-close-LDAP-socket-twice.patch
  SPECS-EXTENDED/realmd/0001-Remove-support-for-deprecated-gtester-format.patch
  SPECS-EXTENDED/realmd/0001-Set-NEWEST-flag-when-resolving-packages-with-Package.patch
  SPECS-EXTENDED/realmd/0001-Use-current-idmap-options-for-smb.conf.patch
  SPECS-EXTENDED/realmd/0001-ipa-Propagate-hostname-error.patch
  SPECS-EXTENDED/realmd/0001-service-Add-nss-and-pam-sssd.conf-services-after-joi.patch
  SPECS-EXTENDED/realmd/0001-service-Add-pam-and-nss-services-in-realm_sssd_confi.patch
  SPECS-EXTENDED/realmd/0001-service-allow-multiple-names-and-_srv_-ad_server-opt.patch
  SPECS-EXTENDED/realmd/0001-sssd-package-fix.patch
  SPECS-EXTENDED/realmd/0001-switch-to-authselect.patch
  SPECS-EXTENDED/realmd/0001-tests-ignore-order-in-test_update_domain.patch
  SPECS-EXTENDED/realmd/0001-tests-run-tests-with-python3.patch
  SPECS-EXTENDED/realmd/0001-tools-fix-ccache-handling-for-leave-operation.patch
  SPECS-EXTENDED/realmd/0002-Change-qualified-names-default-for-IPA.patch
  SPECS-EXTENDED/realmd/0002-service-fix-error-message-when-removing-host-from-AD.patch
  SPECS-EXTENDED/realmd/0003-discover-try-to-get-domain-name-from-hostname.patch
  SPECS-EXTENDED/realmd/0003-doc-fix-reference-in-realmd.conf-man-page.patch
  SPECS-EXTENDED/realmd/realmd.signatures.json
  SPECS-EXTENDED/realmd/realmd.spec
  cgmanifest.json
Labels: specs-extended, 3.0-dev

#10347 mock: upgrade and port from extended to core (including dependencies)
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS-EXTENDED/distribution-gpg-keys/distribution-gpg-keys.signatures.json
  SPECS-EXTENDED/libuser/libuser-0.63-PR49_add_yescrypt.patch
  SPECS-EXTENDED/libuser/libuser-0.63-downstream_test_xcrypt.patch
  SPECS-EXTENDED/libuser/libuser.signatures.json
  SPECS-EXTENDED/mock-core-configs/mock-core-configs.signatures.json
  SPECS-EXTENDED/mock/mock.signatures.json
  SPECS-EXTENDED/python-pyroute2/python-pyroute2.signatures.json
  SPECS-EXTENDED/python-templated-dictionary/python-templated-dictionary.signatures.json
  SPECS-EXTENDED/usermode/fsfaddr.patch
  SPECS-EXTENDED/usermode/selinux_deprecated.patch
  SPECS-EXTENDED/usermode/sysmacros.patch
  SPECS/distribution-gpg-keys/distribution-gpg-keys.signatures.json
  SPECS/distribution-gpg-keys/distribution-gpg-keys.spec
  SPECS/libuser/libuser.signatures.json
  SPECS/libuser/libuser.spec
  SPECS/mock-core-configs/mock-core-configs.signatures.json
  SPECS/mock-core-configs/mock-core-configs.spec
  SPECS/mock/mock.signatures.json
  SPECS/mock/mock.spec
  SPECS/python-backoff/python-backoff.signatures.json
  SPECS/python-backoff/python-backoff.spec
  SPECS/python-pyroute2/python-pyroute2.signatures.json
  SPECS/python-pyroute2/python-pyroute2.spec
  SPECS/python-rpmautospec-core/python-rpmautospec-core.signatures.json
  SPECS/python-rpmautospec-core/python-rpmautospec-core.spec
  SPECS/python-templated-dictionary/python-templated-dictionary.signatures.json
  SPECS/python-templated-dictionary/python-templated-dictionary.spec
  SPECS/usermode/config-util
  SPECS/usermode/usermode.signatures.json
  SPECS/usermode/usermode.spec
  cgmanifest.json
Labels: 3.0-dev

#10568 Add host metadata to logs (Host distro & version and versions of dependencies)
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
  toolkit/tools/pkg/imagecustomizerlib/versionsOfToolDependencies.go
Labels: Tools

#10526 add Azure marketplace ARM64 FIPS image definition
  toolkit/imageconfigs/marketplace-gen2-aarch64-fips.json
Labels: Schema, main

#10575 keda: upgrade to 2.14.1 to fix CVE-2024-35255
  SPECS/keda/keda.signatures.json
  SPECS/keda/keda.spec
  cgmanifest.json
Labels: security, 3.0-dev

#10576 cmake: Fix CVE-2024-6197, CVE-2024-6874, and CVE-2024-8096
  SPECS/cmake/CVE-2024-6197.patch
  SPECS/cmake/CVE-2024-6874.patch
  SPECS/cmake/CVE-2024-8096.patch
  SPECS/cmake/cmake.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#10585 Fixed spec entanglement PR check
  toolkit/scripts/check_entangled_specs.py
Labels: Tools
