Repository microsoft/azurelinux, pull requests merged in 2024-07, with the labels that each got.

#9535 3.0-dev - vitess address CVE-2017-14623
  SPECS/vitess/CVE-2017-14623.patch
  SPECS/vitess/vitess.spec
Labels: security, 3.0

#9513 Add minimum set of LCOW Configs
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel-uki.spec
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 3.0

#9509 Clear systemd state when creating an image
  toolkit/docs/formats/imageconfig.md
  toolkit/tools/imagegen/configuration/systemconfig.go
  toolkit/tools/imagegen/installutils/installutils.go
Labels: bug, Tools, 3.0

#9559 kata-containers-cc: enable and start tardev-snapshotter.service after installation
  SPECS/kata-containers-cc/kata-containers-cc.spec
Labels: 3.0

#9572 Fix encrypted root handling for new grub mkconfig flow
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/internal/resources/assets/efi/grub/grub.cfg
  toolkit/tools/internal/resources/assets/efi/grub/grubEncrypt.cfg
Labels: bug, 3.0

#9566 Bump golang version to 1.22.5-1
  SPECS/golang/golang.signatures.json
  SPECS/golang/golang.spec
  cgmanifest.json
Labels: security, 3.0-dev

#9571 Address Kernel CVE-2021-3847, CVE-2024-26913, CVE-2024-26933, CVE-2024-26978, CVE-2024-36477, CVE-2024-36481, CVE-2024-38664, CVE-2024-39291
  SPECS/kernel/CVE-2021-3847.nopatch
  SPECS/kernel/CVE-2024-26913.nopatch
  SPECS/kernel/CVE-2024-26933.nopatch
  SPECS/kernel/CVE-2024-26978.nopatch
  SPECS/kernel/CVE-2024-36477.nopatch
  SPECS/kernel/CVE-2024-36481.nopatch
  SPECS/kernel/CVE-2024-38664.nopatch
  SPECS/kernel/CVE-2024-39291.nopatch
Labels: security, main

#7893 Update shim-unsigned-x64 to 15.8
  SPECS/shim-unsigned-x64/Don-t-call-QueryVariableInfo-on-EFI-1.10-machines.patch
  SPECS/shim-unsigned-x64/Fix-a-broken-file-header-on-ia32.patch
  SPECS/shim-unsigned-x64/Fix-handling-of-ignore_db-and-user_insecure_mode.patch
  SPECS/shim-unsigned-x64/Relax-the-check-for-import_mok_state.patch
  SPECS/shim-unsigned-x64/cbl-mariner-ca-20211013.der
  SPECS/shim-unsigned-x64/db.x64.esl
  SPECS/shim-unsigned-x64/mok-allocate-MOK-config-table-as-BootServicesData.patch
  SPECS/shim-unsigned-x64/shim-another-attempt-to-fix-load-options-handling.patch
  SPECS/shim-unsigned-x64/shim-unsigned-x64.signatures.json
  SPECS/shim-unsigned-x64/shim-unsigned-x64.spec
  SPECS/shim/shim.signatures.json
  SPECS/shim/shim.spec
  cgmanifest.json
Labels: main

#9553 Fixed CVE-2022-3064 in `packer`
  SPECS/packer/CVE-2022-3064.patch
  SPECS/packer/CVE-2023-45288.patch
  SPECS/packer/CVE-2023-49569.patch
  SPECS/packer/packer.signatures.json
  SPECS/packer/packer.spec
  cgmanifest.json
Labels: 3.0-dev

#9621 [3.0] dcos-cli: patch CVE-2020-26160
  SPECS/dcos-cli/CVE-2020-26160.patch
  SPECS/dcos-cli/dcos-cli.spec
Labels: security, 3.0-dev

#9561 3.0-dev: update wayland-protocols to v1.36
  SPECS/wayland-protocols/wayland-protocols.signatures.json
  SPECS/wayland-protocols/wayland-protocols.spec
  cgmanifest.json
Labels: 3.0-dev

#9560 selinux-policy: Add udev and kmod fixes.
  SPECS/selinux-policy/0033-cloud-init-and-kmod-fixes.patch
  SPECS/selinux-policy/selinux-policy.spec
Labels: 3.0-dev

#9579 msft-golang: upgrade 1.22.4 -> 1.22.5 to address CVE-2024-24790 & CVE-2024-24791
  SPECS/msft-golang/msft-golang.signatures.json
  SPECS/msft-golang/msft-golang.spec
  cgmanifest.json
Labels: security, main

#9549 Fix python-gevent missing dependencies, broken tests, and CVE-2024-24806
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS/python-gevent/CVE-2024-24806.patch
  SPECS/python-gevent/python-gevent.spec
  SPECS/python-gevent/skip-irrelevant-tests.patch
  SPECS/python-zope-event/python-zope-event.signatures.json
  SPECS/python-zope-event/python-zope-event.spec
  cgmanifest.json
Labels: security, ptest, 3.0-dev

#9710 Patched CVE-2023-44487 in 'blobfuse2'.
  SPECS/blobfuse2/CVE-2023-44487.patch
  SPECS/blobfuse2/blobfuse2.spec
  SPECS/blobfuse2/generate_source_tarball.sh
Labels: security, 3.0-dev

#9539 Toolkit: Fix JSON parsing of util-linux commands.
  toolkit/tools/imagegen/diskutils/diskutils.go
  toolkit/tools/imagegen/diskutils/fstab.go
Labels: Tools, 3.0-dev

#9740 python-urllib3 Address CVE-2023-43804, CVE-2023-45803 & CVE-2024-37891.
  SPECS/python-urllib3/CVE-2024-37891.patch
  SPECS/python-urllib3/python-urllib3.signatures.json
  SPECS/python-urllib3/python-urllib3.spec
  cgmanifest.json
Labels: 3.0-dev

#9719 Patched CVE-2023-26253 in `glusterfs`. (CP: #9717)
  SPECS/glusterfs/CVE-2023-26253.patch
  SPECS/glusterfs/glusterfs.spec
Labels: main

#5100 Force initramfs ordering during image build
  toolkit/imageconfigs/packagelists/core-packages-image-aarch64.json
  toolkit/imageconfigs/packagelists/core-packages-image.json
  toolkit/imageconfigs/packagelists/fips-packages.json
  toolkit/tools/imagegen/installutils/installutils.go
Labels: Packaging, Tools, main

#9725 python-pygments: upgrade 2.5.2 -> 2.7.4 to address CVE-2021-20270 & CVE-2021-27291
  SPECS/python-pygments/python-pygments.signatures.json
  SPECS/python-pygments/python-pygments.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, 3.0-dev

#9738 Patch CVE-2022-3996 in bundled openssl in edk2
  SPECS/edk2/CVE-2022-3996.patch
  SPECS/edk2/edk2.spec
Labels: security, 3.0-dev

#9739 Update helm to 3.15.2 to fix CVE-2023-45288 & CVE-2023-44487
  SPECS/helm/CVE-2024-25620.patch
  SPECS/helm/CVE-2024-26147.patch
  SPECS/helm/generate_source_tarball.sh
  SPECS/helm/helm.signatures.json
  SPECS/helm/helm.spec
  cgmanifest.json
Labels: security, 3.0-dev

#9548 irqbalance: Tweak irqbalance environment file to squelch systemd warning
  SPECS/irqbalance/0001-define-IRQBALANCE_ARGS-as-empty-string.patch
  SPECS/irqbalance/irqbalance.spec
Labels: 3.0-dev

#9784 Update toolkit's gonum to v0.15.0
  .github/workflows/go-test-coverage.yml
  toolkit/docs/building/prerequisites-ubuntu.md
  toolkit/tools/go.mod
  toolkit/tools/go.sum
Labels: security, Tools, go, 3.0-dev

#9554 libmemcached-awesome: Upgrading version to 1.1.4 to address CVE-2023-27478
  SPECS/libmemcached-awesome/libmemcached-awesome.signatures.json
  SPECS/libmemcached-awesome/libmemcached-awesome.spec
  cgmanifest.json
Labels: fasttrack/2.0

#9609 cloud-hypervisor-cvm: update to 38.0.72.2
  SPECS/cloud-hypervisor-cvm/cloud-hypervisor-cvm.signatures.json
  SPECS/cloud-hypervisor-cvm/cloud-hypervisor-cvm.spec
  cgmanifest.json
Labels: security, fasttrack/2.0

#9737 libcontainers-common: address CVE-2022-2879, CVE-2023-45288, CVE-2024-1753, CVE-2024-3727 & CVE-2024-37298
  SPECS/libcontainers-common/CVE-2022-2879.patch
  SPECS/libcontainers-common/CVE-2023-45288.patch
  SPECS/libcontainers-common/CVE-2024-1753.patch
  SPECS/libcontainers-common/CVE-2024-3727.patch
  SPECS/libcontainers-common/CVE-2024-37298.patch
  SPECS/libcontainers-common/libcontainers-common.spec
Labels: security, 3.0-dev

#9544 ig: Bump to v0.30.0.
  SPECS/ig/ig.signatures.json
  SPECS/ig/ig.spec
  cgmanifest.json
Labels: 3.0-dev

#9443 hvloader: add patch for CVE-2023-0464
  SPECS-SIGNED/hvloader-signed/hvloader-signed.spec
  SPECS/hvloader/CVE-2023-0464.patch
  SPECS/hvloader/hvloader.spec
Labels: main

#9815 cups: upgrade version 2.3.3op2 -> 2.4.10 to address CVE-2023-34241
  SPECS/cups/cups-failover-backend.patch
  SPECS/cups/cups-lspp.patch
  SPECS/cups/cups-no-export-ssllibs.patch
  SPECS/cups/cups.signatures.json
  SPECS/cups/cups.spec
  cgmanifest.json
Labels: security, 3.0-dev

#9804 Upgrade httpd to 2.4.61 to fix CVE-2024-38473
  SPECS/httpd/httpd.signatures.json
  SPECS/httpd/httpd.spec
  cgmanifest.json
Labels: security, 3.0-dev

#9787 Bump tpm2-tools to 5.5.1 to address CVE-2024-29039 & CVE-2024-29038.
  SPECS/tpm2-tools/CVE-2021-3565.patch
  SPECS/tpm2-tools/tpm2-tools.signatures.json
  SPECS/tpm2-tools/tpm2-tools.spec
  cgmanifest.json
Labels: security, 3.0-dev

#9791 Patch telegraf for CVE-2024-37298 in vendored sources
  SPECS/telegraf/CVE-2024-37298.patch
  SPECS/telegraf/telegraf.spec
Labels: 3.0-dev

#9792 telegraf: Add patch for CVE-2024-37298
  SPECS/telegraf/CVE-2024-37298.patch
  SPECS/telegraf/telegraf.spec
Labels: fasttrack/2.0

#9813 Patch CVE-2024-5535 in openssl
  SPECS/openssl/CVE-2024-5535.patch
  SPECS/openssl/openssl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, 3.0-dev

#9816 cloud-hypervisor-cvm: update to 38.0.72.2 (#9609)
  SPECS/cloud-hypervisor-cvm/cloud-hypervisor-cvm.signatures.json
  SPECS/cloud-hypervisor-cvm/cloud-hypervisor-cvm.spec
  cgmanifest.json
Labels: 3.0-dev

#9789 Patch tpm2-tools for CVE-2024-29038 & CVE-2024-29039.
  SPECS/tpm2-tools/CVE-2021-3565.patch
  SPECS/tpm2-tools/CVE-2024-29038.patch
  SPECS/tpm2-tools/CVE-2024-29039.patch
  SPECS/tpm2-tools/tpm2-tools.spec
Labels: fasttrack/2.0

#9829 kata-containers-cc: Adapt tarfs make install trgt
  SPECS/kata-containers-cc/kata-containers-cc.spec
Labels: main

#9837 kata-cc: Fix make clean call in UVM build
  SPECS/kata-containers-cc/kata-containers-cc.signatures.json
  SPECS/kata-containers-cc/kata-containers-cc.spec
  SPECS/kata-containers-cc/mariner-coco-build-uvm.sh
  SPECS/kata-containers/kata-containers.signatures.json
  SPECS/kata-containers/kata-containers.spec
  SPECS/kata-containers/mariner-build-uvm.sh
Labels: main

#9831 Upgrade python3 to 3.12.3
  SPECS/python3/CVE-2023-6597.patch
  SPECS/python3/python3.signatures.json
  SPECS/python3/python3.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/toolchain-remote-wget-list
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
Labels: security, 3.0-dev

#9732 Updated `blobfuse2` to version 2.2.3.
  SPECS/blobfuse2/CVE-2023-44487.patch
  SPECS/blobfuse2/blobfuse2.signatures.json
  SPECS/blobfuse2/blobfuse2.spec
  cgmanifest.json
Labels: 3.0-dev

#9551 moby-engine: remove daemon.json with backported fix
  SPECS/moby-engine/daemon.json
  SPECS/moby-engine/enable-docker-proxy-libexec-search.patch
  SPECS/moby-engine/moby-engine.signatures.json
  SPECS/moby-engine/moby-engine.spec
Labels: bug, main, 2.0, stable-release-2.0

#9574 Reverted `packer` to version 1.9.5 and patched its CVEs.
  SPECS/packer/CVE-2022-3064.patch
  SPECS/packer/CVE-2023-49569.patch
  SPECS/packer/packer.signatures.json
  SPECS/packer/packer.spec
  cgmanifest.json
Labels: fasttrack/2.0

#9838 ceph: Fix high CVE-2024-38517 and CVE-2024-39684
  SPECS/ceph/CVE-2024-38517.patch
  SPECS/ceph/CVE-2024-39684.nopatch
  SPECS/ceph/ceph.spec
Labels: security, fasttrack/2.0

#9845 Fix Tensorflow Golden Container Smoke test
  SPECS/keras/0001-Add-Keras-3.3.3.patch
  SPECS/keras/keras.signatures.json
  SPECS/keras/keras.spec
  SPECS/python-optree/python-optree.spec
  cgmanifest.json
Labels: 3.0-dev

#9833 curl: upgrade version 8.5.0 -> 8.8.0 to address CVE-2024-2398
  SPECS/curl/curl.signatures.json
  SPECS/curl/curl.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, 3.0-dev

#9857 cloud-init change default binaries install location
  SPECS/cloud-init/Binaries-location.patch
  SPECS/cloud-init/cloud-init.spec
Labels: 3.0-dev

#9871 Removed unused argument in `preparerequest.go`.
  toolkit/tools/scheduler/schedulerutils/preparerequest.go
Labels: 3.0-dev

#9881 Image Customizer: Validate fields on FileConfig.
  toolkit/tools/imagecustomizerapi/fileconfig.go
  toolkit/tools/imagecustomizerapi/fileconfig_test.go
Labels: 3.0-dev

#9842 Patch moby-buildx CVES CVE-2021-43565 CVE-2022-28948 CVE-2022-41723
  SPECS/moby-buildx/CVE-2021-43565.patch
  SPECS/moby-buildx/CVE-2022-28948.patch
  SPECS/moby-buildx/CVE-2022-41723.patch
  SPECS/moby-buildx/moby-buildx.spec
Labels: security, main

#9870 [3.0-dev]rapidjson: fix high CVE-2024-38517 and CVE-2024-39684
  SPECS/rapidjson/CVE-2024-38517.patch
  SPECS/rapidjson/CVE-2024-39684.nopatch
  SPECS/rapidjson/rapidjson.spec
Labels: 3.0-dev

#9880 Image Customizer: Do not shrink verity hash partition.
  toolkit/tools/pkg/imagecustomizerlib/customizeverity.go
  toolkit/tools/pkg/imagecustomizerlib/customizeverity_test.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
  toolkit/tools/pkg/imagecustomizerlib/shrinkfilesystems.go
  toolkit/tools/pkg/imagecustomizerlib/testdata/verity-config.yaml
Labels: 3.0-dev

#8946 Add NVIDIA Container Build Script
  .pipelines/containerSourceData/Dockerfile-Nvidia-Initial
  .pipelines/containerSourceData/cuda/core.pkg
  .pipelines/containerSourceData/cuda/nvidia.pkg
  .pipelines/containerSourceData/scripts/BuildContainerCommonSteps.sh
  .pipelines/containerSourceData/scripts/BuildGoldenContainer.sh
  .pipelines/containerSourceData/scripts/BuildNvidiaDriverContainers.sh
Labels: 3.0-dev

#9882 libguestfs: restore removed tests
  SPECS/libguestfs/libguestfs.spec
Labels: ptest, 3.0-dev

#9884 3.0-dev: move xorg-x11-server and xorg-x11-drv-libinput to SPECS-EXTE…
  SPECS-EXTENDED/xorg-x11-drv-libinput/0001-Add-a-DPIScaleFactor-option-as-temporary-solution-to.patch
  SPECS-EXTENDED/xorg-x11-drv-libinput/71-libinput-overrides-wacom.conf
  SPECS-EXTENDED/xorg-x11-drv-libinput/xorg-x11-drv-libinput.signatures.json
  SPECS-EXTENDED/xorg-x11-drv-libinput/xorg-x11-drv-libinput.spec
  SPECS-EXTENDED/xorg-x11-server/0001-Fedora-hack-Make-the-suid-root-wrapper-always-start-.patch
  SPECS-EXTENDED/xorg-x11-server/0001-autobind-GPUs-to-the-screen.patch
  SPECS-EXTENDED/xorg-x11-server/0001-dix-Add-GetCurrentClient-helper.patch
  SPECS-EXTENDED/xorg-x11-server/0001-hw-Rename-boolean-config-value-field-from-bool-to-bo.patch
  SPECS-EXTENDED/xorg-x11-server/0001-render-Fix-build-with-gcc-12.patch
  SPECS-EXTENDED/xorg-x11-server/0001-xf86-dri2-Use-va_gl-as-vdpau_driver-for-Intel-i965-G.patch
  SPECS-EXTENDED/xorg-x11-server/0001-xfree86-use-modesetting-driver-by-default-on-GeForce.patch
  SPECS-EXTENDED/xorg-x11-server/0002-xwayland-Add-wp_viewport-wayland-extension-support.patch
  SPECS-EXTENDED/xorg-x11-server/0003-xwayland-Use-buffer_damage-instead-of-surface-damage.patch
  SPECS-EXTENDED/xorg-x11-server/0004-xwayland-Add-fake-output-modes-to-xrandr-output-mode.patch
  SPECS-EXTENDED/xorg-x11-server/0005-xwayland-Use-RandR-1.2-interface-rev-2.patch
  SPECS-EXTENDED/xorg-x11-server/0006-xwayland-Add-per-client-private-data.patch
  SPECS-EXTENDED/xorg-x11-server/0007-xwayland-Add-support-for-storing-per-client-per-outp.patch
  SPECS-EXTENDED/xorg-x11-server/0008-xwayland-Add-support-for-randr-resolution-change-emu.patch
  SPECS-EXTENDED/xorg-x11-server/0009-xwayland-Add-xwlRRModeToDisplayMode-helper-function.patch
  SPECS-EXTENDED/xorg-x11-server/0010-xwayland-Add-xwlVidModeGetCurrentRRMode-helper-to-th.patch
  SPECS-EXTENDED/xorg-x11-server/0011-xwayland-Add-vidmode-mode-changing-emulation-support.patch
  SPECS-EXTENDED/xorg-x11-server/0012-xwayland-xwl_window_should_enable_viewport-Add-extra.patch
  SPECS-EXTENDED/xorg-x11-server/0013-xwayland-Set-_XWAYLAND_RANDR_EMU_MONITOR_RECTS-prope.patch
  SPECS-EXTENDED/xorg-x11-server/0014-xwayland-Cache-client-id-for-the-window-manager-clie.patch
  SPECS-EXTENDED/xorg-x11-server/0015-xwayland-Reuse-viewport-instead-of-recreating.patch
  SPECS-EXTENDED/xorg-x11-server/0016-xwayland-Recurse-on-finding-the-none-wm-owner.patch
  SPECS-EXTENDED/xorg-x11-server/0017-xwayland-Make-window_get_none_wm_owner-return-a-Wind.patch
  SPECS-EXTENDED/xorg-x11-server/0018-xwayland-Check-emulation-on-client-toplevel-resize.patch
  SPECS-EXTENDED/xorg-x11-server/0019-xwayland-Also-check-resolution-change-emulation-when.patch
  SPECS-EXTENDED/xorg-x11-server/0020-xwayland-Also-hook-screen-s-MoveWindow-method.patch
  SPECS-EXTENDED/xorg-x11-server/0021-xwayland-Fix-emulated-modes-not-being-removed-when-s.patch
  SPECS-EXTENDED/xorg-x11-server/0022-xwayland-Call-xwl_window_check_resolution_change_emu.patch
  SPECS-EXTENDED/xorg-x11-server/0023-xwayland-Fix-setting-of-_XWAYLAND_RANDR_EMU_MONITOR_.patch
  SPECS-EXTENDED/xorg-x11-server/0024-xwayland-Remove-unnecessary-xwl_window_is_toplevel-c.patch
  SPECS-EXTENDED/xorg-x11-server/0025-xwayland-Make-window_get_client_toplevel-non-recursi.patch
  SPECS-EXTENDED/xorg-x11-server/06_use-intel-only-on-pre-gen4.diff
  SPECS-EXTENDED/xorg-x11-server/10-quirks.conf
  SPECS-EXTENDED/xorg-x11-server/CVE-2023-1594.patch
  SPECS-EXTENDED/xorg-x11-server/driver-abi-rebuild.sh
  SPECS-EXTENDED/xorg-x11-server/gitignore
  SPECS-EXTENDED/xorg-x11-server/xorg-x11-server.signatures.json
  SPECS-EXTENDED/xorg-x11-server/xorg-x11-server.spec
  SPECS-EXTENDED/xorg-x11-server/xserver-sdk-abi-requires.git
  SPECS-EXTENDED/xorg-x11-server/xserver-sdk-abi-requires.release
  SPECS-EXTENDED/xorg-x11-server/xserver.pamd
  SPECS-EXTENDED/xorg-x11-server/xvfb-run.sh
  SPECS/python-mpmath/python-mpmath.spec
  SPECS/sympy/sympy.spec
Labels: specs-extended, 3.0-dev

#9865 rapidjson: fix CVE-2024-38517 and CVE-2024-39684
  SPECS/rapidjson/CVE-2024-38517.patch
  SPECS/rapidjson/CVE-2024-39684.nopatch
  SPECS/rapidjson/rapidjson.spec
Labels: security, fasttrack/2.0

#9877 golang: drop golang-1.17
  SPECS-EXTENDED/nmi/nmi.spec
  SPECS-EXTENDED/umoci/umoci.spec
  SPECS/KeysInUse-OpenSSL/KeysInUse-OpenSSL.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/application-gateway-kubernetes-ingress/application-gateway-kubernetes-ingress.spec
  SPECS/azcopy/azcopy.spec
  SPECS/blobfuse2/blobfuse2.spec
  SPECS/cf-cli/cf-cli.spec
  SPECS/cni-plugins/cni-plugins.spec
  SPECS/coredns/coredns.spec
  SPECS/dcos-cli/dcos-cli.spec
  SPECS/etcd/etcd.spec
  SPECS/flannel/flannel.spec
  SPECS/gh/gh.spec
  SPECS/golang/golang-1.17.signatures.json
  SPECS/golang/golang-1.17.spec
  SPECS/influx-cli/influx-cli.spec
  SPECS/jx/jx.spec
  SPECS/keda/keda.spec
  SPECS/moby-buildx/moby-buildx.spec
  SPECS/moby-containerd-cc/moby-containerd-cc.spec
  SPECS/moby-engine/moby-engine.spec
  SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec
  SPECS/packer/packer.spec
  SPECS/skopeo/skopeo.spec
  cgmanifest.json
Labels: security, main

#9890 fix intermittent openssl FIPS selftest failures in jitterentropy
  SPECS/openssl/openssl-1.1.1-jitterentropy-fix-intermittent-fips-selftest-failure.patch
  SPECS/openssl/openssl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#9875 3.0-dev: add xorg-x11-server-Xwayland v24.1.1
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS/xorg-x11-server-Xwayland/xorg-x11-server-Xwayland.signatures.json
  SPECS/xorg-x11-server-Xwayland/xorg-x11-server-Xwayland.spec
  cgmanifest.json
Labels: 3.0-dev

#9439 Onboard NVIDIA Driver Container to PublishContainer script
  .pipelines/containerSourceData/scripts/PublishContainers.sh
Labels: 3.0-dev

#9923 Upgrade kernel-mos version to 5.15.161.1
  SPECS-SIGNED/kernel-mos-signed/kernel-mos-signed.spec
  SPECS/kernel-mos/config
  SPECS/kernel-mos/kernel-mos.signatures.json
  SPECS/kernel-mos/kernel-mos.spec
  cgmanifest.json
Labels: main

#9925 Upgrade httpd to 2.4.62 to address CVE-2024-40725
  SPECS/httpd/httpd.signatures.json
  SPECS/httpd/httpd.spec
  cgmanifest.json
Labels: fasttrack/2.0

#6698 Filter out debuginfo packages when running sodiff
  .pipelines/templatesWithCheckout/SodiffCheck.yml
  toolkit/scripts/analysis.mk
  toolkit/scripts/sodiff/mariner-sodiff.sh
Labels: main

#9916 Add patch for CVE-2024-6655
  SPECS/gtk2/CVE-2024-6655.patch
  SPECS/gtk2/gtk2.spec
  SPECS/gtk3/CVE-2024-6655.patch
  SPECS/gtk3/gtk3.spec
Labels: security, 3.0-dev

#9883 Use structs to pass data to scheduler prints
  toolkit/tools/scheduler/schedulerutils/printresults.go
Labels: Tools, 3.0-dev

#9899 Add automatic mode for DAILY_BUILD_ID pass 2
  toolkit/Makefile
  toolkit/docs/building/building.md
  toolkit/resources/manifests/package/daily_build_repo.repo.template
  toolkit/scripts/chroot.mk
  toolkit/scripts/daily_build.mk
  toolkit/scripts/get_lkg_id.sh
  toolkit/scripts/manifests.mk
  toolkit/scripts/pkggen.mk
  toolkit/scripts/preview.mk
  toolkit/scripts/toolchain.mk
  toolkit/scripts/update_manifest.sh
Labels: Tools, DevEx, 3.0-dev

#9918 bind: upgrade 9.19.21 -> 9.20.0 to address CVE-CVE-2024-0760, CVE-2024-1737, CVE-2024-1975 & CVE-2024-4076
  SPECS/bind/bind.signatures.json
  SPECS/bind/bind.spec
  SPECS/bind/nongit-fix.patch
  cgmanifest.json
Labels: security, 3.0-dev

#9832 curl: upgrade 8.5.0 -> 8.8.0 to address CVE-2024-2398
  SPECS/curl/curl.signatures.json
  SPECS/curl/curl.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, main

#9904 Fix CVE-2024-6345 in python3
  SPECS/python3/CVE-2024-6345.patch
  SPECS/python3/python3.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, main

#9859 Fix CVE-2024-6104 in skopeo
  SPECS/skopeo/CVE-2024-6104.patch
  SPECS/skopeo/skopeo.spec
Labels: security, main

#9937 compiler-rt: fix path issue
  SPECS/compiler-rt/compiler-rt.spec
  cgmanifest.json
Labels: 3.0-dev

#9612 Address kernel CVE-2024-36288, CVE-2024-38662, CVE-2024-38780, CVE-2024-39277, CVE-2024-39292
  SPECS/kernel/CVE-2024-36288.nopatch
  SPECS/kernel/CVE-2024-38662.nopatch
  SPECS/kernel/CVE-2024-38780.nopatch
  SPECS/kernel/CVE-2024-39277.nopatch
  SPECS/kernel/CVE-2024-39292.nopatch
Labels: security, main

#9912 Python3 patch CVE-2024-0397
  SPECS/python3/CVE-2024-0397.patch
  SPECS/python3/python3.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, fasttrack/2.0

#9917 libcontainers-common: introduce patch to address CVE-2024-37298
  SPECS/libcontainers-common/CVE-2024-37298.patch
  SPECS/libcontainers-common/libcontainers-common.spec
Labels: security, fasttrack/2.0

#9927 Add Patch in terraform for CVE-2024-6257.
  SPECS/terraform/CVE-2024-6257.patch
  SPECS/terraform/terraform.spec
Labels: fasttrack/2.0

#9962 Make check-circular-deps.yml faster with -j, use lkg
  .github/workflows/check-circular-deps.yml
Labels: Tools, 3.0-dev

#9885 Integrate new license checker package into image and package builds.
  toolkit/scripts/imggen.mk
  toolkit/scripts/pkggen.mk
  toolkit/tools/scheduler/scheduler.go
  toolkit/tools/scheduler/schedulerutils/buildworker.go
  toolkit/tools/scheduler/schedulerutils/graphbuildstate.go
  toolkit/tools/scheduler/schedulerutils/pkglicensechecker.go
  toolkit/tools/scheduler/schedulerutils/printresults.go
Labels: 3.0-dev

#9869 Enable CONFIG_RT_GROUP_SCHED in kernel-rt
  SPECS-EXTENDED/kernel-rt/config
  SPECS-EXTENDED/kernel-rt/kernel-rt.signatures.json
  SPECS-EXTENDED/kernel-rt/kernel-rt.spec
Labels: 3.0-dev

#9951 fix CVE-2024-41110 in moby-engine
  SPECS/moby-engine/CVE-2024-41110.patch
  SPECS/moby-engine/moby-engine.spec
Labels: security, fasttrack/2.0

#9915 Patch for gtk2 and gtk3 CVE-2024-6655
  SPECS/gtk2/CVE-2024-6655.patch
  SPECS/gtk2/gtk2.spec
  SPECS/gtk3/CVE-2024-6655.patch
  SPECS/gtk3/gtk3.spec
Labels: security, fasttrack/2.0

#9949 cf-cli: address CVE-2023-39325
  SPECS/cf-cli/CVE-2023-39325.patch
  SPECS/cf-cli/cf-cli.spec
Labels: security, 3.0-dev

#9959 terraform: Patch CVE-2024-6104 for bundled hashicorp/go-retryablehttp.
  SPECS/terraform/CVE-2024-6104.patch
  SPECS/terraform/terraform.spec
Labels: main

#9958 Upgrade default golang to 1.22.5 and backport the fix for 1.18
  SPECS/golang/CVE-2024-24790.patch
  SPECS/golang/golang-1.18.spec
  SPECS/golang/golang.signatures.json
  SPECS/golang/golang.spec
  cgmanifest.json
Labels: security, fasttrack/2.0

#9894 gh: patch CVE-2021-43565
  SPECS/gh/CVE-2021-43565.patch
  SPECS/gh/gh.spec
Labels: security, fasttrack/2.0

#9926 Upgrade httpd to 2.4.62 to address CVE-2024-40725
  SPECS/httpd/httpd.signatures.json
  SPECS/httpd/httpd.spec
  cgmanifest.json
Labels: security, 3.0-dev

#9970 Python3 patch CVE-2024-0397
  SPECS/python3/CVE-2024-0397.patch
  SPECS/python3/python3.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, main

#9888 libcontainers-common: patch CVE-2021-43565
  SPECS/libcontainers-common/CVE-2021-43565.patch
  SPECS/libcontainers-common/libcontainers-common.spec
Labels: security, fasttrack/2.0

#8335 Patch waagent.conf to add firewall rules
  SPECS/WALinuxAgent/WALinuxAgent.spec
  SPECS/WALinuxAgent/add_firewall_rules.patch
Labels: main

#9910 coreutils: introduce patch to address CVE-2024-0684
  SPECS/coreutils/CVE-2024-0684.patch
  SPECS/coreutils/coreutils.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, 3.0-dev

#9960 toolkit/pkgbld.sh: add a helper script to build packages locally
  toolkit/pkgbld.sh
Labels: DevEx, RFC, 3.0-dev
