Repository microsoft/azurelinux, pull requests merged in 2024-04, with the labels that each got.

#8636 kernel-mshv: buildrequire grub2-rpm-macros to fix macro expansion
  SPECS-SIGNED/kernel-mshv-signed/kernel-mshv-signed.spec
  SPECS/kernel-mshv/kernel-mshv.spec
Labels: main

#8501 iptables, flush and restore raw table
  SPECS/iptables/iptables
  SPECS/iptables/iptables.signatures.json
  SPECS/iptables/iptables.spec
  SPECS/iptables/iptables.stop
Labels: 3.0

#8631 cmake: fix package test
  SPECS/cmake/cmake.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: ptest, 3.0

#8632 softhsm: fix tests
  SPECS/softhsm/softhsm-openssl3-tests.patch
  SPECS/softhsm/softhsm.spec
Labels: ptest, 3.0

#8659 Remove csi-driver-lvm
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS/csi-driver-lvm/csi-driver-lvm.signatures.json
  SPECS/csi-driver-lvm/csi-driver-lvm.spec
  cgmanifest.json
Labels: 3.0

#8678 Upgrade emacs to 29.3 to fix CVE-2024-30202, CVE-2024-30204, CVE-2024-30205
  SPECS/emacs/CVE-2007-6109.nopatch
  SPECS/emacs/CVE-2022-45939.patch
  SPECS/emacs/CVE-2022-48337.patch
  SPECS/emacs/CVE-2022-48338.patch
  SPECS/emacs/CVE-2022-48339.patch
  SPECS/emacs/CVE-2023-27986.patch
  SPECS/emacs/CVE-2023-28617.patch
  SPECS/emacs/emacs.signatures.json
  SPECS/emacs/emacs.spec
  cgmanifest.json
Labels: main

#8680 Fixing toolchain rebuilds for delta builds.
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
Labels: main

#8687 Fix the date in logs
  SPECS/emacs/emacs.spec
Labels: main

#8665 Cherry-pick delta for Overlay Dracut Module from 3.0-dev to main.
  SPECS/dracut/20overlayfs/overlayfs-mount.sh
  SPECS/dracut/dracut.signatures.json
  SPECS/dracut/dracut.spec
Labels: main

#8656 rust: enable profiler support
  SPECS/rust/rust.spec
Labels: 3.0

#8658 Fix ephemeral-disk-warning.service not running in mariner 3.0
  SPECS/WALinuxAgent/WALinuxAgent.signatures.json
  SPECS/WALinuxAgent/WALinuxAgent.spec
  SPECS/WALinuxAgent/ephemeral-disk-warning.service
Labels: 3.0

#8625 Dropping Rook package in 3.0-dev
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS/rook/README
  SPECS/rook/flexvolume-dir.patch
  SPECS/rook/rook.signatures.json
  SPECS/rook/rook.spec
  SPECS/rook/update-tarball.sh
  cgmanifest.json
Labels: 3.0

#8672 Add runtime filter to depsearch
  toolkit/tools/depsearch/depsearch.go
Labels: Tools, go, DevEx, 3.0

#8565 [3.0] Upgrade python-tqdm to v4.66.2
  SPECS/python-tqdm/python-tqdm.signatures.json
  SPECS/python-tqdm/python-tqdm.spec
  cgmanifest.json
Labels: 3.0

#8695 llvm: upgrade to 18.1.2
  SPECS/clang/clang.signatures.json
  SPECS/clang/clang.spec
  SPECS/compiler-rt/compiler-rt.signatures.json
  SPECS/compiler-rt/compiler-rt.spec
  SPECS/lld/lld.signatures.json
  SPECS/lld/lld.spec
  SPECS/lldb/lldb.signatures.json
  SPECS/lldb/lldb.spec
  SPECS/llvm/llvm.signatures.json
  SPECS/llvm/llvm.spec
  cgmanifest.json
Labels: 3.0

#8654 opentofu: add new package opentofu v1.6.2
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS/opentofu/generate_source_tarball.sh
  SPECS/opentofu/opentofu.signatures.json
  SPECS/opentofu/opentofu.spec
  cgmanifest.json
Labels: 3.0

#8671 Removed duplicate signatures PR check.
  .github/workflows/check-signatures.yml
  toolkit/scripts/check_signatures.py
Labels: 3.0

#8661 Remove Kernel Required Configs Check
  .github/workflows/check-kernel-config.yml
  toolkit/scripts/check_new_kernel_configs.py
  toolkit/scripts/check_required_kernel_configs.py
  toolkit/scripts/kernel_sources_analysis.py
  toolkit/scripts/mariner-required-configs.json
Labels: main

#8710 lujavrite: introduce for 3.0
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS/lujavrite/lujavrite.signatures.json
  SPECS/lujavrite/lujavrite.spec
  cgmanifest.json
Labels: 3.0

#8667 Update pytorch to 2.2.2
  SPECS/pytorch/pytorch.signatures.json
  SPECS/pytorch/pytorch.spec
  cgmanifest.json
Labels: 3.0

#8368 Auto clean tdnf cache
  toolkit/docs/formats/imageconfig.md
  toolkit/imageconfigs/core-efi.json
  toolkit/imageconfigs/core-legacy.json
  toolkit/imageconfigs/marketplace-gen1-fips.json
  toolkit/imageconfigs/marketplace-gen1.json
  toolkit/imageconfigs/marketplace-gen2-aarch64.json
  toolkit/imageconfigs/marketplace-gen2-fips.json
  toolkit/imageconfigs/marketplace-gen2.json
  toolkit/imageconfigs/postinstallscripts/core-container/cleanup.sh
  toolkit/imageconfigs/postinstallscripts/remove-tdnf-cache.sh
  toolkit/tools/imagegen/configuration/systemconfig.go
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/internal/file/file.go
  toolkit/tools/internal/file/file_test.go
Labels: enhancement, Tools, go, 3.0

#8714 Bump conmon version to 2.1.2 for CVE-2022-1708
  SPECS/conmon/conmon.signatures.json
  SPECS/conmon/conmon.spec
  cgmanifest.json
Labels: security, main

#8713 Revert "[3.0] dhcp/dhclient.conf: add option rfc3442-classless-static…
  SPECS/dhcp/dhcp.spec
Labels: 3.0

#8633 Enable qemu migration tests
  SPECS/qemu/0002-Disable-failing-tests-on-azl.patch
  SPECS/qemu/0002-disable-migration-tests.patch
  SPECS/qemu/qemu.spec
Labels: 3.0

#8737 moby-containerd-cc: remove obsolete build dependency
  SPECS/moby-containerd-cc/moby-containerd-cc.spec
Labels: main, 2.0

#8685 Demote java-xz to specs-extended
  SPECS-EXTENDED/xz-java/xz-java-source-version.patch
  SPECS-EXTENDED/xz-java/xz-java.signatures.json
  SPECS-EXTENDED/xz-java/xz-java.spec
Labels: 3.0

#8675 Drop bazel-workspaces
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS/bazel-workspaces/bazel-workspaces.signatures.json
  SPECS/bazel-workspaces/bazel-workspaces.spec
Labels: 3.0

#8676 kernel-uvm: sync to 6.1.0.mshv16
  SPECS/kernel-uvm/config
  SPECS/kernel-uvm/kernel-uvm.signatures.json
  SPECS/kernel-uvm/kernel-uvm.spec
  cgmanifest.json
Labels: 3.0

#8640 kata-containers: sync to 3.2.0.azl0
  SPECS/kata-containers/0001-Append-systemd-kernel-cmdline-params-for-initrd.patch
  SPECS/kata-containers/0001-Merged-PR-9607-Allow-10-seconds-for-VM-creation-star.patch
  SPECS/kata-containers/0001-osbuilder-Add-support-for-CBL-Mariner.patch
  SPECS/kata-containers/0002-Merged-PR-9671-Wait-for-a-possibly-slow-Guest.patch
  SPECS/kata-containers/0003-Merged-PR-9805-Add-support-for-MSHV.patch
  SPECS/kata-containers/0004-Merged-PR-9806-Fix-enable_debug-for-hypervisor.clh.patch
  SPECS/kata-containers/0005-Merged-PR-9956-shim-avoid-memory-hotplug-timeout.patch
  SPECS/kata-containers/drop-mut-for-variables-that-are-not-mutated.patch
  SPECS/kata-containers/kata-containers.signatures.json
  SPECS/kata-containers/kata-containers.spec
  SPECS/kata-containers/runtime-reduce-uvm-high-mem-footprint.patch
  cgmanifest.json
Labels: 3.0

#8649 moby-containerd-cc: sync to v1.7.7
  SPECS/moby-containerd-cc/CVE-2023-44487.patch
  SPECS/moby-containerd-cc/CVE-2023-47108.patch
  SPECS/moby-containerd-cc/fix_cc_tests_for_golang1.21.patch
  SPECS/moby-containerd-cc/moby-containerd-cc.signatures.json
  SPECS/moby-containerd-cc/moby-containerd-cc.spec
  cgmanifest.json
Labels: 3.0

#8690 kata-containers-cc: sync to 3.2.0.azl0
  SPECS/kata-containers-cc/0001-tardev-snapshotter-enable-feature-impl_trait_in_asso.patch
  SPECS/kata-containers-cc/drop-mut-for-variables-that-are-not-mutated.patch
  SPECS/kata-containers-cc/kata-containers-cc.signatures.json
  SPECS/kata-containers-cc/kata-containers-cc.spec
  SPECS/kata-containers-cc/mariner-coco-build-uvm.sh
  cgmanifest.json
Labels: 3.0

#8683 kernel-mshv: sync to 5.15.126.mshv9
  SPECS/kernel-mshv/fix_python_3.12_build_errors.patch
  SPECS/kernel-mshv/kernel-mshv.signatures.json
  SPECS/kernel-mshv/kernel-mshv.spec
  SPECS/kernel-mshv/perf_bpf_test_add_nonnull_argument.patch
  cgmanifest.json
Labels: 3.0

#8691 kata-packages-uvm: sync to v1.0.0-2
  .github/workflows/validate-cg-manifest.sh
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS/kata-packages-uvm/kata-packages-uvm.spec
Labels: 3.0

#8571 Remove nodejs as it's End of Life
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/nodejs/CVE-2022-25883.patch
  SPECS/nodejs/CVE-2023-35945.patch
  SPECS/nodejs/nodejs.signatures.json
  SPECS/nodejs/nodejs.spec
  SPECS/nodejs/nodejs18.spec
  cgmanifest.json
Labels: main

#8511 Upgrade libnbd to 1.18.3 stable
  SPECS/libnbd/CVE-2023-5215.patch
  SPECS/libnbd/libnbd.signatures.json
  SPECS/libnbd/libnbd.spec
  cgmanifest.json
Labels: 3.0

#8749 Update packer to 1.10.1 to address CVE-2023-49569
  SPECS/packer/CVE-2023-44487.patch
  SPECS/packer/packer.signatures.json
  SPECS/packer/packer.spec
  cgmanifest.json
Labels: fasttrack/2.0

#8663 add image-id file in etc dir
  toolkit/scripts/imggen.mk
  toolkit/tools/go.mod
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/imagegen/installutils/installutils_test.go
  toolkit/tools/imager/imager.go
Labels: main

#8760 Add patch to nodejs to fix CVE-2024-27983
  SPECS/nodejs/CVE-2024-27983.patch
  SPECS/nodejs/nodejs18.spec
Labels: main

#8589 [kata-cc] kernel-uvm: enable CIFS modules
  SPECS/kernel-uvm/config
  SPECS/kernel-uvm/kernel-uvm.signatures.json
  SPECS/kernel-uvm/kernel-uvm.spec
Labels: main

#8762 [kata-cc] kata-packages-uvm: add cifs-utils as dependency
  SPECS/kata-packages-uvm/kata-packages-uvm.spec
Labels: main

#8653 Demote openjade, docbook-style-dsssl to SPECS-EXTENDED
  SPECS-EXTENDED/docbook-style-dsssl/LICENSE.PTR
  SPECS-EXTENDED/docbook-style-dsssl/docbook-style-dsssl.Makefile
  SPECS-EXTENDED/docbook-style-dsssl/docbook-style-dsssl.signatures.json
  SPECS-EXTENDED/docbook-style-dsssl/docbook-style-dsssl.spec
  SPECS-EXTENDED/openjade/config.guess
  SPECS-EXTENDED/openjade/config.sub
  SPECS-EXTENDED/openjade/openjade-1.3.1-nsl.patch
  SPECS-EXTENDED/openjade/openjade-1.3.2-gcc46.patch
  SPECS-EXTENDED/openjade/openjade-deplibs.patch
  SPECS-EXTENDED/openjade/openjade-getoptperl.patch
  SPECS-EXTENDED/openjade/openjade-nola.patch
  SPECS-EXTENDED/openjade/openjade-ppc64.patch
  SPECS-EXTENDED/openjade/openjade.signatures.json
  SPECS-EXTENDED/openjade/openjade.spec
  SPECS/freetds/freetds.spec
Labels: 3.0

#8773 base container builder image
  .pipelines/containerSourceData/scripts/BuildBaseContainers.sh
  toolkit/imageconfigs/core-container-builder.json
  toolkit/imageconfigs/packagelists/core-container-builder-packages.json
Labels: main

#8783 Fixed setting of the `ToolkitVersion` variable for our Go tools.
  toolkit/scripts/tools.mk
  toolkit/tools/internal/exe/exe_test.go
Labels: main

#8784 ruby: patch CVE-2024-27280 and CVE-2024-27281
  SPECS/ruby/CVE-2024-27280.patch
  SPECS/ruby/CVE-2024-27281.patch
  SPECS/ruby/ruby.spec
Labels: main

#8787 [main] increase timeout for "Check Package CGManifests" github check
  .github/workflows/validate-cg-manifest.sh
Labels: main

#7610 libgudev: Upgrade to version 238
  SPECS/libgudev/libgudev.signatures.json
  SPECS/libgudev/libgudev.spec
  cgmanifest.json
Labels: 3.0

#8794 msft-golang: upgrade 1.21.8 -> 1.22.2
  SPECS/msft-golang/msft-golang.signatures.json
  SPECS/msft-golang/msft-golang.spec
  cgmanifest.json
Labels: fasttrack/2.0

#8339 Drop multilib-rpm-config
  .github/workflows/validate-cg-manifest.sh
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS/mariadb-connector-c/mariadb-connector-c.spec
  SPECS/multilib-rpm-config/COPYING
  SPECS/multilib-rpm-config/README
  SPECS/multilib-rpm-config/macros.ml
  SPECS/multilib-rpm-config/multilib-fix
  SPECS/multilib-rpm-config/multilib-info
  SPECS/multilib-rpm-config/multilib-library
  SPECS/multilib-rpm-config/multilib-rpm-config.signatures.json
  SPECS/multilib-rpm-config/multilib-rpm-config.spec
  SPECS/openblas/openblas.spec
Labels: 3.0

#8804 msft-golang: upgrade 1.21.8 -> 1.22.2 (CP: #8794)
  SPECS/msft-golang/msft-golang.signatures.json
  SPECS/msft-golang/msft-golang.spec
  cgmanifest.json
Labels: main

#8378 ig: fix %check.
  SPECS/ig/ig.spec
Labels: 3.0

#8792 Fixing cascading rebuilds. (CP: #8777)
  toolkit/tools/scheduler/schedulerutils/buildworker.go
  toolkit/tools/scheduler/schedulerutils/preparerequest.go
Labels: main

#8793 Fixing cascading rebuilds. (CP: #8777)
  toolkit/tools/scheduler/schedulerutils/buildworker.go
  toolkit/tools/scheduler/schedulerutils/preparerequest.go
Labels: 3.0

#8735 Add "cbl-mariner-multi-package-reviewers" when a multi-package .spec file is added or removed
  .github/pull_request_template.md
  .pipelines/multi-package/MultiPackage.yml
Labels: main

#8362 Enable CONFIG_NFT_OBJREF
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#8796 Add trace-cmd
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS/libtracecmd/libtracecmd.signatures.json
  SPECS/libtracecmd/libtracecmd.spec
  SPECS/libtracefs/libtracefs.signatures.json
  SPECS/libtracefs/libtracefs.spec
  SPECS/trace-cmd/98-trace-cmd.rules
  SPECS/trace-cmd/trace-cmd.conf
  SPECS/trace-cmd/trace-cmd.service
  SPECS/trace-cmd/trace-cmd.signatures.json
  SPECS/trace-cmd/trace-cmd.spec
  cgmanifest.json
Labels: 3.0

#8811 upgrade libaec to 1.1.3
  SPECS/libaec/libaec.signatures.json
  SPECS/libaec/libaec.spec
  cgmanifest.json
Labels: 3.0

#8694 Downgrade cloud-init to 23.3 via epoch
  SPECS/cloud-init/cloud-init.signatures.json
  SPECS/cloud-init/cloud-init.spec
  SPECS/cloud-init/overrideDatasourceDetection.patch
  cgmanifest.json
Labels: main

#8813 fix: add repoutils.FindCreateRepoCommand to flexibly use either creat…
  toolkit/tools/internal/packagerepo/repomanager/rpmrepomanager/rpmrepomanager.go
  toolkit/tools/internal/packagerepo/repoutils/repoutils.go
Labels: 3.0

#8824 clamav: fix build break
  SPECS/clamav/clamav.spec
Labels: 3.0

#8823 pcsc-lite: fix build break
  SPECS/pcsc-lite/pcsc-lite.spec
Labels: 3.0

#8825 libreswan: fix build break
  SPECS/libreswan/capng_apply.patch
  SPECS/libreswan/libreswan.spec
Labels: 3.0

#8827 collectd: fix build break
  SPECS/collectd/collectd.spec
  SPECS/collectd/fix_missing_longintrepr_header.patch
Labels: 3.0

#8833 fix rubygem-fluentd and rubygem-addressable requirements
  SPECS/rubygem-addressable/rubygem-addressable.spec
  SPECS/rubygem-fluentd/rubygem-fluentd.spec
Labels: 3.0

#8830 fix extended build breaks in main: libotr, gupnp, samba
  SPECS-EXTENDED/gupnp/gupnp.spec
  SPECS-EXTENDED/libotr/libotr-4.1.1-socket-h.patch
  SPECS-EXTENDED/libotr/libotr.spec
  SPECS-EXTENDED/samba/samba.spec
Labels: main

#8789 attach eol manifest using oras
  .pipelines/containerSourceData/scripts/PublishContainers.sh
Labels: main

#8843 git-lfs: upgrade to 3.4.1 to fix multiple CVEs
  SPECS/git-lfs/CVE-2021-44716.patch
  SPECS/git-lfs/CVE-2023-44487.patch
  SPECS/git-lfs/git-lfs.signatures.json
  SPECS/git-lfs/git-lfs.spec
  cgmanifest.json
Labels: security, fasttrack/2.0

#8831 ck: add package v7.2
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS/ck/ck-nogettid.patch
  SPECS/ck/ck-register-constraint.patch
  SPECS/ck/ck-unit-sequence.patch
  SPECS/ck/ck-unit-time.patch
  SPECS/ck/ck.signatures.json
  SPECS/ck/ck.spec
  SPECS/ck/ck_disable_ck_hclh_test.patch
  cgmanifest.json
Labels: 3.0

#8839 openssl: Fix unconstrained session cache growth in TLSv1.3
  SPECS/openssl/openssl-1.1.1-Fix-unconstrained-session-cache-growth-in-TLSv1.3.patch
  SPECS/openssl/openssl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#8837 upgrade bpftrace to 0.20.3 and add patch for llvm18 support
  SPECS/bpftrace/bpftrace-0.20-llvm18.patch
  SPECS/bpftrace/bpftrace.signatures.json
  SPECS/bpftrace/bpftrace.spec
  cgmanifest.json
Labels: 3.0

#8780 fix trigger issue for Azl3 CodeQL
  .pipelines/CodeQL/CodeQL.yml
Labels: 3.0

#8044 cal10n: upgrade to 0.8.1
  SPECS/cal10n/cal10n-0.7.7-sourcetarget.patch
  SPECS/cal10n/cal10n.signatures.json
  SPECS/cal10n/cal10n.spec
  cgmanifest.json
Labels: 3.0

#8741 Add configurability in systemd to control default value of UseDomains parameter
  SPECS/systemd/networkd-default-use-domains.patch
  SPECS/systemd/systemd.spec
Labels: main

#8857 Update sos to copy kernel config and vmcore
  SPECS/sos/copy-kernel-config.patch
  SPECS/sos/create-azure-kdump-class.patch
  SPECS/sos/create-azure-plugin.patch
  SPECS/sos/sos.spec
Labels: main

#7859 Upgrade package skopeo to 0.14.2, to take Docker Daemon fix
  SPECS/skopeo/skopeo.signatures.json
  SPECS/skopeo/skopeo.spec
  cgmanifest.json
Labels: main

#8871 git-lfs: upgrade version 3.4.1 -> 3.5.1 to address CVE-2023-39325 & CVE-2023-45288
  SPECS/git-lfs/CVE-2023-45288.patch
  SPECS/git-lfs/git-lfs.signatures.json
  SPECS/git-lfs/git-lfs.spec
  cgmanifest.json
Labels: security, main

#8859 Adding admin approval for certificate changes.
  .github/CODEOWNERS
Labels: main

#8864 attach EOL during image creation
  .pipelines/containerSourceData/scripts/BuildGoldenContainer.sh
  .pipelines/containerSourceData/scripts/PublishContainers.sh
Labels: main

#8862 Patch CVE-2024-3817 in terraform's vendored go-getter
  SPECS/terraform/CVE-2024-3817.patch
  SPECS/terraform/terraform.spec
Labels: main

#8867 conda: upgrade to 24.1.2
  SPECS/conda/0001-Add-back-conda-and-conda_env-entry-point.patch
  SPECS/conda/0001-Fix-toolz-imports.patch
  SPECS/conda/0001-Use-main-entry-point-for-conda-and-re-add-conda-env-.patch
  SPECS/conda/0002-Go-back-to-ruamel_yaml.patch
  SPECS/conda/0003-Drop-fs-path-encoding-manipulation-under-python2.patch
  SPECS/conda/0004-Do-not-try-to-run-usr-bin-python.patch
  SPECS/conda/0005-Fix-failing-tests-in-test_api.py.patch
  SPECS/conda/0006-shell-assume-shell-plugins-are-in-etc.patch
  SPECS/conda/conda
  SPECS/conda/conda-cpuinfo.patch
  SPECS/conda/conda-memoize.patch
  SPECS/conda/conda.signatures.json
  SPECS/conda/conda.spec
  SPECS/conda/conda_gateways_disk_create.patch
  SPECS/conda/conda_sys_prefix.patch
  cgmanifest.json
Labels: 3.0

#8884 frr: upgrade to 9.1
  SPECS/frr/0000-remove-babeld-and-ldpd.patch
  SPECS/frr/0001-enable-openssl.patch
  SPECS/frr/0003-fips-mode.patch
  SPECS/frr/0004-remove-grpc-test.patch
  SPECS/frr/0008-Add-FIPS_mode-compatibility-macro.patch
  SPECS/frr/frr.signatures.json
  SPECS/frr/frr.spec
  SPECS/libyang/libyang.signatures.json
  SPECS/libyang/libyang.spec
  cgmanifest.json
Labels: 3.0

#8879 selinux-policy: Add checkpoint restore for getty.
  SPECS/selinux-policy/0042-getty-grant-checkpoint_restore.patch
  SPECS/selinux-policy/selinux-policy.spec
Labels: main

#8556 moby-engine & moby-cli: upgrade version 20.10.27 -> 24.0.9
  SPECS/moby-cli/CVE-2021-44716.patch
  SPECS/moby-cli/CVE-2022-21698.patch
  SPECS/moby-cli/CVE-2023-48795.patch
  SPECS/moby-cli/disable_manpage_vendor.patch
  SPECS/moby-cli/generate_source_tarball.sh
  SPECS/moby-cli/moby-cli.signatures.json
  SPECS/moby-cli/moby-cli.spec
  SPECS/moby-engine/CVE-2022-21698.patch
  SPECS/moby-engine/CVE-2023-25153.patch
  SPECS/moby-engine/CVE-2024-23651.patch
  SPECS/moby-engine/CVE-2024-23652.patch
  SPECS/moby-engine/daemon.json
  SPECS/moby-engine/moby-engine.signatures.json
  SPECS/moby-engine/moby-engine.spec
  cgmanifest.json
Labels: main

#8894 python-virtualenv: update runtime requirements
  SPECS/python-virtualenv/python-virtualenv.spec
Labels: 3.0

#8903 Replace "April Update 2" with "May Update" in changelog
  SPECS/mariner-release/mariner-release.spec
Labels: main

#8818 Apply patches to fix CVE-2021-3602, CVE-2022-27651, CVE-2022-2995, CVE-2023-42821
  SPECS/cri-o/CVE-2021-3602.patch
  SPECS/cri-o/CVE-2021-44716.patch
  SPECS/cri-o/CVE-2022-21698.patch
  SPECS/cri-o/CVE-2022-27651.patch
  SPECS/cri-o/CVE-2022-29526.patch
  SPECS/cri-o/CVE-2022-2995.patch
  SPECS/cri-o/CVE-2023-42821.patch
  SPECS/cri-o/CVE-2023-44487.patch
  SPECS/cri-o/CVE-2024-28180.patch
  SPECS/cri-o/cri-o.spec
Labels: security, main

#8896 Kubernetes - fix missing auto patch
  SPECS/kubernetes/kubernetes.spec
Labels: main

#8901 Update Makefile to use ms-oss PMC url instead of Microsoft
  toolkit/Makefile
Labels: 3.0

#8326 Upgrading ocaml to 5.1.1, promoting annobin and updating llvm
  SPECS-EXTENDED/annobin/annobin.signatures.json
  SPECS/annobin/annobin.signatures.json
  SPECS/annobin/annobin.spec
  SPECS/llvm/llvm.spec
  SPECS/ocaml/0001-Don-t-add-rpaths-to-libraries.patch
  SPECS/ocaml/0002-configure-Allow-user-defined-C-compiler-flags.patch
  SPECS/ocaml/0003-Update-framepointers-tests-to-avoid-false-positive-w.patch
  SPECS/ocaml/0004-Fix-s390x-stack-reallocation-code-in-PIC-mode.patch
  SPECS/ocaml/macros.ocaml-rpm
  SPECS/ocaml/ocaml.signatures.json
  SPECS/ocaml/ocaml.spec
  SPECS/ocaml/ocaml_files.py
  cgmanifest.json
Labels: 3.0

#8902 Use msopenjdk 17 from AZL3 Preview repo in toolchain
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
Labels: 3.0

#8759 Moved distroless cert dependencies out of the meta package `distroless-packages`. (CP: #8651)
  .pipelines/containerSourceData/nodejs/distroless/nodejs18.pkg
  .pipelines/containerSourceData/prometheus/distroless/prometheus.pkg
  .pipelines/containerSourceData/prometheusadapter/distroless/prometheusadapter.pkg
  .pipelines/containerSourceData/python/distroless/python.pkg
  SPECS/distroless-packages/distroless-packages.spec
  toolkit/imageconfigs/packagelists/distroless-packages-container-minimal.json
  toolkit/imageconfigs/packagelists/distroless-packages-container.json
  toolkit/imageconfigs/packagelists/distroless-packages-debug.json
Labels: 3.0

#8900 Update SymCrypt-OpenSSL to 1.4.2
  SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.signatures.json
  SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.spec
  SPECS/SymCrypt/SymCrypt.spec
  cgmanifest.json
Labels: 3.0

#8912 xxhash: fix build issue with x86-64-v3
  SPECS/xxhash/xxhash.spec
Labels: 3.0

#8919 clamav: upgrade to 1.0.6
  SPECS/clamav/CVE-2022-48579.patch
  SPECS/clamav/CVE-2024-20328.patch
  SPECS/clamav/clamav.signatures.json
  SPECS/clamav/clamav.spec
  cgmanifest.json
Labels: main

#7092 fio: upgrade 3.30 -> 3.37
  SPECS/fio/fio.signatures.json
  SPECS/fio/fio.spec
  cgmanifest.json
Labels: 3.0

#8908 strace: upgrade to 6.8
  SPECS/strace/strace.signatures.json
  SPECS/strace/strace.spec
  cgmanifest.json
Labels: 3.0

#8923 php-pecl-zip: fix runtime requirements to match php 8.3.4
  SPECS/php-pecl-zip/php-pecl-zip.spec
Labels: 3.0

#8933 build redis with BUILD_TLS=yes
  SPECS/redis/redis.spec
Labels: main

#8899 Tune some kernel configs for aarch64
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#8934 attach EOL manifest to base containers as well
  .pipelines/containerSourceData/scripts/BuildBaseContainers.sh
Labels: main

#8949 [2.0] zeromq: upgrade to 4.3.5
  SPECS/zeromq/zeromq.signatures.json
  SPECS/zeromq/zeromq.spec
  cgmanifest.json
Labels: main

#8914 Fix kubernetes missing autopatch for CVE-2023-5408
  SPECS/kubernetes/CVE-2023-5408.patch
  SPECS/kubernetes/kubernetes.spec
Labels: fasttrack/2.0

#8917 Resolved overflow warnings from `installutils.go:ProvisionUserSSHCerts`.
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/internal/mathops/mathops.go
  toolkit/tools/internal/mathops/mathops_test.go
Labels: main

#8812 [CHERRYPICK] Backport azurelinux-sysinfo to 2.0
  .github/workflows/validate-cg-manifest.sh
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/azurelinux-sysinfo/azurelinux-sysinfo.service
  SPECS/azurelinux-sysinfo/azurelinux-sysinfo.signatures.json
  SPECS/azurelinux-sysinfo/azurelinux-sysinfo.spec
  SPECS/azurelinux-sysinfo/collect-sysinfo
  SPECS/azurelinux-sysinfo/sysinfo-schema-v1.json
  SPECS/azurelinux-sysinfo/sysinfo-selinuxpolicies.cil
Labels: main
