Repository microsoft/azurelinux, pull requests merged in 2024-12, with the labels that each got.

#11236 Fix CVE-2023-45288, CVE-2023-39325 and CVE-2024-24786 in kata-containers and kata-containers-cc
  SPECS/kata-containers-cc/CVE-2023-39325.patch
  SPECS/kata-containers-cc/CVE-2023-45288.patch
  SPECS/kata-containers-cc/CVE-2024-24786.patch
  SPECS/kata-containers-cc/kata-containers-cc.spec
  SPECS/kata-containers/CVE-2023-39325.patch
  SPECS/kata-containers/CVE-2023-45288.patch
  SPECS/kata-containers/CVE-2024-24786.patch
  SPECS/kata-containers/kata-containers.spec
Labels: Packaging

#11206 Fix CVE-2024-24786 in multiple packages by patching
  SPECS/cf-cli/CVE-2024-24786.patch
  SPECS/cf-cli/cf-cli.spec
  SPECS/containerd/CVE-2024-24786.patch
  SPECS/containerd/containerd.spec
  SPECS/containerized-data-importer/CVE-2024-24786.patch
  SPECS/containerized-data-importer/containerized-data-importer.spec
  SPECS/coredns/CVE-2024-24786.patch
  SPECS/coredns/coredns.spec
  SPECS/docker-cli/CVE-2024-24786.patch
  SPECS/docker-cli/docker-cli.spec
  SPECS/influxdb/CVE-2024-24786.patch
  SPECS/influxdb/influxdb.spec
  SPECS/kubevirt/CVE-2024-24786.patch
  SPECS/kubevirt/kubevirt.spec
  SPECS/libcontainers-common/CVE-2024-24786.patch
  SPECS/libcontainers-common/libcontainers-common.spec
  SPECS/moby-containerd-cc/CVE-2024-24786.patch
  SPECS/moby-containerd-cc/moby-containerd-cc.spec
  SPECS/moby-engine/CVE-2024-24786.patch
  SPECS/moby-engine/moby-engine.spec
  SPECS/node-problem-detector/CVE-2024-24786.patch
  SPECS/node-problem-detector/node-problem-detector.spec
  SPECS/packer/CVE-2024-24786.patch
  SPECS/packer/packer.spec
  SPECS/prometheus/CVE-2024-24786.patch
  SPECS/prometheus/prometheus.spec
Labels: Packaging

#11245 Add obsoletes and provides to fix errors in shim-unsigned upgrade to shim
  SPECS/shim-unsigned-aarch64/shim-unsigned-aarch64.spec
  SPECS/shim-unsigned-x64/shim-unsigned-x64.spec
  SPECS/shim/shim.spec
Labels: Packaging

#11078 Introduce kernel-64k
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS-SIGNED/kernel-64k-signed/kernel-64k-signed.spec
  SPECS-SIGNED/kernel-64k-signed/sha512hmac-openssl.sh
  SPECS/kernel-64k/0001-add-mstflint-kernel-4.28.0.patch
  SPECS/kernel-64k/0002-Increase-EFI_MMAP_NR_SLACK_SLOTS-for-GB200.patch
  SPECS/kernel-64k/azurelinux-ca-20230216.pem
  SPECS/kernel-64k/config_aarch64
  SPECS/kernel-64k/cpupower
  SPECS/kernel-64k/cpupower.service
  SPECS/kernel-64k/kernel-64k.signatures.json
  SPECS/kernel-64k/kernel-64k.spec
  SPECS/kernel-64k/sha512hmac-openssl.sh
  cgmanifest.json
  toolkit/scripts/check_entangled_specs.py
Labels: stable-release-shiproom

#11332 Fix call to IsSRPMTestActive in new multi build fix (#7992)
  toolkit/tools/scheduler/schedulerutils/preparerequest.go
Labels: Tools, main

#11152 gh: Upgrade to 2.62.0 to address HIGH CVE-2024-52308; add generate-tarball.sh script for auto-upgrading support
  SPECS/gh/0001-Fix-false-negative-in-TestMigrationWriteErrors-when-.patch
  SPECS/gh/generate_source_tarball.sh
  SPECS/gh/gh.signatures.json
  SPECS/gh/gh.spec
  cgmanifest.json
Labels: Packaging

#11321 Fix CVE-2024-52338 in ceph and libarrow for 3.0
  SPECS/ceph/CVE-2024-52338.patch
  SPECS/ceph/ceph.spec
  SPECS/libarrow/CVE-2024-52338.patch
  SPECS/libarrow/libarrow.spec
Labels: security, Packaging

#11326 moby-engine: Fix CVE-2024-36620, CVE-2024-36621, CVE-2024-36623 for 3.0
  SPECS/moby-engine/CVE-2024-36620.patch
  SPECS/moby-engine/CVE-2024-36621.patch
  SPECS/moby-engine/CVE-2024-36623.patch
  SPECS/moby-engine/moby-engine.spec
Labels: Packaging

#11054 make install_dependencies work with file dependencies
  toolkit/scripts/containerized-build/create_container_build.sh
  toolkit/scripts/containerized-build/resources/azl.Dockerfile
  toolkit/scripts/containerized-build/resources/setup_functions.sh
Labels: Tools

#11397 Cloud-init add module-setup.sh azure module for dracut to run
  SPECS/cloud-init/cloud-init.signatures.json
  SPECS/cloud-init/cloud-init.spec
  SPECS/cloud-init/module-setup.sh
Labels: Packaging, main

#11387 Fix CVE-2024-36623 for moby-compose
  SPECS/moby-compose/CVE-2024-36623.patch
  SPECS/moby-compose/moby-compose.spec
Labels: Packaging, fasttrack/2.0

#11386 Fix CVE-2024-36623 for moby-cli
  SPECS/moby-cli/CVE-2024-36623.patch
  SPECS/moby-cli/moby-cli.spec
Labels: Packaging, fasttrack/2.0

#11308 Patch CVE-2024-24786 in cri-tools
  SPECS/cri-tools/CVE-2024-24786.patch
  SPECS/cri-tools/cri-tools.spec
Labels: Packaging

#11069 Fix CVE-2024-27532 for fluent-bit
  SPECS/fluent-bit/CVE-2024-27532.patch
  SPECS/fluent-bit/fluent-bit.spec
Labels: Packaging, fasttrack/2.0

#11071 Fix CVE-2024-27532 for fluent-bit
  SPECS/fluent-bit/CVE-2024-27532.patch
  SPECS/fluent-bit/fluent-bit.spec
Labels: Packaging, fasttrack/3.0

#11309 upgrade php to 8.3.14
  SPECS/php/php-8.3.13-phpinfo.patch
  SPECS/php/php-8.3.14-phpinfo.patch
  SPECS/php/php.signatures.json
  SPECS/php/php.spec
  cgmanifest.json
Labels: Packaging

#11334 Patch CVE-2024-24786 in flannel
  SPECS/flannel/CVE-2024-24786.patch
  SPECS/flannel/flannel.spec
Labels: Packaging

#11392 Fix CVE-2024-36623 for docker-cli
  SPECS/docker-cli/CVE-2024-36623.patch
  SPECS/docker-cli/docker-cli.spec
Labels: Packaging, fasttrack/3.0

#11448 Patch "gh" to fix CVE-2024-54132
  SPECS/gh/CVE-2024-54132.patch
  SPECS/gh/gh.spec
Labels: Packaging

#11439 Release bump systemd-boot to use new keys
  SPECS-SIGNED/systemd-boot-signed/systemd-boot-signed.spec
  SPECS/systemd/systemd.spec
Labels: Packaging

#11320 Patch CVE-2024-24786 in moby-cli
  SPECS/moby-cli/CVE-2024-24786.patch
  SPECS/moby-cli/moby-cli.spec
Labels: Packaging

#11366 Fix CVE-2024-24786 in cf-cli and terraform for 2.0
  SPECS/cf-cli/CVE-2024-24786.patch
  SPECS/cf-cli/cf-cli.spec
  SPECS/terraform/CVE-2024-24786.patch
  SPECS/terraform/terraform.spec
Labels: security, Packaging

#11325 Patch CVE-2024-24786 in moby-buildx, moby-containerd-cc, moby-containerd
  SPECS/moby-buildx/CVE-2024-24786.patch
  SPECS/moby-buildx/moby-buildx.spec
  SPECS/moby-containerd-cc/CVE-2024-24786.patch
  SPECS/moby-containerd-cc/moby-containerd-cc.spec
  SPECS/moby-containerd/CVE-2024-24786.patch
  SPECS/moby-containerd/moby-containerd.spec
Labels: Packaging

#11365 Fix CVE-2024-24786 for packer
  SPECS/packer/CVE-2024-24786.patch
  SPECS/packer/packer.spec
Labels: Packaging

#11388 Fix CVE-2022-1941 for pytorch in 2.0
  SPECS/pytorch/CVE-2022-1941.patch
  SPECS/pytorch/pytorch.spec
Labels: Packaging

#11318 moby-engine: fix CVE-2024-36621, CVE-2024-36623 for 2.0
  SPECS/moby-engine/CVE-2024-36621.patch
  SPECS/moby-engine/CVE-2024-36623.patch
  SPECS/moby-engine/moby-engine.spec
Labels: Packaging

#11198 Enable selinux for liveos iso flow
  SPECS/dracut/0016-Handle-SELinux-configuration-for-overlayfs-folders.patch
  SPECS/dracut/90overlayfs/azl-configure-selinux.sh
  SPECS/dracut/dracut.signatures.json
  SPECS/dracut/dracut.spec
  SPECS/selinux-policy/0038-enable-liveos-iso-flow.patch
  SPECS/selinux-policy/selinux-policy.spec
Labels: Packaging

#11217 patch rust to fix CVE-2024-43806
  SPECS/rust/CVE-2024-43806.patch
  SPECS/rust/rust.spec
Labels: Packaging

#11424 Added distrusted CAs to the cert bundles.
  SPECS/ca-certificates/ca-certificates.signatures.json
  SPECS/ca-certificates/ca-certificates.spec
  SPECS/ca-certificates/certdata.distrusted.txt
  SPECS/prebuilt-ca-certificates-base/prebuilt-ca-certificates-base.spec
  SPECS/prebuilt-ca-certificates/prebuilt-ca-certificates.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, main

#11506 cert-manager: patch CVE-2024-45337
  SPECS/cert-manager/CVE-2024-45337.patch
  SPECS/cert-manager/cert-manager.spec
Labels: Packaging

#11507 moby-compose: patch CVE-2024-45337
  SPECS/moby-compose/CVE-2024-45337.patch
  SPECS/moby-compose/moby-compose.spec
Labels: Packaging

#11508 moby-engine: patch CVE-2024-45337
  SPECS/moby-engine/CVE-2024-45337.patch
  SPECS/moby-engine/moby-engine.spec
Labels: Packaging

#11362 Fix CVE-2024-24786 for influxdb
  SPECS/influxdb/CVE-2024-24786.patch
  SPECS/influxdb/influxdb.spec
Labels: Packaging

#11364 Fix CVE-2024-24786 for coredns
  SPECS/coredns/CVE-2024-24786.patch
  SPECS/coredns/coredns.spec
Labels: Packaging

#11259 Patch python3 for CVE-2024-6923
  SPECS/python3/CVE-2024-6923.patch
  SPECS/python3/python3.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#11449 Patch gh to fix CVE-2024-54132
  SPECS/gh/CVE-2024-54132.patch
  SPECS/gh/gh.spec
Labels: Packaging

#11367 etcd: Fix CVE-2024-24786
  SPECS/etcd/CVE-2024-24786.patch
  SPECS/etcd/etcd.spec
Labels: Packaging

#11407 Fix CVE-2024-53899 for python-virtualenv
  SPECS/python-virtualenv/CVE-2024-53899.patch
  SPECS/python-virtualenv/python-virtualenv.spec
Labels: Packaging, fasttrack/3.0

#11431 Patch "tuned" package to fix CVE-2024-52336 and CVE-2024-52337
  SPECS/tuned/CVE-2024-52336.patch
  SPECS/tuned/CVE-2024-52337.nopatch
  SPECS/tuned/tuned.spec
Labels: Packaging

#11505 packer: patch CVE-2024-45337
  SPECS/packer/CVE-2024-45337.patch
  SPECS/packer/packer.spec
Labels: Packaging

#11324 fix: ISO installer encrypted root doesn't boot
  toolkit/tools/imagegen/diskutils/diskutils.go
  toolkit/tools/imagegen/diskutils/encryption.go
Labels: Tools, 3.0-dev, stable-release-shiproom

#11515 Patch python-zipp for CVE-2024-5569
  SPECS/python-zipp/CVE-2024-5569.patch
  SPECS/python-zipp/python-zipp.spec
Labels: Packaging

#11385 Fix CVE-2024-24786 for etcd in 3.0
  SPECS/etcd/CVE-2024-24786.patch
  SPECS/etcd/etcd.spec
Labels: Packaging

#11330 Add AMD PMC repo for tdnf
  SPECS/azurelinux-repos/azurelinux-amd-preview.repo
  SPECS/azurelinux-repos/azurelinux-amd.repo
  SPECS/azurelinux-repos/azurelinux-repos.signatures.json
  SPECS/azurelinux-repos/azurelinux-repos.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#11442 Fix issue when version pinning packages that are checked by the configvalidator tool
  toolkit/tools/imageconfigvalidator/imageconfigvalidator.go
  toolkit/tools/imageconfigvalidator/imageconfigvalidator_test.go
  toolkit/tools/imageconfigvalidator/testdata/bogus-list.json
  toolkit/tools/imageconfigvalidator/testdata/dummy-list.json
  toolkit/tools/imageconfigvalidator/testdata/fips-list.json
  toolkit/tools/imageconfigvalidator/testdata/pinned-shadowutils-list.json
  toolkit/tools/imageconfigvalidator/testdata/pinned-shadowutils-ws-list.json
  toolkit/tools/imageconfigvalidator/testdata/selinux-policy-list.json
  toolkit/tools/imageconfigvalidator/testdata/shadowutils-list.json
  toolkit/tools/imageconfigvalidator/testdata/test-config.json
Labels: Tools

#11394 grpc: Address CVE-2023-32067
  SPECS/grpc/CVE-2023-32067.patch
  SPECS/grpc/grpc.spec
Labels: Packaging

#11323 Patch CVE-2024-24786 in moby-engine
  SPECS/moby-engine/CVE-2024-24786.patch
  SPECS/moby-engine/moby-engine.spec
Labels: Packaging

#11251 Patch avahi for multiple CVEs
  SPECS/avahi/CVE-2023-38469.patch
  SPECS/avahi/CVE-2023-38470.patch
  SPECS/avahi/CVE-2023-38471.patch
  SPECS/avahi/CVE-2023-38472.patch
  SPECS/avahi/CVE-2023-38473.patch
  SPECS/avahi/avahi.spec
Labels: Packaging

#11573 [AUTO-CHERRYPICK] Patch python-zipp for CVE-2024-5569 - branch 3.0-dev
  SPECS/python-zipp/CVE-2024-5569.patch
  SPECS/python-zipp/python-zipp.spec
Labels: Packaging, Auto Fast-track Cherry-pick

#11574 [AUTO-CHERRYPICK] Fix CVE-2024-24786 for etcd in 3.0 - branch 3.0-dev
  SPECS/etcd/CVE-2024-24786.patch
  SPECS/etcd/etcd.spec
Labels: Packaging, Auto Fast-track Cherry-pick

#11604 [AUTO-CHERRYPICK] iptraf-ng: upgrade to 1.2.2 - branch main
  SPECS/iptraf-ng/iptraf-ng.signatures.json
  SPECS/iptraf-ng/iptraf-ng.spec
  cgmanifest.json
Labels: main, Auto Fast-track Cherry-pick

#11605 [AUTO-CHERRYPICK] grpc: Address CVE-2023-32067 - branch main
  SPECS/grpc/CVE-2023-32067.patch
  SPECS/grpc/grpc.spec
Labels: Packaging, main, Auto Fast-track Cherry-pick

#11606 [AUTO-CHERRYPICK] Patch avahi for multiple CVEs - branch main
  SPECS/avahi/CVE-2023-38469.patch
  SPECS/avahi/CVE-2023-38470.patch
  SPECS/avahi/CVE-2023-38471.patch
  SPECS/avahi/CVE-2023-38472.patch
  SPECS/avahi/CVE-2023-38473.patch
  SPECS/avahi/avahi.spec
Labels: Packaging, main, Auto Fast-track Cherry-pick

#11607 [AUTO-CHERRYPICK] Patch CVE-2024-24786 in moby-engine - branch main
  SPECS/moby-engine/CVE-2024-24786.patch
  SPECS/moby-engine/moby-engine.spec
Labels: Packaging, main, Auto Fast-track Cherry-pick

#11620 cf-cli, kubevirt, packer: patch CVE-2024-45337
  SPECS/cf-cli/CVE-2024-45337.patch
  SPECS/cf-cli/cf-cli.spec
  SPECS/kubevirt/CVE-2024-45337.patch
  SPECS/kubevirt/kubevirt.spec
  SPECS/packer/CVE-2024-45337.patch
  SPECS/packer/packer.spec
Labels: Packaging

#11618 docker-buildx, moby-engine: patch CVE-2024-45337
  SPECS/docker-buildx/CVE-2024-45337.patch
  SPECS/docker-buildx/docker-buildx.spec
  SPECS/moby-engine/CVE-2024-45337.patch
  SPECS/moby-engine/moby-engine.spec
Labels: Packaging

#11631 Upgrade DPDK for CVE-2024-11614
  SPECS/dpdk/dpdk.signatures.json
  SPECS/dpdk/dpdk.spec
  cgmanifest.json
Labels: Packaging

#11621 Enable arch conditionals in azurelinux-repos.spec
  SPECS/azurelinux-repos/azurelinux-repos.spec
Labels: Packaging

#11641 Bump Release for January 2025 Update
  SPECS/azurelinux-release/azurelinux-release.spec
Labels: Packaging

#11642 Bump Release for January 2025 Update
  SPECS/mariner-release/mariner-release.spec
Labels: Packaging, main

#11633 [AUTO-CHERRYPICK] Upgrade DPDK for CVE-2024-11614 - branch 3.0-dev
  SPECS/dpdk/dpdk.signatures.json
  SPECS/dpdk/dpdk.spec
  cgmanifest.json
Labels: Auto Fast-track Cherry-pick

#11630 [AUTO-CHERRYPICK] docker-buildx, moby-engine: patch CVE-2024-45337 - branch 3.0-dev
  SPECS/docker-buildx/CVE-2024-45337.patch
  SPECS/docker-buildx/docker-buildx.spec
  SPECS/moby-engine/CVE-2024-45337.patch
  SPECS/moby-engine/moby-engine.spec
Labels: Packaging, Auto Fast-track Cherry-pick

#11629 [AUTO-CHERRYPICK] cf-cli, kubevirt, packer: patch CVE-2024-45337 - branch 3.0-dev
  SPECS/cf-cli/CVE-2024-45337.patch
  SPECS/cf-cli/cf-cli.spec
  SPECS/kubevirt/CVE-2024-45337.patch
  SPECS/kubevirt/kubevirt.spec
  SPECS/packer/CVE-2024-45337.patch
  SPECS/packer/packer.spec
Labels: Packaging, Auto Fast-track Cherry-pick

#11678 Fixed `golang.org/x/crypto` and `golang.org/x/net` vulnerabilities.
  toolkit/tools/go.mod
  toolkit/tools/go.sum
Labels: Tools

#11679 Fixed `golang.org/x/crypto` and `golang.org/x/net` vulnerabilities.
  toolkit/tools/go.mod
  toolkit/tools/go.sum
Labels: Tools, main

#11718 libxml2: address CVE-2024-40896
  SPECS/libxml2/CVE-2024-40896.patch
  SPECS/libxml2/libxml2.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, fasttrack/3.0

#11719 Added missing `Obsoletes: dbus-x11` in `dbus.spec`
  SPECS/dbus/dbus.spec
Labels: Packaging, main
