Repository microsoft/azurelinux, pull requests merged in 2024-11, with the labels that each got.

#10908 Make pytorch vendor generation script executable
  SPECS/pytorch/generate_source_tarball.sh
Labels: Packaging

#10894 Patched CVE-2023-45866 in `bluez`. (CP: #7097)
  SPECS/bluez/CVE-2023-45866.patch
  SPECS/bluez/bluez.spec
Labels: Packaging

#10899 gnutls: Fix CVE-2024-28834, CVE-2024-28835
  SPECS/gnutls/CVE-2024-28834.patch
  SPECS/gnutls/CVE-2024-28835.patch
  SPECS/gnutls/gnutls.spec
Labels: Packaging

#10917 Partial revert of "Toolkit: Add missing `flock` calls. (#10804)".
  toolkit/tools/imagegen/diskutils/diskutils.go
Labels: Tools

#10870 Fix CVE-2024-50602 in expat
  SPECS/expat/CVE-2024-50602.patch
  SPECS/expat/expat.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#10876 Patched CVE-2024-2410 in `mysql`.
  SPECS/mysql/CVE-2024-2410.patch
  SPECS/mysql/fix-tests-for-unsupported-chacha-ciphers.patch
  SPECS/mysql/mysql.spec
Labels: Packaging

#10926 Address CVE-2022-47007, CVE-2022-47008, CVE-2022-47010, CVE-2022-47011
  SPECS/binutils/CVE-2022-47007.patch
  SPECS/binutils/CVE-2022-47008.patch
  SPECS/binutils/CVE-2022-47010.patch
  SPECS/binutils/CVE-2022-47011.patch
  SPECS/binutils/binutils.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#10944 Image Customizer: Bump to v0.8
  toolkit/scripts/build_tag_imagecustomizer.mk
Labels: Tools

#10781 file: address CVE-2022-48554
  SPECS/file/CVE-2022-48554.patch
  SPECS/file/file.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, main

#10940 Modified `mysql` to explicitly not use `curl`.
  SPECS/mysql/mysql.spec
Labels: Packaging

#10929 ruby and rubygem-rexml: patch CVE-2024-49761
  SPECS/ruby/CVE-2024-49761.patch
  SPECS/ruby/ruby.spec
  SPECS/rubygem-rexml/CVE-2024-49761.patch
  SPECS/rubygem-rexml/rubygem-rexml.spec
Labels: Packaging

#10954 [2.0] prometheus address CVE-2023-39325 CVE-2023-45288
  SPECS/prometheus/CVE-2023-39325.patch
  SPECS/prometheus/CVE-2023-45288.patch
  SPECS/prometheus/prometheus.spec
Labels: Packaging

#10945 netplan: fix CVE-2022-4968
  SPECS/netplan/disable-broken-tests.patch
  SPECS/netplan/netplan.signatures.json
  SPECS/netplan/netplan.spec
  SPECS/netplan/rich-import-failure-no-log.patch
  cgmanifest.json
Labels: Packaging

#10335 cloud-hypervisor-cvm: add upstream patch to work around lack of support for extended guest requests
  SPECS/cloud-hypervisor-cvm/cloud-hypervisor-cvm.spec
  SPECS/cloud-hypervisor-cvm/microsoft-cloud-hypervisor-6695.patch
Labels: Packaging, main

#10998 Fix multiple CVEs in Skopeo
  SPECS/skopeo/CVE-2024-24786.patch
  SPECS/skopeo/CVE-2024-28180.patch
  SPECS/skopeo/CVE-2024-9676.patch
  SPECS/skopeo/skopeo.spec
Labels: security, Packaging, fasttrack/2.0

#10706 Enable Dracut's livenet rootfs handling when systemd-networkd is in use.
  SPECS/dracut/90livenet/azl-liveos-artifacts-download.service
  SPECS/dracut/90livenet/azl-liveos-artifacts-download.sh
  SPECS/dracut/add-livenet-download-service.patch
  SPECS/dracut/dracut.signatures.json
  SPECS/dracut/dracut.spec
Labels: Packaging

#10595 [mic][iso] generate PXE-bootable ISO images.
  toolkit/tools/imagecustomizer/docs/cli.md
  toolkit/tools/imagecustomizer/docs/configuration.md
  toolkit/tools/imagecustomizer/docs/pxe.md
  toolkit/tools/imagecustomizer/main.go
  toolkit/tools/imagecustomizerapi/config.go
  toolkit/tools/imagecustomizerapi/pxe.go
  toolkit/tools/pkg/imagecustomizerlib/customizefiles_test.go
  toolkit/tools/pkg/imagecustomizerlib/customizehostname_test.go
  toolkit/tools/pkg/imagecustomizerlib/customizeoverlays_test.go
  toolkit/tools/pkg/imagecustomizerlib/customizepackages.go
  toolkit/tools/pkg/imagecustomizerlib/customizepackages_test.go
  toolkit/tools/pkg/imagecustomizerlib/customizepartitions_test.go
  toolkit/tools/pkg/imagecustomizerlib/customizeselinux_test.go
  toolkit/tools/pkg/imagecustomizerlib/customizeservices_test.go
  toolkit/tools/pkg/imagecustomizerlib/customizeusers_test.go
  toolkit/tools/pkg/imagecustomizerlib/customizeverity_test.go
  toolkit/tools/pkg/imagecustomizerlib/dracututils.go
  toolkit/tools/pkg/imagecustomizerlib/extractpartitions_test.go
  toolkit/tools/pkg/imagecustomizerlib/grubcfgutils.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
  toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
  toolkit/tools/pkg/imagecustomizerlib/installedkernelcheck_test.go
  toolkit/tools/pkg/imagecustomizerlib/kernelmoduleutils_test.go
  toolkit/tools/pkg/imagecustomizerlib/liveosisobuilder.go
  toolkit/tools/pkg/imagecustomizerlib/liveosisobuilder_test.go
  toolkit/tools/pkg/imagecustomizerlib/resolvconf_test.go
  toolkit/tools/pkg/imagecustomizerlib/runscripts_test.go
  toolkit/tools/pkg/imagecustomizerlib/savedconfigs.go
  toolkit/tools/pkg/imagecustomizerlib/testdata/iso-files-and-args-config.yaml
Labels: Tools

#10891 Patched CVE-2012-2677 in `mysql`.
  SPECS/mysql/CVE-2012-2677.patch
  SPECS/mysql/mysql.spec
Labels: Packaging

#10956 [3.0] prometheus - Fix CVE-2023-45288
  SPECS/prometheus/CVE-2023-45288.patch
  SPECS/prometheus/prometheus.spec
Labels: Packaging

#10949 Patch CVE-2024-49767 in python-werkzeug
  SPECS/python-werkzeug/CVE-2024-49767.patch
  SPECS/python-werkzeug/python-werkzeug.spec
Labels: Packaging, main

#10948 Patch CVE-2024-49767 in python-werkzeug
  SPECS/python-werkzeug/CVE-2024-49767.patch
  SPECS/python-werkzeug/python-werkzeug.spec
Labels: Packaging

#10930 Add merge conflict github PR check
  .github/workflows/merge-conflict-check.yml
Labels: main

#11095 Fix CVE-2024-9632 for xorg-x11-server
  SPECS/xorg-x11-server/CVE-2024-9632.patch
  SPECS/xorg-x11-server/xorg-x11-server.spec
Labels: Packaging

#11098 fluent-bit: Address CVE-2024-25431
  SPECS/fluent-bit/CVE-2024-25431.patch
  SPECS/fluent-bit/fluent-bit.spec
Labels: Packaging

#11011 [2.0] Upgrade nvidia container toolkit and libnvidia-containers to v1.17.1
  SPECS/libnvidia-container/libnvidia-container.signatures.json
  SPECS/libnvidia-container/libnvidia-container.spec
  SPECS/nvidia-container-toolkit/nvidia-container-toolkit.signatures.json
  SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec
  cgmanifest.json
Labels: main

#11110 python3: Address CVE-2024-11168 with a formatted patch
  SPECS/python3/CVE-2024-11168.patch
Labels: security, Packaging

#11111 Fix CVE-2023-7256 and CVE-2024-8006 for nmap: 2.0
  SPECS/nmap/CVE-2023-7256.patch
  SPECS/nmap/CVE-2024-8006.patch
  SPECS/nmap/nmap.spec
Labels: Packaging

#11102 libsoup: add patches for CVE-2024-52530, CVE-2024-52531, CVE-2024-52532
  SPECS/libsoup/CVE-2024-52530.patch
  SPECS/libsoup/CVE-2024-52531.patch
  SPECS/libsoup/CVE-2024-52532.patch
  SPECS/libsoup/libsoup.spec
Labels: Packaging

#11112 Fix CVE-2023-7256 for libpcap :2.0
  SPECS/libpcap/CVE-2023-7256.patch
  SPECS/libpcap/libpcap.spec
Labels: Packaging

#11092 busybox: Address CVE-2023-42366
  SPECS/busybox/CVE-2023-42366.patch
  SPECS/busybox/busybox.spec
Labels: Packaging

#11043 cmake: Fixes for CVE-2022-43552, CVE-2023-27536, CVE-2023-27535, CVE-2023-27538, CVE-2023-23916 and CVE-2023-46218
  SPECS/cmake/CVE-2022-43552.patch
  SPECS/cmake/CVE-2023-23916.patch
  SPECS/cmake/CVE-2023-27535.patch
  SPECS/cmake/CVE-2023-27536.patch
  SPECS/cmake/CVE-2023-27538.patch
  SPECS/cmake/CVE-2023-46218.patch
  SPECS/cmake/cmake.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#11039 Toolkit: Use systemd-detect-virt instead of /.dockerenv to detect container builds.
  toolkit/docs/building/prerequisites-mariner.md
  toolkit/docs/building/prerequisites-ubuntu.md
  toolkit/scripts/chroot.mk
  toolkit/scripts/tools.mk
  toolkit/tools/containercheck/containercheck.go
  toolkit/tools/internal/buildpipeline/buildpipeline.go
  toolkit/tools/pkggen/worker/create_worker_chroot.sh
Labels: bug, Tools, main, 3.0-dev

#11009 Enable lua support for fluent-bit
  SPECS/fluent-bit/CVE-2024-25629.patch
  SPECS/fluent-bit/CVE-2024-28182.patch
  SPECS/fluent-bit/fluent-bit.signatures.json
  SPECS/fluent-bit/fluent-bit.spec
  cgmanifest.json
Labels: Packaging, 3.0-dev

#11106 Fix CVE-2024-21538, CVE-2020-28458 for reaper
  SPECS/reaper/CVE-2020-28458.patch
  SPECS/reaper/CVE-2024-21538.patch
  SPECS/reaper/reaper.spec
Labels: Packaging

#11086 Updated package build templates to capture all build logs.
  .pipelines/templates/PackageBuild.yml
Labels: main

#11178 sriov: Patch CVE-2024-24786 in vendored google.golang.org/protobuf
  SPECS/sriov-network-device-plugin/CVE-2024-24786.patch
  SPECS/sriov-network-device-plugin/sriov-network-device-plugin.spec
Labels: Packaging

#11174 Fix CVE-2024-35235 for cups :2.0
  SPECS/cups/CVE-2024-35235.patch
  SPECS/cups/cups.spec
Labels: security, Packaging

#11173 Fix CVE-2024-10524 for wget :2.0
  SPECS/wget/CVE-2024-10524.patch
  SPECS/wget/wget.spec
Labels: security, Packaging

#11177 Fix CVE-2024-21538 in nodejs
  SPECS/nodejs/CVE-2024-21538.patch
  SPECS/nodejs/nodejs18.spec
  SPECS/python-tensorboard/python-tensorboard.spec
Labels: Packaging

#11094 Fix CVE-2024-9632 for xorg-x11-server-Xwayland
  SPECS/xorg-x11-server-Xwayland/CVE-2024-9632.patch
  SPECS/xorg-x11-server-Xwayland/xorg-x11-server-Xwayland.spec
Labels: Packaging

#11109 Fix CVE-2023-7256 and CVE-2024-8006 for nmap : 3.0
  SPECS/nmap/CVE-2023-7256.patch
  SPECS/nmap/CVE-2024-8006.patch
  SPECS/nmap/nmap.spec
Labels: security, Packaging

#11096 fluent-bit: Address CVE-2024-25431
  SPECS/fluent-bit/CVE-2024-25431.patch
  SPECS/fluent-bit/fluent-bit.spec
Labels: Packaging

#11140 nodejs and python-tensorboard: patched vendor tarball to fix CVE-2024-21538
  SPECS/nodejs/CVE-2024-21538.patch
  SPECS/nodejs/nodejs.spec
  SPECS/python-tensorboard/python-tensorboard.spec
Labels: Packaging

#10612 Update CONFIG_DRM as loadable module and create sub-package for in-tree amdgpu modules
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS-SIGNED/kernel-uki-signed/kernel-uki-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel-uki.spec
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: 3.0-dev, stable-release-shiproom

#11027 iptables: Enable nftables.
  SPECS/ebtables/ebtables.spec
  SPECS/iptables/iptables.spec
Labels: Packaging, 3.0-dev, stable-release-shiproom

#11025 busybox: Address CVE-2023-42366
  SPECS/busybox/CVE-2023-42366.patch
  SPECS/busybox/busybox.spec
Labels: Packaging

#11082 binutils: address CVE-2022-35205, CVE-2022-48063, CVE-2023-1972
  SPECS/binutils/CVE-2022-35205.patch
  SPECS/binutils/CVE-2022-48063.patch
  SPECS/binutils/CVE-2023-1972.patch
  SPECS/binutils/binutils.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: main

#11108 libsoup: add patches for CVE-2024-52530, CVE-2024-52531, CVE-2024-52532
  SPECS/libsoup/CVE-2024-52530.patch
  SPECS/libsoup/CVE-2024-52531.patch
  SPECS/libsoup/CVE-2024-52532.patch
  SPECS/libsoup/libsoup.spec
Labels: Packaging

#11176 Fix CVE-2024-5742 for nano :3.0
  SPECS/nano/CVE-2024-5742.patch
  SPECS/nano/nano.spec
Labels: security, Packaging

#11181 Fix CVE-2024-37891 for python-pip :3.0
  SPECS/python-pip/CVE-2024-37891.patch
  SPECS/python-pip/python-pip.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#11201 Fix CVE-2022-0529 and CVE-2022-0530 for unzip :3.0
  SPECS/unzip/CVE-2022-0529.patch
  SPECS/unzip/unzip.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#11135 Backport toolkit container detection using systemd-detect-virt
  toolkit/docs/building/prerequisites-mariner.md
  toolkit/docs/building/prerequisites-ubuntu.md
  toolkit/scripts/chroot.mk
  toolkit/scripts/tools.mk
  toolkit/tools/containercheck/containercheck.go
  toolkit/tools/internal/buildpipeline/buildpipeline.go
  toolkit/tools/pkggen/worker/create_worker_chroot.sh
Labels: bug, Tools, main

#10626 Fix CVE-2023-46118 for rabbitmq-server
  SPECS/rabbitmq-server/generate-rabbitmq-server-tarball.sh
  SPECS/rabbitmq-server/rabbitmq-server.signatures.json
  SPECS/rabbitmq-server/rabbitmq-server.spec
  cgmanifest.json
Labels: security, main

#11221 Extended CVE-2024-10224 patch and fixed ptests in `perl-Module-ScanDeps`.
  SPECS/perl-Module-ScanDeps/CVE-2024-10224.patch
  SPECS/perl-Module-ScanDeps/perl-Module-ScanDeps.spec
Labels: Packaging

#11223 Fix CVE-2024-5535 in hvloader
  SPECS-SIGNED/hvloader-signed/hvloader-signed.spec
  SPECS/hvloader/CVE-2024-5535.patch
  SPECS/hvloader/hvloader.spec
Labels: Packaging

#10403 Changing name produced for cvm and marketplace images
  toolkit/imageconfigs/marketplace-gen2-cvm.json
Labels: Schema

#11200 fix CVE-2023-39325, CVE-2023-44487 and CVE-2023-45288
  SPECS/multus/CVE-2023-44487.patch
  SPECS/multus/CVE-2023-45288.patch
  SPECS/multus/multus.spec
Labels: Packaging, fasttrack/3.0

#11204 kata-packages-uvm: Add make dependency
  SPECS/kata-packages-uvm/kata-packages-uvm.spec
Labels: Packaging
