Repository microsoft/azurelinux, pull requests merged in 2025-06, with the labels that each got.

#13466 Remove unsupported packages and those available in the cncf repository
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS-EXTENDED/containernetworking-plugins/containernetworking-plugins.signatures.json
  SPECS-EXTENDED/containernetworking-plugins/containernetworking-plugins.spec
  SPECS/blobfuse2/CVE-2025-30204.patch
  SPECS/blobfuse2/blobfuse2.signatures.json
  SPECS/blobfuse2/blobfuse2.spec
  SPECS/blobfuse2/generate_source_tarball.sh
  SPECS/core-packages/core-packages.spec
  SPECS/helm/CVE-2024-45338.patch
  SPECS/helm/CVE-2025-22872.patch
  SPECS/helm/CVE-2025-32386.patch
  SPECS/helm/generate_source_tarball.sh
  SPECS/helm/helm.signatures.json
  SPECS/helm/helm.spec
  SPECS/ig/CVE-2025-22872.patch
  SPECS/ig/CVE-2025-27144.patch
  SPECS/ig/CVE-2025-29786.patch
  SPECS/ig/generate_source_tarball.sh
  SPECS/ig/ig.signatures.json
  SPECS/ig/ig.spec
  SPECS/local-path-provisioner/CVE-2020-8565.patch
  SPECS/local-path-provisioner/CVE-2023-39325.patch
  SPECS/local-path-provisioner/CVE-2023-44487.patch
  SPECS/local-path-provisioner/CVE-2023-45288.patch
  SPECS/local-path-provisioner/local-path-provisioner.signatures.json
  SPECS/local-path-provisioner/local-path-provisioner.spec
  SPECS/node-problem-detector/0001-remove-arch-specific-logic-from-makefile.patch
  SPECS/node-problem-detector/CVE-2024-45338.patch
  SPECS/node-problem-detector/CVE-2025-22868.patch
  SPECS/node-problem-detector/CVE-2025-22869.patch
  SPECS/node-problem-detector/node-problem-detector.signatures.json
  SPECS/node-problem-detector/node-problem-detector.spec
  SPECS/prometheus/0001-Fix-exit-condition-of-TestQuerierIndexQueriesRace.patch
  SPECS/prometheus/0002-Improve-sensitivity-of-TestQuerierIndexQueriesRace.patch
  SPECS/prometheus/02-Default_settings.patch
  SPECS/prometheus/CVE-2023-44487.patch
  SPECS/prometheus/CVE-2023-45288.patch
  SPECS/prometheus/CVE-2024-24786.patch
  SPECS/prometheus/CVE-2024-35255.patch
  SPECS/prometheus/CVE-2024-51744.patch
  SPECS/prometheus/CVE-2024-6104.patch
  SPECS/prometheus/CVE-2025-22868.patch
  SPECS/prometheus/CVE-2025-22870.patch
  SPECS/prometheus/CVE-2025-30204.patch
  SPECS/prometheus/generate_source_tarball.sh
  SPECS/prometheus/prometheus.conf
  SPECS/prometheus/prometheus.logrotate
  SPECS/prometheus/prometheus.service
  SPECS/prometheus/prometheus.signatures.json
  SPECS/prometheus/prometheus.spec
  SPECS/prometheus/prometheus.sysconfig
  SPECS/prometheus/prometheus.yml
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#13919 python-argparse-manpage: Fix ptests
  SPECS-EXTENDED/python-argparse-manpage/0001-Fix-setuptools-v60.patch
  SPECS-EXTENDED/python-argparse-manpage/python-argparse-manpage.spec
Labels: Packaging, specs-extended, 3.0-dev

#13856 xalan-j2: Build Fix
  SPECS-EXTENDED/xalan-j2/xalan-j2.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#13444 [Medium] Patch cert-manager for CVE-2025-32386, CVE-2025-32387, CVE-2025-22872
  SPECS/cert-manager/CVE-2025-22872.patch
  SPECS/cert-manager/CVE-2025-32386.patch
  SPECS/cert-manager/cert-manager.spec
Labels: security, Packaging, 3.0-dev

#13951 Add patch to gcr allowing meson to build
  SPECS-EXTENDED/gcr/fix-meson-packages-build-keyword.patch
  SPECS-EXTENDED/gcr/gcr.spec
Labels: Packaging, specs-extended, 3.0-dev

#13428 [LOW] Patch glib for CVE-2025-3360
  SPECS/glib/CVE-2025-3360.patch
  SPECS/glib/glib.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, Tools, main

#13892 [Medium] Patch jq for CVE-2024-23337
  SPECS/jq/CVE-2024-23337.patch
  SPECS/jq/jq.spec
Labels: security, Packaging, main

#13900 Added simple package build PR checks.
  .github/actions/checkout-with-stable-pkgs/action.yml
  .github/workflows/check-package-builds.yml
Labels: Packaging, Tools, 3.0-dev

#13443 [Medium] Patch cert-manager for CVE-2025-32386, CVE-2025-32387, CVE-2025-22872
  SPECS/cert-manager/CVE-2025-22872.patch
  SPECS/cert-manager/CVE-2025-32386.patch
  SPECS/cert-manager/cert-manager.spec
Labels: security, Packaging, main

#13450 [Medium] patch ntopng for CVE-2021-44964
  SPECS/ntopng/CVE-2021-44964.patch
  SPECS/ntopng/ntopng.spec
Labels: security, Packaging, main

#13811 [MEDIUM] Patch libvirt for CVE-2024-4418
  SPECS/libvirt/CVE-2024-4418.patch
  SPECS/libvirt/libvirt.spec
Labels: security, Packaging, 3.0-dev

#13522 [Medium] Patch libxml2 for CVE-2025-32414 and CVE-2025-32415
  SPECS/libxml2/CVE-2025-32414.patch
  SPECS/libxml2/CVE-2025-32415.patch
  SPECS/libxml2/libxml2.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, main

#13586 [MEDIUM] Patch golang for CVE-2024-24789, CVE-2024-34155 & CVE-2025-22870
  SPECS/golang/CVE-2024-24789.patch
  SPECS/golang/CVE-2024-34155.patch
  SPECS/golang/CVE-2025-22870-1.18.patch
  SPECS/golang/CVE-2025-22870.patch
  SPECS/golang/golang-1.18.spec
  SPECS/golang/golang.spec
Labels: security, Packaging, main

#13901 [MEDIUM] Patch nodejs for CVE-2025-23165 CVE-2025-23166
  SPECS/nodejs/CVE-2025-23165.patch
  SPECS/nodejs/CVE-2025-23166.patch
  SPECS/nodejs/nodejs.spec
Labels: security, Packaging, 3.0-dev

#13982 [Medium] Patch binutils-2.37 for CVE-2025-5245 and CVE-2025-5244
  SPECS/binutils/CVE-2025-5244.patch
  SPECS/binutils/CVE-2025-5245.patch
  SPECS/binutils/binutils.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, main

#13782 [MEDIUM] Patch moby-buildx for CVE-2025-0495
  SPECS/moby-buildx/CVE-2025-0495.patch
  SPECS/moby-buildx/moby-buildx.spec
Labels: security, Packaging, main

#13820 Patch javapackages-bootstrap for CVE-2024-25710 [HIGH]
  SPECS/javapackages-bootstrap/CVE-2024-25710.patch
  SPECS/javapackages-bootstrap/javapackages-bootstrap.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#13496 [Medium] Patch libsoup for CVE-2025-32909, CVE-2025-32910, CVE-2025-32912, CVE-2025-4476
  SPECS/libsoup/CVE-2025-32909.patch
  SPECS/libsoup/CVE-2025-32910.patch
  SPECS/libsoup/CVE-2025-32912.patch
  SPECS/libsoup/CVE-2025-4476.patch
  SPECS/libsoup/libsoup.spec
Labels: security, Packaging, main

#13955 Upgrade `mysql` to 8.0.42 for fixing 25 CVEs
  SPECS/mysql/CVE-2025-0725.patch
  SPECS/mysql/mysql.signatures.json
  SPECS/mysql/mysql.spec
  cgmanifest.json
Labels: security, Packaging, fasttrack/2.0, CVEFixReadyForMaintainerReview

#13984 [High] Patch opa for CVE-2025-46569
  SPECS/opa/CVE-2025-46569.patch
  SPECS/opa/opa.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#13983 [High] Patch python3 for CVE-2025-4516, CVE-2025-4517, CVE-2024-12718, CVE-2025-4138, CVE-2025-4330, CVE-2025-4435
  SPECS/python3/CVE-2025-4516.patch
  SPECS/python3/CVE-2025-4517.patch
  SPECS/python3/python3.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#13996 [Low] Patch valkey for CVE-2025-49112
  SPECS/valkey/CVE-2025-49112.patch
  SPECS/valkey/valkey.spec
Labels: security, Packaging, 3.0-dev

#13999 Patch `frr` for CVE-2024-55553 [High]
  SPECS/frr/CVE-2024-55553.patch
  SPECS/frr/frr.spec
Labels: security, Packaging, fasttrack/2.0, CVEFixReadyForMaintainerReview

#13939 [High] patch grub2 for CVE-2025-0624
  SPECS-SIGNED/grub2-efi-binary-signed/grub2-efi-binary-signed.spec
  SPECS/grub2/CVE-2025-0624.patch
  SPECS/grub2/grub2.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#13813 Prevent stripping of BTF data from kernel modules
  SPECS-EXTENDED/kernel-ipe/kernel-ipe.spec
  SPECS-SIGNED/kernel-64k-signed/kernel-64k-signed.spec
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS-SIGNED/kernel-uki-signed/kernel-uki-signed.spec
  SPECS/kernel-64k/kernel-64k.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/kernel-uki.spec
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, specs-extended, 3.0-dev

#13841 [Medium] Patch rubygem-rexml for CVE-2024-43398 & Upgrade rubygem-rexml to 3.2.9
  SPECS/rubygem-rexml/CVE-2024-39908.patch
  SPECS/rubygem-rexml/CVE-2024-43398.patch
  SPECS/rubygem-rexml/rubygem-rexml.signatures.json
  SPECS/rubygem-rexml/rubygem-rexml.spec
  cgmanifest.json
Labels: security, Packaging, main

#13764 [Medium] Upgrade ruby to 3.1.7 to fix CVE-2024-39908
  SPECS/ruby/CVE-2023-36617.patch
  SPECS/ruby/CVE-2024-27280.patch
  SPECS/ruby/CVE-2024-27281.patch
  SPECS/ruby/CVE-2024-27282.patch
  SPECS/ruby/CVE-2024-35176.patch
  SPECS/ruby/CVE-2024-41946.patch
  SPECS/ruby/CVE-2024-49761.patch
  SPECS/ruby/CVE-2025-27219.patch
  SPECS/ruby/CVE-2025-27220.patch
  SPECS/ruby/CVE-2025-27221.patch
  SPECS/ruby/ruby.signatures.json
  SPECS/ruby/ruby.spec
  cgmanifest.json
Labels: Packaging, main

#14000 [High] Patch libsoup for CVE-2025-32907
  SPECS/libsoup/CVE-2025-32907.patch
  SPECS/libsoup/libsoup.spec
Labels: security, Packaging, fasttrack/2.0

#13994 [High] Patch python3 for CVE-2025-4138, CVE-2025-4330, CVE-2025-4517, CVE-2025-4516, CVE-2024-12718, CVE-2025-4435, CVE-2023-5752, and CVE-2023-45803
  SPECS/python3/CVE-2023-45803.patch
  SPECS/python3/CVE-2023-5752.patch
  SPECS/python3/CVE-2025-4138.patch
  SPECS/python3/CVE-2025-4516.patch
  SPECS/python3/python3.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, fasttrack/2.0

#10850 Port fasttrack PR check to PRs that target dev branches
  .pipelines/prchecks/DevPRCheck.yml
  .pipelines/prchecks/FastTrackPRCheck.yml
  .pipelines/prchecks/PackageBuildPRCheck.yml
  .pipelines/templates/PackageBuild.yml
  .pipelines/templates/PackageBuildPRCheck.yml
  .pipelines/templates/ToolchainBuild.yml
Labels: Packaging, 3.0-dev

#13915 [3.0] Fixing influxdb default config, upgrading entry point script to use new command for server configuration
  .pipelines/containerSourceData/influxdb/Dockerfile-Influxdb
  .pipelines/containerSourceData/influxdb/configuration-files/default-config.yml
  .pipelines/containerSourceData/influxdb/configuration-files/influxdb-docker-entrypoint.sh
  .pipelines/containerSourceData/influxdb/influxdb.pkg
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS/dasel/dasel.signatures.json
  SPECS/dasel/dasel.spec
  SPECS/dasel/generate_source_tarball.sh
  SPECS/influxdb/config.yaml
  SPECS/influxdb/influxdb.signatures.json
  SPECS/influxdb/influxdb.spec
  cgmanifest.json
Labels: Packaging, Tools, specs-extended, 3.0-dev, 3.0

#13934 Patch `glibc` for CVE-2025-4802 & CVE-2025-0395 [High]
  SPECS-EXTENDED/buildah/buildah.spec
  SPECS-EXTENDED/catatonit/catatonit.spec
  SPECS-EXTENDED/dyninst/dyninst.spec
  SPECS-EXTENDED/podman/podman.spec
  SPECS/busybox/busybox.spec
  SPECS/flannel/flannel.spec
  SPECS/glibc/CVE-2025-0395.patch
  SPECS/glibc/CVE-2025-4802.patch
  SPECS/glibc/glibc.spec
  SPECS/kubernetes/kubernetes.spec
  SPECS/kubevirt/kubevirt.spec
  SPECS/libcap/libcap.spec
  SPECS/libguestfs/libguestfs.spec
  SPECS/rust/rust.spec
  SPECS/supermin/supermin.spec
  SPECS/tini/tini.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, specs-extended, fasttrack/2.0, CVEFixReadyForMaintainerReview

#14054 Revert "[High] Patch python3 for CVE-2025-4138, CVE-2025-4330, CVE-2025-4517, CVE-2025-4516, CVE-2024-12718, CVE-2025-4435, CVE-2023-5752, and CVE-2023-45803"
  SPECS/python3/CVE-2023-45803.patch
  SPECS/python3/CVE-2023-5752.patch
  SPECS/python3/CVE-2025-4138.patch
  SPECS/python3/CVE-2025-4516.patch
  SPECS/python3/python3.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, fasttrack/2.0

#13881 containerd2: add updated multi-snapshotters support patch
  SPECS/containerd2/containerd2.spec
  SPECS/containerd2/multi-snapshotters-support.patch
Labels: Packaging, specs-extended, 3.0-dev

#13899 containerd2: add updated tardev-snapshotter support patch
  SPECS/containerd2/containerd2.spec
  SPECS/containerd2/tardev-support.patch
Labels: Packaging, 3.0-dev

#14051 update network timeout to 20min by default to allow for larger filesi…
  toolkit/tools/internal/network/network.go
Labels: Tools, fasttrack/3.0

#14023 [HIGH] Patch coredns for CVE-2025-47950
  SPECS/coredns/CVE-2025-47950.patch
  SPECS/coredns/coredns.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#14035 Add PR package update check to fasttrack/2.0
  .github/workflows/check-package-update-gate.yml
  .github/workflows/packagelist-gate.csv
Labels: Packaging, fasttrack/2.0

#14030 [Medium] Patch valkey for CVE-2025-27151
  SPECS/valkey/CVE-2025-27151.patch
  SPECS/valkey/valkey.spec
Labels: security, Packaging, 3.0-dev

#13905 [Low] patch elfutils for CVE-2025-1352
  SPECS/elfutils/CVE-2025-1352.patch
  SPECS/elfutils/elfutils.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, 3.0-dev

#12978 Upgrade: ibus to version 1.5.31
  SPECS-EXTENDED/ibus/ibus-1385349-segv-bus-proxy.patch
  SPECS-EXTENDED/ibus/ibus-HEAD.patch
  SPECS-EXTENDED/ibus/ibus-xinput
  SPECS-EXTENDED/ibus/ibus.signatures.json
  SPECS-EXTENDED/ibus/ibus.spec
  SPECS-EXTENDED/ibus/ibus.tar.gz.sum
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#13985 Patch rust for CVE-2025-4574 [Medium]
  SPECS-EXTENDED/389-ds-base/389-ds-base.spec
  SPECS-EXTENDED/ripgrep/ripgrep.spec
  SPECS-EXTENDED/rust-cbindgen/rust-cbindgen.spec
  SPECS-EXTENDED/tardev-snapshotter/tardev-snapshotter.spec
  SPECS/clamav/clamav.spec
  SPECS/cloud-hypervisor-cvm/cloud-hypervisor-cvm.spec
  SPECS/flux/flux.spec
  SPECS/influxdb/influxdb.spec
  SPECS/kata-containers-cc/kata-containers-cc.spec
  SPECS/kata-containers/kata-containers.spec
  SPECS/librsvg2/librsvg2.spec
  SPECS/mesa/mesa.spec
  SPECS/netavark/netavark.spec
  SPECS/rpm-ostree/rpm-ostree.spec
  SPECS/rust/CVE-2025-4574.patch
  SPECS/rust/CVE-2025-4574_1.75.patch
  SPECS/rust/rust-1.75.spec
  SPECS/rust/rust.spec
  SPECS/virtiofsd/virtiofsd.spec
Labels: security, Packaging, ptest, specs-extended, 3.0-dev

#14032 [Medium] Patch nbdkit for CVE-2025-47711 & CVE-2025-47712
  SPECS/nbdkit/CVE-2025-47711.patch
  SPECS/nbdkit/CVE-2025-47712.patch
  SPECS/nbdkit/nbdkit.spec
Labels: security, Packaging, main

#13271 Patch mariadb for CVE-2023-52971[Medium] and Bug 51837515: Fix mariadb package installation broken and import spec from Fedora
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS/mariadb/CVE-2023-52971.patch
  SPECS/mariadb/LICENSE.clustercheck
  SPECS/mariadb/README.mariadb-docs
  SPECS/mariadb/README.md
  SPECS/mariadb/README.wsrep_sst_rsync_tunnel
  SPECS/mariadb/clustercheck.sh
  SPECS/mariadb/mariadb-check-socket.sh
  SPECS/mariadb/mariadb-check-upgrade.sh
  SPECS/mariadb/mariadb-libfmt.patch
  SPECS/mariadb/mariadb-logrotate.patch
  SPECS/mariadb/mariadb-mtr.patch
  SPECS/mariadb/mariadb-ownsetup.patch
  SPECS/mariadb/mariadb-prepare-db-dir.sh
  SPECS/mariadb/mariadb-scripts-common.sh
  SPECS/mariadb/mariadb-scripts.patch
  SPECS/mariadb/mariadb-server-galera.te
  SPECS/mariadb/mariadb-ssl-cypher.patch
  SPECS/mariadb/mariadb.rpmlintrc
  SPECS/mariadb/mariadb.signatures.json
  SPECS/mariadb/mariadb.spec
  SPECS/mariadb/mariadb.tmpfiles.d.in
  SPECS/mariadb/my.cnf.in
  SPECS/mariadb/mysql.service.in
  SPECS/mariadb/mysql@.service.in
  SPECS/mariadb/mysql_config_multilib.sh
  SPECS/mariadb/rh-skipped-tests-arm.list
  SPECS/mariadb/rh-skipped-tests-base.list
  SPECS/mariadb/rh-skipped-tests-ppc.list
  SPECS/mariadb/rh-skipped-tests-s390.list
  SPECS/mariadb/rocksdb-6.8-gcc13.patch
  SPECS/mariadb/wsrep_sst_rsync_tunnel
  cgmanifest.json
Labels: security, Packaging, 3.0-dev

#14089 Upgrade clamav to 1.0.9 to address CVE-2025-20260 [CRITICAL]
  SPECS/clamav/clamav.signatures.json
  SPECS/clamav/clamav.spec
  cgmanifest.json
Labels: security, Packaging, fasttrack/2.0, CVEFixReadyForMaintainerReview

#14088 Upgrade clamav to 1.0.9 to address CVE-2025-20260 [CRITICAL]
  SPECS/clamav/CVE-2022-48579.patch
  SPECS/clamav/clamav.signatures.json
  SPECS/clamav/clamav.spec
  cgmanifest.json
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#14044 [High] Patch protobuf for CVE-2025-4565
  SPECS/protobuf/CVE-2025-4565.patch
  SPECS/protobuf/protobuf.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#13949 Update README.md
  README.md
Labels: 3.0-dev, 3.0

#14122 [HIGH] Patch rubygem-webrick for CVE-2025-6442
  SPECS/rubygem-webrick/CVE-2025-6442.patch
  SPECS/rubygem-webrick/rubygem-webrick.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#14070 gnupg2: Upgrade gnupg2 to 2.4.7
  SPECS/gnupg2/gnupg2.signatures.json
  SPECS/gnupg2/gnupg2.spec
  SPECS/libgpg-error/libgpg-error.signatures.json
  SPECS/libgpg-error/libgpg-error.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, 3.0-dev, stable-release-shiproom

#12622 Upgrade sratom to version 0.6.16
  SPECS-EXTENDED/sratom/drobilla.gpg
  SPECS-EXTENDED/sratom/sratom-0.6.16.tar.xz.sig
  SPECS-EXTENDED/sratom/sratom.signatures.json
  SPECS-EXTENDED/sratom/sratom.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#14091 [MEDIUM] Patch dasel for CVE-2024-45338 & CVE-2025-22872
  SPECS/dasel/CVE-2024-45338.patch
  SPECS/dasel/CVE-2025-22872.patch
  SPECS/dasel/dasel.spec
Labels: security, Packaging, 3.0-dev

#13936 Added cqlsh package to SPECS-EXTENDED
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS-EXTENDED/cqlsh/cqlsh.signatures.json
  SPECS-EXTENDED/cqlsh/cqlsh.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#12846 rasqal: fixed build
  SPECS-EXTENDED/rasqal/define-printf.patch
  SPECS-EXTENDED/rasqal/rasqal-configure-c99-2.patch
  SPECS-EXTENDED/rasqal/rasqal.spec
Labels: Packaging, specs-extended, 3.0-dev

#12624 Upgrade lilv version to 0.24.26
  SPECS-EXTENDED/lilv/drobilla.gpg
  SPECS-EXTENDED/lilv/lilv-0.24.26.tar.xz.sig
  SPECS-EXTENDED/lilv/lilv.signatures.json
  SPECS-EXTENDED/lilv/lilv.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#13903 Fix failures in running firewalld service
  SPECS/dbus-python/0001-Move-python-modules-to-architecture-specific-directo.patch
  SPECS/dbus-python/dbus-python.signatures.json
  SPECS/dbus-python/dbus-python.spec
  SPECS/dbus-python/python39.patch
  SPECS/firewalld/firewalld.spec
  SPECS/firewalld/firewalld_fix_testsuite.patch
  cgmanifest.json
Labels: Packaging, 3.0-dev

#14087 [High] patch pam for CVE-2025-6020
  SPECS/pam/CVE-2025-6020.patch
  SPECS/pam/pam.spec
  SPECS/pam/sync_pam_namespace_module_to_version_1.7.0.patch
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, fasttrack/3.0

#14129 [High] Patch ruby for CVE-2025-6442
  SPECS/ruby/CVE-2025-6442.patch
  SPECS/ruby/ruby.spec
Labels: security, Packaging, fasttrack/3.0

#14126 [HIGH] Patch rubygem-webrick for CVE-2025-6442
  SPECS/rubygem-webrick/CVE-2025-6442.patch
  SPECS/rubygem-webrick/rubygem-webrick.spec
Labels: Packaging, fasttrack/2.0

#14145 [HIGH] Patch msft-golang for CVE-2025-22874 & [MEDIUM] CVE-2025-4673
  SPECS/msft-golang/CVE-2025-22874.patch
  SPECS/msft-golang/CVE-2025-4673.patch
  SPECS/msft-golang/msft-golang.spec
Labels: security, Packaging, fasttrack/2.0
