Repository microsoft/azurelinux, pull requests merged in 2025-01, with the labels that each got.

#11735 Bumped `gcr` to 3.38.1 to fix a build break.
  SPECS-EXTENDED/gcr/gcr.signatures.json
  SPECS-EXTENDED/gcr/gcr.spec
  cgmanifest.json
Labels: Packaging, main, specs-extended

#11738 Bumped `gcr` to 3.38.1 to fix a build break.
  SPECS-EXTENDED/gcr/gcr.signatures.json
  SPECS-EXTENDED/gcr/gcr.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#11796 Fixing RPM macros check.
  .github/workflows/check-manifests.yml
  .github/workflows/check-package-cgmanifest.yml
Labels: fasttrack/3.0

#11793 Updated PR checks to use Python 3.9.
  .github/workflows/check-entangled-specs.yml
  .github/workflows/lint-specs.yml
Labels: Packaging, fasttrack/2.0

#11781 Patch telegraf for CVE-2024-45337 & CVE-2024-45338
  SPECS/telegraf/CVE-2024-45337.patch
  SPECS/telegraf/CVE-2024-45338.patch
  SPECS/telegraf/telegraf.spec
Labels: Packaging, fasttrack/2.0

#11795 Made `PackageBuild.yml` accept arbitrary input sources.
  .pipelines/prchecks/PackageBuildPRCheck.yml
  .pipelines/templates/PackageBuild.yml
  .pipelines/templatesWithCheckout/SodiffCheck.yml
Labels: fasttrack/3.0

#11794 Made `PackageBuild.yml` accept arbitrary input sources.
  .pipelines/prchecks/PackageBuildPRCheck.yml
  .pipelines/templates/PackageBuild.yml
  .pipelines/templatesWithCheckout/SodiffCheck.yml
Labels: fasttrack/2.0

#11575 Remove authselect package from SPECS-EXTENDED
  SPECS-EXTENDED/authselect/authselect.signatures.json
  SPECS-EXTENDED/authselect/authselect.spec
Labels: Packaging

#11730 socat: address CVE-2024-54661
  SPECS/socat/CVE-2024-54661.patch
  SPECS/socat/socat.spec
Labels: security, Packaging, fasttrack/2.0

#11778 Patch containerized-data-importer for CVE-2024-45338
  SPECS/containerized-data-importer/CVE-2024-45338.patch
  SPECS/containerized-data-importer/containerized-data-importer.spec
Labels: Packaging, fasttrack/2.0

#11765 Patch kubernetes for CVE-2024-45338
  SPECS/kubernetes/CVE-2024-45338.patch
  SPECS/kubernetes/kubernetes.spec
Labels: Packaging, fasttrack/2.0

#11409 kernel: enable CONFIG_CRYPTO_DH in aarch64
  SPECS-SIGNED/kernel-64k-signed/kernel-64k-signed.spec
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS-SIGNED/kernel-uki-signed/kernel-uki-signed.spec
  SPECS/kernel-64k/config_aarch64
  SPECS/kernel-64k/kernel-64k.signatures.json
  SPECS/kernel-64k/kernel-64k.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel-uki.spec
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, 3.0-dev

#11817 cert-manager: address CVE-2024-45337
  SPECS/cert-manager/CVE-2024-45337.patch
  SPECS/cert-manager/cert-manager.spec
Labels: security, Packaging, fasttrack/3.0

#11820 gh: patch CVE-2024-45337
  SPECS/gh/CVE-2024-45337.patch
  SPECS/gh/gh.spec
Labels: security, Packaging, fasttrack/3.0

#11819 docker-compose: patch CVE-2024-45337
  SPECS/docker-compose/CVE-2024-45337.patch
  SPECS/docker-compose/docker-compose.spec
Labels: security, Packaging, fasttrack/3.0

#11846 Enabled support of luajit for fluent-bit
  SPECS/fluent-bit/fluent-bit.spec
Labels: Packaging, fasttrack/2.0

#11759 Patch cert-manager for CVE-2024-45338
  SPECS/cert-manager/CVE-2024-45338.patch
  SPECS/cert-manager/cert-manager.spec
Labels: Packaging, fasttrack/2.0

#11764 Patch cni-plugins for CVE-2024-45338
  SPECS/cni-plugins/CVE-2024-45338.patch
  SPECS/cni-plugins/cni-plugins.spec
Labels: Packaging, fasttrack/2.0

#11760 Patch cf-cli for CVE-2024-45338
  SPECS/cf-cli/CVE-2024-45338.patch
  SPECS/cf-cli/cf-cli.spec
Labels: Packaging, fasttrack/2.0

#11779 Patch cri-tools for CVE-2024-45338
  SPECS/cri-tools/CVE-2024-45338.patch
  SPECS/cri-tools/cri-tools.spec
Labels: Packaging, fasttrack/2.0

#11744 Patch multus for CVE-2024-45338
  SPECS/multus/CVE-2024-45338.patch
  SPECS/multus/multus.spec
Labels: Packaging, fasttrack/2.0

#11747 Patch vitess for CVE-2024-45338
  SPECS/vitess/CVE-2024-45338.patch
  SPECS/vitess/vitess.spec
Labels: Packaging, fasttrack/2.0

#11748 Patch packer for CVE-2024-45338
  SPECS/packer/CVE-2024-45338.patch
  SPECS/packer/packer.spec
Labels: Packaging, fasttrack/2.0

#11752 python-jinja2: address CVE-2024-56201, CVE-2024-56326
  SPECS/python-jinja2/CVE-2024-56201.patch
  SPECS/python-jinja2/CVE-2024-56326.patch
  SPECS/python-jinja2/python-jinja2.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, fasttrack/2.0

#11756 Patch kubevirt for CVE-2024-45338
  SPECS/kubevirt/CVE-2024-45338.patch
  SPECS/kubevirt/kubevirt.spec
Labels: Packaging, fasttrack/2.0

#11757 Patch helm for CVE-2024-45338
  SPECS/helm/CVE-2024-45338.patch
  SPECS/helm/helm.spec
Labels: Packaging, fasttrack/2.0

#11789 Fix patch logic & add patches for CVE-2022-4318, CVE-2024-9341 & CVE-2024-45338 in cri-o
  SPECS/cri-o/CVE-2022-1708.patch
  SPECS/cri-o/CVE-2022-4318.patch
  SPECS/cri-o/CVE-2023-44487.patch
  SPECS/cri-o/CVE-2024-21626.patch
  SPECS/cri-o/CVE-2024-45338.patch
  SPECS/cri-o/CVE-2024-9341.patch
  SPECS/cri-o/cri-o.spec
Labels: Packaging, fasttrack/2.0

#11751 Patch prometheus-adapter for CVE-2024-45338
  SPECS/prometheus-adapter/CVE-2024-45338.patch
  SPECS/prometheus-adapter/prometheus-adapter.spec
Labels: Packaging, fasttrack/2.0

#11836 Fix CVE-2025-21613 and CVE-2025-21614 for packer
  SPECS/packer/CVE-2023-45288.patch
  SPECS/packer/CVE-2024-45337.patch
  SPECS/packer/CVE-2025-21613.patch
  SPECS/packer/CVE-2025-21614.nopatch
  SPECS/packer/packer.signatures.json
  SPECS/packer/packer.spec
Labels: Packaging, fasttrack/3.0

#11818 Fix CVE-2024-56732 for harfbuzz
  SPECS/harfbuzz/CVE-2024-56732.patch
  SPECS/harfbuzz/harfbuzz.spec
Labels: Packaging, fasttrack/3.0

#11745 python-jinja2 : addresss CVE-2024-22195, CVE-2024-34064, CVE-2024-56201, CVE-2024-56326
  SPECS/python-jinja2/CVE-2024-22195.patch
  SPECS/python-jinja2/CVE-2024-34064.patch
  SPECS/python-jinja2/CVE-2024-56201.patch
  SPECS/python-jinja2/CVE-2024-56326.patch
  SPECS/python-jinja2/python-jinja2.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, fasttrack/3.0

#11736 iperf3: address CVE-2024-53580
  SPECS/iperf3/CVE-2024-53580.patch
  SPECS/iperf3/iperf3.spec
Labels: Packaging, fasttrack/3.0

#11729 socat: address CVE-2024-54661
  SPECS/socat/CVE-2024-54661.patch
  SPECS/socat/socat.spec
Labels: security, Packaging, fasttrack/3.0

#11849 add arm64 fips image definition
  toolkit/imageconfigs/marketplace-gen2-aarch64-fips.json
Labels: Schema, 3.0-dev

#11692 Enable DRM Acceleration and Intel VPU
  SPECS-SIGNED/kernel-64k-signed/kernel-64k-signed.spec
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS-SIGNED/kernel-uki-signed/kernel-uki-signed.spec
  SPECS/kernel-64k/kernel-64k.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/kernel-uki.spec
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, 3.0-dev, 3.0

#11811 Added CodeQL configuration to exclude external sources.
  .CodeQL.yml
Labels: 3.0-dev

#11841 Identify and Update versions of MOFED dependency SPECS that are present in Azure Linux core
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS/mlnx-tools/mlnx-tools.signatures.json
  SPECS/mlnx-tools/mlnx-tools.spec
  SPECS/ofed-docs/ofed-docs.signatures.json
  SPECS/ofed-docs/ofed-docs.spec
  SPECS/ofed-scripts/ofed-scripts.signatures.json
  SPECS/ofed-scripts/ofed-scripts.spec
  SPECS/openmpi/openmpi.signatures.json
  SPECS/openmpi/openmpi.spec
  SPECS/perftest/perftest.signatures.json
  SPECS/perftest/perftest.spec
  SPECS/python-prometheus_client/0001-Remove-the-bundled-decorator-package.patch
  SPECS/python-prometheus_client/python-prometheus_client.signatures.json
  SPECS/python-prometheus_client/python-prometheus_client.spec
  cgmanifest.json
Labels: Packaging, Tools, specs-extended, 3.0-dev, 3.0

#11804 Fix CVE-2024-10220 for kubernetes
  SPECS/kubernetes/CVE-2024-10220.patch
  SPECS/kubernetes/kubernetes.spec
Labels: Packaging, fasttrack/2.0

#11743 Patch keda for CVE-2024-45338
  SPECS/keda/CVE-2024-45338.patch
  SPECS/keda/keda.spec
Labels: Packaging, fasttrack/2.0

#11315 Adding systemd patch for CVE-2023-7008
  SPECS-SIGNED/systemd-boot-signed/systemd-boot-signed.spec
  SPECS/systemd/CVE-2023-7008.patch
  SPECS/systemd/systemd.spec
Labels: Packaging, fasttrack/3.0

#11914 Fix shadow-utils detection in imager as well as validator
  toolkit/tools/imageconfigvalidator/imageconfigvalidator.go
  toolkit/tools/imagegen/installutils/installutils.go
  toolkit/tools/imagegen/installutils/installutils_test.go
Labels: Tools, 3.0-dev

#11921 msft-golang: upgrade version 1.22.10 -> 1.23.3
  SPECS/msft-golang/msft-golang.signatures.json
  SPECS/msft-golang/msft-golang.spec
  cgmanifest.json
Labels: Packaging, fasttrack/2.0

#11933 cmake: patch CVE-2024-11053
  SPECS/cmake/CVE-2024-11053.patch
  SPECS/cmake/cmake.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, fasttrack/3.0

#11938 rsync: upgrade to 3.4.1 to fix multiple CVEs
  SPECS/rsync/rsync.signatures.json
  SPECS/rsync/rsync.spec
  cgmanifest.json
Labels: Packaging, fasttrack/3.0

#11939 rsync: upgrade to 3.4.1 to fix multiple CVEs
  SPECS/rsync/rsync.signatures.json
  SPECS/rsync/rsync.spec
  cgmanifest.json
Labels: Packaging, fasttrack/2.0

#11926 cmake: patch CVE-2024-11053
  SPECS/cmake/CVE-2024-11053.patch
  SPECS/cmake/cmake.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, fasttrack/2.0

#11639 Upgrade: python-rpmfluff version to 0.6.5
  SPECS-EXTENDED/python-rpmfluff/python-rpmfluff.signatures.json
  SPECS-EXTENDED/python-rpmfluff/python-rpmfluff.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#11156 Add Valkey Container
  .pipelines/containerSourceData/valkey/Dockerfile-Valkey
  .pipelines/containerSourceData/valkey/configuration-files/valkey-docker-entrypoint.sh
  .pipelines/containerSourceData/valkey/valkey.name
  .pipelines/containerSourceData/valkey/valkey.pkg
Labels: 3.0-dev, Container

#11699 Upgraded xdg-utils to version 1.2.1
  SPECS-EXTENDED/xdg-utils/0001-open-for-post-1.1.3-development.patch
  SPECS-EXTENDED/xdg-utils/0002-xdg-open-better-pcmanfm-check-BR106636-BR106161.patch
  SPECS-EXTENDED/xdg-utils/xdg-utils-git_checkout.sh
  SPECS-EXTENDED/xdg-utils/xdg-utils.signatures.json
  SPECS-EXTENDED/xdg-utils/xdg-utils.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#11714 Update perl-Lingua-EN-Inflect to version 1.905-1
  SPECS-EXTENDED/perl-Lingua-EN-Inflect/perl-Lingua-EN-Inflect.signatures.json
  SPECS-EXTENDED/perl-Lingua-EN-Inflect/perl-Lingua-EN-Inflect.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#11698 Update perl-IPC-Run3 to version 0.049-1
  SPECS-EXTENDED/perl-IPC-Run3/0001-test-and-fix-for-RT-52317-Calling-run3-garbles-STDIN.patch
  SPECS-EXTENDED/perl-IPC-Run3/perl-IPC-Run3.signatures.json
  SPECS-EXTENDED/perl-IPC-Run3/perl-IPC-Run3.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#11923 Fix CVE-2025-22134 in vim for 3.0
  SPECS/vim/CVE-2025-22134.patch
  SPECS/vim/vim.spec
Labels: Packaging, fasttrack/3.0

#11932 CVE-2024-30161: qtbase upgrades to version 6.6.3
  SPECS/qtbase/qtbase.signatures.json
  SPECS/qtbase/qtbase.spec
  cgmanifest.json
Labels: Packaging, fasttrack/3.0

#11920 Patch tensorflow for CVE-2024-35195
  SPECS/tensorflow/CVE-2024-35195.patch
  SPECS/tensorflow/tensorflow.spec
Labels: Packaging, fasttrack/3.0

#11479 Bphilip/add mofed and dependencies
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS-SIGNED/fwctl-signed/fwctl-signed.spec
  SPECS-SIGNED/iser-signed/iser-signed.spec
  SPECS-SIGNED/isert-signed/isert-signed.spec
  SPECS-SIGNED/knem-signed/knem-modules-signed.spec
  SPECS-SIGNED/mft_kernel-signed/mft_kernel-signed.spec
  SPECS-SIGNED/mlnx-nfsrdma-signed/mlnx-nfsrdma-signed.spec
  SPECS-SIGNED/mlnx-ofa_kernel-signed/mlnx-ofa_kernel-modules-signed.spec
  SPECS-SIGNED/srp-signed/srp-signed.spec
  SPECS-SIGNED/xpmem-signed/xpmem-modules-signed.spec
  SPECS/fwctl/fwctl.signatures.json
  SPECS/fwctl/fwctl.spec
  SPECS/ibarr/ibarr.signatures.json
  SPECS/ibarr/ibarr.spec
  SPECS/ibsim/ibsim.signatures.json
  SPECS/ibsim/ibsim.spec
  SPECS/iser/iser.signatures.json
  SPECS/iser/iser.spec
  SPECS/isert/isert.signatures.json
  SPECS/isert/isert.spec
  SPECS/knem/knem.signatures.json
  SPECS/knem/knem.spec
  SPECS/mft_kernel/mft_kernel.signatures.json
  SPECS/mft_kernel/mft_kernel.spec
  SPECS/mlnx-ethtool/mlnx-ethtool.signatures.json
  SPECS/mlnx-ethtool/mlnx-ethtool.spec
  SPECS/mlnx-iproute2/mlnx-iproute2.signatures.json
  SPECS/mlnx-iproute2/mlnx-iproute2.spec
  SPECS/mlnx-nfsrdma/mlnx-nfsrdma.signatures.json
  SPECS/mlnx-nfsrdma/mlnx-nfsrdma.spec
  SPECS/mlnx-ofa_kernel/mlnx-ofa_kernel.signatures.json
  SPECS/mlnx-ofa_kernel/mlnx-ofa_kernel.spec
  SPECS/mlx-steering-dump/mlx-steering-dump.signatures.json
  SPECS/mlx-steering-dump/mlx-steering-dump.spec
  SPECS/multiperf/multiperf.signatures.json
  SPECS/multiperf/multiperf.spec
  SPECS/rshim/rshim.signatures.json
  SPECS/rshim/rshim.spec
  SPECS/sockperf/sockperf.signatures.json
  SPECS/sockperf/sockperf.spec
  SPECS/srp/srp.signatures.json
  SPECS/srp/srp.spec
  SPECS/xpmem-lib/xpmem-lib.signatures.json
  SPECS/xpmem-lib/xpmem-lib.spec
  SPECS/xpmem/xpmem.signatures.json
  SPECS/xpmem/xpmem.spec
  cgmanifest.json
  toolkit/scripts/check_entangled_specs.py
  toolkit/scripts/spec_source_attributions.py
Labels: Packaging, Tools, 3.0-dev

#11948 Patch CVE-2024-50349 and CVE-2024-52006 in git
  SPECS/git/git.signatures.json
  SPECS/git/git.spec
  cgmanifest.json
Labels: Packaging, fasttrack/2.0

#11952 Fix CVE-2025-22134 in vim for 2.0
  SPECS/vim/CVE-2025-22134.patch
  SPECS/vim/vim.spec
Labels: security, Packaging, fasttrack/2.0

#11935 Added a patch to address CVE-2024-56732 for qtbase.
  SPECS/qtbase/CVE-2024-56732.patch
  SPECS/qtbase/qtbase.spec
Labels: Packaging, fasttrack/3.0

#11983 Add logic to PR checker to detect kernel upgrade for OOT module specs
  SPECS/fwctl/fwctl.spec
  SPECS/iser/iser.spec
  SPECS/isert/isert.spec
  SPECS/knem/knem.spec
  SPECS/mft_kernel/mft_kernel.spec
  SPECS/mlnx-nfsrdma/mlnx-nfsrdma.spec
  SPECS/mlnx-ofa_kernel/mlnx-ofa_kernel.spec
  SPECS/srp/srp.spec
  SPECS/xpmem/xpmem.spec
  toolkit/scripts/check_entangled_specs.py
Labels: Packaging, Tools, 3.0-dev

#11981 Fix CVE-2023-3164 in libtiff package for 3.0
  SPECS/libtiff/CVE-2023-3164.patch
  SPECS/libtiff/libtiff.spec
Labels: Packaging, fasttrack/3.0

#11831 Add ucx to PMC's extended repo
  SPECS-EXTENDED/ucx/ucx.signatures.json
  SPECS-EXTENDED/ucx/ucx.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#11810 Add rdma-core to PMC's extended repo
  SPECS-EXTENDED/rdma-core/rdma-core.signatures.json
  SPECS-EXTENDED/rdma-core/rdma-core.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#11551 Add kernel-srpm-macros package
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS/kernel-srpm-macros/brp-kmod-restore-perms
  SPECS/kernel-srpm-macros/brp-kmod-set-exec-bit
  SPECS/kernel-srpm-macros/find-provides.ksyms
  SPECS/kernel-srpm-macros/find-requires.ksyms
  SPECS/kernel-srpm-macros/firmware.prov
  SPECS/kernel-srpm-macros/kabi.attr
  SPECS/kernel-srpm-macros/kabi.sh
  SPECS/kernel-srpm-macros/kernel-srpm-macros.signatures.json
  SPECS/kernel-srpm-macros/kernel-srpm-macros.spec
  SPECS/kernel-srpm-macros/kmod.attr
  SPECS/kernel-srpm-macros/kmodtool
  SPECS/kernel-srpm-macros/macros.kernel-srpm
  SPECS/kernel-srpm-macros/macros.kmp
  SPECS/kernel-srpm-macros/modalias.attr
  SPECS/kernel-srpm-macros/modalias.prov
  SPECS/kernel-srpm-macros/provided_ksyms.attr
  SPECS/kernel-srpm-macros/required_ksyms.attr
  SPECS/kernel-srpm-macros/rpmsort
  SPECS/kernel-srpm-macros/symset-table
  cgmanifest.json
Labels: Packaging, 3.0-dev

#11767 Fix CVE-2024-45338 in multiple packages
  SPECS/application-gateway-kubernetes-ingress/CVE-2024-45338.patch
  SPECS/application-gateway-kubernetes-ingress/application-gateway-kubernetes-ingress.spec
  SPECS/cert-manager/CVE-2024-45338.patch
  SPECS/cert-manager/cert-manager.spec
  SPECS/cf-cli/CVE-2024-45338.patch
  SPECS/cf-cli/cf-cli.spec
  SPECS/containerized-data-importer/CVE-2024-45338.patch
  SPECS/containerized-data-importer/containerized-data-importer.spec
  SPECS/cri-tools/CVE-2024-45338.patch
  SPECS/cri-tools/cri-tools.spec
  SPECS/docker-buildx/CVE-2024-45338.patch
  SPECS/docker-buildx/docker-buildx.spec
  SPECS/docker-compose/CVE-2024-45338.patch
  SPECS/docker-compose/docker-compose.spec
  SPECS/gh/CVE-2024-45338.patch
  SPECS/gh/gh.spec
  SPECS/helm/CVE-2024-45338.patch
  SPECS/helm/helm.spec
  SPECS/ig/CVE-2024-45338.patch
  SPECS/ig/ig.spec
  SPECS/influxdb/CVE-2024-45338.patch
  SPECS/influxdb/influxdb.spec
  SPECS/keda/CVE-2024-45338.patch
  SPECS/keda/keda.spec
  SPECS/kube-vip-cloud-provider/CVE-2024-45338.patch
  SPECS/kube-vip-cloud-provider/kube-vip-cloud-provider.spec
  SPECS/kubernetes/CVE-2024-45338.patch
  SPECS/kubernetes/kubernetes.spec
  SPECS/kubevirt/CVE-2024-45338.patch
  SPECS/kubevirt/kubevirt.spec
  SPECS/multus/CVE-2024-45338.patch
  SPECS/multus/multus.spec
  SPECS/prometheus-adapter/CVE-2024-45338.patch
  SPECS/prometheus-adapter/prometheus-adapter.spec
  SPECS/sriov-network-device-plugin/CVE-2024-45338.patch
  SPECS/sriov-network-device-plugin/sriov-network-device-plugin.spec
  SPECS/telegraf/CVE-2024-45338.patch
  SPECS/telegraf/telegraf.spec
Labels: security, Packaging, fasttrack/3.0

#11993 mofed and deps signed spec cleanup
  SPECS-SIGNED/fwctl-signed/fwctl-signed.spec
  SPECS-SIGNED/iser-signed/iser-signed.spec
  SPECS-SIGNED/isert-signed/isert-signed.spec
  SPECS-SIGNED/knem-signed/knem-modules-signed.spec
  SPECS-SIGNED/mft_kernel-signed/mft_kernel-signed.spec
  SPECS-SIGNED/mlnx-nfsrdma-signed/mlnx-nfsrdma-signed.spec
  SPECS-SIGNED/mlnx-ofa_kernel-signed/mlnx-ofa_kernel-modules-signed.spec
  SPECS-SIGNED/srp-signed/srp-signed.spec
  SPECS-SIGNED/xpmem-signed/xpmem-modules-signed.spec
  SPECS/fwctl/fwctl.spec
  SPECS/iser/iser.spec
  SPECS/isert/isert.spec
  SPECS/knem/knem.spec
  SPECS/mft_kernel/mft_kernel.spec
  SPECS/mlnx-nfsrdma/mlnx-nfsrdma.spec
  SPECS/mlnx-ofa_kernel/mlnx-ofa_kernel.spec
  SPECS/srp/srp.spec
  SPECS/xpmem/xpmem.spec
Labels: Packaging, 3.0

#11982 iptables: add back missing kernel modules for iptables
  SPECS/iptables/iptables.conf
  SPECS/iptables/iptables.signatures.json
  SPECS/iptables/iptables.spec
Labels: Packaging, 3.0-dev

#11792 Disable debug preemption in x86_64
  SPECS-SIGNED/kernel-64k-signed/kernel-64k-signed.spec
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS-SIGNED/kernel-uki-signed/kernel-uki-signed.spec
  SPECS/kernel-64k/kernel-64k.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/kernel-uki.spec
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, 3.0-dev, stable-release-shiproom

#12016 Cherry-Pick ipTables related fixes to fasttrack.
  SPECS-SIGNED/kernel-64k-signed/kernel-64k-signed.spec
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS-SIGNED/kernel-uki-signed/kernel-uki-signed.spec
  SPECS/hyperv-daemons/hyperv-daemons.signatures.json
  SPECS/hyperv-daemons/hyperv-daemons.spec
  SPECS/iptables/iptables.conf
  SPECS/iptables/iptables.signatures.json
  SPECS/iptables/iptables.spec
  SPECS/kernel-64k/config_aarch64
  SPECS/kernel-64k/kernel-64k.signatures.json
  SPECS/kernel-64k/kernel-64k.spec
  SPECS/kernel-headers/kernel-headers.signatures.json
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel-uki.spec
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/Dockerfile
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_temp_tools.sh
Labels: Packaging, Tools, fasttrack/3.0

#12021 influxdb: Fix CVE-2024-28180 [Medium]
  SPECS/influxdb/CVE-2024-28180.patch
  SPECS/influxdb/influxdb.spec
Labels: security, Packaging, fasttrack/2.0

#12013 cert-manager: [Medium] patch for CVE-2024-12401
  SPECS/cert-manager/CVE-2024-12401.patch
  SPECS/cert-manager/cert-manager.spec
Labels: Packaging, fasttrack/2.0

#11927 Bump go from 1.20 to 1.21 in `.github/workflows/quickstart_2.0.yml`
  .github/workflows/quickstart_2.0.yml
Labels: Packaging, 3.0-dev

#12009 Patch terraform to fix CVE-2023-0475
  SPECS/terraform/CVE-2023-0475.patch
  SPECS/terraform/terraform.spec
Labels: Packaging, fasttrack/2.0

#12045 Add patch to mlnx-ofa_kernel module for IBT compatibility
  SPECS/mlnx-ofa_kernel/001-fix-module-init-for-ibt.patch
  SPECS/mlnx-ofa_kernel/mlnx-ofa_kernel.spec
Labels: Packaging, 3.0-dev

#11934 Add containerd2 tardev-snapshotter patch
  SPECS/containerd2/add-tardev-support.patch
  SPECS/containerd2/containerd2.spec
Labels: Packaging, 3.0-dev

#12032 [3.0] remove opus and opusfile
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS-EXTENDED/gstreamer1-plugins-base/gstreamer1-plugins-base.spec
  SPECS-EXTENDED/opus/opus.signatures.json
  SPECS-EXTENDED/opus/opus.spec
  SPECS-EXTENDED/opus/rfc6716.txt
  SPECS-EXTENDED/opus/rfc8251.txt
  SPECS-EXTENDED/opusfile/opusfile.signatures.json
  SPECS-EXTENDED/opusfile/opusfile.spec
  SPECS-EXTENDED/sox/sox.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#12036 [2.0] remove extended packages opus and opusfile
  SPECS-EXTENDED/gstreamer1-plugins-base/gstreamer1-plugins-base.spec
  SPECS-EXTENDED/opus/opus.signatures.json
  SPECS-EXTENDED/opus/opus.spec
  SPECS-EXTENDED/opus/rfc6716.txt
  SPECS-EXTENDED/opus/rfc8251.txt
  SPECS-EXTENDED/opusfile/opusfile.signatures.json
  SPECS-EXTENDED/opusfile/opusfile.spec
  SPECS-EXTENDED/sox/sox.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: Packaging, main, specs-extended

#12031 remove fdk-aac-free [3.0]
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS-EXTENDED/fdk-aac-free/fdk-aac-free.signatures.json
  SPECS-EXTENDED/fdk-aac-free/fdk-aac-free.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#12030 Remove FDK-AAC-FREE
  SPECS-EXTENDED/fdk-aac-free/fdk-aac-free.signatures.json
  SPECS-EXTENDED/fdk-aac-free/fdk-aac-free.spec
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  cgmanifest.json
Labels: Packaging, main, specs-extended

#12025 Change kernel-mft rpm name to mft_kernel
  SPECS-SIGNED/mft_kernel-signed/mft_kernel-signed.spec
  SPECS/mft_kernel/mft_kernel.spec
  cgmanifest.json
Labels: Packaging, 3.0-dev

#12003 pytorch: patch for CVE-2024-27319, CVE-2021-22918
  SPECS/pytorch/CVE-2021-22918.patch
  SPECS/pytorch/CVE-2024-27319.patch
  SPECS/pytorch/pytorch.spec
Labels: Packaging, fasttrack/3.0

#12008 Patch gh to fix CVE-2024-53858 and CVE-2024-53859
  SPECS/gh/CVE-2024-53858.nopatch
  SPECS/gh/CVE-2024-53859.patch
  SPECS/gh/gh.spec
Labels: Packaging, fasttrack/3.0

#12019 influxdb: Fix CVE-2024-28180
  SPECS/influxdb/CVE-2024-28180.patch
  SPECS/influxdb/influxdb.spec
Labels: security, Packaging, fasttrack/3.0

#12040 cni : Fix CVE-2022-29526 and CVE-2024-45338
  SPECS/cni/CVE-2022-29526.patch
  SPECS/cni/CVE-2024-45338.patch
  SPECS/cni/cni.spec
Labels: security, Packaging, fasttrack/3.0

#12046 xerces-c : Fix CVE-2024-23807
  SPECS/xerces-c/CVE-2024-23807.patch
  SPECS/xerces-c/xerces-c.signatures.json
  SPECS/xerces-c/xerces-c.spec
  cgmanifest.json
Labels: Packaging, fasttrack/3.0

#12058 [Medium] patch vim to fix CVE-2025-24014
  SPECS/vim/CVE-2025-24014.patch
  SPECS/vim/vim.spec
Labels: Packaging, fasttrack/3.0

#12060 libxml2: Fix CVE-2023-45322 and CVE-2024-34459
  SPECS/libxml2/CVE-2023-45322.patch
  SPECS/libxml2/CVE-2024-34459.patch
  SPECS/libxml2/libxml2.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, fasttrack/3.0

#12061 [Medium] patch curl for CVE-2024-9681
  SPECS/curl/CVE-2024-9681.patch
  SPECS/curl/curl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, fasttrack/3.0

#12066 [3.0] Fix CVE-2023-39325 and CVE-2023-44487 for containerized-data-importer
  SPECS/containerized-data-importer/CVE-2023-39325.patch
  SPECS/containerized-data-importer/CVE-2023-44487.patch
  SPECS/containerized-data-importer/containerized-data-importer.spec
Labels: Packaging, fasttrack/3.0

#12072 rollback mft_kernel rpm name and add provides for kernel-mft
  SPECS-SIGNED/mft_kernel-signed/mft_kernel-signed.spec
  SPECS/mft_kernel/mft_kernel.spec
Labels: Packaging, 3.0-dev

#12089 Upgrade cert-manager to 1.12.15 - to fix CVE-2024-12401
  SPECS/cert-manager/CVE-2024-45337.patch
  SPECS/cert-manager/cert-manager.spec
Labels: Packaging, fasttrack/3.0

#12057 [Medium] patch vim to fix CVE-2025-24014
  SPECS/vim/CVE-2025-24014.patch
  SPECS/vim/vim.spec
Labels: Packaging, fasttrack/2.0

#12044 [Medium] Patch cmake to fix CVE-2024-9681
  SPECS/cmake/CVE-2024-9681.patch
  SPECS/cmake/cmake.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, fasttrack/2.0

#12048 xerces-c: Fix CVE-2024-23807
  SPECS/xerces-c/CVE-2024-23807.patch
  SPECS/xerces-c/xerces-c.spec
  cgmanifest.json
Labels: Packaging, fasttrack/2.0

#12091 Fix CVE-2024-53263 in git-lfs
  SPECS/git-lfs/CVE-2024-53263.patch
  SPECS/git-lfs/git-lfs.spec
Labels: Packaging, fasttrack/2.0

#12098 Patch libxml2 for CVE-2022-49043
  SPECS/libxml2/CVE-2022-49043.patch
  SPECS/libxml2/libxml2.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, fasttrack/2.0

#11999 Ceph CVE Fixes - Removing "jaegertracing/opentelemetry-cpp" as it was not being built
  SPECS/ceph/ceph.spec
Labels: Packaging, fasttrack/3.0

#12088 Fix CVE-2024-53263 in git-lfs
  SPECS/git-lfs/git-lfs.signatures.json
  SPECS/git-lfs/git-lfs.spec
  cgmanifest.json
Labels: Packaging, fasttrack/3.0

#12090 Patch nodejs for CVE-2025-23083
  SPECS/nodejs/CVE-2025-23083.patch
  SPECS/nodejs/nodejs.spec
Labels: Packaging, fasttrack/3.0

#12020 [Medium] cmake: Fix CVE-2024-7264 and CVE-2024-9681
  SPECS/cmake/CVE-2024-7264.patch
  SPECS/cmake/CVE-2024-9681.patch
  SPECS/cmake/cmake.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, fasttrack/3.0

#11895 Added logging for missed pre-cacher download error.
  toolkit/tools/precacher/precacher.go
Labels: Tools, 3.0-dev

#11897 Added logging for missed pre-cacher download error.
  toolkit/tools/precacher/precacher.go
Labels: Tools, main

#11693 Update perl-File-ShareDir-Install to version 0.14
  SPECS-EXTENDED/perl-File-ShareDir-Install/perl-File-ShareDir-Install.signatures.json
  SPECS-EXTENDED/perl-File-ShareDir-Install/perl-File-ShareDir-Install.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#11723 ocaml-markup: update to 1.0.3
  SPECS-EXTENDED/ocaml-markup/ocaml-markup.signatures.json
  SPECS-EXTENDED/ocaml-markup/ocaml-markup.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#12050 Update URL for ostree
  SPECS/ostree/ostree.spec
Labels: Packaging, main

#12051 Update URL for ostree
  SPECS/ostree/ostree.spec
Labels: Packaging, 3.0-dev

#11504 Add LZ4 Compression Support for PostgreSQL
  SPECS/postgresql/postgresql.spec
Labels: Packaging, 3.0

#11205 kata-containers(-cc): Update to 3.2.0.azl4
  SPECS/kata-containers-cc/kata-containers-cc.signatures.json
  SPECS/kata-containers-cc/kata-containers-cc.spec
  SPECS/kata-containers/kata-containers.signatures.json
  SPECS/kata-containers/kata-containers.spec
  cgmanifest.json
Labels: Packaging, 3.0-dev

#11991 Build PCI_HYPERV as built-in
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, main

#11992 Build PCI_HYPERV as a built-in
  SPECS-SIGNED/kernel-64k-signed/kernel-64k-signed.spec
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS-SIGNED/kernel-uki-signed/kernel-uki-signed.spec
  SPECS/kernel-64k/config_aarch64
  SPECS/kernel-64k/kernel-64k.signatures.json
  SPECS/kernel-64k/kernel-64k.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel-uki.spec
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, 3.0-dev

#12128 [Medium] patch openmpi to fix CVE-2022-47022
  SPECS/openmpi/CVE-2022-47022.patch
  SPECS/openmpi/openmpi.spec
Labels: Packaging, fasttrack/2.0

#12129 Patch rook for CVE-2024-28180
  SPECS/rook/CVE-2024-28180.patch
  SPECS/rook/rook.spec
Labels: Packaging, fasttrack/2.0

#11007 Fix multiple CVE in Skopeo
  SPECS/skopeo/CVE-2023-45288.patch
  SPECS/skopeo/CVE-2024-9676.patch
  SPECS/skopeo/skopeo.spec
Labels: security, Packaging, 3.0-dev, fasttrack/3.0

#12130 Patch containerized-data-importer for CVE-2024-28180
  SPECS/containerized-data-importer/CVE-2024-28180.patch
  SPECS/containerized-data-importer/containerized-data-importer.spec
Labels: Packaging, fasttrack/3.0

#12138 Bphilip/rename mlnx ofa kernel
  SPECS-SIGNED/knem-modules-signed/knem-modules-signed.spec
  SPECS-SIGNED/mlnx-ofa_kernel-modules-signed/mlnx-ofa_kernel-modules-signed.spec
  SPECS-SIGNED/xpmem-modules-signed/xpmem-modules-signed.spec
  toolkit/scripts/check_entangled_specs.py
Labels: Packaging, Tools, 3.0-dev

#12121 python-pysocks: remove package from extended
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS-EXTENDED/python-pysocks/python-pysocks.signatures.json
  SPECS-EXTENDED/python-pysocks/python-pysocks.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#11768 Upgraded metis to version 5.1.0.3
  SPECS-EXTENDED/metis/metis-GKREGEX-GKRAND-LIBSUFFIX-fix.patch
  SPECS-EXTENDED/metis/metis-libmetis.patch
  SPECS-EXTENDED/metis/metis-pcre2.patch
  SPECS-EXTENDED/metis/metis-shared-GKlib.patch
  SPECS-EXTENDED/metis/metis-width-datatype.patch
  SPECS-EXTENDED/metis/metis.signatures.json
  SPECS-EXTENDED/metis/metis.spec
  SPECS-EXTENDED/metis/metis_lib64.patch
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#12136 Patch moby-containerd for CVE-2024-28180 [Medium]
  SPECS/moby-containerd/CVE-2024-28180.patch
  SPECS/moby-containerd/moby-containerd.spec
Labels: Packaging, fasttrack/2.0

#12147 Patch CVE-2023-27043 in python3 by patching
  SPECS/python3/CVE-2023-27043.patch
  SPECS/python3/python3.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, fasttrack/3.0

#10619 Upgrade fluent-bit to 3.0.6
  SPECS/fluent-bit/CVE-2024-26455.patch
  SPECS/fluent-bit/CVE-2024-28182.patch
  SPECS/fluent-bit/fix_issue_8025.patch
  SPECS/fluent-bit/fluent-bit.signatures.json
  SPECS/fluent-bit/fluent-bit.spec
  SPECS/fluent-bit/in_emitter_fix_issue_8198.patch
  cgmanifest.json
Labels: Packaging, main, stable-release-shiproom

#12154 Add ipmitool support to kernel-64k
  SPECS-SIGNED/fwctl-signed/fwctl-signed.spec
  SPECS-SIGNED/iser-signed/iser-signed.spec
  SPECS-SIGNED/isert-signed/isert-signed.spec
  SPECS-SIGNED/kernel-64k-signed/kernel-64k-signed.spec
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS-SIGNED/kernel-uki-signed/kernel-uki-signed.spec
  SPECS-SIGNED/knem-modules-signed/knem-modules-signed.spec
  SPECS-SIGNED/mft_kernel-signed/mft_kernel-signed.spec
  SPECS-SIGNED/mlnx-nfsrdma-signed/mlnx-nfsrdma-signed.spec
  SPECS-SIGNED/mlnx-ofa_kernel-modules-signed/mlnx-ofa_kernel-modules-signed.spec
  SPECS-SIGNED/srp-signed/srp-signed.spec
  SPECS-SIGNED/xpmem-modules-signed/xpmem-modules-signed.spec
  SPECS/fwctl/fwctl.spec
  SPECS/iser/iser.spec
  SPECS/isert/isert.spec
  SPECS/kernel-64k/config_aarch64
  SPECS/kernel-64k/kernel-64k.signatures.json
  SPECS/kernel-64k/kernel-64k.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/kernel-uki.spec
  SPECS/kernel/kernel.spec
  SPECS/knem/knem.spec
  SPECS/mft_kernel/mft_kernel.spec
  SPECS/mlnx-nfsrdma/mlnx-nfsrdma.spec
  SPECS/mlnx-ofa_kernel/mlnx-ofa_kernel.spec
  SPECS/srp/srp.spec
  SPECS/xpmem/xpmem.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, 3.0-dev, 3.0

#12167 upgrade symcrypt and scossl
  SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.signatures.json
  SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.spec
  SPECS/SymCrypt/SymCrypt.signatures.json
  SPECS/SymCrypt/SymCrypt.spec
  SPECS/SymCrypt/symcrypt-build-environment-variables-v103.6.0.sh
  SPECS/SymCrypt/symcrypt-build-environment-variables-v103.8.0.sh
  cgmanifest.json
Labels: Packaging, 3.0-dev

#12176 openssl: move SymCrypt and SymCrypt-OpenSSL Recommends from main package to libs
  SPECS/openssl/openssl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, 3.0-dev

#12095 Support for Prometheus exporter in HAProxy
  SPECS/haproxy/haproxy.spec
Labels: Packaging, 3.0-dev

#12062 Upgrade dmidecode to 3.6
  SPECS/dmidecode/dmidecode.signatures.json
  SPECS/dmidecode/dmidecode.spec
  cgmanifest.json
Labels: Packaging, 3.0-dev

#12178 Performance improvements via Kernel configuration parameters
  SPECS-SIGNED/fwctl-signed/fwctl-signed.spec
  SPECS-SIGNED/iser-signed/iser-signed.spec
  SPECS-SIGNED/isert-signed/isert-signed.spec
  SPECS-SIGNED/kernel-64k-signed/kernel-64k-signed.spec
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS-SIGNED/kernel-uki-signed/kernel-uki-signed.spec
  SPECS-SIGNED/knem-modules-signed/knem-modules-signed.spec
  SPECS-SIGNED/mft_kernel-signed/mft_kernel-signed.spec
  SPECS-SIGNED/mlnx-nfsrdma-signed/mlnx-nfsrdma-signed.spec
  SPECS-SIGNED/mlnx-ofa_kernel-modules-signed/mlnx-ofa_kernel-modules-signed.spec
  SPECS-SIGNED/srp-signed/srp-signed.spec
  SPECS-SIGNED/xpmem-modules-signed/xpmem-modules-signed.spec
  SPECS/fwctl/fwctl.spec
  SPECS/iser/iser.spec
  SPECS/isert/isert.spec
  SPECS/kernel-64k/kernel-64k.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/kernel-uki.spec
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  SPECS/knem/knem.spec
  SPECS/mft_kernel/mft_kernel.spec
  SPECS/mlnx-nfsrdma/mlnx-nfsrdma.spec
  SPECS/mlnx-ofa_kernel/mlnx-ofa_kernel.spec
  SPECS/srp/srp.spec
  SPECS/xpmem/xpmem.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, Tools, 3.0-dev

#12179 Add missing modules for python-conda-package-handling ptest
  SPECS/python-conda-package-handling/python-conda-package-handling.spec
Labels: Packaging, 3.0-dev

#12177 Fix ptest for pugixml
  SPECS/pugixml/pugixml.spec
Labels: Packaging, 3.0-dev

#12183 Enable NUMA balancing and UCLAMP task feature
  SPECS-SIGNED/fwctl-signed/fwctl-signed.spec
  SPECS-SIGNED/iser-signed/iser-signed.spec
  SPECS-SIGNED/isert-signed/isert-signed.spec
  SPECS-SIGNED/kernel-64k-signed/kernel-64k-signed.spec
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS-SIGNED/kernel-uki-signed/kernel-uki-signed.spec
  SPECS-SIGNED/knem-modules-signed/knem-modules-signed.spec
  SPECS-SIGNED/mft_kernel-signed/mft_kernel-signed.spec
  SPECS-SIGNED/mlnx-nfsrdma-signed/mlnx-nfsrdma-signed.spec
  SPECS-SIGNED/mlnx-ofa_kernel-modules-signed/mlnx-ofa_kernel-modules-signed.spec
  SPECS-SIGNED/srp-signed/srp-signed.spec
  SPECS-SIGNED/xpmem-modules-signed/xpmem-modules-signed.spec
  SPECS/fwctl/fwctl.spec
  SPECS/iser/iser.spec
  SPECS/isert/isert.spec
  SPECS/kernel-64k/kernel-64k.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/kernel-uki.spec
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  SPECS/knem/knem.spec
  SPECS/mft_kernel/mft_kernel.spec
  SPECS/mlnx-nfsrdma/mlnx-nfsrdma.spec
  SPECS/mlnx-ofa_kernel/mlnx-ofa_kernel.spec
  SPECS/srp/srp.spec
  SPECS/xpmem/xpmem.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, 3.0-dev
