Repository microsoft/azurelinux, pull requests merged in 2025-04, with the labels that each got.

#13246 kata(-cc): upgrade kata-containers(-cc) to 3.2.0.azl5
  SPECS/kata-containers-cc/kata-containers-cc.signatures.json
  SPECS/kata-containers-cc/kata-containers-cc.spec
  SPECS/kata-containers/kata-containers.signatures.json
  SPECS/kata-containers/kata-containers.spec
  cgmanifest.json
Labels: Packaging, 3.0-dev

#13240 msft-golang update to 1.24.1 for CVE-2025-22870, CVE-2024-45341, CVE-2024-45336, CVE-2024-34158
  SPECS/msft-golang/msft-golang.signatures.json
  SPECS/msft-golang/msft-golang.spec
  cgmanifest.json
Labels: Packaging, main

#12648 Update Conda to 24.3.0
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS/conda/conda.signatures.json
  SPECS/conda/conda.spec
  SPECS/python-archspec/python-archspec.signatures.json
  SPECS/python-archspec/python-archspec.spec
  SPECS/python-boltons/python-boltons.signatures.json
  SPECS/python-boltons/python-boltons.spec
  SPECS/python-conda-libmamba-solver/python-conda-libmamba-solver.signatures.json
  SPECS/python-conda-libmamba-solver/python-conda-libmamba-solver.spec
  SPECS/python-conda-package-streaming/python-conda-package-streaming.signatures.json
  SPECS/python-conda-package-streaming/python-conda-package-streaming.spec
  SPECS/python-menuinst/python-menuinst.signatures.json
  SPECS/python-menuinst/python-menuinst.spec
  SPECS/python-zstandard/python-zstandard.signatures.json
  SPECS/python-zstandard/python-zstandard.spec
  cgmanifest.json
Labels: documentation, Packaging, Tools, specs-extended, 3.0-dev

#11805 libsndfile: patch CVE-2024-50612
  SPECS/libsndfile/CVE-2024-50612.patch
  SPECS/libsndfile/libsndfile.spec
Labels: security, Packaging, 3.0-dev

#13260 [3.0] Fix ptest for `sysbench`
  SPECS/sysbench/sysbench-1.0.20-fix_deprecated_egrep_call.patch
  SPECS/sysbench/sysbench.spec
Labels: Packaging, ptest, 3.0-dev

#13279 Kernel upgrade to 5.15.179.1
  SPECS-SIGNED/kernel-azure-signed/kernel-azure-signed.spec
  SPECS-SIGNED/kernel-hci-signed/kernel-hci-signed.spec
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS/hyperv-daemons/hyperv-daemons.signatures.json
  SPECS/hyperv-daemons/hyperv-daemons.spec
  SPECS/kernel-azure/config
  SPECS/kernel-azure/config_aarch64
  SPECS/kernel-azure/kernel-azure.signatures.json
  SPECS/kernel-azure/kernel-azure.spec
  SPECS/kernel-hci/0002-net-mlx5-Introduce-port-selection-namespace.patch
  SPECS/kernel-hci/config
  SPECS/kernel-hci/kernel-hci.signatures.json
  SPECS/kernel-hci/kernel-hci.spec
  SPECS/kernel-headers/kernel-headers.signatures.json
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, main

#13286 Patch cmake for CVE-2024-48615 [High]
  SPECS/cmake/CVE-2024-48615.patch
  SPECS/cmake/cmake.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, fasttrack/2.0

#13197 Upgrade etcd to 3.5.21 for CVE-2025-30204 [High]
  SPECS/etcd/CVE-2023-45288.patch
  SPECS/etcd/CVE-2024-24786.patch
  SPECS/etcd/etcd.signatures.json
  SPECS/etcd/etcd.spec
  cgmanifest.json
Labels: security, Packaging, fasttrack/2.0

#13237 Patch coredns for CVE-2025-29786 [HIGH]
  SPECS/coredns/CVE-2025-29786.patch
  SPECS/coredns/coredns.spec
Labels: security, Packaging, fasttrack/2.0

#13200 Patch rabbitmq-server for CVE-2025-30219 [Medium]
  SPECS/rabbitmq-server/CVE-2025-30219.patch
  SPECS/rabbitmq-server/rabbitmq-server.spec
Labels: security, Packaging, fasttrack/2.0

#13198 Patch `cifs-utils` to address CVE-2025-2312 [Medium]
  SPECS/cifs-utils/CVE-2025-2312.patch
  SPECS/cifs-utils/cifs-utils.spec
Labels: security, Packaging, fasttrack/2.0

#11977 Patch grpc for CVE-2023-31130 [Medium]
  SPECS/grpc/CVE-2023-31130.patch
  SPECS/grpc/grpc.spec
Labels: security, Packaging, fasttrack/2.0

#13207 Patch augeas for CVE-2025-2588 [MEDIUM]
  SPECS/augeas/CVE-2025-2588.patch
  SPECS/augeas/augeas.spec
Labels: security, Packaging, fasttrack/2.0

#13245 [Medium] Patch telegraf for CVE-2025-22870 and CVE-2024-51744
  SPECS/telegraf/CVE-2024-51744.patch
  SPECS/telegraf/CVE-2025-22870.patch
  SPECS/telegraf/telegraf.spec
Labels: security, Packaging, fasttrack/2.0

#13272 Patch terraform for CVE-2023-48795 [Medium]
  SPECS/terraform/CVE-2023-48795.patch
  SPECS/terraform/terraform.spec
Labels: security, Packaging, fasttrack/2.0

#13273 Patch kubevirt for CVE-2023-48795 [Medium]
  SPECS/kubevirt/CVE-2023-48795.patch
  SPECS/kubevirt/kubevirt.spec
Labels: security, Packaging, fasttrack/2.0

#13252 containerd2: Remove the tardev-snapshotter patch for Kata CC support
  SPECS/containerd2/add-tardev-support.patch
  SPECS/containerd2/containerd2.spec
Labels: Packaging, 3.0-dev

#13261 Patch gdb to fix CVE-2022-48064 and CVE-2022-48065 [Medium]
  SPECS/gdb/CVE-2022-48064.patch
  SPECS/gdb/CVE-2022-48065.patch
  SPECS/gdb/gdb.spec
Labels: security, Packaging, fasttrack/2.0

#13269 Patch erlang for CVE-2025-30211 [High]
  SPECS/erlang/CVE-2025-30211.patch
  SPECS/erlang/erlang.spec
Labels: security, Packaging, fasttrack/2.0

#13287 Patch libarchive for CVE-2024-48615 [High]
  SPECS/libarchive/CVE-2024-48615.patch
  SPECS/libarchive/libarchive.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, fasttrack/2.0

#13293 [High][2.0] Resolve cri-o CVE-2025-21614
  SPECS/cri-o/CVE-2025-21614.patch
  SPECS/cri-o/cri-o.spec
Labels: Packaging, fasttrack/2.0

#13307 Fix ptest zsh
  SPECS/zsh/zsh.spec
Labels: Packaging, 3.0-dev

#13308 Fix tar Ptest
  SPECS/tar/tar-1.33-fix-capabilities-test.patch
  SPECS/tar/tar-1.35-add-forgotten-tests-from-upstream.patch
  SPECS/tar/tar.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, 3.0-dev

#13310 fix python-jwt ptest
  SPECS/python-jwt/python-jwt.spec
Labels: Packaging, Tools, specs-extended, 3.0-dev, 3.0

#13301 Patch git-lfs for CVE-2025-22870 [Medium]
  SPECS/git-lfs/CVE-2025-22870.patch
  SPECS/git-lfs/git-lfs.spec
Labels: security, Packaging, fasttrack/2.0

#13283 Patch cmake for CVE-2024-48615 [High]
  SPECS/cmake/CVE-2024-48615.patch
  SPECS/cmake/cmake.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, fasttrack/3.0

#13268 Upgrade erlang to 26.2.5.10 for CVE-2025-30211 [HIGH]
  SPECS/erlang/erlang.signatures.json
  SPECS/erlang/erlang.spec
  cgmanifest.json
Labels: security, Packaging, fasttrack/3.0

#13108 Add nil error trapping to licensecheck.go to allow for chroot cleanup on failure and exit gracefully
  toolkit/tools/licensecheck/licensecheck.go
  toolkit/tools/pkg/licensecheck/licensecheck.go
  toolkit/tools/pkg/licensecheck/licensecheck_test.go
  toolkit/tools/pkg/licensecheck/testdata/not_a_json.json
Labels: Tools, 3.0-dev

#12859 [Low] Patch python3 for CVE-2025-1795
  SPECS/python3/CVE-2025-1795.patch
  SPECS/python3/python3.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, fasttrack/2.0

#13275 libsepol: Install chkcon tool in libsepol-devel.
  SPECS/libsepol/libsepol.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, 3.0-dev

#13306 Patch moby-containerd-cc for CVE-2025-27144 [Medium]
  SPECS/moby-containerd-cc/CVE-2025-27144.patch
  SPECS/moby-containerd-cc/moby-containerd-cc.spec
Labels: Packaging, 3.0-dev

#13305 Patch moby-containerd-cc for CVE-2025-27144 [Medium]
  SPECS/moby-containerd-cc/CVE-2025-27144.patch
  SPECS/moby-containerd-cc/moby-containerd-cc.spec
Labels: Packaging, main

#13289 selinux-policy: Add fix for gpg-agent use in rpm scripts for watching root's secrets dir
  SPECS/selinux-policy/0041-rpm-Allow-gpg-agent-run-in-rpm-scripts-to-watch-secr.patch
  SPECS/selinux-policy/selinux-policy.spec
Labels: Packaging, 3.0-dev

#13328 [High] Patch qemu for CVE-2023-1544, CVE-2023-2861
  SPECS/qemu/CVE-2023-1544.patch
  SPECS/qemu/CVE-2023-2861.patch
  SPECS/qemu/qemu.spec
Labels: security, Packaging, fasttrack/2.0

#13270 Patch reaper for CVE-2024-12905 [HIGH]
  SPECS/reaper/CVE-2024-12905.patch
  SPECS/reaper/reaper.spec
Labels: security, Packaging, fasttrack/2.0

#12908 [Low] Patch dcos-cli for CVE-2024-51744
  SPECS/dcos-cli/CVE-2024-51744.patch
  SPECS/dcos-cli/dcos-cli.spec
Labels: security, Packaging, fasttrack/2.0

#12999 [Low] patch bpftrace for CVE-2024-2313
  SPECS/bpftrace/CVE-2024-2313.patch
  SPECS/bpftrace/bpftrace.spec
Labels: security, Packaging, fasttrack/2.0

#13000 [Low] patch libtiff for CVE-2023-6228
  SPECS/libtiff/CVE-2023-6228.patch
  SPECS/libtiff/libtiff.spec
Labels: security, Packaging, fasttrack/2.0

#13050 [Low] Patch prometheus for CVE-2024-51744
  SPECS/prometheus/CVE-2024-51744.patch
  SPECS/prometheus/prometheus.spec
Labels: security, Packaging, fasttrack/2.0

#13051 [Low]patch jx for CVE-2024-51744
  SPECS/jx/CVE-2024-51744.patch
  SPECS/jx/jx.spec
Labels: security, Packaging, fasttrack/2.0

#13054 [LOW] Patch rook to fix CVE-2024-51744
  SPECS/rook/CVE-2024-51744.patch
  SPECS/rook/rook.spec
Labels: security, Packaging, fasttrack/2.0

#13103 [LOW] Patch unzip to fix CVE-2021-4217
  SPECS/unzip/CVE-2021-4217.patch
  SPECS/unzip/unzip.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, fasttrack/2.0

#13121 Patch `wpa_supplicant` for CVE-2025-24912 [Low]
  SPECS/wpa_supplicant/CVE-2025-24912.patch
  SPECS/wpa_supplicant/wpa_supplicant.spec
Labels: security, Packaging, fasttrack/2.0

#13139 [Low] patch cert-manager for CVE-2024-51744
  SPECS/cert-manager/CVE-2024-51744.patch
  SPECS/cert-manager/cert-manager.spec
Labels: Packaging, fasttrack/2.0

#13164 [Low]patch kube-vip-cloud-provider for CVE-2024-51744
  SPECS/kube-vip-cloud-provider/CVE-2024-51744.patch
  SPECS/kube-vip-cloud-provider/kube-vip-cloud-provider.spec
Labels: security, Packaging, fasttrack/2.0

#13165 [Low] patch application-gateway-kubernetes-ingress for CVE-2024-51744
  SPECS/application-gateway-kubernetes-ingress/CVE-2024-51744.patch
  SPECS/application-gateway-kubernetes-ingress/application-gateway-kubernetes-ingress.spec
Labels: security, Packaging, fasttrack/2.0

#13182 [Low] Patch curl for CVE-2025-0167
  SPECS/curl/CVE-2025-0167.patch
  SPECS/curl/curl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, fasttrack/2.0

#13255 [Low] Patch kubernetes for CVE-2024-51744
  SPECS/kubernetes/CVE-2024-51744.patch
  SPECS/kubernetes/kubernetes.spec
Labels: security, Packaging, fasttrack/2.0

#12348 [MEDIUM] Patch numpy to fix CVE-2018-1999024
  SPECS/numpy/CVE-2018-1999024.patch
  SPECS/numpy/numpy.spec
Labels: security, Packaging, fasttrack/3.0

#12432 [Medium] Patch dietlibc for CVE-2015-1473
  SPECS/dietlibc/CVE-2015-1473.patch
  SPECS/dietlibc/dietlibc.spec
Labels: security, Packaging, fasttrack/3.0

#12639 Patch gnutls for CVE-2024-12133 [Medium]
  SPECS/gnutls/CVE-2024-12133.patch
  SPECS/gnutls/gnutls.spec
Labels: security, Packaging, fasttrack/3.0

#12932 [Medium] Patch vitess for CVE-2025-22870
  SPECS/vitess/CVE-2025-22870.patch
  SPECS/vitess/vitess.spec
Labels: security, Packaging, fasttrack/3.0

#13342 Patch `ceph` for CVE-2021-28361 [High]
  SPECS/ceph/CVE-2021-28361.patch
  SPECS/ceph/ceph.spec
Labels: security, Packaging, fasttrack/3.0

#12862 [Low] Patch subversion for CVE-2024-46901
  SPECS/subversion/CVE-2024-46901-advisory.patch
  SPECS/subversion/subversion.spec
Labels: security, Packaging, fasttrack/3.0

#13056 [Medium] patch memcached for CVE-2021-44647
  SPECS/memcached/CVE-2021-44647.patch
  SPECS/memcached/memcached.spec
Labels: security, Packaging, fasttrack/3.0

#13062 Patch expat for CVE-2024-8176 [HIGH]
  SPECS/expat/CVE-2024-50602.patch
  SPECS/expat/CVE-2024-8176.patch
  SPECS/expat/expat.signatures.json
  SPECS/expat/expat.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, fasttrack/3.0

#13304 Patch prometheus-node-exporter for CVE-2025-22870 [Medium]
  SPECS/prometheus-node-exporter/CVE-2025-22870.patch
  SPECS/prometheus-node-exporter/prometheus-node-exporter.spec
Labels: security, Packaging, fasttrack/3.0

#13274 Upgrade libssh2 to 1.11.1 for CVE-2023-48795 [Medium]
  SPECS/libssh2/libssh2.signatures.json
  SPECS/libssh2/libssh2.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, fasttrack/3.0

#13115 Upgrade `mysql` to 8.0.41 for CVE-2025-21490 & CVE-2024-11053 [High]
  SPECS/mysql/CVE-2024-9681.patch
  SPECS/mysql/CVE-2025-0725.patch
  SPECS/mysql/mysql.signatures.json
  SPECS/mysql/mysql.spec
  cgmanifest.json
Labels: security, Packaging, fasttrack/3.0

#13174 Patch `blobfuse2` for CVE-2025-30204 [High]
  SPECS/blobfuse2/CVE-2025-30204.patch
  SPECS/blobfuse2/blobfuse2.spec
Labels: security, Packaging, fasttrack/3.0

#12780 Upgrade zziplib to 0.13.74
  SPECS-EXTENDED/zziplib/zziplib.signatures.json
  SPECS-EXTENDED/zziplib/zziplib.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#11708 Upgrade: perl-Class-Data-Inheritable version to 0.09
  SPECS-EXTENDED/perl-Class-Data-Inheritable/perl-Class-Data-Inheritable.signatures.json
  SPECS-EXTENDED/perl-Class-Data-Inheritable/perl-Class-Data-Inheritable.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#11608 Upgrade: powertop to version 2.15
  SPECS-EXTENDED/powertop/powertop.signatures.json
  SPECS-EXTENDED/powertop/powertop.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#12627 Upgrade: python-colorama version to 0.4.6
  SPECS-EXTENDED/python-colorama/python-colorama.signatures.json
  SPECS-EXTENDED/python-colorama/python-colorama.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#11598 Upgrade: perl-Archive-Extract version to 0.88
  SPECS-EXTENDED/perl-Archive-Extract/perl-Archive-Extract.signatures.json
  SPECS-EXTENDED/perl-Archive-Extract/perl-Archive-Extract.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#11522 Upgrade: perl-Date-Manip version to 6.95
  SPECS-EXTENDED/perl-Date-Manip/perl-Date-Manip.signatures.json
  SPECS-EXTENDED/perl-Date-Manip/perl-Date-Manip.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#10888 added new package to SPECS-EXTENDED : rubygem-sys-filesystem
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS-EXTENDED/rubygem-sys-filesystem/rubygem-sys-filesystem.signatures.json
  SPECS-EXTENDED/rubygem-sys-filesystem/rubygem-sys-filesystem.spec
  cgmanifest.json
  toolkit/freeraduis_cmd.log1
Labels: Packaging, specs-extended, 3.0-dev

#11511 Upgraded mdds to version 2.1.1
  SPECS-EXTENDED/mdds/mdds.signatures.json
  SPECS-EXTENDED/mdds/mdds.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#11495 Upgrade: osinfo-db version to 20240701
  SPECS-EXTENDED/osinfo-db/osinfo-db-20221130.tar.xz.asc
  SPECS-EXTENDED/osinfo-db/osinfo-db-20240701.tar.xz.asc
  SPECS-EXTENDED/osinfo-db/osinfo-db.signatures.json
  SPECS-EXTENDED/osinfo-db/osinfo-db.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#11377 Upgraded libXScrnSaver to version 1.2.4
  SPECS-EXTENDED/libXScrnSaver/libXScrnSaver.signatures.json
  SPECS-EXTENDED/libXScrnSaver/libXScrnSaver.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#11264 libgxps: update to 0.3.2
  SPECS-EXTENDED/libgxps/libgxps.signatures.json
  SPECS-EXTENDED/libgxps/libgxps.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#10987 Update liblqr-1 to 0.4.3
  SPECS-EXTENDED/liblqr-1/liblqr-1.signatures.json
  SPECS-EXTENDED/liblqr-1/liblqr-1.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#10962 libblockdev: Version update to 3.2.0
  SPECS-EXTENDED/libblockdev/libblockdev.signatures.json
  SPECS-EXTENDED/libblockdev/libblockdev.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#10957 hyphen-it: Update Version from 0.20071127 -> 5.1.1
  SPECS-EXTENDED/hyphen-it/hyphen-it.signatures.json
  SPECS-EXTENDED/hyphen-it/hyphen-it.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#11494 Upgrade: os-prober version to 1.81
  SPECS-EXTENDED/os-prober/os-prober-arm64-win11.patch
  SPECS-EXTENDED/os-prober/os-prober-efi-shell.patch
  SPECS-EXTENDED/os-prober/os-prober-gentoo-fix.patch
  SPECS-EXTENDED/os-prober/os-prober-grub2-mount-workaround.patch
  SPECS-EXTENDED/os-prober/os-prober-grub2-parsefix.patch
  SPECS-EXTENDED/os-prober/os-prober-trap_unmount.patch
  SPECS-EXTENDED/os-prober/os-prober-umount-fix.patch
  SPECS-EXTENDED/os-prober/os-prober.signatures.json
  SPECS-EXTENDED/os-prober/os-prober.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#13340 [3.0] Fix Patch Application for `skopeo`
  SPECS/skopeo/skopeo.spec
Labels: security, Packaging, 3.0-dev

#13345 [3.0] Fix Patch Application for `nvidia-container-toolkit`
  SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec
Labels: security, Packaging, 3.0-dev

#13315 Adding SRPM duplicates check.
  .github/workflows/check-srpm-duplicates.yml
  toolkit/scripts/check_srpm_duplicates.py
Labels: Tools, main

#13387 flux warnings 2.0
  SPECS/flux/flux.spec
Labels: Packaging, main

#13385 flux warnings
  SPECS/flux/0001-libflux-unblock-build-by-allowing-warnings.patch
  SPECS/flux/fix-build-warnings.patch
  SPECS/flux/fix-unsigned-char.patch
  SPECS/flux/flux.spec
Labels: Packaging, 3.0-dev

#13137 [Low] Patch kubevirt for CVE-2024-51744
  SPECS/kubevirt/CVE-2024-51744.patch
  SPECS/kubevirt/kubevirt.spec
Labels: security, Packaging, fasttrack/2.0

#13378 Patch `fluent-bit` for CVE-2025-31498 [High]
  SPECS/fluent-bit/CVE-2025-31498.patch
  SPECS/fluent-bit/fluent-bit.spec
Labels: security, Packaging, fasttrack/3.0

#13298 Patch git-lfs for CVE-2025-22870 [Medium]
  SPECS/git-lfs/CVE-2025-22870.patch
  SPECS/git-lfs/git-lfs.spec
Labels: security, Packaging, fasttrack/3.0

#13303 Patch prometheus-process-exporter for CVE-2025-22870 [Medium]
  SPECS/prometheus-process-exporter/CVE-2025-22870.patch
  SPECS/prometheus-process-exporter/prometheus-process-exporter.spec
Labels: security, Packaging, fasttrack/3.0

#13346 [Low] patch clang for CVE-2024-7883
  SPECS/clang/CVE-2024-7883.patch
  SPECS/clang/clang.spec
Labels: security, Packaging, fasttrack/3.0

#13206 Patch augeas for CVE-2025-2588 [MEDIUM]
  SPECS/augeas/CVE-2025-2588.patch
  SPECS/augeas/augeas.spec
Labels: security, Packaging, fasttrack/3.0

#13117 [Medium] Upgrade grpc version to 1.62.3 for CVE-2024-7246
  SPECS/grpc/grpc.signatures.json
  SPECS/grpc/grpc.spec
  cgmanifest.json
Labels: Packaging, fasttrack/3.0

#13120 Patch wpa_supplicant for CVE-2025-24912 [Low]
  SPECS/wpa_supplicant/CVE-2025-24912.patch
  SPECS/wpa_supplicant/wpa_supplicant.spec
Labels: security, Packaging, fasttrack/3.0

#13104 [LOW] Patch unzip to fix CVE-2021-4217
  SPECS/unzip/CVE-2021-4217.patch
  SPECS/unzip/unzip.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, fasttrack/3.0

#12834 [Low] patch vitess for CVE-2024-53257
  SPECS/vitess/CVE-2024-53257.patch
  SPECS/vitess/vitess.spec
Labels: security, Packaging, fasttrack/3.0

#12912 [MEDIUM] Patch syslinux to fix CVE-2011-2501,CVE-2011-2691,CVE-2011-3045,CVE-2012-3425 & CVE-2015-7981
  SPECS/syslinux/CVE-2011-2501.patch
  SPECS/syslinux/CVE-2011-2691.patch
  SPECS/syslinux/CVE-2011-3045.patch
  SPECS/syslinux/CVE-2012-3425.patch
  SPECS/syslinux/CVE-2015-7981.patch
  SPECS/syslinux/syslinux.spec
Labels: security, Packaging, fasttrack/3.0

#12471 [Medium] Patch ruby for CVE-2025-25186
  SPECS/ruby/CVE-2025-25186.patch
  SPECS/ruby/ruby.spec
Labels: security, Packaging, fasttrack/3.0

#13249 Fix to include idmapd.conf and id_resolver.conf in nfs-utils for 3.0
  SPECS/nfs-utils/nfs-utils.spec
Labels: Packaging, 3.0-dev

#13384 [Medium] patch dwarves for CVE-2025-29481
  SPECS/dwarves/0001-btf-Remove-ftrace-filter.patch
  SPECS/dwarves/CVE-2025-29481.patch
  SPECS/dwarves/dwarves.spec
Labels: security, Packaging, 3.0-dev

#13383 [Medium] patch libbpf for CVE-2025-29481
  SPECS/libbpf/CVE-2025-29481.patch
  SPECS/libbpf/libbpf.spec
Labels: security, Packaging, main

#12298 [3.0] Introduce debug and metapackage and reduce size of non-debug metapackage
  SPECS/kata-packages-uvm/kata-packages-uvm.spec
Labels: Packaging, 3.0-dev

#13404 [Medium] edk2 openssl CVE-2024-13176
  SPECS-SIGNED/edk2-hvloader-signed/edk2-hvloader-signed.spec
  SPECS/edk2/CVE-2024-13176.patch
  SPECS/edk2/CVE-2024-4741.patch
  SPECS/edk2/edk2.spec
Labels: Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#13377 [Medium] Patch qemu for CVE-2023-3019, CVE-2023-3180, CVE-2023-3301, CVE-2023-3255
  SPECS/qemu/CVE-2023-3019.patch
  SPECS/qemu/CVE-2023-3180.patch
  SPECS/qemu/CVE-2023-3255.patch
  SPECS/qemu/CVE-2023-3301.patch
  SPECS/qemu/qemu.spec
Labels: security, Packaging, fasttrack/2.0, CVEFixReadyForMaintainerReview

#13247 Patch coredns for CVE-2024-53259 [Medium]
  SPECS/coredns/CVE-2024-53259.patch
  SPECS/coredns/coredns.spec
Labels: security, Packaging, fasttrack/3.0

#13031 [Low]patch flannel for CVE-2024-51744
  SPECS/flannel/CVE-2024-51744.patch
  SPECS/flannel/flannel.spec
Labels: security, Packaging, fasttrack/3.0

#13030 [Low} Patch dcos-cli for CVE-2024-51744
  SPECS/dcos-cli/CVE-2024-51744.patch
  SPECS/dcos-cli/dcos-cli.spec
Labels: security, Packaging, fasttrack/3.0

#12998 [Low] patch bcc for CVE-2024-2314
  SPECS/bcc/CVE-2024-2314.patch
  SPECS/bcc/bcc.spec
Labels: security, Packaging, fasttrack/3.0

#12678 Patch telegraf for CVE-2024-35255 and CVE-2025-27144 [Medium].
  SPECS/telegraf/CVE-2024-35255.patch
  SPECS/telegraf/CVE-2025-27144.patch
  SPECS/telegraf/telegraf.spec
Labels: security, Packaging, fasttrack/3.0

#12064 extended repo LVBS kernel
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS-EXTENDED/kernel-lpg-innovate/azurelinux-ca-20230216.pem
  SPECS-EXTENDED/kernel-lpg-innovate/cpupower
  SPECS-EXTENDED/kernel-lpg-innovate/cpupower.service
  SPECS-EXTENDED/kernel-lpg-innovate/kernel-lpg-innovate.normal.config
  SPECS-EXTENDED/kernel-lpg-innovate/kernel-lpg-innovate.secure.config
  SPECS-EXTENDED/kernel-lpg-innovate/kernel-lpg-innovate.signatures.json
  SPECS-EXTENDED/kernel-lpg-innovate/kernel-lpg-innovate.spec
  SPECS-EXTENDED/kernel-lpg-innovate/sha512hmac-openssl.sh
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#11724 python-requests: add patch for CVE-2024-35195
  SPECS/python-requests/CVE-2024-35195.patch
  SPECS/python-requests/python-requests.spec
Labels: security, Packaging, 3.0-dev, fasttrack/3.0

#9291 Updated context to be used for HTTP request + refactoring
  toolkit/tools/internal/azureblobstorage/azureblobstorage.go
  toolkit/tools/internal/network/network.go
  toolkit/tools/internal/network/network_test.go
  toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
  toolkit/tools/internal/retry/retry_test.go
  toolkit/tools/pkg/specreaderutils/specreaderutil.go
  toolkit/tools/precacher/precacher.go
  toolkit/tools/srpmpacker/srpmpacker.go
Labels: Tools, 3.0-dev

#13424 Fix perl-json-any ptest
  SPECS/perl-JSON-Any/perl-JSON-Any.spec
Labels: Packaging, Tools, specs-extended, 3.0-dev

#13422 Fix ocaml-ctypes ptest
  SPECS/ocaml-ctypes/ocaml-ctypes-stdlib-shims.patch
  SPECS/ocaml-ctypes/ocaml-ctypes.spec
Labels: Packaging, 3.0-dev

#13421 Fix ocaml-astring ptest
  SPECS/ocaml-astring/ocaml-astring-ocaml5.patch
  SPECS/ocaml-astring/ocaml-astring.spec
Labels: Packaging, 3.0-dev

#13420 Fix rubygem-rake ptest
  SPECS/rubygem-rake/rubygem-rake.spec
Labels: Packaging, 3.0-dev

#13414 Fix Ptest for python-ecdsa
  SPECS/python-ecdsa/308.patch
  SPECS/python-ecdsa/python-ecdsa.spec
Labels: Packaging, 3.0-dev

#13413 Fix ptest python-greenlet
  SPECS/python-greenlet/greenlet-py39.patch
  SPECS/python-greenlet/python-greenlet.spec
  SPECS/python-greenlet/skip-leak-checks.patch
Labels: Packaging, 3.0-dev

#13333 Add patch fixing tests for python-cytoolz
  SPECS/python-cytoolz/cytoolz-test-py313.patch
  SPECS/python-cytoolz/python-cytoolz.spec
Labels: Packaging, 3.0-dev

#12935 amtk: upgrade to 5.6.1
  SPECS-EXTENDED/amtk/amtk.signatures.json
  SPECS-EXTENDED/amtk/amtk.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#12939 Upgrade: python-kdcproxy version to 1.0.0
  SPECS-EXTENDED/python-kdcproxy/Drop-coverage-from-tests.patch
  SPECS-EXTENDED/python-kdcproxy/python-kdcproxy.signatures.json
  SPECS-EXTENDED/python-kdcproxy/python-kdcproxy.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#12940 Upgrade: python-lazy-object-proxy version to 1.10.0
  SPECS-EXTENDED/python-lazy-object-proxy/python-lazy-object-proxy.signatures.json
  SPECS-EXTENDED/python-lazy-object-proxy/python-lazy-object-proxy.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#12866 Patch `ruby` CVE-2025-27219, CVE-2025-27220, CVE-2025-27221 [Medium]
  SPECS/ruby/CVE-2025-27219.patch
  SPECS/ruby/CVE-2025-27220.patch
  SPECS/ruby/CVE-2025-27221.patch
  SPECS/ruby/ruby.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#12988 [Medium] Patch azcopy for CVE-2025-22870 and CVE-2024-51744
  SPECS/azcopy/CVE-2024-51744.patch
  SPECS/azcopy/CVE-2025-22870.patch
  SPECS/azcopy/azcopy.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#13053 Patch `elfutils` for CVE-2025-1372, CVE-2025-1376 & CVE-2025-1377 [Medium]
  SPECS/elfutils/CVE-2025-1372.patch
  SPECS/elfutils/CVE-2025-1376.patch
  SPECS/elfutils/CVE-2025-1377.patch
  SPECS/elfutils/elfutils.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#13081 [LOW] Patch coredns to fix CVE-2024-51744
  SPECS/coredns/CVE-2024-51744.patch
  SPECS/coredns/coredns.spec
Labels: security, Packaging, fasttrack/2.0, CVEFixReadyForMaintainerReview

#12259 [Medium] Patch nodejs for CVE-2024-34064, CVE-2020-28493
  SPECS/nodejs/CVE-2020-28493.patch
  SPECS/nodejs/CVE-2024-34064.patch
  SPECS/nodejs/nodejs.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#12686 Patch prometheus for CVE-2024-35255 [Medium].
  SPECS/prometheus/CVE-2024-35255.patch
  SPECS/prometheus/prometheus.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#12882 [Medium] Patch gnutls for CVE-2024-12243
  SPECS/gnutls/CVE-2024-12243.patch
  SPECS/gnutls/gnutls.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#13072 [Low] Patch kubernetes for CVE-2024-51744
  SPECS/kubernetes/CVE-2024-51744.patch
  SPECS/kubernetes/kubernetes.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#13398 [Medium] Patch haproxy for CVE-2025-32464
  SPECS/haproxy/CVE-2025-32464.patch
  SPECS/haproxy/haproxy.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#13451 Patch openssh for CVE-2025-32728 [MEDIUM]
  SPECS/openssh/CVE-2025-32728.patch
  SPECS/openssh/openssh.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#13457 Patch telegraf for CVE-2025-30215 [CRITICAL]
  SPECS/telegraf/CVE-2025-30215.patch
  SPECS/telegraf/telegraf.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#13458 Upgrade erlang to 26.2.5.11 for CVE-2025-32433 [CRITICAL]
  SPECS/erlang/erlang.signatures.json
  SPECS/erlang/erlang.spec
  cgmanifest.json
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#13425 Patch giflib for CVE-2025-31344 [HIGH]
  SPECS/giflib/CVE-2025-31344.patch
  SPECS/giflib/giflib.spec
Labels: security, Packaging, fasttrack/2.0, CVEFixReadyForMaintainerReview

#13465 Patch telegraf for CVE-2025-30215 [CRITICAL]
  SPECS/telegraf/CVE-2025-30215.patch
  SPECS/telegraf/telegraf.spec
Labels: security, Packaging, fasttrack/2.0, CVEFixReadyForMaintainerReview

#13471 Upgrade erlang to 25.3.2.20 for CVE-2025-32433 [CRITICAL]
  SPECS/erlang/CVE-2023-48795.patch
  SPECS/erlang/CVE-2025-26618.patch
  SPECS/erlang/CVE-2025-30211.patch
  SPECS/erlang/erlang.signatures.json
  SPECS/erlang/erlang.spec
  cgmanifest.json
Labels: security, Packaging, fasttrack/2.0, CVEFixReadyForMaintainerReview

#13474 Patch golang-1.18 for CVE-2024-34158 [HIGH]
  SPECS/golang/CVE-2024-34158.patch
  SPECS/golang/golang-1.18.spec
Labels: security, Packaging, fasttrack/2.0

#13447 [High] Patch libsoup for CVE-2025-32913, CVE-2025-32906
  SPECS/libsoup/CVE-2025-32906.patch
  SPECS/libsoup/CVE-2025-32913.patch
  SPECS/libsoup/libsoup.spec
Labels: security, Packaging, fasttrack/2.0

#13314 Fixing specs generating duplicate SRPMs
  .github/workflows/check-srpm-duplicates.yml
  SPECS-SIGNED/fwctl-signed/fwctl-signed.spec
  SPECS-SIGNED/iser-signed/iser-signed.spec
  SPECS-SIGNED/isert-signed/isert-signed.spec
  SPECS-SIGNED/knem-modules-signed/knem-modules-signed.spec
  SPECS-SIGNED/mft_kernel-signed/mft_kernel-signed.spec
  SPECS-SIGNED/mlnx-nfsrdma-signed/mlnx-nfsrdma-signed.spec
  SPECS-SIGNED/mlnx-ofa_kernel-modules-signed/mlnx-ofa_kernel-modules-signed.spec
  SPECS-SIGNED/srp-signed/srp-signed.spec
  SPECS-SIGNED/systemd-boot-signed/systemd-boot-signed.spec
  SPECS-SIGNED/xpmem-modules-signed/xpmem-modules-signed.spec
  SPECS/fwctl/fwctl.spec
  SPECS/iser/iser.spec
  SPECS/isert/isert.spec
  SPECS/knem/knem.spec
  SPECS/mft_kernel/mft_kernel.spec
  SPECS/mlnx-nfsrdma/mlnx-nfsrdma.spec
  SPECS/mlnx-ofa_kernel/mlnx-ofa_kernel.spec
  SPECS/srp/srp.spec
  SPECS/systemd/systemd.spec
  SPECS/xpmem/xpmem.spec
  toolkit/scripts/check_srpm_duplicates.py
Labels: Packaging, Tools, 3.0-dev

#13071 [Medium] patch qemu for CVE-2021-20255, CVE-2023-6693, CVE-2023-6683
  SPECS/qemu/CVE-2021-20255.patch
  SPECS/qemu/CVE-2023-6683.patch
  SPECS/qemu/CVE-2023-6693.patch
  SPECS/qemu/qemu.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#13095 [Medium] Patch influxdb for CVE-2025-22870 and CVE-2024-51744
  SPECS/influxdb/CVE-2024-51744.patch
  SPECS/influxdb/CVE-2025-22870.patch
  SPECS/influxdb/influxdb.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#13110 [Medium] Patch packer for CVE-2025-22870 and CVE-2024-51744
  SPECS/packer/CVE-2024-51744.patch
  SPECS/packer/CVE-2025-22870.patch
  SPECS/packer/packer.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#13166 [LOW] Patch ceph for CVE-2020-14378
  SPECS/ceph/CVE-2020-14378.patch
  SPECS/ceph/ceph.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#13403 Patch golang for CVE-2025-22871[High]
  SPECS/golang/CVE-2025-22871.patch
  SPECS/golang/golang-1.18.spec
  SPECS/golang/golang.spec
Labels: security, Packaging, fasttrack/2.0, CVEFixReadyForMaintainerReview

#13472 Patch openssh for CVE-2025-32728 [MEDIUM]
  SPECS/openssh/CVE-2025-32728.patch
  SPECS/openssh/openssh.spec
Labels: security, Packaging, fasttrack/2.0, CVEFixReadyForMaintainerReview

#13504 Patch `graphviz` for CVE-2023-46045 [High]
  SPECS/graphviz/CVE-2023-46045.patch
  SPECS/graphviz/graphviz.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#13505 Patch `gdb` for CVE-2022-47673, CVE-2022-47696 [High]
  SPECS/gdb/CVE-2022-47673.patch
  SPECS/gdb/CVE-2022-47696.patch
  SPECS/gdb/gdb.spec
Labels: security, Packaging, fasttrack/2.0, CVEFixReadyForMaintainerReview

#13470 Patch cri-o for CVE-2024-9676
  SPECS/cri-o/CVE-2024-9676.patch
  SPECS/cri-o/cri-o.spec
Labels: security, Packaging, main

#13329 Patch moby-containerd for CVE-2024-40635 [medium]
  SPECS/moby-containerd/CVE-2024-40635.patch
  SPECS/moby-containerd/moby-containerd.spec
Labels: Packaging, main

#13435 grub2: Replace fgrep with grep
  SPECS-SIGNED/grub2-efi-binary-signed/grub2-efi-binary-signed.spec
  SPECS/grub2/0203-replace-fgrep-with-grep.patch
  SPECS/grub2/grub2.spec
Labels: Packaging, 3.0-dev

#13507 Fix `crash` for CVE-2021-20197, CVE-2022-47673, CVE-2022-47696, CVE-2022-37434 [High]
  SPECS/crash/crash.signatures.json
  SPECS/crash/crash.spec
Labels: security, Packaging, fasttrack/2.0, CVEFixReadyForMaintainerReview

#13521 Patch `giflib` for CVE-2021-40633 [High]
  SPECS/giflib/CVE-2021-40633.patch
  SPECS/giflib/giflib.spec
Labels: security, Packaging, fasttrack/2.0, CVEFixReadyForMaintainerReview

#13530 [High] Patch moby-engine for CVE-2025-30204
  SPECS/moby-engine/CVE-2025-30204.patch
  SPECS/moby-engine/moby-engine.spec
Labels: Packaging, fasttrack/2.0, CVEFixReadyForMaintainerReview

#13506 Fix `crash` for CVE-2021-20197, CVE-2022-47673, CVE-2022-47696 [High]
  SPECS/crash/crash.signatures.json
  SPECS/crash/crash.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#13520 Patch `giflib` for CVE-2021-40633 [High]
  SPECS/giflib/CVE-2021-40633.patch
  SPECS/giflib/giflib.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview
