Repository microsoft/azurelinux, pull requests merged in 2025-05, with the labels that each got.

#13652 Patch busybox for CVE-2023-39810 [HIGH]
  SPECS/busybox/CVE-2023-39810.patch
  SPECS/busybox/busybox.spec
Labels: security, Packaging, fasttrack/2.0, CVEFixReadyForMaintainerReview

#13668 Patch libsoup for CVE-2025-2784 [HIGH], CVE-2025-32050, CVE-2025-32051, CVE-2025-32052, CVE-2025-46420, CVE-2025-46421 [MEDIUM]
  SPECS/libsoup/CVE-2025-2784.patch
  SPECS/libsoup/CVE-2025-32050.patch
  SPECS/libsoup/CVE-2025-32051.patch
  SPECS/libsoup/CVE-2025-32052.patch
  SPECS/libsoup/CVE-2025-46420.patch
  SPECS/libsoup/CVE-2025-46421.patch
  SPECS/libsoup/libsoup.spec
Labels: security, Packaging, fasttrack/2.0, CVEFixReadyForMaintainerReview

#13646 Patch `dnf5` CVE-2024-1929, CVE-2024-1930, CVE-2024-2746 [High]
  SPECS/dnf5/CVE-2024-1929.patch
  SPECS/dnf5/CVE-2024-1930.patch
  SPECS/dnf5/CVE-2024-2746.patch
  SPECS/dnf5/dnf5.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#13651 Patch busybox for CVE-2023-39810 [HIGH]
  SPECS/busybox/CVE-2023-39810.patch
  SPECS/busybox/busybox.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#13667 Patch libsoup for CVE-2025-2784 [HIGH], CVE-2025-32050, CVE-2025-32051, CVE-2025-32052, CVE-2025-46420, CVE-2025-46421 [MEDIUM]
  SPECS/libsoup/CVE-2025-2784.patch
  SPECS/libsoup/CVE-2025-32050.patch
  SPECS/libsoup/CVE-2025-32051.patch
  SPECS/libsoup/CVE-2025-32052.patch
  SPECS/libsoup/CVE-2025-46420.patch
  SPECS/libsoup/CVE-2025-46421.patch
  SPECS/libsoup/libsoup.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#13673 Patch qemu for CVE-2024-4467, CVE-2024-7730 [HIGH], CVE-2024-6505, CVE-2024-4693, CVE-2024-3447, CVE-2024-3567 [MEDIUM]
  SPECS/qemu/CVE-2024-3447.patch
  SPECS/qemu/CVE-2024-3567.patch
  SPECS/qemu/CVE-2024-4467.patch
  SPECS/qemu/CVE-2024-4693.patch
  SPECS/qemu/CVE-2024-6505.patch
  SPECS/qemu/CVE-2024-7730.patch
  SPECS/qemu/qemu.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#11957 virtiofsd: patch CVE-2024-43806
  SPECS/virtiofsd/CVE-2024-43806.patch
  SPECS/virtiofsd/virtiofsd.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#13468 Update kernel-lpg-innovate to version 6.6.85.1
  SPECS-EXTENDED/kernel-lpg-innovate/kernel-lpg-innovate.normal.config
  SPECS-EXTENDED/kernel-lpg-innovate/kernel-lpg-innovate.secure.config
  SPECS-EXTENDED/kernel-lpg-innovate/kernel-lpg-innovate.signatures.json
  SPECS-EXTENDED/kernel-lpg-innovate/kernel-lpg-innovate.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#13623 Upgrade: marisa version to 0.2.6
  SPECS-EXTENDED/marisa/marisa.signatures.json
  SPECS-EXTENDED/marisa/marisa.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#13615 [Medium] Patch cni-plugins for CVE-2025-22872
  SPECS/cni-plugins/CVE-2025-22872.patch
  SPECS/cni-plugins/cni-plugins.spec
Labels: security, Packaging, 3.0-dev

#13608 Fixes boost by adding phoenix multiple defn patch needed by libetonyek
  SPECS/boost/boost-1.81-phoenix-multiple-defn.patch
  SPECS/boost/boost.spec
Labels: Packaging, 3.0-dev

#13593 [Medium] Patch multus for CVE-2025-22872
  SPECS/multus/CVE-2025-22872.patch
  SPECS/multus/multus.spec
Labels: security, Packaging, 3.0-dev

#13573 generic-logos: fix the build error
  SPECS-EXTENDED/generic-logos/generic-logos.spec
Labels: Packaging, specs-extended, 3.0-dev

#13526 Patch telegraf for CVE-2025-22872 [Medium]
  SPECS/telegraf/CVE-2025-22872.patch
  SPECS/telegraf/telegraf.spec
Labels: security, Packaging, main

#13497 [Medium] Patch libxml2 for CVE-2025-32414 and CVE-2025-32415
  SPECS/libxml2/CVE-2025-32414.patch
  SPECS/libxml2/CVE-2025-32415.patch
  SPECS/libxml2/libxml2.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, 3.0-dev

#13477 Fixes broken build of perl-File-DesktopEntry
  SPECS-EXTENDED/perl-File-DesktopEntry/perl-File-DesktopEntry.spec
Labels: Packaging, specs-extended, 3.0-dev

#13452 [MEDIUM] Patch helm for CVE-2025-32386 & CVE-2025-22872
  SPECS/helm/CVE-2025-22872.patch
  SPECS/helm/CVE-2025-32386.patch
  SPECS/helm/helm.spec
Labels: security, Packaging, 3.0-dev

#13064 Upgrade python-beautifulsoup4 version to 4.12.3
  SPECS-EXTENDED/python-beautifulsoup4/python-beautifulsoup4.signatures.json
  SPECS-EXTENDED/python-beautifulsoup4/python-beautifulsoup4.spec
  SPECS-EXTENDED/python-beautifulsoup4/soupsieve26.patch
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#12985 Upgrades rp-pppoe to version 4.0
  SPECS-EXTENDED/rp-pppoe/pppoe-connect
  SPECS-EXTENDED/rp-pppoe/pppoe-server.service
  SPECS-EXTENDED/rp-pppoe/pppoe-setup
  SPECS-EXTENDED/rp-pppoe/pppoe-start
  SPECS-EXTENDED/rp-pppoe/pppoe-status
  SPECS-EXTENDED/rp-pppoe/pppoe-stop
  SPECS-EXTENDED/rp-pppoe/rp-pppoe-3.12-bz#1469960-new-kernel-header.patch
  SPECS-EXTENDED/rp-pppoe/rp-pppoe-3.12-doc.patch
  SPECS-EXTENDED/rp-pppoe/rp-pppoe-3.12-ip-allocation.patch
  SPECS-EXTENDED/rp-pppoe/rp-pppoe-3.12-man.patch
  SPECS-EXTENDED/rp-pppoe/rp-pppoe-3.12-plugin.patch
  SPECS-EXTENDED/rp-pppoe/rp-pppoe-3.12-pluginpath.patch
  SPECS-EXTENDED/rp-pppoe/rp-pppoe-manpages.patch
  SPECS-EXTENDED/rp-pppoe/rp-pppoe.signatures.json
  SPECS-EXTENDED/rp-pppoe/rp-pppoe.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#13502 Upgrade stunnel for work item 56658178
  SPECS-EXTENDED/stunnel/stunnel-5.56-coverity.patch
  SPECS-EXTENDED/stunnel/stunnel-5.56-curves-doc-update.patch
  SPECS-EXTENDED/stunnel/stunnel-5.62-disabled-curves.patch
  SPECS-EXTENDED/stunnel/stunnel-5.69-default-tls-version.patch
  SPECS-EXTENDED/stunnel/stunnel.signatures.json
  SPECS-EXTENDED/stunnel/stunnel.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#13660 Switched the fast-track PR check to run on an AZL 3.0 agent pool.
  .pipelines/prchecks/PackageBuildPRCheck.yml
  .pipelines/templates/PackageTestResultsAnalysis.yml
Labels: Packaging, Tools, specs-extended, 3.0-dev, fasttrack/3.0

#13661 Switched the fast-track PR check to run on an AZL 3.0 agent pool.
  .pipelines/prchecks/PackageBuildPRCheck.yml
  .pipelines/templates/PackageTestResultsAnalysis.yml
Labels: Packaging, main, fasttrack/2.0

#13621 Patch hvloader for CVE-2023-45236, CVE-2023-45237 [High]
  SPECS-SIGNED/hvloader-signed/hvloader-signed.spec
  SPECS/hvloader/CVE-2023-45236.patch
  SPECS/hvloader/CVE-2023-45237.patch
  SPECS/hvloader/hvloader.spec
Labels: security, Packaging, fasttrack/2.0, CVEFixReadyForMaintainerReview

#13691 Fix Ptest python-Cryptography
  SPECS/python-cryptography/python-cryptography.spec
Labels: Packaging, 3.0-dev

#13637 Fix python-oauthlib ptest
  SPECS-EXTENDED/python-blinker/python-blinker.signatures.json
  SPECS/python-blinker/python-blinker.signatures.json
  SPECS/python-blinker/python-blinker.spec
  SPECS/python-oauthlib/python-oauthlib.spec
  cgmanifest.json
Labels: Packaging, ptest, specs-extended, 3.0-dev

#13693 fix perl-cpan-meta-check ptest
  SPECS/perl-CPAN-Meta-Check/perl-CPAN-Meta-Check.spec
Labels: Packaging, 3.0-dev

#10947 add repo snapshot options to dnf5
  SPECS/dnf5/dnf5-repo-snapshot.patch
  SPECS/dnf5/dnf5.spec
Labels: Packaging, 3.0-dev

#13525 Patch telegraf for CVE-2025-22872 [Medium]
  SPECS/telegraf/CVE-2025-22872.patch
  SPECS/telegraf/telegraf.spec
Labels: security, Packaging, 3.0-dev

#13694 Upgrade: zenity version to 3.44.1
  SPECS-EXTENDED/zenity/zenity.signatures.json
  SPECS-EXTENDED/zenity/zenity.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#13407 Patch libsoup for CVE-2025-32053 [Medium]
  SPECS/libsoup/CVE-2025-32053.patch
  SPECS/libsoup/libsoup.spec
Labels: security, Packaging, main

#13735 SymCrypt-OpenSSL -- Update mechanism for creating keysinuse logging directory.
  SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.spec
Labels: Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#13339 toolkit: golang-jwt: 5.2.1 -> 5.2.2 to address excessive memory allocation during header parsing (CVE-2025-30204)
  toolkit/tools/go.mod
  toolkit/tools/go.sum
Labels: security, Tools, 3.0-dev

#13758 Remove a build log file added by mistake
  toolkit/freeraduis_cmd.log1
Labels: 3.0-dev

#13765 [MEDIUM] Patch cmake for CVE-2024-8096
  SPECS/cmake/CVE-2024-8096.patch
  SPECS/cmake/cmake.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, main

#13715 [MEDIUM] Patch edk2 for CVE-2024-2511, CVE-2024-38796 & CVE-2024-4603
  SPECS-SIGNED/edk2-hvloader-signed/edk2-hvloader-signed.spec
  SPECS/edk2/CVE-2024-2511.patch
  SPECS/edk2/CVE-2024-38796.patch
  SPECS/edk2/CVE-2024-4603.patch
  SPECS/edk2/edk2.spec
Labels: Packaging, 3.0-dev

#13714 Patch qemu for CVE-2024-26327, CVE-2024-26328 [MEDIUM]
  SPECS/qemu/CVE-2024-26327.patch
  SPECS/qemu/CVE-2024-26328.patch
  SPECS/qemu/qemu.spec
Labels: security, Packaging, 3.0-dev

#13709 Build Fix: jsch 0.1.55
  SPECS-EXTENDED/jsch/jsch-0.1.54-sourcetarget.patch
  SPECS-EXTENDED/jsch/jsch-osgi-manifest.patch
  SPECS-EXTENDED/jsch/jsch.spec
Labels: Packaging, specs-extended, 3.0-dev

#13704 Upgrades objenesis to version 3.3
  SPECS-EXTENDED/objenesis/objenesis-javadoc.patch
  SPECS-EXTENDED/objenesis/objenesis.signatures.json
  SPECS-EXTENDED/objenesis/objenesis.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#13696 Upgrade: libgeotiff version to 1.7.3
  SPECS-EXTENDED/libgeotiff/libgeotiff.signatures.json
  SPECS-EXTENDED/libgeotiff/libgeotiff.spec
  SPECS-EXTENDED/libgeotiff/libgeotiff_cmake.patch
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#13678 Upgrade: perl-JSON-MaybeXS version to 1.004008
  SPECS-EXTENDED/perl-JSON-MaybeXS/perl-JSON-MaybeXS.signatures.json
  SPECS-EXTENDED/perl-JSON-MaybeXS/perl-JSON-MaybeXS.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#13641 [MEDIUM] Patch pytorch for CVE-2025-2953
  SPECS/pytorch/CVE-2025-2953.patch
  SPECS/pytorch/pytorch.spec
Labels: security, Packaging, 3.0-dev

#13706 mock: backport upstream change for disabling ca-trust copying
  SPECS/mock/disable-copying-ca-trust-dirs.patch
  SPECS/mock/mock.spec
Labels: Packaging, 3.0-dev

#13732 Patch `syslog-ng` for CVE-2024-47619 [High]
  SPECS/syslog-ng/CVE-2024-47619.patch
  SPECS/syslog-ng/syslog-ng.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#13734 Patch `syslog-ng` for CVE-2024-47619 [High]
  SPECS/syslog-ng/CVE-2024-47619.patch
  SPECS/syslog-ng/syslog-ng.spec
Labels: security, Packaging, fasttrack/2.0

#13769 Upgrade `maven` to 3.8.1 to fix CVE-2021-26291 in `javapackages-bootstrap` [Critical]
  SPECS/javapackages-bootstrap/CVE-2021-26291.patch
  SPECS/javapackages-bootstrap/javapackages-bootstrap.signatures.json
  SPECS/javapackages-bootstrap/javapackages-bootstrap.spec
Labels: security, Packaging, fasttrack/2.0, CVEFixReadyForMaintainerReview

#13763 [3.0 fasttrack] glibc: add pthread_cond_wait patch
  SPECS-EXTENDED/buildah/buildah.spec
  SPECS-EXTENDED/catatonit/catatonit.spec
  SPECS-EXTENDED/dyninst/dyninst.spec
  SPECS-EXTENDED/podman/podman.spec
  SPECS/busybox/busybox.spec
  SPECS/flannel/flannel.spec
  SPECS/glibc/glibc.spec
  SPECS/kubernetes/kubernetes.spec
  SPECS/kubevirt/kubevirt.spec
  SPECS/libcap/libcap.spec
  SPECS/libguestfs/libguestfs.spec
  SPECS/qemu/qemu.spec
  SPECS/rust/rust-1.75.spec
  SPECS/rust/rust.spec
  SPECS/supermin/supermin.spec
  SPECS/tini/tini.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, specs-extended, fasttrack/3.0, CVEFixReadyForMaintainerReview

#13687 [MEDIUM] Upgrade ansible to 2.14.18 to fix CVE-2024-8775 & CVE-2024-9902
  SPECS/ansible/CVE-2024-0690.patch
  SPECS/ansible/ansible.signatures.json
  SPECS/ansible/ansible.spec
  cgmanifest.json
Labels: security, Packaging, main

#13755 Promote stunnel to core
  SPECS/stunnel/Certificate-Creation
  SPECS/stunnel/pop3-redirect.xinetd
  SPECS/stunnel/sfinger.xinetd
  SPECS/stunnel/stunnel-5.50-authpriv.patch
  SPECS/stunnel/stunnel-5.56-curves-doc-update.patch
  SPECS/stunnel/stunnel-5.56.tar.gz.asc
  SPECS/stunnel/stunnel-5.61-systemd-service.patch
  SPECS/stunnel/stunnel-5.69-default-tls-version.patch
  SPECS/stunnel/stunnel-5.69-system-ciphers.patch
  SPECS/stunnel/stunnel-pop3s-client.conf
  SPECS/stunnel/stunnel-sfinger.conf
  SPECS/stunnel/stunnel.signatures.json
  SPECS/stunnel/stunnel.spec
  SPECS/stunnel/stunnel@.service
Labels: Packaging, 3.0-dev

#13780 Fix ptest for python-asn1crypto, python-mako, python-gast, and python-nocasedict
  SPECS/python-asn1crypto/python-asn1crypto.spec
  SPECS/python-asn1crypto/remove-import.patch
  SPECS/python-gast/python-gast.spec
  SPECS/python-mako/python-mako.spec
  SPECS/python-nocasedict/python-nocasedict.spec
Labels: Packaging, 3.0-dev

#13647 kata-containers(-cc): Update to 3.15.0.aks0 release
  SPECS/kata-containers-cc/kata-containers-cc.signatures.json
  SPECS/kata-containers-cc/kata-containers-cc.spec
  SPECS/kata-containers/kata-containers.signatures.json
  SPECS/kata-containers/kata-containers.spec
  cgmanifest.json
Labels: Packaging, 3.0-dev

#13786 Revert "Upgrade `maven` to 3.8.1 to fix CVE-2021-26291 in `javapackages-bootstrap` [Critical]"
  SPECS/javapackages-bootstrap/CVE-2021-26291.patch
  SPECS/javapackages-bootstrap/javapackages-bootstrap.signatures.json
  SPECS/javapackages-bootstrap/javapackages-bootstrap.spec
Labels: Packaging, fasttrack/2.0

#13803 Upgrade SymCrypt-OpenSSL to 1.8.1
  SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.signatures.json
  SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.spec
  cgmanifest.json
Labels: Packaging, fasttrack/3.0

#13648 dom0 packages: Update to dom0 release v2411.19.1
  SPECS-SIGNED/kernel-mshv-signed/kernel-mshv-signed.spec
  SPECS/cloud-hypervisor-cvm/CVE-2024-12797.patch
  SPECS/cloud-hypervisor-cvm/cloud-hypervisor-cvm.signatures.json
  SPECS/cloud-hypervisor-cvm/cloud-hypervisor-cvm.spec
  SPECS/cloud-hypervisor-cvm/config.toml
  SPECS/cloud-hypervisor-cvm/upgrade-openssl-to-3.3.2-to-address-CVE-2024-6119.patch
  SPECS/kernel-mshv/config
  SPECS/kernel-mshv/fix_python_3.12_build_errors.patch
  SPECS/kernel-mshv/kernel-mshv.signatures.json
  SPECS/kernel-mshv/kernel-mshv.spec
  SPECS/kernel-uvm/config
  SPECS/kernel-uvm/kernel-uvm.signatures.json
  SPECS/kernel-uvm/kernel-uvm.spec
  cgmanifest.json
Labels: Packaging, 3.0-dev

#13808 Prepare May 2025 Update 2
  SPECS/azurelinux-release/azurelinux-release.spec
Labels: Packaging, 3.0-dev

#13705 Extended build failure logging
  toolkit/tools/go.mod
  toolkit/tools/go.sum
  toolkit/tools/internal/pkggraph/graphprinter.go
  toolkit/tools/internal/pkggraph/graphprinter_test.go
  toolkit/tools/internal/pkggraph/gtreebuilder_test.go
  toolkit/tools/internal/pkggraph/pkggraph.go
  toolkit/tools/internal/pkggraph/pkggraph_test.go
  toolkit/tools/scheduler/scheduler.go
  toolkit/tools/scheduler/schedulerutils/depsolver.go
  toolkit/tools/scheduler/schedulerutils/printresults.go
Labels: Tools, 3.0-dev

#10802 Upgrade kyotocabinet to version 1.2.80
  SPECS-EXTENDED/kyotocabinet/kyotocabinet-1.2.78-random-failures.patch
  SPECS-EXTENDED/kyotocabinet/kyotocabinet.signatures.json
  SPECS-EXTENDED/kyotocabinet/kyotocabinet.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#11179 Updated lua-json to version 1.3.4
  SPECS-EXTENDED/lua-json/48.patch
  SPECS-EXTENDED/lua-json/lua-json.signatures.json
  SPECS-EXTENDED/lua-json/lua-json.spec
  SPECS-EXTENDED/lua-json/luajson-lua-5.2.patch
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#13815 [3.0] bmake: move tests to check section
  SPECS/bmake/bmake.spec
  SPECS/bmake/do-not-run-tests-on-install.patch
Labels: Packaging, 3.0-dev

#13810 [2.0] bmake: fix test issue
  SPECS/bmake/bmake.spec
  SPECS/bmake/do-not-run-tests-on-install.patch
Labels: Packaging, main

#13674 kernel-64k: enabling config options required for GB200 and GB200F diags
  SPECS-SIGNED/fwctl-signed/fwctl-signed.spec
  SPECS-SIGNED/iser-signed/iser-signed.spec
  SPECS-SIGNED/isert-signed/isert-signed.spec
  SPECS-SIGNED/kernel-64k-signed/kernel-64k-signed.spec
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS-SIGNED/kernel-uki-signed/kernel-uki-signed.spec
  SPECS-SIGNED/knem-modules-signed/knem-modules-signed.spec
  SPECS-SIGNED/mft_kernel-signed/mft_kernel-signed.spec
  SPECS-SIGNED/mlnx-nfsrdma-signed/mlnx-nfsrdma-signed.spec
  SPECS-SIGNED/mlnx-ofa_kernel-modules-signed/mlnx-ofa_kernel-modules-signed.spec
  SPECS-SIGNED/srp-signed/srp-signed.spec
  SPECS-SIGNED/xpmem-modules-signed/xpmem-modules-signed.spec
  SPECS/fwctl/fwctl.spec
  SPECS/iser/iser.spec
  SPECS/isert/isert.spec
  SPECS/kernel-64k/config_aarch64
  SPECS/kernel-64k/kernel-64k.signatures.json
  SPECS/kernel-64k/kernel-64k.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/kernel-uki.spec
  SPECS/kernel/kernel.spec
  SPECS/knem/knem.spec
  SPECS/mft_kernel/mft_kernel.spec
  SPECS/mlnx-nfsrdma/mlnx-nfsrdma.spec
  SPECS/mlnx-ofa_kernel/mlnx-ofa_kernel.spec
  SPECS/srp/srp.spec
  SPECS/xpmem/xpmem.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, 3.0-dev

#13827 [Medium] Patch azl-compliance for CVE-2025-4574
  SPECS/azl-compliance/CVE-2025-4574.patch
  SPECS/azl-compliance/azl-compliance.spec
Labels: security, Packaging, main

#13818 [Medium] patch rpm-ostree for CVE-2024-2905
  SPECS/rpm-ostree/CVE-2024-2905.patch
  SPECS/rpm-ostree/rpm-ostree.spec
Labels: security, Packaging, 3.0-dev

#13806 [Low] Patch mdadm for CVE-2023-28938
  SPECS/mdadm/CVE-2023-28938.patch
  SPECS/mdadm/mdadm.spec
Labels: security, Packaging, main

#13804 [Medium] Patch iniparser for CVE-2023-33461
  SPECS/iniparser/CVE-2023-33461.patch
  SPECS/iniparser/iniparser.spec
Labels: security, Packaging, 3.0-dev

#13795 [Medium] Patch yasm for CVE-2023-51258 & CVE-2023-37732
  SPECS/yasm/CVE-2023-37732.patch
  SPECS/yasm/CVE-2023-51258.patch
  SPECS/yasm/yasm.spec
Labels: security, Packaging, main

#13792 [Medium] Patch yasm for CVE-2023-51258 and CVE-2023-37732
  SPECS/yasm/CVE-2023-37732.patch
  SPECS/yasm/CVE-2023-51258.patch
  SPECS/yasm/yasm.spec
Labels: security, Packaging, 3.0-dev

#13768 Patch docker-buildx for CVE-2025-0495 [Medium]
  SPECS/docker-buildx/CVE-2025-0495.patch
  SPECS/docker-buildx/docker-buildx.spec
Labels: security, Packaging, 3.0-dev

#13642 [MEDIUM] Patch pytorch for CVE-2025-2953
  SPECS/pytorch/CVE-2025-2953.patch
  SPECS/pytorch/pytorch.spec
Labels: security, Packaging, main

#13529 [MEDIUM] Patch packer for CVE-2025-22872
  SPECS/packer/CVE-2025-22872.patch
  SPECS/packer/packer.spec
Labels: security, Packaging, main

#13783 kernel-64k: Added a new patch to solve EFI slack slots issue
  SPECS-SIGNED/fwctl-signed/fwctl-signed.spec
  SPECS-SIGNED/iser-signed/iser-signed.spec
  SPECS-SIGNED/isert-signed/isert-signed.spec
  SPECS-SIGNED/kernel-64k-signed/kernel-64k-signed.spec
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS-SIGNED/kernel-uki-signed/kernel-uki-signed.spec
  SPECS-SIGNED/knem-modules-signed/knem-modules-signed.spec
  SPECS-SIGNED/mft_kernel-signed/mft_kernel-signed.spec
  SPECS-SIGNED/mlnx-nfsrdma-signed/mlnx-nfsrdma-signed.spec
  SPECS-SIGNED/mlnx-ofa_kernel-modules-signed/mlnx-ofa_kernel-modules-signed.spec
  SPECS-SIGNED/srp-signed/srp-signed.spec
  SPECS-SIGNED/xpmem-modules-signed/xpmem-modules-signed.spec
  SPECS/fwctl/fwctl.spec
  SPECS/iser/iser.spec
  SPECS/isert/isert.spec
  SPECS/kernel-64k/0002-Increase-EFI_MMAP_NR_SLACK_SLOTS-for-GB200.patch
  SPECS/kernel-64k/0002-efi-Added-efi-cmdline-line-option-to-dynamically-adj.patch
  SPECS/kernel-64k/kernel-64k.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/kernel-uki.spec
  SPECS/kernel/kernel.spec
  SPECS/knem/knem.spec
  SPECS/mft_kernel/mft_kernel.spec
  SPECS/mlnx-nfsrdma/mlnx-nfsrdma.spec
  SPECS/mlnx-ofa_kernel/mlnx-ofa_kernel.spec
  SPECS/srp/srp.spec
  SPECS/xpmem/xpmem.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, 3.0-dev

#13831 kernel-lpg-innovate: update to version 6.6.89.2
  SPECS-EXTENDED/kernel-lpg-innovate/kernel-lpg-innovate.normal.config
  SPECS-EXTENDED/kernel-lpg-innovate/kernel-lpg-innovate.secure.config
  SPECS-EXTENDED/kernel-lpg-innovate/kernel-lpg-innovate.signatures.json
  SPECS-EXTENDED/kernel-lpg-innovate/kernel-lpg-innovate.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#13839 Anphel/3 mid may 2025 update b
  SPECS-SIGNED/fwctl-signed/fwctl-signed.spec
  SPECS-SIGNED/iser-signed/iser-signed.spec
  SPECS-SIGNED/isert-signed/isert-signed.spec
  SPECS-SIGNED/kernel-64k-signed/kernel-64k-signed.spec
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS-SIGNED/kernel-uki-signed/kernel-uki-signed.spec
  SPECS-SIGNED/knem-modules-signed/knem-modules-signed.spec
  SPECS-SIGNED/mft_kernel-signed/mft_kernel-signed.spec
  SPECS-SIGNED/mlnx-nfsrdma-signed/mlnx-nfsrdma-signed.spec
  SPECS-SIGNED/mlnx-ofa_kernel-modules-signed/mlnx-ofa_kernel-modules-signed.spec
  SPECS-SIGNED/srp-signed/srp-signed.spec
  SPECS-SIGNED/xpmem-modules-signed/xpmem-modules-signed.spec
  SPECS/azurelinux-release/azurelinux-release.spec
  SPECS/fwctl/fwctl.spec
  SPECS/iser/iser.spec
  SPECS/isert/isert.spec
  SPECS/kernel-64k/0002-Increase-EFI_MMAP_NR_SLACK_SLOTS-for-GB200.patch
  SPECS/kernel-64k/0002-efi-Added-efi-cmdline-line-option-to-dynamically-adj.patch
  SPECS/kernel-64k/config_aarch64
  SPECS/kernel-64k/kernel-64k.signatures.json
  SPECS/kernel-64k/kernel-64k.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/kernel-uki.spec
  SPECS/kernel/kernel.spec
  SPECS/knem/knem.spec
  SPECS/mft_kernel/mft_kernel.spec
  SPECS/mlnx-nfsrdma/mlnx-nfsrdma.spec
  SPECS/mlnx-ofa_kernel/mlnx-ofa_kernel.spec
  SPECS/srp/srp.spec
  SPECS/xpmem/xpmem.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, 3.0

#13817 [2.0] javapackages-bootstrap build reliability
  SPECS/javapackages-bootstrap/javapackages-bootstrap.spec
Labels: Packaging, main

#13596 [Medium] Patch multus for CVE-2025-22872
  SPECS/multus/CVE-2025-22872.patch
  SPECS/multus/multus.spec
Labels: security, Packaging, main

#13849 Fix 5 more ptests (perl-Net-SSLeay perl-Module-Implementation perl-URI rubygem-introspection rubygem-metaclass)
  SPECS/perl-Module-Implementation/perl-Module-Implementation.spec
  SPECS/perl-Net-SSLeay/compatible-openssl.patch
  SPECS/perl-Net-SSLeay/perl-Net-SSLeay.spec
  SPECS/perl-URI/perl-URI.spec
  SPECS/rubygem-introspection/rubygem-introspection.spec
  SPECS/rubygem-metaclass/rubygem-metaclass.spec
Labels: Packaging, 3.0-dev

#13860 cassandra: fix build
  SPECS-EXTENDED/cassandra/cassandra.spec
Labels: Packaging, specs-extended, 3.0-dev

#13879 [MEDIUM] Patch containerd2 for CVE-2025-22872
  SPECS/containerd2/CVE-2025-22872.patch
  SPECS/containerd2/containerd2.spec
Labels: security, Packaging, 3.0-dev

#13832 [MEDIUM] Patch net-tools for CVE-2025-46836
  SPECS/net-tools/CVE-2025-46836.patch
  SPECS/net-tools/net-tools.spec
Labels: security, Packaging, main

#13797 Upgrade: tang version to 15
  SPECS-EXTENDED/tang/tang.signatures.json
  SPECS-EXTENDED/tang/tang.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#13791 Upgrade: jose version to 14
  SPECS-EXTENDED/jose/jose.signatures.json
  SPECS-EXTENDED/jose/jose.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#13771 Upgrade: jimtcl version to 0.83
  SPECS-EXTENDED/jimtcl/jimtcl-fix_doc_paths.patch
  SPECS-EXTENDED/jimtcl/jimtcl-stdio-for-readline.diff
  SPECS-EXTENDED/jimtcl/jimtcl.signatures.json
  SPECS-EXTENDED/jimtcl/jimtcl.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#13897 Fixed reporting of build errors (CP: #13889)
  toolkit/tools/scheduler/scheduler.go
Labels: Tools, 3.0

#13127 Add tardev-snapshotter package to specs-extended
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS-EXTENDED/tardev-snapshotter/regenerate-archives.sh
  SPECS-EXTENDED/tardev-snapshotter/tardev-snapshotter.signatures.json
  SPECS-EXTENDED/tardev-snapshotter/tardev-snapshotter.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#13645 OOT Modules -> Add kernel version and release nb into release nb
  .github/workflows/check-package-cgmanifest.yml
  .github/workflows/overwrite_shell_link.sh
  .github/workflows/validate-cg-manifest.sh
  SPECS-SIGNED/fwctl-signed/fwctl-signed.spec
  SPECS-SIGNED/iser-signed/iser-signed.spec
  SPECS-SIGNED/isert-signed/isert-signed.spec
  SPECS-SIGNED/knem-modules-signed/knem-modules-signed.spec
  SPECS-SIGNED/mft_kernel-signed/mft_kernel-signed.spec
  SPECS-SIGNED/mlnx-nfsrdma-signed/mlnx-nfsrdma-signed.spec
  SPECS-SIGNED/mlnx-ofa_kernel-modules-signed/mlnx-ofa_kernel-modules-signed.spec
  SPECS-SIGNED/srp-signed/srp-signed.spec
  SPECS-SIGNED/xpmem-modules-signed/xpmem-modules-signed.spec
  SPECS/fwctl/fwctl.spec
  SPECS/iser/iser.spec
  SPECS/isert/isert.spec
  SPECS/knem/knem.spec
  SPECS/mft_kernel/mft_kernel.spec
  SPECS/mlnx-nfsrdma/mlnx-nfsrdma.spec
  SPECS/mlnx-ofa_kernel/mlnx-ofa_kernel.spec
  SPECS/srp/srp.spec
  SPECS/xpmem/xpmem.spec
  toolkit/scripts/check_entangled_specs.py
  toolkit/scripts/check_spec_guidelines.py
Labels: Packaging, Tools, 3.0-dev

#13921 address bug in OOT spec that depend on mlnx - bump to right mlnx release nb
  SPECS-SIGNED/fwctl-signed/fwctl-signed.spec
  SPECS-SIGNED/iser-signed/iser-signed.spec
  SPECS-SIGNED/isert-signed/isert-signed.spec
  SPECS-SIGNED/mlnx-nfsrdma-signed/mlnx-nfsrdma-signed.spec
  SPECS-SIGNED/srp-signed/srp-signed.spec
  SPECS-SIGNED/xpmem-modules-signed/xpmem-modules-signed.spec
  SPECS/fwctl/fwctl.spec
  SPECS/iser/iser.spec
  SPECS/isert/isert.spec
  SPECS/mlnx-nfsrdma/mlnx-nfsrdma.spec
  SPECS/mlnx-ofa_kernel/mlnx-ofa_kernel.spec
  SPECS/srp/srp.spec
  SPECS/xpmem/xpmem.spec
Labels: Packaging, 3.0-dev

#13884 [Low] Patch moby-engine for CVE-2024-51744
  SPECS/moby-engine/CVE-2024-51744.patch
  SPECS/moby-engine/moby-engine.spec
Labels: security, Packaging, main

#13885 [Low] Patch moby-engine for CVE-2024-51744
  SPECS/moby-engine/CVE-2024-51744.patch
  SPECS/moby-engine/moby-engine.spec
Labels: security, Packaging, 3.0-dev

#13852 [LOW] Patch nodejs for CVE-2025-47279
  SPECS/nodejs/CVE-2025-47279.patch
  SPECS/nodejs/nodejs18.spec
Labels: security, Packaging, main

#13843 [LOW] Patch nodejs for CVE-2025-47279
  SPECS/nodejs/CVE-2025-47279.patch
  SPECS/nodejs/nodejs.spec
Labels: security, Packaging, 3.0-dev

#13930 Fixed CG manifest check when parsing specs with `%include`.
  .github/workflows/validate-cg-manifest.sh
Labels: 3.0-dev

#13898 Remove psw protected zip file from upstream src (if psw cannot be found)
  SPECS/libzip/libzip.signatures.json
  SPECS/libzip/libzip.spec
  SPECS/linux-firmware/linux-firmware.signatures.json
  SPECS/linux-firmware/linux-firmware.spec
  SPECS/perl/perl-remove-psw-protected-zip.patch
  SPECS/perl/perl.signatures.json
  SPECS/perl/perl.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, 3.0-dev

#13547 Remove containerd spec folder from the 3.0-dev github tree
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS/containerd/CVE-2023-44487.patch
  SPECS/containerd/CVE-2023-45288.patch
  SPECS/containerd/CVE-2023-47108.patch
  SPECS/containerd/CVE-2024-24786.patch
  SPECS/containerd/CVE-2024-28180.patch
  SPECS/containerd/CVE-2024-40635.patch
  SPECS/containerd/CVE-2025-27144.patch
  SPECS/containerd/Makefile.patch
  SPECS/containerd/containerd.service
  SPECS/containerd/containerd.signatures.json
  SPECS/containerd/containerd.spec
  SPECS/containerd/containerd.toml
  SPECS/containerd/fix_tests_for_golang1.21.patch
  cgmanifest.json
Labels: Packaging, 3.0-dev
