Repository microsoft/azurelinux, pull requests merged in 2025-10, with the labels that each got.

#14756 [AUTO-CHERRYPICK] [High] Patch keras for CVE-2025-8747 - branch aaruagrawal/autoPRdummy3.0-dev
  SPECS/keras/CVE-2025-8747.patch
  SPECS/keras/keras.spec
Labels: Packaging, Auto Fast-track Cherry-pick

#11600 Upgraded mythes to version 1.2.5
  SPECS-EXTENDED/mythes/mythes.signatures.json
  SPECS-EXTENDED/mythes/mythes.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#14638 Enable Aquantia AQtion ethernet driver kernel configs
  SPECS-EXTENDED/kernel-ipe/config
  SPECS-EXTENDED/kernel-ipe/kernel-ipe.signatures.json
  SPECS-EXTENDED/kernel-ipe/kernel-ipe.spec
  SPECS-SIGNED/kernel-64k-signed/kernel-64k-signed.spec
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS-SIGNED/kernel-uki-signed/kernel-uki-signed.spec
  SPECS/kernel-64k/kernel-64k.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/kernel-uki.spec
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, specs-extended, 3.0-dev

#14688 Update ImageCustomizer to v1.0.0 and add semantic version and latest tag support for imagecustomizer golden container
  .pipelines/containerSourceData/scripts/PublishContainers.sh
  SPECS/azurelinux-image-tools/azurelinux-image-tools.signatures.json
  SPECS/azurelinux-image-tools/azurelinux-image-tools.spec
  cgmanifest.json
Labels: Packaging, 3.0-dev

#14735 [AutoPR- Security] Patch libtiff for CVE-2025-9900 [HIGH]
  SPECS/libtiff/CVE-2025-9900.patch
  SPECS/libtiff/libtiff.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview, AutoPR-Security

#14660 Enable DMA P2P
  SPECS-EXTENDED/kernel-ipe/config
  SPECS-EXTENDED/kernel-ipe/kernel-ipe.signatures.json
  SPECS-EXTENDED/kernel-ipe/kernel-ipe.spec
  SPECS-SIGNED/kernel-64k-signed/kernel-64k-signed.spec
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS-SIGNED/kernel-uki-signed/kernel-uki-signed.spec
  SPECS/kernel-64k/kernel-64k.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/kernel-uki.spec
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, specs-extended, 3.0-dev

#14712 [2.0][toolkit] Optimized processing time of prebuilt specs
  toolkit/tools/scheduler/schedulerutils/implicitprovides.go
Labels: Tools, fasttrack/2.0, CVEFixReadyForMaintainerReview

#14565 switch to bootstrap toolchain from 3.0 container
  toolkit/scripts/toolchain/container/Dockerfile
Labels: Tools, 3.0-dev

#14691 Patch `python3` for CVE-2025-8194 [High]
  SPECS/python3/CVE-2025-8194.patch
  SPECS/python3/python3.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, fasttrack/2.0, CVEFixReadyForMaintainerReview

#14672 [AutoPR- Security] Patch cups for CVE-2025-58364, CVE-2025-58060 [HIGH]
  SPECS/cups/CVE-2024-35235.patch
  SPECS/cups/CVE-2025-58060.patch
  SPECS/cups/CVE-2025-58364.patch
  SPECS/cups/cups.spec
Labels: security, Packaging, fasttrack/2.0, CVEFixReadyForMaintainerReview, AutoPR-Security, AI Backport

#14736 [AutoPR- Security] Patch libtiff for CVE-2025-9900 [HIGH]
  SPECS/libtiff/CVE-2025-9900.patch
  SPECS/libtiff/libtiff.spec
Labels: security, Packaging, fasttrack/2.0, CVEFixReadyForMaintainerReview, AutoPR-Security

#14783 [Medium] Patch erlang for CVE-2025-48039
  SPECS/erlang/CVE-2025-48039.patch
  SPECS/erlang/erlang.spec
Labels: security, Packaging, main, ready-for-stable-review

#13476 Upgrades perl-File-MimeInfo to version 0.35
  SPECS-EXTENDED/perl-File-MimeInfo/perl-File-MimeInfo.signatures.json
  SPECS-EXTENDED/perl-File-MimeInfo/perl-File-MimeInfo.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#14506 Bug 58672870: Enable stream ssl preread in nginx
  SPECS/nginx/nginx.spec
Labels: Packaging, 3.0-dev

#14828 Upgrade `redis` to 6.2.20 for CVE-2025-49844 [CRITICAL]
  SPECS/redis/CVE-2025-32023.patch
  SPECS/redis/CVE-2025-48367.patch
  SPECS/redis/redis.signatures.json
  SPECS/redis/redis.spec
  cgmanifest.json
Labels: security, Packaging, fasttrack/2.0, CVEFixReadyForMaintainerReview

#14717 [HIGH] Patch golang-1.18.8 for CVE-2025-4674 & CVE-2025-47906[MEDIUM]
  SPECS/golang/CVE-2025-4674-1.18.patch
  SPECS/golang/CVE-2025-47906-1.18.patch
  SPECS/golang/golang-1.18.spec
  SPECS/influx-cli/influx-cli.spec
  SPECS/influxdb/influxdb.spec
  SPECS/vitess/vitess.spec
Labels: security, Packaging, fasttrack/2.0, CVEFixReadyForMaintainerReview
