Repository microsoft/azurelinux, pull requests merged in 2025-09, with the labels that each got.

#13098 Upgrade: python-genshi to version 0.7.9
  SPECS-EXTENDED/python-genshi/python-genshi.signatures.json
  SPECS-EXTENDED/python-genshi/python-genshi.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#11619 Upgrade: python-betamax to version 0.9.0
  SPECS-EXTENDED/python-betamax/python-betamax.signatures.json
  SPECS-EXTENDED/python-betamax/python-betamax.spec
  cgmanifest.json
Labels: documentation, Packaging, Tools, Schema, specs-extended, 3.0-dev

#14578 Upgrade Kata packages
  SPECS/kata-containers/kata-containers.signatures.json
  SPECS/kata-containers/kata-containers.spec
  cgmanifest.json
Labels: Packaging, 3.0-dev

#14593 [3.0] Added 2 CAs to `ca-certificates-base`: 'Microsoft TLS RSA Root G2' and 'Microsoft TLS ECC Root G2'
  SPECS/ca-certificates/ca-certificates.signatures.json
  SPECS/ca-certificates/ca-certificates.spec
  SPECS/ca-certificates/certdata.base.txt
  SPECS/prebuilt-ca-certificates-base/prebuilt-ca-certificates-base.spec
  SPECS/prebuilt-ca-certificates/prebuilt-ca-certificates.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, 3.0-dev

#14592 Update Arm64 64k ISO to produce with 6.12 HWE kernel
  toolkit/imageconfigs/files/imagecustomizer/isoinstaller/README.txt
  toolkit/imageconfigs/files/imagecustomizer/isoinstaller/attended_config_aarch64_64k_hwe.json
  toolkit/imageconfigs/full-64k-hwe-arm64.yaml
  toolkit/imageconfigs/packagelists/isoinstaller-64k-hwe-packages.yaml
Labels: Schema, 3.0-dev

#11565 Upgrade: pkcs11-helper to version 1.30.0
  SPECS-EXTENDED/pkcs11-helper/pkcs11-helper-rfc7512.patch
  SPECS-EXTENDED/pkcs11-helper/pkcs11-helper.signatures.json
  SPECS-EXTENDED/pkcs11-helper/pkcs11-helper.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#11356 Added package rubygem-scanf to SPECS-EXTENDED
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS-EXTENDED/rubygem-scanf/LICENSE.txt
  SPECS-EXTENDED/rubygem-scanf/data.txt
  SPECS-EXTENDED/rubygem-scanf/rubygem-scanf.signatures.json
  SPECS-EXTENDED/rubygem-scanf/rubygem-scanf.spec
  SPECS-EXTENDED/rubygem-scanf/test_scanf.rb
  SPECS-EXTENDED/rubygem-scanf/test_scanfblocks.rb
  SPECS-EXTENDED/rubygem-scanf/test_scanfio.rb
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#11557 Upgrade: perl-XML-Writer to version 0.900
  SPECS-EXTENDED/perl-XML-Writer/perl-XML-Writer.signatures.json
  SPECS-EXTENDED/perl-XML-Writer/perl-XML-Writer.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#14519 Patch qemu for CVE-2024-7409 [HIGH]
  SPECS/qemu/CVE-2024-7409.patch
  SPECS/qemu/qemu.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#10832 Removed: dpkg from Azure Linux
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS-EXTENDED/dpkg/cputable_ppc64le.patch
  SPECS-EXTENDED/dpkg/dpkg.signatures.json
  SPECS-EXTENDED/dpkg/dpkg.spec
  SPECS-EXTENDED/dpkg/ostable_armv7hl.patch
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#14612 Proposed tweaks.
  toolkit/tools/internal/azureblobstorage/azureblobstorage.go
  toolkit/tools/srpmpacker/srpmpacker.go
Labels: Tools

#14223 [MEDIUM] Patch glib for CVE-2024-34397
  SPECS/glib/CVE-2024-34397.patch
  SPECS/glib/glib.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, main

#11688 Upgrade: perl-Crypt-OpenSSL-RSA to version 0.33
  SPECS-EXTENDED/perl-Crypt-OpenSSL-RSA/perl-Crypt-OpenSSL-RSA.signatures.json
  SPECS-EXTENDED/perl-Crypt-OpenSSL-RSA/perl-Crypt-OpenSSL-RSA.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#13297 Upgrade: resource-agents version to 4.16.0
  SPECS-EXTENDED/resource-agents/resource-agents.signatures.json
  SPECS-EXTENDED/resource-agents/resource-agents.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#14239 [MEDIUM] Patch for python-virtualenv CVE-2025-50181
  SPECS/python-virtualenv/CVE-2025-50181v0.patch
  SPECS/python-virtualenv/CVE-2025-50181v1.patch
  SPECS/python-virtualenv/CVE-2025-50181v2.patch
  SPECS/python-virtualenv/CVE-2025-50181v3.patch
  SPECS/python-virtualenv/python-virtualenv.spec
Labels: security, Packaging, main

#14600 [AutoPR- Security] Patch packer for CVE-2025-58058 [MEDIUM]
  SPECS/packer/CVE-2025-58058.patch
  SPECS/packer/packer.spec
Labels: security, Packaging, 3.0-dev, AutoPR-Security

#14666 [AutoPR- Security] Patch libtiff for CVE-2024-13978 [LOW]
  SPECS/libtiff/CVE-2024-13978.patch
  SPECS/libtiff/libtiff.spec
Labels: security, Packaging, main, AutoPR-Security

#13055 Upgrade: libpeas version to 1.36.0
  SPECS-EXTENDED/libpeas/libpeas.signatures.json
  SPECS-EXTENDED/libpeas/libpeas.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#14606 [AutoPR- Security] Patch containerized-data-importer for CVE-2025-58058 [MEDIUM]
  SPECS/containerized-data-importer/CVE-2025-58058.patch
  SPECS/containerized-data-importer/containerized-data-importer.spec
Labels: security, Packaging, 3.0-dev, AutoPR-Security

#14607 [AutoPR- Security] Patch containerized-data-importer for CVE-2025-58058 [MEDIUM]
  SPECS/containerized-data-importer/CVE-2025-58058.patch
  SPECS/containerized-data-importer/containerized-data-importer.spec
Labels: security, Packaging, main, AutoPR-Security

#14603 [AutoPR- Security] Patch terraform for CVE-2025-58058 [MEDIUM]
  SPECS/terraform/CVE-2025-58058.patch
  SPECS/terraform/terraform.spec
Labels: security, Packaging, main, AutoPR-Security

#14601 [AutoPR- Security] Patch packer for CVE-2025-58058 [MEDIUM]
  SPECS/packer/CVE-2025-58058.patch
  SPECS/packer/packer.spec
Labels: security, Packaging, main, AutoPR-Security

#14605 [AutoPR- Security] Patch jx for CVE-2025-58058 [MEDIUM]
  SPECS/jx/CVE-2025-58058.patch
  SPECS/jx/jx.spec
Labels: security, Packaging, main, AutoPR-Security

#14676 kernel-64k, kernel-hwe: Enable ipmi panic string
  SPECS-EXTENDED/kernel-ipe/kernel-ipe.spec
  SPECS-SIGNED/kernel-64k-signed/kernel-64k-signed.spec
  SPECS-SIGNED/kernel-hwe-signed/kernel-hwe-signed.spec
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS-SIGNED/kernel-uki-signed/kernel-uki-signed.spec
  SPECS/kernel-64k/config_aarch64
  SPECS/kernel-64k/kernel-64k.signatures.json
  SPECS/kernel-64k/kernel-64k.spec
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel-hwe-headers/kernel-hwe-headers.spec
  SPECS/kernel-hwe/config_aarch64
  SPECS/kernel-hwe/kernel-hwe.signatures.json
  SPECS/kernel-hwe/kernel-hwe.spec
  SPECS/kernel/kernel-uki.spec
  SPECS/kernel/kernel.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, specs-extended, 3.0-dev

#14651 [AutoPR- Security] Patch coredns for CVE-2025-58063 [HIGH]
  SPECS/coredns/CVE-2025-58063.patch
  SPECS/coredns/coredns.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview, AutoPR-Security

#14669 Fix : patch application of CVE-2025-4802 in `glibc` (re-apply: #14582)
  SPECS-EXTENDED/buildah/buildah.spec
  SPECS-EXTENDED/catatonit/catatonit.spec
  SPECS-EXTENDED/dyninst/dyninst.spec
  SPECS-EXTENDED/podman/podman.spec
  SPECS/busybox/busybox.spec
  SPECS/flannel/flannel.spec
  SPECS/glibc/add_support_record_failure_barrier.patch
  SPECS/glibc/glibc.spec
  SPECS/glibc/test-CVE-2025-4802.patch
  SPECS/kubernetes/kubernetes.spec
  SPECS/kubevirt/kubevirt.spec
  SPECS/libcap/libcap.spec
  SPECS/libguestfs/libguestfs.spec
  SPECS/qemu/qemu.spec
  SPECS/rust/rust-1.75.spec
  SPECS/rust/rust.spec
  SPECS/supermin/supermin.spec
  SPECS/tini/tini.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, specs-extended, fasttrack/3.0, CVEFixReadyForMaintainerReview

#14632 [AutoPR- Security] Patch glib for CVE-2025-7039 [LOW]
  SPECS/glib/CVE-2025-7039.patch
  SPECS/glib/glib.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, 3.0-dev, AutoPR-Security

#14696 Remove `blobfuse2` from Core-SPECS
  SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md
  SPECS/LICENSES-AND-NOTICES/data/licenses.json
  SPECS/blobfuse2/CVE-2023-45288.patch
  SPECS/blobfuse2/CVE-2024-24786.patch
  SPECS/blobfuse2/CVE-2025-22868.patch
  SPECS/blobfuse2/blobfuse2.signatures.json
  SPECS/blobfuse2/blobfuse2.spec
  cgmanifest.json
Labels: Packaging, main

#14697 Fixed `coredns` random rebuilds bug.
  SPECS/coredns/CVE-2025-47950.patch
  SPECS/coredns/coredns.spec
Labels: Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#14407 [AutoPR- Security] Patch binutils for CVE-2025-8225 [MEDIUM]
  SPECS/binutils/CVE-2025-8225.patch
  SPECS/binutils/binutils.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, main, AutoPR-Security

#14406 [AutoPR- Security] Patch binutils for CVE-2025-8225 [MEDIUM]
  SPECS/binutils/CVE-2025-8225.patch
  SPECS/binutils/binutils.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, 3.0-dev, AutoPR-Security

#13083 Upgrade: perl-Test-Script version to 1.29
  SPECS-EXTENDED/perl-Test-Script/perl-Test-Script.signatures.json
  SPECS-EXTENDED/perl-Test-Script/perl-Test-Script.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#14010 Upgrade: python-pyperclip version to 1.8.2
  SPECS-EXTENDED/python-pyperclip/0001-Skip-tests-irrelevant-in-the-context-of-Fedora-packa.patch
  SPECS-EXTENDED/python-pyperclip/python-pyperclip.signatures.json
  SPECS-EXTENDED/python-pyperclip/python-pyperclip.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#14675 [AutoPR- Security] Patch cmake for CVE-2025-10148 [MEDIUM]
  SPECS/cmake/CVE-2025-10148.patch
  SPECS/cmake/cmake.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, 3.0-dev, AutoPR-Security, AI Backport

#14694 [fasttrack 3.0] Upgrade kernels to 6.6.104.2
  SPECS-EXTENDED/kernel-ipe/config
  SPECS-EXTENDED/kernel-ipe/config_aarch64
  SPECS-EXTENDED/kernel-ipe/kernel-ipe.signatures.json
  SPECS-EXTENDED/kernel-ipe/kernel-ipe.spec
  SPECS-SIGNED/kernel-64k-signed/kernel-64k-signed.spec
  SPECS-SIGNED/kernel-signed/kernel-signed.spec
  SPECS-SIGNED/kernel-uki-signed/kernel-uki-signed.spec
  SPECS/hyperv-daemons/hyperv-daemons.signatures.json
  SPECS/hyperv-daemons/hyperv-daemons.spec
  SPECS/kernel-64k/config_aarch64
  SPECS/kernel-64k/kernel-64k.signatures.json
  SPECS/kernel-64k/kernel-64k.spec
  SPECS/kernel-headers/kernel-headers.signatures.json
  SPECS/kernel-headers/kernel-headers.spec
  SPECS/kernel/config
  SPECS/kernel/config_aarch64
  SPECS/kernel/kernel-uki.spec
  SPECS/kernel/kernel.signatures.json
  SPECS/kernel/kernel.spec
  cgmanifest.json
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
  toolkit/scripts/toolchain/container/Dockerfile
  toolkit/scripts/toolchain/container/toolchain-sha256sums
  toolkit/scripts/toolchain/container/toolchain_build_temp_tools.sh
Labels: Packaging, Tools, specs-extended, fasttrack/3.0

#13997 [Medium] Patch systemd for CVE-2025-4598
  SPECS-SIGNED/systemd-boot-signed/systemd-boot-signed.spec
  SPECS/systemd/CVE-2025-4598.patch
  SPECS/systemd/systemd.spec
Labels: security, Packaging, 3.0-dev

#14557 [TEST AUTO-CHERRYPICK] IGNORE 1 [AutoPR- Security] Patch python3 for CVE-2025-8194 [HIGH] - branch aaruagrawal/autoPRdummy3.0-dev
  SPECS/python3/CVE-2025-8194.patch
  SPECS/python3/python3.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, Auto Fast-track Cherry-pick

#14723 [AutoPR- Security] Patch fio for CVE-2025-10823 [MEDIUM]
  SPECS/fio/CVE-2025-10823.patch
  SPECS/fio/fio.signatures.json
  SPECS/fio/fio.spec
  cgmanifest.json
Labels: security, Packaging, 3.0-dev, AutoPR-Security, ready-for-stable-review

#11802 Upgraded mod_security to version 2.9.7
  SPECS-EXTENDED/mod_security/mod_security-2.9.7-send_error_bucket.patch
  SPECS-EXTENDED/mod_security/mod_security.signatures.json
  SPECS-EXTENDED/mod_security/mod_security.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#13119 gl-manpages: Build error fix
  SPECS-EXTENDED/gl-manpages/gl-manpages.spec
Labels: Packaging, specs-extended, 3.0-dev

#14731 Revert glib PR#14223 to unblock release
  SPECS/glib/CVE-2024-34397.patch
  SPECS/glib/glib.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, main

#14745 Revert "[MEDIUM] Patch glib for CVE-2024-34397 (#14223)"
  SPECS/glib/CVE-2024-34397.patch
  SPECS/glib/glib.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, 2.0

#12509 Upgrade: python-aiodns version to 3.2.0
  SPECS-EXTENDED/python-aiodns/python-aiodns.signatures.json
  SPECS-EXTENDED/python-aiodns/python-aiodns.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#14725 [Medium] Patch Fio for CVE-2025-10823
  SPECS/fio/CVE-2025-10823.patch
  SPECS/fio/fio.signatures.json
  SPECS/fio/fio.spec
  cgmanifest.json
Labels: security, Packaging, main, ready-for-stable-review

#14653 [AutoPR- Security] Patch curl for CVE-2025-10148 [MEDIUM]
  SPECS/curl/CVE-2025-10148.patch
  SPECS/curl/curl.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, 3.0-dev, AutoPR-Security, AI Backport, ready-for-stable-review
