Repository microsoft/azurelinux, pull requests merged in 2025-07, with the labels that each got.

#14096 add install-prereqs-and-configure option, update docs
  toolkit/docs/building/prerequisites-mariner.md
  toolkit/docs/building/prerequisites-mariner.sh
  toolkit/docs/building/prerequisites-ubuntu.md
  toolkit/docs/building/prerequisites-ubuntu.sh
  toolkit/scripts/toolkit.mk
  toolkit/scripts/tools.mk
Labels: documentation, Tools, 3.0-dev

#14215 Revert "[Medium] Patch python-pip for CVE-2025-50181"
  SPECS/python-pip/CVE-2025-50181.patch
  SPECS/python-pip/python-pip.spec
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging, 3.0-dev

#13980 detach old eol annotations
  .pipelines/containerSourceData/scripts/PublishContainers.sh
Labels: 3.0-dev

#14100 [HIGH] Patch bind for CVE-2024-11187
  SPECS/bind/CVE-2024-11187.patch
  SPECS/bind/bind.spec
Labels: security, Packaging, fasttrack/2.0, CVEFixReadyForMaintainerReview

#14188 [AutoPR- Security] Patch gdk-pixbuf2 for CVE-2025-6199
  SPECS/gdk-pixbuf2/CVE-2025-6199.patch
  SPECS/gdk-pixbuf2/gdk-pixbuf2.spec
Labels: security, Packaging, fasttrack/2.0, AutoPR-Security, AI Backport

#14217 [2.0] Added a workaround for PR checks from forked repos.
  .pipelines/templates/PackageTestResultsAnalysis.yml
Labels: fasttrack/2.0

#14187 [AutoPR- Security] Patch ceph for CVE-2025-52555
  SPECS/ceph/CVE-2025-52555.patch
  SPECS/ceph/ceph.spec
Labels: security, Packaging, fasttrack/3.0, AutoPR-Security

#14236 [AutoPR- Security] Patch redis for CVE-2025-32023
  SPECS/redis/CVE-2025-32023.patch
  SPECS/redis/redis.spec
Labels: security, Packaging, fasttrack/2.0, AutoPR-Security

#10889 facter : Upgrade to 4.8.0
  SPECS-EXTENDED/facter/facter-4.8.0.gem.asc
  SPECS-EXTENDED/facter/facter.signatures.json
  SPECS-EXTENDED/facter/facter.spec
  SPECS-EXTENDED/facter/puppet-gpg-signing-key-20250406.pub
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#11518 Upgrade: paps version to 0.8.0
  SPECS-EXTENDED/paps/paps-0.6.8-glib282.patch
  SPECS-EXTENDED/paps/paps-c99.patch
  SPECS-EXTENDED/paps/paps-fix-build.patch
  SPECS-EXTENDED/paps/paps-fix-cpi.patch
  SPECS-EXTENDED/paps/paps-fix-src-to-paps.patch
  SPECS-EXTENDED/paps/paps-glib282.patch
  SPECS-EXTENDED/paps/paps.signatures.json
  SPECS-EXTENDED/paps/paps.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#10857 foomatic-db: Upgrade to version 4.0.20250311
  SPECS-EXTENDED/foomatic-db/foomatic-db.signatures.json
  SPECS-EXTENDED/foomatic-db/foomatic-db.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#10544 Upgrade PyGreSQL version to 6.0.1
  SPECS-EXTENDED/PyGreSQL/PyGreSQL.signatures.json
  SPECS-EXTENDED/PyGreSQL/PyGreSQL.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#13296 Upgrade: usbguard version to 1.1.3
  SPECS-EXTENDED/usbguard/usbguard-0.7.6-libqb.patch
  SPECS-EXTENDED/usbguard/usbguard-revert-catch.patch
  SPECS-EXTENDED/usbguard/usbguard.signatures.json
  SPECS-EXTENDED/usbguard/usbguard.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#11241 Upgrade: libproxy version to 0.5.8
  SPECS-EXTENDED/libproxy/libproxy-0.4.17-fix-python-version-check.patch
  SPECS-EXTENDED/libproxy/libproxy.signatures.json
  SPECS-EXTENDED/libproxy/libproxy.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#11061 Upgrade: libsrtp version to 2.6.0
  SPECS-EXTENDED/libsrtp/libsrtp-2.3.0-shared-fix.patch
  SPECS-EXTENDED/libsrtp/libsrtp.signatures.json
  SPECS-EXTENDED/libsrtp/libsrtp.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#14084 [MEDIUM] Patch xorg-x11-server for CVE-2025-49175, CVE-2025-49176, CVE-2025-49178, CVE-2025-49179 & CVE-2025-49180
  SPECS/xorg-x11-server/CVE-2025-49175.patch
  SPECS/xorg-x11-server/CVE-2025-49176.patch
  SPECS/xorg-x11-server/CVE-2025-49178.patch
  SPECS/xorg-x11-server/CVE-2025-49179.patch
  SPECS/xorg-x11-server/CVE-2025-49180.patch
  SPECS/xorg-x11-server/xorg-x11-server.spec
Labels: security, Packaging, main

#14071 [MEDIUM] Patch yasm for CVE-2024-22653
  SPECS/yasm/CVE-2024-22653.patch
  SPECS/yasm/yasm.spec
Labels: security, Packaging, main

#14020 [MEDIUM] Patch libtpms for CVE-2025-49133
  SPECS/libtpms/CVE-2025-49133.patch
  SPECS/libtpms/libtpms.spec
Labels: security, Packaging, 3.0-dev

#14082 [Medium] Patch xorg-x11-server-Xwayland for CVE-2025-49175, CVE-2025-49177, CVE-2025-49178, CVE-2025-49179, CVE-2025-49180
  SPECS/xorg-x11-server-Xwayland/CVE-2025-49175.patch
  SPECS/xorg-x11-server-Xwayland/CVE-2025-49177.patch
  SPECS/xorg-x11-server-Xwayland/CVE-2025-49178.patch
  SPECS/xorg-x11-server-Xwayland/CVE-2025-49179.patch
  SPECS/xorg-x11-server-Xwayland/CVE-2025-49180.patch
  SPECS/xorg-x11-server-Xwayland/xorg-x11-server-Xwayland.spec
Labels: security, Packaging, 3.0-dev

#14261 [High] Patch redis for CVE-2025-48367
  SPECS/redis/CVE-2025-48367.patch
  SPECS/redis/redis.spec
Labels: security, Packaging, fasttrack/2.0, CVEFixReadyForMaintainerReview

#14263 [High] patch helm for CVE-2025-53547
  SPECS/helm/CVE-2025-53547.patch
  SPECS/helm/helm.spec
Labels: Packaging, fasttrack/2.0

#14130 [High] Patch ruby for CVE-2025-6442
  SPECS/ruby/CVE-2025-6442.patch
  SPECS/ruby/ruby.spec
Labels: security, Packaging, Tools, fasttrack/2.0

#14227 Patch `busybox` for CVE-2022-48174 [Critical]
  SPECS/busybox/CVE-2022-48174.patch
  SPECS/busybox/busybox.spec
Labels: security, Packaging, fasttrack/3.0

#14281 [AutoPR- Security] Patch gnutls for CVE-2025-32990, CVE-2025-32989, CVE-2025-32988
  SPECS/gnutls/CVE-2025-32988.patch
  SPECS/gnutls/CVE-2025-32989.patch
  SPECS/gnutls/CVE-2025-32990.patch
  SPECS/gnutls/gnutls.spec
Labels: security, Packaging, fasttrack/3.0, AutoPR-Security

#14285 [High] Upgrade httpd to 2.4.64 to fix CVE-2025-49812, CVE-2025-53020, CVE-2024-47252, CVE-2025-32048, CVE-2025-42516, CVE-2024-43204
  SPECS/httpd/httpd.signatures.json
  SPECS/httpd/httpd.spec
  cgmanifest.json
Labels: security, Packaging, fasttrack/3.0

#14256 [AutoPR- Security] Patch libssh for CVE-2025-5987, CVE-2025-5372, CVE-2025-5351, CVE-2025-5318
  SPECS/libssh/CVE-2025-5318.patch
  SPECS/libssh/CVE-2025-5351.patch
  SPECS/libssh/CVE-2025-5372.patch
  SPECS/libssh/CVE-2025-5987.patch
  SPECS/libssh/libssh.spec
Labels: security, Packaging, fasttrack/2.0, CVEFixReadyForMaintainerReview, AutoPR-Security, AI Backport

#14274 [High] Patch nodejs18 for CVE-2025-23166
  SPECS/nodejs/CVE-2025-23166.patch
  SPECS/nodejs/nodejs18.spec
Labels: security, Packaging, main, fasttrack/2.0

#14280 [High] patch git for CVE-2025-48384, CVE-2025-48385 and CVE-2025-27613
  SPECS/git/CVE-2025-27613.patch
  SPECS/git/CVE-2025-48384.patch
  SPECS/git/CVE-2025-48385.patch
  SPECS/git/git.spec
Labels: security, Packaging, fasttrack/2.0

#14284 [High] Upgrade httpd to 2.4.64 to fix CVE-2025-49812, CVE-2025-53020, CVE-2024-47252, CVE-2025-32048, CVE-2025-42516, CVE-2024-43204
  SPECS/httpd/httpd.signatures.json
  SPECS/httpd/httpd.spec
  cgmanifest.json
Labels: security, Packaging, fasttrack/2.0, CVEFixReadyForMaintainerReview

#14202 [3.0] Port patch to disable flaky tests for bmake
  SPECS/bmake/bmake.spec
  SPECS/bmake/remove-inconsistent-time-tests.patch
Labels: Packaging, 3.0-dev

#14324 [MEDIUM] Patch krb5 for CVE-2025-3576
  SPECS/krb5/CVE-2025-3576.patch
  SPECS/krb5/krb5.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging

#14275 [AutoPR- Security] Patch gdk-pixbuf2 for CVE-2025-7345
  SPECS/gdk-pixbuf2/CVE-2025-7345.patch
  SPECS/gdk-pixbuf2/gdk-pixbuf2.spec
Labels: security, Packaging, fasttrack/3.0, AutoPR-Security

#14330 [AutoPR- Security] Patch sysbench for CVE-2024-25178, CVE-2024-25176 [HIGH]
  SPECS/sysbench/CVE-2024-25176.patch
  SPECS/sysbench/CVE-2024-25178.patch
  SPECS/sysbench/sysbench.spec
Labels: security, Packaging, fasttrack/3.0, AutoPR-Security

#14293 [AutoPR- Security] Patch gnutls for CVE-2025-6395, CVE-2025-32989, CVE-2025-32988
  SPECS/gnutls/CVE-2025-32988.patch
  SPECS/gnutls/CVE-2025-32989.patch
  SPECS/gnutls/CVE-2025-32990.patch
  SPECS/gnutls/CVE-2025-6395.patch
  SPECS/gnutls/gnutls.spec
Labels: security, Packaging, fasttrack/2.0, AutoPR-Security

#14332 [AutoPR- Security] Patch sysbench for CVE-2024-25178, CVE-2024-25176 [HIGH]
  SPECS/sysbench/CVE-2024-25176.patch
  SPECS/sysbench/CVE-2024-25178.patch
  SPECS/sysbench/sysbench.spec
Labels: security, Packaging, fasttrack/2.0, AutoPR-Security

#14323 Copy the installer RPMs
  toolkit/imageconfigs/full-64k-arm64.yaml
  toolkit/imageconfigs/postinstallscripts/imagecustomizer/isoinstaller_postinstalltask.sh
Labels: Schema

#14328 Patch libarchive for CVE-2025-5914, CVE-2025-5915, CVE-2025-5916, CVE-2025-5917, CVE-2025-5918
  SPECS/libarchive/CVE-2025-5914.patch
  SPECS/libarchive/CVE-2025-5915.patch
  SPECS/libarchive/CVE-2025-5916.patch
  SPECS/libarchive/CVE-2025-5917.patch
  SPECS/libarchive/CVE-2025-5918.patch
  SPECS/libarchive/libarchive.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#14327 Patch libarchive for CVE-2025-5914, CVE-2025-5915, CVE-2025-5916, CVE-2025-5917, CVE-2025-5918
  SPECS/libarchive/CVE-2025-5914.patch
  SPECS/libarchive/CVE-2025-5915.patch
  SPECS/libarchive/CVE-2025-5916.patch
  SPECS/libarchive/CVE-2025-5917.patch
  SPECS/libarchive/CVE-2025-5918.patch
  SPECS/libarchive/libarchive.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: Packaging

#14142 [Medium] Patch qtbase for CVE-2025-5455
  SPECS/qtbase/CVE-2025-5455.patch
  SPECS/qtbase/qtbase.spec
Labels: security, Packaging, 3.0-dev

#14342 Fix git ptest with new git config syntax
  SPECS/git/Ptest-fix-git-config-syntax.patch
  SPECS/git/git.spec
Labels: Packaging, ptest, 3.0-dev

#14105 kata-containers: Update to 3.18.0.kata0 release
  SPECS/kata-containers-cc/kata-containers-cc.spec
  SPECS/kata-containers/kata-containers.signatures.json
  SPECS/kata-containers/kata-containers.spec
  cgmanifest.json
Labels: Packaging, 3.0-dev

#14343 [Medium] Upgrade vim version to 9.1.1552 for CVE-2025-53905 and CVE-2025-53906
  SPECS/vim/vim.signatures.json
  SPECS/vim/vim.spec
  cgmanifest.json
Labels: security, Packaging, main

#14314 [Medium] Upgrade vim version to 9.1.1552 for CVE-2025-53905 and CVE-2025-53906
  SPECS/vim/vim.signatures.json
  SPECS/vim/vim.spec
  cgmanifest.json
Labels: security, Packaging, 3.0-dev

#13954 git: fix git-subtree subpackage
  SPECS/git/git.spec
Labels: Packaging, 3.0-dev

#14073 Patch doxygen for CVE-2025-6140 [Medium]
  SPECS/doxygen/CVE-2025-6140.patch
  SPECS/doxygen/doxygen.spec
Labels: security, Packaging, 3.0-dev

#14365 New PR check for disallowed files
  .github/workflows/check-files.yml
  .github/workflows/disallowed-extensions.txt
Labels: 3.0-dev

#14144 Remove support for bluez5-codec-aac from pipewire to avoid license issues
  SPECS-EXTENDED/pipewire/pipewire.spec
Labels: Packaging, Tools, Schema, specs-extended, 3.0-dev

#14382 [2.0] Upgrade nvidia-container-toolkit and libnvidia-container to 1.17.8 to resolve CVE-2025-23266
  SPECS/libnvidia-container/libnvidia-container.signatures.json
  SPECS/libnvidia-container/libnvidia-container.spec
  SPECS/nvidia-container-toolkit/nvidia-container-toolkit.signatures.json
  SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec
  cgmanifest.json
Labels: Packaging, fasttrack/2.0

#14240 [High] Update valkey to fix CVE-2025-32023, CVE-2025-48367
  SPECS/valkey/valkey.signatures.json
  SPECS/valkey/valkey.spec
  cgmanifest.json
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#14351 Patch libxml2 for CVE-2025-49794, CVE-2025-49796[CRITICAL], CVE-2025-6021[MED], CVE-2025-6170[LOW]
  SPECS/libxml2/CVE-2025-49794_CVE-2025-49796.patch
  SPECS/libxml2/CVE-2025-6021.patch
  SPECS/libxml2/CVE-2025-6170.patch
  SPECS/libxml2/libxml2.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#14368 [AutoPR- Security] Patch jq for CVE-2025-48060 [HIGH]
  SPECS/jq/CVE-2025-48060.patch
  SPECS/jq/jq.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview, AutoPR-Security

#14266 Added the `python-junit-xml` package.
  LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md
  LICENSES-AND-NOTICES/SPECS/data/licenses.json
  SPECS/python-junit_xml/python-junit_xml.signatures.json
  SPECS/python-junit_xml/python-junit_xml.spec
  cgmanifest.json
Labels: Packaging, fasttrack/3.0

#14350 Patch libxml2 for CVE-2025-49794, CVE-2025-49796[CRITICAL], CVE-2025-6021[MED], CVE-2025-6170[LOW]
  SPECS/libxml2/CVE-2025-49794_CVE-2025-49796.patch
  SPECS/libxml2/CVE-2025-6021.patch
  SPECS/libxml2/CVE-2025-6170.patch
  SPECS/libxml2/libxml2.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, fasttrack/2.0

#14357 [High] Patch nodejs18 for CVE-2025-7656
  SPECS/nodejs/CVE-2025-7656.patch
  SPECS/nodejs/nodejs18.spec
Labels: security, Packaging, fasttrack/2.0, CVEFixReadyForMaintainerReview

#14379 [AutoPR- Security] Patch jq for CVE-2025-48060 [HIGH]
  SPECS/jq/CVE-2025-48060.patch
  SPECS/jq/jq.spec
Labels: security, Packaging, fasttrack/2.0, AutoPR-Security, AI Backport

#12201 freeradius : update version to 3.2.5
  SPECS-EXTENDED/freeradius/fix-error-for-expansion-of-macro-in-thread.h.patch
  SPECS-EXTENDED/freeradius/freeradius-Use-system-crypto-policy-by-default.patch
  SPECS-EXTENDED/freeradius/freeradius-configure-c99.patch
  SPECS-EXTENDED/freeradius/freeradius-ease-openssl-version-check.patch
  SPECS-EXTENDED/freeradius/freeradius-ldap-infinite-timeout-on-starttls.patch
  SPECS-EXTENDED/freeradius/freeradius-no-buildtime-cert-gen.patch
  SPECS-EXTENDED/freeradius/freeradius.signatures.json
  SPECS-EXTENDED/freeradius/freeradius.spec
  SPECS-EXTENDED/freeradius/radiusd.service
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#14355 Update linuxguard config
  toolkit/imageconfigs/files/linuxguard/cloud.cfg
  toolkit/imageconfigs/files/linuxguard/selinux-ci-uki.semanage
  toolkit/imageconfigs/files/linuxguard/verity-signature/10-mountbootpartition.conf
  toolkit/imageconfigs/files/linuxguard/verity-signature/90mountbootpartition/module-setup.sh
  toolkit/imageconfigs/files/linuxguard/verity-signature/90mountbootpartition/mountbootpartition-generator.sh
  toolkit/imageconfigs/files/linuxguard/verity-signature/90mountbootpartition/mountbootpartition-genrules.sh
  toolkit/imageconfigs/files/linuxguard/verity-signature/90mountbootpartition/mountbootpartition.sh
  toolkit/imageconfigs/linuxguard-amd64.yaml
  toolkit/imageconfigs/scripts/linuxguard/azlinuxagentconfig.sh
  toolkit/imageconfigs/scripts/linuxguard/cleanup-machineid.sh
  toolkit/imageconfigs/scripts/linuxguard/performance-tuning.sh
  toolkit/imageconfigs/scripts/linuxguard/prepare_trusted_cni_plugins.sh
  toolkit/imageconfigs/scripts/linuxguard/selinux-ci-config.sh
  toolkit/imageconfigs/scripts/linuxguard/tmp-no-exec.sh
Labels: Schema, 3.0-dev

#12894 Upgrade SDL2 to version 2.30.9
  SPECS-EXTENDED/SDL2/SDL2-2.0.22-prefer-wayland.patch
  SPECS-EXTENDED/SDL2/SDL2-2.0.9-khrplatform.patch
  SPECS-EXTENDED/SDL2/SDL2-2.30.1-prefer-wayland.patch
  SPECS-EXTENDED/SDL2/SDL2.signatures.json
  SPECS-EXTENDED/SDL2/SDL2.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#14326 [AutoPR- Security] Patch polkit for CVE-2025-7519 [MEDIUM]
  SPECS/polkit/CVE-2025-7519.patch
  SPECS/polkit/polkit.spec
Labels: security, Packaging, main, AutoPR-Security

#14331 [AutoPR- Security] Patch binutils for CVE-2025-7546, CVE-2025-7545 [MEDIUM]
  SPECS/binutils/CVE-2025-7545.patch
  SPECS/binutils/CVE-2025-7546.patch
  SPECS/binutils/binutils.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, 3.0-dev, AutoPR-Security

#14292 [MEDIUM] Upgrade php to 8.1.33 - to fix CVE-2025-1735, CVE-2025-6491, CVE-2025-1220
  SPECS/php/php.signatures.json
  SPECS/php/php.spec
  cgmanifest.json
Labels: security, Packaging, main

#14403 Upgrade httpd to 2.4.65 to fix CVE-2025-54090
  SPECS/httpd/httpd.signatures.json
  SPECS/httpd/httpd.spec
  cgmanifest.json
Labels: security, Packaging, main

#14402 Upgrade httpd to 2.4.65 to fix CVE-2025-54090
  SPECS/httpd/httpd.signatures.json
  SPECS/httpd/httpd.spec
  cgmanifest.json
Labels: security, Packaging, 3.0-dev

#14348 [Medium] Upgrade bind to fix CVE-2025-40777
  SPECS/bind/bind.signatures.json
  SPECS/bind/bind.spec
  SPECS/bind/nongit-fix.patch
  cgmanifest.json
Labels: security, Packaging, 3.0-dev

#13077 Upgrade libappstream-glib version to 0.8.3
  SPECS-EXTENDED/libappstream-glib/libappstream-glib.signatures.json
  SPECS-EXTENDED/libappstream-glib/libappstream-glib.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#13078 fixed build for fonts-rpm-macros
  SPECS-EXTENDED/fonts-rpm-macros/fonts-rpm-macros-drop-yaml.patch
  SPECS-EXTENDED/fonts-rpm-macros/fonts-rpm-macros-epoch-in-req.patch
  SPECS-EXTENDED/fonts-rpm-macros/fonts-rpm-macros.spec
  SPECS-EXTENDED/fonts-rpm-macros/update_for_azl.patch
Labels: Packaging, specs-extended, 3.0-dev
