Repository microsoft/azurelinux, pull requests merged in 2025-08, with the labels that each got.

#14312 rubygem-webrick: Add %check section
  SPECS/rubygem-webrick/CVE-2023-40225-content-length-validation.patch
  SPECS/rubygem-webrick/CVE-2025-6442.patch
  SPECS/rubygem-webrick/rubygem-webrick.spec
Labels: security, Packaging, ptest, 3.0-dev

#14434 radar into 3.0-dev
  .pipelines/prchecks/CveSpecFilePRCheck/AntiPatternDetector.py
  .pipelines/prchecks/CveSpecFilePRCheck/CveSpecFilePRCheck.py
  .pipelines/prchecks/CveSpecFilePRCheck/CveSpecFilePRCheck.yml
  .pipelines/prchecks/CveSpecFilePRCheck/GITHUB_INTEGRATION.md
  .pipelines/prchecks/CveSpecFilePRCheck/GitHubClient.py
  .pipelines/prchecks/CveSpecFilePRCheck/GptModelConfigClass.py
  .pipelines/prchecks/CveSpecFilePRCheck/OpenAIClientClass.py
  .pipelines/prchecks/CveSpecFilePRCheck/PromptTemplatesClass.py
  .pipelines/prchecks/CveSpecFilePRCheck/README.md
  .pipelines/prchecks/CveSpecFilePRCheck/ResultAnalyzer.py
  .pipelines/prchecks/CveSpecFilePRCheck/apply-security-config.sh
  .pipelines/prchecks/CveSpecFilePRCheck/pr-check-diagrams.md
  .pipelines/prchecks/CveSpecFilePRCheck/requirements.txt
  .pipelines/prchecks/CveSpecFilePRCheck/run-pr-check.sh
  .pipelines/prchecks/CveSpecFilePRCheck/security-config-dev.json
  .pipelines/prchecks/CveSpecFilePRCheck/test_antipattern_detector.py
Labels: 3.0-dev

#13868 [MEDIUM] Patch cri-tools for CVE-2025-22872
  SPECS/cri-tools/CVE-2025-22872.patch
  SPECS/cri-tools/cri-tools.spec
Labels: security, Packaging, 3.0-dev

#14435 Remove unused files and cleanup
  toolkit/imageconfigs/files/linuxguard/99-dhcp-eth0.network
  toolkit/imageconfigs/files/linuxguard/no-password-prompt-on-sudo
  toolkit/imageconfigs/files/linuxguard/selinux-ci-uki.semanage
  toolkit/imageconfigs/files/linuxguard/sshd-keygen.service
  toolkit/imageconfigs/linuxguard-amd64.yaml
  toolkit/imageconfigs/scripts/linuxguard/azlinuxagentconfig.sh
  toolkit/imageconfigs/scripts/linuxguard/duid-type-to-link-layer.sh
  toolkit/imageconfigs/scripts/linuxguard/selinux-ci-config.py
Labels: Schema, 3.0-dev

#14442 msft-golang: upgrade version 1.24.1 -> 1.24.5
  SPECS/msft-golang/CVE-2025-22871.patch
  SPECS/msft-golang/CVE-2025-22874.patch
  SPECS/msft-golang/CVE-2025-4673.patch
  SPECS/msft-golang/msft-golang.signatures.json
  SPECS/msft-golang/msft-golang.spec
  cgmanifest.json
Labels: Packaging, main

#13978 [MEDIUM] Patch glib for CVE-2025-4373
  SPECS/glib/CVE-2025-4373.patch
  SPECS/glib/glib.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, main

#14297 [MEDIUM] Minor version of php upgraded to 8.3.23 - to fix CVE-2025-1735, CVE-2025-6491, CVE-2025-1220
  SPECS/php/php-8.3.20-embed.patch
  SPECS/php/php.signatures.json
  SPECS/php/php.spec
  cgmanifest.json
Labels: security, Packaging, 3.0-dev

#14335 [AutoPR- Security] Patch binutils for CVE-2025-7545, CVE-2025-7546 [MEDIUM]
  SPECS/binutils/CVE-2025-7545.patch
  SPECS/binutils/CVE-2025-7546.patch
  SPECS/binutils/binutils.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, main, AutoPR-Security, AI Backport

#14268 Replaced PyPi's `junit-xml` with AZL's `python3-junit-xml`
  .pipelines/templates/PackageBuild.yml
  .pipelines/templates/PackageBuildPRCheck.yml
  .pipelines/templates/PackageTestResultsAnalysis.yml
Labels: fasttrack/3.0, CVEFixReadyForMaintainerReview

#14433 [AutoPR- Security] Patch iperf3 for CVE-2025-54350, CVE-2025-54349 [MEDIUM]
  SPECS/iperf3/CVE-2025-54349.patch
  SPECS/iperf3/CVE-2025-54350.patch
  SPECS/iperf3/iperf3.spec
Labels: security, Packaging, main, AutoPR-Security

#14411 [AutoPR- Security] Patch iputils for CVE-2025-48964 [MEDIUM]
  SPECS/iputils/CVE-2025-48964.patch
  SPECS/iputils/iputils.spec
Labels: security, Packaging, main, AutoPR-Security

#14419 [AutoPR- Security] Patch ceph for CVE-2024-48916 [HIGH]
  SPECS/ceph/CVE-2024-48916.patch
  SPECS/ceph/ceph.spec
Labels: security, Packaging, fasttrack/2.0, CVEFixReadyForMaintainerReview, AutoPR-Security

#14420 [AutoPR- Security] Patch ceph for CVE-2024-48916 [HIGH]
  SPECS/ceph/CVE-2024-48916.patch
  SPECS/ceph/ceph.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview, AutoPR-Security

#14412 [AutoPR- Security] Patch libsoup for CVE-2025-4948 [HIGH]
  SPECS/libsoup/CVE-2025-4948.patch
  SPECS/libsoup/libsoup.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview, AutoPR-Security

#14441 Additional cleanup for the OSGuard image definition
  toolkit/imageconfigs/files/common/99-dhcp-eth0.network
  toolkit/imageconfigs/files/osguard/repart.d/14-root-a.conf
  toolkit/imageconfigs/files/osguard/repart.d/18-root-b.conf
  toolkit/imageconfigs/linuxguard-amd64.yaml
  toolkit/imageconfigs/osguard-amd64.yaml
  toolkit/imageconfigs/scripts/common/move-iptables-scripts-to-usr.sh
  toolkit/imageconfigs/scripts/common/remove-getty-import-credential.sh
  toolkit/imageconfigs/scripts/common/tmp-no-exec.sh
  toolkit/scripts/generate-repartd.sh
Labels: Tools, Schema, 3.0-dev

#14468 Export osguard root hash for signing
  toolkit/imageconfigs/osguard-amd64.yaml
Labels: Schema, 3.0-dev

#14316 [MEDIUM] Patch apache-commons-lang3 for CVE-2025-48924
  SPECS/apache-commons-lang3/CVE-2025-48924.patch
  SPECS/apache-commons-lang3/apache-commons-lang3.spec
Labels: security, Packaging, main

#14296 [Medium] Patch ruby for CVE-2025-24294
  SPECS/ruby/CVE-2025-24294.patch
  SPECS/ruby/ruby.spec
Labels: security, Packaging, main

#14115 [Medium] Patch python-urllib3 for CVE-2025-50181
  SPECS/python-urllib3/CVE-2025-50181.patch
  SPECS/python-urllib3/python-urllib3.spec
Labels: security, Packaging, main

#14369 [AutoPR- Security] Patch rubygem-thor for CVE-2025-54314 [LOW]
  SPECS/rubygem-thor/CVE-2025-54314.patch
  SPECS/rubygem-thor/rubygem-thor.spec
Labels: security, Packaging, main, AutoPR-Security

#14446 [AutoPR- Security] Patch fluent-bit for CVE-2025-54126 [MEDIUM]
  SPECS/fluent-bit/CVE-2025-54126.patch
  SPECS/fluent-bit/fluent-bit.spec
Labels: security, Packaging, main, AutoPR-Security

#14381 Patch `sqlite` for CVE-2025-6965 [High]
  SPECS/sqlite/CVE-2022-46908.patch
  SPECS/sqlite/CVE-2025-6965.patch
  SPECS/sqlite/sqlite.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview

#14470 osguard: fix usr-a/b repart.d types to match image
  toolkit/imageconfigs/files/osguard/repart.d/12-usr-a.conf
  toolkit/imageconfigs/files/osguard/repart.d/16-usr-b.conf
  toolkit/scripts/generate-repartd.sh
Labels: Tools, Schema, 3.0-dev

#14354 [Medium] patch rust for CVE-2025-53605
  SPECS-EXTENDED/389-ds-base/389-ds-base.spec
  SPECS-EXTENDED/ripgrep/ripgrep.spec
  SPECS-EXTENDED/rust-cbindgen/rust-cbindgen.spec
  SPECS-EXTENDED/tardev-snapshotter/tardev-snapshotter.spec
  SPECS/clamav/clamav.spec
  SPECS/cloud-hypervisor-cvm/cloud-hypervisor-cvm.spec
  SPECS/flux/flux.spec
  SPECS/influxdb/influxdb.spec
  SPECS/kata-containers-cc/kata-containers-cc.spec
  SPECS/kata-containers/kata-containers.spec
  SPECS/librsvg2/librsvg2.spec
  SPECS/mesa/mesa.spec
  SPECS/netavark/netavark.spec
  SPECS/rpm-ostree/rpm-ostree.spec
  SPECS/rust/CVE-2025-53605.patch
  SPECS/rust/CVE-2025-53605_1.75.patch
  SPECS/rust/rust-1.75.spec
  SPECS/rust/rust.spec
  SPECS/virtiofsd/virtiofsd.spec
Labels: security, Packaging, specs-extended, 3.0-dev

#13021 Upgrade: perl-Locale-Maketext-Gettext version to 1.32
  SPECS-EXTENDED/perl-Locale-Maketext-Gettext/perl-Locale-Maketext-Gettext.signatures.json
  SPECS-EXTENDED/perl-Locale-Maketext-Gettext/perl-Locale-Maketext-Gettext.spec
  cgmanifest.json
Labels: Packaging, specs-extended, 3.0-dev

#14443 [AutoPR- Security] Patch python3 for CVE-2025-8194 [HIGH]
  SPECS/python3/CVE-2025-8194.patch
  SPECS/python3/python3.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview, AutoPR-Security

#14429 Patch sqlite for CVE-2025-6965[HIGH], CVE-2025-7458[MEDIUM]
  SPECS/sqlite/CVE-2025-6965.patch
  SPECS/sqlite/CVE-2025-7458.patch
  SPECS/sqlite/sqlite.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, fasttrack/2.0, CVEFixReadyForMaintainerReview

#14487 [AutoPR- Security] Patch icu for CVE-2025-5222 [HIGH]
  SPECS/icu/CVE-2025-5222.patch
  SPECS/icu/icu.spec
Labels: security, Packaging, fasttrack/2.0, CVEFixReadyForMaintainerReview, AutoPR-Security

#14504 refactor: create OS Guard yaml generators
  toolkit/imageconfigs/osguard-amd64.yaml
  toolkit/imageconfigs/templates/osguard-base.yaml
  toolkit/imageconfigs/templates/osguard-no-ci-delta.yaml
  toolkit/scripts/generate-osguard-imageconfigs.sh
  toolkit/scripts/merge_yaml.py
  toolkit/scripts/tests/test_merge_yaml.py
Labels: Tools, Schema, 3.0-dev

#13588 Fix post and postun sections in sdbus-cpp.spec
  SPECS/sdbus-cpp/sdbus-cpp.spec
Labels: Packaging, 3.0-dev

#14477 [3.0] Change default AZ creds to AZ CLI creds.
  toolkit/tools/internal/azureblobstorage/azureblobstorage.go
  toolkit/tools/internal/ccachemanager/ccachemanager.go
Labels: Tools, 3.0-dev

#14515 ci: introduce osguard imageconfig verifier
  .github/workflows/verify-osguard-imageconfigs.yml
  toolkit/scripts/generate-osguard-imageconfigs.sh
Labels: Tools, 3.0-dev

#14514 refactor: clean up osguard base definition
  toolkit/imageconfigs/files/osguard/selinux-ci-uki.semanage
  toolkit/imageconfigs/osguard-amd64.yaml
  toolkit/imageconfigs/templates/osguard-base.yaml
Labels: Schema, 3.0-dev

#14486 [AutoPR- Security] Patch icu for CVE-2025-5222 [HIGH]
  SPECS/icu/CVE-2025-5222.patch
  SPECS/icu/icu.spec
Labels: security, Packaging, fasttrack/3.0, CVEFixReadyForMaintainerReview, AutoPR-Security

#14436 Patch luajit for CVE-2024-25177[HIGH]
  SPECS/luajit/CVE-2024-25177.patch
  SPECS/luajit/luajit.signatures.json
  SPECS/luajit/luajit.spec
  cgmanifest.json
Labels: security, Packaging, fasttrack/2.0, CVEFixReadyForMaintainerReview

#14546 OS Guard: Remove unnecessary SELinux context mapping and enable SELinux and IPE lockout module
  toolkit/imageconfigs/files/linuxguard/selinux-ci-uki.semanage
  toolkit/imageconfigs/files/osguard/selinux-ci-uki.semanage
  toolkit/imageconfigs/scripts/common/selinux-ci-config.py
Labels: Schema, 3.0-dev

#14544 Bug 58271905: Enable pdf support in graphviz
  SPECS/graphviz/graphviz.spec
Labels: Packaging, 3.0-dev

#14458 Fix "Conda init bash" issue.
  SPECS/conda/conda.spec
Labels: Packaging, 3.0-dev

#14505 osguard-ci: Add Code Integrity variant of OS Guard
  toolkit/imageconfigs/files/osguard-ci/config.toml
  toolkit/imageconfigs/osguard-ci-amd64.yaml
  toolkit/imageconfigs/templates/osguard-ci-delta.yaml
  toolkit/scripts/generate-osguard-imageconfigs.sh
Labels: Tools, Schema, 3.0-dev

#13974 [MEDIUM] Patch glib for CVE-2025-4373 and CVE-2025-6052
  SPECS/glib/CVE-2025-4373.patch
  SPECS/glib/CVE-2025-6052.patch
  SPECS/glib/glib.spec
  toolkit/resources/manifests/package/pkggen_core_aarch64.txt
  toolkit/resources/manifests/package/pkggen_core_x86_64.txt
  toolkit/resources/manifests/package/toolchain_aarch64.txt
  toolkit/resources/manifests/package/toolchain_x86_64.txt
Labels: security, Packaging, 3.0-dev

#14472 [AutoPR- Security] Patch edk2 for CVE-2025-3770 [MEDIUM]
  SPECS-SIGNED/edk2-hvloader-signed/edk2-hvloader-signed.spec
  SPECS/edk2/CVE-2025-3770.patch
  SPECS/edk2/edk2.spec
Labels: security, Packaging, 3.0-dev, AutoPR-Security

#14498 [AutoPR- Security] Patch libsoup for CVE-2025-4969 [MEDIUM]
  SPECS/libsoup/CVE-2025-4969.patch
  SPECS/libsoup/libsoup.spec
Labels: security, Packaging, main, AutoPR-Security

#14556 [AutoPR- Security] Patch libtiff for CVE-2025-9165, CVE-2025-8851 [MEDIUM]
  SPECS/libtiff/CVE-2025-8851.patch
  SPECS/libtiff/CVE-2025-9165.patch
  SPECS/libtiff/libtiff.spec
Labels: security, Packaging, 3.0-dev, AutoPR-Security

#14555 [AutoPR- Security] Patch libtiff for CVE-2025-9165, CVE-2025-8851 [MEDIUM]
  SPECS/libtiff/CVE-2025-8851.patch
  SPECS/libtiff/CVE-2025-9165.patch
  SPECS/libtiff/libtiff.spec
Labels: security, Packaging, main, AutoPR-Security

#14499 [AutoPR- Security] Patch jasper for CVE-2025-8837, CVE-2025-8836 [MEDIUM]
  SPECS/jasper/CVE-2025-8836.patch
  SPECS/jasper/CVE-2025-8837.patch
  SPECS/jasper/jasper.spec
Labels: security, Packaging, main, AutoPR-Security

#14445 [AutoPR- Security] Patch fluent-bit for CVE-2025-54126 [MEDIUM]
  SPECS/fluent-bit/CVE-2025-54126.patch
  SPECS/fluent-bit/fluent-bit.spec
Labels: security, Packaging, 3.0-dev, AutoPR-Security

#14405 [AutoPR- Security] Patch nvidia-container-toolkit for CVE-2025-22872 [MEDIUM]
  SPECS/nvidia-container-toolkit/CVE-2025-22872.patch
  SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec
Labels: security, Packaging, main, AutoPR-Security

#14404 [AutoPR- Security] Patch nvidia-container-toolkit for CVE-2025-22872 [MEDIUM]
  SPECS/nvidia-container-toolkit/CVE-2025-22872.patch
  SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec
Labels: security, Packaging, 3.0-dev, AutoPR-Security

#14574 [AutoPR- Security] Patch aide for CVE-2025-54409, CVE-2025-54389 [MEDIUM]
  SPECS/aide/CVE-2025-54389.patch
  SPECS/aide/CVE-2025-54409.patch
  SPECS/aide/aide.spec
Labels: security, Packaging, 3.0-dev, AutoPR-Security

#14262 [Medium] Patch kubevirt for CVE-2024-33394
  SPECS/kubevirt/CVE-2024-33394.patch
  SPECS/kubevirt/kubevirt.spec
Labels: security, Packaging, 3.0-dev

#14540 systemd-boot-signed: add aarch64 package
  SPECS-SIGNED/systemd-boot-signed/systemd-boot-signed.spec
  SPECS/systemd/systemd.spec
Labels: Packaging, Tools, Schema, 3.0-dev

#14580 osguard: add "which" package to OS Guard base images
  toolkit/imageconfigs/osguard-amd64.yaml
  toolkit/imageconfigs/osguard-ci-amd64.yaml
  toolkit/imageconfigs/templates/osguard-base.yaml
Labels: Schema, 3.0-dev
